### ISSUE TITLE
Use globals in email template

### ISSUE THREAD

**Issue by maximilian-schwarz** [verbb/formie#10]
### Description
It would be nice if we can use globals in the email templates.
Currently if you use global fields in the email templates you got the error: undefined variable.

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.4.29

**Comment by engram-design** [comment]
Great idea, I'd also want to add these to the variable select fields as well. At least, for fields that are considered "plain text". But then, that also introduces the issue of providing _all_ globals in the variable select dropdown, which isn't ideal. I'm sure there are some global fields that you wouldn't want clients to use. We'd probably need to introduce some sort of variable-management options for this.

**Comment by engram-design** [comment]
I should point out that if you're referring to the actual Twig template used for emails, including globals should be fine. However, they won't work in the HTML content editor when editing a notification.

To use globals in the Twig templates, you need to fetch the global set first:
```
{% set resources = craft.globals.setByHandle('resources') %}
<p>{{ resources.myVariable }}</p>
```

**Comment by maximilian-schwarz** [comment]
Ah cool. Yeah it's working fine. I have used the syntax from craft cms only "resources.myVariable".

**Comment by engram-design** [comment]
Closing for now, we'll pick up add global variables in the email "HTML Content" at a far later stage.
