### ISSUE TITLE
Integration error with Microsoft Dynamic

### ISSUE THREAD

**Issue by iamtompickering** [verbb/formie#1003]
### Describe the bug

I am trying to set up an integration with Microsoft Dynamics and following your instructions and keep hitting the following error message (screenshot below)

![CleanShot 2022-07-14 at 12 06 43](https://user-images.githubusercontent.com/6592882/181000275-6d1897b5-8b45-4195-bd1b-496003a70fb2.png)

Any idea why this would be happening and how to get around it? I tried using both local and live URLs, http and https.

### Steps to reproduce

1. Follow the Microsoft Dynamics integration set up guide 

### Form settings

- Multi-page form: No
- Submission Method: Page Reload

### Craft CMS version

4.0.5.1

### Plugin version

2.0.0-beta.14

### Multi-site?

No

**Comment by engram-design** [comment]
Is this when connecting the integration? Can you show me your redirect URI? Sounds like it might contain a query string, which you'll have to change with `pathInfo`. Some providers are strict about this, and don't like it.

https://craftcms.com/knowledge-base/enabling-path-info

**Comment by iamtompickering** [comment]
@engram-design yeah when connecting the integration. 

The redirect URI is showing as https://area.local/index.php?p=actions/formie/integrations/callback on local

So would you suggest changing it to https://area.local/index.php/actions/formie/integrations/callback ?

**Comment by engram-design** [comment]
Yeah, so you'll likely need to change it using the [`usePathInfo`](https://craftcms.com/docs/3.x/config/config-settings.html#usepathinfo) config setting. Some providers just don't like query strings in the redirect URI, so not much we can do about it otherwise!

**Comment by jamesmacwhite** [comment]
I've also hit this as well. It isn't a unique problem to Formie, I've seen the same happen with Twitter as well, some providers just won't let you use any query string in redirect URI values.

**Comment by iamtompickering** [comment]
@jamesmacwhite have you managed to figure out any workaround for this error?

**Comment by jamesmacwhite** [comment]
I had to disable path info for a redirect URI to be generated without query parameters. Twitter has a similar rule having no query strings.

https://github.com/dukt/twitter/issues/18

**Comment by jamesmacwhite** [comment]
You could try leaving it just https://your domain.com/index.php without any query paramters

**Comment by engram-design** [comment]
Another options is to setup a route yourself to forward onto Formie action endpoint. In your `config/routes.php` you could have:

```
<?php

return [
    'my-callback-path' => 'formie/integrations/callback',
];
```

**Comment by jamesmacwhite** [comment]
@engram-design I would personally go with the route approach I think, changing the PathInfo setting has implications across all of Craft CMS, if it's needed just for Formie, a custom route seems like the safest approach without potential negative impact on other parts of the CMS that might not expect it.

**Comment by engram-design** [comment]
@jamesmacwhite FYI, this should be improved in https://github.com/verbb/formie/issues/1092 thanks to custom site routes within Formie itself. We're now no longer constrained by the `usePathInfo` setting.

**Comment by jamesmacwhite** [comment]
@engram-design Sorry, I never replied to this, that looks like a good solution, for Formie 1.x I'll set a route myself for now to workaround the issue.

**Comment by jamesmacwhite** [comment]
It looks like you can't really fix it in v1, even by adding your own site route. The Redirect URI displayed on the settings page is what is sent in the request data. If you don't enable usePathInfo, you'll have query parameters, which you can't use in Azure so whatever redirect URI you set, can't match given no query parameters allowed.

![image](https://user-images.githubusercontent.com/8067792/197028181-e6d03e56-29be-4d0f-86e0-12936f34d8d2.png)

I think usePathInfo is the only way out on v1. Unless the v2 change is backported but it might break compatibility.

**Comment by engram-design** [comment]
@jamesmacwhite I've just back-ported the change already made in Formie 2 that creates a site route to prevent this sort of issue. Both URLs can continue to be used, although in your case the former won't work for you.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.14",
  "...": "..."
}
```

Then run `composer update`. Let me know how you go.

**Comment by jamesmacwhite** [comment]
@engram-design Awesome. Thanks for this!
