### ISSUE TITLE
Static translations not being picked up correctly

### ISSUE THREAD

**Issue by gogogorski** [verbb/formie#1008]
### Question

Hey there 👋

I'm having trouble with setting up static translations for a multi-language site. My project is using German (primary) and English (secondary), they're setup as separate sites following the Craft docs. The translation works fine in all other parts of the website. 

I've created a quite basic contact form using German field labels (see screenshot).

<img width="1042" alt="Bildschirmfoto 2022-07-27 um 16 55 25" src="https://user-images.githubusercontent.com/51097187/181279680-cd2a61e7-b563-4d44-bec4-7c803414b2f2.png">

I put the translation for the strings in the translations folder(s), following the [static translation guidelines](https://craftcms.com/docs/4.x/sites.html#static-message-translations). I've also followed the thread on [translation support (#60)](https://github.com/verbb/formie/issues/60).

In /translations/de/formie.php:
return [
    'Vorname' => 'Vorname',
'Nachname' => 'Nachname',
    'E-Mail' => 'E-Mail',
    'Telefonnummer' => 'Telefonnummer',
    'Bereich' => 'Bereich',
    'Kontaktaufnahme' => 'Kontaktaufnahme',
    'Unternehmen' => 'Unternehmen',
];

In /translations/en/formie.php:
return [
	'Vorname' => 'Given name',
    'Nachname' => 'Last name',
    'E-Mail' => 'E-Mail',
    'Telefonnummer' => 'Phone number',
    'Bereich' => 'Area',
    'Kontaktaufnahme' => 'Contact',
    'Unternehmen' => 'Company',
];

But the translations are not being picked up correctly.

With this setup all strings are **overriden with the English strings**. The German site also gets the English strings.

**Comment by engram-design** [comment]
Can you let me know what version you're on? We've consolidated everything into the `formie` translation category in Formie 2, but for Formie 1, they're split over `site` and `formie` (hence, you'll need to use two different files).

I should mention that static translations are more for the front-end, as opposed to the form builder.

**Comment by gogogorski** [comment]
I'm using Craft v4.1.4.1 and Formie v2.0.4.

And yes, I'm trying to translate the strings in the front-end of the form.

**Comment by engram-design** [comment]
Hmmm, nothing I can see that's an issue on my end, translating the label/name of fields, instructions and more.

Here's a before:

![image](https://user-images.githubusercontent.com/1221575/181459090-3c1b29a1-5f30-43f8-80f7-a105bc552d25.png)

In /translations/en/formie.php:
```php
<?php

return [
    'First Name' => 'First Name Override',
    'Last Name' => 'Last Name Override',
    'eg. Peter' => 'eg. John',
    'eg. Sherman' => 'eg. Citizen',
    'Please enter your full name.' => 'Enter your name.',
    'Email Address' => 'Email',
    'Please enter your email so we can get it touch.' => 'Enter your email.',
    'eg. psherman@wallaby.com' => 'eg. jc@gmail.com',
];
```

![image](https://user-images.githubusercontent.com/1221575/181459679-5f3c63a1-9c4c-41ec-85a9-c86e4103e276.png)

**Comment by gogogorski** [comment]
Ah, okay, I figured it out: the problem was that I was putting identical strings in the German translation file.

`'Vorname' => 'Vorname` does not work, but `'Vorname' => 'Vorname Override'` works. 

Thanks for taking the time to check!
