### ISSUE TITLE
Retrieve upload file in EVENT_BEFORE_SUBMISSION

### ISSUE THREAD

**Issue by roland-d** [verbb/formie#1009]
### Question

Once a user submits a form I have 2 hidden fields that needs to be filled with the base64 encoded value of their corresponding file upload field.

The file upload works fine, I can see the files being uploaded but when I get the submission in the `Submissions::EVENT_BEFORE_SUBMISSION` trigger I can't find how to access the uploaded file information. 

Can you tell me how I can get the filepath/file content of the uploaded file from the `$submission` in the `Submissions::EVENT_BEFORE_SUBMISSION`?

What I have found is that I can do `$submission->getFieldValue('my_handle');` which gets me an `AssetQuery` object but there I do not see the file info.

Thank you for your help.

### Additional context

You may want to know why I need this, that is because we are sending the file to an external service called FileMaker and they need the actual file, so we transfer it via base64. This works in Joomla + RSforms at the moment but we are switching to Craft + Formie.

**Comment by engram-design** [comment]
So the file uploads should already have been converted to assets at that point. As you've found, calling `$submission->getFieldValue('my_handle');` will provide you an `AssetQuery` which is correct - just like if you called `entry.myAssetField` in Twig.

You'll want to use:

```php
$value = $submission->getFieldValue('my_handle');
$assets = $value->all();

foreach ($assets as $asset) {
    Craft::dd($asset->getDataUrl());
}
```

You could use [$asset->getDataUrl()](https://github.com/craftcms/cms/blob/3db7fb231049166f102aa75a5a23b52a8762b7d1/src/elements/Asset.php#L1886) to get what you need for each upload.

**Comment by roland-d** [comment]
@engram-design Thank you for your great support, this works as explained.
