### ISSUE TITLE
PHP Notice – yii\base\ErrorException Undefined offset: 0 when creating or editing form

### ISSUE THREAD

**Issue by hassanmah** [verbb/formie#101]
**Description**
Whenever I go to create a form I get the following error: `PHP Notice – yii\base\ErrorException Undefined offset: 0`

![image](https://user-images.githubusercontent.com/3025707/93349784-d5107b80-f82f-11ea-84db-ade946e2be6f.png)

But the form is created if I click on back, then if I try editing the form I get the same error.

**Steps to reproduce**
1. Click on new form
2. Fill in the name
3. Click on Next
4. Error occurs
5. Click on Back on the browser
6. The form is listed
7. Click on form to edit
8. Error occurs

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.12
- Craft version: 3.5.10.1
- Multi-site: No

**Comment by engram-design** [comment]
It looks like the default form statuses didn't get created when you installed the plugin. Were there any errors when you installed?

You'll need to head to Formie > Settings > Statuses and create at least one status. This is the default status that is supposed to get created - https://d.pr/i/7BeB46

Our of interest, do you have any Stencils? Once should also automatically be created upon install, like statuses

**Comment by engram-design** [comment]
Should be fixed in [1.2.13](https://github.com/verbb/formie/releases/tag/1.2.13) as well, where I've added improvements to this handling of an error - should fix it right up.

**Comment by hassanmah** [comment]
@engram-design Thanks for fixing this, all works now.

I didn't get any errors on install. Also, no stencils were created
