### ISSUE TITLE
Formie 1.6.5 conflicts with roave/security-advisories (dompdf)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1020]
### Describe the bug

I installed Formie through composer:

```
 composer require verbb/formie "^1.0" && php craft plugin/install formie
```

I needed to lock it to 1.x due to being Craft CMS 3 and without it will try and install the Craft CMS 4 version. Formie installed fine, however I noticed the version was 1.4.x not the latest 1.x version, I then updated composer.json to match the latest versions and then got this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires verbb/formie ^1.6.5 -> satisfiable by verbb/formie[1.6.5].
    - verbb/formie 1.6.5 requires dompdf/dompdf ^1.0.2 -> satisfiable by dompdf/dompdf[v1.0.2, ..., v1.2.2].
    - roave/security-advisories dev-latest conflicts with dompdf/dompdf v1.2.2.
    - roave/security-advisories dev-latest conflicts with dompdf/dompdf v1.1.1.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

The issue is because of the dompdf dependency. I can see Formie has this in it's composer.json, but perhaps is conflicting due to the fact it is asking for a vulnerable version?

### Steps to reproduce

N/A

### Form settings

N/A

### Craft CMS version

3.7.50

### Plugin version

1.6.5

### Multi-site?

No

**Comment by engram-design** [comment]
Yeah, this change has been made for Formie 2, but not for Formie 1

**Comment by jamesmacwhite** [comment]
Sorry, I just saw: https://github.com/verbb/formie/issues/972.

Is there any chance is can be backported? Because our main composer.json uses roave, we cannot install beyond 1.4.x.

**Comment by engram-design** [comment]
Try changing your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Thanks, my next step was a composer version alias, is it likely this will have to be done for 1.x going forward? The dependency itself won't be bumped for Formie 1.x due to compatibility with Craft 3/commerce?

**Comment by engram-design** [comment]
Correct, we can't really pin the minimum requirement in Formie to dompdf ^2.0 because Commerce (and other plugins) won't support that major version change. It'll try and install the latest version that works for all dependancies (which will be the lowest version requirement - currently Commerce I believe). Our change basically says using either dompdf 1 or 2 is fine, but if Commerce only allows v1 then it'll use that and you'll still get this issue.

As such, you'll want to include it in your own `composer.json` file as `"dompdf/dompdf": "^2.0.0",` to ensure that's the minimum version **all** other plugins use.

**Comment by jamesmacwhite** [comment]
OK, thanks for the info. Temporarily I'll use a composer alias for testing, so no worries. I'll look at the longer term solution when we go live with Formie for production

Thanks!

**Comment by engram-design** [comment]
I've just checked and looks like Commerce still doesn't have a release that works with dompdf 2+ for Craft 3, so you'll likely hit an issue if you're using Commerce. If you're not, then this fix should be fine for Formie.

**Comment by jamesmacwhite** [comment]
Thanks for investigating! We aren't using Commerce, just Craft CMS 3 Pro, so we can potentially include that dompdf dependency directly if needed. Currently, I'll just alias the Craft CMS 3 branch for testing as composer version override and review when we come to using it in production.
