### ISSUE TITLE
Increase granularity of user permission for "View Forms" and "View sent notifications" so this can be turned on or off per form

### ISSUE THREAD

**Issue by jubalj** [verbb/formie#1021]
### What are you trying to do?

I want to limit the ability of a user to only be able to view and manage a subset of forms (ie. compartmentalise the forms for a user so they only see a subset of forms pertinent to them)

In particular so they;
1) Are NOT shown a list of all the forms under formie - Currently, they are unable to click and manage other forms, but can still see a list of forms that they don't have manage permissions for. I'd rather the user had an uncomplicated view of only the forms they have access to.
2) Have view sent notifications only for a subset of forms that they have permissions to. Currently, they either have no ability to view any sent notifications or they can view all sent notifications - it cannot be enabled for a subset of forms.

### What's your proposed solution?

Currently, there is a "Manage form" option for each form. 

1) Instead of the root/primary permission being 'View forms' is it possible for the "Manage form" for each form to be renamed to 'View and manage form' (and if the user had 'create form' permissions they would be conferred the ability to 'View and Manage' the new form they created). So the permission to view and manage forms could be turned on and off on an individual form basis. 
**Alternatively**, if the forms could have a 'hide for this user' option, that would also work while leaving the current permission tree structure. 

2) the 'View sent notification' could be nested under each form to enable a specific form notification view. So this could be turned on either globally or individually. 

Thanks for looking into this.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
