### ISSUE TITLE
Conditional show of field using current URL

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#1022]
### Describe the bug

I have a dropdown field that I want to only show when there's a certain word in the current URL.

My current setup is having a hidden field that contains the current URL (which works). The dropdown then has the conditional setting to check for the certain word in that value.

I can't get this to work.

If I use a plain text field and type that certain word into it and use the plain text field as the trigger, then the dropdown field shows/hides correctly.

### Steps to reproduce

1. Add hidden field and set default value to current URL
2. Add a dropdown field and set conditions to be the hidden field contains a word that should be present in the URL
3. View form from the desired URL

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

3.6.10

### Plugin version

1.4.5

### Multi-site?

No

**Comment by engram-design** [comment]
I can't replicate this sorry. No matter the destination field, the conditional-hiding logic should be the same, as the source (your hidden field) is the same. I've just tested this to be sure spinning up a new form:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/1221575/182364819-60170916-4718-4861-adb2-408a60c1bf30.png">

Which shows and hides correctly, depending on whether a value ("testing") exists in the URL

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1221575/182365001-4a97117c-a171-447a-bfd7-1338c06e2b10.png">

**Comment by jamiematrix** [comment]
It looks like I have pretty much identical field setup as your screenshots.

It's not something that has been fixed at some point? I realise I'm using an older version than current

**Comment by jamiematrix** [comment]
I've tried making a new form just with the hidden field of the URL and a text box. If I set the text box to hide if the current URL ends with "contact" then the text box is shown, but if I set it to show if the current URL ends with "contact" then it gets hidden (I can see it load onto the page then gets hidden).

**Comment by jamiematrix** [comment]
After much more testing it seems that the conditional show/hide doesn't work with default values. Using the hidden field, no matter what I set to (date/url/custom), if I use that hidden fields value as the trigger then the field I'm trying to show/hide doesn't show/hide.
If I change it to use a checkbox, a dropdown, typing a certain word/letter into a plaintext box - that works. It only appears to work with dynamic inputs instead of static or values that are present at page load.

**Comment by jamiematrix** [comment]
More testing. It seems to be limited to the hidden field.

1x plain text field with the default value of "property"
1x plain text field with the conditional to hide if the first pain text field is set to "property"
... this works.

Does the page URL get injected post page load?

**Comment by engram-design** [comment]
Just realised you were on Formie 1, but I've also tested that there, and that's working correctly too.

Just a quick sanity check for the hidden field - are you picking the "Default Value" to be "Current URL"? You're not populating the hidden field with `craft.formie. populateFormValues()` or anything?

Conditions are evaluated as soon as the page loads, you shouldn't have to do anything to trigger it by typing. If something is set to be hidden by default, it'll be hidden by the JS that evaluates the condition. 

I've also attached an export of my form - in case there's anything we're missing between us. If you want to export your form (the one you tested as a minimal reproduction) and send that through I can double check things.

I should also ask how you're rendering the form, in case that's in a special way?

[formie-hiddenUrlTest-1f76a07e-ed42-47e7-a8d2-d442175b1468.json.zip](https://github.com/verbb/formie/files/9247055/formie-hiddenUrlTest-1f76a07e-ed42-47e7-a8d2-d442175b1468.json.zip)

**Comment by engram-design** [comment]
Ah right, yep 1.4.5 is quite old (over a year old), and that wouldn't even have the import/export functionality in there.

I'd recommend updating to the latest Formie 1 release!

**Comment by jamiematrix** [comment]
> Just realised you were on Formie 1, but I've also tested that there, and that's working correctly too.
> 
> Just a quick sanity check for the hidden field - are you picking the "Default Value" to be "Current URL"? You're not populating the hidden field with `craft.formie. populateFormValues()` or anything?
> 
> Conditions are evaluated as soon as the page loads, you shouldn't have to do anything to trigger it by typing. If something is set to be hidden by default, it'll be hidden by the JS that evaluates the condition.
> 
> I've also attached an export of my form - in case there's anything we're missing between us. If you want to export your form (the one you tested as a minimal reproduction) and send that through I can double check things.
> 
> I should also ask how you're rendering the form, in case that's in a special way?
> 
> [formie-hiddenUrlTest-1f76a07e-ed42-47e7-a8d2-d442175b1468.json.zip](https://github.com/verbb/formie/files/9247055/formie-hiddenUrlTest-1f76a07e-ed42-47e7-a8d2-d442175b1468.json.zip)

Yep, picking "Default Value" to be "Current URL". There's no custom rendering of the form either, just using the Formie tag to show the selected form.

I spotted a couple of breaking changes with custom templated forms in previous updates - I'll see if I can update Formie without breaking one of our templated forms. If it comes to it, I can make another form up - was trying to avoid duplicating forms.

If a field set to hide conditionally and it's a required field, does the form still submit?

**Comment by jamiematrix** [comment]
I've updated to 1.5.19 and the conditional filtering is working on the hidden field

**Comment by engram-design** [comment]
Sounds good, and marking this as closed. I did try to go back to 1.4.5, but there's been oodles of changes since then, I would've had to have spun up a new install to test. Glad that's working for you.

If a field is both required and conditionally hidden, it'll skip validation.

**Comment by jamiematrix** [comment]
In fairness the plugin should be kept up to date anyway.

Thanks for your help, and good news on the required field!
