### ISSUE TITLE
Sprout forms migration  preg_replace_callback(): Argument #3 ($subject) must be of type array|string, DateTime given

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1024]
### Describe the bug

Running the Sprout Forms migration the process is throwing exceptions on some submissions which I believe is hitting a custom date field we have.

I did expect a potential issue given it's a custom field type. However, would you have any recommendation on how custom Sprout Forms fields can be handled to work with the Formie migration at all?

For reference, the field is basically a clone of the Craft Date/Time field with a datepicker on the front end.

```

Exception: preg_replace_callback(): Argument #3 ($subject) must be of type array|string, DateTime given (/app/vendor/elvanto/litemoji/src/LitEmoji.php:88)
#0 /app/vendor/elvanto/litemoji/src/LitEmoji.php(88): preg_replace_callback('/\\&\\#(x?[a-zA-Z...', Object(Closure), Object(DateTime))
#1 /app/vendor/verbb/formie/src/fields/formfields/SingleLineText.php(52): LitEmoji\LitEmoji::entitiesToUnicode(Object(DateTime))
#2 /app/vendor/craftcms/cms/src/base/Element.php(4296): verbb\formie\fields\formfields\SingleLineText->normalizeValue(Object(DateTime), Object(verbb\formie\elements\Submission))
#3 /app/vendor/craftcms/cms/src/base/Element.php(3355): craft\base\Element->normalizeFieldValue('bookingDate')
#4 /app/vendor/craftcms/cms/src/base/Element.php(1764): craft\base\Element->getFieldValue('bookingDate')
#5 /app/vendor/yiisoft/yii2/validators/Validator.php(258): craft\base\Element->__get('bookingDate')
#6 /app/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(verbb\formie\elements\Submission), Array)
#7 /app/vendor/verbb/formie/src/elements/Submission.php(447): yii\base\Model->validate(Array, true)
#8 /app/vendor/craftcms/cms/src/services/Elements.php(2552): verbb\formie\elements\Submission->validate()
#9 /app/vendor/craftcms/cms/src/services/Elements.php(785): craft\services\Elements->_saveElementInternal(Object(verbb\formie\elements\Submission), true, false, NULL)
#10 /app/vendor/verbb/formie/src/migrations/MigrateSproutForms.php(289): craft\services\Elements->saveElement(Object(verbb\formie\elements\Submission))
#11 /app/vendor/verbb/formie/src/migrations/MigrateSproutForms.php(91): verbb\formie\migrations\MigrateSproutForms->_migrateSubmissions()
#12 /app/vendor/craftcms/cms/src/db/Migration.php(53): verbb\formie\migrations\MigrateSproutForms->safeUp()
#13 /app/vendor/verbb/formie/src/console/controllers/MigrateController.php(27): craft\db\Migration->up()
#14 [internal function]: verbb\formie\console\controllers\MigrateController->actionMigrateSproutForms()
#15 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('migrate-sprout-...', Array)
#18 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('migrate-sprout-...', Array)
#19 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('formie/migrate/...', Array)
#20 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('formie/migrate/...', Array)
#21 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('formie/migrate/...', Array)
#22 /app/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#23 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#24 /app/craft(13): yii\base\Application->run()
#25 {main}
```

### Steps to reproduce

N/A

### Form settings

Migration from Sprout Forms (see description)

### Craft CMS version

3.7.50

### Plugin version

1.6.5

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
My first thought as a possible workaround, given it's mainly for a migration, could be to update the existing custom date fields to the standard Craft/Sprout one before the Formie migration is run that way the data should still be able to be moved over under the standard fields. Then if needed, create a new custom field under Formie to provide the equivalent date picker functionality.

**Comment by engram-design** [comment]
It _should_ skip any custom field, but it depends how you've implemented this. Your best approach is to handle it yourself through an event.

```php
use verbb\formie\events\ModifyMigrationFieldEvent;
use verbb\formie\migrations\MigrateSproutForms;
use yii\base\Event;

Event::on(MigrateSproutForms::class, MigrateSproutForms::EVENT_MODIFY_FIELD, function(ModifyMigrationFieldEvent $event) {
    if ($event->field instanceof MyCustomField) {
        // The destination field will depend on your need. You could switch to a native Formie field, or you
        // still might need a custom field - this time compatible with Formie.
        $newField = new MyCustomField -- or -- FormieFieldType();
        
        $newField->name = $event->field->name;
        $newField->handle = $event->field->handle;
        $newField->placeholder = $event->field->placeholder ?? '';
        $newField->cssClasses = $event->field->cssClasses ?? '';

        ...

        $event->newField = $newField;
    }
});
```

**Comment by jamesmacwhite** [comment]
The field itself is custom but uses the Sprout Forms field integration e.g. https://sprout.barrelstrengthdesign.com/docs/forms/custom-form-fields.html

It has a custom field type name "DatePicker" provided by a module but it is essentially a clone of the Craft Date field.

The migration isn't skipping it as I can see error traces with the field handles which are using it. The issue appears to be that DateTime isn't valid and expects an string or array.

I think converting it to a Date/Time field is probably safest in the first instance, given it's standard.

**Comment by engram-design** [comment]
That alone seems like a (new) bug, any un-supported field should be skipped. But you can still use that event to check for that custom field and convert it - or you can convert it beforehand.

I'll look into it.

**Comment by jamesmacwhite** [comment]
Thanks for providing the `ModifyMigrationFieldEvent` example as that seems better than modifying the field types in a migration before, I'll give it a go.

If you need me to test anything, let me know as we are currently testing the Sprout Forms data migration parts quite extensively, we have a lot of Sprout Forms and entries, so it is a fairly comprehensive data migration.

**Comment by jamesmacwhite** [comment]
Good news, the `ModifyMigrationFieldEvent` works great to fix the issue with the custom field. Just re-tested the migration and no longer getting errors on the forms/submissions using it now, it's being converted to the Formie Date field.

Do you want me to open a new issue around the custom field not being skipped?

**Comment by engram-design** [comment]
No stress with the new issue, I'll check it out here

**Comment by jamesmacwhite** [comment]
OK great, let me know if you need anymore info.

**Comment by engram-design** [comment]
Added a few things for migrations to improve for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
@engram-design Re-testing this with the latest changes using dev-craft3 in Composer. The migration output now shows the custom field as unsupported during the form migration, however the original fix of using the `ModifyMigrationFieldEvent` event is now not working, so the custom field is just discarded and not handled.

Prior to the fix, I had this code, which was creating the field as a Formie Date/Time field, although the migration itself was not flagging it as unsupported.

DatePicker is the custom field in Sprout Forms, Date is the Formie date field.

```php
Event::on(MigrateSproutForms::class,
	MigrateSproutForms::EVENT_MODIFY_FIELD,
	static function(ModifyMigrationFieldEvent $event) {
		if ($event->field instanceof DatePicker) {
			$newField = new Date();
			$newField->name = $event->field->name;
			$newField->handle = $event->field->handle;
			$newField->placeholder = $event->field->placeholder ?? '';
			$newField->cssClasses = $event->field->cssClasses ?? '';
			$event->newField = $newField;
		}
	}
);
```

**Comment by engram-design** [comment]
Should be fixed in the `craft-3` branch, if you want to run `composer update` again!

**Comment by jamesmacwhite** [comment]
Confirmed the field is now handled by the `ModifyMigrationFieldEvent` event.

**Comment by jamesmacwhite** [comment]
https://github.com/verbb/formie/commit/37d20fa9eb7392f1e2b07dfa967ecdbce978d90c Fixes the detection of a custom field and logs that it won't be migrated.

https://github.com/verbb/formie/commit/92d76ae63ae475b53d1ae47959c92d4aa731a901 Allows the ModifyMigrationFieldEvent to handle a custom field with this change.
