### ISSUE TITLE
GraphQL missing several arguments for submissions

### ISSUE THREAD

**Issue by joshuabaker** [verbb/formie#1025]
### Describe the bug

`isIncomplete`, `isSpam`, `spamReason`, et al. are not available on the GraphQL interface. This prevents using the API for several use cases.

### Steps to reproduce

N/a

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax (Headless)
- Client-side Validation: Yes

### Craft CMS version

3.7.27.2

### Plugin version

1.6.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
`isIncomplete` is somewhat valid to be missing, but the reason I haven't included `spam` and `spamReason` was I figured people aren't showing that on the front-end, but that's indeed an assumption on my part. Happy to add these (and any more) in.

**Comment by joshuabaker** [comment]
Valid to be missing? To clarify, are you saying that shouldn’t be made available? We have a use case where we need to access incomplete submissions, which is how I ran into it. 

Other arguments like `isSpam` are helpful. An example use case is business intelligence reports.

Please can you extend the arguments on the 1.x branch too.

**Comment by engram-design** [comment]
Sorry, I didn't explain that well - that your suggestion to have them available is valid.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.6.6](https://github.com/verbb/formie/releases/tag/1.6.6)
