### ISSUE TITLE
Can't add recipients field

### ISSUE THREAD

**Issue by bartrylant** [verbb/formie#103]
When trying to add a recipients field, the control panel UI does nothing.

1. Drag a recipients field to the form builder
2. A popup opens to set field name and extras
3. Fill in everything as you want (I set display type to hidden)
4. In the background I see the recipients field on the form
5. When I click "apply", nothing happens

Note: when I fist save it as a dropdown recipients field, it works. When I click the field to change it and choose Hidden, it then works as well. Conclusion: it only does not work when "Hidden" is the initial choice. It does work when you first save it as another type.

**Comment by engram-design** [comment]
Fixed in [1.2.14](https://github.com/verbb/formie/releases/tag/1.2.14)
