### ISSUE TITLE
Clear all data console command

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1031]
### What are you trying to do?

I'm currently testing the Sprout Forms migration regularly and need to wipe the data to start fresh to simulate the live scenario accurately. It would be great if there was a console command that would clear all form, submission and notification data to be able to test this process from a fresh without having to uninstall and install the entire plugin again.

### What's your proposed solution?

A console command that cleans all forms, submissions and notification data but without deleting the actual database tables or triggering an uninstall on the plugin.

**Comment by engram-design** [comment]
I'll consider this, but also quite afraid of the implication of it at the same time 😅

**Comment by jamesmacwhite** [comment]
Indeed! Hopefully putting it as a console command so it can't be clicked out of curiousity from a controller in the CP is a good start. Then adding appropriate annotations around the console command description when viewed via ./craft as a destructive command.

```
> Do you want to delete ALL formie data?
Yes
> No really, are you REALLY sure you want to delete everything?!
Yes

Deletes all data...
```

The reason I ask is having issues trying to truncate tables even with foreign key constraints disabled etc, using the service classes for deleting elements is so quite slow for the amount of data we are testing with.

**Comment by engram-design** [comment]
I'm going to close this in favour of being able to run two commands, which are already useful on their own:

```
./craft formie/submissions/delete --form-handle=form1,anotherForm
./craft formie/forms/delete --form-handle=form1,anotherForm
```

Deleting a form will also cascade and delete the notifications associated with it.
