### ISSUE TITLE
Setting a form on Formie Forms field that's on a matrix block in a content migration

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1032]
### Question

We are migrating from Sprout Forms and we have a matrix field that has a form matrix block, this currently has a Sprout Forms form field on it with a form selected to display on that page. I can easily add a Formie field on this matrix block through project config which propagates across the existing blocks, however what I'm looking to try and automatically get the form handle or Form object that's current set on the Sprout Forms field and then save this onto the Formie Forms field to then save the updated matrix block. This is something that will be done after the migrate Sprout Forms console command has run so all the forms exist in Formie that are currently in Sprout Forms. There should be some common values between them i.e. handle.

My understanding is I'd need to get all the entries that have a form matrix block defined, obtain the specific ID of the matrix block get the existing Sprout Forms field value on that block, then convert and format this to be compatible with Formie's field to save this data on the Formie field.

I know these fields are doing are elements and doing a DB Query, but stuck on how to approach it.

Do you have any suggestions on the best way to go about programmatically updating the value of a Formie form field in something like a content migration? Is it possible to use something like `$matrixBlock->setFieldValue()` to do it?

**Comment by jamesmacwhite** [comment]
Here's my attempt, I was able to get a matrix block with the Form field to update when using column().

* `formName` - Sprout Forms field
* `form` - Formie Form field

```php
$formMatrixBlocks = MatrixBlock::find()
			->type('form')
			->ids();

foreach ($formMatrixBlocks as $id) {
	$block = Craft::$app->getMatrix()->getBlockById($id);

	if ($block) {

		// Get the current SproutForm object
		/** @var SproutForm $sproutForm */
		$sproutForm = $block->formName->one();

		if ($sproutForm) {
			// Find the equivalent Formie Form
			$formieForm = FormieForm::find()
				->where(['handle' => $sproutForm->handle])
				->column();

			echo "Copying $sproutForm->name form to Formie Form field... \n";

			$block->setFieldValue('form', $formieForm);

			if (!Craft::$app->getElements()->saveElement($block)) {
				echo "Could not save matrix block with ID: $id \n";
				return false;
			}
		}
	}
}
```

Am I on the right lines or if there a better way? Basically I need a way to query the current form of the Sprout Forms field, the handle of it seems like the best choice given this shouldn't have changed between the two where as IDs have, then do a find query on the Formie Form element to match the equivalent form, then save the value.

**Comment by engram-design** [comment]
That's the correct approach. You'll need to update the field itself, and then update any instance of content for that field.

Here's how I handle it!

```php
use Craft;
use craft\db\Query;
use barrelstrength\sproutforms\elements\Form as SproutForm;
use verbb\formie\elements\Form as FormieForm;

$db = Craft::$app->getDb()->createCommand();

$fields = (new Query())
    ->from('{{%fields}}')
    ->where(['type' => 'barrelstrength\sproutforms\fields\Forms'])
    ->all();

// Update any fields that are Sprout Forms Fields
foreach ($fields as $field) {
    // Find any relations
    $relations = (new Query())
        ->from('{{%relations}}')
        ->where(['fieldId' => $field['id']])
        ->all();

    foreach ($relations as $relation) {
        $sproutFormId = $relation['targetId'];

        // Find the Formie form with the same name
        $sproutForm = SproutForm::find()->id($sproutFormId)->one();
        $formieForm = FormieForm::find()->title($sproutForm->name)->one();

        $db->update('{{%relations}}', ['targetId' => $formieForm->id], ['id' => $relation['id']])->execute();
    }

    $db->update('{{%fields}}', ['type' => 'verbb\formie\fields\Forms'], ['id' => $field['id']])->execute();
}
```

We target the `relations` table because being both elements, any reference to Sprout Forms forms will be targeted (whether in Matrix or not)

**Comment by jamesmacwhite** [comment]
Thank you for the alternative approach, I will do more testing!

**Comment by engram-design** [comment]
FYI, will likely turn this into a user guide with some further details.
