### ISSUE TITLE
Field values set via JavaScript not picked up

### ISSUE THREAD

**Issue by roland-d** [verbb/formie#1034]
### Describe the bug

The issue I have is that in my form I fill two fields using JavaScript but when I submit my form it comes back telling me the fields cannot be empty because they are required.

In this particular case it is the address and city field that are filled automatically by an API call made to a zipcode service. This call returns the address and city belonging to a zipcode and house number and I set the value in the form.

### Steps to reproduce

1. Create a form with a required field
2. Set the field value using JavaScript like (replace ID with the ID from your form) `document.getElementById('fui-contact-qmsyfg-fields-address').value = 'test' `
3. Submit the form
4. Form will not submit telling you that the field cannot be empty

This happens with both client-side and server-side validation.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.0.2

### Plugin version

dev-craft-4

### Multi-site?

No

**Comment by engram-design** [comment]
Can't seem to replicate this, sorry. Are you using the autocomplete behaviour for the Address field? How have you set up the required sub-fields for the Address field? As in - are all sub-fields required?

Here's my example for field settings:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1221575/183222024-16fcb53d-510c-4578-9485-24e5212dda29.png">

```js
document.querySelector('[name="fields[address][city]"]').value = 'test';
document.querySelector('[name="fields[address][zip]"]').value = '1234';
```

And the rendered field after being populated.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/1221575/183222058-73bcb4e8-69a0-49e6-be53-c2635648320e.png">

**Comment by roland-d** [comment]
Hello,

> Are you using the autocomplete behaviour for the Address field?

I am using my own autocomplete because it talks to a Dutch API service for validating the zipcode.

> How have you set up the required sub-fields for the Address field?

I have created a test form with 3 fields now and can reproduce it with that as well. The form is attached so you can check that. It is a simple form with 3 input fields of which the last one is required and disabled. I fill the last field via JavaScript in the browser console. After that I submit the form but it fails telling me the field cannot be empty.

Hopefully you can see it with the attached form:

[formie-filemakerDemo-ff2aaa8f-d3b4-4ec4-9bac-ad53350101b8.zip](https://github.com/verbb/formie/files/9287745/formie-filemakerDemo-ff2aaa8f-d3b4-4ec4-9bac-ad53350101b8.zip)

**Comment by engram-design** [comment]
I assume you're trying to populate the "Sitenaam" field? If so, you should know that this has the `disabled` attribute. With this, no value will be POSTed to Formie, so that sounds like the reason it's not working. That's just the way `<form>` elements work - nothing to do with Formie.

As such, you can't have a disabled, required input. Might I suggest using `readonly` instead?

**Comment by roland-d** [comment]
@engram-design A good catch. I did not realize that the fields will not be send, `readonly` will do. Thank you.
