### ISSUE TITLE
Checkbox option label with & character is &amp; after migration from Sprout Forms

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1035]
### Describe the bug

From a Sprout Forms migration a checkbox field had an option label of `Science and R&D`, when this has been migrated to Formie, the checkbox label has become `Science and R&amp;D`.

It is minor but I assume perphaps if characters like `&` have been used in Sprout Forms they might not be handled the same way in Formie, so just flagging it if it's something that can be handled in the migration code.

Possibly might apply to other values like the field name or instructions.

### Steps to reproduce

1. Create a Sprout Forms form with a checkbox field
2. Set an option label using the `&` character
3. Migrate this form to Formie with the Sprout Forms migrater
4. Observe the option label will now be `&amp;` when saved in Formie.

### Form settings

N/A migrated from Sprout Forms

### Craft CMS version

3.7.50

### Plugin version

Craft 3 develop branch

### Multi-site?

No

**Comment by engram-design** [comment]
Can't seem to replicate this sorry! Just to confirm, in Sprout Forms is that a Checkboxes field, or an Opt In field? I have tested both with the result: 
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1221575/183219623-48c11f19-b58b-448c-8504-233869b02b78.png">

**Comment by jamesmacwhite** [comment]
Right, so slight difference from the original issue reported, apologies.

So the checkbox option label is in fact like that in Sprout Forms with `&amp;` in the actual label value, it appears the difference is actually the rendering on the front end. The Sprout Forms template is displaying it as "&" when viewed on a template, Formie is displaying it literally.

Whether or not that is technically wrong, I'm not sure. Looking at the Sprout Forms front end template code it would appear the label is being output with `|raw` so that's likely the difference, however the option label being like that in the first place is wrong looking at it now.

I guess using characters like ampersand in labels are these correctly encoded for HTML validation under Formie?

**Comment by engram-design** [comment]
Oh right, so the argument is that Formie doesn't handle HTML entities when rendering on the front-end. I imagine this is regardless of Sprout Forms in the mix, as adding `&amp;` in any of the settings for a Formie field will show this behaviour.

I'll close this for now and maybe consider adding this behaviour in, but I'm of the opinion (at the moment) to keep things literal. But I also can't see a reason to use HTML entities in their raw form either...

**Comment by jamesmacwhite** [comment]
@engram-design Yes, I think the difference is probably the template code does not use the `|raw` filter on the label values, where as Sprout Forms does. Whether or not this should be changed due to security is debate.

You can include something like an ampersand raw, but I guess would this cause a HTML validation issue?
