### ISSUE TITLE
Hidden recipients field shows label

### ISSUE THREAD

**Issue by bartrylant** [verbb/formie#104]
When adding a recipients field with the type "hidden", it still shows the label on the front-end form. I know you can choose to not show the label, but I think this should be default for a hidden recipients field.

**Comment by engram-design** [comment]
Yeah, this is a bit tricky in practice, because you can switch between different layouts and the label would need to change when you do that.

For instance, what if you set the field as a dropdown, but then switch it to hidden - we'd have to change the label state which would be a bit odd.

**Comment by engram-design** [comment]
Updated in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
