### ISSUE TITLE
Cannot read properties of undefined JavaScript errors

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1042]
### Describe the bug

After a migration from Sprout Forms I am seeing two JavaScript errors being thrown in console on a form.

These forms have been migrated from Sprout Forms, they have all been configured under a template that does not output any CSS theme because we have our own form styling which is being applied using SASS and `@extend ` on existing form/field rules but all JavaScript settings are enabled.

This form does have a checkbox field along with a Date field that does have the date picker setting on.

```
date-picker.js?v=1659602171:1 Uncaught TypeError: Cannot read properties of undefined (reading 'formTheme')
    at e.value (date-picker.js?v=1659602171:1:70929)
    at new e (date-picker.js?v=1659602171:1:70256)
    at t.value (formie.js?v=1659602171:1:38933)
    at formie.js?v=1659602171:1:38695
    at Array.forEach (<anonymous>)
    at n.length.n.forEach.r.src.n.onload (formie.js?v=1659602171:1:38672)
value @ date-picker.js?v=1659602171:1
e @ date-picker.js?v=1659602171:1
value @ formie.js?v=1659602171:1
(anonymous) @ formie.js?v=1659602171:1
n.length.n.forEach.r.src.n.onload @ formie.js?v=1659602171:1
load (async)
(anonymous) @ formie.js?v=1659602171:1
value @ formie.js?v=1659602171:1
(anonymous) @ formie.js?v=1659602171:1
value @ formie.js?v=1659602171:1
BZ5K @ formie.js?v=1659602171:1
r @ formie.js?v=1659602171:1
6 @ formie.js?v=1659602171:1
r @ formie.js?v=1659602171:1
(anonymous) @ formie.js?v=1659602171:1
(anonymous) @ formie.js?v=1659602171:1
```

```
checkbox-radio.js?v=1659602171:1 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at checkbox-radio.js?v=1659602171:1:9529
    at NodeList.forEach (<anonymous>)
    at t.value (checkbox-radio.js?v=1659602171:1:9501)
    at new t (checkbox-radio.js?v=1659602171:1:9296)
    at t.value (formie.js?v=1659602171:1:38933)
    at formie.js?v=1659602171:1:38695
    at Array.forEach (<anonymous>)
    at n.length.n.forEach.r.src.n.onload (formie.js?v=1659602171:1:38672)
```

Any ideas to further debug the JavaScript errors related to the identified form fields/properties?

### Steps to reproduce

1. Migrate a form from Sprout Forms that has a checkbox field
2. After migration and displaying this form using Formie, observe console errors related to undefined properties.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.50

### Plugin version

dev-craft3

### Multi-site?

No

**Comment by engram-design** [comment]
There's no inherent issues with a migrated form on my end, even migrating every single field type from Sprout Forms. But it sounds like the JS isn't initialising properly.

You're just using `craft.formie.renderFor()` to render your form, and no custom templates, or template overrides?

For instance, the `<form>` element must have an `id` attribute starting with `formie-form-`, have a data attribute `data-config`. And each field that requires JS should have a `data-field-config` attribute with settings.

**Comment by jamesmacwhite** [comment]
Yeah this is how I'm rendering it:

```twig
{% set form = form.one() %}

{% if form %}
    {% set options = {
        formClasses: [
            'form'
        ],
        formAttributes: {
            'id': "formie-form-#{form.handle}"
        }
    } %}
   
    {{ craft.formie.renderForm(form.handle, options) }}
{% endif %}
```

I am overriding the form ID for easier tracking, but that is still prefixed with `formie-form-`, otherwise I have no custom templates or overrides other than the options array above.

As far as I can see the ID, data-config attribute etc are all there.

**Comment by engram-design** [comment]
Ah, I see. Yes there's some issues with overriding the form's ID in Formie 1 - it's actually advisable to **not** do it if you can help it. This handling was revamped in Formie 2.

I've back-tracked the appropriate fixes to Formie 1 for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Thanks! That's now fixed the issues with JS errors
