### ISSUE TITLE
Form with multiple date pickers enabled only loads Flatpickr on first field

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1043]
### Describe the bug

We have a form that has two date fields which have the date picker options enabled on both. It appears that when you have more than one date field present that uses has the "Use date picker" option enabled, only the first field has the Flatpickr enabled on it, the other field ends up being rendered as a date field which just uses the web browsers native date field type and provides a different date picker implementation.

It seems that in this case a form can only have one flatpickr instance and it's the date field that appears first that receives it.

This would suggest that the Flatpickr target selector is pointing to a specific element in a singular way or doesn't expect/handle multiple flatpickr instances on a form.

I have confirmed that by just having one enabled at a time it works fine, but not with both.

### Steps to reproduce

1. Create a form with two date fields with the "use datepicker option" enabled
2. Observe the first field with the setting enabled gets the Flatpickr date picker, the other will be a standard date field as rendered by the browser.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.50

### Plugin version

dev-craft3

### Multi-site?

No

**Comment by engram-design** [comment]
I can't replicate this, sorry. Sounds like this might be similar to your issues with JS in your [other issue](https://github.com/verbb/formie/issues/1042)

**Comment by jamesmacwhite** [comment]
The trace does mention a date picker JS file in the other issue, so perhaps it is related.

**Comment by jamesmacwhite** [comment]
It is related to the JS issue in the other issue. Closing this!
