### ISSUE TITLE
Adding custom CSS class to form tag add extra space in class value

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1044]
### Describe the bug

When adding a custom class via the formClasses key with form options, the CSS class on the form has extra space after the default classes.

![image](https://user-images.githubusercontent.com/8067792/183590118-6696b9b8-fbbc-4797-8660-b3a57a51e7fa.png)

While this isn't harming anything, this could be reduced by including the `|filter` after the merge() of the custom class value e.g.

```
class: [
        'fui-form',
        "fui-labels-#{defaultLabelPosition}",
        form.settings.displayPageProgress ? "fui-progress-#{form.settings.progressPosition}",
        form.settings.validationOnFocus ? 'fui-validate-on-focus',
] | merge(options.formClasses ?? []) | filter,
```

Currently the class value might have extra space like this:

```
fui-form fui-labels-above-input   form
```

Using `filter` you can make the class value more normalised.

```
fui-form fui-labels-above-input form
```

### Steps to reproduce

1. Add a custom CSS class to the form tag
2. Observe the extra space between the default and custom CSS class

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.50

### Plugin version

dev-craft3

### Multi-site?

No

**Comment by engram-design** [comment]
Going to close this as it's fixed in Formie 2 thanks to Theme Config, and being such a small change for Formie 1 (it's really not affecting anything functional), going to close this.
