### ISSUE TITLE
Status field not up to date in submissions list

### ISSUE THREAD

**Issue by iamtompickering** [verbb/formie#1049]
### Describe the bug

I have added a new status 'Resolved', and when I set a submission entry to this status, the submission list still shows as 'New'

![CleanShot 2022-08-17 at 08 17 13@2x](https://user-images.githubusercontent.com/6592882/185062082-e3102b43-13f3-4f9c-b46e-638ddfee7d0a.png)

As you can see in the screenshot, I am filtering by 'Resolved' with has a colour of Red, but the status of the submission entry is still green. 

### Steps to reproduce

1. Create a new status
2. Assign a submission to the new status
3. View the submissions in the table with this new status

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.2.1.1

### Plugin version

2.0.6

### Multi-site?

No

**Comment by engram-design** [comment]
Pretty sure the status is correct, but just not showing the correct colour indicator, I'll take a look

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
(sorry for the duplicate, missed it ; thanx for fixing this so quickly)

**Comment by engram-design** [comment]
Added in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)
