### ISSUE TITLE
Email notification variable Site Name shows primary site only

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#105]
When sending email notification with **Site name** and **Submission URL** variables, the output of these two is primary site URL and Submission admin URL.

I believe Site name should output actual site name the form was sent from. For example Site2-url.com, site1-url.com.

The second variable, Submission URL – I was expecting to output actual page URL the submission was send from, for example: site2-url.com/news/2020/very-new-article. Instead I am getting URL to CP, not sure if this is bug or expected output.

**Comment by engram-design** [comment]
As for the submission URL, that's correct behaviour, but I can see how it's confusing. It's referring to the submission element's URL, which is the control panel, which is useful in some cases.

The tricky part about even trying to add a "Referral URL" to your variable list is that we need to record it at the time of submission. As email notifications are sent later in a queue, it's already technically lost where it came from (as the queue job could be run much later after submission - potentially).

The solution is to use a hidden field and use the "HTTP Refer URL" as its value. I've also renamed this to "Submission CP URL" for clarity.

In the same boat is the Site Name - it's not recorded upon submission what site the user was on when they submitted the form. Again, being in a queue, it's got no reference to which site it was on.

**Comment by lexislav** [comment]
@engram-design I will use the hidden fields to add the requested functionality then. Thanks for pointing that out

**Comment by engram-design** [comment]
We'll be able to handle this better once https://github.com/verbb/formie/issues/149 is done

**Comment by engram-design** [comment]
Should be fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
