### ISSUE TITLE
Adding 'author' to submission entries

### ISSUE THREAD

**Issue by iamtompickering** [verbb/formie#1050]
### What are you trying to do?

The client would like to assign different users to the submissions, so they can track who has viewed and resolved the submissions. 

### What's your proposed solution?

Add an 'author' field to submission entries.

**Comment by engram-design** [comment]
There'a already the ability to assign a user to a submission, so long as you enable "Collect User" setting for a form.

**Comment by iamtompickering** [comment]
@engram-design ahhh perfect thanks for that, just what I need!
