### ISSUE TITLE
Multipage form validation focus JS error after upgrading to 1.6.7 from1.6.6

### ISSUE THREAD

**Issue by parthi-me** [verbb/formie#1051]
### Describe the bug

We have a form with 3 pages, previously it's working properly with Version 1.6.6 after upgrading to the latest version 1.6.7. We are getting JS errors like the below when require field validation is happening. 

"An invalid form control with name='fields[xxx]' is not focusable. "

- fields[xxx] is a page 2 required element. 

### Steps to reproduce

1. Create a multipage form with required fields on each page.
2. Submit the form without filling the required fields.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.51

### Plugin version

1.6.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
Ah, sorry about that. This was a bad merge of behaviour on my part from Formie 2 for Craft 4. Fixed in [1.6.8](https://github.com/verbb/formie/releases/tag/1.6.8)
