### ISSUE TITLE
Missing CORS headers on submission endpoint 

### ISSUE THREAD

**Issue by lukasIO** [verbb/formie#1056]
### Describe the bug

Some users report a CORS error when using Firefox to try to submit a form via formie.
The error says that `Access-Control-Allow-Origin` headers are missing from the `/actions/formie/submissions/api` endpoint.
The weird part is, I do not encounter the same problem when using Firefox. 

### Steps to reproduce

Wasn't able to reproduce myself with Firefox, so this is kind of tricky. I did see the error happening on a user's laptop however. 
So sorry for those utterly useless repro steps... 
1.  Open submit page in firefox
2.  Try to submit the form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.6

### Plugin version

1.6.7

**Comment by engram-design** [comment]
Hmm, I can't reproduce it either (have also tried all other browsers and a few versions back for Firefox). I would've thought [this](https://github.com/verbb/formie/blob/craft-3/src/controllers/SubmissionsController.php#L926) be enough.

Will keep investigating.

**Comment by engram-design** [comment]
Unable to reproduce this one, we can open it if this is still an issue.
