### ISSUE TITLE
project yaml config for global formie settings

### ISSUE THREAD

**Issue by kevinmu17** [verbb/formie#1057]
### What are you trying to do?

When configuring formie with for example, `settings -> Fields -> Disabled fields` it is not creating an project yaml configuration. So when pushing to production you need to reconfigure the entire formie settings again.

### What's your proposed solution?

Make the global formie settings create a project yaml configuration file for more friendly maintaining environments

**Comment by engram-design** [comment]
Not sure what you mean, sorry. These are plugin settings, which are stored in project config? You shouldn't be allowed to edit these settings on production (if you have `allowAdminChanges = false` on production).

For instance, here's my diff when adding some fields to be disabled in my `project.yaml` file

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1221575/186535085-d7386e47-215b-480b-a59f-4437893e55a3.png">

**Comment by kevinmu17** [comment]
Man, i'm sorry! i see that it is updating the project.yaml. Must have missed it somehow (sorry using new editor so have to get used to the new git interface)
