### ISSUE TITLE
Minimum character input setting for fields

### ISSUE THREAD

**Issue by yuvi100** [verbb/formie#1058]
### What are you trying to do?

Setting up the minimum number of characters required for a field to be submitted.

Sometimes people don't fill out the fields with enough information, so setting a minimum would force them to write more.

I'm specifically referring to the multi-text and single line text fields but might be useful for all text input fields.

### What's your proposed solution?

Similar to the current maximum character option for a field.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
