### ISSUE TITLE
Changing SASS theme variables for custom styling

### ISSUE THREAD

**Issue by olemagnus** [verbb/formie#106]
**What are you trying to do?**

I wish to be able to change the primary color and the other variables in the `formie-theme.scss` file. I'm currently overriding the classes with `!important`.

**What's your proposed solution?**

1. Either to change these values in the settings screen in Craft
*or*
2. The option to install the CSS (and JS) through NPM without having to import from the (composer) vendor directory. 

**Additional context**

The reason I want this option and not the full control over the styling is because I suspect this might play nicer with future updates, without stuff breaking. 

It would also be nice if there were more variables, like border-radius for the repeater remove button.

**Comment by engram-design** [comment]
It's something we've discussed internally, but haven't really come up with an elegant solution we're happy with.

On the one hand, we could "variable-ize" everything in the control panel so you can configure various things about the appearance of the form. But this means including additional CSS on the page, likely inline separate from the external CSS theme file. We could use CSS variables, but I'm not comfortable with browser support (yet). We'd also still just be overriding properties, so it's no better than what you're doing now, except content-managed.

As for the separate NPM package, I'm not thrilled about maintaining a separate package for the JS and theme. You should be able to dive into the SCSS file in the vendor directory and override the variables defined there.

We'll continue giving it some thought.

**Comment by leevigraham** [comment]
I think this could be achieved by using `!default` for the sass variables. https://thoughtbot.com/blog/sass-default

That way you could set the variables in your own stylesheet and then import the `formie-theme.scss`

Alternatively convert all the sass variable output to css variables which could be overiden by non-sass projects. In this case you would need to remove any colour functions in the sass and drop IE support.

**Comment by engram-design** [comment]
@leevigraham `!default` should've been added in the first place. I was only reminded about it after this conversation, but it slipped my mind to add it in.

CSS variables are a tricky one. I'd love to use them, but I've also got to prioritise conservative browser support for the off-the-shelf CSS (and JS). I'd like to investigate having both - if at all possible.

**Comment by leevigraham** [comment]
See: https://github.com/verbb/formie/pull/165

**Comment by engram-design** [comment]
@leevigraham PR much appreciated 👍

**Comment by leevigraham** [comment]
I'll have a think about how to include css vars without breaking backwards compatibility.

**Comment by leevigraham** [comment]
One thing to point out is that you're using flex which has the same support as css variables. The only minor (or major) exception is that flex has some limited and buggy support in ie 11.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/25124/95543443-42d15100-0a44-11eb-9045-6295af79541f.png">

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/25124/95543497-609eb600-0a44-11eb-9c74-4040516d91b6.png">

**Comment by engram-design** [comment]
Well, flex in IE 10 and 11 has lots of bugs, it plain doesn't support CSS variables, which is kind of a difference. My tests have shown that what flex properties Formie uses are supported in IE11 (IE10 needs some work, but that's not my priority compared to IE11)

**Comment by engram-design** [comment]
After some tinkering, we'll likely switch to CSS variables with a fallback for IE11.

**Comment by engram-design** [comment]
I've managed to switch all the theme styles over to CSS variables, with a fallback for IE11, so no breaking change. This should help greatly when overriding theme styles. Refer to the [docs](https://verbb.io/craft-plugins/formie/docs/developers/front-end-css#css-variables).

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
