### ISSUE TITLE
Add support to JS theme file custom classes for components

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1060]
For example, when using an Ajax-based form, because error/success messages are generated in JS on-demand, they're unaware of Theme Config settings in Twig. As such, we need to feed these into JS. See https://github.com/verbb/formie-theme-configs/issues/1

**Comment by engram-design** [comment]
This is now handled in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)

**Comment by chasegiunta** [comment]
@engram-design I'm not sure if there was a regression, but on `dev-craft-4 as 2.0.12` I'm only able to get themeConfig classes to be respected when JS features ("Validate Form on Submit", "Validate When Typing") are off.

**Comment by engram-design** [comment]
@chasegiunta Which classes aren't being respected?

**Comment by chasegiunta** [comment]
@engram-design Error related classes specified in themeconfig are only applied after doing a full page submit.

There's quite a few weird bugs related to themeconfig that I'll try to notate thoroughly in a future issue with some proper research and steps to reproduce... 

But as a quick high level:

- As already mentioned, error classes not being applied to AJAX presented validation errors (on type & before submit)
- Even with the latest dev commit (560319ca303d897aef94e24fce0b7a1973ec9c85 - Oct 10) there's still issues applying css classes specified in field settings, regardless of if resetClass/es option is specified.
- Classes specified in theme config are being applied to the tag _twice_.
- Other quirks that may be due to items above (is there an internal cache being used for settings and/or render output?)

**Comment by engram-design** [comment]
Ah yes, good point. When using client-side validation, you'll still get the `fui-error` class added to your inputs and field wrappers. This is because we don't have a specific theme config key for errors on the field, because they're combined with other config keys. Instead, they're defined like:

```
fieldInput: {
    attributes: {
        class: [
            'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md',
            "{{ (submission.getErrors(field.handle) ?? null) ? 'border-red-300' }}",
        ],
    },
},
```

Which of course won't work at the JS level for client-side validation. We'd need to introduce some extra theme config options to cater for this, but as I've mentioned there's no other instances of combining two different config keys in a single element. I'll have to give this some further thought.

As for your other issues:

> Even with the latest dev commit (https://github.com/verbb/formie/commit/560319ca303d897aef94e24fce0b7a1973ec9c85 - Oct 10) there's still issues applying css classes specified in field settings, regardless of if resetClass/es option is specified.

Just not rendering? It will only render it on the top-level field div (the one with `data-field-handle`, `data-field-type`)

> Classes specified in theme config are being applied to the tag twice.

Should be fixed in the latest branch changes.

> Other quirks that may be due to items above (is there an internal cache being used for settings and/or render output?)

There isn't, but you can always run Craft's cache-clearing utilities which might help.

**Comment by mtwalsh** [comment]
@engram-design Hi, :wave: I'm using the Tailwind theme (first time giving Formie a whirl on a project) and noticing that on multi-page forms subsequent pages are not displayed, the tab changes but the form fields are hidden. The `hidden` class defined here seems to remain:

https://github.com/verbb/formie-theme-configs/blob/main/tailwind/index.html#L77

Formie `2.0.21`

**Comment by engram-design** [comment]
@mtwalsh I can only reproduce this with Ajax page submission enabled, if you wanted to confirm? 

If so, some of these advanced features aren't possible with Ajax, because it relies on Twig code to render the output, and isn't aware of state. Without a server-side call to re-render the form (to evaluate if the current page is the one to be shown) the classes won't have their Twig template parsed.

I'll likely need to add in some more property options to handle this sort of thing, as it affects a few different UI interactions (like clicking on the page tabs). Something like (proposed):

```
pageInactive: {
    attributes: {
        class: 'hidden',
    },
},

pageTabLink: {
    attributes: {
        class: [
            'whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300',
        ],
    },
},

pageTabLink: {
    attributes: {
        class: [
            'whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm',
        ],
    },
},

pageTabLinkInactive: {
    attributes: {
        class: [
            'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
        ],
    },
},

pageTabLinkActive: {
    attributes: {
        class: [
            'border-indigo-500 text-indigo-600'
        ],
    },
},
```

As you can see it gets a bit tricky when defining page tabs active/inactive classes, because you need to define both the inactive and active classes separately, as Tailwind won't really work to override things. You'll also probably want base classes for all states.

Similarly for pages we want to show a `hidden` class when **not** active, and remove it when active. Overriding that with `hidden` for default and `block` when active isn't ideal, nor reliable.

So - I'm working on it, and probably a separate issue!

**Comment by mtwalsh** [comment]
Thanks @engram-design, that still sounds fine to me. I don't really mind if this is going to require a little effort on my side so long as it's possible. Yes I am using the Ajax page submission option, that seems to work better for my use-case as the form is quite lengthy and starts midway down a page.
