### ISSUE TITLE
Be able to add links in email notifications

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1061]
### What are you trying to do?

I would like to be able to add links to Entries or external links, in the settings of emails notifications found in _Edit Notification_ > _Email Content_.

### What's your proposed solution?

As an example, we can do it in Redactor.

**Comment by engram-design** [comment]
You can add a "link" button to the rich text editor via the [docs](https://verbb.io/craft-plugins/formie/docs/get-started/configuration#rich-text-configuration)
