### ISSUE TITLE
Add ability to limit "past" or "future" selection for dates in Date/Time field

### ISSUE THREAD

**Issue by jubalj** [verbb/formie#1063]
### What are you trying to do?

I want users not to be able to select a future date. Currently, there is a "Max Date" and "Min Date" option for the field however this can't be set relative to the "current date" - it can only be assigned to a specific date.

### What's your proposed solution?

Solution 1:
Have a checkbox next to Max Date, called "Prevent dates in the future", and a checkbox next to Min Date, called "Prevent dates in the Past"

Solution 2:
Alternatively, have two (long) integer fields that act as an offset from the current date for the Max and Min date. 
ie Maximum days into the future to allow dates to be picked:
Set to 0 for preventing all dates in the future. Set to 300, it allows up to 300 days into the future.

The latter may be more beneficial than the current Max and Min absolute date

**Comment by engram-design** [comment]
Added the ability to set min/max settings to offsets for today's date for days/weeks/months/years (and just be today). To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jubalj** [comment]
Thanks for so quickly implementing this feature. 

I notice that the field no longer defaults to the 'Today data' on load - if the Max Date offset is left at 0 (however if I increase the offset to 1, the default date pre-populates as expected).

**Comment by engram-design** [comment]
Should be fixed in the latest `craft-4` branch, if you'd like to run `composer update` again.

**Comment by engram-design** [comment]
Added in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)
