### ISSUE TITLE
Exporting Submissions and Unique Fields

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#1065]
### Describe the bug

I came across an issue where exporting a submission wasn't exporting all of my form fields.

After looking into it, I see that you're using the field's label as the key. This is great for outputting columns titles in a pretty way but has some drawbacks in complex forms, when fields share the same label (in multipage setup for instance, you can easily have phone, address and such which you simply want to label Phone or Address, or when organizing your form in sections).

An easy fix for this would be to use the field's handle as the key, loosing the prettiness along the way. Or using both like `Address (addressFieldHandle)`.

What do you think?

### Steps to reproduce

1. Create a 2 pages form with a Name field and Address field on each page (same label)
2. Export some submissions

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.2

### Plugin version

2.0.7

### Multi-site?

No

**Comment by engram-design** [comment]
Yep, this change was via https://github.com/verbb/formie/issues/928 and I'm not sure if including both is going to be a backwards step for users who would prefer the label.

So the options are:
- Including both `Address (addressFieldHandle)`
- Suffixing `Address 1`, `Address 2`, etc
- Making it configurable

The suffix option isn't ideal, as it's kinda messing with the label for the form. What if the field was already labelled `Address 1` and then it would turn into `Address 1 1`.

**Comment by JeanLucEsser** [comment]
The suffix option lacks context too, where the first option brings along the full context of the field.

I would go with the first option, maybe adding the Handle only for those fields that share the same label, leaving all other fields with only their labels, so that wouldn't be a drawback step for users preferring the label.

Making it configurable could be for a future version of Formie, but the configuration shouldn't allow for missing fields data, so not sure about making it fully configurable.

**Comment by engram-design** [comment]
Yep, I can get behind that as an appropriate option!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
