### ISSUE TITLE
Alert message deleting submision from CP - Undefined variable $form

### ISSUE THREAD

**Issue by Herokid** [verbb/formie#1068]
### Describe the bug

When I try to delete some Submission I received this error in the bottom-left warming tooltip .
`Undefined variable $form`

### Steps to reproduce

1. Open CP and go to Formie/Submissions section
2. Select one submission and try to delete it.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.8

### Multi-site?

Yes

### Additional context

Here the exception error:
`2022-08-31 14:06:31 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Undefined variable $form in /MY_PROJECT_FOLDER/vendor/verbb/formie/src/elements/Submission.php:1064
Stack trace:
#0 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined varia...', '/Users/unvoid/D...', 1064)
#1 /MY_PROJECT_FOLDER/vendor/verbb/formie/src/elements/Submission.php(1064): craft\web\ErrorHandler->handleError(2, 'Undefined varia...', '/Users/unvoid/D...', 1064)
#2 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/services/Elements.php(1745): verbb\formie\elements\Submission->afterDelete()
#3 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/elements/actions/Delete.php(189): craft\services\Elements->deleteElement(Object(verbb\formie\elements\Submission))
#4 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(240): craft\elements\actions\Delete->performAction(Object(verbb\formie\elements\db\SubmissionQuery))
#5 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#6 /MY_PROJECT_FOLDER/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /MY_PROJECT_FOLDER/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /MY_PROJECT_FOLDER/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('perform-action', Array)
#9 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('element-indexes...', Array)
#10 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('element-indexes...', Array)
#11 /MY_PROJECT_FOLDER/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /MY_PROJECT_FOLDER/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /MY_PROJECT_FOLDER/web/index.php(12): yii\base\Application->run()
#14 {main} {"memory":30625552,"exception":"[object] (yii\\base\\ErrorException(code: 2): Undefined variable $form at /MY_PROJECT_FOLDER/vendor/verbb/formie/src/elements/Submission.php:1064)"} `

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Herokid** [comment]
Hi @engram-design 
Thanks for your quick reponsse.
I'll check it later.

**Comment by Herokid** [comment]
Thanks for your help,
I could remove submission correctly.
