### ISSUE TITLE
Error when submiting a form with Microsoft Dynamics 365 CRM intergration

### ISSUE THREAD

**Issue by jurgenkrol** [verbb/formie#1071]
### Describe the bug

When submitting a form with a with Microsoft Dynamics 365 CRM intergration with custom field mapping an error occurs:
 
"Microsoft.OData.ODataException: An undeclared property 'crmp_odinbedrijfid' which only has property annotations in the payload but no property value was found in the payload."

It seems that when linking with a custom Dynamics field the logical name is used instead of the schema name. I think for custom fields the schema name must be used and for default fields the logical name.

In the above error message 'crmp_odinbedrijfid' is the logical name of the custom field, while 'crmp_Odinbedrijfid' is the schema name.

### Steps to reproduce

1. Create a Microsoft Dynamics 365 CRM intergration for a form
2. Map form fields with some custom fields in Dynamics.
3. Make a form submission

### Form settings

- Multi-page form: No
- Submission Method: Ajax and Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

3.7.53.1

### Plugin version

1.6.10

### Multi-site?

No

**Comment by engram-design** [comment]
I'm no Dynamics expert, so this clarity is appreciated! I didn't actually realise there was a difference in my testing. From what I've seen, I think the `SchemaName` should be used for everything?

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.6.11](https://github.com/verbb/formie/releases/tag/1.6.11)

**Comment by jurgenkrol** [comment]
I tested this with an intergration that uses both custom fields (like the mentioned "crmp_Odinbedrijfid") and out of the box fields (like "OwnerId"). The custom field now seems to work fine with the SchemaName, unlike the OwnerId field. This gives an error:

"An undeclared property 'OwnerId' which only has property annotations in the payload but no property value was found in the payload."

As I mentioned before , I think for custom fields the schema name must be used and for default fields the logical name, which in this case is "ownerid". So, all lowercase.

**Comment by engram-design** [comment]
Should be fixed now! To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jurgenkrol** [comment]
Thanks, this update fixed the issue!

**Comment by jamesmacwhite** [comment]
Just for reference, I'm not sure all custom fields should use the schema name.

See this case: https://github.com/verbb/formie/issues/1251

The schema name causes an error, where as the logical name doesn't and it is a custom field, so this rule might not be 100% accurate for all cases. Although I did seem to find sources that suggest that Schema Name should be used for OData, but here we have the opposite a custom field that doesn't work unless using the logical name.

**Comment by jamesmacwhite** [comment]
@jurgenkrol I'd be really interested if you could potentially dump the metadata for the CRM environment you use this with `{{webapiurl}}$metadata` e.g. `{{crmUrl}}/api/data/v9.0/$metadata` and confirm for any entity like `contacts` or `leads` what the Property Name values for any field appear to be, this environment seems to be all LogicalName values.

Also is this for Dynamics 365 online or on-premises?
