### ISSUE TITLE
Can't set Checkboxes Option Label that contains emoji

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1079]
### Describe the bug

I can't set Checkboxes Option Label that contains emoji.

I get this kind of error while saving the form:
`Unable to save form: {"general":["SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x8E\\x9F T...' for column 'settings' at row 1\nThe SQL being executed was: UPDATE `craft_fields` SET `settings`='`

The only option I found is to add the Checkboxes Option Label without emoji, then copy the content to the `{language}/formie.php` file and add the match with an emoji.

### Steps to reproduce

1. Try to set a Checkboxes Option Label that contains emoji
2. Save the form
3. Get the error

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)

**Comment by giorgiopogliani** [comment]
@engram-design I have the same error on Fomie 1.6.14 (Craft 3) with the `cache` column of the `formie_integrations` table, it's crashing on the refresh of the integration. Could you make a fix? Thanks!

**Comment by engram-design** [comment]
@giorgiopogliani That would be different to the original issue, and more related to https://github.com/verbb/formie/issues/1088.

What integration are you using that has emoji's in the content?

**Comment by giorgiopogliani** [comment]
@engram-design The integration is salesforce CRM. My guess was that the database column doesn't have the right settings to save emojis. Let me know if I need to open another issue, thanks!

**Comment by engram-design** [comment]
@giorgiopogliani A new issue would be great thanks. Can you provide detail on what part of your content in Salesforce contains an emoji too? We have to cater for things specifically when it comes to emoji's.

**Comment by giorgiopogliani** [comment]
@engram-design I opened the issue #1115, I added an equivalent example of content with the emojis part there. Thanks!
