### ISSUE TITLE
Allow submit button to be placed inline with other inputs

### ISSUE THREAD

**Issue by furioursus** [verbb/formie#108]
**What are you trying to do?**
Oftentimes we have single line email campaign signups that our staff would like to add to our content builder, but the current implementation of Formie seems to limit the submit button to its own line. For large forms this makes sense, but in cases of calls to action, it can feel clunky.

**What's your proposed solution?**
Like other fields in the form builder, allow us to drag the submit button to the end of a single row so that when it renders, it looks something like this:

<img width="1031" alt="CleanShot 2020-09-18 at 00 10 45@2x" src="https://user-images.githubusercontent.com/366427/93567403-6fadaf00-f943-11ea-8754-495f19547202.png">

For now, we can make a custom template for this kind of form, but I suspect as they start adding more campaigns, it will become more difficult to support them in rendering template customizations.

**Comment by engram-design** [comment]
Thanks for the feedback! So firstly, I'm not a massive fan of having it as drag-and-drop, but I'd be open to it if we can make it work at a technical level.

There's other things to consider - if your form has reCAPTCHA, which relies on the placement of the submit button for where it inserts itself - where does it end up?

Mostly, I just don't want to get into the situation like Freeform where you have to add the submit button and captchas to each page - that's just entirely unintuitive.

I'll consider how to handle this - but as you've mentioned a custom template, or using the rendering hooks is the way to go for now.

**Comment by spoeken** [comment]
I simply did this by adding classes. I'm using tailwind. 

```
      {% set renderOptions = {
          themeConfig: {
              fieldLabel: {
                  attributes: {
                      class: 'text-white',
                  },
              },
              field: {
                attributes: {
                      class: '!mb-0',
                  },
              },
              page: {
                   attributes: {
                      class: 'flex space-x-4 place-items-end',
                  },
              },
              submitButton: {
                attributes: {
                      class: 'rounded-full',
                  },
              }
          }
      } %}

      {{ craft.formie.renderForm('newsletter', renderOptions) }}
```

**Comment by engram-design** [comment]
After many months (years?!) of considering this, I'm going to mark this as something we're not going to implement. There's a whole lot of complexity to making this happen, along with handling where captchas sit.

With the addition of Theme Config (as @spoeken has shown), this should be easier to implement a custom layout without touching the Twig templates for the form.

While the use case here for a 2-field + 1 button horizontal newsletter form is very valid and common, it's the more complicated forms that concern me. I don't actually want to encourage users to be able to throw submit buttons wherever they like in a form, as that just leads to some bad UX.

Conversation is always open, but at this stage, it's not something we're looking to pursue.
