### ISSUE TITLE
Entries and categories dropdown field with multiple options on

### ISSUE THREAD

**Issue by belkin** [verbb/formie#1080]
### Describe the bug

I've added 'Entries' and 'Categories' dropdown fields to form with 'Multiple' option on but in the front-end I'm getting the following error: 

`Object of class craft\fields\data\MultiOptionsFieldData could not be converted to string`

![image](https://user-images.githubusercontent.com/3419659/188614799-8b55e809-400b-4d17-b2d5-985d34556752.png)

### Steps to reproduce

1. Create a new form.
2. Add Entries or/and Categories dropdown field with Multiple options on.
![image](https://user-images.githubusercontent.com/3419659/188615389-ec26c2eb-f69c-4cd6-8d28-5e8247eaea25.png)
![image](https://user-images.githubusercontent.com/3419659/188615461-29dbb898-72ec-4bbd-bd19-0ebb7d3037b0.png)
4. Save form.
5. Add it to an entry and open the url.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by belkin** [comment]
Thanks for the quick fix! 🚀

**Comment by belkin** [comment]
Switching Display Type of this field to Checkboxes breaks the frontend.

![image](https://user-images.githubusercontent.com/3419659/188635728-fe37ee92-8371-46ed-b8fa-8ccf2901ae1c.png)

**Comment by engram-design** [comment]
If you want to run `composer update` again, that should fix the issue.
