### ISSUE TITLE
Container attributes are not working

### ISSUE THREAD

**Issue by belkin** [verbb/formie#1081]
### Describe the bug

Container attributes are not working properly. After setting custom attribute to a field container and input only de input attribute becomes visible.

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/3419659/188619421-7696f720-fa3e-46bb-9b9f-6de0380cc715.png">

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/3419659/188620789-351ee86f-21fe-413f-9724-684e7720f9a8.png">

### Steps to reproduce

1. Create form.
2. Add field to form with custom container attribute.
3. Embed it to page.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
This certainly got missed along the way with Theme Config!

Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by belkin** [comment]
Thanks for the quick fix! 🙌 🚀
