### ISSUE TITLE
When setting user permissions, theres no way to set users to access all current and future forms. 

### ISSUE THREAD

**Issue by toddpadwick** [verbb/formie#1083]
### Describe the bug

I have set the following to true for a specific user group:

- View forms
- Create forms
- Delete forms
- Manage all forms 
- Manage form appearance 
- Manage form behavior 
- Manage form notifications
- Manage notification advanced 
- Manage notification templates 
- Manage form integrations 
- Manage form settings 

But when I create a new form on production, users in this group cannot see it, and can only see forms created before the above settings were made.

### Steps to reproduce

1. Create user group
2. assign permissions
3. create new form
4. ask a user within the user group to try and access it

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 3.7.50

### Plugin version

	1.6.5

### Multi-site?

No

### Additional context

I am aware that you can specifically add permissions to individual forms, but that would require an admin to go in and make system changes, locally, then deploy them, any time a client creates a new form.

**Comment by engram-design** [comment]
Can't seem to replicate this, sorry. And yep, that's the reason for this permission is that you want users to have access to every new form created without having to explicitly grant access to each one.

It's thanks to [this](https://github.com/verbb/formie/blob/bfc3e127e1b7168952a844df39ecd34683752093/src/elements/Form.php#L1803) check that if the user has the "View forms" permission, they have access to all forms in the system. I'm not quite sure how that's not working on your end.

Do you get the same result impersonating the user locally?

**Comment by engram-design** [comment]
Closing due to lack of response.
