### ISSUE TITLE
Status column doesn't match the real status

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1086]
### Describe the bug

I can't use the `Status` column as it doesn't match the real default status of my submissions.

### Steps to reproduce

1. In `/admin/formie/settings/statuses`, set a `New` status with blue color and an `Accepted` status with green color
2. In `Form` > `Settings`, set `Default Status` to `New`
3. Add submissions to this form
4. In `/admin/formie/submissions/{handle}`, click `Customize` and add `Status`
5. Here, the `Status` column is shown with a green dot, which is equal to `Accepted` instead of a blue dot for `New`
6. When clicking a submission, we can see in the `Status` field (at the right aside column) that the value is `New` with blue dot

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Same issue as https://github.com/verbb/formie/issues/1049 and https://github.com/verbb/formie/issues/1075 ?

**Comment by romainpoirier** [comment]
Yes it is, sorry for the duplicate. I can confirm that `dev-craft-4 as 2.0.9` fix it.
