### ISSUE TITLE
OAuth error in Trello Integration

### ISSUE THREAD

**Issue by heymarkreeves** [verbb/formie#1088]
### Describe the bug

When I try to connect to Trello to enable that integration, I receive the following error. I believe Trello only supports OAuth1.

```
verbb\formie\integrations\miscellaneous\Trello::getOauthProvider(): Return value must be of type League\OAuth2\Client\Provider\AbstractProvider, League\OAuth1\Client\Server\Trello returned
```

### Steps to reproduce

1. Configure Trello integration as prescribed, using Developer API Key & Secret, and the Formie proxy URL.
2. Attempt to connect to Trello.

### Form settings

I have not configured a form yet.

### Craft CMS version

4.2.3

### Plugin version

2.0.10

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by heymarkreeves** [comment]
Thanks! That eliminated that error. Now when I connect and authorize the app in Trello, I'm redirected back to:

[dev site URL]/index.php?oauth_token=[token string]&oauth_verifier=[verifier string]

That shows my site's home page. When I go back to the Trello integration settings or attempt to use the Trello integration for a form, I'm not connected.

**Comment by engram-design** [comment]
Strange. The "Allowed Origin" is set correctly?

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1221575/190797874-d9fa4b52-96c4-4505-b9c2-ee2eec915835.png">

Note that Trello shows only the base URL, but it should be the full "Redirect URI" in the integration settings (eg `http://formie.test/actions/formie/integrations/callback`)

Can you also check your log files at `storage/logs/formie.log`?

**Comment by heymarkreeves** [comment]
I only see the following for Redirect URI, and it's a read-only field:

```
http://craft4.morins.test/index.php
```

My logs have a few entries that look like this:

```
2022-09-16 09:19:33 [ERROR] Trello Sales Pipeline: API error: “Call to a member function getMessage() on string” /Users/markreeves/Sites/morins/morins-craft4/craft/vendor/verbb/formie/src/base/Integration.php:118
2022-09-16 09:19:33 [INFO] Request context:
$_GET = [
    'p' => 'admin/actions/formie/integrations/form-settings'
    'v' => '1663345173926'
]
```

**Comment by engram-design** [comment]
Ah, I see the issue. It's because you have `usePathInfo = false` in your general config. Refer to [this thread](https://github.com/verbb/formie/issues/1003#issuecomment-1195464275) for more information, as some providers don't like the redirect URL containing a query string.

**Comment by engram-design** [comment]
I've also pushed a fix for this, so that the URL will now correctly work even with `usePathInfo = false`. Just run `composer update` again. I've also added a warning when this setting is set to `false` to prevent confusion.

I _believe_ there's no issue with using a query string in the Redirect URI for Trello, but a lot of other providers don't like this. As such, the only solution is to either `usePathInfo = true` or if that's not possible, setup a [custom route](https://github.com/verbb/formie/issues/1003#issuecomment-1226586058) on your site.

I'll also be looking to improve this in https://github.com/verbb/formie/issues/1092

**Comment by engram-design** [comment]
Fixed in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)

**Comment by heymarkreeves** [comment]
I'm getting the following now when I try to refresh the Boards and Lists lists. I deleted the value from `cache=''`, as it contains many references to my work across many boards and lists. I did note that some list titles have emoji characters in them.

```
Next yii\db\Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x93\xA5 I...' for column 'cache' at row 1
The SQL being executed was: UPDATE `craft_formie_integrations` SET `cache`='', `dateUpdated`='2022-09-19 13:54:22' WHERE `id`='2' at /Users/markreeves/Sites/morins/morins-craft4/craft/vendor/yiisoft/yii2/db/Schema.php:676)
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x93\\xA5 I...' for column 'cache' at row 1 at /Users/markreeves/Sites/morins/morins-craft4/craft/vendor/yiisoft/yii2/db/Command.php:1302)"} 
2022-09-19 13:54:22 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'admin/actions/formie/integrations/form-settings'
    'v' => '1663595647707'
]
```

**Comment by engram-design** [comment]
We didn't support saving emoji's for Trello boards or lists. Updated for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.12](https://github.com/verbb/formie/releases/tag/2.0.12)
