### ISSUE TITLE
Don't load default CSS

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/formie#1089]
### What are you trying to do?

It would be great if there would be the possibility to disable the default formie CSS.

### What's your proposed solution?

Is there a plan to add this option?

**Comment by engram-design** [comment]
You can achieve this by creating a custom [Form Template](https://verbb.io/craft-plugins/formie/docs/theming/template-overrides)
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1221575/190499001-e7211914-1906-4ca6-a093-ff2dc5923432.png">
