### ISSUE TITLE
Allow same email twice in Recipients dropdown field?

### ISSUE THREAD

**Issue by hassanmah** [verbb/formie#109]
**Description**
When I try adding a Recipients field with the type of Dropdown, I can't use the same email address twice, like in the screenshot. Is there any reason behind this? 

![image](https://user-images.githubusercontent.com/3025707/93607692-94e10280-f9c1-11ea-80cb-5ac19a49b08f.png)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.13
- Craft version: 3.5.10.1
- Multi-site: No

**Comment by engram-design** [comment]
Mostly because it's impossible to track which option they've picked, but it doesn't actually matter in the instance of this field - like it would in say a regular dropdown field.

Changed in [1.2.15](https://github.com/verbb/formie/releases/tag/1.2.15)
