### ISSUE TITLE
Disable exit alert

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/formie#1090]
### What are you trying to do?

From a UX point of view it can make sense to have an exit alert when people have filled something into the fields.

However, the exit alert always appears even if people have not left anything on the page. 

### What's your proposed solution?

It would be good if you could disable this behavior. As Option

### Additional context

<img width="291" alt="Bildschirmfoto 2022-09-15 um 17 16 10" src="https://user-images.githubusercontent.com/69263307/190442063-da87db97-c285-4f65-b8d8-ad1d00cc991e.png">

**Comment by engram-design** [comment]
You can disable this unload warning. [enableUnloadWarning](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) or Formie > Settings > Forms > Enable Unload Warning.
