### ISSUE TITLE
Submission export

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/formie#1093]
### Describe the bug

Exporting submissions does not work in my installation. I have made a video about this:

https://user-images.githubusercontent.com/69263307/191273243-3e54e77a-35aa-4161-ad95-df65eb4c7a4d.mov

### Steps to reproduce

Plugin Update.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.2.4

### Plugin version

2.0.11

### Multi-site?

No

**Comment by engram-design** [comment]
There is a known issue at the moment when exporting from "All submissions", because Craft can't handle querying multiple content tables in a single call (we're looking into it).

Can you confirm if this is still an issue when exporting by first selecting the form you want to export submissions for (in the left-hand sidebar), and then exporting?

**Comment by alexanderloewe** [comment]
Hello engram,

if we select a specific form, the export works as it seems. We will test it extensively and if there are still problems, I will contact you again.

Thanks for the support.

**Comment by engram-design** [comment]
Actually been able to come up with a solution to this. It's a tiny bit less performant, but it shouldn't be that noticeable. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.12](https://github.com/verbb/formie/releases/tag/2.0.12)

**Comment by alexanderloewe** [comment]
Hello, thanks, it works fine.

I have another request: Adding the option to export all fields with their handle name in the table cols.

**Comment by engram-design** [comment]
@alexanderloewe That would be covered in https://github.com/verbb/formie/issues/1030
