### ISSUE TITLE
Understanding Formie POST - Netlify 404

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#1094]
### Question

Hey there,

Maybe you can help me on this, I'm trying to understand how Formie works and where it is POSTing but first a little context.

I am caching my website to Netlify via Blitz. So I have my dynamic site hosted on cms.mysite.com and the static version deployed on mysite.netlify.app (on a primary mysite.com domain). I have a Formie form which I configured according to the caching doc and the CSRF tokens work fine. Netlify has a way to handle forms on their own which I'm not using and even deactivated in their settings, making sure I'm only using Formie here to handle the submissions.

When submitting the form via the dynamic site, everything works fine. When submitting the form via the static deployed version, Netlify throws me a 404. It feels like Netlify has some security in place for POST requests but I'm not sure about it. So I asked them about it and they are asking for more details about the way I'm posting the form to try to identify the issue.

Hence this support request. Can you help me understand exactly where Formie is posting when submitting either via page reload or via Ajax (both return a 404). Did you encounter this issue with other clients who are using Netlify by any chance? Am I missing something obvious here?

FWIW, the form is live on the dynamic site (I left it live for testing purposes) on covivance.frb.io (bottom of page) and the static version is live on covivance.eu (that's where the 404 occurs).

Any help would be much much appreciated.

**Comment by engram-design** [comment]
Formie will be submitting a POST request to the action endpoint `formie/submissions/submit` (see https://github.com/verbb/formie/blob/9aa5c262f547d3ad2b76000408e7e9be854bdda9/src/templates/_special/form-template/form.html#L45 and https://github.com/verbb/formie/blob/9aa5c262f547d3ad2b76000408e7e9be854bdda9/src/elements/Form.php#L1071)

Craft will translate that endpoint to `https://your-site.com/actions/formie/submissions/submit`.

I'm not exactly an expert with Netlify, but I'm surprised there are issues with others using it with Formie.

**Comment by JeanLucEsser** [comment]
Ok, thank you for this. I don't understand how I should make this work in the static version of the site.

How is the static site supposed to know what to do with an action of `formie/submissions/submit`? That should be sent to the dynamic version of the site hosted on another domain so that Craft can take it from there... this may be a stupid question but how am I supposed to do that?

I've opened a ticket with Netlify, I wonder if there's not an issue proxying a POST request to the dynamic site. I'll keep you posted if and when they reply. In the meantime if you have any suggestion ;)

**Comment by engram-design** [comment]
You shouldn't have to do anything. The `actionInput()` we use in templates will generate an action URL endpoint resolving to the Craft backend. Whether that's on a seperate domain (in your case) or on the same one - Craft sorts that out for you.

I might suggest enabling the `headlessMode` in Craft so that you can let Craft know it's a split system. This should help adding the proper URL to the CMS for things like this. Or use the `baseCpUrl` (see https://craftcms.com/knowledge-base/access-control-panel-from-alternate-domain)

**Comment by JeanLucEsser** [comment]
Well, even when using a baseCpUrl, the rendered form still has `<input type="hidden" name="action" value="formie/submissions/submit">` as the POST action. And still experiencing a 404.

I cannot enable headlessMode as that would mess with Blitz caching for now as it relies on templates.

Netlify: 

> Since your form submission endpoint is hosted elsewhere on CraftCMS, you need to send the form data using JavaScript to that endpoint.
I see that you have created an issue on the formie github page regarding the same issue.
At this point it would would be best to contact Formie for support.

**Comment by JeanLucEsser** [comment]
Hey Josh, I'm about to getting it to work, but it doesn't "just work" ;)

I'll report back after more tests, probably this WE, keeping the conversation opened for now.

**Comment by engram-design** [comment]
You're right about the `action` input, that indeed won't change.

One thing you can do is use the `action` attribute on the form to change which page the form is being posted to.

```twig
{{ craft.formie.renderForm(form, {
    themeConfig: {
        form: {
            attributes: {
                action: 'http://my-craft-install.test/',
            },
        },
    },
}) }}
```

So the POST data will be sent to `http://my-craft-install.test/` (obviously change that). My only real concern might be CSRF tokens, because this is a cross-site request.
