### ISSUE TITLE
When importing a new form with Recaptcha, mutations do not work directly

### ISSUE THREAD

**Issue by benediktblank** [verbb/formie#1095]
### Describe the bug

When you import a new, non-existing form with the Formie importer, that has Recaptcha already enabled, mutations on this form are not possible.
Only when you disable Recaptcha on the form, save the form, then enable Recaptcha on the form and save the form again, it starts working. Almost like the schema is not up to date or something like that.

Currently, since we are using Recaptcha, we have to do these steps after a deployment when there were new Forms included in the deployment.

I'm not sure what the underlying actual issue is in this case. Maybe you have an idea.

What I noticed is, that sometimes the form export has a "1" exported for Recaptcha and sometimes "true".
We have some form exports like this:
{\"recaptcha\":{\"enabled\":true,\"showAllPages\":\"\"},
And some are like this:
{\"recaptcha\":{\"enabled\":\"1\",\"showAllPages\":\"\"}

So the same field/option exported with two different values. But we are not sure, that it has anything to do with the issue reported.

I think that true/1 stuff has something to do with the way we export the forms. Because we've integrated the form import in our deployment, we've also built a form export console command that we run locally to update all of our form exports.

Basically it just calls the same two lines you are using in your ImportExportController:
```
$data = ImportExportHelper::generateFormExport($formElement);
$json = Json::encode($data, JSON_PRETTY_PRINT | JSON_NUMERIC_CHECK);
```

You have any idea why that would return "1" in the backend and "true" when called on console?

Here is a simple form with recaptcha enabled (with "1").
Make sure that recaptcha is enabled in your formie setup before importing that.
```
{
    "handle": "myform",
    "settings": "{\"displayFormTitle\":false,\"displayCurrentPageTitle\":false,\"displayPageTabs\":false,\"displayPageProgress\":false,\"scrollToTop\":true,\"progressPosition\":\"end\",\"defaultLabelPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"defaultInstructionsPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"submitMethod\":\"page-reload\",\"submitAction\":\"message\",\"submitActionTab\":null,\"submitActionUrl\":null,\"submitActionFormHide\":false,\"submitActionMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Submission saved.\\\"}]}]\",\"submitActionMessageTimeout\":null,\"submitActionMessagePosition\":\"top-form\",\"loadingIndicator\":null,\"loadingIndicatorText\":null,\"validationOnSubmit\":true,\"validationOnFocus\":false,\"errorMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Couldn\u2019t save submission due to errors.\\\"}]}]\",\"errorMessagePosition\":\"top-form\",\"requireUser\":false,\"requireUserMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"scheduleForm\":false,\"scheduleFormStart\":null,\"scheduleFormEnd\":null,\"scheduleFormPendingMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"scheduleFormExpiredMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"limitSubmissions\":false,\"limitSubmissionsNumber\":null,\"limitSubmissionsType\":\"total\",\"limitSubmissionsMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"integrations\":{\"recaptcha\":{\"enabled\":\"1\",\"showAllPages\":\"\"}},\"submissionTitleFormat\":\"{timestamp}\",\"collectIp\":false,\"collectUser\":false,\"dataRetention\":null,\"dataRetentionValue\":null,\"fileUploadsAction\":null,\"redirectUrl\":null,\"defaultEmailTemplateId\":null,\"disableCaptchas\":false}",
    "submitActionEntryId": null,
    "submitActionEntrySiteId": null,
    "defaultStatusId": 1,
    "dataRetention": "forever",
    "dataRetentionValue": null,
    "userDeletedAction": "retain",
    "fileUploadsAction": "retain",
    "fieldLayoutId": 1312,
    "title": "myform",
    "notifications": [],
    "pages": [
        {
            "settings": {
                "submitButtonLabel": "Submit",
                "backButtonLabel": "Back",
                "showBackButton": false,
                "saveButtonLabel": "Save",
                "showSaveButton": false,
                "saveButtonStyle": "link",
                "buttonsPosition": "left",
                "cssClasses": null,
                "containerAttributes": null,
                "inputAttributes": null,
                "enableNextButtonConditions": false,
                "nextButtonConditions": [],
                "enablePageConditions": false,
                "pageConditions": [],
                "enableJsEvents": false,
                "jsGtmEventOptions": []
            },
            "userCondition": null,
            "elementCondition": null,
            "label": "Page 1",
            "rows": [
                {
                    "fields": [
                        {
                            "label": "test",
                            "handle": "test",
                            "type": "verbb\\formie\\fields\\formfields\\SingleLineText",
                            "settings": {
                                "instructions": null,
                                "required": false,
                                "limit": false,
                                "limitType": "characters",
                                "limitAmount": null,
                                "matchField": null,
                                "placeholder": null,
                                "defaultValue": null,
                                "prePopulate": null,
                                "errorMessage": null,
                                "labelPosition": null,
                                "instructionsPosition": null,
                                "cssClasses": null,
                                "containerAttributes": null,
                                "inputAttributes": null,
                                "includeInEmail": true,
                                "enableConditions": false,
                                "conditions": null,
                                "enableContentEncryption": false,
                                "visibility": null,
                                "isNested": false
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

Mutation:
```
mutation save_myform_submssion($test: String) {
  save_myform_Submission(
    test: $test
  ) {
    test
  }
}
```

### Steps to reproduce

1. Import new non-existing form that has recaptcha enabled
2. Try to sent a mutation for that form with the recaptcha information
3. The mutations fails, it seems because it does not understand the recaptcha parameter
4. Go to the Craft backend, into the form.
5. Disable recaptcha, save the form
6. Enable recaptcha, save the form
7. Try to sent a mutation for that form with the recaptcha information
8. Works now

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.2.3

### Plugin version

dev-craft-4 as 2.0.10

### Multi-site?

No

**Comment by engram-design** [comment]
The `1/true` value shouldn't be an issue (just needs some typecasting) for consistency, but I can't replicate what you're seeing following your exact steps. The mutation works straight away without me doing anything (and yes, reCAPTCHA is enabled at the plugin and form level).

The submission is also submitted (albeit as spam, due to missing captcha information in the mutation).

What's the actual error message for the mutation?

Also, how are you importing forms as part of your deployment? Just manually by going to Formie > Settings > Import/Export?

**Comment by benediktblank** [comment]
Unfortunately I cannot give you the exact error message at the moment as nobody saved it when it happened.
I'll try to replicate the issue with a new form and report back with the error.

We've built a console command for importing the forms during deployment.
It's looping over a folder with all our json export files and imports them one by one.

The actual import part consists of this and it's mostly taken from  your ImportExportController.php:
  ```
  protected function _importFormFile(string $fileLocation): mixed
    {
        $json = Json::decode(file_get_contents($fileLocation));

        // Find an existing form with the same handle
        $existingForm = null;
        $formHandle = $json['handle'] ?? null;

        if ($formHandle) {
            $existingForm = Formie::$plugin->getForms()->getFormByHandle($formHandle);
        }

        if ($existingForm) {
            $formAction = 'update';
        } else {
            $formAction = 'create';
        }

        if ($formAction === 'update') {
            // Update the form (force)
            $form = ImportExportHelper::createFormFromImport($json, $existingForm);
        } else {
            // Create the form element, ready to go
            $form = ImportExportHelper::createFormFromImport($json);
        }

        if (! Formie::$plugin->getForms()->saveForm($form)) {
            return $form;
        }

        return true;
    }
```

Yesterday, we've noticed another thing now that might be related or the cause to this issue.

For about 2 weeks we had a Formie config in project.yaml that activated all the Captchas (not just Recaptcha, that we are using).
Every captcha was active in the global Formie config.

On already existing forms we still only imported the Recaptcha config from the import json as that json was created before all Captchas were active.

That led to the other Captchas (except Recaptcha) not being shown on the Form's Integration tab. That's also why we did not realize that all the Captchas were active globally.

Maybe that was the actual issue that required the resaving of the Form's Recaptcha config.

Now that we've noticed our project.yaml mistake, we've disabled all other Captchas in the project.yaml again and recreated all of our json exports.

I will report back when the issue occurs again and give you the actual error message.

**Comment by engram-design** [comment]
Sounds good, an interesting approach to deploying forms that I haven't seen before! 

Captchas do need to be enabled globally before they show in the form integration settings, but it seems strange that if you'd applied that in project config, they were't appearing. There need not be any form settings for captchas to get them to show (so you _can_ add settings for them!).

I'll keep playing around with things on my end.

**Comment by benediktblank** [comment]
> Sounds good, an interesting approach to deploying forms that I haven't seen before!

Yeah, we needed some automation to get the forms to all environments and devs without any sort of manual doing.
And we also wanted to have the forms in the repository for revisioning, so we wanted to rely on the Json exports for that.

> Captchas do need to be enabled globally before they show in the form integration settings, but it seems strange that if you'd applied that in project config, they were't appearing. There need not be any form settings for captchas to get them to show (so you _can_ add settings for them!).

Ah okay, so it does not matter if the captcha config is present in the json export for them to appear on the integration tab. That's good to know.
I hope there is no real issue and it was just a bit of config chaos on our end.
Should it re-appear now, I'll gather as much information as possible.

> I'll keep playing around with things on my end.

Thank you.

**Comment by engram-design** [comment]
> Ah okay, so it does not matter if the captcha config is present in the json export for them to appear on the integration tab. That's good to know.

Correct! Captchas (and other integrations) can have config data for the form, but they won't do anything unless both globally and per-form enabled.

**Comment by medoingthings** [comment]
I have an issue with importing forms as well – not sure if it’s the same as here though. I exported a form locally and tried to move it to production. But on import it threw this error:
`Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails`

**Comment by engram-design** [comment]
Are you able to send through the full stack trace of the error, which would show us the file and line number this occurs from? Difficult to pinpoint what field this might be. There should be this information in your `storage/logs/formie.log` file.

And, if you're able to post your exported form (or email through to `support@verbb.io`) that might help us replicate it.

**Comment by medoingthings** [comment]
Thanks for getting back to me so fast! I just sent you an email with the logs and more information.
