### ISSUE TITLE
Captcha::getOrSet always throws unnecessary warning in logs

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#1096]
### Describe the bug

On lines https://github.com/verbb/formie/blob/craft-3/src/base/Captcha.php#L139-L141 there's a check for false, but the method called returns void.

![image](https://user-images.githubusercontent.com/25124/192178759-626eca15-a0f2-4a45-ae94-9898aac6a056.png)

### Steps to reproduce

1. Create form with Duplicate protection
2. Request form in template

### Form settings

N/A

### Craft CMS version

Craft CMS 3.7.54

### Plugin version

1.6.12

### Multi-site?

NO

**Comment by leevigraham** [comment]
PR: https://github.com/verbb/formie/pull/1097

**Comment by engram-design** [comment]
Thanks @leevigraham good point on the return check

**Comment by leevigraham** [comment]
To easy… this change will actually clean up the web.log heaps as there's no warning thrown.
