### ISSUE TITLE
Failed to instantiate component or class "above-input"

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1098]
### Describe the bug

After migrating various Sprout Forms, I receive this error when trying to view the Formie form on the front end. If I resave the form via the Control Panel the error goes away, it possibly looks like it is related to the set form template.

```
Failed to instantiate component or class "above-input".
```

I am using a different form template which is set the in the `config/formie.php` and applied in project config, it is not customising the actual form template, but just preventing CSS being output, so the default theme isn't loaded and our main CSS are the only rules controlling the form styling.

If I create a new form from scratch the error is not present, but this defaults to the Formie theme.

Any ideas?

### Steps to reproduce

1. Migrate a Sprout Form
2. Change the form template
3. Observe error on front end when using a different form template

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes (but just prevent default CSS)

### Craft CMS version

3.7.55.2

### Plugin version

1.6.14

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
This might be related to the fact the templateId is not set, so I can potentially add some additional logic to set the templateId from the default to the one created with the project config data saved.

**Comment by engram-design** [comment]
Let me know if you need a hand with this (as you've closed it), but I can't see how the template would have an affect on this.  I'd need to see the full stack trace of the error, so that I could determine which field it's coming from, along with some details on your original Sprout form field being migrated.

Let me know!

**Comment by jamesmacwhite** [comment]
Thanks! I think it's possibly solved. What I think may have been happening is a combination of project config data and the template ID set not being set correctly.

I'll reopen if I can replicate it again. Its because at the moment I am doing multiple migrations tests from the live database from scratch with additional extra migrations running after. In these additional migrations I'm handling any project specific requirements.

One area I've noticed is ensuring the project config data gets applied early on, before the migrate sprout forms command is triggered.
