### ISSUE TITLE
Edit Error Message for each form

### ISSUE THREAD

**Issue by maximilian-schwarz** [verbb/formie#11]
### Description
I think it's really cool to edit the error message of a form similar to "Submission Message"?

### Steps to reproduce

1. Edit form
2. Click Behaviour
3. Textarea for editing "error message"

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.4.29

**Comment by engram-design** [comment]
For the moment, you can use [static translations](https://docs.craftcms.com/v3/static-translations.html) to change this text. We'll add it as a configurable option to forms.

**Comment by engram-design** [comment]
Added in [1.0.5](https://github.com/verbb/formie/releases/tag/1.0.5)
