### ISSUE TITLE
Using form submission data in an email template

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1101]
### Question

Coming from Sprout Forms, the submission data was exposed in an object variable so you can access the submitted form data in the email tempalte. In Formie it looks like this isn't the case, however it looks like you can do an element query to obtain the submission data.

I was wondering what the best approach would be in order to use submission data in an email template? 

Is this the right way:

```twig
{% set object = craft.formie.submissions().id(submission.id).one() %}
{{ object.field }}
```

I know there is `{{ contentHtml }}`, however I want to have a bespoke template just being able to reference certain data fields with the ability to use custom layout styling.

**Comment by engram-design** [comment]
You can do exactly the same thing in Formie. As the [docs](https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates#available-template-variables) state, you have access to a `submission` variable in your templates. You could then use `submission.myField`.

But, as each field will have a different type of value (array, string, int, etc), you might like to use our helper methods to output these as strings (`field.getValueAsString()`).

There's no need to re-fetch the submission like you're doing, as it's already available in your template.

There's a [user guide](https://verbb.io/craft-plugins/formie/user-guides/build-a-success-page-for-your-form) to help with some of the finer details of submission data.

**Comment by jamesmacwhite** [comment]
Thanks! What I think confused me slightly was when testing email templates with the preview, the submissions field weren't populated, but when a full email test was sent they were.

Perhaps it's a feature request for the preview mode to select the latest submission of the form being tested if possible. Sprout Forms did this, so it's more of a behaviour difference I think.

Sorry for the noise!

**Comment by engram-design** [comment]
Ah gotcha. So yes the preview generates a fake submission, populating it with fake data. Just because what happens when there's no submissions at all? So it _should've_ been showing some data in some form.

**Comment by jamesmacwhite** [comment]
I'll retest to confirm and get back to you, it did seem that certain submission fields weren't populated in the preview  but if I use the submission variable properly I'll double check that.
