### ISSUE TITLE
Freshworks CRM

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/formie#1102]
### What are you trying to do?

Hello everyone.

Dose Verbb plan to add Freshworks CMS as an Integration?

### What's your proposed solution?

Some Clients of ours had requested the Integration with Freshworks.

**Comment by engram-design** [comment]
We currently support [Freshsales CRM](https://www.freshworks.com/crm/login/) - or are you after a different product?

**Comment by engram-design** [comment]
Closing for now if you can provide clarification?
