### ISSUE TITLE
Submissions to Campaign Monitor fail if they contain checkboxes

### ISSUE THREAD

**Issue by nickcobley** [verbb/formie#111]
I have a simple form, with just three fields. A name, email and category field. The category field contains a number of checkboxes, with the intent being the user can check a number of checkboxes, then upon submit, these checkbox values will be sent to the Campaign Monitor API and populate a custom field that's set to "multiple choice - select many". The values stored in this field are identical to the form.

The problem I'm getting is when I submit the form, it throws the following error in the queue:

```
API error: “Client error: `POST https://api.createsend.com/api/v3.2/subscribers/******.json` resulted in a `400 Bad Request` response: {"Code":400,"Message":"Failed to deserialize your request.\r\nPlease check the documentation and try again.\r\nFields in (truncated...) ” /var/www/vhosts/****/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

I have simplified the values as a test, giving just one value of "Test" both in the form and in Campaign Monitor, but I get the same end result.

I get this error if I select a value, or if I don't check any values. Removing the field mapping in Formie, allows the submission to Campaign Monitor to succeed. 

**Steps to reproduce**
1. Create a form with checkboxes in Formie
2. Create a list with checkboxes that accept multiple values in Campaign Monitor
3. Map the fields in formie
4. Submit a form, check the queue for the error

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Ajax 
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.14
- Craft version: 3.5.8
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.2.15](https://github.com/verbb/formie/releases/tag/1.2.15)
