### ISSUE TITLE
Selecting a Root Category results in only the selected Category being displayed. (`descendantOf` vs `id`)

### ISSUE THREAD

**Issue by taylordaughtry** [verbb/formie#1111]
### Describe the bug

Hi! In Formie 1.6.13, selecting the Root Category for Categories fields seems to only display the Root Category itself, instead of its children. I believe it's related to [this](https://github.com/verbb/formie/commit/41670911b162c582280a4167e666ffe13c2f43bc) commit, where the criterion was changed from `descendantOf` to `id`. (Since it's using the root's ID, it makes sense that it's only returning the selected Root itself.)

The previous logic of `descendantOf` makes sense, but it doesn't accept an array. Since `getColumn` will always return an array of the matched keys, that's possibly the cause of the original issue. (I can't confirm that; don't see a GH issue that relates to that commit.)

Swapping back to `descendantOf` and changing the ArrayHelper method used addresses the issue locally. 

If this all sounds above-board to you, here's a PR to actually make the below change:
https://github.com/verbb/formie/pull/1112

```diff
// Handle the two ways a default value can be set
if ($this->rootCategory instanceof ElementQueryInterface) {
    $ids = $this->rootCategory->id;
} else {
-    $ids = ArrayHelper::getColumn($this->rootCategory, 'id');
+    $ids = ArrayHelper::getValue($this->rootCategory, '0.id');
}

if ($ids) {
-    $query->id($ids);
+    $query->descendantOf($ids);
}
```

### Steps to reproduce

1. Add a Categories field with a Root Category selected.
2. On the frontend, you'll see only the Root Category displayed in the field's options.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.54

### Plugin version

1.6.13

### Multi-site?

Yes

**Comment by taylordaughtry** [comment]
@engram-design If the above seems above-board to you, I've created a PR here for you:
https://github.com/taylordaughtry/formie/pull/1

**Comment by engram-design** [comment]
Thanks for this, and I think you might be right. If you want to submit your PR to this repository, I can accept that.

**Comment by taylordaughtry** [comment]
Ah! Sorry about that; didn't catch I'd opened it against my local repo's branch. Just reopened it here against your upstream:
https://github.com/verbb/formie/pull/1112

**Comment by engram-design** [comment]
Thanks! Here's hoping this doesn't break the fix that I did initially (I too can't recall why I made the "fix")

**Comment by taylordaughtry** [comment]
@engram-design No problem at all! When do you think this'll make it into a release?
