### ISSUE TITLE
Migrating a portion of existing Sprout Forms, submissions and notifications

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1114]
### Question

I'm looking to migrate Sprout Forms, Submissions and Notification data, but only from a specific date period i.e. not all data after a certain point.

My first thought was to delete the Sprout Forms data not needed prior to running the migration, but potentially we might want to keep it around for old links and email notifications to work temporarily until we remove Sprout Forms entirely.

My next thought was to call the MigrateSproutForms migration in my own content migration and pass in the required IDs from a Sprout Forms element query with a dateCreated criteria, which would also likely work and possibly be the better option, however, I'd want to potentially have the `$this->_consoleRequest` work so it outputs the console messages. Is there a way I can pass this in a content migration to make sure it outputs the console messages, when called from a content migration `$this` from a content migration won't be a console object.

Or I could just trigger the same console command logic being done in the controller in my own module with any amended element query potentially.

I don't know if you'd have any use case of allowing the native console command to pass specific IDs, rather than just the form handle?

**Comment by engram-design** [comment]
The only real issue is that the submissions query isn't really accessible or configurable at the moment (and probably no plans to, unless you want to submit a PR). But as for `_consoleRequest` you only really need to set that if you're indeed running it from a console controller (see how we [do that](https://github.com/verbb/formie/blob/560319ca303d897aef94e24fce0b7a1973ec9c85/src/console/controllers/MigrateController.php#L62))

**Comment by jamesmacwhite** [comment]
Thanks! Would the best solution be essentially to copy the existing console controller logic here:

https://github.com/verbb/formie/blob/560319ca303d897aef94e24fce0b7a1973ec9c85/src/console/controllers/MigrateController.php#L48-L67

But with a modified formIds element query and then just call that in a content migration with runAction?

```php
public function actionMigrateSproutForms(): int
    {
        $formIds = SproutFormsForm::find()
            ->dateCreated('custom date range query')
            ->ids();

        foreach ($formIds as $formId) {
            $this->stderr('Migrating Sprout Forms form #' . $formId . PHP_EOL, Console::FG_GREEN);

            $migration = new MigrateSproutForms(['formId' => $formId]);
            $migration->setConsoleRequest($this);
            $migration->up();
        }

        return ExitCode::OK;
    }
```

**Comment by engram-design** [comment]
Yep, but that'll still migrate all notifications and entries (submissions) from Sprout, regardless of date range? It'll just only migrate the forms for the given range.

**Comment by jamesmacwhite** [comment]
Ah, sorry, I understand your point now because it's just a element query on forms it wouldn't restrict to submissions or notifications and they would get migrated regardless.

OK. I could just let Formie migrate everything and then rely on garbage collection to do the removal later potentially.
