### ISSUE TITLE
Add link to form's Submission in the edit view of a form

### ISSUE THREAD

**Issue by HannahDeWachter** [verbb/formie#1121]
### What are you trying to do?

In the edit view of a Form, I would like to add a link to the form's submissions. This would mean a link to: /admin/formie/submissions/{form.handle}.

### What's your proposed solution?

There are two options:
- You add this link functionality
- You provide a hook in the edit template, so I can add this link myself.

**Comment by engram-design** [comment]
Not a bad idea, now just to think where to put this link 🤔

**Comment by HannahDeWachter** [comment]
Hi @engram-design, is there news on this? :)

**Comment by engram-design** [comment]
Nothing yet, I haven't really figured out a great place to put it in the form builder that it's too glaring, works with permissions people have setup, and is in the appropriate place. But I think a good area for it is next to the save button.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by HannahDeWachter** [comment]
Hi @engram-design,
The button next to the Save button looks great! However, it links to the wrong submissions form. For example: I open the form "Test Antwerpen", click on "View Submissions" and it goes to the submissions of "Test Brussel". I also tested it with an other form and it also goes to the submissions of "Test Brussel".
Could you take another look at this please?

**Comment by engram-design** [comment]
Updated now, run `composer update` again.

**Comment by engram-design** [comment]
Added in [2.0.14](https://github.com/verbb/formie/releases/tag/2.0.14)

**Comment by HannahDeWachter** [comment]
Thank you!
