### ISSUE TITLE
Submissions stay incomplete whereas they are completed

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1124]
### Describe the bug

I have a few entries that stays Incomplete for no reason.
They are completed, as they don't have any required field (outside condition) which is empty on save. And with that, I don't get any error or any change on resave (on front-end, back-end, and CLI using `resave/formie-submissions`).
Is there any possibility to force the fix of these submissions from the database? Changing the value of the `isIncomplete` column doesn't seem to work, and I also tried to empty the snapshot column, but without any change.

### Steps to reproduce

1. Get an `Incomplete` submission for an unknown reason
2. Try to resave it change its state

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.45.2

### Plugin version

1.5.16

### Multi-site?

Yes

**Comment by engram-design** [comment]
That sounds quite strange. The `isIncomplete` column is the only reference to that, and changing that is the only place we set the incomplete state to true/false.

Is there maybe some form of caching involved? Might be worth clearing the data (and other) Craft caches.

But otherwise - there's no other place we determine if the submission is incomplete, other than that column!

**Comment by romainpoirier** [comment]
> That sounds quite strange. The isIncomplete column is the only reference to that, and changing that is the only place we set the incomplete state to true/false.

Thank you. Based on your answer, I tried this time directly in the Production env (instead of a replicate), and this time that worked. The caches are emptied regularly, so I can't confirm if this could be linked.

However, I still haven't figured out why these complete submissions were staying as `Incomplete`.

**Comment by engram-design** [comment]
Hmmm, I couldn't say without further looking into your setup. Granted, there's not a way in the control panel to change an incomplete submission to a completed one, and maybe there should be.

**Comment by romainpoirier** [comment]
Ok, thank you. As I'm not figuring out what had caused it and how to reproduce it (as it's not constant), I can provide you the information you would need to investigate, but it should be also hard for you to find what/how... Let me know if you would like to investigate. If not, I propose to pause this ticket until I potentially get more information later.

**Comment by jan-dh** [comment]
I'm experiencing something similar. I exported the incomplete submission as CSV & when I open the file, all fields are filled in, however the submission stays marked as incompleted. Can provide the CSV if you want.

**Comment by engram-design** [comment]
Having all the fields filled in for a submission isn't an indicator that the submission is complete. Especially if the user hits a validation issue at the final step with all the fields populated. Or, with the ability to save a for submission and continue later - that could've happened. It's difficult to say without looking at your form (not just the completed submission data)

**Comment by jan-dh** [comment]
I filled in the submission all the way through and didn't run into some hickup. The `isspam` field is also empty. Anywhere I could find the reason for it to not be marked as completed?

**Comment by engram-design** [comment]
Is it just a single submission, or is it a consistent issue? So long as you get to the last page in a form and submit it, it will complete the submission. There's not really a way to tell why it wasn't marked as completed, as I've mentioned it could be a few reasons, from validation, or another error.

If it's a consistent issue, send through a support request (Formie > Settings > Get Support) and we can see if there's anything obvious with the form, and if we can recreate it on our end.

**Comment by engram-design** [comment]
Closing due to lack of response.
