### ISSUE TITLE
Allow pruning of submissions and notifications to be sent as a queue job

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1126]
### What are you trying to do?

For the existing pruning routines for submissions and notifications, it would be great if these could be executed as a queue job for offloading, particularly when running the CLI command is long running.

### What's your proposed solution?

Provide a queue job interface for pruning routines.

**Comment by engram-design** [comment]
Are you referring to the [garbage collection tasks](https://github.com/verbb/formie/blob/0c12515e9070fd8c774da8cebb4b04e3212007a0/src/Formie.php#L315-L333)? And you just want to run these via a queue job?

We're never going to probably run these via a queue job, so I'd almost recommend that these be created in a module for your site (as your module is going to be the only thing calling it - Formie won't). Which just saves us having to create multiple queue job classes (although they'll be extremely simple)

**Comment by jamesmacwhite** [comment]
Yes, the GC routines which are in the service classes of Submissions and SentNotifications.

Funnily enough I've just done that myself added two queue job in a module using the logic in the service classes. The reason why I wanted to queue them is because from a large migration running them via CLI is slower, compared to off loading to a queue using Redis.

I'll make some minor tweaks so progress is tracked along with the correct label for each form when cleaning submissions.
