### ISSUE TITLE
Add form title as a data attribute to form template or form data config

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1127]
### What are you trying to do?

Would it be possible to include the form title as a data attribute on the default form template, either as a data attribute or added to the data config value. The ID and handle is available through the data config but the form title doesn't appear to be and that would be useful for tracking potentially?

Testing the `_special/form-template/form.html` template it appears `form.title` is available, so it could be added if deemed acceptable?

### What's your proposed solution?

Adding form.title as a data attribute to the default form template.

### Additional context

Formie 1.6.14

**Comment by jamesmacwhite** [comment]
Or alternative, I could pass it via the renderForm options, but just wondered if it was something that could be added to the main form template.

**Comment by engram-design** [comment]
I don't _think_ there would be any issue with adding this, apart from maybe privacy reasons. Maybe editors name their form "New Enquiries - USE THIS" or something (which I have certainly seen editors use), which is useful for their admin usage, but not so much for on the front-end. It wouldn't be great showing that, but granted that's for the segment of people who know how to look at source code.

This is trivial to do yourself with theme config ([Formie 2](https://verbb.io/craft-plugins/formie/docs/theming/theme-config)):

```
{{ craft.formie.renderForm('contactForm', {
    themeConfig: {
        form: {
            attributes: {
                'data-title': form.title,
            },
        },
    },
}) }}
```

But you can also do this in [Formie 1](https://verbb.io/craft-plugins/formie/docs/v1/template-guides/rendering-options):

```
{{ craft.formie.renderForm('contactForm', {
    formAttributes: {
        'data-title': form.title,
    },
}) }}
```

**Comment by jamesmacwhite** [comment]
Thanks! I didn't think about internal type title values, so maybe sticking with the renderForm approach.

I've confirmed it works on Formie v1, with a custom data attribute, so that's fine thanks!
