### ISSUE TITLE
Tab Usage

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#1148]
### What are you trying to do?

Its OK.  to have info where form is used 

But now i have about 300+ rows on taht page 
drafts revisons.   and entries that dont exist anymore.. 

let say 250 dont exist anymore..

### What's your proposed solution?

Option to show just Live entries..  where form is..
**or to clean at least.. to clean non exiisting. one..**

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.14](https://github.com/verbb/formie/releases/tag/2.0.14)
