### ISSUE TITLE
[Craft 4.3.1 & dev-craft-4] Cannot add integrations: getIntegrationById(): Argument #1 ($integrationId) must be of type int, null given

### ISSUE THREAD

**Issue by Maybach91** [verbb/formie#1150]
### Describe the bug

I want to add any integration, but getting the following error on save:

```php
verbb\formie\services\Integrations::getIntegrationById(): Argument #1 ($integrationId) must be of type int, null given, called in /vendor/verbb/formie/src/services/Integrations.php on line 400
```

I just downloaded a different project config and wanted the apply this.

### Steps to reproduce

1. Install Formie
2. Try to add any integration (email, crm)
3. Hit save

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Te	mplates: No

### Craft CMS version

4.3.1

### Plugin version

dev-craft-4 as 2.0.13

### Multi-site?

Yes

### Additional context

Used [craft-copy](https://github.com/fortrabbit/craft-copy) to get the Database from the remote server and wanted to check, if the field etc. are still there. But they are gone and i cannot add any new integration.

I upgraded Craft CMS from `4.2.8` to `4.3.1`. But reverting to `4.2.8` did not solve the issue.

## Edit:

Using `^2.0` of formie is working. `composer require verbb/formie`
Using the `dev-craft-4 as 2.0.13` version is **not** working. With Craft `4.3.1`.

**Comment by engram-design** [comment]
Fixed in [2.0.14](https://github.com/verbb/formie/releases/tag/2.0.14)
