### ISSUE TITLE
Summary field translation.. 

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#1155]
### What are you trying to do?

Can you add in summary field option to this translate/change this message.. 

![Snag_6e6bfb8](https://user-images.githubusercontent.com/76176291/198879130-5e882e4a-f419-4eef-b70a-419d9ce32771.png)

### What's your proposed solution?

---

**Comment by engram-design** [comment]
You can override this with Theme Config at the moment:

```
{{ craft.formie.renderForm('contactForm', {
    themeConfig: {
        summary: {
            fieldSummaryHeading: {
                attributes: {
                    text: 'Override text',
                },
            },
        },
    },
}) }}

```

**Comment by wmdhosting** [comment]
i think better to remove that text completly. if there will be no way to  change it in admin

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
