### ISSUE TITLE
Salesforce Refresh Token is missing

### ISSUE THREAD

**Issue by martinherweg** [verbb/formie#1159]
### Describe the bug

A few hours after connecting to a salesforce app (refresh token etc. is enabled there) when I try to Refresh the Integration I get this error message:

```
AxiosError: Request failed with status code 500
API error: “Required parameter not passed: "refresh_token"”
```

### Steps to reproduce

1. Connect Salesforce App
2. wait a few hours - a day
3. Try to refresh Integration

### Form settings

Salesforce Settings
Sandbox: true
Use Credentials: true
Client Secret, Client ID, username and password provided

### Craft CMS version

4.3.1

### Plugin version

2.0.14

### Multi-site?

Yes

**Comment by engram-design** [comment]
This would be when you go to the Formie > Settings > CRM > Salesforce settings, correct? Not when refreshing the integration from the Form Integrations pane?

Are you able to have a look at your `formie_tokens` database table, and find the row(s) where `type == 'verbb\formie\integrations\crm\Salesforce'`? If there are multiple, pick the latest in the list. Can you confirm if the `refreshToken` has a value?

It does look like this is probably related to using "Use Credentials", which creates a different type of OAuth grant to usual.

**Comment by martinherweg** [comment]
@engram-design No it's when refreshing from the form integrations panel.

There are two rows with type of Salesforce and both `refreshToken` columns are null.

I've set useCredentials to false and now the last item in the list has a refreshToken value.

I have two Salesforce integrations though, one for a sandbox and one without, should both rows have a `refreshToken` now?

**Comment by engram-design** [comment]
@martinherweg Yep, sounds like the `refreshToken` isn't being stored when enabling `useCredentials`, and both rows should have a refresh token. I'll do some testing with the sandbox endpoint as well, as sounds like your first integration has `useCredentials` disabled, but `sandbox` enabled with no `refreshToken`?

**Comment by martinherweg** [comment]
@engram-design Yeah I was sure both integrations use the same env variables, figured out they don't so issue seems to be fixed on our end when disabling `useCredentials`

**Comment by engram-design** [comment]
Thanks for confirming! Will keep open for the moment to investigate `useCredentials`
