### ISSUE TITLE
Form submissions via GraphQL mutation don't trigger notification

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#116]
**Description**
When I create a submission via a typical front-end form (e.g. `{{ craft.formie.renderForm('contactForm') }}` ) , the notification is sent correctly, but when the submission is via GraphQL mutation, the notification is never sent. I've confirmed the submission is successfully received and saved in the database.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.14
- Craft version: 3.5.10.1
- Multi-site: No

**Comment by grndctrl** [comment]
Same for me, I'm trying to submit a form through NextJS, on a different domein. The submission is saved nicely as a new entry, but I receive no notification of it. In CraftCMS there are no pending jobs in the Queue manager either.
Plugin version: 1.2.14
Craft version: 3.5.11.1

**Comment by engram-design** [comment]
Should be fixed in [1.2.15](https://github.com/verbb/formie/releases/tag/1.2.15).

**Comment by grndctrl** [comment]
Can confirm, it's working now. Thanks for the quick response!
