### ISSUE TITLE
Page variable not available in theme config context

### ISSUE THREAD

**Issue by chasegiunta** [verbb/formie#1163]
### Describe the bug

Seems that all the other variables (at least that I've tested) seem to work fine, but the `page` variable when used in a theme config (either in a `formie.php` config file, or directly referenced in as a `renderForm()` option) will throw a `Variable "page" does not exist` error.

This, of course, does not happen when only a single page exists.

### Steps to reproduce

1. Create a multi-page form.
2. Try to render anything in your themeConfig dependent on the `page` variable, for example: https://github.com/verbb/formie-theme-configs/blob/c09d01811d30c5a5b4bd4e2540f8ea1a96dddcb7/tailwind/index.html#L77

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.1

### Plugin version

2.0.16

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by chasegiunta** [comment]
tested, working. thanks!
