### ISSUE TITLE
Unable to save draft on front-end

### ISSUE THREAD

**Issue by seantimlin** [verbb/formie#1166]
### Describe the bug

When I try to save a draft on the front end I get a 500 submission error.

This is the error more specifically.
{"name":"Exception","message":"craft\\helpers\\Db::batchInsert(): Argument #4 ($db) must be of type ?craft\\db\\Connection, bool given, called in ../vendor/verbb/formie/src/services/Relations.php on line 88"

I can fix the issue by changing this line of code on formie/src/services/Relations.php:88
`Db::batchInsert('{{%formie_relations}}', ['type', 'sourceId', 'sourceSiteId', 'targetId'], $values, true);`

To:
`Db::batchInsert('{{%formie_relations}}', ['type', 'sourceId', 'sourceSiteId', 'targetId'], $values, $db);`

### Steps to reproduce

1. Create a form with save draft enabled
2. Click save draft

### Form settings

Multi-page form: No
Submission Method: Ajax
Client-side Validation: Yes
Custom Form Templates: No

### Craft CMS version

4.3.1

### Plugin version

2.0.16

### Multi-site?

No

### Additional context

I have recently upgraded craft version 3 to 4.

**Comment by engram-design** [comment]
Fixed in [2.0.17](https://github.com/verbb/formie/releases/tag/2.0.17)
