### ISSUE TITLE
descriptionHtml field missing on graphql Agree Field inline fragment

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/formie#1168]
### Describe the bug

Hi,

I am using formie in a headless setup and trying to query the descriptionHtml field on the Agree inline fragment. It is documented in the documentation but is missing in the inline fragment.

### Steps to reproduce

1. Make a form with an agree field
2. Query the form with the Agree field and descriptionHtml.

### Form settings

Headless

### Craft CMS version

4.3.1

### Plugin version

2.0.16

**Comment by engram-design** [comment]
Fixed in [2.0.17](https://github.com/verbb/formie/releases/tag/2.0.17)
