### ISSUE TITLE
Google reCaptcha not working

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#117]
I tried all 3 reCaptcha styles: 
v3: no forms are submitted and spam is not saved to the database (setting is on)
v2 invisible: no forms are submitted and spam is not saved to the database (setting is on)
v2 checkbox: checkbox disappears when form is submitted with invalid content. No forms are submitted and spam is not saved to the database (setting is on).

So I can't get it to work in any way :(
ReCaptcha has troubled me before (especially the v3) but the v2 always worked with other plugins though.

**Comment by engram-design** [comment]
Can you provide some more detail?
- Are you using custom templates
- Are you using any template overrides
- Is this a multi-page form?
- Are there any JS errors when you load the page

To be clear, for all options, does the captcha appear? V3 should be bottom-right, V2 invisible should be inline or bottom-right (there's a setting for placement), and checkbox inline.

**Comment by TomDeSmet** [comment]
- I'm using a custom template to override the agree field only.
- It's a single page form.

**ReCaptcha v2 checkbox:**
- Sometimes I see it, most of the time the placeholder is there, but the captcha is not. When it's there, I can submit the form without it giving an error but the form is not saved to the database. Not even as spam.
- JS error: `Uncaught (in promise) Timeout`

**ReCaptcha v2 invisible:**
- No label can be seen, not when set to inline nor left or right.
- Javascript file is being loaded.
- JS error: `Uncaught (in promise) Timeout`
- No forms are submitted.

**ReCaptcha v3:**
- The label on the bottom right appears.
- No JS error
- No forms are submitted.

I have had the timeout error with Sprout forms too and I think it is a Google bug because I can find a lot of requests but no solution on many forums.
But I never had it not working with the simple v2 option...

**Comment by engram-design** [comment]
Hmmm, wonder if you might have an adblocker or anything installed? I'll look into it a bit further, but my local tests are passing for all the captchas.

**Comment by TomDeSmet** [comment]
I do have an ad-blocker installed. I'll disabled it and test it again. Didn't think that could interfere with it.

**Comment by engram-design** [comment]
Hard to say without looking at the full error in JS. Are you able to shoot through a screenshot of your web console? Just interested in the script throwing the error, line number, function call, etc

**Comment by TomDeSmet** [comment]
It didn't give any info except the message :(
But I'll try without ad blocker and will try different browsers too to see if I can gather any more info.

**Comment by TomDeSmet** [comment]
My ad-blocker doesn't interfere with anything I've noticed.
I started testing on the development server and I noticed that I got the ReCaptcha v2 invisible label working, but only on http. For some reason, when going through https the label dissapears and no recaptcha is shown...

The plot thickens.

**Comment by engram-design** [comment]
Hmm, I'm just testing locally and http/https doesn't seem to make a difference - it probably shouldn't.

So just to start with - the V2 checkbox appears, and you can tick it all okay - correct?

**Comment by engram-design** [comment]
Also, are you using Formie's JS, and if so, the base and the theme? It'd also really help to see that JS error in some form. If there's a fatal JS error, it most likely won't get saved properly, even as a spam submission.

I should also ask, anything in `storage/logs/formie`?

**Comment by engram-design** [comment]
Also, you took out the issue template suggestions, but I'd like to confirm what version of Formie you're on. I will assume its the latest.

**Comment by TomDeSmet** [comment]
I'm using Formie's JS, base as well as theme.
I'm using Formie 1.2.14 with Craft 3.5.11.1 so all up-to-date.

Where I'm currently at (testing only on a live server now, not locally as I'm not able to get that working):

**ReCaptcha v2 invisible:**
- I'm able to get the label to show on http. Doesn't show on https.

_Will edit this while testing._

**Comment by engram-design** [comment]
Alrighty, so submitting the form with v2 invisible on http - does that work all okay? On https where it doesn't show, any JS errors? There should be a `formie-recaptcha-placeholder` div in the source HTML of the page, where the captcha is supposed to be loaded into.

By the way, if you're on the Craft discord, feel free to reach out to me (crawf) if that's quicker?

**Comment by engram-design** [comment]
This was due to using async modules with Vue as documented [here](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#async-modules). The provided solution fixed the issue.
