### ISSUE TITLE
Heading fields are translated in site instead of formie category

### ISSUE THREAD

**Issue by MaartenWaegeman** [verbb/formie#1174]
### Describe the bug

The translation strings for heading elements are translatable, but they are not added to the formie category, but to site.

![image](https://user-images.githubusercontent.com/7084691/201977240-a950171d-5c5a-4bc1-ab31-a4474592b8a8.png)

![image](https://user-images.githubusercontent.com/7084691/201977841-6b694c2e-2142-4136-af85-062528a53aea.png)

### Steps to reproduce

1. Create a header element
2. Try to find the element in a translation plugin under the formie category

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.3.1

### Plugin version

2.0.17

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.17",
  "...": "..."
}
```

Then run `composer update`.

**Comment by MaartenWaegeman** [comment]
Super thanks!
