### ISSUE TITLE
Ability to set the email notification content from Twig templates

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1178]

**Comment by JeffreyBenusa** [comment]
More specifically - the ability to update the email notification's Send To on per entry level.

**Comment by engram-design** [comment]
That could be achieved by using a Hidden field, settings it's Visibility to "Hidden" (so that it's not rendered on the front-end), then using the [population](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) to populate the hidden field with your value, then using that field in the "Set To" setting for a notification.

**Comment by engram-design** [comment]
We'll probably employ something similar to submission snapshots, where you can store this override settings for notifications.

However, in order to do that, we'll need to implement https://github.com/verbb/formie/issues/1048 so we've got a good way to reference a notification, rather than via their ID, which would be pretty tricky.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
