### ISSUE TITLE
Add the ability to drag an existing field to another group

### ISSUE THREAD

**Issue by uandco** [verbb/formie#1182]
### What are you trying to do?

Move a field that has already been put in a form, or another group, to a new group.

### What's your proposed solution?

Allow existing fields to be dragged to new or other groups.

### Additional context

Our forms rely on groups to ensure there's at least one fieldset in the form. If authors start creating the form without a group, they need to start the fields from scratch as they can't be moved into a new group.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
