### ISSUE TITLE
Phone Number - Add country/international validation

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#119]

**Comment by lexislav** [comment]
Maybe adding pattern in field setting for entering custom regex would be good enough… at least untill some more sofisticated solution comes out?

`<input type="tel" pattern="{regex entered trought field admin}">`

**Comment by engram-design** [comment]
@lexislav You should be able to achieve that as-is right now using input attributes https://d.pr/i/PLrEza

This in particular is for more robust handling that's client-friendly.

**Comment by lexislav** [comment]
> @lexislav You should be able to achieve that as-is right now using input attributes https://d.pr/i/PLrEza

Thanks, would take me another year to find out by my own :-/

Then the more user-friendly solution can wait :-)

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
