### ISSUE TITLE
Microsoft Dynamics 365 refresh integration memory exhaustion 

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1194]
### Describe the bug

When running the refresh integration action on Microsoft Dynamics 365, on our staging environment with 2x 256 MB PHP node scaling, the action cannot run due to:

```
Error: Request failed with status code 500
Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)
```

It would appear the memory allocation required for the action is beyond 256 MB. While this isn't major as our dev environment is 1 GB and production 512 MB. However if there's any potential optimisation opportunities for the requests made by the action.

It might be tricky due to the amount of data being returned by a Dynamics 365 CRM environment being varied and larger than others, but I don't know if there's anything that can be optimised within Formie to help reduce the memory allocation needed? Or alternatively if the refresh integration action was offloaded as a console request rather than a web request to avoid this.

### Steps to reproduce

1. Run refresh integration action with PHP 256MB scaling
2. Observe memory exhausted error

### Form settings

N/A

### Craft CMS version

3.7.61

### Plugin version

1.6.19 (dev-craft-3)

### Multi-site?

No

### Additional context

No

**Comment by engram-design** [comment]
I think our other issue https://github.com/verbb/formie/issues/1170 was the main culprit with too much data being returned. I have made a [tiny](https://github.com/verbb/formie/commit/4c1edc8a79a481c45fd6f93c4b0946932f3fe226) improvement.

What objects are you mapping to?

We do have plans to improve handling for only fetching data for the enabled objects, but that's a little ways off yet, and for Craft 4.

We also can't feasibly use a console command or queue job to refresh the integration, as not all installs have CLI access. There'a also not a great mechanism at the moment to know when a queue job has been processed.

**Comment by jamesmacwhite** [comment]
Thanks. This is running with the additional fix in #1170 in place. It's mostly around a memory allocation required by the looks it, our staging environment with reduced scaling due to less load flags the issue. However, I'm aware it's also potentially around the amount of entities and data being returned.

In my case, I've just been testing the being able to have entities being mappable, but I'm not actually toggling any of the mapping options as on.

Perhaps the toggle switches for mapping between entities can determine what requests run, at the moment it seems the refresh integration action might be requesting all the entities available in Formie, regardless if they are enabled or not?

**Comment by engram-design** [comment]
Definitely hard to say without seeing a "real" account with data, but I'm surprised there's a memory issue, particular if not on local. How long does refreshing take locally?

> Perhaps the toggle switches for mapping between entities can determine what requests run, at the moment it seems the refresh integration action might be requesting all the entities available in Formie, regardless if they are enabled or not?

That's what I mentioned as something on the cards. However, it's not a quick-fix, as we need to refactor the integrations settings interface to include sending the lightswitch values for enabling objects, as currently they aren't. It'd be bad UX to have to save the form for these settings to be picked up.

This would almost certainly assist with the issue.

**Comment by jamesmacwhite** [comment]
Locally running a refresh integration action is taking around 1 minute and 20 seconds, with a bit of variance.

I think that's partly because of entities like Contact, Lead are quite larger. For #1170. The full request for all data on the contact entities for 5000 records was 88 MB, I'd imagine that still means there's a large amount of entities to be returned.

If you want me to provide more detailed data to help, let me know. I can even speak with our CRM developer to provide access to a Dynamics 365 CRM system, if I can get it cleared, or I can share JSON data responses to calculate the average size?

**Comment by engram-design** [comment]
Yeah, that's way, way too long. We do limit responses back for entities to the [first 100](https://github.com/verbb/formie/blob/fff55845c1a2fa7865590ab668edee0f962bd793/src/integrations/crm/MicrosoftDynamics365.php#L583). Might be worth changing that to like 10, to see if that's a drastic improvement? These entity results are cached across multiple objects, so they should only be called once. But it will try and fetch all fields for each entity object.

If I can gain access, that'd be swell. Happy to chat further on Discord `@crawf`.

**Comment by jamesmacwhite** [comment]
It is, but technically doesn't need to be run too much so it's acceptable for the sake of it working and it does complete on our production environment and our dev and staging both point to the test Dynamics 365 CRM environment.

Would a potential interim solution be to allow the limit to be set in the integration settings? I'll give the refresh integration a test with setting the limit as 10 and see if has a major impact.

**Comment by jamesmacwhite** [comment]
Just for reference, setting the limit to 10, took around 50 seconds, so certainly an improvement around 40% quicker, maybe setting that as the limit generally is an option for all to benefit, in theory the entities would be the same per record? Not sure you could have a situation where record 1 compared to record 2 under the same entity wouldn't have the same fields. They might not have the same data, but the field would still exist as a reference.

**Comment by engram-design** [comment]
Let me investigate if bulk-querying is supported, as that's still not really an acceptable time for me!

**Comment by jamesmacwhite** [comment]
Thanks! There is possibly some areas that make this per CRM environment. Our contact and lead entity may have more custom fields than others, so that's possibly a factor too.

I can do some benchmarking with the API requests if it helps to know what request size and response time we are dealing with, with all entities broken down?

**Comment by jamesmacwhite** [comment]
Recent improvements help with this.
