### ISSUE TITLE
Unable to set up multi-step form using the Craft Forms templating guide

### ISSUE THREAD

**Issue by jan-dh** [verbb/formie#1197]
### Describe the bug

So I've been trying to set up a custom rendering of a form in order to be able to get a custom progress bar & add the form results in the url to my redirect url (this info is just for context).

I'm trying this examples:
```
<form method="post" accept-charset="UTF-8" enctype="multipart/form-data" data-fui-form="{{ form.configJson }}">
    {{ csrfInput() }}
    {{ craft.formie.renderPage(form, null, {
          fieldNamespace: '',
      }) }}
  </form>
```
  
from the docs: https://verbb.io/craft-plugins/formie/docs/template-guides/craft-forms

After each submit I get the error:
```
Unable to parse response `SyntaxError: Unexpected token '<', "
Couldn’t save submission due to errors.
```
  
I found a related previous issue: #747 . As suggested in that issue I checked my Formie logs (no errors there) & the XML response in the network tab. The response has a 200 status code & is just an HTML document (which causes the issue I assume since it expects JSON?). 

### Steps to reproduce

1. Create a multi-page form
2. Use this as a template in a DDEV setup

```
{% set form = craft.formie.forms.handle('test_form').one() %}
  {% do craft.formie.registerAssets(form) %}


  <form method="post" accept-charset="UTF-8" enctype="multipart/form-data" data-fui-form="{{ form.configJson }}">
    {{ csrfInput() }}
    {{ craft.formie.renderPage(form, null, {
          fieldNamespace: '',
      }) }}
  </form>
  ```

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.3.3

### Plugin version

2.0.18

### Multi-site?

yes

### Additional context

I'm using a DDEV setup for local development.

**Comment by engram-design** [comment]
You're missing the `{{ actionInput() }}` tag (at least in your example) so tell it _where_ in Craft to actually try to submit to. Can you confirm if this is the case in your real code, or you've just omitted it for brevity?

**Comment by jan-dh** [comment]
Turns out using the ` fieldNamespace: '',` like this broke the form.
