### ISSUE TITLE
Add pageIndex for currentPage to the JS api

### ISSUE THREAD

**Issue by jan-dh** [verbb/formie#1204]
### What are you trying to do?

I would like to have an easy way to, for example figure out on what step of a multi-step form I am (from the total amount of steps). I can do this with a lot of hassle:: get the currentPageId & compare that to the pages array & check with the ID's.

### What's your proposed solution?

to have the currentPageIndex available in the JS API

**Comment by engram-design** [comment]
I've just added some functions to the Formie Theme JS.

```
document.addEventListener('onFormieInit', (e) => {
    // Fetch the Form Factory once it's been loaded
    let Formie = e.detail.formie;

    // Get an already-initialised form by its handle
    let form = Formie.getFormByHandle('multiPage');

    console.log(form.formTheme.getCurrentPage());
    console.log(form.formTheme.getCurrentPageIndex());
});
```

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jan-dh** [comment]
Perfect!
