### ISSUE TITLE
Notification email not automatically sending after submission.

### ISSUE THREAD

**Issue by 0xElectric** [verbb/formie#1205]
### Describe the bug

Notification email not automatically sending after submission.
It only sends the email notification when the `Control Panel` is reloaded.

### Steps to reproduce

1. Create form with email notification setup.
2. Render form on front-end using `{{ craft.formie.renderForm('formHandle') }}`
3. Make a form submission on frontend.
4. Wait form email notification (which will not happen).
5. Refresh the `Control Panel`, now the email sends.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.4 or 4.2.* 

### Plugin version

2.0.18

### Multi-site?

No

### Additional context

Ran on local using ddev.
Email settings is SMTP.
I tested sending email on **Settings > Email** and it works fine.

`runQueueAutomatically` is set to `true`

**Comment by engram-design** [comment]
Formie submissions use queue jobs to send out emails, and a visit to the control panel is required. This is the default behaviour of Craft running queue jobs. 

There's plenty of options on how to address this, depending on your environment and workflow.

Read up further on [the docs](https://verbb.io/craft-plugins/formie/docs/get-started/troubleshooting)
