### ISSUE TITLE
Calendar input triggering form change

### ISSUE THREAD

**Issue by Diewy** [verbb/formie#1208]
### Describe the bug

When using the Calendar display type for Date fields, the browsers always warns about having filled in the form.

In Chrome: "Leave site? Changes you made may not be saved."
![CleanShot 2022-12-09 at 17 14 20](https://user-images.githubusercontent.com/1014380/206745233-8e004ac8-af93-4908-a083-baa54c0fde22.png)

In Firefox: "This page is asking you to confirm that you want to leave - information you've entered may not be saved"
![CleanShot 2022-12-09 at 17 14 29](https://user-images.githubusercontent.com/1014380/206745263-f1fbe88a-a5ed-480d-9bb8-7ba101cb8036.png)

Via an earlier GitHub issue (#473) I've found the general setting to disable the message for now. But of course I would prefer to use both the Calendar and the unload warning.

Thanks!

### Steps to reproduce

1. Add date field to form
2. Set Display type to "Calendar"
3. Add form to page
4. Visit page without filling in the form
5. Leave or refresh the page
 

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.61

### Plugin version

1.6.20

**Comment by engram-design** [comment]
Yeah, this would be due to the date picker (Flatpickr) initialising through JS and adding a new input element. Formie will think something has changed, when it hasn't.

However, we have logic to [update](https://github.com/verbb/formie/blob/66e6e23776bbfb0f8f06a5e8945891a478efe497/src/web/assets/frontend/src/js/fields/date-picker.js#L118) Formie's internal hash that is checked to fire this warning.

I can't seem to replicate it on my end.

**Comment by Diewy** [comment]
I've created a new page with a new form to debug where it is going wrong. It took me a while to find out that, strangely enough, it only happens when I scroll..

### Steps to reproduce

1. Add date field to form
2. Set Display type to "Calendar"
3. Add form to page
4. Visit page
5. **Scroll** 
6. Without filling in the form, leave or refresh the page

**Comment by engram-design** [comment]
Yeah, still nothing for me. Even tested opening and closing the date picker. I'm wondering if maybe its a race condition, and we should probably wait until Flatpickr's `onReady()` event.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Diewy** [comment]
That didn't solve it.

After some more debugging I found that the value of the field is an empty string when the hash is updated. But when leaving the page it was the current date, triggering the warning. So I searched for the component which sets the default value and I think it is the locale.

It is fixed when I update the hash after the locale was loaded:

![CleanShot 2022-12-15 at 17 17 04](https://user-images.githubusercontent.com/1014380/207912531-ce9626e7-3a1b-4feb-b6ef-05b5519161dc.png)

**Comment by engram-design** [comment]
Ah, I should've asked that. Are you setting a default date value in your field settings?

But yes, you're absolutely right. For any non-English languages, this is going to trigger the warning.

Should be fixed now, running `composer update` one last time.

**Comment by Diewy** [comment]
Yes, fixed! :tada:

Thanks Josh!
