### ISSUE TITLE
Passing Twig values to Flatpickr

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1210]
### What are you trying to do?

Formie allows you to pass various parameters to a Flatpickr field through the Date Picker options.

For certain options like minDate and maxDate, it would be good if you could pass a value using Twig, e.g. something like a dynamic date e.g. `date('-10 years')` as a way to have a calculated date that dynamic relative to the time of execution. Say for example if you wanted to calculate a minimum date based on age, you'd need it to be dynamic and change every year.

### What's your proposed solution?

Potentially allow Twig syntax in Date Picker options field?

**Comment by engram-design** [comment]
This can't be done with Twig, sorry. You'll need to use JS to set Flatpickr options, but you can of course do that with Twig's JS.

```twig
{% set myDate = now %}

{% js %}
// Fetch all Date fields - specifically the input. Events are bound on the input element
let $fields = document.querySelectorAll('.fui-type-date-time input');

// For each field, bind on the `beforeInit` event
$fields.forEach($field => {
    $field.addEventListener('beforeInit', (e) => {
        let datePickerField = e.detail.datepicker;
        let options = e.detail.options;

        // Modify any Flatpickr options
        e.detail.options.minDate = '{{ myDate | date_modify('-10 years') | date('Y-m-d') }}';
        e.detail.options.maxDate = '{{ myDate | date_modify('+10 years') | date('Y-m-d') }}';
    });
});

{% endjs %}
```

Refer to the [docs](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#the-beforeInit-event)

**Comment by jamesmacwhite** [comment]
Thanks for the top on the before init event! I'll look at that for customising the date field.
