### ISSUE TITLE
MySQL 8 field handles longer than 53 characters with ALTER TABLE/DROP COLUMN commands

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1219]
### Describe the bug

There is a [MySQL 8 bug](https://bugs.mysql.com/bug.php?id=107236) which we've recently uncovered as a side effect of #1212, but worth pointing out. 

It would appear any field handle longer than 53 characters will trigger:

```
Failed to update columns dictionary object.
```

This would likely occur when the field is attempted to be deleted.

It would appear Formie fields have a handle char limit of 49 which is below this, but our Formie forms are originally migrated from Sprout Forms and it would appear this limit was not enforced, during the migration.

I can look for long field handles and correct these in our own migration, but maybe worth enforcing in the Sprout Forms migration process for anyone else who happens to trigger this.

### Steps to reproduce

1. Delete a field longer than 53 characters from a field layout.
2. An SQL error will occur on MySQL 8 due to the field handle length

### Form settings

N/A

### Craft CMS version

3.7.62

### Plugin version

1.6.20

### Multi-site?

No

**Comment by engram-design** [comment]
Yeah, I've seen this issue before, and indeed the rename-first then drop seems to fix the issue. I actually need to spin up MySQL 8 locally to test this further. Table columns should be no longer than 64 characters (factoring in `field_` prefix, and the field suffix). I'll double check if there's anything Sprout Forms-specific, but it should certainly all be handled the same.

**Comment by jamesmacwhite** [comment]
Looking at the craft_fields table and handle values we have, all are below 49 (maximum length is 48), so the migration did enforce it, you are correct. In fact thinking about it, I remember having to rename some handles during migration to avoid them failing.

What is more likely is the additional `field_` prefix along with the suffix, which pushes the field itself over 53 characters, yielding the MySQL 8 error.

Fields that are or near the maximum handle length are likely to be over 53 chars total with the additional characters from the prefix and column suffix

* Field prefix - 6 characters (`field_`)
* columnSuffix - 8 characters
* Formie handle max length - 49 characters

49 + 14 = 63 characters total

This size is valid for MySQL 8 generally (64 chars) but too much for ALTER TABLE/DROP COLUMN commands by the looks of the bug.

So in order to not trigger the MySQL 8 issue, the formie handle should be no more than 39 characters, given the 14 characters for the prefix and column suffix will always be 6 and 8 respectively I'd think?

**Comment by jamesmacwhite** [comment]
Happy Christmas!

As the field length has been further reduced in the codebase now, what is the best way to handle existing fields that exceed the MySQL count of 53 with the prefix and suffix?

I guess a DB migration but you'd have to rename both the craft_fields and the reference in the relevant craft_fmc table?

**Comment by jamesmacwhite** [comment]
Just checking as well, the max field length now being 40, but with 6 chars (field_ prefix) + 8 (column suffix if using Craft CMS 3.7) = 14. So potentially 40 + 14 = 54 chars.

That can mean the max field column length could still be 54 which could still trigger the MySQL 8 bug, as it's 53 characters or below that seems to be OK.

You could also make it lower just for MySQL implementations with something like:

```php
$maxHandleLength = Craft::$app->getDb()->getSchema()->maxObjectNameLength;
$maxHandleLength -= strlen(Craft::$app->getContent()->fieldColumnPrefix);
$maxHandleLength -= 8;

if (Craft::$app->getDb()->getIsMysql()) {
     $maxHandleLength -= 11;
}
else { 
    $maxHandleLength -= 10;
}
```

If you didn't want to cap all DB types

**Comment by engram-design** [comment]
Yeah, I was against running a migration as that could be pretty disruptive to users that might be referring to fields in email notifications, integrations or manual rendering. As this also only affects some users, I was going to just ensure it takes care of things from this point onward.

For your use-case, I would rename any long fields manually (which is still possible despite the MySQL 8 bug).

As for the limits, we're working backwards, so your calculations are a little off.

`maxObjectNameLength` is 64 (for MySQL), `fieldColumnPrefix` is 6 (`field_`).

So `64 - 6 - 8 - 10 = 40` so that's well under the limit.

**Comment by jamesmacwhite** [comment]
I'll look at a migration for our specific project for the one's that are beyond the limit pre change.

My calculation is based on the fact the ALTER TABLE/DROP COLUMN commands will be the full field name in craft_fmc_xxxx table which the prefix and column suffix needs to be 53 chars or under, it's not just the field handle on it's own I didn't think?

So let's say I have a handle of: `SomeReallyLongHandleThatWillMakeMySQLSad`, when in the fmc table it will be:

`field_SomeReallyLongHandleThatWillMakeMySQLSad_cf84654`

With the prefix and column suffix despite the 40 chars handle limit, it still exceeds 53 chars, so if I ever delete this form, MySQL will not have a good time. Unless I'm misunderstanding.

**Comment by engram-design** [comment]
Ah, yes of course - you make a great point! Just pushed that small change up for next time.

**Comment by jamesmacwhite** [comment]
Thanks! Sorry if I didn't explain it clearly enough, basically what you initially did was fine, but needed to be one more character basically to cover any handle exceeding 53 with the prefix + handle + column suffix together.

Despite 64 chars being the max chars and being valid for the schema in MySQL, the more MySQL 8.0 specific safeguard calculation is:

53 - (6 + 8) = 39

So no Formie field handle can be larger than 39 chars to ensure any ALTER TABLE/DROP COLUMN commands will not blow up. Maybe Oracle will fix it one day, seems like a regression that wasn't there previously.

If you didn't want to enforce it across all DB schemas you could do `Craft::$app->getDb()->getIsMysql()` as a condition to not make something like postgres be put under the same ruling. Although, querying specifically MySQL 8 is probably not really possible with the Craft API, so maybe it's better just to do lower for all, at least it's consistent.

**Comment by engram-design** [comment]
Nah you explained it fine, I've lobbed on 2 extra characters (just in case it's 53 _inclusive_). And yeah, just going to enforce it schema-wide for the moment. People can mess around with their field handles to get them how they want if they like.

**Comment by jamesmacwhite** [comment]
Awesome, that will do it!

**Comment by jamesmacwhite** [comment]
I ended up writing a migration as there's quite a few fields that are over 40 across various forms in this project. Is this the best way to do it with Formie service classes?

Trigger a form save seems to update the field handle in both the craft_fmc_xxxx and craft_fields table.

```php
$fieldHandleMapping = [
    'anExampleReallyLongHandleToBeMadeShorter' => 'shortenedHandle1',
    'anExampleReallyLongHandleToBeMadeShorter2' => 'shortenedHandle2',
    'anExampleReallyLongHandleToBeMadeShorte3' => 'shortenedHandle3',
];

$forms = Formie::$plugin->getForms()->getAllForms();

foreach ($forms as $form) {
	echo "Searching form: $form->title for long field handles...\n";

	$fieldLayout = $form->getFormFieldLayout();

	foreach ($fieldLayout->getFields() as $field) {
		if(strlen($field->handle) > 39) {
			$newHandle = $fieldHandleMapping[$field->handle] ?? null;

			if ($newHandle) {
				echo "Field handle $field->handle will be modified to $newHandle...\n";
				$field->handle = $newHandle;
			}
		}
	}

	Formie::$plugin->getForms()->saveForm($form);
}
```

**Comment by jamesmacwhite** [comment]
@engram-design Just wondering if you could take a look at the above code if it's suitable for renaming fields in place without losing the data in a DB migration? I've tested it and it seems to be OK, it basically renames the fields in place and maintains the data in the fmc table, but just in case I've missed something or if I should be using the service classes differently. Thanks!

**Comment by engram-design** [comment]
@jamesmacwhite Yep, this would be a good way to handle it, and nothing special you need to do otherwise.

**Comment by jamesmacwhite** [comment]
@engram-design Awesome, thanks for taking a look. Always nervous when doing modifications like this, but easier if it's done with a DB migration through deployment to track it in the migrations table.
