### ISSUE TITLE
Failed Captcha “Recaptcha”: “”

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1220]
### Describe the bug

We recently enabled Recaptcha V3 on a Formie form but found all the submissions were being marked as spam, the spamReason recorded was:

```
Failed Captcha “Recaptcha”: “”
```

We have set the Recaptcha v3 key accordingly through env vars.

Any ideas on what can be done to debug why the submissions were marked as spam? Is it the spam score value, I believe default 0.5?

### Steps to reproduce

1. Enable Recaptcha v3 integration
2. Enable on Formie form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.62

### Plugin version

1.6.20

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
So two problems:

1. Content Security Policy, need to allow recaptcha.net in both script-src and frame-src.
2. I am overriding the Formie form ID value.

The second point I think I remember you mentioning previously in v1 overriding the form ID is potentially risky, what I will do is move my currently set ID that's overriding the main ID onto a data attribute for safety, so I can at least still use it in custom tracking, but not interfere with the core Formie stuff.

**Comment by engram-design** [comment]
Yep, there are limitations with Formie 1 for IDs https://verbb.io/craft-plugins/formie/docs/v1/template-guides/rendering-forms#override-form-id

**Comment by jamesmacwhite** [comment]
Happy Christmas! I found despite following `formie-form-xxxxxxx` it still caused random JavaScript errors, so it seems for safety not to override it at all and instead set a custom ID property on a data attribute instead under v1.

**Comment by engram-design** [comment]
@jamesmacwhite I'll look into it, but agreed that it's not something that's possible in Formie 1 as a lot of things rely on that. We're also not planning to do anything about that for v1 as that finishes up support in the new year (alongside Craft 3).

**Comment by jamesmacwhite** [comment]
It's fine with me to not override it and put anything custom on data attributes, accessing them can be done just as easily as the form ID.
