### ISSUE TITLE
Submissions doesn't render the right snapshot when overwritten on frontend

### ISSUE THREAD

**Issue by belkin** [verbb/formie#1227]
### Describe the bug

I have a form where I'm overriding the options on frontend dynamically with ```{% do form.setFieldSettings('related_subjects', { options: subjects }) %}``` but the submissions aren't showing the right submitted data. I see new options in the submissions on every page refresh in the frontend with changed data.

### Steps to reproduce

1. Create new form and add new Dropdown field with multiple enabled.
![image](https://user-images.githubusercontent.com/3419659/210393108-b9a1fe5b-43ce-4080-a53f-8cdd5b0b360c.png)
![image](https://user-images.githubusercontent.com/3419659/210393160-a25c1fbe-e961-49cd-91d0-884635bbf4bb.png)

2. Override the data of the dropdown field on frontend with form.setFieldSettings() 
```
{% do form.setFieldSettings('related_subjects', { options: [
    {
        label: 'test-title-1',
        value: '1',
        isDefault: false,
    },
    {
        label: 'test-title-2',
        value: '2',
        isDefault: false,
    }
] }) %}
```
3. Submit the form with selected options.
![image](https://user-images.githubusercontent.com/3419659/210393687-ef681265-d05b-4f43-8c3e-763bb822837a.png)

4. Open the submission 

![image](https://user-images.githubusercontent.com/3419659/210393316-dcedd4bb-6ac6-43fc-b88d-1230d3e6ff14.png)
6. Update the label and value of the data and refresh the page.
```
[
    {
        label: 'test-title-11111111',
        value: '12222',
        isDefault: false,
    },
    {
        label: 'test-title-2222222222',
        value: '233333',
        isDefault: false,
    }
]
```

7. Refresh the submission
![image](https://user-images.githubusercontent.com/3419659/210393509-68b64e41-21e4-4ea4-9e79-0756b1660453.png)

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.3.5

### Plugin version

2.0.20

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by belkin** [comment]
Thanks! It works hier!
