### ISSUE TITLE
Address field: Postcode field is not contained it's own .fui-row like all other address fields

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1228]
### Describe the bug

Looking at the markup of the Address field, the postcode field is not contained it's own `.fui-row` like all the other fields. In my case, City and Postcode are under the same fui-row and put together.

![image](https://user-images.githubusercontent.com/8067792/210735093-40213a50-d271-42af-9aab-63a684bb92d5.png)

If you are applying custom CSS onto the fui-row class this won't apply equal spacing between the fields in this case, the postcode field would need to be handled by targeting another class which isn't ideal.

### Steps to reproduce

1. Add Address field to form
2. Use custom CSS styling and apply padding on fui-row.
3. Observe the spacing between City and Postcode on the Address field not being equal like the rest, due to the markup

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: No

### Craft CMS version

3.7.62

### Plugin version

1.6.21

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
Workaround is to move margin on fields to the `.fui-field` class, although I don't know if the markup could still be changed for consistency.

**Comment by engram-design** [comment]
Depends what "custom CSS" you're including. The default Formie theme will render the below:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1221575/210786790-03ffd058-ff8d-4e4e-a0e1-0a1c9f986ebf.png">

As for the markup, the default templates use a combination of row and columns (the fields):

- `.fui-row`
    - `fui-field` (Address 1)
- `.fui-row`
    - `fui-field` (Address 2)
- `.fui-row`
    - `fui-field` (Address 3)
- `.fui-row`
    - `fui-field` (City)
    - `fui-field` (ZIP / Postal Code)
- `.fui-row`
    - `fui-field` (State / Province)
    - `fui-field` (Country)

Of course, you can change this with custom templates, or in Formie 2 you have control over which fields are grouped into which columns.

Even with the Base CSS from Formie (no Theme CSS), you'll still get the bare-bones to style a `.fui-row` class with:

```css
.fui-row {
    display: flex;
    flex-wrap: wrap;
}

.fui-field {
    flex: 1;
}
```

Which from your screenshot, looks like isn't applied. Hard to tell without knowing your setup. But, I would highly recommend treating the row and field classes like row/col classes from Bootstrap, Tailwind, etc. If you'd rather not use flex and gap, you can add padding to the inner field divs, which act like columns in the form builder.

Let me know if there's more detail on what you're trying to do.

**Comment by jamesmacwhite** [comment]
So what I think is my mistake is using the .fui-row class as a way to do spacing between each field. Reviewing the markup it looked like there would always be a .fui-row for each element, in the case of the address field, this doesn't happen.

So the better way is to shift the field spacing rule to something like .fui-field which always is present.

I am using custom form styling so that's why the output is different. Because there's already form styling broken down for each component in this project, I'm actually in most cases, just doing `@extend .classname` on a lot of the `.fui-xxxx` classes to apply the existing styling to save duplicating.

In my case, switching to apply spacing between fields that more closely aligns with the formie-theme.css is the better option!

Sorry for the noise!

**Comment by engram-design** [comment]
So the `.fui-row` should 100% be wrapping every field, by default. Unless you're changing the HTML templates yourself.

Are you able to show me the HTML source of the Address field to confirm?

**Comment by jamesmacwhite** [comment]
I'm not modifying any HTML templates, just custom CSS styling. Grabbing a screenshot for you now

**Comment by jamesmacwhite** [comment]
![2023-01-05](https://user-images.githubusercontent.com/8067792/210891062-dda1624d-fb25-4c4d-8717-f8f2c00d99b3.png)

So the City and Postcode field are within the same fui-row, based on the markup here.

I don't know if it's specific to the address field having certain address lines on and off potentially?

**Comment by jamesmacwhite** [comment]
Ignore the address line 1, address line 2 etc under the address field these are single line input fields which have come from Sprout Forms, I intend to replace them with the address field, so that's why I've come across this while testing.

I have sort of resolved the styling issue, by using different selector targeting anyway, but if it's a bug, then hopefully this helps!

**Comment by engram-design** [comment]
Nope, that all looks correct to me! As I've mentioned, by default, some of the sub-fields of the address field are grouped into the same row, just because the fields will be crazy long if stacked under one another (shown in your example on mobile - which is fine and necessary with screen real estate).

So this looks like it's working correctly according to the [example markup](https://github.com/verbb/formie/issues/1228#issuecomment-1372203251).

If you're wanting to add spacing between fields, best to use `fui-field` which will always wrap each field individually. `fui-row` wraps one or more fields, according to either sub-fields (Name, Address, etc), or how you lay out fields in the form builder (up to 4 in the same row).

**Comment by jamesmacwhite** [comment]
That's fine, no worries, I have indeed used the fui-field class instead. Reviewing the formie-theme.css, that seems to be the way it was being done, so I implemented a similar ruleset!

**Comment by jamesmacwhite** [comment]
Sorry, I understand this better now, the reason why there isn't a fui-row is for the flexbox rules, so the fields are in columns. I wasn't using the formie-theme.scss at all, but I've now implemented it in conjunction with my own styling rules and it works better.
