### ISSUE TITLE
GraphQL `captchas` field is empty.

### ISSUE THREAD

**Issue by denisyilmaz** [verbb/formie#1231]
### Describe the bug

Since version 2.0.19 the captchas field inside the gql query is empty no matter what the settings are:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/4189607/211366104-3ff7d86b-6b68-40a7-8297-a979cf63e62d.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/4189607/211366159-f2ca6556-c512-4ab4-ad95-67cf99c418c0.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/4189607/211366244-224d3ef7-f143-4eeb-adf7-ec01fb2234a9.png">

The Recaptcha object inside settings.integrations is filled out correclty (with the recent update to now show the recaptcha secret.

Any (new) settings that is required to retrieve the `captchas` object?
I also recognized that the `FormieCaptchasInput` is not part of my GraphQL Schema. "GraphiQL Explorer" only shows

### Steps to reproduce

1. 
2. 

### Form settings

- Multi-page form: Yes
- Submission Method: GraphQL
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.5

### Plugin version

2.0.20

### Multi-site?

No

**Comment by engram-design** [comment]
This is correct behaviour, there are no captcha settings you can query on reCAPTCHA/hCaptchas. Only the Duplicate and JavaScript captchas return values for `captchas` object, as these are required client-side to be sent with the request back to the server.

I suppose we could include the reCAPTCHA client-site key if you find that useful, but otherwise, there's nothing else Formie needs to provide the front-end. If you're BYO-ing the front-end with GraphQL, its expected you implement reCAPTCHA yourself, as it would be impossible to implement otherwise with Formie (due to the BYO nature of your front-end).

Does that make sense?

**Comment by denisyilmaz** [comment]
sure, i understand why `captchas` is empty for reCAPTCHA, makes sense. The client site key is added as a env const on build time in our case.
But this does not explain the more pressuring issue `FormieCaptchasInput` to pass the validated reCAPTCHA token to the submission. 

I'm using a angular adaption from your formie-headless example to create mutation:

```ts
createMutationTypes(form: FormieFormFragment) {
    const types = this.getFormFieldMeta(form).map(({ handle, inputTypeName }) => {
      return `$${handle}: ${inputTypeName}`;
    });

    // Add in any captcha tokens generated when we queried the form.
    form.captchas?.forEach((captcha) => {
      types.push(`$${captcha?.handle}: FormieCaptchasInput`);
    });

    form.settings?.integrations?.forEach((integration) => {
      if (!integration?.enabled) return;
      if (integration.handle === 'recaptcha') {
        types.push(`$recaptchaCaptcha: FormieCaptchasInput`);
      }
    });

    return types.join(', ');
  }
```

… failing with unknowin input type `FormieCaptchasInput`. But same issue is in crafts own GraphiQL explorer where this is not a valid input type as well.

**Comment by engram-design** [comment]
Not sure if that's just a typo, so wanted to check first. That should be `FormieCaptchaInput` **not** `FormieCaptchasInput` if you can confirm?

**Comment by denisyilmaz** [comment]
sorry, was just a typo, `FormieCaptchaInput` is not available. Here is a screenshot from GraphiQL explorer for the mutation: 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/4189607/211571245-dec0da01-6078-448f-8361-ee75c8cff714.png">

When this was working i could select `recaptcha` (or something similar) of type `FormieCaptchaInput` as an input.

**Comment by engram-design** [comment]
Hmmm, so that certainly appears for me:

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/1221575/211679166-c92826bd-0e92-40d2-8c0a-e3518e85af5b.png">

Granted, you'll need to have the captcha enabled globally, and for the form you're trying to mutate on.

**Comment by denisyilmaz** [comment]
Thanks for your message, it forced me to try out every combination to find out what might cause this. And now I found it...
"Show on All Pages" was disabled by default and not set to true for the forms. This is preventing the `FormieCaptchasInput` to be available on mutation. Enabling the settings and clearing the GraphQL cache was returning the input.

I never realised this settings to have an effect as our test forms only had one page, therefore the settings was never applied... Does it make sense to have this settings affect the graphql schema? Headless Formie integrations would most of the time send the content for the full submission at once, making a this setting obsolete. 
We have "edit of Submissions" disabled in the schema settings anyway.

Anyhow, got it working again.

**Comment by engram-design** [comment]
Glad you figured it out, and that's interesting. I'll see what I can do about that - although I was also testing on a single page form with this disabled.

> Headless Formie integrations would most of the time send the content for the full submission at once, making a this setting obsolete.

While I agree, I know for a fact some users like to send a mutation for each page.
