### ISSUE TITLE
Multi-line text display on submissions (row size value)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1234]
### What are you trying to do?

On the back-end of a submission using a multi-line text field, is there anyway to adjust the default size of the textarea field being displayed.

An example field on a form called "Additional informaiton"

```html
<textarea class="text fullwidth" name="fields[additionalInformation]" maxlength="" rows="2" cols="50"></textarea>
```

When populated with content, this will be quite small:

![image](https://user-images.githubusercontent.com/8067792/211527165-9d422a57-35ff-4229-8b0a-963d6b028104.png)

Is there anyway to adjust the default row size or display of them to make them bigger. They can be resized but this will not be persisted.

Alternatively, I could look at adding a CSS rule to target the control panel page, but probably better to try and set a row size value which makes more sense.

### What's your proposed solution?

Ability to set row size on textarea in back-end.

**Comment by jamesmacwhite** [comment]
Looking at the field template, a row value can be specified on the include, but currently is just defaulting to the form macro default I think:

https://github.com/verbb/formie/blob/craft-3/src/templates/_formfields/multi-line-text/input.html#L17

**Comment by engram-design** [comment]
Not at the moment, but as we're rendering the native Craft [`_includes/forms/textarea`](https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/textarea.twig) template you can provide a `cols` and `rows` value.

There's not really a way to override the input template for a submission in the control panel, we're largely just trying to make it native Craft-like, and I'm not really sure the best way to manage such a setting. I suppose we could look at adding an event to modify the render-time variables for the template.

In the meantime, I would suggest using CP CSS to modify this.

**Comment by jamesmacwhite** [comment]
Yeah, this just purely on the backend for submissions, front end is fine with theme styling, just for editors that view submissions in the backend. When a textarea has multi lines the default size provided is a little small. I am happy to apply a CP CSS rule as we are already loading custom CP CSS.

However, rather than a setting, would you consider setting a hard coded rows value within: `_formfields/multi-line-text/input.html`? on the `{% include '_includes/forms/textarea' %}` line i.e.

```twig
{% include '_includes/forms/textarea' with { rows: 5 } %}
```

The default of 2 that is there currently is a little small for a rendered textarea which might have multiple lines, bumping generally might be acceptable.

Anyone wanting to change it beyond the default or a set value can target textarea fields on submissions using the body class selector:

```css
.fui-submission textarea { 

}
```

**Comment by engram-design** [comment]
Yep, more than happy to tweak the default a little - just wasn't sure _your_ desired default would suit everyone, but that seems fine to me.

**Comment by jamesmacwhite** [comment]
I think if you can a slightly bigger row value by default that would be great to benefit everyone with a sensible value. Any further tweaks could be done with CP CSS.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Amazing! Thank you!

**Comment by engram-design** [comment]
Added in [1.6.22](https://github.com/verbb/formie/releases/tag/1.6.22)
