### ISSUE TITLE
Moving existing column positions in fmc tables without losing data

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1235]
### Question

I've been migrating data on forms that were originally from Sprout Forms and taking advantage of the combo fields like "Name" and "Address" where we previously just using single line input fields.

To safely migrate data across, I created the new Formie fields on the field layout, made the single line inputs fields hidden on the front end and then wrote a DB migration to copy the data from the old fields to the new one on previous submissions. I left the old fields until after the migration to ensure we could recover if anything went bad and also to verify after migration, given it was the first time writing migrations for Formie data.

One downside to this is the new fields created have been created in the relevant fmc table at the end, as with any new column added to a table. This doesn't cause any major impact unless exporting, where the column order is then more important. However it appears with MySQL you can move the column without losing data with an ALTER TABLE and MODIFY. Something like this:

```php
$this->execute("ALTER TABLE $contentTable MODIFY $columnToMove $columnToMoveType AFTER $columnAfter");
```

```sql
ALTER TABLE {{%fmc_something}} MODIFY field_newColumn text AFTER field_column1
```

Just wondering if you think that's safe and any potential issues?

I might look at how possible in-place field type migration and moving the data in the fmc table is to preserve positions for other changes, but I did the new field and migrate data approach to get comfortable and provide a way out if it went south. So far, no issues!

**Comment by engram-design** [comment]
The order of columns in the content table will have zero ramifications if moved around, so you're welcome to shift things around as needed. That's an interesting point, but I assume the end-game would be to delete those legacy fields at some point, after which the columns would be gone?

There doesn't exist the ability to "Hide field from export" which is maybe something we could add, but have to question the usefulness of it (just adds more settings clutter to fields), but seeing as though we'll be adding a similar setting for including in email notifications, maybe that's justifiable.

**Comment by jamesmacwhite** [comment]
Thanks. Yes the fields where the data was migrated from will be deleted, but in the case of Name and Address, as they are a bit different and require basically a JSON payload to be inserted for each, I created new fields first to then move, the advantage, it's easier for the migration to copy the existing data over and be able to verify both the old and new directly.

I however realised that even though the new columns in the database are at the end on the fmc table, the export function in Formie still outputs them in fieldLayout order anyway, so it makes it less of an issue really. I thought the export function might not follow that order, but it does, so I guess for my question not so much of a problem!

In terms of a hide from export, it could be useful in some cases I guess.

**Comment by engram-design** [comment]
Sounds good, we'll track that in another issue!
