### ISSUE TITLE
Default Date Field Fails Validation

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/formie#1236]
### Describe the bug

I have a standard date field which defaults to the current date on the front end.

However, the form won't submit even though the form field is (defaulted) filled in.

Formie also is not showing which field is causing the error so users were having problems submitting. I had to go into the formie.log to find what the problem was.

### Steps to reproduce

1. Setup a date field.
2. Set the default value as Today's Date. 
3. Formie will tell you the form failed validation but won't say which field failed.

### Form settings

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft CMS 3.7.63.1

### Plugin version

Formie 1.6.21

### Additional context

Workaround: keep the date field blank. When the user manually picks a date it works fine. It's almost like the default value is being seen as a placeholder and not an actual form value.

**Comment by engram-design** [comment]
Can't seem to replicate this immediately. Are you using the date picker and calendar options?

There is however a console warning that is triggered before Flatpickr initializes (fixed for the next release), which might be causing an issue. But I still couldn't replicate the failed validation for any combination of date field setups.

**Comment by RitterKnightCreative** [comment]
Yes, display type is Calendar. Include Date is ticked on. Use Date Picker is ON as well. Date Format is set to MM-DD-YYYY.

**Comment by RitterKnightCreative** [comment]
Problem is definitely the date picker. I noticed if I turn off the date picker it works.

Getting this in the log:

```
2023-01-12 09:43:15 [-][-][-][info][formie] Submission triggered for contactForm.
2023-01-12 09:43:15 [-][-][-][error][formie] Couldn’t save submission due to errors - {"dated":["Dated cannot be blank."]}.
2023-01-12 09:43:15 [-][-][-][info][application] $_GET = []
```

**Comment by engram-design** [comment]
Managed to replicate this! Should be fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by setheryb** [comment]
@engram-design What would be the version for getting this fix early for Craft 4.3.6?

**Comment by engram-design** [comment]
Added to `craft-4`. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.21](https://github.com/verbb/formie/releases/tag/2.0.21)
