### ISSUE TITLE
Repeater - Add ability to set default values for fields

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#124]

**Comment by engram-design** [comment]
Keen to get your thoughts on how you were thinking this to look/work @jaydensmith

**Comment by jaydensmith** [comment]
@engram-design from memory it was about being able to set a number of default repeater rows/values

**Comment by engram-design** [comment]
@jaydensmith Gotcha, that might be tricky from the CP given it needs to know about the inner fields. Might shelve this until someone asks for it.

**Comment by engram-design** [comment]
Closing in favour of being able to achieve this with `craft.formie.populateFormValues()` in templates. It might be near-impossible to have this work in the form builder.
