### ISSUE TITLE
Google Places Autocomplete with United Kingdom (GB) addresses (City value is filled incorrectly)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1242]
### Describe the bug

Testing the Address field with Google Places Autocomplete, I am finding that UK address lookup data is being filled in a way that overwrites the City value when the address has more than one address line before City.

Test case:

Address field configured with:

* Address Lookup
* Address Line 1
* Address Line 2
* Address Line 3
* City
* Postcode
* Country

Address data test case:

```
101 Example Road
Example Town
Example City
NG1 1AA
```

What seems to happen is `Example Town` is populated onto the City field, where I would expect "Example Town" to be Address Line 2 and `Example City` to be on the City field. This however doesn't happen. So what the result of the lookup on the fields is actually:

* **Address Line 1**: 101 Example Road
* **City**: Example Town
* **Postcode**: NG1 1AA
* **Country**: United Kingdom

`Example City` has been discarded when filling the fields.

Is there a way to steer the address lookup population to go to specific fields in this case, do any of the events for address fields allow for this control i.e. https://verbb.io/craft-plugins/formie/docs/developers/events#address-field-events?

### Steps to reproduce

1. Enable Google Places API autocomplete
2. Enable Address Lookup option on address field with Google Places API provider
3. Enter a UK address with more than one address line before the City value
4. Observe the City value has been overwritten by what should be Address Line 2.

### Form settings

- Multi-page form: No
- Submission Method:  Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.63.1

### Plugin version

1.6.21

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
I'm wondering if it's due to not using the state address sub field. State is generally not something used in the UK for addresses but is for the US and others.

**Comment by engram-design** [comment]
Are you able to give me a sample, real address to test? I've tried a bunch of them out, and they seem to work okay for me - to my understanding at least. I've been using https://www.fakexy.com/fake-address-generator-uk

However, I _do_ see an issue with UK-based addresses not getting their city/town populated. This seems to be in the `postal_town` not `locality` from Google's API. But what I don't see is what you describe, with it populating in Address Line 2. In fact, we **never** populate that field, just stick with Address Line 1, combining `street_number`, `route` and if available, `subpremise`.

That should be fixed in the `craft-3` branch, but if you can let me know your testing addresses?

**Comment by jamesmacwhite** [comment]
Yes, the main issue is it looks like for UK addresses the postal_town value is not populated onto the City address line. Using a real postcode example:

Search: `NG1 1AA`
Address Lookup value: `Lower Parliament Street, Nottingham NG1 1AA, UK`
Doesn't populate "Nottingham" on the City field.

You can use [Royal Mail postcode lookup](https://www.royalmail.com/find-a-postcode) to get samples of real UK addresses for reference (you get about 50 lookups per day free).

The other issue which is more specific to UK addresses is the fact that when a UK address has multiple address lines before the City value i.e.

```
101 Example Road [Address Line 1]
Example Town [Would be Address Line 2]
Example City
NG1 1AA
```

Normally `Example Town` would be populated on Address Line 2 and `Example City` would be on the City address line. Currently it looks like Address Line 2 is never filled or used.

In terms of address data, the minimum required is Address Line 1 and Postcode to be valid, but often UK addresses may have more than one Address Line before the City value, sometimes there might be three or even four address lines before City, depending on the address data.

I don't know if there's a way to steer this data into that fill format as that is more aligned to the UK.

**Comment by engram-design** [comment]
So on my end, the field populates as the below:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1221575/213332514-b3f67eba-8cd5-42a3-ac8e-306bf7bcae47.png">

But you raise an interesting point populating Address Line 2 with the town. That might be a UK-specific thing (but I'm sure would crop up in other countries), I wasn't sure of the need to have both town _and_ city. That would be quite uncommon for Australia for instance, where Line 2 is typically for the unit number, floor or complex.

```
101 Example Road [Address Line 1]
Unit 203 [Address Line 2]
Ascot Vale [City]
3032 [Postcode]
```

It's also common to have the lines reversed (unit first). And while it could also be written as the below, I've never seen it that way, and not sure if it's valid at the post office!

```
Unit 203 [Address Line 1]
101 Example Road [Address Line 2]
Ascot Vale [Address Line 3]
Melbourne [City]
3032
```

But of course, every place is different, so I think a one size fits all approach will be tricky.

That's probably going to need something more detailed to address this. Maybe providing a JS map to the field to determine what info goes where. This is already done [internally](https://github.com/verbb/formie/blob/67391fdf755b69aa81986d3eaf3ea2807da57ffe/src/web/assets/addressproviders/src/js/google-address.js#L103-L106) so we'd just need to open this up to an event.

**Comment by jamesmacwhite** [comment]
Thanks for the follow up! I guess there's technically two parts to the original issue, although the main area around the City value seems resolved now.

1. One the UK City value being discarded, which I think you've now resolved by using `postal_town` rather than locality as this I believe by Google's own docs suggests it should be used for UK and Sweden.

2. When a UK address has more than one address line before the City value it's currently not populated on a lookup into the address line fields as one might expect being from the UK.

I certainly appreciate address formats across different countries are going to be tricky to make work across all, so perhaps any event to try and steer the address data for a specific country or format is better. The same argument might be for the autocomplete values on address sub fields too, City I think is address-level2, for UK address-level1 might better as an example.

Alternatively, a perhaps a longer term solution for UK addresses is an integration with a UK specific postcode lookup service. Royal Mail in the UK provides access to a database called PAF (Postcode Address File) on commercial basis. Various UK postcode lookup services will provide access to this, which will leverage the PAF data.

**Comment by engram-design** [comment]
Appreciate the feedback. I think an event to allow developers to fine-tune what goes where will do a lot to help this.

> When a UK address has more than one address line before the City value it's currently not populated on a lookup into the address line fields as one might expect being from the UK.

The only issue I see here is that if people want to add unit or flat numbers (I assume that's a separate part of the address in the UK) that would probably go in line 1 or 2, before the town. That just get's a bit tricky to handle, but like i've mentioned, we don't populate into Line 2 or 3 at the moment - but we could.

And good call on Royal Mail, I'd be keen for that. I originally added Loqate for UK and Europe as someone asked me to implement it. Google Places is pretty horrible at anything non-US (it's horrible for AU/NZ with unit numbers, which is why we recommend AddressFinder for that - not to mention expensive).

I'll keep this issue around for now to reference adding a new event to control things.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
