### ISSUE TITLE
Sendinblue Integration - linking multiple lists

### ISSUE THREAD

**Issue by carinameissl** [verbb/formie#1245]
### What are you trying to do?

Hello,

I'm currently linking a form with sendinblue using the integration. Is there a way to link more than one list? 
We'd need to link to 2 lists in order to trigger 2 different mails. 

Thanks,
Carina

### What's your proposed solution?

Having a second list dropdown.

**Comment by engram-design** [comment]
Sure! You'd need to create a new "Sendinblue" integration. So you might have "Newsletter Sendinblue" and "Contacts Sendinblue" as your integrations (they'd both have the same settings). Then, you can configure them in your form to use different lists.

**Comment by carinameissl** [comment]
That's great, work perfectly - thanks for the quick response!
