### ISSUE TITLE
Date Field input cleared on multi-page forms on Page Reload Submission type

### ISSUE THREAD

**Issue by transopticmedia** [verbb/formie#1247]
### Describe the bug

Hi, I noticed on the latest Formie that the when including a Date Field on a multi-page form, the date field is cleared out when advancing to the next page, then the form won't submit if it's a required field. If you advance back to the page with the date field it's always cleared out. Ajax submission doesn't seem to have this problem, just Page Reload.

### Steps to reproduce

1. Create a multi-page form
2. Add a date field to the first page
3. Leave Form Submission Method as "Page Reload"
4. Test the form, filling out the date field on page 1
5. Advance to page 2
6. Return to page one, and the previously populated date field is cleared. 

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.3.6.1

### Plugin version

2.0.20

### Multi-site?

Yes

### Additional context

I've confirmed this is happening in my DDEV installation as well as on the staging server.

**Comment by engram-design** [comment]
Can you advise on your Date field settings? I've tested a few different combinations, which seem to be working correctly. It might also be related to https://github.com/verbb/formie/issues/1236 so worth trying on the `craft-4` branch.

**Comment by transopticmedia** [comment]
Thanks for looking into it. I've tested with the default date field, but without time included. Although making the field required is stopping the form from submitting, it's not affecting this bug, which happens in either case. I'll test out the craft-4 branch. 
  
<img width="624" alt="Screen Shot 2023-01-19 at 17 17 41" src="https://user-images.githubusercontent.com/302693/213583885-0bc8d2fa-e8c5-46ce-b3e5-d9812c66915f.png">

**Comment by engram-design** [comment]
Thanks for that, and just checking if you have Flatpickr enabled (**Use Date Picker** setting in Appearance)?

**Comment by transopticmedia** [comment]
Flatpicker/Datepicker is enabled, and I just tested – it works correctly without it! I haven't installed craft-4 yet, I'll check it out now.

**Comment by transopticmedia** [comment]
Thanks for your help! #1236 / craft-4 seems to fix the issue.
