### ISSUE TITLE
Adjust 'scroll to top' offset

### ISSUE THREAD

**Issue by daniellelecomte** [verbb/formie#1256]
### Question

Is it possible to adjust the 'scroll to top of form' JS to include some offset? Our navigation is sticky and when the pages scrolls to the top of the form to show success or error messages, as well as proceeding to pages in multi-page forms, a large part of the form is hiding behind our navigation.

We've done something similar with another form plugin by looking for a certain event:
```
form.addEventListener("myform-ajax-after-submit", function (event) {
    var $root = $('html, body');
    $root.animate(
        {
            scrollTop: $(form).offset().top - 400
        },
        500
    );
    return false;
})
```

Is there a similar option for this with Formie? Thanks!

**Comment by engram-design** [comment]
There's no JS event to modify this at the moment, but I'd recommend using `scroll-padding-top` or `scroll-margin-top` on the `<html>` element to control the offset. It's something you'll likely want to use elsewhere on your site, particularly if you have a sticky header.

```css
html {
    scroll-padding-top: 50px;
}
```
