### ISSUE TITLE
Microsoft Dynamics 365 CRM: Event for obtaining contact ID, account ID or lead ID for further mapping in payload

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1257]
### What are you trying to do?

In our CRM environment we have certain relational fields that are links to entities like contact, accounts etc that can be populated. Currently the integration payload assigns this to standard CRM fields i.e. `primarycontactid@odata.bind`, `parentcontactid@odata.bind`, `parentaccountid@odata.bind`

Is there any possibly through events to be able to further assign the record ID created to other relations fields on specific entities?

Scenario/use case:

In our CRM environment the lead entity has a field called "enquirer" which is actually called `customerid` by logical name, this is for a contact relation. In addition to the Formie integration, I would want to be able to obtain the GUID of the created contact after the payload has been delivered and assign this to the customerid field on the lead so this can be populated when the lead is created in the payload sequence. `customerid` is not a custom field, but perhaps not everyone would want this populating, therefore an event may be better to allow more flexibility and customisation when choosing to populate relational fields.

### What's your proposed solution?

For each entity where the payload is sent and a record created, add in an event to allow the ability to obtain the GUID/ID of the entity created (if successful) to then assign on other entities.

e.g. If I use the contact and lead mapping, when the contact is created and the ID is available, allow the ability to obtain this ID in an event via a module to then add onto the lead payload before it gets created.

Or if the mapping itself in the CMS can have the ability to assign a special variable that is a placeholder for what would be the GUID/ID of the record created that could also work but may have issues, therefore with events being able to directly modify the payload/mapping data at this level, might be safer with flexible control.

**Comment by engram-design** [comment]
We don't store these values anywhere, although if you're mapping to multiple data objects, we often use one for the next. For example, it's common to map to a Contact, and the resulting contact ID is used in the Lead/Deal mapping to link it together.

The easiest way to gain access to this is by using `EVENT_AFTER_SEND_PAYLOAD`.

```php
use verbb\formie\events\SendIntegrationPayloadEvent;
use verbb\formie\integrations\crm\MicrosoftDynamics365;
use yii\base\Event;

Event::on(MicrosoftDynamics365::class, MicrosoftDynamics365::EVENT_AFTER_SEND_PAYLOAD, function(SendIntegrationPayloadEvent $event) {
    if (str_starts_with($event->endpoint, 'contacts')) {
        $contactId = $event->response['contactid'] ?? '';
    }
});
```

This event is fired on every successful payload-send for each object. There's no categorization of what request is for what object, so the easiest way is to check what the endpoint used is, then in the (raw) response back, get the info you need.

The only drawback, which might be the sticking point, is that you can't modify the already-prepped payload data for other objects, like a lead. Everything is pretty siloed. However, because we use `$contactId` in the lead, you could modify the `response['contactId']` which would override things.

It's at this point where I might suggest creating a new Integration, extending the existing `MicrosoftDynamics365` one. All the functions can still use the native one, but you can override `sendPayload()` - in case you've got a lot of customised logic you need to work through.

**Comment by jamesmacwhite** [comment]
Thanks! I looked at the payload the events, the main sticking point I found is the fact that I can grab the contactid no problem, but it's then using that in the something like the lead payload, which I don't think that can be done at the right point. You'd also technically need to jump between the Before and After event. You can use the after payload event for contact, given its created first, but then getting that into the lead data would need to be before the payload is sent, but as you say it is pretty locked down and modifying the payload after it's prepared is probably not going to be possible?

My alternative was for the mapping in the CMS to use a special placeholder value in the mapping on such fields like "Contact ID" and then in the main integration this gets populated with the actual ID during the payload stage.

If it's not something others may find useful, I may have to use a custom CRM integration, I am already having to use various events to overwrite other parts so it might be better in the long run, to give us that control.

In fairness I have found Formie and the events to be very extendable, this just may be one step too far and specific business logic.

**Comment by jamesmacwhite** [comment]
Just confirming I'll basically need to extend the original CRM integration but switch forms to use the Custom Integration via:

https://verbb.io/craft-plugins/formie/docs/developers/custom-integration

So they use the custom class that's extending the default one and copy the templates under formie/integrations/crm/microsoft-dynamics-365?

**Comment by engram-design** [comment]
Using the before/after events as you describe should be exactly the way to go!

```
$contactId = null;

Event::on(MicrosoftDynamics365::class, MicrosoftDynamics365::EVENT_AFTER_SEND_PAYLOAD, function(SendIntegrationPayloadEvent $event) {
    if (str_starts_with($event->endpoint, 'contacts')) {
        $contactId = $event->response['contactid'] ?? '';
    }
});

Event::on(MicrosoftDynamics365::class, MicrosoftDynamics365::EVENT_BEFORE_SEND_PAYLOAD, function(SendIntegrationPayloadEvent $event) {
    if (str_starts_with($event->endpoint, 'leads')) {
        $event->payload['contactId'] = $contactId;
    }
});
```

But as for extending, the exactly right, extending the current integration, so you don't have to write everything from scratch and maintaining things. There's a [user guide](https://verbb.io/craft-plugins/formie/user-guides/building-a-crm-integration-from-scratch#extending-an-existing-integration) about this.

**Comment by jamesmacwhite** [comment]
Thank you, I was just checking, taking on a bigger project, but extending the integration with a custom one seems like the best way given some of the custom requirements.

I have found you seem to be excluding some fields here:

https://github.com/verbb/formie/blob/craft-3/src/integrations/crm/MicrosoftDynamics365.php#L422-L427

One of the fields I am wanting to populate in the payload with the contact ID is under the Customer type and is currently not in the mapping. As I'm mapping it in the payload anyway, it doesn't really matter, but just curious, why is the customer type excluded.

**Comment by engram-design** [comment]
Yeah, I just suggested extending it because I know you're doing a few things with Dynamics from your other issues, so it might be worthwhile.

The reason escapes me at the moment, but I'm sure there was a reason for it. I think it might have been the complexity of the customer field, but it's something I can certainly revisit!

**Comment by jamesmacwhite** [comment]
Yeah, it does make sense. I've implemented a custom integration that extends the original Microsoft Dynamics 365 class. with some modifications and it's working well for us.

* Custom integration available to configure labelled as "Microsoft Dynamics 365 CRM (Custom)"
* Modified payload with additional relational fields mapped during payload send for certain entities.
* Different logic for field name i.e. selecting the logical name instead
* Adding in default true/false values for boolean fields for mapping purposes
* Only require SystemRequired RequiredLevel level fields (our CRM has some weird ApplicationRequired fields) but the API doesn't seem to care if you don't provide them.
* Additional service classes for making further API calls using Formie integration GuzzleClient

I could share it as a plugin if it helped others, but I get the impression this is probably too bespoke at this point. However it works for us better, but we'll just have to keep an eye on any Dynamics 365 related changes in the main class.

**Comment by engram-design** [comment]
Nice! You're honestly the expert here with Dynamics 365 compared to me (and their docs aren't amazing), so I'm really keen for any PR or modification suggestions for others to take advantage of. Only if you have the time, and have tested things of course.

I think there's certainly some things in your custom implementation that we can make use of in Formie's native integration. The only one I'm wary of is the whole schema/logical name business as described in https://github.com/verbb/formie/issues/1071

**Comment by jamesmacwhite** [comment]
Thanks! I'm not a Dynamics 365 CRM expert to be honest, but the docs are enough to allow you setup an environment in Postman for working with the APIs and then allowed me to follow through the integration class to understand the inner workings. Within our organisation we do have a CRM developer and a CRM integrator who we work with, so I'm able to consult with some more knowledgeable people! Funnily enough on average on various issues I've hit it's been the Dynamics 365 community forum that some poor person who's also hit the same issue has been able to resolve. Some of the API responses while giving you error codes are a bit cryptic!

The schema/logical name thing I want get a true Dynamics 365 expert on it, because it's just contradictory. Everything I've read suggests SchemaName should be used with OData, but I re-tested when I was implementing the custom version (as I've basically just removed the conditionals around the handle in our class and our CRM environment certainly doesn't work with SchemaName on fields that are custom, so I can certainly try and get more concrete information on this. Maybe our CRM is backwards?!
