### ISSUE TITLE
Console Command : delete sent-notifications for all forms

### ISSUE THREAD

**Issue by denisyilmaz** [verbb/formie#1259]
### What are you trying to do?

We have a lot of forms with personal data in it, for this we setup data retention rules for each form and added a cronjob to prune all submissions (running every minute).

Now we realised that sent notifications (that might include personal data as well) are not deleted with that cronjob. Digging into Formie we found `src/console/controllers/SentNotificationsController.php` and the corresponding `./craft formie/sent-notifications/delete` console command. Unfortunately this command requires a list of IDs or form handles to be added.
As we have around 23 forms and more to come, we cant ensure that this list is always up to date.

### What's your proposed solution?

Therefore it would be great if the `./craft formie/sent-notifications/delete` command would allow a `--all` argument to be added so all notifications are sent.

Would it make sense that `sent-notifications` can be delted with the same garbage collection command used for pruning submissions?

**Comment by denisyilmaz** [comment]
2min after writing this i found the setting `maxSentNotificationsAge` ... never mind.

**Comment by denisyilmaz** [comment]
Actually I found that maxSentNotificationsAge does not delete the submissions automatically, we still have to run `./craft formie/sent-notifications/delete` with the list of form IDs for this to work.

additionally i checked the database and the tab "trashed" in the CP and was able to see that even with deleted submissions are not hard deleted but only marked for deletion. When is Formie deleting this sent-notification data from the database?

**Comment by denisyilmaz** [comment]
by the way, is there a reason why i cant delete submissions/sent-notification from the CP? the Button "Delete Permanently" is disabled:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/4189607/214832466-0af9f82b-8939-40bf-a1b6-e37c462b6a6b.png">

**Comment by engram-design** [comment]
So `maxSentNotificationsAge` will only work with Craft'a garbage collection, which runs every so often, and it's not guaranteed (unless you setup `./craft gc/run`).

I can look at adding an `--all` option.

Like all other elements that are soft deleted, they are hard deleted when Craft's garbage collection is run. I can also add a `--hard-delete` option to control this if you like.

The delete button issue from the element index is fixed in the latest `craft-4` branch.

**Comment by engram-design** [comment]
Added those options for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.21](https://github.com/verbb/formie/releases/tag/2.0.21)

**Comment by denisyilmaz** [comment]
great, thanks. just updated the application.
