### ISSUE TITLE
Serialization of name field for integrations

### ISSUE THREAD

**Issue by corneliusio** [verbb/formie#126]
**Description**
Looks like the recent 1.2.15 updated refactored some serialization for integrations, however [this section](https://github.com/verbb/formie/commit/31833dd634e52de01d685c8f1b2da98e1dc1d519#diff-9c9514f6bc91076a61fb9a4b6bef9b49) doesn't check for cases where "Use Multiple Name Fields" isn't enabled, so is passed a string instead of an object with the toArray() method and errors out.

**Steps to reproduce**
1. Create integration such as Mailchimp
2. Create name field with Use Multiple Name Fields disabled
3. Assign name field to field mapping on a form for integration
4. Trigger integration with form submission.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.15
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by engram-design** [comment]
Ah, you're completely right here. This went through several iterations to get right, but should've run all the tests again. Should be fixed in [1.2.16](https://github.com/verbb/formie/releases/tag/1.2.16)
