### ISSUE TITLE
Custom Validation rules on fields in a Group/Repeater

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1267]
### Question

I'm looking to to add custom validation rules to fields within a group on a form but I'm not sure what key I should be using to target the field in an `$events->rules[]` call.

The docs example use the `field:exampleField` this however only appears to trigger when it's a field outside of a repeater and group, this doesn't match when in a group repeater. I'm unsure of the key to use to make the validation rule trigger. I'm assuming it needs to be a key that specifies the group handle first followed by the field within, but any ideas on what I should use?

I can see a Group calls validateRows which triggers validation within, but any pointers on attaching custom validator rules with group/repeater fields?

Thanks!

**Comment by engram-design** [comment]
You'll want to add rules to the `NestedFieldRow` element instead of the submission (which can be done, it's just a little more complicated).

```php
use craft\events\DefineRulesEvent;
use verbb\formie\elements\NestedFieldRow;
use yii\base\Event;

Event::on(NestedFieldRow::class, NestedFieldRow::EVENT_DEFINE_RULES, function(DefineRulesEvent $event) {
    $field = Craft::$app->getFields()->getFieldById($event->sender->fieldId);

    if ($field->handle === 'myRepeaterField') {
       $event->rules[] = [['field:mySubField'], 'required'];
    }
});
```

**Comment by jamesmacwhite** [comment]
Ah, thank you. So it's the event context that's wrong to begin with, but it makes more sense now.

It's still the same `field:fieldName` syntax but specifically targeting a nested row instead, I'll test it out, thank you!

**Comment by jamesmacwhite** [comment]
Just a follow up question. Because you need to use a different event to target the specific nested row you wouldn't be able to create a when condition that used another field on the form the nested row is on?

I'm just experimenting with groups/repeaters, but looks like if I want to do custom validation based on other fields like the docs shows with a when arrow function, it is probably better just to make them standard fields, so you can target the submission event?

**Comment by engram-design** [comment]
Sort of! You could "bubble-up" the element to get the submission from the `NestedRow` element

```php
$event->rules[] = [['field:mySubField'], 'required', 'when' => function($value) {
    if ($value->getOwner()->myOtherField === 'some-value') {
        return false;
    }

    return true;
}];
```

**Comment by jamesmacwhite** [comment]
Thank you. I'll do some more testing. Thanks for the tip

**Comment by jamesmacwhite** [comment]
Last question I promise! Fields like name and address when you have multiple fields under one i.e. for name firstName and lastName these don't exist as actual field handles as technically it is under the containing field handle i.e. say `name`, can you attach validation conditions to the subfields? You can't seem to target via field:handle, because for example if you had First Name and Last Name enabled this doesn't actually exist as `field:firstName` or `field:lastName`, although dumping the `$event->rules` on a nested row, I can see validators like `validateRequiredFields` on the containing name field so I guess it's possible, would you have to loop through the subfields and attach event rules that way? If so, how would you reference the subfield handle?

The reason I ask is because there are max length requirements for the system such data would get sent to. In some cases, you cannot set this on the form builder. Plain text fields you can, name fields, address fields you can't.

**Comment by engram-design** [comment]
With these fields, the value is a Model, rather than a primitive value like a string or int. Like a Group/Repeater field uses a `NestedFieldRow` element.

For example, a name field:

```php
Event::on(Submission::class, Submission::EVENT_DEFINE_RULES, function(SubmissionRulesEvent $event) {
    $event->rules[] = [['field:nameField'], 'required', 'when' => function($value) {
        // $value will be https://github.com/verbb/formie/blob/craft-3/src/models/Name.php
        if (!$value->firstName) {
            return false;
    }];
});
```

Here's how sub-fields are validated out of the box https://github.com/verbb/formie/blob/craft-3/src/base/SubfieldTrait.php

**Comment by jamesmacwhite** [comment]
Thank you. That's really helpful and will help with more bespoke validation rules when mixed with repeaters/combo fields! Really appreciate the code examples.

**Comment by jamesmacwhite** [comment]
Sorry for resurrecting an old issue. Since Repeater fields are no longer elements in Formie v3, is there an updated version to perform custom server-side validation on fields within a repeater, given they are no longer elements.

**Comment by engram-design** [comment]
Should just be far more simpler on the Submission, rather than a `NestedElement`:

```php
Event::on(Submission::class, Submission::EVENT_DEFINE_RULES, function(SubmissionRulesEvent $event) {
    $event->rules[] = [['field:repeaterField'], 'required', 'when' => function($value) {
        // ...
    }];
});
```

**Comment by jamesmacwhite** [comment]
Thanks! Ah right, because we are dealing with arrays, it can be done on the submission level, it is indeed simpler!
