### ISSUE TITLE
Mailchimp integration failing

### ISSUE THREAD

**Issue by corneliusio** [verbb/formie#127]
**Description**
The Mailchimp integration seems to simply fail. Tested with ActiveCampaign and it worked fine.

**Steps to reproduce**
1. Create Mailchimp integration and ensure is connected
2. Enable integration on a form with fields mapped.
3. Trigger integration with form submission.

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**

- Plugin version: 1.2.15
- Craft version: 3.5.11.1
- Multi-site: No

**formie.log**
```
2020-09-21 10:32:21 [-][1][-][error][formie] Mailchimp General: API error: “Client error: `PUT https://us2.api.mailchimp.com/3.0/lists/a5588b5797/members/0e31fe19abba06b3840914c1c95709e9` resulted in a `400 Bad Request` response:
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","stat (truncated...)
” /Users/cornelius/Git/path/to/project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
2020-09-21 10:32:16 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/queue/run'
]

$_POST = []
```

**Comment by engram-design** [comment]
Couple of things to check:
- Your API keys looks like `xxxxxxxxxxxx-us17` - can you confirm the last couple of digits are `us2`
- Can you confirm a list exists with an ID of `a5588b5797`
- What email are you using to test?
- What fields are you mapping to?

**Comment by corneliusio** [comment]
a5588b5797

**Comment by corneliusio** [comment]
Can confirm API key ends in `us2` and is the correct one from the account as well as the list ID being correct as well.

**Comment by corneliusio** [comment]
Crap, so used to hitting ctrl+enter from Slack that I keep sending comments by accident.

I've used a few of my emails as well as form filler extension in my browser that just enter random emails, but fails with real emails as well.

Currently mapping email, first name, and last name. Not including phone.

**Comment by engram-design** [comment]
Thanks for that - I note your other issue https://github.com/verbb/formie/issues/126 (which I've fixed), so wanted to check what sort of fields these are - I assume the first/last name fields are single text fields?

From what I've read online, this error seems to be when incorrect data is sent to Mailchimp

**Comment by corneliusio** [comment]
Yeah, that had occurred to me—at first, I missed it; I hadn't switched the name to use multiple fields and was still mapping the first/last name data. But did update the form and tested with those fields mapped correctly and still got the same results.

**Comment by engram-design** [comment]
Wondering if you can try again with the following updates:

To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.15",
  "...": "..."
}
```

Then run `composer update`.

This should add some more info to the logs about the payload being sent, which I'm interested in.

**Comment by corneliusio** [comment]
Alright, so you mentioned that you added the payload to the logging—I don't know if you made any other changes, but it IS working for me now so I'm assuming you did? Either way, something changed that fixed it. Possibly just the composer update? Maybe there was some other dep that was the source of the issue.

**Comment by corneliusio** [comment]
Also noticed you updated the field mapping to take into account using multiple fields for some inputs. That's great, thanks!

**Comment by engram-design** [comment]
I have a feeling it was related to https://github.com/verbb/formie/issues/126 so that's good!
