### ISSUE TITLE
Add a `--before` parameter to the submissions bulk-delete console command

### ISSUE THREAD

**Issue by Kashkin** [verbb/formie#1271]
### What are you trying to do?

Clients sometimes like to clear out submissions older than X months/years.

There's currently not a great way of doing this, other than changing the data retention for each form.

### What's your proposed solution?

If possible, it would be great if the [Bulk Delete command](https://verbb.io/craft-plugins/formie/docs/developers/console-commands#delete-submissions) supported a datetime string as a paramater.

`./craft formie/submissions/delete --form-handle=form1,anotherForm --before="2023-01-01 00:00:00"`

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
