### ISSUE TITLE
Phone number field - Allowed countries is not saved when you click on Apply

### ISSUE THREAD

**Issue by smcyr** [verbb/formie#1285]
### Describe the bug

When creating a phone number field and adding countries to the "Allowed Countries" under "Country Code Dropdown", the countries are not saved when you click on "Apply" and come back to the "Edit field".

### Steps to reproduce

1. Create a phone number field
2. Add countries to the "Allowed countries"
3. Click on Apply
4. Modify the field and notice and that the "Allowed countries" is empty.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.2.1

### Plugin version

2.0.21

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by smcyr** [comment]
It's good now, thanks!
