### ISSUE TITLE
Copper integration is failing

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1293]
### Describe the bug

- I've set up an integration with Copper, using the API key and an email address
- The integration has a green circle
- I've got a subscribe form at the bottom of https://theengineisred.com
- We only have an email field, which I've mapped to the email field in "Lead Field mapping" but also "Name", because it says that field is required

![image](https://user-images.githubusercontent.com/1250017/218149471-5cd486ed-32d4-4a42-846f-f56a7a2cf661.png)

When you submit the form, I get this error message:

![image](https://user-images.githubusercontent.com/1250017/218149736-4ff57eed-d004-41c9-a099-5558eaa20933.png)

Details:

![image](https://user-images.githubusercontent.com/1250017/218149832-eb173b4b-77db-4113-ad41-5fa2c31a9f59.png)

### Steps to reproduce

Set up a form with a Copper integration with only an email address

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.8.2

### Plugin version

2.0.21

### Multi-site?

No

**Comment by engram-design** [comment]
Can you confirm if the lead is actually added to Copper? Looking at this looks like a typo with the check that it was added successfully, but you can see in the error message that it actually shows a valid response from the API.

Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.22](https://github.com/verbb/formie/releases/tag/2.0.22)

**Comment by darylknight** [comment]
Now that I've deployed this update, the connection to Copper has broken completely. It's showing as "not connected" and if I click "Refresh" in the sidebar, I get this:

![image](https://user-images.githubusercontent.com/1250017/218420520-75df4493-133f-4b3f-9a92-171afd2a9dc0.png)

**Comment by engram-design** [comment]
Hmm, this was certainly a minor fix so it shouldn't have been a drastic change. I've just tested this with an expired Copper account and received this same error. Creating a new account (I was just on a trial for testing) connects just fine. 

I would double check or re-generate the API key before going too much further.

**Comment by darylknight** [comment]
Ok, thanks - I'll get my boss to send over a new key and test it with that.
