### ISSUE TITLE
Feed Me Import Submissions: Allow dateCreated value to be set via imported data

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1297]
### What are you trying to do?

Something which might be useful for backfilling or migrating data and maintaining it's original date would be when importing submissions to allow you to set the dateCreated value to be something in the past, rather than when the submissions is created.

For example if you had a date/time value from another system, this could be mapped in the feed import to make the creation date align to the originals system.

Currently the dateCreated is the value of when the submissions was first saved from the Feed Me import process, which will be whatever time it was ran.

### What's your proposed solution?

Add date created to the mapping and allow it to be set in the import process, which will then be used, rather than the date/time value that is populated when the element is created.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.23",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Amazing thank you!

**Comment by engram-design** [comment]
Updated in [1.6.24](https://github.com/verbb/formie/releases/tag/1.6.24)
