### ISSUE TITLE
GraphQL headless, always receiving: "Failed Captcha “Recaptcha”: “Client-side token missing.”"

### ISSUE THREAD

**Issue by zsavajji** [verbb/formie#1298]
### Describe the bug

Hi, 
i'm trying to submit a form from an headless website, using the gQL API.
I set up the Recaptcha V2 invisible integration, added the keys and configured my requests accordingly, but the CMS seems not to understand my reCAPTCHA response, disregarding it completely.
The request contains the recaptcha response as you can see, but i always get the "Client-side token missing" error as a response.

I also can see that in my request for the form fields, nothing gets returned in the `captchas` field.

Am i doing something wrong? 🤔 

![image](https://user-images.githubusercontent.com/6460348/218443319-e9d4eaac-0ca3-46e9-a79a-9e59b9224bb4.png)

![image](https://user-images.githubusercontent.com/6460348/218443341-e03c67b3-e270-4c52-b9f0-fdf25dc6d9ef.png)

### Steps to reproduce

1. Create a form with reCAPTCHA v2 invisible integration
2. Mutate with a gQL request
3. Error gets thrown

### Form settings

- Multi-page form: No
- Submission Method: GraphQL
- Client-side Validation: /
- Custom Form Templates: No

### Craft CMS version

4.3.82

### Plugin version

2.0.22

### Multi-site?

Yes

**Comment by engram-design** [comment]
> I also can see that in my request for the form fields, nothing gets returned in the captchas field.

This is correct for the moment, there's nothing you need from the server. We'll probably add the client-side token for Recaptcha so you don't have to manage that in multiple places.

I believe the key is incorrect, as it should be `recaptchaCaptcha` not just `recaptcha` (see an [example](https://github.com/verbb/formie/issues/1239#issuecomment-1396235789))

**Comment by zsavajji** [comment]
@engram-design Thanks, i see.

The key is correct, the `recaptcha` field is only sent as variable, the request gets made with the `recaptchaCaptcha` field set. 
I would receive a gQL error if that was the case :(

Thanks

**Comment by engram-design** [comment]
Ah, I see. I assumed that screenshot was of the payload data sent to the server, in which case that would be incorrect. The variable must be named `recaptchaCaptcha` in the variable data sent to the server.

If you'd like to confirm that the variable is accessible from the server, add the following line [here](https://github.com/verbb/formie/blob/b3f7ef427a720e5a09d96bf2da21e12a3b12e332/src/base/Captcha.php#L132)

```php
Craft::dd(Craft::$app->getRequest()->getParam('variables'));
```

To see what variable params are reaching the server.

**Comment by zsavajji** [comment]
Damn it, you were right all along.
I assumed that the variable name would be replaced in the query, but my client does not for objects.

The culprit was indeed the variable naming.

Sorry for wasting your time!
