### ISSUE TITLE
Add document on using the  `Forms (formie)` field

### ISSUE THREAD

**Issue by hongc-cc** [verbb/formie#130]
Document is missing on how to use the field.
eg
`formfield.one()`
`formfield.one().id`
`{{ craft.formie.renderForm(formfield.one().handle) }}`

**Comment by TomDeSmet** [comment]
If I may add my two cents on this. This doesn't seem to be related to Formie. This is just basic Craft CMS Twig syntax which applies to all Craft fields so shouldn't really be part of the Formie docs per se?

**Comment by engram-design** [comment]
The form field returns a form element query, which is the same as any other element field out there. I would've thought this to be pretty clear given people coming from Freeform, Sprout and being used to other element fields like entries.

But just to give people the benefit - https://verbb.io/craft-plugins/formie/docs/template-guides/element-fields
