### ISSUE TITLE
Date form field formatting for integration settings

### ISSUE THREAD

**Issue by sanderpotjer** [verbb/formie#1300]
### Describe the bug

The selection of the date field options, for example "year", "month", "day" in the FieldMapping options are not taken into account  for integrations:
<img width="291" alt="Schermafbeelding 2023-02-13 om 15 56 22" src="https://user-images.githubusercontent.com/522834/218493507-4c6bdd3a-0ed5-4838-9485-8ba9c4d1aa7d.png">

For each of the field mappings the full datetime is used (e.g. `2020-01-02T00:00:00+00:00`) for the submission data.

I expect the mapping is using the settings, so when selecting `{Field Name}: Year` as "Form Field" setting I expect `2020` to be submitted to the integration as field value. 

### Steps to reproduce

1. Create Date/Time form field, of Display Type "Dropdowns", e.g. label "Date of Birth"
2. Setup integration to with field mapping to send "Date of Birth: Year"
3. Check the full datetime is submitted, instead of year only

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.8.2

### Plugin version

2.0.22

### Multi-site?

No

### Additional context

Using a custom integration of type CRM, but similar for any mapping of fields.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by sanderpotjer** [comment]
@engram-design thanks! Can confirm it fixed the issue.
