### ISSUE TITLE
Add Friendly Captcha

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1301]
https://friendlycaptcha.com/

**Comment by gglnx** [comment]
@engram-design Do you have timeline when Friendly Captcha will be integrated? I have a client which is using it and would like to switch to Formie.

**Comment by engram-design** [comment]
No timeline yet sorry, still looking into it!

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Added in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
