### ISSUE TITLE
Update league/html-to-markdown?

### ISSUE THREAD

**Issue by kringkaste** [verbb/formie#1302]
### Question

Would it be possible to upgrade the dependancy package league/html-to-markdown to the current 5.x version. The 4.x version from this plugin conflicts with other plugins that have already upgraded. Version 5 was released in March 2021. That would be very nice.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by kringkaste** [comment]
Thanks! :)
