### ISSUE TITLE
Hubspot array type mapped field returns id's instead of titles

### ISSUE THREAD

**Issue by jodeba** [verbb/formie#1303]
### Describe the bug

Now that issue #1272 is fixed, I found a new issue:

When a relation field is mapped to a multiple checkbox field in Hubspot, only the id's of the Entries are send.

I found this line is responsible:
https://github.com/verbb/formie/blob/2bb5a6e479591bb59ebb4abee52beabe2c098017/src/base/RelationFieldTrait.php#L383

Instead of the entry id's, the title's should be send. Because the entry-id's are unknown to Hubspot.

### Steps to reproduce

1. 'Element' type form field with Entry sources selected
2. Submission with one or more related Entries selected
3. Map to Hubspot integration field of type 'multiple checkboxes'
4. Trigger Hubspot Integration

### Form settings

- Multi-page form: -
- Submission Method: -
- Client-side Validation: -
- Custom Form Templates: -

### Craft CMS version

4.3.8.2

### Plugin version

2.0.22

### Multi-site?

Yes

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by jodeba** [comment]
looks good, thanks!

**Comment by engram-design** [comment]
Updated in [2.0.23](https://github.com/verbb/formie/releases/tag/2.0.23)
