### ISSUE TITLE
Error on empty Schedule Start Date

### ISSUE THREAD

**Issue by kringkaste** [verbb/formie#1304]
### Describe the bug

If you just enter a Schedule End Date and the Schedule Start Date is empty, you get an Exception when rendering the form:

"Call to a member function getTimestamp() on bool"

### Steps to reproduce

Add a form an schedule the end of the form and leave the start date empty.

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.8.2

### Plugin version

2.0.22

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by engram-design** [comment]
Updated in [2.0.23](https://github.com/verbb/formie/releases/tag/2.0.23)
