### ISSUE TITLE
Setting max length on non plain text fields

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1305]
### Question

So something that's recently come up is the fact our CRM has field length requirements. Interestingly these are inconsistently applied as I tested some payloads larger on some fields and it doesn't care, but it does appear to be something in play on some fields.

Example error:

> API error: “{"error":{"code":"0x80044331","message":"A validation error occurred. The length of the 'address1_postalcode' attribute of the 'contact' entity exceeded the maximum allowed length of '20'."}}” /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

This means that Formie ideally needs to enforce this validation, however outside plain text fields, it doesn't appear there is a max length option within Formie itself. In this example, this is an address field using the postcode sub field, but you cannot directly set a max length. Is this something we'd need to enforce with custom validation rules?

**Comment by jamesmacwhite** [comment]
Not sure if this is the right approach

```php
Event::on(Submission::class,
Submission::EVENT_DEFINE_RULES,
static function(SubmissionRulesEvent $event) {

      if ($field instanceof Address) {
          $event->rules[] = [['field:addressInformation'], 'string', 'message' => 'Postcode must be a maximum of 20 characters', 'when' => function($value) {
              return strlen($value->addressInformation->zip) > 20;
          }];
      }
});
```

**Comment by jamesmacwhite** [comment]
Not sure what the best approach is with max length, if I set it directly on the rule, I get "field must be a string" I assume because it is not actually targeting the model value, but the above does work with a message override, if I write a condition that basically returns true on the strlength

**Comment by engram-design** [comment]
That's an appropriate way to do that, although things like postcode are valid to be enforced within Formie itself, not just a custom validator - which I've added for the next release. I would also add a numeric check, but some countries (like the UK) contain letters.

To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.23"`

**Comment by jamesmacwhite** [comment]
Thank you! There's some other interesting max lengths on the CRM side, which I'll implement as custom validators, because... Microsoft apparently!

**Comment by engram-design** [comment]
Okay - well any that make sense to be in core, happy to add them in

**Comment by jamesmacwhite** [comment]
I don't think any of these make any logical sense personally, but just for a developer laugh here's what I've found:

Contact entity:

* First name and last name max 50 chars
* Date of birth minimum 01/01/1753
* Email address max 100 chars
* Address Line 1,2,3 max 250 chars
* City 80 chars
* Postcode 20 chars
* Home number max 50 chars
* Mobile number max 20 chars

Lead entity:

* First name and last name 100 chars (Not sure why contact is less, but ok...)
* Description max 1048576 (LOL good luck exceeding this. Even a spam bot would give up).

Organisation entity:

* Name max 999 chars (I mean why at this point?!)
* Postcode max 20 chars

And they are just the one's I know of by using them. It is safe to say we will implement these directly, just by targeting the field type i.e. `Name` or `Address` and pass whatever the field handle is down, so it means any form that may be CRM enabled has these limits, so will any form, but not really a way around it. We have to essentially validate as if it was all going to CRM. This was detected because it looked like a form got submitted with a bit of a wonky autofill where address line 1 went into the postcode field and exceeded 20 chars, triggering that. I then sent some payloads on a few fields and started to find these limits.

I was looking at a way to obtain the max lengths but they weren't on the Entity definitions but I'll see if there is a way. Edit: There is, through the CRM itself and customisations.

Either way though, custom validators should be fine! This is highly likely to be specific to our CRM environment too.

**Comment by engram-design** [comment]
Updated in [1.6.24](https://github.com/verbb/formie/releases/tag/1.6.24)
