### ISSUE TITLE
Elements integration and Redactor/Rich Text field

### ISSUE THREAD

**Issue by HannahDeWachter** [verbb/formie#1306]
### Describe the bug

I made a form with an Element intergration which makes an Entry once the form is submitted. This form has a "Multi-line Text" field with Rich Text options (bold, italic, link). The content of this field gets mapped on a Redactor field in the Entry. The HTML-tags of this content gets escaped when mapping it to the Entry, which causes it to print those HTML-tags in the frontend. This is not ideal!

**Submission:**
<img width="765" alt="Screenshot 2023-02-16 at 16 37 36" src="https://user-images.githubusercontent.com/55497252/219413970-9c6bcd1b-48ef-4aff-ac11-5ba8017c396a.png">

**Backend entry:**
I also mapped the Multi-line/Rich Text field to a Plain Text field to see what would happen.
<img width="773" alt="Screenshot 2023-02-16 at 16 14 39" src="https://user-images.githubusercontent.com/55497252/219411035-a25ec123-ce2d-486f-b1bc-8cf969e80ce1.png">

**Frontend:**
<img width="941" alt="Screenshot 2023-02-16 at 16 30 06" src="https://user-images.githubusercontent.com/55497252/219411593-0328c668-3897-4221-8f21-33b6fddf5e2c.png">

Is it possible to not escape the HTML-tags, so that we don't have HTML-tags on the frontend? I always have the "Purify HTML" option enabled on our Redactor field. 

I also tried enabling other Clean up HTML options, but this didn't resolve this issue.
<img width="715" alt="Screenshot 2023-02-16 at 16 33 53" src="https://user-images.githubusercontent.com/55497252/219412925-7597703e-f2d6-4cda-af61-f888ca136fdf.png">

### Steps to reproduce

1. Have a form with a "Multi-line Text" field with Rich Text options.
2. Add an Element intergration to this form.
3. Map the Rich Text field to a Redactor field.
4. Fill in the form.
5. Have a look at the Entry.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Custom Form Templates: Yes

### Craft CMS version

4.3.6.1

### Plugin version

2.0.21

### Multi-site?

Yes

### Additional context

I also use the Redactor plugin

**Comment by engram-design** [comment]
There's a good reason we escape HTML for rich text, to prevent XSS attacks. We can make allowances for this specific case though.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by engram-design** [comment]
Updated in [2.0.23](https://github.com/verbb/formie/releases/tag/2.0.23)

**Comment by HannahDeWachter** [comment]
@engram-design This works! Thanks!
