### ISSUE TITLE
Repeater Row Count

### ISSUE THREAD

**Issue by masonry47** [verbb/formie#1308]
### Question

Hi there!  We were wondering about the feasibility of displaying the row number of a "Repeater" field.  So...as repeater rows are added we are dynamically displaying the row number along side the fields nested within the "Repeater" field.  Like this 

![Screen Shot 2023-02-16 at 11 52 25 AM](https://user-images.githubusercontent.com/48130527/219448066-18fc870e-a8e1-4dbc-866b-66ddaf55d54d.png)

We are exploring using some javascript but did not know if perhaps there was a better way with maybe the HTML field and use Twig somehow to count the row numbers?

Thanks in advance for any info!

**Comment by engram-design** [comment]
Yep, best to use some JS to listen to the add/remove events on a repeater, and use JS to insert the number in the row. You can't really not use JS as adding/removing rows is done via JS.

```js
// Fetch all Repeater fields
let $fields = document.querySelectorAll('[data-field-type="repeater"]');

// For each field, bind on the `append` event
$fields.forEach($field => {
    $field.addEventListener('append', (e) => {
        console.log($field.querySelector('[data-repeater-row]').length);
    });
});
```

**Comment by masonry47** [comment]
Thanks!  That is where we were  headed but this is really helpful.   We are successfully counting the rows but any advice on the actual displaying the number into the rows?  Thanks again!

**Comment by engram-design** [comment]
I suppose that's entirely up to the UI you want to achieve.

```js
// Fetch all Repeater fields
let $fields = document.querySelectorAll('[data-field-type="repeater"]');

// For each field, bind on the `append` event
$fields.forEach($field => {
    const updateCount = function() {
        // For each row element in the field...
        $field.querySelectorAll('[data-repeater-row]').forEach(($row, index) => {
            let $rowCount = $row.querySelector('.row-count');

            // Get or create a div to contain the row count
            if (!$rowCount) {
                $rowCount = document.createElement('div');
                $rowCount.className = 'row-count';

                $row.prepend($rowCount);
            }

            $rowCount.innerHTML = index + 1;
        });
    }

    // Update the count immediately for any static rows or validation errors
    updateCount();
    
    // Update the count for adding/removing rows
    $field.addEventListener('append', (e) => {
        updateCount();
    });

    $field.addEventListener('remove', (e) => {
        updateCount();
    });
});
```

**Comment by masonry47** [comment]
Thanks again!
