### ISSUE TITLE
How to pass additional form data to Stripe?

### ISSUE THREAD

**Issue by MattAppleton** [verbb/formie#1309]
### Describe the bug

We need to pass a form value ( {event} handle in this instance ) to Stripe for our clients accountants, so they know WHAT has been paid for...

I guess that might be possible on the 'Settings' tab, as per this screenshot...

<img width="1552" alt="Zircon-Screenshot 2023-02-17 at 12 07 04" src="https://user-images.githubusercontent.com/6295710/219651952-2356f806-338c-4b9c-9774-f202bff83d91.png">

but so far my Stripe transaction just gives me this version of the metadata (see screenshot below)

I can see any detail on this on the documentation, perhaps we are doing this wrong?

The field is called 'Events Applied For' and the handle is 'event'

<img width="508" alt="Zircon-Screenshot 2023-02-17 at 12 19 33" src="https://user-images.githubusercontent.com/6295710/219652205-3b1f6826-e992-4df2-a13d-a20eb17fe76f.png">

### Steps to reproduce

1. Attempt to add extra field value into the metadata passed to Stripe in the payment/settings tab...
2. Make a payment
3. Check Stripe Metadata

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: ?? Stripe
- Custom Form Templates: No

### Craft CMS version

4.3.5

### Plugin version

2.0.22

### Multi-site?

Yes

### Additional context

We have Blitz installed, and the site uses Barba.js

**Comment by engram-design** [comment]
At the moment, metadata is restricted to static text, and cannot reference other fields' content from your form fields. You can only use an event on a module to alter this.

```php
use verbb\formie\integrations\payments\Stripe;
use verbb\formie\events\ModifyPaymentPayloadEvent;
use yii\base\Event;

Event::on(Stripe::class, Stripe::EVENT_MODIFY_SINGLE_PAYLOAD, function(ModifyPaymentPayloadEvent $event) {
    $event->payload['metadata']['myField'] = $event->submission->getValue('someField');
});
```

**Comment by MattAppleton** [comment]
managed to add the event into the Stripe Description this way... solved without having to get into additional module work...

<img width="1012" alt="Halite-screenshot 2023-02-17 at 23 56 16-2023-02-17" src="https://user-images.githubusercontent.com/6295710/219818476-fb5a8df2-ada5-409a-b80b-bac7ea91e8bb.png">
