### ISSUE TITLE
Missing filename checks on upload fields

### ISSUE THREAD

**Issue by nilsenpaul** [verbb/formie#1310]
### Describe the bug

When we add an upload field to a form, and a user submits a file name with a 'corrupt filename', an error is thrown:

<img width="772" alt="screenshot-issue" src="https://user-images.githubusercontent.com/6794819/219663397-ef926fe4-46f7-410e-af23-ad858872bcc6.png">

This happens, for instance, with screenshots that have a filename containing multiple period characters (`Scherm­afbeelding-2023-02-15-om-10.56.44.png`).

### Steps to reproduce

1. Add an upload field to a form
2. Try to upload and submit a file with this name: `Scherm­afbeelding-2023-02-15-om-10.56.44.png`

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.9

### Plugin version

2.0.22

### Multi-site?

No

**Comment by engram-design** [comment]
I can't seem to replicate that with the same named file, sorry. What are your asset volume settings? This seems to be coming from the Flysystem setting. Would you be able to provide the full stack trace so I can trace where the error is coming from in the lifecycle of things?

Under the hood, the File Upload field extends Craft's Assets field, so everything about file upload handling should be identical.

Another option is to use the "Rename file" setting for the field to see if that helps, just to test?
