### ISSUE TITLE
Cannot redeclare execute()

### ISSUE THREAD

**Issue by jorisnoo** [verbb/formie#1316]
### Describe the bug

Since the latest update, when submitting a form the following errors are thrown:

```
PHP Compile Error
Cannot redeclare verbb\formie\jobs\TriggerIntegration::execute()
``` 
as well as `Cannot redeclare verbb\formie\jobs\SendNotification::execute()`

### Steps to reproduce

1. Create a form with an integration or notification
2. Submit

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates:No

### Craft CMS version

4.3.10 

### Plugin version

2.0.23

### Multi-site?

No

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [2.0.23.1](https://github.com/verbb/formie/releases/tag/2.0.23.1)
