### ISSUE TITLE
Changing the status of a submission can delete some content.

### ISSUE THREAD

**Issue by stuh** [verbb/formie#1319]
### What are you trying to do?

Stumbled upon an issue and subsequently a workaround for this problem which I've encountered a few times during developing a job application system with this plugin. Not sure if this is a feature request or bug or maybe just notice to anyone else who stumbles across this issue as it threw us for a bit.

A simple test case for the the problem described in the title is ...

1. Create a new status in settings called 'Viewed'
2. Create a form with a customer hidden field with the handle vacancyTitle 
3. When we show the form to the user we pre-populate the hidden field with 
` {% do craft.formie.populateFormValues(form.handle, { `
`            vacancyTitle: vacancy.title,`
`          }) %}`

4. When we change the Status of the submission in admin with the 'All Forms' filter selected to 'Viewed'. The status updates but the vacancyTitle is deleted from the submission.

Now if we change the 'All forms' filter to narrow the submissions query to the form and update the status - it all works. As does drilling down into the submission edit page and changing status there. 

Also when we do this from a template using...
`{% set submission = craft.formie.submissions.uid(submissionId).one() %}`
`  {% do submission.setAttributes({statusId: 2}, false) %}`
`  {% do craft.app.getElements().saveElement(submission) %}`

It again clears the data. but if we include the form directly in the query it works as expected 
`{% set submission = craft.formie.submissions.form(entry.onlineApplicationForm.one()).uid(submissionId).one() %}`
`  {% do submission.setAttributes({statusId: 2}, false) %}`
`  {% do craft.app.getElements().saveElement(submission) %}`

We can workaround this by removing the 'All forms' option from the Submissions list in 'Customize sources' and by including the form in the submission query before the saveElement call. We also had difficulty showing form data with a list of submissions until we added the form to the query. This made it a bit tricky to show a list of submissions across all forms.

`{% set submissionsQuery = craft.formie.submissions() %}`
`{% set submissions = submissionsQuery.all() %}`
`{% for submission in submissions %}`
`    <p>{{ submission.title }}</p>`
`    <p>{{ submission.vacancyTitle}}</p> <---- does not work`
`{% endfor %}`

We got around this in the end by using multiple submission queries to all our forms and merging before displaying in one list.

### What's your proposed solution?

This is not a huge issue and I can understand how this is happening due to submissions having different types with craft. I just wanted to put it up here as it's not immediately obvious to a simpleton user like myself. Perhaps a note or example in the docs would be handy. Great plugin, saved us a ton of time. 👍

**Comment by engram-design** [comment]
Yeah, so this is one of the annoying issues with submissions having their own content table. There's no real way at the moment to change the content table based on the element that's encountered in the query. For example, when you look at "All forms" submissions, it'll have to switch between content tables for each submission it finds. Element queries only support setting the content table once for the entire element query.

However, it _certainly_ shouldn't be removing content setting the status like that, or saving the element.

Now, I can't replicate your Twig example:

```twig
{% set submission = craft.formie.submissions.uid(submissionId).one() %}
{% do submission.setAttributes({statusId: 2}, false) %}
{% do craft.app.getElements().saveElement(submission) %}
```

As that will always work. You're grabbing a single instance of a submission, which will be able to determine its content table, even without the form. A submission contains a reference to the form it was used, and the form is where the content table that should be used is defined. As such, I can't replicate that - is there something more to your templates?

If, however - you're doing something like this:

```twig
{% set submissions = craft.formie.submissions.limit(10).all() %}

{% for submission in submissions %}
    {% do submission.setAttributes({statusId: 2}, false) %}
    {% do craft.app.getElements().saveElement(submission) %}
{% endfor %}
```

Then that indeed will be an issue. The element query will find all the submissions potentially across multiple forms, but would have to join the content tables depending on what form the submission is for, which isn't currently possible. It's not ideal, but re-fetching the submission within the loop is the way to get around this.

```twig
{% set submissions = craft.formie.submissions.limit(10).all() %}

{% for submission in submissions %}
    {% set submission = craft.formie.submissions.uid(submission.uid).one() %}
    {% do submission.setAttributes({statusId: 2}, false) %}
    {% do craft.app.getElements().saveElement(submission) %}
{% endfor %}
```

I wish this weren't the case, but we'll figure out a solution someday soon, along with Craft querying across multiple element types.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.23.1"`

**Comment by stuh** [comment]
Thanks for this Josh, I completely understand the problem and the predicament now. Your last example there is actually what I should be doing in a few places where we have come up against this problem, it makes sense: use the loop submission as a reference to pull out a single submission. A bit less performant but this will be a low traffic system anyway. 

As for the twig template statusId update, it's definitely just using the first version ( .one() )as opposed to pulling from a query of submissions ( .all() ) .  It's not an issue though as we just pass it the form which we know from a related field on the main page's entry and all is well.  Thanks again for your attention on this.

**Comment by engram-design** [comment]
Hmm, thanks for clarifying, I'll keep at it to see if I can reproduce it

**Comment by stuh** [comment]
If I get a chance tomorrow I'll put together a reduced example of it for you. 👍
