### ISSUE TITLE
Require minimum Craft version 3.5 upon installing Formie -> craft\helpers\Json::isJsonObject()

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#132]
When installing Formie on Craft 3.4, this error shows up when using the Recipients field:
`Call to undefined method craft\helpers\Json::isJsonObject()`

This is due to the `isJsonObject` function only being added in 3.5.

**Comment by engram-design** [comment]
Fixed in [1.2.17](https://github.com/verbb/formie/releases/tag/1.2.17)
