### ISSUE TITLE
Captcha enhancements should be disabled by default

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1320]
### What are you trying to do?

Whenever I install Formie on a new site and get the front end template working, I get this error message:

![image](https://user-images.githubusercontent.com/1250017/220362621-c3331e32-d651-442b-87e9-0ed17d055e19.png)

It looks like this is because all the Captcha methods are enabled by default:

![image](https://user-images.githubusercontent.com/1250017/220362712-1232f0e5-e302-4f76-a9cc-6767b43c2c72.png)

### What's your proposed solution?

Given that reCAPTCHA and hCaptcha require signing up for external services, they should be disabled by default.

**Comment by engram-design** [comment]
If you disable the captchas at the plugin level (Formie > Settings > Captchas) they are not enabled on any new forms that you create. Or, do you mean that you want them enabled/available, just not "switched on" by default when you create a new form?

I'm not a massive fan of splitting behaviour based on whether it's an external service or not (so some captchas would be on already, others not), so we'd need to do this for all captchas. It's a change in behaviour, and we'd probably need to add another setting for "Enabled for new forms" or similar, in addition to whether the captcha is enabled globally. It's probably more in line with how other integrations act anyway, which are an opt-in process. Captchas are just far more commonly used on every form than other integrations.

If I've understood things correctly?

**Comment by darylknight** [comment]
What I'm suggesting is that when you first install the plugin, they should be switched off by default under Formie > Settings > Captchas. So in the list, but with a white circle instead of a green one. So it would look like this:

![image](https://user-images.githubusercontent.com/1250017/220556414-dd5bbd22-e9b5-4839-a90d-87885b249654.png)

We can also just update our standard boilerplate to use environment variables and set them on/off there. I just think it's confusing that when you first install and use Formie, the first thing you see is an error message that hCaptcha failed to initialize. I'd never heard of hCaptcha before, I hadn't turned it on, so I didn't know why I was seeing an error about it. It took me a while to find out what it was, realise there's a setting in Formie for it, and that that it was enabled by default without settings, which is why it was showing an error.

**Comment by engram-design** [comment]
Oh, well **that's** strange - they certainly aren't supposed to be enabled globally by default! I've just installed Formie on a fresh Craft install, and those are certainly not enabled by default.

Not sure if you've copied project config files from one project to another - maybe? Was this for Formie 2.x?

**Comment by darylknight** [comment]
No, I just created a new empty Craft site, installed Formie as the only plugin, and all the captchas are enabled:

https://user-images.githubusercontent.com/1250017/220590867-067ef578-0a38-4da2-ac14-c2af1021d0b3.mov

Also verified that there is no config/formie.php file that could affect this

**Comment by engram-design** [comment]
Ah, my mistake - I was testing on a Craft 3 install with Formie 1. That's indeed a bug with Formie 2.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.23.1"`

**Comment by darylknight** [comment]
Thank you :)

**Comment by engram-design** [comment]
Updated in [2.0.24](https://github.com/verbb/formie/releases/tag/2.0.24)
