### ISSUE TITLE
recaptch shows hcaptcha message

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#1322]
### Describe the bug

This could be because I have multiple captchas enabled during testing.

![image](https://user-images.githubusercontent.com/25124/221461870-13fec29e-8886-4711-93db-f77a353702e1.png)

### Steps to reproduce

Create a form with both recaptcha and hcaptcha enabled

### Form settings

-

### Craft CMS version

4.4 beta.3

### Plugin version

2.0.23.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
This would be due to the `recaptchacompat` setting for [`Hcaptcha`](https://docs.hcaptcha.com/configuration/) as the two aren't really designed to be run together.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.23.1"`

**Comment by engram-design** [comment]
Updated in [2.0.24](https://github.com/verbb/formie/releases/tag/2.0.24)
