### ISSUE TITLE
Exporting with no submissions under a form throws an unhandled error

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1323]
### Describe the bug

This is a minor bug, but when attempting to export submissions from a form with no submissions, an unhandled exception is thrown.

> ValueError /vendor/verbb/formie/src/elements/exporters/SubmissionExport.php
max(): Argument #1 ($value) must contain at least one element

Potentially just needs to be a bit more defensive to check for at least one submission.

### Steps to reproduce

1. Go to submissions of a form which has no submissions
2. Use the export function
3. A server error is thrown

### Form settings

N/A

### Craft CMS version

3.7.65

### Plugin version

1.6.24

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.24"`

**Comment by jamesmacwhite** [comment]
Thanks!

**Comment by engram-design** [comment]
Updated in [1.6.25](https://github.com/verbb/formie/releases/tag/1.6.25)
