### ISSUE TITLE
Undefined array key "*" when querying dropdowns via GraphQL

### ISSUE THREAD

**Issue by jamesedmonston** [verbb/formie#1327]
### Describe the bug

I'm running into an issue when trying to query dropdown fields via GraphQL:

```json
{
  "errors": [
    {
      "debugMessage": "Undefined array key \"label\"",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "file": "/var/www/html/vendor/verbb/formie/src/gql/types/KeyValueType.php",
      "line": 15
    }
  ]
}
```

Example query:

```graphql
query Form {
  form(id: 394931) {
    ... on healthAssessment_Form {
      id
      title
      fields {
        id
        ... on Field_Dropdown {
          options {
            label
          }
        }
      }
    }
  }
}
```

The error stops occurring when removing the `... on Field_Dropdown` subset.

### Steps to reproduce

1. Create a form
2. Add a drodown field
3. Try to query the options via GraphQL:
```
fields {
  ... on Field_Dropdown {
    options {
      label
      value
    }
  }
}
```

### Form settings

- Multi-page form: No
- Submission Method: GraphQL
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

3.7.67

### Plugin version

1.6.25

### Multi-site?

Yes

### Additional context

Control Panel JS	2.4.0
Control Panel Nav	3.0.17
DigitalOcean Spaces Volume	1.1.3
Download Assets	1.0.2
Field Manager	2.2.5
Formie	1.6.25
GraphQL Authentication	1.12.3
Jason	2.0.1
Logs	3.0.5
Maps	3.9.4
Notes	1.0.6
Redactor	2.10.11
Super Table	2.7.4
Two-Factor Authentication	2.10.1

**Comment by engram-design** [comment]
Can't seem to replicate that for myself I'm afraid.

https://share.cleanshot.com/sFvRfB8H and https://share.cleanshot.com/DTwT7mXM

**Comment by jamesedmonston** [comment]
@engram-design thanks for checking! We do have a ton of custom business logic on this site, so it's likely to be something we've done.

**Comment by jamesedmonston** [comment]
@engram-design we've narrowed it down to having the `optgroup` option selected on one of the options.

Having that enabled causes the query to error. Disabling it then causes an error when saving the form; until you've added a value – you can successfully save with a blank value after saving with a value.

https://user-images.githubusercontent.com/4851924/222746822-a2b36c06-6b74-4d92-a406-8a0d3e9a40f9.mov

**Comment by engram-design** [comment]
Thanks for investigating! Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.25"`.

**Comment by engram-design** [comment]
Updated in [1.6.26](https://github.com/verbb/formie/releases/tag/1.6.26)
