### ISSUE TITLE
Zoho CRM integration updates Account Name field incorrectly

### ISSUE THREAD

**Issue by mkrigsman** [verbb/formie#1330]
### Describe the bug

When Formie sends data to Zoho CRM, it does not correctly update the Account Name field correctly in either the Contacts module or the Accounts module. 

In the Contacts module, the company field looks like this after being sent from Formie:
**["company"]**

In the Accounts module of Zoho CRM, the Account Name field gets entered twice:
**["company"]
company**

### Steps to reproduce

1.  Enable integration with Zoho CRM and map a field to Account Name

2.  Fill out form in Formie

### Form settings

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

### Craft CMS version

Craft Pro 4.3.10

### Plugin version

2.0,24

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`. Do note you'll need to refresh the integration in your form settings and save the form. This is because the mapped-to field definitions have updated.

**Comment by engram-design** [comment]
Updated in [2.0.25](https://github.com/verbb/formie/releases/tag/2.0.25)
