### ISSUE TITLE
Theme Config: Cannot set HTML attributes on alert form tags

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1335]
### Describe the bug

[Per the Theme Config docs](https://verbb.io/craft-plugins/formie/docs/theming/theme-config#theme-tags), I should be able to add HTML attributes to the error and success alerts.

I have the following configuration, but when the error alert is rendered, only the `class` attribute is applied.

```
alertError: {
  attributes: {
    class: baseAlertClassList,
    'data-color-theme': 'error',
  },
},
```

### Steps to reproduce

1. Use theme config to set attributes for `alertError` (and/or `alertSuccess`).
2. Submit a form and see the alert only has the `class` attribute.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.3.10

### Plugin version

2.0.23

**Comment by engram-design** [comment]
That would be correct behaviour _for the moment_ with an ajax-based form. As these alerts are generated with JS, they don't generate all their attributes, just classes. We'll see what we can do.

**Comment by chrismlusk** [comment]
Oh duh! Yep, of course that makes sense. Though it would be nice to have your theme config honored consistently for server- and client-rendered elements. 

I appreciate it might not be worth the complexity to add for this one thing (I think alerts are the only UI `FormieFormTheme` creates?), but at the very least it might help to add some clarifying language to the docs while you consider your options.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
