### ISSUE TITLE
Webhook sending wrong information

### ISSUE THREAD

**Issue by cole007** [verbb/formie#1336]
### Describe the bug

Odd issue since updating Formie from 2.0.10 to 2.0.20 where webhooks are not sending the correct information.
The webhook is posting into Zapier but via the webhook not Zapier integration (don't ask me why - this was set up by another developer but was working fine until the update).

If we look at the data in Zapier on the data received ("Data In") then we can see the following:

Before (when working):

```
email:	haXXXX@hotmail.com
forename:	HaXXXX
surname:	DeXXXX
```

After (not working):

```
email:	{{170549967__json__submission__email}}
forename:	{{170549967__json__submission__name1}}
surname:	{{170549967__json__submission__lastName}}
```

Any thoughts on what might be causing this or steps to resolve?
Upgrade to latest (2.0.24) doesn't resolve.

PHP 8.0.28
Craft Pro 4.3.10
Formie	2.0.24

### Steps to reproduce

1. Set up Webhook in Formie
2. Assign to Form in Formie and specify Webhook URL

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.3.10

### Plugin version

2.0.24

### Multi-site?

No

**Comment by cole007** [comment]
One more thing to add - the webhook URL is being specified via an ENV variable but that doesn't seem to be problematic as the submission data is getting to Zapier, just not in the correct format.

**Comment by engram-design** [comment]
This would likely be the changed format of the payload, which was changed in [2.0.20](https://github.com/verbb/formie/blob/craft-4/CHANGELOG.md#2020---2022-12-15)

Pre 2.0.20 format:
```
[
    'json' => [
        'submission' => [
            'id' => 1234
            'formId' => 12977
            'userId' => null
            // ...
        ]
        'form' => [
            'handle' => 'myform'
            // ...
        ]
    ]
]
```

Post 2.0.20 format
```
[
    'submission' => [
        'id' => 1234
        'formId' => 12977
        'userId' => null
        // ...
    ]
    'form' => [
        'handle' => 'myform'
        // ...
    ]
]
```

So it's the omission of the `json` key, that's all. This is true for either Zapier or the Webhooks integration. This was to fix another integration (Pardot I believe) that couldn't handle payload data like this.

Sending a test payload to Zapier should pick up the new values to map from.

**Comment by cole007** [comment]
Many thanks for the prompt response Josh

Glad to see it wasn't just me! Have managed to resolve by setting up some new Zapier-specific webhooks.
Should be okay for any new hooks - just an issue for updating when existing hooks are in place.

Perhaps might be worth adding a "breaking changes" note to the changelog for folks updating?

Thanks again, Cole

**Comment by engram-design** [comment]
Good point, and done.
