### ISSUE TITLE
Date field ignores Input Attributes when "Use Date Picker" is disabled

### ISSUE THREAD

**Issue by alexroper** [verbb/formie#1337]
### Describe the bug

A date field type with the "Display Type" option set to "Calendar" and the "Use Date Picker" option disabled will not render with any custom attributes on the input tag.

![Screen Shot 2023-03-02 at 1 47 59 PM](https://user-images.githubusercontent.com/377542/222568441-bf7c0c07-394e-424b-8ee1-15e3b4301add.png)

![Screen Shot 2023-03-02 at 1 47 50 PM](https://user-images.githubusercontent.com/377542/222568449-2c0f510a-85a7-402a-ad71-8aa7abe33345.png)

In my case, I tried adding the attribute `data-test="work"` under the Advance options.

![Screen Shot 2023-03-02 at 1 50 19 PM](https://user-images.githubusercontent.com/377542/222568383-605ceca5-9f1d-4b7c-8fc6-100d2949036f.png)

**Template code:**
```
{{ craft.formie.renderField(form, 'moveInDate') }}
```

**Output:**
```
<div class="fui-field fui-type-date-time fui-label-above-input fui-subfield-label-above-input fui-instructions-above-input fui-field-required fui-page-field col-6 col-md-3" data-field-handle="moveInDate" data-field-type="date-time" data-field-display-type="calendar">
  <fieldset class="fui-fieldset fui-subfield-fieldset">
    <div class="fui-input-container">
      <div class="fui-field-rows">
        <div class="fui-row">
          <div class="fui-field fui-type-single-line-text fui-label-above-input fui-subfield-label-above-input fui-instructions-above-input fui-field-required fui-date-time-date" data-field-handle="date" data-field-type="single-line-text">
            <div class="fui-field-container">
              <label class="fui-label" for="fui-contact-zwgqaz-fields-moveInDate-date">Move in Date&nbsp;<span class="fui-required" aria-hidden="true">*</span></label>
              <div class="fui-input-container">
                <input type="date" id="fui-contact-zwgqaz-fields-moveInDate-date" class="fui-input" name="fields[moveInDate][date]" required="" autocomplete="off" data-fui-id="contact-moveInDate-date">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
</div>
```

I also tried using the `setFieldSettings()` method, but I get the same result.

```
{% do form.setFieldSettings('moveInDate', {
  inputAttributes: [
    {
      label: "data-test",
      value: "works"
    },
  ],
}) %}
```

### Steps to reproduce

1. Create a Date field
2. Set the Display Type to "Calendar"
3. Disable the Use Date Picker option
4. Create an Input Attribute under the Advanced tag (e.g. data-test="works")

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.3.10

### Plugin version

2.0.23.1

### Multi-site?

No

**Comment by engram-design** [comment]
Yeah, the reason for this is that technically a Date field is a sub-field type of field, with multiple fields contained within (one for date and one for time). As such, this setting is a bit ambiguous on which input to add it to.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`.

**Comment by engram-design** [comment]
Updated in [2.0.25](https://github.com/verbb/formie/releases/tag/2.0.25)
