### ISSUE TITLE
Improving a11y for Name fields when label is set to hidden

### ISSUE THREAD

**Issue by simonleadbetter** [verbb/formie#1339]
### What are you trying to do?

The Name field uses a fieldset tag as parent wrapper for the subfields, however, if the **Label Position** is set to _Hidden_ then the label field is removed from the dom.  As it is a Level A criterion for a fieldset to have a legend it causes an inadvertent accessibility issue.

### What's your proposed solution?

Retain the legend tag, but visibly hide it rather than remove it from the form or convert the parent element into a div when the label is hidden.

**Comment by jamesmacwhite** [comment]
I checked this as we also have WCAG 2.1 AA requirements being a public sector. On Craft 3, I checked a form that's using hidden for the label position on a name field, with the first name and last name subfields enabled, the legend is still in the DOM, the `.fui-sr-only` class is applied so it's visually hidden but would still get announced by a screen reader.

I haven't checked Craft 4, but certainly in the Craft 3 version that behaviour would comply to WCAG requirements.

**Comment by simonleadbetter** [comment]
Just to confirm that the reported issue affects Formie 2.0.24

**Comment by jamesmacwhite** [comment]
Ah OK, might be something different in Craft 4 then. I only chimed in as we have recently been through a WCAG 2.1 audit and this wasn't flagged, but we are using the Craft CMS 3 version.

**Comment by JshGrn** [comment]
I have an issue where I am customising the class of this, but struggling however can confirm that the label is in the DOM and just the class ```fui-sr-only``` is applied. I would suggest this can be closed.

**Comment by engram-design** [comment]
We now add the `[data-fui-sr-only]` attribute to elements when the label is hidden, to visually hide it. This is in preference to a `.fui-sr-only` class, as that doesn't play nicely with Theme Config, where people remove Formie's classes on elements.

To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.43"`.

**Comment by engram-design** [comment]
Fixed in [2.0.44](https://github.com/verbb/formie/releases/tag/2.0.44)
