### ISSUE TITLE
Files attachments don't work on non-locale asset volumes

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#134]
**Description**
When I'm using an asset volume on S3 storage for example, the files upload perfectly from a file upload field, but aren't attached to the notification e-mail.

**Comment by engram-design** [comment]
Fixed in [1.2.18](https://github.com/verbb/formie/releases/tag/1.2.18)

**Comment by mattcdavis1** [comment]
Hmm - i'm on 1.2.19 and I've tried local and non-local volumes but neither seem to work (I don't receive any attachments).

**Comment by mattcdavis1** [comment]
So - looking at the code for attaching files, it appears as though there is an assumption of a flattened field list being returned by `$submission->getFieldLayout()->getFields()` so my asset fields are never getting evaluted. [See screenshot here](https://www.screencast.com/t/afWe8UmwYue9).

**Comment by mattcdavis1** [comment]
Confirmed that this is a nesting issue. When I brought the file upload field to the top level of the form the attachment was included in the email.
