### ISSUE TITLE
Integration Referrer TypeError

### ISSUE THREAD

**Issue by joelzerner** [verbb/formie#1340]
### Describe the bug

Just updated to the latest version 2.0.24 and experiencing this error for form submissions.
The form has a Google reCaptcha integration and a MailChimp integration.

TypeError
Cannot assign null to property verbb\formie\base\Integration::$referrer of type string

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/11308275/222955525-c9b118c3-1933-440f-abc8-6fb322fe88a2.png">

### Steps to reproduce

1. Attempt form submission

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.10

### Plugin version

2.0.24

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`.

**Comment by joelzerner** [comment]
Nice work - thanks!
