### ISSUE TITLE
Date field error when "Default Date/Time" is left empty

### ISSUE THREAD

**Issue by friartuck6000** [verbb/formie#1344]
### Describe the bug

When building/editing a Date field, it's possible for an editor to set **Default Value** to "Custom Date/Time", but leave the **Default Date/Time** setting empty:

![Screenshot 2023-03-09 at 11 01 59 AM](https://user-images.githubusercontent.com/4365821/224081754-ae73e7c7-7c65-4cb8-856c-46c7066d0992.png)

When using the "Dropdowns" or "Text Inputs" **Display Type**, this results in an error:

```
Call to a member function format() on array at <plugin-path>/src/fields/formfields/Date.php:1375
```

Ideally, I think the **Default Date/Time** field would include the `required` validation and prevent an editor from saving the field in that state to begin with; but with that aside, I would have expected an empty custom date to ultimately behave the same as setting the default to "None".

### Steps to reproduce

1. Create a Date field.
2. For **Default Value**, choose "Custom Date/Time".
3. Leave **Default Date/Time** unset.
4. Set **Display Type** to either "Dropdowns" or "Text Inputs".
5. Save the form, and attempt to view it on a page.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.9

### Plugin version

2.0.24

**Comment by engram-design** [comment]
Thanks for the PR! 

And as for the lack of FormKit validation, that's just a tricky one that we'd need a custom validator for, because _technically_ the setting has a value of `{date: '', timezone: ''}` for an empty date/time field control, otherwise adding `'validation' => 'required'` to the field settings schema would do.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
