### ISSUE TITLE
Error when I use an emoji in Error Message of a Single-line Text Field

### ISSUE THREAD

**Issue by maxstrebel** [verbb/formie#1348]
### Describe the bug

I just added an emoji to an error message and could not save anymore. It says `SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: ` but actually it pretty reliably goes away when I remove the emoji ;).

Because we had a chat there, I will reference this issue – I do not know if it is related: https://github.com/verbb/formie/issues/1115.

Thanks for your help and for your great work on formie.

### Steps to reproduce

1. Create a new form
2. Add a Single Text Field
3. Make it required
4. Use an apple emoji in Error Message

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/910594/224424498-5acd1f13-d7bc-4d23-a517-db6481ace63f.png">

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.1

### Plugin version

2.0.24

### Multi-site?

No

### Additional context

Here's the full error:

```
Unable to save form: {"general":["SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x99\\x82\",...' for column `db`.`fields`.`settings` at row 1\nThe SQL being executed was: INSERT INTO `fields` (`uid`, `groupId`, `name`, `handle`, `context`, `columnSuffix`, `instructions`, `searchable`, `translationMethod`, `translationKeyFormat`, `type`, `settings`, `dateCreated`, `dateUpdated`) VALUES ('640cc51e-92ab-49d9-9662-1089aa8cdd4f', NULL, 'Name', 'name1', 'formie:f83d6ea5-8985-40d2-977c-9cd90894917c', 'jwamjnar', NULL, 1, 'none', NULL, 'verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText', '{\\\"limit\\\":false,\\\"min\\\":null,\\\"minType\\\":\\\"characters\\\",\\\"max\\\":null,\\\"maxType\\\":\\\"characters\\\",\\\"matchField\\\":null,\\\"placeholder\\\":null,\\\"defaultValue\\\":null,\\\"prePopulate\\\":null,\\\"errorMessage\\\":\\\"Please post a name, so we can answer 🙂\\\",\\\"labelPosition\\\":null,\\\"instructionsPosition\\\":null,\\\"cssClasses\\\":null,\\\"containerAttributes\\\":null,\\\"inputAttributes\\\":null,\\\"includeInEmail\\\":true,\\\"enableConditions\\\":false,\\\"conditions\\\":null,\\\"enableContentEncryption\\\":false,\\\"visibility\\\":null,\\\"formId\\\":82,\\\"isNested\\\":false}', '2023-03-10 20:40:50', '2023-03-10 20:40:50')"]}.
```

**Comment by engram-design** [comment]
Yep, so error messages on fields don't currently support emoji's, along with the form success/error messages. We'll look at adding support for that.

**Comment by maxstrebel** [comment]
Thanks for looking into it.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
