### ISSUE TITLE
JavaScript API and auto populating fields

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1349]
### Question

I was looking at auto populating fields but rather than using Twig was considering doing it via JavaScript/XHR. This is due not wanting to render block a form, as the auto population would require a query to an external system i.e. CRM, which could have a slower response time. I have added `connect_timeout` and `connect` timeout to the current Guzzle request but it's still not ideal if it doesn't complete in time before the timeout settings. Instead, it would be better have an asynchronous request upon the formie loading, to not have to be concerned about the slow request/response, but not block the form/page request from loading.

The setup is currently a entry with a form is loaded with a URL parameter that contains a GUID that links back to the data in our CRM. This GUID is then pulled from the URL parameters and then used with GET request to obtain the data of this record, this then is linked to the form fields, currently using the populateValues method with Twig.

With the JavaScript API, I can see there is onFormieInit event, which would seem viable to use for moving this to an async request and having the request happen upon this.

Is this something that would be possible/supported?

**Comment by engram-design** [comment]
So you want to make an XHR call to the API to fetch the values to populate, and then use JS to populate those values? I guess you'll have a loading indicator to prevent the form from being shown before being populated, in case that request takes a while?

I'm very likely not going to implement JS-side population, as it's a lot to maintain. Every field is different, and not just a simple case of setting the value of a text field. This can also be done with some JS on your end, and depending on what fields you need to populate could be pretty simple.

Maybe one day, when I [publish a front-end library](https://github.com/verbb/formie/issues/1010)

**Comment by jamesmacwhite** [comment]
No worries, thanks for the reply. It was more of a general question around auto population with JavaScript having any API specifics around populating fields but not to worry.

Yes, the observed downside appears to be if the API response is slow and without any timeout handling, it could hang a page with a form for a while. Adding a specific connect_timeout and timeout value to the Guzzle request prevents that, but it does mean that the request might not have completed and hence the auto population has not happened. Although, it is technically handled in the sense that it's more of a progressive enhancement without anyone really knowing. given it is more of a convenience thing.

**Comment by engram-design** [comment]
Yep, as you're framing it like a progressive enhancement, that all sounds fine and the right way to go.

So yep, at the moment you're "on your own" with populating the fields via JS.

**Comment by jamesmacwhite** [comment]
Fair enough, thanks for confirming either way!
