### ISSUE TITLE
Allowing Dynamics 365 Web API version to be set via settings and not hard coded

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1350]
### Question

Would you accept a PR for making the Web API version used in Dynamics 365 integration Guzzle requests a configured integration setting i.e. on the plugin settings where the API keys are?

Currently the integration hard codes the 9.0 version. While I cannot see anything major with this, for compatibility or customisation, having this configured at the integration level might be beneficial? There could be a scenario where backwards compatibility is needed or a specific API version required to use an endpoint that's only available in a specific version?

**Comment by engram-design** [comment]
Happy to make that configurable, probably just in the integration settings (not the form integration settings)

**Comment by jamesmacwhite** [comment]
Awesome. I'm happy to submit a PR for it, unless you want to add directly. 

I would add a drop down field to the plugin integration settings so it's global with the options 9.0, 9.1, 9.2 with a default of 9.0, given this has been the hard coded value since implementation to maintain existing compatibility, if that sounds OK?

**Comment by jamesmacwhite** [comment]
Implemented for new release [7668725](https://github.com/verbb/formie/commit/766872583702e1b45065342d7f2b0235e04c6214)
