### ISSUE TITLE
formDataAttributes not working anymore after upgrading from V1 to V2

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1353]
### Question

I've just upgraded from Formie `1.5.16` to `2.0.24` and have checked the [Upgrading from v1](https://verbb.io/craft-plugins/formie/docs/get-started/upgrading-from-v1) guide.

However, I've found that the `formDataAttributes` options set as parameters of `craft.formie.renderForm` are not working anymore. Also, I don't see the [Rendering Options](https://verbb.io/craft-plugins/formie/docs/v1/template-guides/rendering-options) page in the V2 documentation.

Why it's been deleted without mentioning it in the upgrade guide? What's the recommended method now?

**Comment by romainpoirier** [comment]
On top of that, I can note that the `formClasses` parameter is also not working anymore.

**Comment by engram-design** [comment]
This would be correct behaviour, as that limited functionality (`formDataAttributes` and `formClasses`) has been replaced with [Theme Config](https://verbb.io/craft-plugins/formie/docs/theming/theme-config).

```twig
{{ craft.formie.renderForm('contactForm', {
    themeConfig: {
        form: {
            attributes: {
                'some-attribute': 'some-value',
                'class': 'some-class',
            },
        },
    },
}) }}
```

I'll make a note in the upgrade guide, just an omission on my part.
