### ISSUE TITLE
Autopilot Integration - incorrect variable

### ISSUE THREAD

**Issue by jhealey5** [verbb/formie#136]
**Description**
The Autopilot Email Marketing integration currently returns an API error:
`API error: “Unable to find “{instance_id}” in response.” .../vendor/verbb/formie/src/base/Integration.php:132`

`$response['instance_id']` should be `$response['instanceId']` here: https://github.com/verbb/formie/blob/2cf62c8ae3b15e93fd77d483186772637609b552/src/integrations/emailmarketing/Autopilot.php#L201-L204

**Comment by engram-design** [comment]
Fixed in [1.2.18](https://github.com/verbb/formie/releases/tag/1.2.18)
