### ISSUE TITLE
Upgrade from V1 to V2: Reload the page on submit is not working anymore

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1360]
### Describe the bug

I've upgraded from `1.5.16` to `2.0.24`, and the reload the page on submit setting is not working anymore : it's redirecting to the `siteUrl` instead of just reload the page.

Follow the `Steps to reproduce` below and add this in a blank template:

```
{% set handle = 'myFormHandle' %}
{% set form = craft.formie.forms({ handle: handle }).one() %}
{% set submission = craft.formie.submissions.from(handle).user(currentUser).isIncomplete(true).one() %}
{{ craft.formie.renderForm(form) }}
```

### Steps to reproduce

1. Setup a multi-pages forms in Craft 3 + Formie V1
2. Setup `Submission Method`:` Page Reload (Server-Side)` + `Action on Submit`: `Reload the page` + `Validate Form on Submit` (enabled)
3. Setup a blank template and add a `{{ craft.formie.renderForm(form) }}`
4. Migrate to Craft 4 + Formie V2
5. Fill in the form until the final submit
6. The final submit is redirecting to `siteUrl` instead of reloading the page

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.3

### Plugin version

2.0.24

### Multi-site?

Yes

**Comment by romainpoirier** [comment]
As additional information, after inspecting the form from the `craft_formie_forms` DB table, in the column `settings` I can see that the settings seems correct:
```
"submitMethod": "page-reload",
"submitAction": "reload",
"redirectUrl": null,
```

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`.

**Comment by engram-design** [comment]
Updated in [2.0.25](https://github.com/verbb/formie/releases/tag/2.0.25)
