### ISSUE TITLE
Date picker not initialized inside repeater

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#1362]
### Describe the bug

Hi,

We've been running into an issue where flatpickr is not rendered when using a Date/Time calendar field inside a repeater.

I checked our form template settings and the Output Base JavaScript and Output Theme settings are enabled, and tested on two installations so I think this is a Formie issue

Let me know if you need any more info,
Thanks!

### Steps to reproduce

1. Add a Date/Time field using calendar display type inside a repeater field
2. Field appears as a text input on the front end

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.10

### Plugin version

2.0.24

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`.

**Comment by d-karstens** [comment]
Cheers!

**Comment by engram-design** [comment]
Updated in [2.0.25](https://github.com/verbb/formie/releases/tag/2.0.25)
