### ISSUE TITLE
Open link in new tab is not being remembered when editing Agree field

### ISSUE THREAD

**Issue by dowadidi** [verbb/formie#1366]
### Describe the bug

Checking 'open link in a new tab' works fine when creating and showing an 'Agree' field. But when you edit the field again, 'open link in a new tab' becomes unchecked.

### Steps to reproduce

1. Add agree field to form
2. Add link to the description
3. Save the field and form
4. Edit the existing Agree field
5. Edit a link in the description field

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.5

### Plugin version

2.0.24

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.24"`.

**Comment by engram-design** [comment]
Updated in [2.0.25](https://github.com/verbb/formie/releases/tag/2.0.25)

**Comment by dowadidi** [comment]
Thanks!
