### ISSUE TITLE
Custom Email templates not working anymore

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/formie#1367]
### Describe the bug

We are using custom email templates for some Formie forms and they suddenly aren't working anymore. This is the setup of the email template in the CMS:

![Screenshot 2023-03-24 at 11 06 13](https://user-images.githubusercontent.com/6649706/227492084-bc15be26-ebf9-4df1-a278-aaffba3661e4.png)

With the corresponding structure in templates folder;

<img width="269" alt="Screenshot 2023-03-24 at 11 06 20" src="https://user-images.githubusercontent.com/6649706/227492086-c5ffb503-9f7d-4795-acda-d944a632a812.png">

This is how the email looks in the preview

![Screenshot 2023-03-24 at 11 05 54](https://user-images.githubusercontent.com/6649706/227492072-03d1fd71-58d5-4443-91d5-35d1bd8b0985.png)

This is the actual email, the default unstyled formie template:

![Screenshot 2023-03-24 at 11 08 55](https://user-images.githubusercontent.com/6649706/227492574-894045b9-7856-4786-8e3d-6bc897ec2f4f.png)

And this is error we're getting in the formie.log file:
`$_POST = []
2023-03-24 11:02:33 [ERROR] Notification email template does not exist at “_emails/orderConfirmation”.
2023-03-24 11:02:33 [INFO] Request context:
$_GET = []`

Lastly when using the "Send test email" from the preview, the email sent, does look correct
![Screenshot 2023-03-24 at 11 13 58](https://user-images.githubusercontent.com/6649706/227493852-6cd24520-af41-49af-b7bb-4d96e7d91f50.png)

Is there a setting we need to change, we just upgrade from the 2.0.20 to 2.0.24 when this behaviour started to show.

Thanks in advance!

### Steps to reproduce

1. Add a custom email template in CMS and templates
2. Add template to form
3. Preview it
4. Submit the form and compare

### Form settings

- Multi-page form: No
- Submission Method: Page Reload

### Craft CMS version

4.4.5

### Plugin version

2.0.24

### Multi-site?

Yes

**Comment by engram-design** [comment]
I don't believe there's been any recent changes with email templates. Are you using the queue to send out email notifications (the default behaviour)? If so, can you let me know how you're running the queue - whether it be via the CLI, cron ,etc?

Otherwise, everything seems to be working correctly on my end with custom email templates, no matter what method I'm using to send it.

You're also welcome to submit a support request via Formie > Settings > Get Support for you form. That'll send us your form setup, including your email notification. We can test that out just in case there's some unique configuration on your end.

**Comment by ishetnogferre** [comment]
This was all while working on local dev, so immediately via standard Craft queue.

Sending the form your way right now! I'll keep testing on this/another project.
Maybe some additional context: we've also used MJML templating and for this specific form we're doing custom actions:
- add some info with the `Emails::EVENT_MODIFY_RENDER_VARIABLES`
- trying to change the to variable of the notification on `Submissions::EVENT_BEFORE_SEND_NOTIFICATION`

But with these commented out and using another form without these custom code, it was the same result.

**Comment by ishetnogferre** [comment]
It's working again, so I'll close it for now

**Comment by ishetnogferre** [comment]
Okay no, cheered too soon :( 

Template still can't be found anymore, the structure hasn't changed.

<img width="801" alt="Screenshot 2023-05-04 at 11 10 23" src="https://user-images.githubusercontent.com/6649706/236160959-7af3a9e5-46f7-46e8-8841-71a65c24d108.png">

The settings and structure are as following:
<img width="801" alt="Screenshot 2023-05-04 at 11 10 23" src="https://user-images.githubusercontent.com/6649706/227492084-bc15be26-ebf9-4df1-a278-aaffba3661e4.png">

<img width="801" alt="Screenshot 2023-05-04 at 11 10 23" src="https://user-images.githubusercontent.com/6649706/227492086-c5ffb503-9f7d-4795-acda-d944a632a812.png">

**Comment by engram-design** [comment]
Very strange, that path looks totally fine to me, and I certainly can't reproduce it with your email template settings.

Is your email notification running via the queue?
Does the Email Notification Preview work, or the same error?

**Comment by ishetnogferre** [comment]
Sorry for the late reply!

The notification goes through the standard flow, so yes. The preview does work, same for sending it out via there, but when using any form, we get the errors above and the flat version of the email. Same if we remove all custom code.

**Comment by engram-design** [comment]
So I'll assume they're sent using Craft's queue. How are you processing your queue, through the Craft default (the queue is only processed when visiting the control panel), or via cron, a daemon, the CLI, etc?

I'm just wondering if there's a difference with how templates are being resolved when potentially being run from a non-web request - depending on your setup.

**Comment by ishetnogferre** [comment]
Craft queue indeed and processing though visiting the control panel. It's local environment running on DDEV for now

**Comment by ishetnogferre** [comment]
@engram-design could it been something with us using DDEV now? Like a difference in path? Cause the preview works and the mail sent from the test in preview as well, just not the actual notification 🤔 

**EDIT: tried to follow that assumption and found that when we turn off the "Use Queue for Notifications" setting, the emails are sent with the template rendered.**

**Comment by engram-design** [comment]
The environment _shouldn't_ matter. There's nothing special you're doing with the queue, like using the Async Queue plugin, or running it with the CLI? From your last response, you mentioned just using the default handling (the queue is only processed when you visit the control panel).

Something about a non-web request is clearly messing up the path. Anything in your `storage/logs/formie-*.log` files, or any of the other logs (like `queue-*.log`)?

**Comment by ishetnogferre** [comment]
Oh.. Yeah, it was Async Queue blocking the emails, when removed, everything works as it should.
Sorry for the inconvenience 🙏
