### ISSUE TITLE
Custom password reset form does not send mail

### ISSUE THREAD

**Issue by JulieVelghe** [verbb/formie#1368]
### Question

Hi, 
I've followed the documentation to get a custom password reset form.
I have the following code:
```
            {% set exists = entry.formFormie.exists() %}
            {% if exists %}
                {% set form = entry.formFormie.one() %}
                <form method="post" accept-charset="UTF-8">
                    {{ actionInput('users/send-password-reset-email') }}
                    {{ csrfInput() }}

                    {{ craft.formie.renderPage(form, null, {
                        fieldNamespace: '',
                    }) }}
                </form>
            {% endif %}
```
my form has the following handle: passwordReset
and a field for the username with the handle loginName.
When I insert a username (or the emailaddress linked to that user), the page just refreshes and no mail gets send. I also have a login page and user profile page, both of those work just fine. I can use the login page and on a refresh of the profile page, I can see the user data.

What am I missing for the password reset one?

**Comment by engram-design** [comment]
Seems all okay to me (working for me)! Might I suggest outputting any errors from that action endpoint for some more detail?

```twig
<form method="post" accept-charset="UTF-8">
    {{ actionInput('users/send-password-reset-email') }}
    {{ csrfInput() }}

    {% if errors is defined %}
        {{ errors | join(', ') }}
    {% endif %}

    {{ craft.formie.renderPage(form, null, {
        fieldNamespace: '',
    }) }}
</form>
```

**Comment by JulieVelghe** [comment]
nope, doesn't do a thing. I thought that perhaps the submission method was wrong, it was on server-side. But even after I changed it to ajax (client-side), the page simply reloads with no messages or mails.

**Comment by engram-design** [comment]
At this point, none of the settings for the form are taken into account - this is just a plain form that uses Formie to content manage the fields.

Out of interest, would you mind giving this [form](https://craftcms.com/knowledge-base/front-end-user-accounts#reset-password-forms) a go? That will at least remove Formie from the equation, in case something else is going on.

**Comment by JulieVelghe** [comment]
same result :(
I do see that in the example, the twig file is called 'reset-password.twig'.
I have named my twig file 'password-reset.twig'. Is that of any importance?

**Comment by JulieVelghe** [comment]
same result :(
I do see that in the example, the twig file is called 'reset-password.twig'.
I have named my twig file 'password-reset.twig'. Is that of any importance?

**Comment by engram-design** [comment]
So if that example from Craft isn't working, I'd say it's probably got nothing to do with Formie. The filename shouldn't matter as well.

Anything in your log files about the error? Might be worth chatting to the Craft support team about it (just be sure to ask for support using their exact template setup, not including Formie for clarity).

Are any of your other emails working? Does going to Settings > Email > Send Test Email work?

**Comment by JulieVelghe** [comment]
hm, ok, that test doesn't work, so might be something with those settings. Didn't think anything was wrong there, because I've also got a custom module that sends extra notifications when a new user fills in a registration form. There, I use  following code:
        $this->mailer = Craft::$app->getMailer()->compose();
        $this->mailer->setFrom(['digibanken@vlaanderen.be' => 'Digibanken']);
And those do get send, I thought that that mailer used the same emailsettings.

**Comment by JulieVelghe** [comment]
Ok, it was the settings ...
