### ISSUE TITLE
Editor not permitted to edit form for the site error

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#137]
**Description**
When editor – with permissions to edit forms – tries to edit form, he gets message: Not authorized - User not permitted to edit content in this site.

The URL of the form edit page contains primarySiteKey:
`/admin/formie/forms/edit/182982/primarySiteID`
when I remove the /primarySiteID, so the URL is:
`/admin/formie/forms/edit/182982`
user can edit the form (but that is not too friendly to editor).

_edit: when I append englishSiteID handle, the user is allowed to edit the form_

**Not sure how to reproduce it, but the steps I took before this and some other related hints:**

1. editor has created the form and saved
2. administrator has changed the form and saved
3. editor has no permission to edit any content on primarySiteID, only on englishSiteID

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.17
- Craft version: Craft Pro 3.5.11.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.2.18](https://github.com/verbb/formie/releases/tag/1.2.18)
