### ISSUE TITLE
Email notifications failing after 2.0.25 update

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#1370]
### Describe the bug

Hi,

After updating to 2.0.25 we've started encountering the following error with email notifications when using any of the `all form fields` variables.

`Failed to send notification email: {"error":"Notification email template parse error for “formie\/_special\/email-template”. Template error: “Email body render returned empty. Please check your email content for invalid variables.” \/home\/runcloud\/webapps\/wilderness-school\/vendor\/verbb\/formie\/src\/services\/Emails.php:276"}. `

Seems like it could be related to this change? https://github.com/verbb/formie/commit/3697dd0967d9d11b60a618d6db15b4ad60a46f22

Let me know if you need any more info, 
Thanks!

### Steps to reproduce

1. Set up an email notification using one of the variables to show all form fields
2. Refresh the notification preview and see error

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.5

### Plugin version

2.0.25

### Multi-site?

No

**Comment by ArnoMoqo** [comment]
Same issue here after updating to 2.0.25

**Comment by garycrane** [comment]
Same here too.

**Comment by engram-design** [comment]
Apologies for the issue, should be fixed in [2.0.25.1](https://github.com/verbb/formie/releases/tag/2.0.25.1)

**Comment by idawgik** [comment]
So we've been having issues with this same error on one of our sites currently. We're up to date on all updates, so running Formie 2.0.38 (just updated today from 2.0.37).

This is causing emails not to be sent to the client.

The error is:

`Notification email template parse error for “formie/_special/email-template”. Template error: “Email body render returned empty. Please check your email content for invalid variables.” /path/to/site/vendor/verbb/formie/src/services/Emails.php:276`

I did check the code changes from the previous referenced update are still in place, so something else seems to be causing this issue.
