### ISSUE TITLE
Prevent form submissions after a certain date/time

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1372]
### What are you trying to do?

Some forms may be date/time sensitive or be for a limited time only, therefore being able to set a closing date/time on the form to prevent submissions after a certain date would be beneficial. When a form has a closing date/time set when being embedded by the Twig variable it would be replaced with a generic or customised message.

### What's your proposed solution?

* Have a new form setting for a date/time on the form model for being able to set a closing date.
* When a form is output check the current date/time vs a closing date/time value set, if it's greater, display a message instead of rendering the form if the closing date is past the current date.

### Additional context

This can be implemented with Twig, but will require custom logic for each time this is required on a form and repeated.

**Comment by engram-design** [comment]
This is available for Formie 2.x 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/1221575/227934081-bb1f9be1-8e77-4d66-a5cb-ec2d6808188d.png">

Along with other useful restriction settings:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/1221575/227934478-fd7beb97-17e3-4148-ac2f-a366d6957a15.png">

**Comment by jamesmacwhite** [comment]
Ah, I'm using Formie 1.x that's why I haven't seen those features.

Would a backport of part or all of this functionality be realistically feasible do you think? I would potentially volunteer to do it, but if it relies on major changes between 1.x to 2.x then it's probably not realistic in a 1.6.x release as that's pretty major changes

**Comment by jamesmacwhite** [comment]
Ah, I'm using Formie 1.x that's why I haven't seen those features.

Would a backport of part or all of this functionality be realistically feasible do you think? I would potentially volunteer to do it, but if it relies on major changes between 1.x to 2.x then it's probably not realistic in a 1.6.x release as that's pretty major changes

**Comment by engram-design** [comment]
Yeah, I know you're on Formie 1 still, it's probably not an impossible feat to backport it, but my priorities on new features are mostly on Formie 2 at the moment. It's otherwise covered [here](https://github.com/verbb/formie/commit/f6ebf19d33ef64a7ffce49c3b16cdfc89b69166b)

It's something I can look at sometime!

**Comment by engram-design** [comment]
Yeah, I know you're on Formie 1 still, it's probably not an impossible feat to backport it, but my priorities on new features are mostly on Formie 2 at the moment. It's otherwise covered [here](https://github.com/verbb/formie/commit/f6ebf19d33ef64a7ffce49c3b16cdfc89b69166b)

It's something I can look at sometime!

**Comment by jamesmacwhite** [comment]
@engram-design Thanks! I will potentially do it given I understand mostly new features will be on Formie 2, but was just querying if you'd allow it considering it's a feature and doing a 1.6.x release is more incremental/minor changes, compared to bigger changes.
