### ISSUE TITLE
Phone field: restrict countries to one or a group of countries

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#138]
It is quite handy to restrict phone country to specific country. But it would be great to have an option to restrict countries in more detail way: to Europe, USA, maybe to the selection of countries the form is supposed to work for (Germany + Austria etc.) so user doesn't need to scroll to endless list.

**Comment by engram-design** [comment]
Agreed, and this will be coming in the [roadmap](https://github.com/verbb/formie/projects/1#card-42121368)

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
