### ISSUE TITLE
Adding an emoij to a label breaks everything

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/formie#1380]
### Describe the bug

When adding an emoij to a field label, the json object saved in the database isn't valid and breaks the entire site.
same issue happend in Craftcms itself https://github.com/craftcms/cms/issues/2725 and in Commerce https://github.com/craftcms/commerce/issues/886

### Steps to reproduce

1. Add an emoij to a form field label
2. save the form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

### Multi-site?

No

**Comment by engram-design** [comment]
The form shouldn't save at all if it contains an emoji. Are you saying that the form actually saves despite the error notice? If so, that certainly shouldn't be the case (it isn't for me). I'll correctly get the following form error 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1221575/230687736-92729943-271d-4e47-aaa8-eee2dffd888e.png">

And the form will have failed to save, so refreshing the page doesn't retain my update.

**Comment by WHITE-developer** [comment]
Looks like the problem is somewhere in our sever setup.
Locally I'm also getting the error notice, but on our servers we are able to save the form.

**Comment by engram-design** [comment]
Just want to confirm that using emoji's in field labels is **not** allowed, but you shouldn't be able to save the form with the error being raised. From the sounds of your issue, if it's breaking the control panel, the form has somehow been saved despite validation errors, which shouldn't happen.
