### ISSUE TITLE
"Default Status" for forms cannot choose anything other than "New"

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1383]
### Describe the bug

I just created a new status:
![image](https://user-images.githubusercontent.com/1250017/231138672-efb97c3a-e7d5-494c-bd19-b013c69935fc.png)

The form is unable to select the created status. When I click on New, nothing happens:
![image](https://user-images.githubusercontent.com/1250017/231138760-b89c0b48-e456-4728-a212-5c834f1bc7b1.png)
(http://website.test/control/formie/forms/edit/formId#tab-settings)

### Steps to reproduce

1. Create a status
2. Try to change the default status of a form

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: No

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

### Multi-site?

No

### Additional context

Chrome, with extensions disabled

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
