### ISSUE TITLE
It's not possible to delete Statuses

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1385]
### Describe the bug

I created a new status (https://github.com/verbb/formie/issues/1383). I am now unable to delete that status, only re-order it.

### Steps to reproduce

1. Create a form status
2. Try to delete it. There is no delete button either on /admin/formie/settings/statuses or on the edit page for the status you created

### Form settings

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

**Comment by engram-design** [comment]
This would likely be because some submissions are assigned that status. You would need to re-assign any submissions using the status you want to delete before deleting it. This would also need to be done on each environment.

It's the latter point that we can't really automate this by switching submissions to use another status automatically.

**Comment by darylknight** [comment]
This isn't the case. All 4 submissions I tested with are set to "new", but the status I created is called "Requires approval" - there's just no button to delete. It's not greyed out or anything, it just doesn't exist.

**Comment by darylknight** [comment]
I've just done some more testing with this, and it looks like you can't remove a Status, if there are ANY form submissions stored, even if they're not assigned to that status:

Submissions:
![image](https://user-images.githubusercontent.com/1250017/231369924-2b65bd27-61bc-4013-b326-23a32acedf79.png)

Status Settings:
![image](https://user-images.githubusercontent.com/1250017/231369958-de22b0f8-b77b-4c22-9a4b-ba282e38ecc5.png)

The submission was assigned to "New". Once I delete the submission, a delete button appears for the "Requires Approval" status:

![image](https://user-images.githubusercontent.com/1250017/231370072-263e48d0-d7c3-4e99-83a7-ec25433c0270.png)

**Comment by engram-design** [comment]
Ah, you're absolutely right that new statuses are tripping this logic, I missed that. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`.

And I should also add that the default status cannot be deleted also.

**Comment by darylknight** [comment]
That makes sense - thanks!

**Comment by medoingthings** [comment]
I have the same issue – created a new status, used it, then realized I don’t need it, deleted all submissions and settings that referenced that status, but I don’t see the delete status button. Any idea?

**Comment by engram-design** [comment]
Have you ensured that your submissions are hard-deleted? By default, they are soft-deleted and added to "trashed" so that you can restore them again.

**Comment by medoingthings** [comment]
That did the trick, thanks! Wasn’t aware that a trash exists, cheers!
