### ISSUE TITLE
Adding option for custom attribute to Formie script elements

### ISSUE THREAD

**Issue by joepagan** [verbb/formie#1386]
### What are you trying to do?

Improve Google PageSpeed Insights scores (Reduce unused Javascript)

![image](https://user-images.githubusercontent.com/2337910/231121228-d003921f-67b8-4e77-b75c-9524fd561fd7.png)

From the context of a pagspeed test, I guess it sees 100% of recaptcha JS (and maybe formie.js) as unused because no captcha validation has been performed yet.

### What's your proposed solution?

2 options I think would work:

1. Provide an option in the backend or via `craft.formie.renderForm` to allow custom attributes so we can load the Formie scripts on a different worker thread using [Partytown](https://partytown.builder.io/)

2. Only load the required scripts based on user interaction with a form field using a dynamic import, e.g.:

```js
() => {
  const input = document.querySelector('input');
  input.addEventListener('keyup', () => {
    import('./formie.js').then(module => {
      module.init();
    });
  });
}
```

or if `formie.js` is required and too much work to rearrange, could perform this type of function on the `registeredJs` scripts such as `/cpresources/4e031f27/recaptcha-v2-invisible.js`

**Comment by engram-design** [comment]
I've not used Partytown, but seems like a neat concept! From what I can tell, you just need to add `<script type="text/partytown"`. That should be achievable.

The second option should be available now, where you can manually initialize the Formie JS on-demand, whenever you need it. You can pass in `renderJs: false` as a [render option](https://verbb.io/craft-plugins/formie/docs/theming/render-options), and then initialize the JS when you need to.

Commonly, this is done by [importing](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules) the Formie JS and then calling `initForm()` when your logic calls for it.

**Comment by joepagan** [comment]
Thanks for getting back!

>I've not used Partytown, but seems like a neat concept! From what I can tell, you just need to add <script type="text/partytown". That should be achievable.

Yeah spot on! (Off topic sometimes it's a bit temperamental if a reverse proxy doesn't work which is super annoying, it seems like google ads are the worst offender).

>The second option should be available now, where you can manually initialize the Formie JS on-demand, whenever you need it. You can pass in renderJs: false as a [render option](https://verbb.io/craft-plugins/formie/docs/theming/render-options), and then initialize the JS when you need to.

Cool thanks, I suppose I was a little unsure in the scenario where the script loads in the footer for all forms, rather than each.
Am I right in presuming that this setting does the same as `renderJs: false` on all forms?
<img width="441" alt="image" src="https://user-images.githubusercontent.com/2337910/231398621-9355e1d3-355c-4069-8cae-86ebadf7bd03.png">


>Commonly, this is done by [importing](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules) the Formie JS and then calling initForm() when your logic calls for it.

Perfect I can dynamically import that formie lib and initialise it on an event like that!

**Comment by engram-design** [comment]
Yep, if you prefer you can manage that at the Form Template level so it's re-usable, both does the same thing.

I've often wanted to get to the bottom of performance issues (not just a Formie thing, but Google libraries, etc), so I'll do my best to make this as user-friendly as possible.

**Comment by engram-design** [comment]
Just looking at this, and you can achieve point number 1. now, via:

```twig
{{ craft.formie.renderJs(false, {
    type: 'text/partytown',
}) }}
```

Which will add the `<script type="text/partytown"`. But we'll also be addressing loading JS via https://github.com/verbb/formie/issues/1394, so will close this in favour of following up there.
