### ISSUE TITLE
User Field Sources only populates data if `All users` is selected in Field Settings

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/formie#1387]
### Describe the bug

Entry Field Sources only populates data if `All users` is selected in Field Settings. I expect to be able to select one group and see users within the form populated from within that group.

The `Entries` field works properly, but not the `Users` field.

### Steps to reproduce

1. Create a couple of user groups
2. Assign a user or two to that new group
3. Create a User field for your form and attach it
4. Update the source to point to one of the groups you created in Step 1.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

### Multi-site?

No

**Comment by engram-design** [comment]
Seems to work okay for me. Can you confirm if you're trying to refer to a custom source, or just a user group? Do you also have multiple sources selected, or just one?

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1221575/231337112-efc40485-3c7d-4b25-958e-12d7ceb62bb9.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1221575/231337135-341197f4-8469-4825-91bc-53fb7aaeaec3.png">

<img width="191" alt="image" src="https://user-images.githubusercontent.com/1221575/231337226-9421a291-512f-432f-a8a0-778d6c4f426f.png">

**Comment by DynamiteGoesBoom** [comment]
Just in the user groups. I simply created a couple of user groups. Inside the field if I select all the sources it works. But if I only select one of them nothing displays, even if there are users in that group.

**Comment by engram-design** [comment]
Closing for now, as I _still_ can't replicate this, but happy to review it again.
