### ISSUE TITLE
Use <template> for rendering repeater fields instead of <script>

### ISSUE THREAD

**Issue by hongc-cc** [verbb/formie#139]
**Description**
(Detail doc in #131 )
Form rendering is weird as `<script type="text/template">` get halved when using `ajax` (or `htmx`, `sprig`) to load the form. (use case:  load the next page when at the end of the page)

Suggest using `<template>` instead of `<script type="text/template">`

**Comment by engram-design** [comment]
This isn't a solution sorry - refer to browser support for `<template>` which cannot be ignored https://caniuse.com/template

**Comment by engram-design** [comment]
I think your only solution right now is to override the repeater template with your own, replacing `<script type="text/template">` with `<template>` so long as you don't care about browser support.
