### ISSUE TITLE
Creating a `Review submission` page prior to submission via multipage forms

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/formie#1390]
### Question

Is there a way to display all of the data submitting on a single page prior to submitting? I'd like to take all of the submitted data on other pages and use that data to allow users to review their submission prior to submitting.

Thanks gang!

**Comment by DynamiteGoesBoom** [comment]
Ahh I just realized that the Summary field is available. Is there an easy way to override the layout of that field? I'd like to have an Edit link on each `page` in the summary that when clicked would bring the user to that particular page too.

Thanks agani!

**Comment by engram-design** [comment]
Yep a Summary field would be perfect for that. Have a look at [template overrides](https://verbb.io/craft-plugins/formie/docs/theming/template-overrides) to supply your own template for the field.
