### ISSUE TITLE
Submitting forms using reCAPTCHA with a E2E Cypress test

### ISSUE THREAD

**Issue by joepagan** [verbb/formie#1391]
### What are you trying to do?

We use reCAPTCHA v2 invisible on most sites so a user can complete a challenge, and, I'd like to write some cypress tests post deployment.

It looks like this is possible with v2 with a specific set of keys:
https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

### What's your proposed solution?

Do you think it would be possible to use these keys in a scenario where a particular query string parameter exists (or similar)? 
And _almost_ treat it like a successful spam submission where the test could reach the confirmation page, but not trigger a notification email?

**Comment by engram-design** [comment]
The idea of a test-specific scenario isn't something that Formie supports at the moment. If you fill out a submission, whether automated or not, it'll trigger the usual post-submission tasks like running integrations and sending email notifications. We'd probably need to make some alterations for that.

There is a `disableCaptchas` setting that you can set which I know others have used for their automated testing (granted, this doesn't actually test captchas, so maybe it's not desirable). 

```
{% set form = craft.formie.forms({ handle: 'contactForm' }).one() %}

{% do form.setSettings({
    disableCaptchas: true,
}) %}

{{ craft.formie.renderForm(form) }}
```

You _could_ set the keys at runtime in your templates (the syntax isn't amazing):

```
{% do form.setSettings({
    integrations: form.settings.integrations | merge({
        recaptcha: {
            siteKey: 'xxxxxxxxxxxx',
            secretKey: 'xxxxxxxxxxxx',
        },
    }, true),
}) %}
```

But that still leaves the fact that you probably want to tailor behaviour just for tests.

**Comment by joepagan** [comment]
Thanks for getting back with your thoughts much appreciated!

I think `setSettings` method might actually be great for this situation at least on staging where we want to keep some working keys!
It's probably the case that it's going to be more convoluted than it needs to be just to try make this work in prod.
