### ISSUE TITLE
how to get javascript working when showing form in a modal

### ISSUE THREAD

**Issue by jripmeester** [verbb/formie#1392]
### Question

We are using formie to show the forms in a modal but somehow the javascript doesn't work. So for example the country code phone number field dropdown isn't opening.

What would be the best way to get this going?

**Comment by engram-design** [comment]
This largely depends on exactly how you're managing to show a modal. Can you detail how you're showing the modal? Is is native JS, Vue or something else? Are you rendering the modal content initially, or ajax-loading it? Lots of variables to consider.

Depending on how you're loading the form, you may need to initialise Formie's JS [manually](https://verbb.io/craft-plugins/formie/docs/developers/front-end-js)

**Comment by jripmeester** [comment]
Hi Josh,

We use Alpine to show hide the form. The form is renderend initially.
[Here you can view the form:](https://www.snapper.eu/en-gb/lawn-tractors/spx110/) it's behind the call me back button.

**Comment by engram-design** [comment]
Right, so the `<form>` element isn't actually rendered in the DOM until you click the button, which is good to know. In that instance, you need to trigger events to be re-bound when the form is shown.

You can see that as soon as you load the page, Formie's JS is run and other JS like the Phone Field, Recaptcha are lazy-loaded in 

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1221575/232163473-80fd3a45-a608-40ca-81a5-38bfc3c09fcf.png">

Which is fine, but they're binding to things that don't exist in the DOM yet.

To test this, you can open the modal window, then in your web developer tools console, type `window.Formie.initForms();` which will initialize all forms on the page. The telephone field will work, much like other JS (client-side validation, etc).

So I would recommend you need to follow a similar approach for [Vue](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules) where you manually initialize the form's JS when the modal is shown.

```js
var $form = document.querySelector("#glightbox-body form");
window.Formie.initForm($form);
```

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
