### ISSUE TITLE
Mismatched times

### ISSUE THREAD

**Issue by JulieVelghe** [verbb/formie#1393]
### Describe the bug

I've made a form with a table field that has time fields.
These fields are then being mapped via an element integration to an entry where these values are being inputted.

The problem is that there is a mismatch in timezones. In the form I enter for example 8 AM, and the entry shows me 10 AM.

I've read in the issues that it should have been fixed so I updated to the last version of Formie, but the issue seems to still be there?

Is this issue fixable? Or are there some things that I can do? Perhaps via a custom module changing that particular field? (don't know how well it would work with element integration ...)

### Steps to reproduce

1. set timezone in craft to brussels (utc+2)
2. create section with table field that has time columns
3. create form with table field that has time columns
4. setup an element integration to link the fields
5. make a submission

### Form settings

- Multi-page form:  No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.4.7

### Plugin version

2.0.26

### Multi-site?

no

### Additional context

Redactor | 3.0.4
SEO | 4.1.0
Sprig | 2.5.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
