### ISSUE TITLE
Improve Formie.js loading to only load when form is visible

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1394]
To get around cases where Formie's JS doesn't need to run immediately (the form is hidden in a modal), we should use something like `IntersectionObserver` to detect when the form is visible on the page to then run the JS. This will also help with page performance when including things like captchas.

https://github.com/verbb/formie/issues/1392
https://github.com/verbb/formie/issues/1386

**Comment by hassanmah** [comment]
@engram-design any updates on this? All my forms are in modals

**Comment by engram-design** [comment]
This is available for Formie 3 (starting in [3.0.0-beta.1](https://github.com/verbb/formie/releases/tag/3.0.0-beta.1)), we're not looking to make this available in Formie 2.x.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
