### ISSUE TITLE
Conditional field rules ignoring "fieldNamespace" when rendering pages/fields

### ISSUE THREAD

**Issue by CustomCodeIT** [verbb/formie#1395]
### Describe the bug

Hi there,

I am trying to render a form that has logic with a custom namespace.
It is a single page form, rendered manually as I need to control where it is posting to (not using submissions).

### Expected Result
I expect the logic in this form to work as configured from the admin panel.

### Actual Result
Logic does not work when a namespace is specified (both at a page and field level).

### Desired Outcome
A form that follows the logic configured on the form, even with a custom namespace

### Steps to reproduce

Take the following form with the following code:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/66106520/232232306-07da34c4-7297-42a9-b948-73e033dfb2f7.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/66106520/232232237-1d0b2d3c-5532-4075-8aaa-60b3d61b5aca.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/66106520/232232520-e84e80d3-1ec0-4e22-a49a-7061e31a883b.png">

The above renders and applies logic without issue. However if I tweak the code to add fieldNamespace:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/66106520/232232482-c6807644-dd28-47af-b8a9-4fb731947d36.png">

The logic no longer works. Despite the namespace being correct, it looks like the data attribute that handles the logic is still using the default "fields" namespace:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/66106520/232233236-e479860c-7c97-45ba-806f-73e629facfa1.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/66106520/232232699-f8c72fcd-9cfb-4e30-acf3-819c27a876c0.png">

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.4.7

### Plugin version

2.0.26

### Multi-site?

No

### Additional context

Let me know if there's anything else I can provide to help.

**Comment by engram-design** [comment]
Yep, so there are a few things that are pretty geared towards using `fields` as the namespace. In fact, posting form data to Formie won't really work without it, so it only make sense to change it when you're posting it to somewhere else - as you've mentioned you are (although the `actionInput()` in your screenshot shows otherwise).

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
