### ISSUE TITLE
Prefill a table field

### ISSUE THREAD

**Issue by JulieVelghe** [verbb/formie#1396]
### Question

I've made a form with a table field that has time fields.
These fields are then being mapped via an element integration to an entry where these values are being inputted.

I output this form on a page where I would like to have this form prefilled. How can I prefill such a table field? I couldn't find a lot of info about this.

**Comment by engram-design** [comment]
It'll be similar to how a Craft Table field is structured. Refer to the [docs](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) on populating content.

This will populate 2 rows with 2 columns. The key for each column is sequential - “col1, col2, etc). Using the handle of the column won’t work.

```twig
{% do craft.formie.populateFormValues(form, {
    tableFieldHandle: [
        {
            col1: 'test1',
            col2: 'test2',
        },
        {
            col1: 'test3',
            col2: 'test4',
        },
    ],
}) %}
```
