### ISSUE TITLE
Duplicated forms do not match source form's settings

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1398]
### Describe the bug

I have a form (built from a Stencil) that I duplicated, but the new form's settings do not match either the source form or the Stencil's settings.

The new form does have the same fields/field layout and appearance, but the following seem to have been reverted to the Formie defaults:

### Behaviour
- Submission Method
- Action on Submit
- Loading Indicator
- Validate When Typing

### Integrations
- A custom integration that is enabled in the source Stencil was disabled.

### Settings
- Submission Title Format
- Data Retention
- File Uploads

### Steps to reproduce

1. Create a Stencil with specific settings different than Formie's defaults.
2. Add a new form using that Stencil.
3. Use the Duplicate utility to duplicate that form.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.4.7.1

### Plugin version

2.0.26

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
