### ISSUE TITLE
Some settings are not copied when duplicating a form

### ISSUE THREAD

**Issue by fishriver** [verbb/formie#1404]
### Describe the bug

When I duplicate a form not all settings are copied, e.g. the field "Action on Submit" in the Appearance tab is set to "Redirect to an entry" but in the duplicated version it is set to "Display message". Also, all settings from the Integrations tab were not copied.

### Steps to reproduce

1. Go to the forms overview
2. Select a form (checkbox)
3. Select Duplicate in the actions menu
4. Open the duplicated form and check the settings mentioned above

### Form settings

- Multi-page form: No
- Submission Method: Page Reload (this setting is not copied)

### Craft CMS version

4.4.7.1

### Plugin version

2.0.27.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Can't seem to replicate that on 2.0.27.1. sorry. This was fixed in 2.0.27. Can you triple check you're on the right version of Formie?

**Comment by chrismlusk** [comment]
Hey @engram-design. I've just run into a similar issue. I cloned an existing form and the following values were not copied correctly:

### Integrations
I have the reCAPTCHA integration enabled in Formie > Settings > Captchas, however the form I duplicated has this integration disabled. The newly cloned form has this enabled, though.

### Settings
- Data Retention (reset to the default)
- Data Retention Duration (reset to the default)
- File Uploads (reset to the default)

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.

**Comment by engram-design** [comment]
Fixed in [2.0.34](https://github.com/verbb/formie/releases/tag/2.0.34)
