### ISSUE TITLE
Migrating from Freeform fails

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1406]
### Describe the bug

I'm looking into using Formie on my personal website. There's one simple Freeform contact form, with 45 submissions. When I click Formie > Settings > Migrate Forms, I get the following error message. Let me know if there's anything else I can provide to help!

![image](https://user-images.githubusercontent.com/1250017/234207319-25fe26d7-85bc-4a0e-8099-8996b66deaff.png)

### Steps to reproduce

1. Migrate a Freeform form

### Form settings

N/A

### Craft CMS version

4.4.7.1

### Plugin version

2.0.27.1

### Multi-site?

No

**Comment by engram-design** [comment]
Would you be able to let me know what Freeform version you're on?

**Comment by darylknight** [comment]
4.0.22

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"`

**Comment by darylknight** [comment]
Thank you. Yep, that partially worked. This time it did succeed with migrating the form itself, but I got this error message for all submissions. I've double checked, and they are valid email addresses (otherwise the form wouldn't have allowed it to be submitted and saved)

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1250017/234262567-78537c27-e2e3-4d93-a4c2-817235b7ef7b.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1250017/234262596-a07cd082-7342-4e17-9c4f-a588aca08886.png">

**Comment by engram-design** [comment]
Ah, looks like Freeform has changed the storage value for email fields (they used to be an array). Run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"` again.

**Comment by darylknight** [comment]
Yep, that worked! Must be a nightmare keeping track of how other people's plugins work to do this. Thank you very much.
