### ISSUE TITLE
Non en-sites throws error on every request

### ISSUE THREAD

**Issue by jishi** [verbb/formie#1407]
### Describe the bug

I have a site which is configured for Swedish language. On every page request Craft logs the following:

`[error][yii\i18n\PhpMessageSource::loadFallbackMessages] The message file for category 'formie' does not exist: /app/vendor/verbb/formie/src/translations/sv-SE/formie.php Fallback file does not exist as well: /app/vendor/verbb/formie/src/translations/sv/formie.php`

I was expecting this to be muted when I create a fallback formie.php within the translations folder (similar to site translations work) but even with that in place it still spams this error message. It's weird because it does replace translations if I create the formie.php translation file, but this error still throws for some reason.

### Steps to reproduce

1. Set site language to be sv or sv-SE
2. Render a form in a template
3. Watch the error log 

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes, some fields are adapted

### Craft CMS version

4.4.5

### Plugin version

2.0.25.1

### Multi-site?

No

**Comment by jishi** [comment]
This is also the case for Craft CMS 4.4.7.1 with Formie 2.0.27.1

**Comment by engram-design** [comment]
This is the first time I've noticed this "error" (not really an error honestly), and apparently, it's a known issue without a specific fix https://github.com/craftcms/cms/issues/1531

**Comment by jishi** [comment]
Aha, so this doesn't actually log anything outside of dev, then I guess it's a non-problem. I was just surprised that I couldn't create a formie.php and have it muted, because the error logged for the site category translations works that way, and formie do seem to load load my formie.php translation file for the customer facing site.

**Comment by engram-design** [comment]
Yeah, it's a little bit odd, I've not actually come across it. It's largely harmless, but I'll check it out.
