### ISSUE TITLE
View submissions permission doesn't list actual submissions

### ISSUE THREAD

**Issue by jishi** [verbb/formie#1408]
### Describe the bug

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3165475/234313517-32d568aa-89ca-436b-8dbc-79c70405c156.png">

When giving a user permission to view submissions, it correctly show the graph and list the number of elements in admin (see screenshot), but it doesn't list the actual submissions. It does however allow you to export a CSV with the data.

In 2.0.25.1 it didn't even show the forms under submission, so something was fixed in 2.0.27 but not mentioned in the change log it seems. However, I would expect the user to be able to view the submissions as well, just not edit them. 

### Steps to reproduce

1. Give a user the permission "View submissions" only.
2. Visit the Formie/Submissions section for a form that has submissions.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.4.7.1

### Plugin version

2.0.27.1

### Multi-site?

No

**Comment by engram-design** [comment]
Right, that would've been a side effect of correcting [another bug](https://github.com/verbb/formie/commit/1f6ca7b11fd06f807847e381013adc9a6b95ecde) with duplicating forms, and fixing how we're filtering submissions/forms in the element index.

Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"`

**Comment by engram-design** [comment]
Fixed in [2.0.28](https://github.com/verbb/formie/releases/tag/2.0.28)
