### ISSUE TITLE
Recruitee integration needs an update

### ISSUE THREAD

**Issue by sander-lameco** [verbb/formie#1409]
### Describe the bug

According to the [API documentation of Recruitee](https://docs.recruitee.com/reference/candidates-post) the API expects a payload like this: 
``` json
{
  "candidate": {
    "emails": ["%string%"],
    "phones": ["%string%"],
    "sources": ["%string%"],
    "name": "string",
    "remote_cv_url": "%string%",
    "cover_letter": "%string%"
  },
  "offers": [
    %integer%
  ]
}
```

Now currently the integration sends it like this:
``` json
"candidate": {
    "email": "%string%",
    "name": "%string%",
    "phone": "%string%",
    "remote_cv_url": "%string%",
    "referrer": "%string%",
    "photo":  "%string%",
    "cover_letter": "%string%",
    "open_question_answers_attributes": []
}
```

Note that some fields are renamed and require an array, also `offers` is completely missing and `photo` is not requested anymore.

### Steps to reproduce

1. Create a form with the fields
2. Link the integration
3. Submit the form
4. Check Queue 

### Form settings

- Multi-page form: Yes or No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

3.8.7

### Plugin version

1.6.26

### Multi-site?

No

**Comment by sander-lameco** [comment]
Sorry, I might have been looking at the wrong documentation. [This](https://docs.recruitee.com/reference/offersoffer_idcandidates) seems to be more like the one integrated in Formie.

But according to this documentation `photo` isn't a mappable field.

We get this 400 error:
```
{
  "error": [
    "Cv can't be blank"
  ],
  "error_fields": {
    "cv": [
      "can't be blank"
    ]
  }
```

Which I think is a account configuration issue.
Will update this issue with more info or close if needed.

**Comment by sander-lameco** [comment]
Apparently the API can also accept a CV file but I don't see this option in the Formie => Recruitee integration.

> Link to file saved on some external website. You can use candidate[cv] instead if you want to upload a file - see examples.

**Comment by engram-design** [comment]
It's correct that this supports [offers](https://docs.recruitee.com/reference/offersoffer_idcandidates) objects. I'm with you on the `photo` field, that doesn't seem to make much sense. However, the integration is 1.5 years old now. I believe we had it purpose-built for @jan-dh so it probably could do with expanding its functionality.

It probably makes more sense to allow candidates to be created (for a typical enquiry form), but I believe they might have wanted offers to be created from form submissions too.

As for the `CV` value, that should be `remote_cv_url` (marked as "CV" in the mapping table).

**Comment by sander-lameco** [comment]
Thanks for the reply, I understand this integration isn't really top priority hence it is in the Miscellaneous section.

You are correct that `CV` is mapped but it is mapped to `candidate[remote_cv_url]`. But the clients configuration made it so that it expects a `candidate[cv]` with a file instead of the URL. Would that be possible to include as an option?
The client is also looking into disabling the file requirement, but that might be a dead end.

**Comment by engram-design** [comment]
Not that it's not a priority, but you're probably the second person I know to actually use it! 🙂

Ah, I see in the API notes:

```
Link to file saved on some external website. You can use candidate[cv] instead if you want to upload a file - see examples.
```

Which given their example is still a file path `candidate[cv]=@/path/to/cv.pdf` which doesn't fully make sense to me. Providing the raw file in the payload _might_ be possible, but I'll need to look into it.

Everything is completely customisable with events to hook into the payload and edit it, before being sent to 
Recruitee if that helps in the meantime - https://verbb.io/craft-plugins/formie/docs/developers/events#the-beforeSendPayload-event

**Comment by sander-lameco** [comment]
That is indeed weird, but I guess the difference is it would actually download the file instead of creating a link.
We are currently chatting with Recruitee Support to see if there is a account configuration which might help for now, but a option to include a `candidate[cv]` as well as a `candidate[remote_cv_url]` would be nice.

**Comment by sander-lameco** [comment]
@engram-design turns out the problem was that the url to the CV wasn't publicly available. (We used a local env and a staging env (htpasswd) for testing. After disabling the htpasswd it worked.

Only thing is we're getting an error returned from Recruitee or Formie even if the candidate is successfully inserted into Recruitee.

```
API error: “Missing return “candidateId”
{
  "candidate": {
    "id": 51359843,
    "name": "Lameco Development",
    "emails": [
      "development@lameco.nl"
    ],
    "phones": [
      "0612345678"
    ],
    "created_at": "2023-04-26T13:32:03.633311Z",
    "updated_at": "2023-04-26T13:32:04.883970Z",
    "photo_url": "https://recruitee-main.s3.eu-central-1.amazonaws.com/candidates/51359843/normal_photo_kgwym8cadmgw.png",
    "photo_thumb_url": "https://recruitee-main.s3.eu-central-1.amazonaws.com/candidates/51359843/thumb_photo_kgwym8cadmgw.png",
    "cv_url": "https://recruitee-main.s3.eu-central-1.amazonaws.com/candidates/51359843/cv_c6wc19l6ts4r.pdf",
    "cv_pdf_url": "https://recruitee-main.s3.eu-central-1.amazonaws.com/candidates/51359843/pdf_cv_c6wc19l6ts4r.pdf",
    "open_question_answers": []
  }
}
. Sent payload 
{
  "candidate": {
    "email": "development@lameco.nl",
    "name": "Lameco Development",
    "phone": "0612345678",
    "remote_cv_url": "https://louwers-hanique-staging.lamecoserver.com/uploads/vacancies/blanco_2023-04-26-132945_enpd.pdf",
    "referrer": "Website",
    "cover_letter": "Dit is een test van Lameco Development op de staging omgeving",
    "open_question_answers_attributes": []
  }
}
” /home/louwers/domains/louwers-hanique-staging.lamecoserver.com/public_html/shared/vendor/verbb/formie/src/base/Integration.php:149
```

Any clues if it is Recruitee or Formie side?

When I look into the code on line [#158](https://github.com/verbb/formie/blob/craft-4/src/integrations/miscellaneous/Recruitee.php#L158) it should take the `candidate[id]` which according to the error is in the `response `.

**Comment by engram-design** [comment]
That one's on my end, fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"`

**Comment by engram-design** [comment]
Fixed in [2.0.28](https://github.com/verbb/formie/releases/tag/2.0.28)

**Comment by sander-lameco** [comment]
Thanks a lot, I will do a test when possible.

**Comment by sander-lameco** [comment]
Could you also fix this for Craft 3 version of Formie? Currently running: `1.6.26`.
