### ISSUE TITLE
Error rendering row.getFields()

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#141]
**Description**
Hi,

I'm attempting to render a forms fields with rows as described here https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields

using the following

``` twig         
{% set form = craft.formie.forms({handle: 'billingAddress'}).one()%}

{% for page in form.getPages() %}
  {% for row in page.getRows() %}
    {% for field in row.getFields() %}
      {{
        craft.formie.renderField(
          form,
          field,
          {
            fieldNamespace: 'billingAddress'
          }
        )
      }}
    {% endfor %}
  {% endfor %}
{% endfor %}
```

But I'm getting a twig runtime error saying 

> Impossible to invoke a method ("getFields") on an array.

Unsure if there's a bug here or I'm missing something

**Steps to reproduce**
1. Attempt to render fields in a row using row.getFields()

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.18
- Craft version: 3.5.11.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Sorry about that, the docs are actually incorrect, Should be:

```
{% set form = craft.formie.forms({handle: 'billingAddress'}).one()%}

{% for page in form.getPages() %}
  {% for row in page.getRows() %}
    {% for field in row.fields %}
      {{
        craft.formie.renderField(
          form,
          field,
          {
            fieldNamespace: 'billingAddress'
          }
        )
      }}
    {% endfor %}
  {% endfor %}
{% endfor %}
```
