### ISSUE TITLE
`require is not defined` when trying to bundle `formie-lib` JS with Vite

### ISSUE THREAD

**Issue by johndwells** [verbb/formie#1410]
### Question

We need to manually initialize a form (which we load on-demand into a modal), so have followed the documentation's guidelines on importing via modules:

https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules

We use ViteJS to bundle our app. The app appears to build fine, but when we run our JS in the browser, we see this error in the console:

```
caught ReferenceError: require is not defined
    at formie-form-base.js:1:17
```

The line in question is this:

```
const globals = require('./utils/globals');
```

This is a known limitation that Vite does not support Commonjs. Despite the various ways I have tried to nudge Vite to play nice, we're still stumped.

Ultimately I just need a way to get `window.Formie` defined, so that we can then call `Formie.init()` when we need to. Happy to hear any advice!

**Comment by engram-design** [comment]
I've actually been meaning to change that to a module, which feels more modern anyway. It's always been a bit of an anti-pattern.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"`

**Comment by johndwells** [comment]
@engram-design Amazing Josh, thank you for the quick response!

So, next question, and please let me know if you'd like to carve this into a separate request. The change you made worked great, now we can run `Formie.initForm()` on a form element that we have dynamically injected into the page.

However, the form requires additional CSS - in our case specifically we have a telephone form field. Is there a way to have those automatically lazyloaded in as well?

Right now my workaround is to add this into the <head> of all pages: `{{ craft.formie.renderFormCss('general') }}`. Which is OK, but I just wanted to ask if you had a better idea.

Thanks again!

**Comment by engram-design** [comment]
Ah yes, the CSS isn't lazy-loaded in. I _could_ do this through JS, but it seemed a little gross, but it's probably how we're going to have to do it in the future. There's a number of reasons we do this, mostly so that people can control where in the document CSS (and JS) is rendered.

For now, you'll indeed need to use `renderFormCss` to get Formie to prompt the CSS to be included in the page.

**Comment by johndwells** [comment]
Thanks Josh. Turns out we hit another snag with this overall approach, which is particular to our situation - we host this site on Servd, so at the time that we're building our app, the environment doesn't have access to our vendor folder. Our current workaround is to copy the contents of the plugin's `web/assets/frontend/src` into a path that we commit, but I think we might go a completely different route, and just call `renderFormCss` and `renderFormJs` on all pages so that all of the necessary code is already in place. Feels dirty but it appears to be a viable solution.

**Comment by engram-design** [comment]
Ah, yeah that's a tricky one. At some point, we'll likely abstract the JS out to an `npm` package that you can include in your projects to make this easier. https://github.com/verbb/formie/issues/1010

**Comment by johndwells** [comment]
@engram-design Thanks for pointing me to that issue, I'll keep an eye on it.

**Comment by engram-design** [comment]
Updated in [2.0.28](https://github.com/verbb/formie/releases/tag/2.0.28)
