### ISSUE TITLE
Default author for the Elements (Entry) integration do nothing

### ISSUE THREAD

**Issue by jishi** [verbb/formie#1412]
### Describe the bug

I have an integration where a form submit creates an entry within a Channel. There is a setting where you select the user that will be assigned as the author for the post, but this seems to do nothing. 

Problem being that when I try to update the entry over graphQL, the calls fails. Other editing of it automatically sets author to current user, so it isn't directly evident.

### Steps to reproduce

1. Setup form with an elements integration, that creates an entry 
2. Declare the integration to assign Default Author to any user of the system
3. Submit form
4. Entry will now lack author in the entry list, also when you try editing the entry. 
5. If you save it, it will get the current user as author

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes 

### Craft CMS version

4.4.7.1

### Plugin version

2.0.27.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.27.1"`

**Comment by engram-design** [comment]
Fixed in [2.0.28](https://github.com/verbb/formie/releases/tag/2.0.28)
