### ISSUE TITLE
Address sub-fields are out of order

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1418]
### Describe the bug

I seem to be having an issue where my ZIP and State sub-fields are rendering out of order.

<img width="707" alt="address" src="https://user-images.githubusercontent.com/5922913/235969408-98684546-26a4-4361-9f16-7c07686f3806.png">

When editing the form, the sub-fields are ordered with State coming before ZIP, so I would expect the same behavior on the front end. I've tried various configurations of sub-fields enabled/disabled, but ZIP keeps getting rendered before State.

I do have my own form template (but it is not using custom files), but this still happens even when I switch `Appearance > Form Templates` to Default Formie Template.

### Steps to reproduce

1. Add an Address field with at least State and ZIP sub-fields.

### Form settings

- Custom Form Templates: No

### Craft CMS version

4.4.9

### Plugin version

2.0.28

**Comment by engram-design** [comment]
This would just be an oversight on my part, sorry. There is indeed inconsistency with the order of fields and I'll get that sorted. You also can't [re-order sub-fields](https://github.com/verbb/formie/issues/490)

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
