### ISSUE TITLE
Submission UID as a variable in notifications

### ISSUE THREAD

**Issue by bartrylant** [verbb/formie#1420]
### What are you trying to do?

Right now we're able to use the Submission ID in a notification. I want to include a link in the email where people can edit their own submission. As en extra safety layer, it would be nice to be able to use the UID instead of the ID.

### What's your proposed solution?

Add Submission UID as a variable for notifications.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28`

**Comment by bartrylant** [comment]
I have updated to this version but I don't see it in the dropdown yet in the notifications pane.

<img width="478" alt="Scherm­afbeelding 175" src="https://github.com/verbb/formie/assets/1434451/bc8e643b-5c12-44f8-914c-87d981bd0238">

**Comment by engram-design** [comment]
Cleared your caches? Seems to show for me! 
<img width="355" alt="image" src="https://github.com/verbb/formie/assets/1221575/85a303b3-bcfb-45c4-835a-ad54570df0b9">

**Comment by engram-design** [comment]
Added in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
