### ISSUE TITLE
Formie integration in Campaign: bug in Category fields

### ISSUE THREAD

**Issue by webvader** [verbb/formie#1423]
### Describe the bug

We're using the Formie integration with Campaign. We've built a Formie form which is composed of 4 fields, three PlainTextfields (firstName, LastName, email) and one category field (Topics). The Category field is used to determine the topics the user is interested in which are Blog categories. We're using the categories to build segments in Campaign.

We then used the custom fields in a Contact model. So also two PlainText fields, since email is already present in the contact model and a categories field named Topics, linked to same categories.

To sync the Formie data to Campaign, we use the available integration in Formie. All single fields are synced without a hitch, but the category field always stays empty. After some digging we found that the Formie integration processes the Category field as a comma-seperated list of Category titles. Campaign then tries to set the fields via `setFieldValues` but since the categories are not an array of category id's those are not picked up by `setFieldValues`.

### Steps to reproduce

1.  Build form in Formie with Category field
2. Build Contact in Campaign with the same Category field
3. Setup integration
4. Try to sync a form submission to Campaign
5. Category field is empty in Campaign but categories are filled in submission

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.9

### Plugin version

2.0.28

### Multi-site?

Yes

### Additional context

I've also posted an issue on the Campaign issue tracker.
https://github.com/putyourlightson/craft-campaign/issues/382

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28`

**Comment by engram-design** [comment]
Fixed in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
