### ISSUE TITLE
Mailchimp contact disappearing from audience when appending a tag to existing contact.

### ISSUE THREAD

**Issue by dhmax88** [verbb/formie#1430]
### Describe the bug

We are using Formie's integration with Mailchimp, including double opt-in and appending tags settings checked. 
When a new email address is used, and 'sign up to mailing list' is checked the Mailchimp process works as expected, a double opt-in email is received and the contact is added to the list with a tag that we pass in to Formie via the populateForms function. 

Now, when going to another page and filling out another form, which has a different mailchimp tag associated with it, the audience member is updated with that extra tag BUT... also seems to be removed from the audience... even though the contact still does exist (somewhere!?) in Mailchimp. We can't decide whether this is a Mailchimp issue or a Formie issue 😓 

### Steps to reproduce

1. Create form with double opt-in + append tags options checked. 
2. Pass tag to mailchimp and subscribe.
3. With the same email address and a different tag, submit the form again...
4. The contact updates in Mailchimp (only visible if you're already on the contacts page within MC) but disappears from the Mailing List selected within the forms integration options.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.67

### Plugin version

1.6.25

### Multi-site?

No

**Comment by dhmax88** [comment]
This seems to be caused by this line

`'status' => $this->useDoubleOptIn ? 'pending' : 'subscribed',`

When a user is not new, and they submit a 2nd form where useDoubleOptIn is true, that contact is then set back to pending within Mailchimp - causing them to disappear from an audience. No 2nd opt-in email is sent from Mailchimp so that contact will now only ever be 'pending'.

**Comment by engram-design** [comment]
Hmm, good point. I suppose we can remove the "status" setting, which enforces a users status, whether they're new or existing. Instead, relying on `status_if_new` to do the same thing, checking the opt-in status. I agree that we probably shouldn't be altering the status of existing contacts.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28`

**Comment by engram-design** [comment]
Fixed in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
