### ISSUE TITLE
Formie form editor interface does not load intermittently

### ISSUE THREAD

**Issue by jubalj** [verbb/formie#1432]
### Describe the bug

In the past few months I have noted that when I attempt to edit a formie form it does not load the fields and editing UI. e.g. -

![image](https://github.com/verbb/formie/assets/39228775/4e4fd5a1-9375-4ba8-a0c9-c3d15256062b)

The following error is shown on the console log:
Console log - 
![image](https://github.com/verbb/formie/assets/39228775/650fe600-8345-4980-9a59-ad5a1c18ea90)

Page refresh seems to fix the error - but also reproduces the error; ie. it loads without error on some refreshes and with error on others. 

### Steps to reproduce

1. Try to edit formie form

### Form settings

- Multi-page form:  No
- Submission Method: Ajax or Page Reload
- Client-side Validation: 
- Custom Form Templates:  No

### Craft CMS version

4.4.10.1

### Plugin version

2.0.28

### Multi-site?

yes

**Comment by engram-design** [comment]
Can you provide your OS and browser versions? Is this on your local dev server? If so, can you let me know the specs?

I've seen similar issues on staging/production servers with Cloudflare's RocketLoader enabled, in case that's a factor (although the exact error is different). It's certainly not something I can reproduce.

Does this happen _every_ time, or just sometimes?

**Comment by jubalj** [comment]
Thanks for the prompt reply

The issue seems to be server-side as it also happens on the mobile browser and on the Mac. I am currently using Windows 11 and Chrome (Version 112.0.5615.140). 

The first load is almost always without the interface loaded, and then it needs to be refreshed for the rest to show. So every initial load seems to be impacted. It's in a cloud production server.

The server settings are as follows: Essentially LAMP stack with php-fpm
![image](https://github.com/verbb/formie/assets/39228775/3dfc67a5-263a-4eed-b75e-5849747cf07d)

**Comment by engram-design** [comment]
If it's a JS error, it must be client-side, but that seems very strange behaviour. I've had no other reports like this I'm afraid. Is the JS error coming from the `formie.js` file?

Any other plugins enabled? Cleared Craft's caches?

**Comment by jubalj** [comment]
Hey Josh,

Yes, the error is client side - I meant it's something specific to the server that is causing the error as it happens across multiple clients.. 

There are a few other plugins enabled - but minimal Typography, redactor and asyncqueue.
 
error is from the compiler-core.esm-bundler.js file as it tries to traverseChildren nodes - It is a bit past my understanding, not sure if it's some sort of race condition.

![image](https://github.com/verbb/formie/assets/39228775/f0094ff6-51c1-4ba0-bae3-53401c15bfcb)

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
