### ISSUE TITLE
resetClasses doesn't seem to affect alerts

### ISSUE THREAD

**Issue by adrianjean** [verbb/formie#1434]
### Describe the bug

Whether using the `resetClasses` config/formie.php setting, or in twig — the `resetClasses` feature does not seem to have an effect on error messages. `fui-` classes remain.

### Steps to reproduce

1. Set the `resetClasses`
2. Submit a form with a required field omitted
3. Note the css classes still have `fui` elements.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes 
- Custom Form Templates: Yes and No — happens in both scenarios.

### Craft CMS version

4.4.10.1

### Plugin version

2.0.28

### Multi-site?

No

**Comment by engram-design** [comment]
This is true for client-side validation, where classes are added with JS. I'll see what I can do.

**Comment by adrianjean** [comment]
Could even be just be a note in the docs about the setting not having an effect on client side generated responses.

Thanks for looking into it!

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
