### ISSUE TITLE
Date field: Changing the date format breaks datepicker

### ISSUE THREAD

**Issue by Diewy** [verbb/formie#1435]
### Describe the bug

When using a date field in a non-standard format (anything other than "yyyy-mm-dd", e.g. "dd-mm-yyy"), the functionality of setting minimum and maximum dates in the date picker seems to be compromised. This issue is observed on the frontend after saving the changes.

### Steps to reproduce

1. Add a date field 
2. Select a different date format, e.g. "dd-mm-yyyy".
3. Select a minimum date, e.g. Today + 1 week.
4. Save & check the frontend

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.11

### Plugin version

2.0.28

### Additional context

If I were to hypothesize a potential solution, I would suggest that the following line of code should adhere to the date format settings: https://github.com/verbb/formie/blob/9c831dfee242591d2909139a6866af5fc3a72e62/src/web/assets/frontend/src/js/fields/date-picker.js#L67

**Comment by engram-design** [comment]
For Flatpickr (the datepicker) there's actually two input fields, and two date formats. There's an internal format and external one. The internal is used for the value saved to the field, which should always be consistent and never change (the `Y-m-d H:i:S` value). The external or visual value is what the end-user sees, which is configurable.

Can you let me know what your field settings are? I've tested a bunch of different format, but the min/max date limits seem to work all okay. Even tested `dd-mm-yyyy` as the date format and you can see the limiting working:

<img width="322" alt="image" src="https://github.com/verbb/formie/assets/1221575/4571bca4-2a3d-478d-bc39-0d77025a0e9a">

<img width="297" alt="image" src="https://github.com/verbb/formie/assets/1221575/4855f853-9975-4728-a3c0-584ebe5cd1bb">

<img width="363" alt="image" src="https://github.com/verbb/formie/assets/1221575/1e0069fd-4dba-479b-96b2-9fe0af6949bd">

**Comment by Diewy** [comment]
I am unable to reproduce the issue anymore; it appears to be functioning correctly at the moment. I'm unsure about the cause, but it seems like I may have reported the issue prematurely. My apologies!
