### ISSUE TITLE
New user passwords are saved un-hashed when disabling integration queue

### ISSUE THREAD

**Issue by johndwells** [verbb/formie#1436]
### Describe the bug

I've run into an issue whereby when the queue is disabled for integrations, user records created via the 'Users' integration are being saved to the database with un-hashed passwords. This is troublesome when `Activate User` is enabled in the form's integration settings, as the then activated user cannot login on subsequent attempts.

With the queue enabled, passwords are being saved in the expected hashed format.

### Steps to reproduce

1. Add user integration in `Settings` -> `Elements`
2. Create user registration form with `Email` and `Password` fields
3. In form settings, enable User integration
4. In integration settings, map `Email` and `Password` user attributes
5. In Formie settings, disable `Submissions` -> `Use Queue for Integrations`
6. Render and submit form
7. Check latest record in `users` db table

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No
- Use Queue for Integrations: No

### Craft CMS version

4.4.1.1

### Plugin version

2.0.27.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28"`

**Comment by johndwells** [comment]
@engram-design Hero! I appreciate such a fast response, thank you.

**Comment by engram-design** [comment]
Fixed in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
