### ISSUE TITLE
themeConfig settings not applying to Stripe payment field input

### ISSUE THREAD

**Issue by javangriff** [verbb/formie#1437]
### Describe the bug

It appears that the `fui-input` class is being output directly on the field input within the `_input.html` template for the Stripe payment integration. This means that any `themeConfig` settings for the `fieldInput` are not honoured.

### Steps to reproduce

1. Create a form with a Stripe payment integration within a payment field
2. Add a `themeConfig` for the form/field and change the class attribute for the `fieldInput`

### Form settings

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: Yes

### Craft CMS version

4.4.10.1

### Plugin version

2.0.28

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28"`

**Comment by engram-design** [comment]
Fixed in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
