### ISSUE TITLE
Email Preview not showing correctly if there is a payment field

### ISSUE THREAD

**Issue by aodihis** [verbb/formie#1438]
### Describe the bug

After updating to version 2.0.28 the preview for email notification got this error message if there is a payment field inside the form. But if there is an submission and email notification trigger, the email got sent without error.

`Notification email parse error for Subject: {field.be}”. Template error: “verbb\formie\models\DynamicModel::__construct(): Argument #1 ($attributes) must be of type array, string given, called in /var/www/html/vendor/verbb/formie/src/fields/formfields/Payment.php on line 87” /var/www/html/vendor/verbb/formie/src/models/DynamicModel.php:21`

### Steps to reproduce

1. Create form with payment field inside it, in our case it is stripe payment.
2. Create email notification and preview.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.4.10.1

### Plugin version

2.0.28

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.28"`. 

Please note that payment fields can't really be previewed at the moment without some payment data. At some stage, we may introduce "mock" data to show what actual content will look like, but that's low on the priority list.

**Comment by engram-design** [comment]
Fixed in [2.0.29](https://github.com/verbb/formie/releases/tag/2.0.29)
