### ISSUE TITLE
File upload fields in field groups are not included in notification email attachments

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#144]
**Description**
File upload fields in field groups are not included in notification email attachments. Looking at the code for attaching files, it appears as though there is an assumption of a flattened field list being returned by `$submission->getFieldLayout()->getFields()` so asset fields are never getting evaluated. [See screenshot here](https://www.screencast.com/t/afWe8UmwYue9).

**Comment by engram-design** [comment]
Fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
