### ISSUE TITLE
Using `autosuggestField` in custom integration's form settings throws error

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1443]
### Describe the bug

Attempting to use an `autosuggestField` in my `_form-settings.twig` template for a custom integration throws an error from the Vue bundler:

```
TypeError: Cannot read properties of undefined (reading 'initialValue') at Proxy.render (eval at UC (vue.esm-bundler.js:61:21), <anonymous>:1362:34)
```

Here's my field code:

```twig
{{ forms.autosuggestField({
    label: 'Form Name',
    name: 'formName',
    required: true,
    suggestEnvVars: true,
    value: form.settings.integrations[handle].formName ?? '',
    warning: macros.configWarning('formName', 'formie'),
    errors: integration.getErrors('formName'),
}) }}
```

### Steps to reproduce

1. Add an autosuggest field to a form settings template

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.4.11

### Plugin version

2.0.29

**Comment by engram-design** [comment]
The problem with using that field, is that it's a Vue component, and it's trying to resolve the `vue-autosuggest` component from Craft within the Vue app that Formie is using. It also makes it challenging to combine Vue 2 and Vue 3.

I've not figured out a way to make this work, so for now, you can't use an `autosuggestField` within integration settings for a form.
