### ISSUE TITLE
The `EVENT_AFTER_SEND_PAYLOAD` event isn't fired when creating a Draft.

### ISSUE THREAD

**Issue by taylordaughtry** [verbb/formie#1444]
### Describe the bug

If an Elements Integration has the `createDraft` option enabled `EVENT_AFTER_SEND_PAYLOAD` is never triggered. Since we've technically 'sent' the payload at this point (i.e. the draft has been created) and we're about to return early, it seems reasonable to trigger that event here to ensure it's still available for developers' use.

Opening a super-small PR now for this; let me know if there's any context I'm missing! Happy to tweak something if needed.

### Steps to reproduce

1. Create an Elements Integration
2. Enable the `createDraft` setting.
3. Attempt to bind a listener for the `EVENT_AFTER_SEND_PAYLOAD` event
4. You shouldn't ever see your logic fired, since current logic returns early

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

3.7.54

### Plugin version

1.6.21

### Multi-site?

Yes

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.26"`.

**Comment by engram-design** [comment]
Updated in [1.6.27](https://github.com/verbb/formie/releases/tag/1.6.27)
