### ISSUE TITLE
Hidden field default value does not get saved correctly!

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#1446]
### Describe the bug

Since 1.6.26 (updated from 1.6.20) the default value for a hidden field gets saved incorrectly.
The value I enter is `{{ currentSite.language }}` but the value always gets reset to `{{ currentSite.language } }`
**Mind the extra space between the closing curly braces!** 

It looks correct in the form editor (see screenshot 1) but it gets saved incorrectly (see screenshot 2) and therefor the field is empty in all submissions and my conditionals to send notifications are broken.

![image](https://github.com/verbb/formie/assets/16959207/9cff77ce-0694-4044-98d8-98289b7e0c84)
![image](https://github.com/verbb/formie/assets/16959207/47a2cb40-a760-4c79-ac3a-36d1b8e35cd8)

### Steps to reproduce

1. Add a hidden field with a default value `{{ currentSite.language }}`
2. Save the field and re-open it.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.8.10

### Plugin version

1.6.26

### Multi-site?

Yes

**Comment by engram-design** [comment]
This was a breaking change made in [1.6.22](https://github.com/verbb/formie/blob/craft-4/CHANGELOG.md#breaking-changes-1) to mitigate security concerns. Hidden fields now only support short-hand syntax, but not the full range of Craft global variables.

Having said that, `currentSite` is probably a good use case which isn't working. I actually thought Craft included these as global variables, but seems not to be the case when using `renderObjectTemplate()`.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.26"`.

**Comment by engram-design** [comment]
Updated in [1.6.27](https://github.com/verbb/formie/releases/tag/1.6.27)
