### ISSUE TITLE
Pipedrive Integration Custom Field Issue

### ISSUE THREAD

**Issue by bryantAXS** [verbb/formie#1447]
### Describe the bug

Inside the Integrations tab for a specific form, when configuring the field mapping for Pipedrive, the "Lead Field Mapping" section doesn't pull in the associated "Lead/Deal" custom fields from inside Pipedrive.

What appears to be happening is shared "Lead/Deal" fields from inside Pipedrive are being included only inside the **Deal Field Mapping** list, rather than inside **both** Deal Field Mapping and Lead Field Mapping.

https://capture.dropbox.com/a9WQbGsZywqmpWXy

When configuring Pipedrive Custom Fields inside their CRM, custom fields are noted as being "Lead/Deal" fields because those custom fields apply to both Leads and Deals.

https://support.pipedrive.com/en/article/custom-fields

The solution is making sure that "Lead/Deal" custom fields from inside Pipedrive appear in both Field Mapping sections within Formie.

### Steps to reproduce

1. Configure multiple Lead/Deal fields inside Pipedrive
2. Configure Pipedrive integration inside formie settings
3. Configure Pipedrive integration inside form Integration settings
4. Attempt to pull in both Deal and Lead fields for mapping.

### Form settings

- Multi-page form: No
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

### Craft CMS version

4.3.6.1

### Plugin version

2.0.20

### Multi-site?

No

**Comment by engram-design** [comment]
Right, so deal custom fields also apply to leads it seems? You can see that we fetch the [`dealFields`](https://github.com/verbb/formie/blob/9a132ad2e695e06981cdee03cbc2f7223a9aeaed/src/integrations/crm/Pipedrive.php#L141-L170) endpoint (see [API](https://developers.pipedrive.com/docs/api/v1/DealFields)), but because there's no `leadFields` I was under the impression that you couldn't fetch custom fields for leads.

Happy to make the change to include deal custom fields as lead custom fields, but just wanted to confirm! I'm not exactly a Pipedrive expert.

**Comment by bryantAXS** [comment]
Yes... I believe that's the case...

Their documentation is vague (and arguably incomplete) about how it works behind the scenes, but inside the Pipedrive UI it's very clear that Lead and Deal custom fields are shared between both models.

I'm hoping that if you save a Deal custom field to a Lead it also populates there too!

**Comment by bryantAXS** [comment]
Actually the Add a [Lead API](https://developers.pipedrive.com/docs/api/v1/Leads#addLead) documentation speaks to this and notes that:

> Please note that leads do not have a separate set of custom fields, instead they inherit the custom fields' structure from deals.

So hopefully that works!

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.29"`.

**Comment by engram-design** [comment]
Updated in [2.0.30](https://github.com/verbb/formie/releases/tag/2.0.30)
