### ISSUE TITLE
Address provider field - allow sub-fields to be enabled but hidden 

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#145]
**What are you trying to do?**
We only want the typeahead address field to display in the form but currently we've got to also enable at least one of the address sub-fields.

**What's your proposed solution?**

Change option 'Enabled' to  'hide this field' on the sub-fields so they will be populated by the typeahead address entered but not visible to the user if set to hidden. If not hidden they will display as usual.

**Additional context**
+ If you can get the original autocomplete address displayed in the admin submission view that would be great - currently it's only showing the address sub-fields.

**Comment by engram-design** [comment]
All addressed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20).

- Added hidden option to each field
- Allow just the autocomplete field with no other fields
- Show autocomplete content in submissions
