### ISSUE TITLE
400 Response when submitting a form that is rendered multiple times on one page

### ISSUE THREAD

**Issue by gddotorg** [verbb/formie#1450]
### Describe the bug

I have a website on which the contact form is integrated twice (footer and modal). The first form (footer) always works.  With the second one, however, we get a 400 error when submitting. Message: "Unable to verify your data submission." Sounds like a CSRF token issue to me. However, I have checked the token sent and it is sent correctly. The cache is activated and we have integrated the JS snippet from the documentation. Creating a new token works for both forms. Any idea?

### Steps to reproduce

1. Create a form
2. Render the form twice on one page {{ craft.formie.renderForm(form) }}
3. Try to submit the second rendered form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.67

### Plugin version

1.6.24

### Multi-site?

Yes

**Comment by engram-design** [comment]
What caching does your site use? Twig template tags (`{% cache %}`) or static caching?

How are you showing the form in the modal? As in, does the form exist in the DOM on-load, and you're just toggling the hidden state of the modal content, or using a more advanced method?

I have no issue submitting the forms via:

```twig
{% set form = craft.formie.forms({ handle: 'contactForm' }).one() %}

{% do form.setFormId('formie-form-1') %}
{{ craft.formie.renderForm(form) }}

<script>
    // Wait until the DOM is ready
    document.addEventListener('DOMContentLoaded', (event) => {
        // Fetch the form we want to deal with
        let $form = document.querySelector('#{{ form.formId }}');

        // Find the CSRF token hidden input, so we can replace it
        let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

        // Fetch the new token for the form and replace the CSRF input with our new one
        fetch('/actions/formie/forms/refresh-tokens?form={{ form.handle }}')
            .then(result => { return result.json(); })
            .then(result => { $csrfInput.outerHTML = result.csrf.input; });
    });
</script>

{% do form.setFormId('formie-form-2') %}
{{ craft.formie.renderForm(form) }}

<script>
    // Wait until the DOM is ready
    document.addEventListener('DOMContentLoaded', (event) => {
        // Fetch the form we want to deal with
        let $form = document.querySelector('#{{ form.formId }}');

        // Find the CSRF token hidden input, so we can replace it
        let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

        // Fetch the new token for the form and replace the CSRF input with our new one
        fetch('/actions/formie/forms/refresh-tokens?form={{ form.handle }}')
            .then(result => { return result.json(); })
            .then(result => { $csrfInput.outerHTML = result.csrf.input; });
    });
</script>
```

**Comment by thomashoefferl** [comment]
It seems that the problem can occur when the refreshtoken requests are fired overlapping so that both are sent without the CSRF cookie set yet. Both requests then get a different CSRF token cookie set in the response, the 2nd cookie is actually overwriting the first one and therefore the initial token doesnt work anymore.
For me it looks like thats exactly what happens in your case

Maybe there is a possiblity to set the csrf cookie already for the initial page load response or something to avoid that issue ?

**Comment by engram-design** [comment]
From my understanding of how CSRF tokens work, having multiple ones should be fine, and they should all be valid. Rather than one overwriting another, and invalidating the previous ones.

You haven't mentioned if you're using any caching. For example, using the "csrf cookie already for the initial page load" won't work for a statically-cached site, as once used, it will be invalid. Still, I can't seem to reproduce this one yet either...

**Comment by thomashoefferl** [comment]
yes thats true - but the situation can be a bit more tricky. 
CSRF works by matching/asigning a cookie token to a request token. So the cookie token must match the request token.

the refresh-token endpoint generates a request token and returns it to embedd it in the form, while asigning it to the  cookie token for later matching - if existing. If the  cookie token does not exist yet, it will create one.

So the problem situation is when you dont have a cookie token yet and fetch 2 request tokens in parallel. In that case you will get a individual cookie token asigned to both of them as there was none before - but only one can be used as of how cookies work. 

So when requesting 2 csrf tokens you either need to ensure that you already have a cookie token upfront or request them sequentially so the 2nd one will use the cookie created by the first one.

Another and probably easiest and cleanest possibility for that case would be to use only 1 request token. As you are rendering the same form twice with the same form handle you should be able to fetch only 1 csrf token and use it for both forms

**Comment by engram-design** [comment]
Right, I see what you mean. I'll have to do some testing on my end just to ensure that doesn't throw any unexpected issues, but that's a good starting point.

**Comment by gddotorg** [comment]
@engram-design @engram-design Thank you guys for the discussion so far.
Just briefly to add: We use Blitz's static cache and reload all CSRF tokens as described in the documentation. So each form has its own CSRF token. It should also be mentioned that we do not always receive a 400 error. Sometimes I don't get one and both forms work as expected. My colleague instead gets one right at the first test. Sometimes only the second form works and we get the 400 on the first. To me, the issue initially sounded more like a rendering issue in the frontend. So what @thomashoefferl mentions also sounds like a good approach to me.

**Comment by gddotorg** [comment]
@thomashoefferl I have implemented and tested your solution of using only one CSRF token for both forms. Unfortunately no luck on that one. Still getting a 400.

@engram-design I've tested a little further and now I've come to suspect a caching issue here. I have deactivated Blitz cache completely and now we don't get 400 anymore. But as I mentioned earlier, when the cache is activated, the CSRF tokens are regenerated and replaced correctly.

**Comment by thomashoefferl** [comment]
well as it seems disabling the cache leads to exactly what I mentioned in the first post - the cookie token is set in the response of the intial page request and therefore it already exists upfront so you dont run into the issue. So it seems the cache is preventing the cookie token to be set upfront.

Still also the 1 Token solution should work and it did perfectly in my tests - happy to get in touch directly to have a look at your concrete implementation case to see where the problem lies

**Comment by engram-design** [comment]
@thomashoefferl Just so I'm clear on what you're doing on your end, can you share the changes you've made for a single token per request?

**Comment by thomashoefferl** [comment]
Sure, this is just a quick example i used to test out selecting all forms of a page by a selector, grouping by formhandle and requesting a token per handle and set it to all forms using that handle.

With that code - when having 2 forms using the same handle only 1 request is being send.

Its already a bit a generic solution so for sure can be simplified for specific use cases. 

Let me know if any further info is requiered

```
let nforms = []

//get all forms by selector and save their handle and ID
document.querySelectorAll(".contact").forEach(section => {
    let form = section.querySelector(".form");

    let formId = form.dataset.formId;

    if (formId) {
        const currentForm = document.querySelector("#" + formId);

        if (!currentForm) return;

        const formHandle = currentForm.querySelector(
            "input[name='handle']"
        );
        //Find the CSRF token hidden input, so we can replace it
        const csrfInput = currentForm.querySelector(
            "input[name='CRAFT_CSRF_TOKEN']"
        );
        nforms.push({
            handle: formHandle.defaultValue,
            input: csrfInput
        })
    }
})

//group forms by handle 
handles = nforms.reduce((acc, curr) => {
    if (!acc[curr.handle])
        acc[curr.handle] = [curr.input]
    else
        acc[curr.handle].push(curr.input)
    return acc;

}, {})

//Request token for each unique handle and set for all forms using this handle
Object.keys(handles).forEach(formHandle => {

    fetch(
            "/actions/formie/forms/refresh-tokens?form=" + formHandle
        )
        .then((result) => {
            return result.json();
        })
        .then((result) => {
            handles[formHandle].forEach(csrfInput => csrfInput.outerHTML = result.csrf.input);
        });

})
```

**Comment by engram-design** [comment]
I believe our new JS mechanism should help this sort of situation, among others.

```twig
{% set form = craft.formie.forms.handle('contactForm').one() %}

{{ craft.formie.renderForm(form) }}

{% js %}
    // Wait until Formie has been loaded and initialized
    document.addEventListener('onFormieInit', (event) => {
        // Fetch the Form Factory once it's been loaded
        let Formie = event.detail.formie;

        // Refresh the necessary bits that are statically cached (CSRF inputs, captchas, etc)
        Formie.refreshForCache('{{ form.formId }}');
    });
{% endjs %}

```
