### ISSUE TITLE
Date/Time fields with Text Inputs and Dropdown displays are missing validation feedback

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1456]
### Describe the bug

When making a Date/Time field required, if the display type is Text Inputs or Dropdown, no error messages appear after validation. This is the case when validation occurs on blur or on submit.

<img width="566" alt="dates" src="https://github.com/verbb/formie/assets/5922913/e320cb83-620e-46c9-bb0f-a02df1edbb9a">

### Steps to reproduce

1. Add a Date/Time field
2. Set its display type to `Text Inputs`
3. Make the field required
4. Trigger an invalid submission

### Form settings

- Submission Method: Ajax
- Custom Form Templates: No

### Craft CMS version

4.4.13

### Plugin version

2.0.30

**Comment by chrismlusk** [comment]
(Sorry for the flood of Date/Time activity!)

If I add a value of `0` to a sub-field, the form submission fails because that's of course an invalid value. I see this error in the response:

```
Date Field - Text Inputs cannot be blank.
```

But a user wouldn't see anything since error messages aren't showing up.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
