### ISSUE TITLE
Date/Time field with Dropdowns display does not show configured placeholder

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1457]
### Describe the bug

When configuring a Date/Time field with a `Dropdowns` display type, you can set placeholder text for each sub-field. But that placeholder is not used as the initial value on the front end.

<img width="546" alt="date-dropdowns" src="https://github.com/verbb/formie/assets/5922913/b458f471-2c37-4af2-9868-33701ea91efc">

Looking at the markup, both the custom placeholder and the default blank one have the `selected` attribute.

![date-dropdowns-markup](https://github.com/verbb/formie/assets/5922913/a75b622b-fc45-4eec-a131-1a087517a1c0)

### Craft CMS version

4.4.13

### Plugin version

2.0.30

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
