### ISSUE TITLE
Conflict when trying to install Sprout Redirects

### ISSUE THREAD

**Issue by nilsenpaul** [verbb/formie#1459]
### Describe the bug

When trying to install Sprout Redirects, the requirements cause a conflict with the requirements of Formie:

<img width="832" alt="Scherm­afbeelding 2023-06-01 om 16 00 43" src="https://github.com/verbb/formie/assets/6794819/69864ea2-b379-4286-ab9a-3e2e29d306c9">

Would it be possible to update the requirements of Formie to use version 5.1 of `html-to-markdown`?

### Steps to reproduce

1. Install Formie
2. Try to install Sprout Redirects

### Form settings

Not applicable

### Craft CMS version

4.4.13

### Plugin version

2.0.18

### Multi-site?

no

**Comment by engram-design** [comment]
That's strange, Formie allows `^4.10 || ^5.0` (so 4.10+ or 5.0+) so it should be possible to have both. In fact, I can install both just fine on a fresh install. I might recommend adding the `-W` option to the composer command?

**Comment by engram-design** [comment]
Can you confirm if the above fixes your issue?
