### ISSUE TITLE
Multi page forms - submit to email marketing integration on each page submission.

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#146]
**What are you trying to do?**
We've got multi-page forms with a mailing list signup opt-in on page 1 and a hidden status field on each form page with an incremental value i.e.
From page 1, step = 1
From page 2, step = 2
etc.

We have this so we can capture incomplete signups within the Email Marketing platform, in our case Campaign Monitor, where we have automated customer journeys.
If a user is sitting on step=1 etc. CM will then trigger an email after 3 days or so to get the user back and complete the form or get in contact another way.

**What's your proposed solution?**
Add additional option in the form settings to toggle on/off sending to email marketing on every page submit. So if email marketing opt-in is automatic or has been selected, the users is subscribed/updated in the email marketing integration.

**Additional context**

**Comment by engram-design** [comment]
I can see the value in this. I'll have to give it some thought as to how best to handle it. Integrations are heavily tied to the complete step of a submission at the moment.

**Comment by anchovy** [comment]
Sweet - in the meantime is there and event/hook I can use to manually trigger the integration after the first/every page of a multi-page form has been submitted?

I've looked at https://verbb.io/craft-plugins/formie/docs/developers/events but the _afterSubmission_ event is only triggered when the entire form, i.e. all pages, have been completed.

So, can we either get the _afterSubmission_ event to be called after every page submission as well or another event like _afterMultiPagePageSubmission_ that's called on every multipage submit?

**Comment by engram-design** [comment]
I've added this event for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.25",
  "...": "..."
}
```

Then run `composer update`.

See the [event docs](https://verbb.io/craft-plugins/formie/docs/developers/events#the-afterIncompleteSubmission-event). You should be able to trigger the integrations with the following:

```
use verbb\formie\Formie;
use verbb\formie\events\SubmissionEvent;
use verbb\formie\services\Submissions;
use yii\base\Event;

Event::on(Submissions::class, Submissions::EVENT_AFTER_INCOMPLETE_SUBMISSION, function(SubmissionEvent $event) {
    if ($event->success) {
        Formie::$plugin->getSubmissions()->triggerIntegrations($event->submission);
    }
});
```

**Comment by anchovy** [comment]
Thanks @engram-design - exactly what I was after.

For anybody else that requires integrations to be fired on the first (or any page - see note 3 below) page of a multipage form I've managed to get this working via the following code.

```
Event::on(Submissions::class, Submissions::EVENT_AFTER_INCOMPLETE_SUBMISSION, function(SubmissionEvent $event) {

    if ($event->success && $event->submission->isIncomplete && $event->submission->dateCreated == $event->submission->dateUpdated)  {

        // $event->success 
        // true, successfully submitted

        // $event->submission->isIncomplete 
        // true, For complete submissions we'll let the default integrations code be used. Will also detect single page forms and ignore.

        // $event->submission->dateCreated->date === $event->submission->dateUpdated->date 
        // true, This is the first page and first submission, not a re-submission via the back button.

        $submission = $event->submission;
        $form = $submission->getForm();
        $integrations = Formie::$plugin->getIntegrations()->getAllEnabledIntegrationsForForm($form);

        foreach ($integrations as $integration) {

            if (!$integration->supportsPayloadSending()) {
                continue;
            }

            // Add additional useful info for the integration
            $integration->referrer = Craft::$app->getRequest()->getReferrer();
            Formie::$plugin->getSubmissions()->sendIntegrationPayload($integration, $submission);
        
        }
    }
}); 
```

## There's a coupe of things to note.

1. Doesn't take into account the queue setting for Integrations - it'll try the integration immediately as `Formie::$plugin->getSubmissions()->triggerIntegrations($event->submission);` can't fetch a valid submission (because it's incomplete??) in line 39 of _vendor/verbb/formie/src/jobs/TriggerIntegration.php_ 
2. Expects the 'Opt-In Field' and any of the initial fields mapped in the integration you want initially captured that to be on the first page of any multipage form. 
3. Will only try the integration on the first page - if you want to try on all submissions (expect when it's actually complete) remove the `$event->submission->dateCreated->date === $event->submission->dateUpdated->date` in the if statement.
4. This has only been tested with a Campaign Monitor integration.

**Comment by engram-design** [comment]
Nice one! I thought to mention you might like to use `$submission->form->getCurrentPageIndex()` to check if this is the first page or not, which might be easier, or even `$submission->form->isFirstPage()`.

I've also just pushed a fix for the queue job to handle incomplete submissions as well.

**Comment by anchovy** [comment]
Hi @engram-design 

Sweet!

I'm getting the error `Class 'verbb\formie\jobs\Submission' not found` now after the queue job fix.
Adding in `use verbb\formie\elements\Submission;` to _TriggerIntegration.php_ seems to fix the issue.

**Comment by engram-design** [comment]
Yep, sorry about that, someone distracted me halfway through that update!

**Comment by anchovy** [comment]
Sweet / hope that person wasn't me! :)

Code now looks like the following, and is working with the queue job now thanks to your update:

```
Event::on(Submissions::class, Submissions::EVENT_AFTER_INCOMPLETE_SUBMISSION, function(SubmissionEvent $event) {
    
    $submission = $event->submission;

    if ($event->success && $submission->isIncomplete && $submission->form->isFirstPage() )  {

        Formie::$plugin->getSubmissions()->triggerIntegrations($submission);
        
    }
    
});
```

**Comment by engram-design** [comment]
Nah, not at all 😄

I'll actually close this now, as I don't think I'm planning to introduce this as native behaviour, at least not in the near-future. But glad it can be reasonably possible using events.

Let me know if there's any further issues.
