### ISSUE TITLE
Date/Time field with calendar shows as invalid after initial selection

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1460]
### Describe the bug

When a form's validation setting is to validate when typing, Date/Time calendar fields are showing up as invalid after initial selection. Once you click away from the field, the error goes away.

[Screen recording](https://watch.screencastify.com/v/N4mFtF0ohHmPY4D6HBEJ)

### Steps to reproduce

1. Add a Date/Time field with the display type set to Calendar.
2. Set form to validate when typing.

### Craft CMS version

4.4.13

### Plugin version

2.0.30

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
