### ISSUE TITLE
Unable to access "Save Button Style" setting in theme config

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1461]
### Describe the bug

When creating a custom theme config, I'm unsure how to access a form's "Save Button Style" setting to determine which CSS class to apply. 

I couldn't find anything in the docs ([Page Settings](https://verbb.io/craft-plugins/formie/docs/developers/page#attributes-1) does not list this attribute), but in the source code I see that the `PageSettings` model includes an `saveButtonStyle` property. I attempted to use this like so:

```twig
saveButton: {
    attributes: {
        class: [
          "{{ saveButtonStyle == 'link' ? 'btn--link' : 'btn--secondary' }}",
        ],
    },
},
```

But that gives me this error:

```
Variable "saveButtonStyle" does not exist in "__string_template__4cf3ab9936590e47a947ba15df78b940" at line 1.
```

### Craft CMS version

4.4.13

### Plugin version

2.0.30

**Comment by engram-design** [comment]
Looks like that's slipped past the docs, but it's indeed `saveButton`.

```twig
saveButton: {
    attributes: {
        class: [
          "{{ page.settings.saveButtonStyle == 'link' ? 'btn--link' : 'btn--secondary' }}",
        ],
    },
},
```
