### ISSUE TITLE
Multiline Text Field: Validation of 'max value'

### ISSUE THREAD

**Issue by jorisnoo** [verbb/formie#1468]
### Describe the bug

It appears that, when setting a character limit for multi-line text fields, the validation is correctly displayed on input (displaying the character limit message in red), but submitting the form is still possible. Leaving the field empty does throw a validation error, exceeding the character limit does not.

Thanks a lot for your support! 🙌 

### Steps to reproduce

1. Create a new form with a multi-line text field
2. In the field settings, set 'Required Field' and 'Limit Value' to on
3. Set a 'Max Value' of 500 Characters
4. Submit the form with an input of more than 500 Characters

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.13

### Plugin version

2.0.30

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by jorisnoo** [comment]
Thank you! 🙌 ✨

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
