### ISSUE TITLE
Filtering Sent Notifications by "Failed" always yields zero results

### ISSUE THREAD

**Issue by johndwells** [verbb/formie#1469]
### Describe the bug

When in Formie > Sent Notifications, filtering by "Failed" always returns zero results. The behavior is the same whether filtering all forms, or a specific form.

### Steps to reproduce

Pre-requisite: must have at least one failed sent notification

1. Go to Formie > Sent Notifications
2. Filter listing by status of "Failed"

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.13

### Plugin version

2.0.30

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
