### ISSUE TITLE
ActiveCampaign CRM field mapping doesn't show number fields?

### ISSUE THREAD

**Issue by thijskaspers** [verbb/formie#1470]
### Describe the bug

When using the ActiveCampaign CRM integration we only see ActiveCampaign text fields at the Deal mapping. For example: if we create a number field "Number of employees" in ActiveCampaign and then refresh the integration in the Formie integration settings, it doesn't show this field in the field mapping section. If we create a text field in ActiveCampaign, it shows up instantly after refreshing the integration in Formie.

Perhaps this also goes for other field types (other than number), haven't been able to test that yet.

### Steps to reproduce

1. Create a form with an ActiveCampaign CRM integration
2. Add a number field in ActiveCampaign to a Deal (or Contact?)
3. Check Formie to see if the number field shows up in the fieldmapping section.

### Form settings

- Multi-page form: No

### Craft CMS version

4.4.13

### Plugin version

2.0.30

### Multi-site?

Yes

**Comment by engram-design** [comment]
Ah, looks like those field types are unique to Deals, and don't exist for Contacts. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.31"`.

**Comment by thijskaspers** [comment]
Thanks @engram-design!

If I may, there is 1 more thing I've noticed. The Deals 'pipelines' field is nicely prefilled with pipelines from ActiveCampaign, but the Deals 'stage' field is not for the stages. We can work around this with a hidden or disabled field where we enter the stage ID and then map that to the stage field, but being able to select a stage from the API would be even nicer :)

Enjoy your weekend!

**Comment by engram-design** [comment]
Ah yes, this was fixed for Formie 1.x for Craft 3. Should be fixed for the next Formie 2.x release too (run the `composer require` command above again).

**Comment by engram-design** [comment]
Fixed in [2.0.32](https://github.com/verbb/formie/releases/tag/2.0.32)
