### ISSUE TITLE
Max character length on textarea field has incorrect validation

### ISSUE THREAD

**Issue by thijskaspers** [verbb/formie#1479]
For a contact form, we've set a limited value of 1000 characters on the field. However, when entering exactly 1000 chars, we can't submit the form. The validation says the maximum number of characters is 1000. When we remove 4-5 characters, then we are able to submit the form.

Somehow there's a difference between the number of chars in the field and the server side validation. Our guess would be new lines / paragraphs? Not sure though.

See example:

![Scherm­afbeelding 2023-06-20 om 10 39 42](https://github.com/verbb/formie/assets/1608184/9296510f-62b0-406a-91a4-b6d3735d3e66)

The counter shows 0 chars left, and HTML maxlength of the field is set to 1000. After submission, the validation error shows up.

### Steps to reproduce

1. Create a form with a textarea field
2. Enable limit value and set max chars to 1000
3. Enter 1000 characters
4. Submit the form

### Form settings

- Multi-page form: No
- Submission Method: Ajax

### Craft CMS version

4.4.14

### Plugin version

2.0.31

### Multi-site?

Yes

**Comment by engram-design** [comment]
So there is a _slight_ variation in character count, but that's only applicable for multi-byte characters like emoji's, that have to be translated for them to be saved to the database.

But, you raise an excellent point. New lines are evaluated as `\r\n` which is more than a single newline character.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by thijskaspers** [comment]
Thanks for the quick reply and fix!

**Comment by engram-design** [comment]
Fixed in [2.0.32](https://github.com/verbb/formie/releases/tag/2.0.32)
