### ISSUE TITLE
[Bug] Email Notification Preview CSS Applied to Admin

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#148]
**Description**
When adding styles to html email notifications theses styles are applied to the CMS admin area form due to the preview functionality

**Steps to reproduce**
1. Create a custom notification template with CSS that targets elements present on admin console
2. Admin console styling is affected by preview.  [Here's a screenshot](https://www.screencast.com/t/ub1h9rCA) (notice all the text is white and not visible)

Simple fix would be to just load the preview in an iframe

**Comment by engram-design** [comment]
Fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
