### ISSUE TITLE
Allow entries fields to be selected in the fields dropdown (+) in the default value of another field

### ISSUE THREAD

**Issue by thijskaspers** [verbb/formie#1480]
### What are you trying to do?

In the default value of fields, you have the option to select other fields to render their value there after submission:

![Scherm­afbeelding 2023-06-20 om 10 52 17](https://github.com/verbb/formie/assets/1608184/931f116b-3e2d-416c-99ad-1d49698a6460)

If you have an "entries" fieldtype however, you can't select that one from this list. A default 'dropdown' field does work, but we have a "dropdown" entries field showing a couple of entries, and that one can't be selected. We're trying to get the title of the selected entry into a new hidden field with some additional text, so that we can map it to an ActiveCampaign Deal field.

Would be convenient to also be able to select entries fields, so we won't have to build a plugin to do something with a hook/event or the JS event onAfterFormieSubmit.

### What's your proposed solution?

Add entries fields to the fields dropdown. Use the selected "Label Source" from that entry field as the value that will be rendered?

### Additional context

Craft 4.4.14
Formie 2.0.31

**Comment by engram-design** [comment]
The reason for the lack of support with the variable-picker (or field-picker) not being able to pick element fields, is that the value of fields can have multiple values. By default, these are stored as an array of IDs as their values. I know you might have your entries field set to dropdown, which is a singular value, but this can be changed to multi-dropdown or checkboxes.

We would have to introduce changed behaviour for hidden fields that want to use element fields as their value to translate IDs to their label (for most elements, this is their title). I'll see what I can do.

**Comment by thijskaspers** [comment]
Ah makes sense, thanks!

The regular 'dropdown' field has a 'multiple' option too by the way. So that might mess it up too when you select it as a variable in another field?

What would be the quickest workaround you think to retrieve the entry title and use it in another field? My guess would be a javascript event to copy the entries dropdown option label into a hidden field right before submission?

**Comment by engram-design** [comment]
Using JS is probably the right approach, as it (I assume) needs to happen in real-time on the front-end so that's client-side code. I would probably listen to the JS change event on the source field, and use that for the destination field value.

Where it might be tricky is using the title, instead of the ID of elements. For that, you might fare better with a PHP event for on-submission, to set the field value when the form is submitted.
