### ISSUE TITLE
Ability to limit form submissions by custom options

### ISSUE THREAD

**Issue by belkin** [verbb/formie#1481]
### What are you trying to do?

Ability to limit form submissions e.g. by time/days or custom options on dropdown/radio group or checkbox group fields.
It is useful if you use one form for event registration. I know that there's already an option to restrict submissions but current the options aren't that versatile.

### What's your proposed solution?

Here I'm not so sure how best to implement it in a form with an existing limit option. But it will certainly be nice to have the availability to place it where we want, just like the rest of the fields with the following options for example:

<img width="1672" alt="image" src="https://github.com/verbb/formie/assets/3419659/2d4f4b20-e5fa-4d51-98e5-f7f672d6f604">

**Comment by engram-design** [comment]
We do have limit options for submissions, mostly for total and date/times.

<img width="450" alt="image" src="https://github.com/verbb/formie/assets/1221575/a9b6341e-14dc-4893-9226-f9cbbb379387">

As for "custom" options (i.e. being able to set arbitrary time), we'll likely never provide the ability to source this from a field, which would be a bad idea if someone manipulated that field from the front-end. It also poses data issues to ensure date/times are formatted correctly.

I would recommend using the "Schedule Form" setting, which allows you to set (a single) start/end date.
