### ISSUE TITLE
Attach (structured) metadata to submissions

### ISSUE THREAD

**Issue by timoschwarzer** [verbb/formie#1484]
### Question

Hi! I'm writing a custom module that further processes submissions from Formie. For Forms, I can add custom fields to them and fill them like that, but for Submissions, I didn't find a way to add custom internal fields to them without exposing them to the users filling out the forms. Is there any way I can attach metadata to submissions or would I have to manage this myself using a custom model? Simple key/value pairs would be enough.

Thank you very much! :sun_with_face:

**Comment by engram-design** [comment]
Sure! You can store arbitrary data using the `snapshot` property, which we use to store some things, like dynamic field settings at submission time.

Usage is:

```php
$submission->snapshot['myData'] = 'test';
```

**Comment by timoschwarzer** [comment]
@engram-design Thank you very much! Have a wonderful week :sun_with_face:
