### ISSUE TITLE
Add Redactor content field

### ISSUE THREAD

**Issue by uandco** [verbb/formie#1486]
### What are you trying to do?

Hi,

It seems like the only option to add generic content (formatted content between 2 block or before submit button for example) is to use the HTML field, which is not ideal for non technical content managers, if they just need to add some paragraphs, bold or links.

### What's your proposed solution?

I would suggest adding some kind of Redactor powered field that allows form editors to add content within a form, so they can format the content without knowing HTML.

**Comment by engram-design** [comment]
It's [planned](https://github.com/verbb/formie/issues/1028) but it almost certainly won't be a Redactor field, as we don't want to rely on another plugin for a field.

**Comment by uandco** [comment]
@engram-design thanks for your prompt reply and apologises for the duplicate, that's exactly the same feature request. Agreed on Redactor, any rich text editor would do, it doesn't really need fancy features as the inter-fields content would often be very simply formatted.
