### ISSUE TITLE
Small bug in templates/forms/_panes /usage.html

### ISSUE THREAD

**Issue by bartdigitalpulse** [verbb/formie#1489]
### Describe the bug

Missing backslash on this line:
https://github.com/verbb/formie/blob/craft-4/src/templates/forms/_panes/usage.html#L10C1-L11C1

`verbb\supertable\\elements\\SuperTableBlockElement`

should be

`verbb\\supertable\\elements\\SuperTableBlockElement`

### Steps to reproduce

not applicable

### Form settings

not applicable

### Craft CMS version

Craft Solo 4.4.15

### Plugin version

2.0.32

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.32"`.

**Comment by engram-design** [comment]
Fixed in [2.0.33](https://github.com/verbb/formie/releases/tag/2.0.33)
