### ISSUE TITLE
Update the docs regarding change from `limitAmount` to `minType`/`maxType`

### ISSUE THREAD

**Issue by joshuabaker** [verbb/formie#1490]
### Describe the bug

`limitAmount` doesn’t appear in the GraphQL schema.

<img width="513" alt="Screenshot 2023-07-04 at 18 00 07@2x" src="https://github.com/verbb/formie/assets/160484/20d6df0f-b3eb-4a7c-84ae-60a00971b5ac">

### Steps to reproduce

N/a

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.4.15

### Plugin version

2.0.32

### Additional context

The property is still [listed in the docs](https://verbb.io/craft-plugins/formie/docs/developers/field#multi-line-text:~:text=or%20words.-,limitAmount,field%E2%80%99s%20number%20of%20characters/words%20to%20limit%2C%20based%20on%20limitType.,-useRichText). There’s no note of an alternative.

**Comment by engram-design** [comment]
Looks like the docs are out of date on this one, as we refactored limits to encompass min/max limits. Using `min/max` should do the trick, with `minType/maxType` being the respective character/words type.

**Comment by joshuabaker** [comment]
Thanks, Josh. Please can I request that you update the docs for that (i.e. upgrade guides).

Am I right in thinking that the values for `minType` and `maxType` are the same as `limitType`? Thinking about downstream changes to my React implementation.

**Comment by engram-design** [comment]
Updated the docs already, but also added to the upgrade docs. But that's correct, they're the same, just renamed from "limit" to handle both minimum and maximum constraints.

**Comment by joshuabaker** [comment]
Thanks, Josh. Appreciate the quick responses. 🙏🏻 

Noticed that `limitType` is still showing in the field docs. Going to close this anyway as we have reference here for posterity.
