### ISSUE TITLE
Hubspot boolean returns always true

### ISSUE THREAD

**Issue by kristofser** [verbb/formie#1491]
### Describe the bug

When submitting to Hubspot and you have the Agree form field (which is a boolean)
In Hubspot.php on line 86 there is this part of code:
![image](https://github.com/verbb/formie/assets/5928907/0c1570e8-961a-4f4a-8ecd-7da06bcf837e)
For some reason there is a loop that checks this variable more than once which makes 
false -> 'false' -> 'true'
![image](https://github.com/verbb/formie/assets/5928907/348bab43-5d4e-447f-84fc-9afe03903d10)

### Steps to reproduce

1. add an Agree field to your form 
2.  Submit form to Hubspot
3. Value in Hubspot turns out to be always false or always true

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes or No

### Craft CMS version

Craft 4.4.14

### Plugin version

2.0.32

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.32"`.

**Comment by engram-design** [comment]
Fixed in [2.0.33](https://github.com/verbb/formie/releases/tag/2.0.33)
