### ISSUE TITLE
Loading minified JS and CSS files

### ISSUE THREAD

**Issue by sander-lameco** [verbb/formie#1493]
### What are you trying to do?

We ran a Craft site using Formie through a Web Audit, and one of the issues was the formie-theme.css not being minified. Not sure if I'm missing something (docs or config) that allows this but I can't find anything regarding this.

### What's your proposed solution?

Provide the JS and CSS minified instead.

**Comment by engram-design** [comment]
Good call, not sure how I've missed that. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.32"`.

**Comment by engram-design** [comment]
Fixed in [2.0.33](https://github.com/verbb/formie/releases/tag/2.0.33)
