### ISSUE TITLE
Freshsale Connection not working - queue error

### ISSUE THREAD

**Issue by veronika-g** [verbb/formie#1495]
### Describe the bug

Hi!

I have integrated and connected Freshsales. The connection seems to be working, as it shows "Connected State." However, when the form is submitted, it appears an error message in the queue.

![Bildschirmfoto 2023-07-12 um 14 44 24](https://github.com/verbb/formie/assets/71814882/fe7f5b22-958a-4a31-9268-5b46809ac319)

### Steps to reproduce

1. Setup freshsales integration
2. Create form
3. Add freshsales to form
4. Test form in frontend
5. Message is successful and submission works
6. Error in queue

![Bildschirmfoto 2023-07-12 um 14 44 24](https://github.com/verbb/formie/assets/71814882/17d44976-eda7-4749-8c10-8d3246312682)

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.0

### Plugin version

2.0.24

**Comment by engram-design** [comment]
If you press the "Refresh Integration" button, does that all work correctly? I can confirm things work as expected on my end with a brand new account. One recent change is the domain name setting, which should be the "Bundle alias" in your API Keys settings.

e.g. `https://my-domain.myfreshworks.com/crm/sales` and not just `https://my-domain.myfreshworks.com/`

**Comment by veronika-g** [comment]
Yes, everything is working, I have the green "connected" state. I use the "Bundle Alias" as well. 
The problem occurs at a customers website. Does Freshsales still need something to be activated? Maybe on the Freshsales site?

**Comment by engram-design** [comment]
If you can share what your field mapping looks like for the integration, that'd be useful. You can also send us a support request with all your form information so we can see exactly how you're mapping things (Formie > Settings > Get Support).

There should be nothing to my knowledge you need to do on Freshsales, other than gaining the API details.

**Comment by veronika-g** [comment]
Thank you! I will you send you a support request!

**Comment by veronika-g** [comment]
Hi,

Yesterday I send a support request, but we found out something new.
Map to Contact works fine.
Map to lead sends us the 403 error. 

Maybe this info helps.

Best,
Veronika

**Comment by engram-design** [comment]
Unfortunately, I haven't received your support request yet. You can also export your form and send it through to `support@verbb.io` by going to Formie > Settings > Import/Export which will largely do the same thing. The support request just also bundles log files, which would be great (see `storage/logs/formie-*.log`).

But that does seem strange that you are getting an `Access Denied` error when adding a lead, and not a contact. I'm not a Freshsales expert, but are there any restrictions on creating leads in your account?

According to their docs:

> This indicates that the user whose credentials were used in making this request was not authorized to perform this API call. It could be that this API call requires admin level credentials or perhaps the Freshsales portal doesn't have corresponding feature enabled.
