### ISSUE TITLE
Element Integration: "Update Element Mapping" shows incorrect fields

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/formie#1496]
### Describe the bug

Hi Josh! Love the plugin. 😻

When I try to map a form's submissions to an existing entry, the fields available for matching are not correct. 
1. No matter what entry type I select, I see the same fields.
2. Fields are repeated (see screenshot). 

<img width="614" alt="entry fields repeat" src="https://github.com/verbb/formie/assets/7085184/fabd260d-404e-49a0-bf57-542e23c382be">

You can also see repeated fields in the screenshots from https://github.com/verbb/formie/issues/475.

### Steps to reproduce

1. Create an Element integration (Entry) in Settings.
2. Create a new form.
3. In Integrations, choose the new element entry integration.
4. Select an entry type.
5. Toggle the lightswitch on for "Update Entries". 

### Form settings

- Multi-page form: No
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

### Craft CMS version

Pro 4.4.14

### Plugin version

2.0.32

### Multi-site?

No

### Additional context

There are minimal options when creating a new integration. Am I missing something?
<img width="612" alt="Screenshot 2023-07-12 at 12 00 38 PM" src="https://github.com/verbb/formie/assets/7085184/77b897e0-f505-4370-9ae1-7808c4549a0f">

**Comment by engram-design** [comment]
Glad you're loving it! This was actually something that never really worked, as values in that table would need to update as you pick the entry type dropdown above. Similar to how the custom fields change when you do this.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.

**Comment by KatieMFritz** [comment]
That does the trick! Thanks so much, Josh.
