### ISSUE TITLE
Possible Unexpected Behavior with Calculations Field

### ISSUE THREAD

**Issue by idawgik** [verbb/formie#1497]
### Describe the bug

So I'm trying to wrap my head around how the Calculations field works, and it doesn't seem to be working the way I would expect with a formula. It's entirely possible I'm doing something wrong.

In my form, I have 3 number fields. One is a read only with a pre-set value. The other two allow inputs. I'm trying to set a formula where it checks if the sum of the two inputs is less than or equal to the pre-set value and output true or false.

However, no matter what I try with the formula, it doesn't seem to get to the conditional part of the formula. It will just output the value of the sum.

I have this as my formula:

`{field1}+{field2} <= {field3}`

Note: this does work if I hard code the formula (something like: 5+4 <= 10), it's only when using the field variables (added via the + button) that it doesn't work.

### Steps to reproduce

1. Create multiple number inputs
2. Create conditional field with `{field1}+{field2} <= {field3}` formula
3. Notice the value is always whatever the sum is, not true or false

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.15

### Plugin version

2.0.33

### Multi-site?

No

**Comment by idawgik** [comment]
Correction, a hard coded formula like `5+4 <= 10` does not work, it just shows the total of the first part. However, just putting something like `9 <= 10` does work.

So, is something like this not supported? It's not really clear in the documentation how advanced the formulas can be, it's just a list of the operators that are allowed.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`. 

I'd also recommend the ternary operator: `(({field1}+{field2}) <= {field3}) ? 'true' : 'false'`

In terms of the documentation, we use the [Symfony ExpressionLanguage](https://symfony.com/doc/current/reference/formats/expression_language.html#supported-operators), and Formie's docs aren't exhaustive in that regard for all the things you can do.

**Comment by engram-design** [comment]
Fixed in [2.0.34](https://github.com/verbb/formie/releases/tag/2.0.34)
