### ISSUE TITLE
Variants Source setting not populating as expected

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#1499]
### Describe the bug

The Source setting for saved variants fields doesn't populate the saved value for the dropdown.

### Steps to reproduce

1. In a form edit page, add a variants field and set all configurations including Source.
2. Click Apply and save form.
3. Click on the variants field to reopen the Edit Field modal.
4. Source dropdown displays `Select an option` instead of saved configuration.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.15

### Plugin version

2.0.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.

**Comment by engram-design** [comment]
Fixed in [2.0.34](https://github.com/verbb/formie/releases/tag/2.0.34)
