### ISSUE TITLE
[Feature Request] Fully Qualify Twig Includes

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#150]
Currently, if I want to override just form.twig I also have to override all of it's includes as well (_progress, _errors, etc.).  I can add the template directory for formie to the list of twig template roots but the problem is that any sub includes will then fail.  

For example, if i want to wrap the entirety of form.twig as follows:

```
<my-stuff></my-stuff>
<my-container> 
  {% include 'formie/form' %}
</my-container>
```

^^ This will not work because formie/form has sub includes that then fail. If all includes were fully qualified they would not fail (see below):

This: `{% include 'formie/_errors' %}` (assumes front end template root registered for `formie` namespace).
Not this: `{% include '_errors' %}`

**Comment by engram-design** [comment]
The point of custom templates is that it gives you complete control over the templating. This means you can implement it however you like, by including the template structure and features as we do, or roll your own.

I'm not sure this will be possible.

**Comment by mattcdavis1** [comment]
Yeah - i get that custom templates provide complete control but I like to minimize the code that I have to maintain. It doesn't seem like a difficult task to simply register a root and use that for all includes. Am I missing something?

**Comment by engram-design** [comment]
I'm not sure what you're suggesting about registering a root sorry.

The way we resolve a template either looks at Formie's template folder, or your own path resolving to your project template. When using `_errors` in a file, it'll always be relative to the current file.

For instance, we can't have the `form.html` file resolve to your site files, but then have all the `include` files resolve to Formie's template or your own. We'd have to refactor our templates to not use `{% include %}` and instead route them through our own Twig function to determine if we should include it from Formie's templates, or your site templates.

**Comment by mattcdavis1** [comment]
* If form.html resolves to my file then either I can control the include (and omit the formie root) or leave the formie root and let everything else resolve to formie (which is what I want).

* When I talk of registering a root, this is what I mean:
```
Event::on(View::class, View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS, function(RegisterTemplateRootsEvent $e) {
  $e->roots[$this->id] = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates/_special';
});
```

Then, in the templates:

```
{% include ['include-that-may-exist-at-user-level', 'formie/fallback-include-with-formie-root'] %}
```

**Comment by engram-design** [comment]
I'm not exactly sure what effect `EVENT_REGISTER_SITE_TEMPLATE_ROOTS` will have, or if its the right approach. What is `$this->id` in this case?

I think this is mostly down to the template template mode, and I'm not sure something like this will be possible. To be able to grab Formie's templates, we need the template mode set to `TEMPLATE_MODE_CP`, and for site overrides, `TEMPLATE_MODE_SITE`.

In any case I think a custom `{% include %}` mechanism is unavoidable anyway, as even a little bit of custom PHP code in a module isn't ideal for novices.

**Comment by mattcdavis1** [comment]
* `$this->id` is the plugin id which in this case would resolve to `formie` 
Template modes are only going to cover FE vs Backend that's not really going to be much help here as we should already be in FE mode.
* I'm not sure why you'd need a custom include - the array fallback syntax is native to Twig. If an end user overrides the template just using a normal include would work as expected.  However, if `formie` were registered as a root that would just make an additional option available.

**Comment by engram-design** [comment]
Yep, my mistake on the template mode being an issue, I was thinking of something else.

I'm liking the idea behind this, so will do some further testing on using template roots or aliases to achieve a better outcome here!

**Comment by engram-design** [comment]
Alright, so after having time to look at this properly, this is a pretty nice solution using template roots, something I hadn't even thought of, so really appreciate the suggestion @mattcdavis1. This should make template overrides much easier.

However I've actually gone with the approach of a custom Twig function - `{{ formieInclude('_includes/page-tabs') }}` - for example, mostly to facilitate what's described in https://github.com/verbb/formie/issues/161 where users want to override _just_ the include.

But, if you need it, the template roots are there for free use. In either case, this should alleviate your issue.

See [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)

**Comment by mattcdavis1** [comment]
great - thanks!
