### ISSUE TITLE
After upgrading: Column not found 

### ISSUE THREAD

**Issue by SanboKyo** [verbb/formie#1504]
### Describe the bug

After Upgrading Craft (3 ->4), Formie and several other plugins I get an error when calling a form in the backend:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_Block1_Frage1' in 'field list'

8 other forms work perfectly, as before.

### Steps to reproduce

1. Upgrading Craft 3 ->4 and Formie 1.6 > 2.0.33

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.4.15

### Plugin version

2.0.33

### Multi-site?

No

**Comment by engram-design** [comment]
I'm almost certain this doesn't have to do with Formie, as Formie doesn't really touch with `content` table. The error message is showing that there's something looking for a `Block1_Frage1` column in the content table.

Does it only throw this error when editing a form? Did you have any custom fields on that form (custom fields are managed via the Form Template)?

**Comment by SanboKyo** [comment]
It throws the error also when I call up the submissions for this form, but only in a notification pop-up.

![Bildschirmfoto 2023-07-18 um 16 20 52](https://github.com/verbb/formie/assets/26556339/4af277d7-fcf6-40bc-a643-8a32b53e33df)

Yes, I have a custom field on this form, but also on the other forms where everything works without error.

**Comment by engram-design** [comment]
Hmm. What sort of field is `Block1`? Can you try resaving that field?

**Comment by SanboKyo** [comment]
If I duplicate the form, then the error does not occur. Maybe my client has changed the handle of a field?

I will export the submissions directly from the database and delete the broken form. Thanks.
