### ISSUE TITLE
Date field getDefaultDate() throws exception return must be string but DateTime is returned

### ISSUE THREAD

**Issue by dian-kaagman** [verbb/formie#1506]
### Describe the bug

When setting a default value to the Date field it throws an internal server error on my GrapQL call:

`verbb\\formie\\fields\\formfields\\Date::getDefaultDate(): Return value must be of type ?string, DateTime returned`

### Steps to reproduce

1. Add a Date field.
2. Select a default value for this field.
3. Query the form using GraphQL.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.16

### Plugin version

2.0.33

### Multi-site?

yes

### Additional context

This is my Field_Date GraphQL query, but whether I comment this piece of code out, the error still occurs.

`
... on Field_Date {
    dateFormat
    timeFormat
    displayType
    includeTime
    includeDate
    timeLabel
    defaultOption
    dayLabel
    dayPlaceholder
    monthLabel
    monthPlaceholder
    yearLabel
    yearPlaceholder
    hourLabel
    hourPlaceholder
    minuteLabel
    minutePlaceholder
    secondLabel
    secondPlaceholder
    ampmLabel
    ampmPlaceholder
    useDatePicker
    minDate
    maxDate
    defaultDate
}
`

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.
