### ISSUE TITLE
How to retrieve the available days from the Date Field?

### ISSUE THREAD

**Issue by dian-kaagman** [verbb/formie#1508]
### Question

How can I retrieve the data from the Available Days checkboxes from the Date field -> Settings using GraphQL? In the package code I see some references like `availableDaysOfWeek` but this keyword gives me the following error when added to my query: [GraphQL] Cannot query field "availableDaysOfWeek" on type "Field_Date".

There is also no documentation available on this option: https://verbb.io/craft-plugins/formie/docs/feature-tour/fields#date-time

### Additional context

<img width="390" alt="Scherm­afbeelding 2023-07-24 om 18 12 55" src="https://github.com/verbb/formie/assets/56150605/a21103e5-96d8-42e9-80f9-d343dbc4185f">

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.

**Comment by dian-kaagman** [comment]
Thanks for implementing it in the next release @engram-design! 

I run into the problem that when I uncheck Saturday and Sunday for example (see screenshot above), I get the following response:

`['zondag', 'maandag', 'dinsdag', 'woensdag', 'donderdag']` -> translation `['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']`

In this case I expect 'vrijdag' (friday) to be in the array and not 'zondag' (sunday), since I unchecked it. It looks like the indexes of the days are not corresponding the checkboxes day strings in the CMS.

In addition, wouldn't it be more convenient to send the days indexes 0-6 (For example: Sunday = 0, Saturday = 6). Instead of the translated weekdays, in my case Dutch?

**Comment by engram-design** [comment]
Good point, that's an issue on my end with that. Run `composer require verbb/formie:"dev-craft-4 as 2.0.33"` to get that fix.

But that's also a good point about sending the numeric representations vs the named days. I assumed it'd be more useful to have the named days than the ambiguous numeric ones (does `0` stand for Sunday or Monday for example). But happy to alter it, if you prefer.
