### ISSUE TITLE
Texts are not always translated in email response

### ISSUE THREAD

**Issue by martinhellwagner** [verbb/formie#1510]
### Describe the bug

We're using the e-mail notification feature of Formie with translation strings (which are located in the `translations/en/site.php` file for English, and `translations/de/site.php` file for German) like this:

![Screenshot 2023-07-25 at 10 07 12](https://github.com/verbb/formie/assets/19146752/ebf03af6-fe6b-4913-a127-d0c9acedaee3)

The translations look this this:

```
    'translate.trainings.mail.subject' => 'Thank you for your registration!',
    'translate.trainings.mail.content1' => '
        <p>Dear participant,</p>
        <p>we are pleased to inform you that your registration for the training session
    ',
    'translate.trainings.mail.content2' => '
        has been successfully received.</p>
        <p>Further information regarding the training will be provided to you in due course. If you are still looking for suitable accommodation in Linz, we have compiled a list of recommended hotels for your convenience. You can find additional details at the following link: <a href="https://www.laska.at/hotel-recommendation" target="_blank">Hotel Recommendations</a></p>
        <p>Should you have any questions or concerns, please do not hesitate to contact us: <a href="mailto:training@laska.at">training@laska.at</a></p>
        <p>We look forward to your participation and a successful training session!</p>
        <p>Best regards,<br>Your LASKA Team</p>
    ',
```

Most of the time, the translations are honoured and the e-mail notification is displayed correctly. Sometimes however, the e-mail notification looks like this:

<img width="668" alt="Bildschirmfoto 2023-07-25 um 09 50 38" src="https://github.com/verbb/formie/assets/19146752/bccdc6b6-d541-4780-8695-5eda9904a747">

Is there a problem with fetching the translations in Formie?

### Steps to reproduce

1. Add translation strings as e-mail content
2. Submit form – e-mail gets sent

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

3.7.38

### Plugin version

dev-craft-3 as 1.5.15

**Comment by engram-design** [comment]
I'm pretty sure that's because when in the context of a queue there's no knowledge of the site that the string needs to be translated for. Formie _does_ record which site the submission was made on, but that's not fed through Craft's translations.

**However** seeing them not be consistently translated seems very odd. I can see you're using your own strings like `translate.trainings.mail.content1` which is fine, but that may be due to using static strings rather than fields which hooks into which site the submission was made on.

I should also mention that you may get mixed results using HTML in the rich text editor, because it's a complicated one that uses ProseMirror schema rather than just HTML strings.

**Comment by martinhellwagner** [comment]
Thanks for the clarification! Is there any change to get consistent translated strings in the mail notifications?

**Comment by engram-design** [comment]
So when you say _sometimes_ it doesn't work, can you provide any detail on that? I wouldn't have thought this actually work for any language other than the primary one...

**Comment by martinhellwagner** [comment]
Unfortunately, I haven't found any pattern whatsoever. It sometimes works, and sometimes doesn't. Is there any way to achieve translated mail notifications – maybe with a different approach?

**Comment by engram-design** [comment]
There's better string translation support in queue jobs in Craft 4, but it's difficult to say where this is going wrong if it's not consistent. How is your queue run, via a web request (the Craft default - when you visit the control panel), or via the CLI?

**Comment by martinhellwagner** [comment]
Unfortunately, for this project an update to Craft 4 is possible in autumn at the earliest. 😐 

We're running the queue via the CLI.

**Comment by martinhellwagner** [comment]
Would it help to create a dedicated translations file for Formie, like `translations/en/formie.php` or `translations/de/formie.php`?

**Comment by engram-design** [comment]
Potentially, although I think you’ll still run into similar issues. You’d need to update your Twig code to reflect that `t('formie')`

**Comment by martinhellwagner** [comment]
The translation pipes are only in the email notification field in Formie, not in twig. Should I change it there?

**Comment by engram-design** [comment]
Yeah, sorry that's what I was referring to.

**Comment by martinhellwagner** [comment]
Will try that, and let know if that changes anything!

**Comment by martinhellwagner** [comment]
@engram-design

I've moved the translations into `translations/xx/formie.php` files, and changed the translation pipe to `t('formie')`, as you suggested. I did a couple of tests, and they were all successful!

I'll continue to monitor the e-mail notifications, and get back to you if needed. In the meantime: thanks a lot for your help! 🚀
