### ISSUE TITLE
Loading spinner interferes with after element of submit button

### ISSUE THREAD

**Issue by carinameissl** [verbb/formie#1515]
### Describe the bug

Hello!

For several projects we've had the issue that the submit button was styled with an after element (arrow icon), however, when using the spinner as loading indicator it seems interfere with our after element: on submit, the spinner turns into the arrow icon which is spinning on submit button click. If needed, I can send you a link of an example via email. 

Is there a way to fix this problem? We'd rather not disable the loading indicator because due to the captcha we've integrated, there's a slight waiting time.

Thanks!
Carina

### Steps to reproduce

1. Press submit button on form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation:
- Custom Form Templates: No

### Craft CMS version

4.4.0

### Plugin version

2.0.24

### Multi-site?

no

**Comment by engram-design** [comment]
Just wanted to check in on this one, as you've closed the issue?

**Comment by carinameissl** [comment]
Hey, thanks for checking in - appreciate it.
Yes I've closed the issue since we found a workaround (also styling the after element of the spinner with a separate ion). However, if there's be another way of avoiding the "double styling" we'd appreciate it. Thanks!
