### ISSUE TITLE
Symfony error when sending mail on the queue with runQueueAutomatically disabled

### ISSUE THREAD

**Issue by JshGrn** [verbb/formie#1516]
### Describe the bug

When I set **runQueueAutomatically** to false in general.php and then initiate the queue with a deamon running craft queue/listen, every single submission fails with:

```
TypeError: Symfony\Component\Mime\Part\TextPart::__construct(): Argument #3 ($subtype) must be of type string, null given, called in /home/ploi/_redacted_/vendor/symfony/mime/Part/DataPart.php on line 43
```

When I then set **runQueueAutomatically** to true, and then run them within the web console, they work as expected.

As a workaround, I have disabled the queue sending in formie.php, but its not ideal. I am unsure how to debug this initially... The PHP version on CLI is the same as the web worker, and I can't initially think of anything else which is different between the methods. Perhaps there is something in Formie?

### Steps to reproduce

1. runQueueAutomatically(false)
2. Run Daemon

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

Same for all forms however, and seems to be related to the queue running method.

### Craft CMS version

4.4.16.1

### Plugin version

2.0.33

### Multi-site?

No

### Additional context

Only happens on production when running queue as a deamon.

**Comment by engram-design** [comment]
That's certainly a new error I've not seen. Can you send through the full stack trace? You're welcome to send to `support@verbb.io` if you prefer to share it there. I just need some more context where this error is coming from.

Also - what's your mailer?
