### ISSUE TITLE
Error after updating from 1.6.29 to 2.0.33

### ISSUE THREAD

**Issue by nickyichov** [verbb/formie#1519]
### Describe the bug

I updated craft CMS to lates version (4.4.16.1) and together with it I updated verbb/formie. However, now I have the following error

```
yii\base\InvalidRouteException: Unable to resolve the request "formie/csrf/input". in /var/www/html/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('formie/csrf/inp...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/web/Application.php(607): craft\web\Application->runAction('formie/csrf/inp...', Array)
#2 /var/www/html/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#3 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#4 /var/www/html/web/index.php(25): yii\base\Application->run()
#5 {main}
```
The website loads but the error appear on top of the site. I can access craft's control panel with no problem. 

![image](https://github.com/verbb/formie/assets/79098081/1e92873f-9cb8-4bb6-a81b-f5b31f8ba239)

### Steps to reproduce

1. Updated Craft CMS to 4.4.16.1
2. Updated the plugins including verbb/formie (version 2.0.33) making them compatible with craft CMS 4.4.16.1

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.4.16.1

### Plugin version

2.0.33

**Comment by engram-design** [comment]
That seems strange, is that form in an iframe or something? Are you using something out of the ordinary to render the form, like Sprig? This seems like you might be running the [cache](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms#csrf-token) snippet for refreshing the token, but I'm not sure why the error is being presented like that.

**Comment by engram-design** [comment]
Actually, I've just realised you're including a removed endpoint for refreshing your CSRF tokens for forms. Review the [v2 upgrade notes](https://verbb.io/craft-plugins/formie/docs/get-started/upgrading-from-v1#removed-controller)

**Comment by nickyichov** [comment]
Yes, this fixed the issue. Thanks for the help :)
