### ISSUE TITLE
[Feature Request] Allow Twig inside of HTML field (or create dedicated twig field)

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#152]
Allow Twig inside of HTML field (or create dedicated twig field)

**Comment by engram-design** [comment]
We won't be implementing a Twig field, so we'll look at enabling Twig in a HTML field.

**Comment by engram-design** [comment]
Added in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
