### ISSUE TITLE
Add Iterable Email Marketing integration

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1521]
### What are you trying to do?

https://api.iterable.com/api/docs

### What's your proposed solution?

https://api.iterable.com/api/docs

**Comment by chrisrowe** [comment]
Hey! This has a milestone of 2.2.0, but I know y'all just shipped v3 (congrats – I love it). Is this still on the roadmap and is there any _vague_ timeline?

**Comment by engram-design** [comment]
2.2.0 is still coming and for Craft 4! It’s our big new integrations release. Expect it by the end of the year as we’re still a little way off yet.

**Comment by chrisrowe** [comment]
Thanks Josh, good to know. Will the Craft 5 version support the new integrations?

**Comment by engram-design** [comment]
That’s right, features will be available for both Craft 4 and 5

**Comment by engram-design** [comment]
Added in [3.0.8](https://github.com/verbb/formie/releases/tag/3.0.8)
