### ISSUE TITLE
[Feature Request] Provide UI for Page Row Level Data Association

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#153]
We really need to be able to associate data with page rows because page rows typically have padding / margin and when I want to do something conditional based on a certain state I'm only able to target the page row contents. So, for example, I can hide the field in the page row via css based on logic but that still leaves me with a row that has margin / padding associated with it that I no longer want. 

To get around this I either have to do a bunch of one-off negative margin styling or add some custom javascript neither of which I really want to do.  Even if i have use custom template there's still not a great solution here.  Only think i could really do is add all the field handles to the parent row (which may be a good interim solution since UI takes alot longer to implement).

```
{% for row in page.rows %}
  {% set rowCss = '' %}
  {% for field in row.fields %} {% set rowCss = rowCss ~ ' page-row-' ~ field.handle %} {% endfor %}
  <div class="fui-row fui-page-row {{ rowCss }}">
    {% for field in row.fields %}
      {{ craft.formie.renderField(form, field, options) }}
    {% endfor %}
  </div>
{% endfor %}
```

**Comment by engram-design** [comment]
I think this comes into more of your conditional fields issue? Hiding a field isn't a great solution (but its one of the only few ways we can right now). in the future, removing the HTML element altogether would remove the element, therefore the padding/margin associated with it.

Due to how the row data structure is setup to extend a FieldLayout, it's a bit tricky storing additional information on a row in any case. Additionally, there's no UI concept of a row, nor do we want to introduce one (where you add a row to the form, then add your fields). If you prefer this, I'd suggest using the Group field to contain your fields.

I'll agree that there's not a great solution for this at the moment

**Comment by mattcdavis1** [comment]
This is a separate issue from conditional fields because even if we had conditional fields that will still leave the row visible.  I suppose you could get around that by adding logic that checks for at least one visible field before rendering the row but as it stands now the row renders regardless of what you do with the field and the row is what typically has the margin / padding.

As far as storing the data, why not just map it via index.  The UI work would still need to be done, but you could just map the data to the page row index and then reference the index in the page loop. I don't think the backend logic would be difficult but it would take some work to build out front end UI.

If you didn't want to build the UI in the main form builder area a variation of the above twig could work and would be fairly straightforward - every root level field could have the opportunity to add a class to its parent.  That would be pretty simple and wouldn't require any new UI.

**Comment by engram-design** [comment]
Well, when we implement conditional fields, we'll certainly be tackling this properly, as its a necessity to have fields display correctly. But then that opens up a can of worms about how we should react to conditional layouts - if you have 2 fields with 50% width each, but you want to hide the right field - does the lone field take up 100% width, or just 50% and stays on the left. Tricky.

I'll consider this, but I also wouldn't want to introduce too much complexity to the form builder.

**Comment by mattcdavis1** [comment]
I'm running up against this issue again - i really hate these invisible rows.  I created a custom field to wrap multiple rows but it's just painful to implement.  Here's my code from page.twig:

```
{% for row in page.rows %}
  {% set firstField = row.fields[0] ?? null  %}
  {% if row.fields|length == 1 and firstField.getGqlTypeName == 'Field_FlexField' %}
    {{ firstField.getFrontEndInputHtml(form, firstField, options)|raw }}
  {% else %}
    <div class="fui-row fui-page-row {{ rowCss }}">
      {% for field in row.fields %}
          {{ craft.formie.renderField(form, field, options) }}
      {% endfor %}
    </div>
  {% endif %}
{% endfor %}
```

The structure really needs to be fully exposed in the field designer UI.  It's just awful otherwise.

**Comment by engram-design** [comment]
Going to close this, as we have no plans to introduce a "row" UI concept for the form builder. it's confusing for non-developers, and requires just one more step to building forms (you'd need to add a "row" element first, then add fields to that).

Totally get the issue with empty row HTML elements when fields are conditionally hidden, or are classified as hidden. This should be far more maintainable using [theme config](https://verbb.io/craft-plugins/formie/docs/theming/theme-config)
