### ISSUE TITLE
HTML entities not parsed in submission index

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#1530]
### Describe the bug

HTML entities in submission titles are not parsed in the submission index. As a result, a title like `Sneed's Feed & Seed` is rendered as `Sneed&#039;s Feed & Seed` in the submission index.

### Steps to reproduce

1. Create a submission that will generate a title including a special character like an apostrophe.
2. View the submission in the index.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.16.1

### Plugin version

2.0.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Hmmm, can't seem to replicate that with regular and "pretty" quotes.

<img width="254" alt="image" src="https://github.com/verbb/formie/assets/1221575/764c20a8-bb88-4c1b-aa48-f193a47aebd3">

**Comment by engram-design** [comment]
I imagine you might be mapping the title from the content of a field. If that's the case, then you'll want to get the latest fix for that which addresses entity encoding.

To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.34.1"`.

**Comment by jmauzyk** [comment]
That's correct, thanks!

**Comment by engram-design** [comment]
Fixed in [2.0.35](https://github.com/verbb/formie/releases/tag/2.0.35)
