### ISSUE TITLE
Small lightswitch styles

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#1532]
### Describe the bug

This is super trivial, but small lightswitches display as halfway engaged when turned on
<img width="303" alt="Screenshot 2023-08-10 at 8 53 56 AM" src="https://github.com/verbb/formie/assets/21298596/6f74e230-059f-4d88-9c84-11e50fa0a23d">

### Steps to reproduce

1. In field with small lightswitch like phone, enable the lightswitch.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.16.1

### Plugin version

2.0.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yep, I believe this was a Craft 4 update change that broke this.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.34.1"`.

**Comment by engram-design** [comment]
Fixed in [2.0.35](https://github.com/verbb/formie/releases/tag/2.0.35)
