### ISSUE TITLE
How can I access button field when rendering the form?

### ISSUE THREAD

**Issue by nickyichov** [verbb/formie#1537]
### Question

I have a form that I want to style in a way that the button is located next to the field on the last row. Unfortunately, I did not find this option on Craft CMS and I need to render the form. The main issue that I have right now is outputting the button.

This is the code I have:

```
          {% set form = row.form.one() %}

          <form method="post" data-fui-form="{{ form.configJson }}">
            {{ csrfInput() }}
            {{ actionInput('formie/submissions/submit') }}
            {{ hiddenInput('handle', form.handle) }}

            {% for page in form.getPages() %}
              <div class="page" data-page-id="{{ page.id }}">
                {% for row in page.getRows() %}
                  <div class="row">
                    {% for field in row.fields %}
                      <div class="col-6 wrapper">
                        {{ craft.formie.renderField(form, field) }}
                      </div>
                    {% endfor %}
                      <div class="col-6">
                          <button type="submit" data-submit-action="submit">Submit</button>
                      </div>
                  </div>
                {% endfor %}
              </div>
            {% endfor %}
          </form>
```

I have a button that is hardcoded but I want to change it with the one on Craft CMS. 
The code still needs to be edited because at this point the button is shown after every row.

My question is how can I access the button field from Craft CMS?

**Comment by engram-design** [comment]
There are a few [similar](https://github.com/verbb/formie/issues/443) [issues](https://github.com/verbb/formie/issues/108) and as you're doing, custom rendering or template overrides is the way to go.

Might I suggest falling back to the Formie template for the submit button? This will either resolve to Formie's [template](https://github.com/verbb/formie/blob/craft-4/src/templates/_special/form-template/_includes/submit.html) or a template of your own in you're using Form Templates with template overrides.

You can do this with:

```twig
{{ formieInclude('_includes/submit') }}
```

**Comment by nickyichov** [comment]
Using `{{ formieInclude('_includes/submit') }}` in the place of the `button` element did the job. After a bit of modifying, I got the result I wanted.

I can see that there are a few requests for making the button possible to be dragged. Are you planning to implement this in any future updates or you are not prioritizing it at this moment?

Thank you for the help :)

**Comment by engram-design** [comment]
It's on our todo list 100%, we've just got to figure out a nice way to implement it! I wouldn't say it's a _priority_, but it's not bottom of the list.
