### ISSUE TITLE
Formie v1.x use field Name instead of Handle when exporting

### ISSUE THREAD

**Issue by 0xElectric** [verbb/formie#1538]
### What are you trying to do?

Can you also do for version 1.x what you did here https://github.com/verbb/formie/commit/2a74aecb8ed79321201e82791f736f25d679633a ?
Thank you.

### What's your proposed solution?

same above

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.30"`.
