### ISSUE TITLE
Add "User Email" to email notification settings

### ISSUE THREAD

**Issue by timoschwarzer** [verbb/formie#1539]
### What are you trying to do?

Currently, all email notification settings (To, CC etc.) only allow inserting "System Email" and "System Reply-To" using the GUI. The "User Email" option that exists in the body template editor is missing. You can currently insert `{userEmail}` manually to work around it.

### What's your proposed solution?

Users should be able to select "User Email" for email address fields in the email notification settings.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
