### ISSUE TITLE
Brevo Integration (Sendinblue) 400 Error

### ISSUE THREAD

**Issue by carinameissl** [verbb/formie#1541]
### Describe the bug

Hello, 

I'm currently adding the brevo integration in a project. However, after adding the API key, when testing the integration (save + refresh) I get the following error:

<img width="1192" alt="Screenshot 2023-08-22 at 10 34 50" src="https://github.com/verbb/formie/assets/62565016/d8eaae3e-f3c0-442a-ba04-64ad54ed3ac1">

Also, the integration is still called Sendinblue - I could not find an integration find brevo yet, is there any differences?

Thanks,

Carina

### Steps to reproduce

1. add sendinblue integration 
2. add API key
3. save integration
4. click refresh --> error

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.4.17

### Plugin version

2.0.34.1

### Multi-site?

no

**Comment by engram-design** [comment]
It's on my list to update the Sendinblue integration to [Brevo](https://github.com/verbb/formie/issues/1425) but I haven't investigated the changes between the two systems. I would have _hoped_ they be compatible, but they may not be given this error message.

May need to investigate further.

**Comment by carinameissl** [comment]
Thanks, would appreciate it!

**Comment by carinameissl** [comment]
Hey @engram-design!
Is there any news on this issue or an estimation on when you could look into it? My clients released their website today and we could not implement their Brevo account yet. 
Thanks 🙏

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by carinameissl** [comment]
Hey, thanks for adding - I've updated formie to this version successfully, unfortunately, I'm still getting the same error when refreshing?

**Comment by engram-design** [comment]
According to [some sites](https://wpforms.com/how-to-set-up-sendinblue-wp-mail-smtp/#Unauthorized_Key_Not_Found) they suggest creating a new api key

**Comment by carinameissl** [comment]
I actually tried that already..

**Comment by engram-design** [comment]
Would you like to try one I've just generated, as I've confirmed it works?

EDIT: Looks like they've auto-deleted it once I've shared it on GitHub. I've split it over 2 lines

```
xkeysib-0507cbf4e690ea2aba12fcba4d2bc
7ac5b3c93336859d7275f6caa080a6aaf10-wfqceelynf9fAQvd
```

**Comment by carinameissl** [comment]
hmm that one doesn't work for me either? According to my composer.json file I definitely have the right dev formie version though..

**Comment by engram-design** [comment]
Huh, very strange. Just to confirm you're using the new Brevo integration, not the Sendinblue one?

And, it's not a SMTP key, just in case? Sorry if that's a dumb question - I'm not quite sure what's going on otherwise.

<img width="554" alt="image" src="https://github.com/verbb/formie/assets/1221575/e46f05c2-9108-4c9e-b57a-4e483534becd">

**Comment by carinameissl** [comment]
Ah it works now! Yes I've used the Brevo integration and API key (accidentally used the SMTP key 2 weeks ago so valid question haha) - I've just removed the integration completely and re-added it, not it's working. Thanks so much, really excited it's working now 💯

**Comment by engram-design** [comment]
Ah, nice one! I'll admit, I almost generated an SMTP key myself, so thought it was a valid thing to mention.
