### ISSUE TITLE
Klaviyo e-mail integration: duplicate error

### ISSUE THREAD

**Issue by JoeriE** [verbb/formie#1543]
### Describe the bug

I have a form that's linked with a Klaviyo e-mail marketing integration. After submitting the form, users get subscribed to a specific list in Klaviyo. Although, if the user already has a profile on Klaviyo, I always get the error of a 'duplicate_profile'. Although, the user is not in that specific list yet. 

Is there a way to overwrite duplicate profiles, so they also get subscribed to the list?

### Steps to reproduce

1. Add form with Klaviyo email marketing integration
2. Add a profile to Klaviyo, don't add it to a list yet
3. Submit form with email that is used to make the profile in Klaviyo

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

### Craft CMS version

4.5.2

### Plugin version

2.0.43.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
That's interesting to hear. The process is split into two parts. We first call [identify](https://developers.klaviyo.com/en/v1-2/reference/identify-post) which ensures a profile is created. Then a call to [subscribe](https://developers.klaviyo.com/en/v1-2/reference/subscribe) to add them to the nominated list.

For the first call, this doesn't seem to throw an error for me, no matter what I do! New users and existing users both work fine for me. Their API does only ever return `1` as the response.

Looks like I'm using deprecated APIs in any case, so it might be prudent to update that on my end. But I can't seem to replicate your issue immediately.

Where does the `duplicate_profile` appear? In Klaviyo, or in your Formie logs?

**Comment by JoeriE** [comment]
@engram-design The error is returned from the Ajax submit request:
```Client error: `POST https://a.klaviyo.com/api/profiles/` resulted in a `409 Conflict` response:\n{\"errors\":[{\"id\":\"317567d4-1216-49e1-b462-c72cca61342a\",\"status\":409,\"code\":\"duplicate_profile\",\"title\":\"Conflict.\",\"det (truncated...)\n"```

**Comment by engram-design** [comment]
There are no references to the `/profiles` endpoint in Formie, so I'm not sure where that's coming from? Is this maybe a custom integration?
