### ISSUE TITLE
CSRF token after template override

### ISSUE THREAD

**Issue by nickyichov** [verbb/formie#1544]
### Question

After I overrode the template of a form I was using, the following error appeared:

![image](https://github.com/verbb/formie/assets/79098081/bef3f379-12e8-467f-b4af-d23fa796a23f)

The problem is with the CSRF token that needs to be replaced. However, I am not sure if that is already done in this part of the code:

```
    <form method="post" data-fui-form="{{ form.configJson }}">
        {{ csrfInput() }}
        {{ actionInput('formie/submissions/submit') }}
        {{ hiddenInput('handle', form.handle) }}
```

I found some information in the documentation that `data-fui-form` attribute takes care of the javascript part. 

The script used for the CSRF token replacement is this:

```
          <script>
              // Wait until the DOM is ready
              document.addEventListener('DOMContentLoaded', (event) => {
                // Fetch the form we want to deal with
                let $form = document.querySelector('#{{ form.formId }}');

                // Find the CSRF token hidden input, so we can replace it
                let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

                // Fetch the new token for the form and replace the CSRF input with our new one
                fetch('/actions/formie/forms/refresh-tokens?form={{ form.handle }}')
                        .then(result => { return result.json(); })
                        .then(result => { $csrfInput.outerHTML = result.csrf.input; });
              });
          </script>
```

My question is, can I completely remove the js part because it is taken care of or do I need to make some changes to it?

**Comment by engram-design** [comment]
The JS to refresh the token is still needed, only if you have static cache enabled. Removing it will cause the CSRF token to be statically cached - so just wanted to clarify your point on "it's taken care of already"?

The error simply points to this line:

```js
let $form = document.querySelector('#{{ form.formId }}');
```

Becuase you've omitted an `id` attribute on the `<form>` element, it cannot find the element. Using:

```twig
<form id="{{ form.formId }}" method="post" data-fui-form="{{ form.configJson }}">
```

Would remove the error as the form will have a proper ID. Or, you can of course change `querySelector()` to something else to identify your `<form>` element.

**Comment by nickyichov** [comment]
Giving an ID to the form fixed the problem. 

I wrongly understood this part of the [documentation](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-pages#:~:text=Make%20sure%20to%20include%20the%20data%2Dfui%2Dform%20attribute%20with%20JSON%20configuration%20from%20the%20form.%20Without%20this%20attribute%2C%20Formie%27s%20JavaScript%20will%20fail%20to%20initialise%2C%20meaning%20client%2Dside%20validation%2C%20captchas%20and%20more%20will%20not%20work.), making me think that `data-fui-form` will take care of the JS under the hood.

Thank you!

**Comment by engram-design** [comment]
So the document is correct in that regard. Formie's JS that handles everything like validation, ajax submissions field functionality, etc will work with `data-fui-form`. But this additional JS which is just for CSRF token generation does need an `id`. But, as I've mentioned, this is just example code and you're free to alter how you select your `<form>` element as required.
