### ISSUE TITLE
Captcha is not starting anymore automatically on submit (multipage form)

### ISSUE THREAD

**Issue by TurboThomsen** [verbb/formie#1548]
### Describe the bug

The Captcha is not starting automatically if i submit the form on the last page. Instead, the submission is accepted and the submission is marked as spam.

### Steps to reproduce

1. New Form (2 Pages) with Friendly Captcha
2. Fill out all required fields.
3. Submit

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No
- Integrations: Friendly Captcha, Duplicate, Honeypot, Javascript (all => Enabled: true, Show on All Pages: false)

### Craft CMS version

4.5.3

### Plugin version

2.0.34.1

### Multi-site?

Yes

### Additional context

If one required field is not filled on page 1 and I submit the form on page 2, the Captcha is automatically starting.

**Comment by engram-design** [comment]
Are there any JS errors on your front-end? Can you confirm if you see a `<div class="formie-friendly-captcha-placeholder" data-friendly-captcha-placeholder="">` element in your form's source?

**Comment by TurboThomsen** [comment]
There is no js error.
Yes, I can see the element.

Control Panel -> Submission Status Info: 
Failed Captcha “FriendlyCaptcha”: “{"success":false,"details":"captcha was not started yet","errors":["solution_invalid"]}”

**Comment by TurboThomsen** [comment]
If it helps:
Friendlycaptcha setting: Show on All Pages: false
If i use only 1 page: the captcha starts on submit.
Or if i use multipage and set show on all Pages to true -> the captcha starts on NextPage Button on Page 1.

**Comment by engram-design** [comment]
I believe this should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by TurboThomsen** [comment]
not fixed in 2.0.35

**Comment by engram-design** [comment]
I don’t suppose you could send through a public URL showing this issue? Or a screen recording? You’re welcome to send through to `support@verbb.io` if that’s preferable

**Comment by engram-design** [comment]
Any news on this, as I haven't heard back any further details?

**Comment by TurboThomsen** [comment]
sry, i am currently not available. I will see next week.

**Comment by TurboThomsen** [comment]
Tried it with the current version (2.0.37). Not a problem anymore.
