### ISSUE TITLE
Add custom css class to fields input using template hooks

### ISSUE THREAD

**Issue by FrancisMawn** [verbb/formie#155]
**What are you trying to do?**
I need to add a `form-control` class to all inputs generated by formie. There is an option to add input attributes in the field advanced options, but this approach is cumbersome as it needs to be done manually for each fields. 

**What's your proposed solution?**
Ideally, I could hook into `formie.field.input-start` and add the css class there for all inputs like so:
```
Craft::$app->view->hook('formie.field.input-start', function (array &$context) {
    $context['field']->inputAttributes = [
        'class' => ['form-control']
    ];
});
```

**Comment by engram-design** [comment]
This should now be possible in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20). Refer to the syntax below:

```
Craft::$app->view->hook('formie.field.input-start', function (array &$context) {
    $context['inputOptions']['field']->inputAttributes[] = [
        'label' => 'class', 'value' => 'form-control my-custom-class',
    ];
});
```
