### ISSUE TITLE
Category field "Root Category" fails to save selection.

### ISSUE THREAD

**Issue by mjniland1** [verbb/formie#1556]
### Describe the bug

I'm attempting to set a root category on a category formie field. My source is set, and there are four levels within my category. I set the root category as level 2 in my hierarchy with the intent to only display its immediate children. When I make the root category selection and hit "apply", the change isn't applied and my category field displays all categories with my source category. 

### Steps to reproduce

1. Create a category and make it a few levels deep.
2. Create a category field within Formie and set the root category to a sub-level 
3. hit apply
4. Reopen the category fields setting and the root category will be missing

https://github.com/verbb/formie/assets/56364768/7a5331e9-e8fe-416d-bc69-a4d29a14a7b4

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes but only CSS removed, js and HTML are the same. 

### Craft CMS version

Craft Pro 4.5.3

### Plugin version

2.0.35

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by engram-design** [comment]
Fixed in [2.0.36](https://github.com/verbb/formie/releases/tag/2.0.36)
