### ISSUE TITLE
Class "verbb\formie\models\Formie" not found when saving a custom template folder path

### ISSUE THREAD

**Issue by ryssbowh** [verbb/formie#1559]
### Describe the bug

I'm creating a custom form template and when I activate "Use Custom Template" I get this error :

![Screenshot 2023-09-06 at 08-03-36 Error](https://github.com/verbb/formie/assets/6736613/4221aae6-d8fd-417d-8959-8e78259d5b39)

Importing the class in BaseTemplate.php fixes the error.

### Steps to reproduce

1. Create a custom template
2. Tick "Use Custom Template"
3. Enter a folder
4. Save

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.5.3

### Plugin version

2.0.35

### Multi-site?

No

**Comment by mateostabio** [comment]
Same issue here. I did send the developers an email last night.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by engram-design** [comment]
Fixed in [2.0.36](https://github.com/verbb/formie/releases/tag/2.0.36)
