### ISSUE TITLE
Automatically remove old submissions

### ISSUE THREAD

**Issue by olemagnus** [verbb/formie#156]
**What are you trying to do?**
Some of our client's forms collect personal information from the sender, and they want a way to automatically remove older submissions after a certain time. They do ask for consent, but they don't want the liability that comes with storing the data.

**What's your proposed solution?**
In the form's settings under the Privacy section, it would be nice if there was a field for selecting a number and a unit of time (hour, day, week, etc.).
When the submission life span reaches this limit it gets removed.

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
