### ISSUE TITLE
PayPal integration's "Payment authorized" message is not translatable

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#1560]
### Describe the bug

A message reading _"Payment authorized. Finalise the form to complete payment."_ is shown after a PayPal payment has been authorized. 

This message is marked as translatable here: https://github.com/verbb/formie/blob/c10812a3f8b33ad08c0ad760ad36a544246bbc6c/src/web/assets/frontend/src/js/payments/paypal.js#L164

However, it is not possible to translate this string by adding a translation to `/translations/[...]/formie.php`  because the string in question is not included in the array that is passed to `Rendering::_getTranslatedStrings()`  in the `Rendering::getFrontEndJsTranslations()` method:
https://github.com/verbb/formie/blob/c10812a3f8b33ad08c0ad760ad36a544246bbc6c/src/services/Rendering.php#L326-L334

### Steps to reproduce

1. Add a translation for the "Payment authorized. Finalise the form to complete payment." string to a translation file
2. See that the translation is not used when a PayPal payment field's payment is authorized.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.3

### Plugin version

2.0.35

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by engram-design** [comment]
Fixed in [2.0.36](https://github.com/verbb/formie/releases/tag/2.0.36)
