### ISSUE TITLE
Malformed UTF-8 characters Server Error

### ISSUE THREAD

**Issue by baileydoestech** [verbb/formie#1562]
### Describe the bug

An internal server error can be caused when submitting malformed UTF-8 characters in the query string of pages that contain a Formie form. This should return a 4XX error instead of a 5XX error.

### Steps to reproduce

1. Create a Formie form and add it to a page i.e. contact-us
2. Navigate to the page with malformed UTF-8 characters i.e. ?%AA%AA
3. Internal server error is returned, the full URL would be https://example.ddev.site/contact-us?%AA%AA

![image](https://github.com/verbb/formie/assets/3185073/5998ad19-d050-42b9-8b3a-996753c8fc11)

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.3

### Plugin version

2.0.36

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.36"`.

**Comment by engram-design** [comment]
Fixed in [2.0.37](https://github.com/verbb/formie/releases/tag/2.0.37)
