### ISSUE TITLE
Conflict with Stripe for Craft Commerce [4.0]

### ISSUE THREAD

**Issue by showandtellstudio** [verbb/formie#1564]
### Describe the bug

The latest version of Stripe for Craft Commerce by Pixel & Tonic now requires a minimum version of stripe-php [10.0]" and therefore conflicts with Formie's requirement of "^7.0".

Problem 1
    - verbb/formie 2.0.36 requires stripe/stripe-php ^7.0 -> found stripe/stripe-php[v7.0.0, ..., v7.128.0] but the package is fixed to v10.21.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires verbb/formie 2.0.36 -> satisfiable by verbb/formie[2.0.36].

### Steps to reproduce

N/A

### Form settings

N/A

### Craft CMS version

4.5.4

### Plugin version

2.0.36

### Multi-site?

No

### Additional context

.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.36"`.

**Comment by engram-design** [comment]
Fixed in [2.0.37](https://github.com/verbb/formie/releases/tag/2.0.37)
