### ISSUE TITLE
"Agree" field error message isn't translated by default, while other fields' error messages are

### ISSUE THREAD

**Issue by frontedbe** [verbb/formie#1565]
### Describe the bug

"Agree" field error message isn't translated by default, while other fields' error messages are. (Happens only with AJAX submission)

[screenshot](https://www.dropbox.com/scl/fi/rma35g95lbv90vdp5gknd/screenshot.png?rlkey=3y0fp9btotvlahky0h6pfdgjr&dl=0)

### Steps to reproduce

1. Add Dutch site to Craft
2. Add form and required single text field (for example) with error message field empty
3. Add required Agree field and leave error message field empty
4. Set the submission method to AJAX
5. submit the form and see that the input field gets a dutch error message by default
6. the Agree field doen't get the dutch error message by default

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.4

### Plugin version

2.0.36

### Multi-site?

Yes

**Comment by engram-design** [comment]
Seems to be working for me! Adding:

```php
'This field is required.' => 'Custom error',
``` 

to `formie.php` in the correct translations file is working on my end.
