### ISSUE TITLE
Elements Integration with Submission Field

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/formie#1569]
### Describe the bug

I have a form that uses an Elements Integration where I map some fields from the form to an Entry, this works fine. But when I also add a Formie "Submission field" on the Entry and try to link it by passing the Submission ID, it stays empty?

I expect it to be mapped since it's a Formie specific field? Or this is not standard behaviour?

<img width="1469" alt="Screenshot 2023-09-20 at 14 49 59" src="https://github.com/verbb/formie/assets/6649706/2b0f376e-b014-49d5-857a-a249da0ad3f9">

### Steps to reproduce

1. Create a form
2. Create a section with a Formie Submission field.
3. Add an element integration
4. Map the Submission > ID with the Formie Submission field.

### Form settings

- Multi-page form: Yes 
- Submission Method: Page Reload
- Custom Form Templates: Yes 

### Craft CMS version

4.5.4

### Plugin version

2.0.36

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.36"`.

**Comment by ishetnogferre** [comment]
It works, thanks! 🙌
