### ISSUE TITLE
Form Submission search always return empty results

### ISSUE THREAD

**Issue by FrancisMawn** [verbb/formie#157]
**Description**
When using the search field on the Form Submissions page, the result is always empty.

**Steps to reproduce**
1. Browse to /admin/formie/submissions
2. Type something in the search field to filter the submissions

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.19
- Craft version: 3.5.11.1
- Multi-site: Yes

**Additional context**

**Comment by FrancisMawn** [comment]
Hi @engram-design,

Could you please confirm if you can replicate this issue?

**Comment by engram-design** [comment]
I can, looking into it

**Comment by engram-design** [comment]
Should be fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
