### ISSUE TITLE
Allow selecting multiple fields for Mailchimp tags

### ISSUE THREAD

**Issue by davidwebca** [verbb/formie#1570]
### What are you trying to do?

Hi! 

It would be nice to be able to select multiple fields for tags in the integration mapping. For example, we have two questions in our field and their answers would be great candidates to be mapped to tags, but right now it's only possible to select one field. To accommodate for that right now, I either have to merge the fields up front myself before the submission is sent to Mailchimp or try to use categories / groups for a similar solution. Tags would have been better because of their fuzzy search and display in Mailchimp itself.

### What's your proposed solution?

Make the tags integration field a multi-select so we can add multiple form fields to map on tags.

**Comment by engram-design** [comment]
This will have to be a larger refactor of integrations, and not something we're planning for I'm afraid - even long-term. There are several ways around this, ranging from using modules and events to prepare the payload for your needs, or using the Calculations field to concatenate values.
