### ISSUE TITLE
Stripe payments do not work when the payment field is inside a group

### ISSUE THREAD

**Issue by ithic** [verbb/formie#1588]
### Describe the bug

When using the Payment field with Stripe within a Group field, the payment is not processed. We can see in Stripe's logs that a new payment method is being registered, but the payment is not processed. 

Perhaps this is related to the way field values are looked up in Stripe.php? The payment information columns do not exist in the submissions table when the payment field is stored within a group. 

## To replicate failure
1. Create a Group field
2. Place a Name Field, Email field, Address Field, and Payment Field within the group
3. Configure the Payment field to use the name, email, and address fields
4. Render the form using built-in rendering within the most basic possible template, fill in all fields
5. Submit the form

The submission will show no payment details in the CP, and Stripe will not process the payment.

## To produce a successful payment:
1. Place a Name Field, Email field, Address Field, and Payment Field at the top level of the form
2. Configure the Payment field to use the name, email, and address fields
3. Render the form using built-in rendering within the most basic possible template, fill in all fields
4. Submit the form

This is successfully processed by Stripe.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.6.1

### Plugin version

2.0.37

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.37"`.

**Comment by engram-design** [comment]
Fixed in [2.0.38](https://github.com/verbb/formie/releases/tag/2.0.38)
