### ISSUE TITLE
craft.formie.renderJs empty

### ISSUE THREAD

**Issue by ax2000** [verbb/formie#1589]
### Describe the bug

When using {{ craft.formie.renderJs() }} in a template nothing seems to be rendered.

I've got a number of forms that can be loaded to a modal dynamically using sprig and when using the tag within the sprig template, nothing seems to be parsed. I've also tried in non-sprig includes and also within the `<head>` tags.

### Steps to reproduce

1.  Use the tag {{ craft.formie.renderJs() }} 
2. Nothing seems to be parsed from that tag

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.6.1

### Plugin version

2.0.37

### Multi-site?

No

**Comment by engram-design** [comment]
The default behaviour of `renderJs` is to use Craft's view `registerJs` and `registerJsFile` functions, which will add the following to the end of the page:

```html
<script src="/cpresources/7801fd0/formie.js?v=1696294819" defer=""></script>
<script type="text/javascript">...</script>
```

However, this probably isn't going to suit your lazy-loading needs, as this registration is only really going to work on a server-rendered page call. The docs actually show this tag placed in the `<head>`, but in reality, it doesn't matter where you place it, as Craft controls where it's output.

Instead, I would recommend to load the JS inline, inline with the form - `{{ craft.formie.renderJs(true) }}`. This _does_ matter where you put it.

**Comment by ax2000** [comment]
Thanks for looking into this @engram-design .

I can confirm that setting it to display online does the job as intended, very much appreciated.
