### ISSUE TITLE
[Salesforce integration] How to set redirect URL in staging env. if allowAdminChanges is off?

### ISSUE THREAD

**Issue by j-greig** [verbb/formie#159]
**What are you trying to do?**
We have _allowAdminChanges_ set to false in our staging environment, which means the Salesforce Redirect URI is set locally to our localhost.test url and therefore the "Connect" button throws an error when you attempt to connect.

Am I missing an easy way to set the redirect URI to our staging domain?

Thanks, excited to take Formie for a spin : )

**Comment by engram-design** [comment]
The redirect URI for integrations that support OAuth should be automatically generated based on the URL of the environment you're on. You can't change this value. Are you saying on the staging site, its showing localhost.test? It should be showing your staging site URL + `formie/integrations/callback`

**Comment by j-greig** [comment]
Apologies, I didn't explain myself very well the first time!

I can't see what the value is on staging because we're using project config and can only view/change settings in our local dev environment.

Locally the value is correct, eg https://clietname.test?p=actions/formie/integrations/callback, but when I try to connect I get the error below... I guess because Salesforce can't hit this url.

_error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration_

Not sure what to try next other than disabling project config... 

Thanks!

**Comment by engram-design** [comment]
Ah, now that's a great point! Yes, the settings area will be disabled thanks to `allowAdminChanges` set to false on staging and production sites. This might require some further thought and likely open up the integrations settings as read-only.

For now, you will have to guess the Redirect URI - just replace the domain name with the appropriate value. OAuth is a bit tricky connecting against multiple environments in any case. You'll need to keep updating the Salesforce settings throughout your development lifecycle.

But yep, we'll have it so you can view integrations settings which should help.

**Comment by engram-design** [comment]
Integrations can now be viewed read-only with `allowAdminChanges  = false` in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
