### ISSUE TITLE
Unable to access webhook integration data from GraphQL

### ISSUE THREAD

**Issue by jpcarpenter** [verbb/formie#1591]
### Describe the bug

After updating Formie from 1.6.2 to 1.6.33, we are no longer able to access the integration webhook information set up through the CP. We were previously able to access the webhook data via the following query:

```
form {
    ... on FormInterface {
        settings {
            integrations {
                setttings
            }
        }
    }
}
```

It seems this change in 1.6.22 completely breaks forms for anyone utilizing webhooks within Formie on a headless site.:
> Integration settings for forms now only return settings for ReCAPTCHA and hCaptcha captchas when querying via GraphQL.

Is there an alternative approach to access the webhook data via GraphQL? I've searched the docs and have come up empty.

### Steps to reproduce

1.  Set up webhook under integrations within Formie
2.  Attempt to access webhook data via GraphQL `settings{integrations { settings }}` (previously worked on 1.6.2)
3.  Only ReCaptcha information is returned

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

3.9.4

### Plugin version

1.6.33

### Multi-site?

No

**Comment by engram-design** [comment]
Right, so we addressed some security concerns where you could query the settings for integrations via GQL - things like API keys, etc - so pretty important to tighten that up.

But you're right that Webhook URLs should probably not be excluded in this case.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.33"`.

**Comment by jpcarpenter** [comment]
Thanks for that! Will this fix be applied in V2 as well? We're planning on moving this particular project to Craft 4 eventually, and will need this for that environment as well.

**Comment by engram-design** [comment]
Of course! To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.
