### ISSUE TITLE
Craft 4 upgrade -issue with Formie subfields 

### ISSUE THREAD

**Issue by kate-stretton** [verbb/formie#1594]
### Question

Hi there, 

I've upgraded a site from Craft 3.9.1 to 4.5.6.1. As part of this, I've updated Formie from 1.6.31 to 2.0.38. 

I'm experiencing issues with the name and address subfields. Previously I was using .getFrontEndSubfields to access the first name and last name fields - as follows 

```
   <div class="fui-field-rows">
        {% for row in field.getFrontEndSubfields() %}
            <div class="fui-row flex flex-col md:flex-row">
                {% for handle, autocomplete in row %}
                    {{ formieInclude('fields/name/_field') }}
                {% endfor %}
            </div>
        {% endfor %}
    </div>`
```
    
However I'm now receiving this error:        
![image](https://github.com/verbb/formie/assets/81283807/fd45b8bd-b612-4217-a0c5-ff2df498a633)

These are custom template forms. I'm see in the changelog  for Formie update 2.0.0 that fields like 'name' and 'address' now "output proper field templating for their sub fields, consistent with their outer-field counterparts". However I'm unclear about how I should now be accessing these subfields instead? 

Thanks, 
Kate

**Comment by engram-design** [comment]
Should just be a quick change:

```twig
field.getFrontEndSubfields(_context)
```

As the `getFrontEndSubfields()` function just requires the current Twig context.

**Comment by kate-stretton** [comment]
Thank you so much for your help. 

I've tried that but am now encountering this issue. Is this likely part of a different problem that doesn't relate to subfields? 

![image](https://github.com/verbb/formie/assets/81283807/07dae93b-1acc-46a2-80b9-6fb7d79126c9)

**Comment by engram-design** [comment]
The subfield handling did get a full revamp for Formie 2, so I'm not surprised there are follow-up issues. We've streamlined things to use Theme Config for adding classes and attributes, which has simplified templates significantly, as they're now defined in PHP.

In addition, subfields are now proper fields, unlike how they were in Formie 1.x. For example, the subfields of a multi-name field are now a collection of Single-Line Text fields (depending on first/middle/last name). As such, looping through the subfields you now have field instances, and not just an array of settings.

You can see in the [craft-4](https://github.com/verbb/formie/tree/craft-4/src/templates/_special/form-template/fields/name) branch that there no longer exists a `_field.html` file. Instead, we can call [`renderField()`](https://github.com/verbb/formie/blob/f98a9ca0ef454292972399007f179ccfd3061d38/src/templates/_special/form-template/fields/name/_multiple.html#L5-L8) to render the sub-field (which is a Single-Line Text).

**Comment by kate-stretton** [comment]
Thank you!
