### ISSUE TITLE
Doc update: Constant Contact

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1595]
### Describe the bug

I'm in the middle of setting up Constant Contact, and it looks like their setup process has changed since the Formie integration instructions were written. Only minor, but the screen for creating a new application now looks like this:

![image](https://github.com/verbb/formie/assets/1250017/3b382942-f511-4c12-a7c7-b9c0cd828d26)

You now have to choose key types, save it and re-open it to add the Redirect URI

### Steps to reproduce

1. Add a Constant Contact integration and follow the instructions in Formie

### Form settings

N/A

### Craft CMS version

4.5.6.1

### Plugin version

2.0.38

### Multi-site?

No

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
