### ISSUE TITLE
Email notifications failing with "Email body render returned empty. Please check your email content for invalid variables." error on 2.0.38

### ISSUE THREAD

**Issue by idawgik** [verbb/formie#1596]
### Describe the bug

So we've been having issues with this same error from #1370 on one of our sites currently. We're up to date on all updates, so running Formie 2.0.38 (just updated today from 2.0.37).

This is causing emails not to be sent to the client.

The error is:

`Notification email template parse error for “formie/_special/email-template”. Template error: “Email body render returned empty. Please check your email content for invalid variables.” /path/to/site/vendor/verbb/formie/src/services/Emails.php:276`

I did check the code changes from the previous referenced update are still in place, so something else seems to be causing this issue.

We are using the default content for the form body.

### Steps to reproduce

1. Set up form with Admin Notification set to default content
2. Submit form, receive error when submission is sent

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.6.1

### Plugin version

2.0.38

### Multi-site?

No

**Comment by engram-design** [comment]
Are you able to share the content of your email notification? And if you can, submitting a support ticket from Formie (Formie > Settings > Get Support) would be great, so we can see your form setup.

**Comment by idawgik** [comment]
I've submitted a support request through the admin including some screenshots.

**Comment by engram-design** [comment]
Sorry for the delay here, but I don’t believe we received your support request, if you can send through again, I’ll double check it’s not getting caught in spam or something in our support system.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)

**Comment by klick** [comment]
Bumping this because I get the same error on Craft 5.1.7 with Formie 3.0.0-beta.14

What was the problem and how can I fix this?

**Comment by engram-design** [comment]
Can you check your logs? This is likely an issue with the Twig sandbox we were using, which we've eased-up on with in [3.0.0-beta.14](https://github.com/verbb/formie/releases/tag/3.0.0-beta.14)

**Comment by klick** [comment]
Hey.

Sorry for the delay.
Cleared out the logs to make way for new logged errors. But there are none. A formie log is not being cerated.
The bug seems to be that the email body in the notifications which go out to the user is empty. Formie then refuses to send that email.

Formie’s error message (localised, sorry):

`Fehler beim Parsen der E-Mail-Benachrichtigungsvorlage für "formie/_special/email-template". Vorlagenfehler: "Email body render returned empty. Please check your email content for invalid variables." /var/customers/webs/temedos/www1.temedos.de/vendor/verbb/formie/src/services/Emails.php:284`

**Comment by engram-design** [comment]
So yeah, something is tripping up Formie's parsing of your email content. That error should also be included in your logs (separately), but what's the content of your email notification?

**Comment by klick** [comment]
I seem to have found the error:

`“Function "url" is not allowed in "__string_template__420f3455aa7d28931ded942c3c3e582d"`

I had a link back to the site in my email-template.

**Comment by engram-design** [comment]
Ah, so we do actually disallow a bunch of Twig functions/filters/etc in order to prevent some security vulnerabilities using a [Sandbox](https://github.com/verbb/verbb-base/blob/craft-5/src/services/Templates.php). But we can certainly allow for those URL functions which are pretty common.
