### ISSUE TITLE
Mark as Spam from Submissions Detail Page

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/formie#1597]
### What are you trying to do?

Hey Gang,

It would be really nice if we could mark a submission as Spam on the Submission Detail page. The only way this is doable now is from the main submissions screen. This is a little tough sometimes to know which entry was spam if there are a bunch of other submissions.

### What's your proposed solution?

Just give us a button to mark as spam from the Details page.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
