### ISSUE TITLE
Translation of character or word limit

### ISSUE THREAD

**Issue by maassfm** [verbb/formie#1598]
### Describe the bug

I added a translation of 
'{startTag}{num}{endTag} word left' => '{startTag}{num}{endTag} Wort übrig',  and
'{startTag}{num}{endTag} character left' => '{startTag}{num}{endTag} Zeichen übrig',
to a formie.php translation file but there is no effect at the rendered form. Other translations are working as expected, e.g.:
'{startTag}{num}{endTag} words left' => '{startTag}{num}{endTag} Wörter übrig', 

### Steps to reproduce

Enable 'Limit Field Content'
Add a custom translation file translations/de/formie.php
Add translations for '{startTag}{num}{endTag} word left' and '{startTag}{num}{endTag} character left'

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.4.16.1

### Plugin version

2.0.33

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.
