### ISSUE TITLE
Element integration for Users and Products

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#160]
**What are you trying to do?**
I'd like to be able to use Formie to create Craft users (and create products, if possible). In particular, my client wants a single form to register users and also let them subscribe to mailing lists. The mailing lists bit is already possible, of course, but there seems to be element integration only for entries, not users and products. The need for products is not pressing at the moment, but will probably come up later on.

**What's your proposed solution?**
A new element integration for users (and products, if possible).

**Additional context**
Apologies if this is already possible (I'm not sure if you once mentioned this to me in a different exchange), but I couldn't find anything in the docs, other than for entries.

**Comment by engram-design** [comment]
Yep, only entries are supported at the moment, but was just waiting for someone to actually need other elements to implement them. I can't provide an ETA, and you can spin up [your own](https://verbb.io/craft-plugins/formie/docs/developers/custom-integration#element), but it's certainly on our list to do.

**Comment by engram-design** [comment]
User integrations has been added in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20).

Products are a little more trickier, mostly because they contain nested information like multiple variants. I'm going to shelve that for the far-future for the time being.

**Comment by AndrewMac** [comment]
Just wondering if there's any chance you might have plans to revisit this issue (element connection for products) at some time? I have a client I'm trying to push to Formie, but they need to be able to have users edit product elements.

**Comment by engram-design** [comment]
Wondering if you might like to create a new ticket just for products? As I've mentioned, they're a little trickier due to multiple variants...

But I'll mention its not on the immediate roadmap, but happy to see what we can do.

**Comment by AndrewMac** [comment]
Will do, and thanks for considering it!
