### ISSUE TITLE
Summary: Option to display the name of the page of the fields 

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1604]
### What are you trying to do?

We have a long form that is split into 5 pages, the summary element does not give a clear overview from which page the information comes.
If this information were available, the user could easily know which page to go back to in order to update it.

### What's your proposed solution?

The summary Element should have the option to display the fields grouped by page name.

- Page 1
    - **Field 1.1**
    field value
- Page 2
    - **Field 2.1**
    field value
    - **Field 2.2**
    field value

### Additional context

This is the desired result from our designer: 

![image](https://github.com/verbb/formie/assets/10438940/eac01179-37b8-46ef-8fa5-87516111693a)

**Comment by engram-design** [comment]
A good idea for sure. Probably something we'll add to the default template. For now, best to supply a [template override](https://verbb.io/craft-plugins/formie/docs/theming/template-overrides) for the summary field for your needs.

**Comment by Megafry** [comment]
Thanks for the feedback, I was able to adjust the output to my liking.
