### ISSUE TITLE
friendlycaptcha integration issues

### ISSUE THREAD

**Issue by DavidKabelitz** [verbb/formie#1606]
### Describe the bug

Hi all, 
the integration of friendlycaptcha.eu causes a couple of problems:

-  the div with the class formie-friendly-captcha-placeholder needs a position relative and min height otherwise the layout is broken, their advertisment link is set to position absolute
- On all forms where friendlycaptcha is used the form fires a change even nothing was changed in the form, so clicking around causes a browser message
- On forms with two or more pages validation without a click let submit the form but no submissions are saved. It works when you click on "Verification"...
- Friendly Captcha offers a [data-lang attribute](https://docs.friendlycaptcha.com/#/widget_api?id=data-lang-attribute) to have more languages, it's missing at the integration tab

I was not sure to create just one ticket or multiple, hopefully its ok

### Craft CMS version

4.5.8

### Plugin version

2.0.38

**Comment by engram-design** [comment]
Most of those items are addressed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.

However, for the:

> On forms with two or more pages validation without a click let submit the form but no submissions are saved. It works when you click on "Verification"...

Can you expand on this a bit further? Things seem to be working for me on multi-page forms?

**Comment by DavidKabelitz** [comment]
Hey, thanks for the fast reply.

Multiply pages just works for us when someone clicks on  "friendly captcha", but it's also a feature that user don't need to click. So that validation is done while form submit. In this case it's not working for forms with multiple pages. On a single page form you can click on submit without using friendly captcha and it works like a charm.

**Comment by engram-design** [comment]
Hmm, that’s what I tested - just hitting the submit button in each page. Just to confirm - so you just have the captcha enabled on the last page? Is it Ajax or page reload?

**Comment by DavidKabelitz** [comment]
Yes, last page and Ajax on. After submitting we see the success message but no submission or notification generated. As soon we click on "friendly recap." to validate it's fine. We also have lot's of conditions to show and hide fields depending on values but that shouldn't cause any problems i guess.

**Comment by engram-design** [comment]
I'll keep testing this, but for reference, here's a very simple form on my end for you to double-check I'm replicating it correctly. https://share.cleanshot.com/tBMGdv4T

In case your conditions are a factor, it might be worth testing a simplified form on your end?

**Comment by DavidKabelitz** [comment]
Yes we can do that but will take till end of the week, if thats ok for you.

**Comment by DavidKabelitz** [comment]
Hi, testing with a simple multi page form worked out! So there is something related to conditions that show and hide fields. When will be Data Lang Attribute setting available?

**Comment by engram-design** [comment]
Are you able to send a support request for the form, so I can see your form setup? Or, export the form and send to `support@verbb.io`. It must be something specific to your form.

The changes you mentioned above and my fixes are already available in [2.0.39](https://github.com/verbb/formie/releases/tag/2.0.39)

**Comment by DavidKabelitz** [comment]
oh really, how it's working? connected to the browser language? And sure, i will share the form with you

**Comment by engram-design** [comment]
There's a Language setting for the captcha 
<img width="766" alt="image" src="https://github.com/verbb/formie/assets/1221575/dd768017-a52c-452f-b4bb-d4b89d708a58">

**Comment by DavidKabelitz** [comment]
Ah at the settings section, sorry missed to look there. Thanks a lot works perfect!
