### ISSUE TITLE
Brevo Integration Double OptIn

### ISSUE THREAD

**Issue by DavidKabelitz** [verbb/formie#1607]
### Describe the bug

Former Send In Blue now Brevo Integration does not start double optIn.

### Steps to reproduce

Every user signed up over the API integration is always opted In. Would be needed (GDPR-Compliant), like at the MailChimp Integration, to switch it on or off.  Makes no difference if it's active at Brevo or not.

### Form settings

**

### Craft CMS version

4.5.8

### Plugin version

2.0.38

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.

**Comment by DavidKabelitz** [comment]
oh wow, awesome. Thanks a lot!

**Comment by engram-design** [comment]
Added in [2.0.39](https://github.com/verbb/formie/releases/tag/2.0.39)

**Comment by DavidKabelitz** [comment]
Hi, after the update we got that error, do we need to change something on our side?

API error: “{"code":"missing_parameter","message":"includeListIds is missing"}” /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

**Comment by engram-design** [comment]
Looks like you'll also need to provide a `templateId` and `redirectionUrl` which I've added settings for. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.

**Comment by DavidKabelitz** [comment]
Hi, where do templateID and redirectionUrl come from? Where can i find it? Brevo?

**Comment by engram-design** [comment]
These are from Brevo apparently. I'm not overly familiar with Brevo yet, but according to the API docs, these are required. See https://developers.brevo.com/reference/createdoicontact

**Comment by DavidKabelitz** [comment]
ok thanks a lot, will test it.

**Comment by engram-design** [comment]
Updated in [2.0.40](https://github.com/verbb/formie/releases/tag/2.0.40)

**Comment by DavidKabelitz** [comment]
Hi, the API returns always 
`API error: “{"code":"invalid_parameter","message":"Invalid template id"}” /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113`

I tested the same values here and it worked: https://developers.brevo.com/reference/createdoicontact

**Comment by DavidKabelitz** [comment]
Hi @engram-design, any update here?
Don't know if that is the reason, but the test api links sends an integer for the template id and the formie submit sends a string.

**Comment by engram-design** [comment]
Pushed a fix for that for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.42"`.

**Comment by DavidKabelitz** [comment]
Hm, with that update i am not able to save any form:

`Unable to save form: [["Queue must be an application component."],{"general":["Queue must be an application component."]}].`

**Comment by DavidKabelitz** [comment]
also the Double OptIn test does not work. I got no error at craft but also no data is send to Brevo. Switching Double OptIn off still works. Looks like that parameter has a different format: createDoiContact.includeListIds = [2];
Sorry for this, do you want real test data?

**Comment by engram-design** [comment]
That `Queue must be an application component` error seems to be a Craft error. Are you using a custom Queue or something? Anything about your infrastructure worth mentioning?

As for the payload error, that does seem to work for me - we indeed send the listId as an array.

Can you check your logs at `/storage/logs/formie*-.log`?

**Comment by DavidKabelitz** [comment]
Hm we just switched runQueueAutomatically off and use craft-async-queue for running the jobs. That's nothing we changed shortly. Also i just tested at dev environment, don't know if that makes a difference. On production double OptIn works just the error while saving appears on every environment now. The log shows just the errors as mentioned above.

**Comment by engram-design** [comment]
Hmm, I wonder if something has changed with custom queues in recent Craft versions and maybe the `craft-async-queue`. It's not an error I've come across. If [this commit](https://github.com/ostark/craft-relax/commit/4dd1c066b8b30d2da8fc097c93d0c6716ab531d4) for another plugin is anything to go by, it's possible it's an issue with the `craft-async-queue` plugin.

**Comment by DavidKabelitz** [comment]
hm you are right, other plugins also fire Queue must be an application component error now while saving that usually start a queue job

**Comment by DavidKabelitz** [comment]
It's the relax plugin and not the async. We also tested it, when it's deactivated everything works fine again. Thanks for your help and fixes. We can close it finally :)
