### ISSUE TITLE
Updating from 2.0.38 to 2.0.39 stops conditional fields from showing

### ISSUE THREAD

**Issue by zizther** [verbb/formie#1609]
### Describe the bug

Since updating from 2.0.38 to 2.0.39 the form setup I have which contains conditional fields based on a dropdown value no longer works.
I have a section which is a divider line which shows fine, but the fields themselves don't show `data-conditionally-hidden` is not changing.

I have a dropdown field called `Do you have a profile on the site already?` (Handle `doYouHaveAProfileOnTheSiteAlready`) with a value `Yes` and `No`. I have fields underneath it which show based on the condition if the dropdown field is Yes or No.

I have tried the form with difference behaviours, but it has not worked.

The theme config contains classes for certain elements and fields, and set `resetClasses` to `true`.

The JS and CSS are being added to the template via Formie.
The project is a non-SPA.

The conditional on the section (divider) which shows correctly is (Shows on Yes or No)
```
data-field-conditions="{&quot;showRule&quot;:&quot;show&quot;,&quot;conditionRule&quot;:&quot;any&quot;,&quot;conditions&quot;:[{&quot;field&quot;:&quot;fields[doYouHaveAProfileOnTheSiteAlready]&quot;,&quot;condition&quot;:&quot;=&quot;,&quot;value&quot;:&quot;Yes&quot;},{&quot;field&quot;:&quot;fields[doYouHaveAProfileOnTheSiteAlready]&quot;,&quot;condition&quot;:&quot;=&quot;,&quot;value&quot;:&quot;No&quot;}],&quot;isNested&quot;:false}"
```

The conditional on the field which should show if the value of the dropdown field is `Yes`
```
data-field-conditions="{&quot;showRule&quot;:&quot;show&quot;,&quot;conditionRule&quot;:&quot;all&quot;,&quot;conditions&quot;:[{&quot;field&quot;:&quot;fields[doYouHaveAProfileOnTheSiteAlready]&quot;,&quot;condition&quot;:&quot;=&quot;,&quot;value&quot;:&quot;Yes&quot;}],&quot;isNested&quot;:false}"
```

Reverting back to 2.0.38 allow the conditionals to work again.

### Steps to reproduce

1. In Craft 4 using Formie 2.0.38 create a form with multiple pages
2. On the first page have a dropdown field with the options `Yes` and `No`
3. Create fields underneath with conditionals based on whether the dropdown field value is `Yes` or `No`
4. Set the behaviour submission method to be `Page Reload`
5. Test make sure it works
6. Update to Formie 2.0.39
7. Test for form on the frontend

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload (Also tested with AJAX)
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.9

### Plugin version

2.0.39

### Multi-site?

No

**Comment by zizther** [comment]
I've tested the frontend JS (`src/web/assets/frontend/dist/js/formie.js`) from 2.0.38 within 2.0.39 and it resolves the issue I am having.

**Comment by engram-design** [comment]
Are there any JS errors? I can't replicate this with some of my (simple) sample forms.

Can you send through a support request via Formie > Settings > Get Support for your form, so I can replicate your form setup exactly?

**Comment by zizther** [comment]
Thanks @engram-design I've sent this through

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by zizther** [comment]
Thanks for the quick fix. I can confirm this has been resolved for the next release
