### ISSUE TITLE
Allow override form part-templates like _page-tabs.html

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#161]
I am trying to keep original Formie's template untouched as possible - for feature updates. Which is well thought and easy with fields. But I'am struggleing with override the _page-tabs.html template. My intention is to add numbering and some dividers to the tabs .

That template needs to be overriden including form.html and all form's part-templates (_errors, _instructions etc.)

Would be great to copy and adjust only those templates we need - in my case _page-tabs.html.

**Comment by engram-design** [comment]
We're looking to improve this, related to https://github.com/verbb/formie/issues/150 and warrants some further investigation into options

**Comment by lexislav** [comment]
Great. Have missed #150 before posting :-/

**Comment by engram-design** [comment]
Added in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20).

There's nothing you need to do, apart from ensure any custom templates reflect the new changes to use `{{ formieInclude('_includes/page-tabs') }}` - refer to https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/form.html

So this function will either load the default Formie template, or if your form uses custom templates, it'll try to find an override template matching the partial. 

In your situation, you can just create a `_includes/page-tabs.html` file, without the need to create a `form.html` file.

All partials used in templates are included in a `_includes` folder now as well.
