### ISSUE TITLE
"Toggle Checkbox" doesn't toggle any checkboxes on front-end

### ISSUE THREAD

**Issue by Antimated** [verbb/formie#1612]
### Describe the bug

Hey

Recently migrated my website from Craft 3.9.5 to the latest 4.x version. I noticed after updating all plugins and updating my forms that the option to check all checkboxes is broken.

Admin panel:
![Screenshot 2023-10-26 at 15 44 40](https://github.com/verbb/formie/assets/2869409/5037c907-1083-49a1-8ee7-7c71347c1c08)

Front-end after checking the "toggle checkbox (Give me the full monty!)" and trying to submit my form:
![Screenshot 2023-10-26 at 15 45 07](https://github.com/verbb/formie/assets/2869409/6494b30b-efd5-4703-962b-6903e3681870)

Expected result after pressing the "toggle checkbox (Give me the full monty!)":
![Screenshot 2023-10-26 at 15 49 29](https://github.com/verbb/formie/assets/2869409/c260ae31-7a32-469a-a4ad-8fa6d19dd9af)

### Steps to reproduce

1. Add checkboxes to your form
2. Enable the "Toggle checkbox"
3. Try and toggle all checkboxes

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes but only slightly modified the submit button, nothing changed to the checkbox templates.

### Craft CMS version

Craft Pro 4.5.9

### Plugin version

2.0.39

### Multi-site?

No

**Comment by engram-design** [comment]
Seems to be working okay for me:
![CleanShot 2023-10-28 at 09 10 45@2x](https://github.com/verbb/formie/assets/1221575/2a8a8c1a-222d-449c-84ed-40588ff78bbd)

Are there any JS errors on your front-end? You're also not excluding Formie's JS?

**Comment by Antimated** [comment]
No, no errors to be seen. I have no idea what is happening tbh... Also on another website we have issues with conditional fields not showing up.

**Comment by engram-design** [comment]
Can you submit a support request via Formie > Settings > Get Support so I can replicate your form, just in case there's something unique in that?

**Comment by Antimated** [comment]
Just sent in a support request. The body of the e-mail is the title of this issue and the link to this issue.

**Comment by engram-design** [comment]
Hmm, looks like for whatever reason that hasn’t come through to our support service.

Are you able to export your form via Formie > Settings > Import/Export and manually send through to `support@verbb.io`?

**Comment by Antimated** [comment]
> Hmm, looks like for whatever reason that hasn’t come through to our support service.
> 
> Are you able to export your form via Formie > Settings > Import/Export and manually send through to `support@verbb.io`?

Sent!

**Comment by engram-design** [comment]
Thanks for that, at least that's arrived. I'm afraid that's still working on my end https://share.cleanshot.com/czvlpb9r

Is there any custom JS or anything on your end that you could rule out interfering with things? Any custom templates, or even custom CSS?

**Comment by Antimated** [comment]
@engram-design For some reason this issue is fixed by my other issue! https://github.com/verbb/formie/issues/1615
I updated to the latest formie version [2.0.40](https://github.com/verbb/formie/releases/tag/2.0.40) and now the toggle checkboxes work again!

**Comment by engram-design** [comment]
Good to know!
