### ISSUE TITLE
Condition rules are not applied (or not correctly)

### ISSUE THREAD

**Issue by Antimated** [verbb/formie#1615]
### Describe the bug

I have a form that has a few conditional fields. Some address fields and a title are being displayed when a checkbox is checked.

For some reason this broke and no matter how hard I try to show these fields it doesn't work like it should. Now I have a state where a title field is conditionally shown, and other fields are not.

Sometimes a field conditional setting works but after saving my form it just breaks again...
I disabled all my javascript (excluding an import of my css) to ensure no internal javascript (like vue) is breaking the front-end.

I created this form:

![Screenshot 2023-10-30 at 15 40 29](https://github.com/verbb/formie/assets/2869409/b4d59f71-2bd7-45fc-a6fe-03f27761ae5a)

The conditional fields should be shown if the "Ander relevant adres" checkmark is checked.

![Screenshot 2023-10-30 at 15 41 15](https://github.com/verbb/formie/assets/2869409/0731e0d5-86c2-4442-b6d2-ec450142f3ab)

Screenshot of front-end
![Screenshot 2023-10-30 at 15 41 38](https://github.com/verbb/formie/assets/2869409/fb6ff543-0826-4ec7-a3e9-093f31d82a3d)

I also notice a `checked="true"` property being added when checking the checkbox on the front-end (not sure if this is correct behaviour"?

### Steps to reproduce

1. Create a form with conditional fields and a checkbox which toggles these fields
2. Toggle the checkbox on the front-end.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes but disabling my custom `agree` and `checkboxes` field templates does not resolve the issue.

### Craft CMS version

Craft Pro 4.5.9

### Plugin version

2.0.39

### Multi-site?

No

**Comment by engram-design** [comment]
Can you submit a support request via Formie > Settings > Get Support so I can replicate your form, just in case there's something unique in that?

**Comment by Antimated** [comment]
Just sent in a support request. The body of the e-mail is the title of this issue and the link to this issue.

EDIT: @engram-design did you receive this support request or not? I saw the one on my other ticket didn't come through?

**Comment by sander-lameco** [comment]
I also noticed updating to the latest version `2.0.39` (coming from `2.0.33`) conditions are no longer working.

I had a really simple test setup with radio buttons A & B and have Text fields for each as a condition. After upgrading to the latest version the conditions are broken.

Sometimes the `data-conditionally-hidden="true"` attribute is set to both conditional fields and sometimes on none of them.

**Comment by sander-lameco** [comment]
@engram-design does it maybe have to do with:
> Added initJs to render options for forms, to prevent auto-initializing of Formie’s JS.

**Comment by dennis-vdw** [comment]
Any news @Antimated ? I also noticed updating to the latest version 2.0.39 (upgrading from 2.0.38) the conditions are no longer working!

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by engram-design** [comment]
Fixed in [2.0.40](https://github.com/verbb/formie/releases/tag/2.0.40)
