### ISSUE TITLE
Calculations field stopped working after 2.0.39 update

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1616]
### Describe the bug

I have a form with a hidden Calculations field that concatenates three fields like so:

<img width="978" alt="Screenshot 2023-10-31 at 10 58 15" src="https://github.com/verbb/formie/assets/5922913/7b6ebc54-f742-4542-a7cb-de956933bad9">

This was working great, but after updating to v2.0.39, the value on submission is now `0/0/0`.

I built a new test form to try other operators (I tested arithmetic, comparison, and logical) and the result is similar: the Calculations field value is `0`.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.9

### Plugin version

2.0.39

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by Tim-Wils** [comment]
@engram-design Just confirmed with @JeroenOnstuimig  this fix also works for front-end field conditions that didn't work anymore.

**Comment by engram-design** [comment]
Fixed in [2.0.40](https://github.com/verbb/formie/releases/tag/2.0.40)
