### ISSUE TITLE
Add "Visibility" Option for Agree-Fields

### ISSUE THREAD

**Issue by jarheadcore** [verbb/formie#1617]
### What are you trying to do?

Want to use the Agree fieldtype for a custom opt-in feature, but hidden in the frontend.
It would be nice if this fieldtype gets the "Visibility" option in the appearance tab as well (like some other fields do)

### What's your proposed solution?

Add "Visibility" dropdown + corresponding logic to the agree fieldtype

### Additional context

Craft CMS 4.5.9
Formie 2.0.39

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
