### ISSUE TITLE
Add CSS classes to specific button not only buttons container

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#162]
Right now it's possible to add CSS classes to submitn button container only.
With multipage forms I have found this sort of limiting.
**The ability to add CSS classes to specific button only would be more then wellcome.**

Related are classes on multipage buttons.
What I need is the _next page_ button be visually different from _Finaly submit the form_ button on last page. But all _next page_ buttons have the `fui-submit` class on them. Introduce of `fui-next ` class instead of `fui-submit` on first page would be very usefull as well. `fui-submit` class would stay only for the form submit button, not the next page buttons.

**Comment by engram-design** [comment]
[1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20) adds submit attributes just like you have with fields.

Regarding your second part, `fui-submit` will stay on all form submit buttons, which I believe is important. However, I've added a `fui-next` class on any forward-progressing button that it's the final one.

**Comment by lexislav** [comment]
Thanks for the solutions and all  work on update!
