### ISSUE TITLE
Field type "checkboxes" not resetting to default state after form submission

### ISSUE THREAD

**Issue by carinameissl** [verbb/formie#1620]
### Describe the bug

Hey,

I have implemented the field type "checkboxes" in my form with various checkbox options. When submitting, the checkboxes which have been selected do not go back to default (unchecked) state (side note - none of the options have been selected as default value). For field type "Agree" this works just fine and resets the field to not selected after submitting. Is there a way to fix this for the checkbox field type too?

Thanks!

### Steps to reproduce

1. add checkboxes to form
2. select checkbox
3. submit form
4. checkboxes are still selected

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Custom Form Templates: No

### Craft CMS version

4.5.9

### Plugin version

2.0.40

### Multi-site?

no

**Comment by engram-design** [comment]
Fixed in [2.0.41](https://github.com/verbb/formie/releases/tag/2.0.41)

**Comment by carinameissl** [comment]
Thanks for the quick fix!
