### ISSUE TITLE
Custom PDF template 'Filename Format' not being saved/updated

### ISSUE THREAD

**Issue by srosenbrand** [verbb/formie#1621]
### Describe the bug

When creating or editing a PDF template the 'Filename Format' field doesn't get saved or updated. Submission-{submission.id} stays the filename format.

### Steps to reproduce

1. Create or edit a PDF template
2. Customize the Filename Format (e.g. 'Sticker-{submission.form.title}-{submission.id} )
3. Save the template
4. Re-open the template settings
5. Filename Format is still the default 'Submission-{submission.id}'

<img width="1028" alt="SCR-20231104-padf" src="https://github.com/verbb/formie/assets/5593262/7e12940e-0780-4358-a063-517e2441319f">

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.5.9

### Plugin version

2.0.40

### Multi-site?

Yes

### Additional context

Only tested on development env. Deleted all existing submissions and removed all relations to the PDF template. All without success.

**Comment by engram-design** [comment]
Fixed in [2.0.41](https://github.com/verbb/formie/releases/tag/2.0.41)
