### ISSUE TITLE
Use public URL of assets in notifications for File Upload fields

### ISSUE THREAD

**Issue by bfjare** [verbb/formie#1623]
### Describe the bug

I have a client whose forms is for them accept files that sometimes are large so they cant be attached to the email.

The field setting in the notification is to the control panel "/admin/assets/edit/10004-Flight-Fund-2023-10" which isn't useful to the client since it doesn't have the full site url and I cant seem to be able to customize it or chose the public url.

Any chance we can get a little flexibility with this?

Thanks,

### Steps to reproduce

1. Have a form that accepts large attachments and sends a url by email

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: No

### Craft CMS version

4.4.17

### Plugin version

2.0.34.1

### Multi-site?

No

**Comment by engram-design** [comment]
It's on our todo list to handle this better for a few different fields (see https://github.com/verbb/formie/issues/753) but there's not really a solution yet. You would need to override this with [Template Overrides](https://verbb.io/craft-plugins/formie/docs/theming/template-overrides) for [Email Templates](https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates).

It'd be a matter of replacing this line: https://github.com/verbb/formie/blob/ad50200dbab9e872b77d042acc61b1098b8582df/src/templates/_special/email-template/fields/file-upload.html#L12

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)

**Comment by frontedbe** [comment]
> Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)

"Added the ability to set the control panel or public URL for element fields (Categories, Entries, File Upload, Products, Tags, Users, Variants)."

Where can we find this setting?

**Comment by engram-design** [comment]
In the **Settings** tab for the field. 
<img width="551" alt="image" src="https://github.com/user-attachments/assets/d740cd6f-ba66-4c82-bb04-40b41fa398fe">

**Comment by frontedbe** [comment]
Crap, this site is still on Craft 4 with Formie 2.X, so the setting isn't present there?

**Comment by engram-design** [comment]
That's right, sorry. This feature was only added in Formie 3 for Craft 5.

**Comment by frontedbe** [comment]
Do you have any recommendations for handling how this appears in the notification when displaying 'All Form Fields'?

**Comment by engram-design** [comment]
Only from my comment above https://github.com/verbb/formie/issues/1623#issuecomment-1801694960 which involved a custom email template for the File Upload field. That should do the trick.
