### ISSUE TITLE
Honeypot captcha preventing valid form submissions

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#1625]
### Describe the bug

I have a cached form with the honeypot captcha enabled. All form submissions are being marked as spam, and the submission spam detail states 'Failed Captcha “Honeypot”: “Honeypot input has value: undefined.”'

When I disable caching and remove the cache busting JS code, the form submission is successful.

### Steps to reproduce

1. Create a cached Formie form.
2. Use cache busting JavaScript.
3. Enable the Honeypot captcha.
4. Submit the form.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.5.10

### Plugin version

2.0.41

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.41"`.

**Comment by engram-design** [comment]
Fixed in [2.0.42](https://github.com/verbb/formie/releases/tag/2.0.42)
