### ISSUE TITLE
Update Klaviyo API; version currently used (v2) is deprecated and retiring 2024-06-30

### ISSUE THREAD

**Issue by tremby** [verbb/formie#1626]
### What are you trying to do?

Use the Klaviyo integrations, with long-term stability.

### What's your proposed solution?

Update to the current version of the Klaviyo API.

### Additional context

The current Klaviyo integrations use the "v2" API, which is deprecated and is scheduled to retire on 2024-06-30. (https://developers.klaviyo.com/en/v1-2/reference/api-overview)

**Comment by engram-design** [comment]
Certainly on our todo list. Will keep you updated!

**Comment by yuvi100** [comment]
@engram-design any updates on this?

**Comment by engram-design** [comment]
Nothing yet (scheduled for [2.2.0](https://github.com/verbb/formie/milestone/13), but will be done by the retirement date.

**Comment by tremby** [comment]
At the time of writing this is one of 99 open issues on the 2.2.0 milestone. Given that there's a fast-approaching time limit on this one, I wonder if it could be prioritized?

**Comment by engram-design** [comment]
Yeah, this has crept up on us a little, so we'll schedule that ASAP for 2.1.x

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.18"`.

Existing Klaviyo CRM and Email Marketing integrations will not be touched, and will be swapped to a "legacy" integration. This ensures no immediate disruption to integrations.

But it's advised that you switch these integrations over from their legacy counterparts to the latest. This can be done by editing the integration settings. Once updated, you'll need to re-map any fields in your forms, as they have changed slightly, and they are technically for a new integration.

**Comment by tremby** [comment]
Thank you. We'll try to get updated as soon as possible.

**Comment by engram-design** [comment]
Updated in [2.1.19](https://github.com/verbb/formie/releases/tag/2.1.19)

**Comment by tremby** [comment]
I've gone to settings and changed the integration from "Klaviyo (legacy)" to "Klaviyo".

You said I need to also update some mappings. I went to a form with that integration enabled, but everything already looks OK. Do I need to do anything? Do I need to force a save? You said the mappings have changed slightly -- in what way; what should I look out for?

Thanks.

**Comment by tremby** [comment]
On the mapping settings, if I click "refresh" for the "lists" dropdown I'm now getting an "authentication failed" error now. It's configured exactly as it was before. I'll ask the client to see if they have updated credentials, but I'm mentioning it here just in case that might not be the issue.

**Comment by tremby** [comment]
Oops no I think the creds I have in my dev environment are just out of date.

**Comment by engram-design** [comment]
So the API connection details are exactly the same, so no need to change API details.

You'll need to refresh the integration, as the mapping would be cached. And it's only the underlying IDs which were prefixed by a `$` character, so from a user point of view, it should show the same options to map to.

**Comment by tremby** [comment]
> So the API connection details are exactly the same, so no need to change API details.

On switching from legacy to current, the API key boxes are cleared so I did have to enter them again.

> You'll need to refresh the integration

Sorry -- what does this mean exactly? Do you simply mean pressing this button? 
![image](https://github.com/verbb/formie/assets/199635/f5506ec7-f5ea-46b3-aa9f-c609a10acc0f)

Assuming yes, once I've done that, if I look at a form with this integration enabled and the mappings look right, am I done? Or do I need to click save on those?

**Comment by engram-design** [comment]
Sorry, I meant you'll need to refresh the _form_ integration settings. This is by either refreshing the list (for an Email Marketing integration - https://share.cleanshot.com/NR4HYtG9) or hitting the Refresh Integration button (for a CRM integration - https://share.cleanshot.com/Ct4Bq9D1), as they're the mappings which are cached. Because you're just switching the type of integration that it is, and there are existing field mapping data in there, it might show out-of-date mappings.

Just hit those buttons just to be safe, and double check things are still mapped, but if everything looks good otherwise, you're good to go.

**Comment by damonadigital** [comment]
Is there an equivalent update available/coming for Craft 3?

**Comment by engram-design** [comment]
Whilst we have [dropped active support](https://verbb.io/blog/craft-3-plugins) for Formie 1.x (no new features, just security updates), I'll see what I can do about back-tracking this.

**Comment by damonadigital** [comment]
Thanks @engram-design , we would be hugely grateful.
