### ISSUE TITLE
reCAPTCHA v3 issue in 2.0.42

### ISSUE THREAD

**Issue by frontedbe** [verbb/formie#1630]
### Describe the bug

When updating to 2.0.42 the reCAPTCHA v3 doesn't validate on submission, getting a 400 error. When disabling reCAPTCHA it works fine too.
When rolling back to 2.0.41 it works too.

### Steps to reproduce

1. Create form
2. Enable reCAPTCHA v3
3. Add reCAPTCHA keys
4. Enable it for the form
5. Fill in all required fields
6. Form can't be validated due to 400 error

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.10

### Plugin version

2.0.42

### Multi-site?

No

### Additional context

Let me know if it's working on your end or you need any more info!

**Comment by darylknight** [comment]
I can't replicate this - latest version with recaptcha work fine on our new landing page. A 400 error is nearly always to do with caching - I'd check that first.

**Comment by engram-design** [comment]
You shouldn't be getting 400 errors just from enabling reCAPTCHA. That's usually a CSRF issue.

Can you let me know if your site is cached, either template or static cached?

Can you also look in your `/storage/logs/formie.*.log` files for anything useful, or send them through to `support@verbb.io`? If there is a live/staging URL for your site, that would be handy to provide so I can verify what's going on too.

**Comment by frontedbe** [comment]
Ahh yes, stupid me, the form was being wrapped by {% cache %} tags, thx!
