### ISSUE TITLE
Mailchimp Integration retrieves only the last Interest Category

### ISSUE THREAD

**Issue by bavocorteville** [verbb/formie#1635]
### Describe the bug

In the Mailchimp integration, the $options variable is overwritten with each iteration of the interest categories loop, causing only the last interest category to be stored and all previous categories to be discarded.

https://github.com/verbb/formie/blob/craft-4/src/integrations/emailmarketing/Mailchimp.php#L117-L120

In my case, It's actually the first category that I need.

### Steps to reproduce

1. Set up a form with Mailchimp integration enabled.
2. Add multiple interest categories to the Mailchimp list.
3. Submit the form and observe the interest categories data sent to Mailchimp.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: Yes

### Craft CMS version

4.4.12

### Plugin version

2.0.29

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yeah, stupid mistake on my part here. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.42"`.

**Comment by bavocorteville** [comment]
Great, the fix solves the problem. Thanks!

**Comment by engram-design** [comment]
Fixed in [2.0.43](https://github.com/verbb/formie/releases/tag/2.0.43)
