### ISSUE TITLE
Add the ability to use the Enter key to submit the "new field" modal instead of clicking

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1637]
### What are you trying to do?

When adding a new field, you have to click the red Apply button to save the field. 

![image](https://github.com/verbb/formie/assets/1250017/e049332d-bd00-41c2-92f9-cb8caa290ed9)

### What's your proposed solution?

As with other areas in the control panel, it would be great to be able to hit the enter key to submit this instead of having to click it.

**Comment by engram-design** [comment]
On the list for Formie 3 with some Vue refactors we have planned. Agreed this is ideal for accessibility too.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
