### ISSUE TITLE
Permissions are not honnored

### ISSUE THREAD

**Issue by FrancisMawn** [verbb/formie#164]
**Description**
As an admin, I can manage and use Formie just fine. If I add all of the required permissions to a user (or a user group), the Formie tab does not show up in the control panel for them. 

![image](https://user-images.githubusercontent.com/45174482/95494678-4396b400-096c-11eb-8513-583558251eb8.png)

**Steps to reproduce**
1. Add all of the permissions under Formie to a user or a user group
2. Login as user
3. Browse to /admin/formie/forms
4. 403 Forbidden response returned

### Form settings

**Additional info**
- Plugin version: 1.2.19
- Craft version: 3.5.11.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Can you ensure the user has access to Formie, under General? 
![Screen Shot 2020-10-09 at 9 59 49 am](https://user-images.githubusercontent.com/1221575/95521815-359d6d80-0a16-11eb-8f78-c356a60b3281.png)

**Comment by FrancisMawn** [comment]
My bad, that was the issue. I was missing the general permission. This issue can be closed. 

Thank you!
