### ISSUE TITLE
Freeform Migration: [custom-handle] isn’t a valid handle

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/formie#1640]
### Describe the bug

While migrating forms from Freeform to Formie there are a couple of forms that are not saved.
Is it possible to update the handle while throwing this error because now we lose a lot of forms and we cannot update 50 forms manually here. Or can you make this handle also allowed?

### Steps to reproduce

1. Create a form in Freeform with a custom handle: contactForm_en-BE”
2. Install Formie and migrate the data from Freeform to Formie

```
Form: Preparing to migrate form “contactForm-en-BE”.
    > Handle “name” is a reserved word, will use “field_name” instead.
    > Failed to migrate field “grecaptcha_Qmr7o9QwX” on form “contactForm-en-BE”. Unsupported field.
    > Failed to save form “contactForm_en-BE”.
    > handle: “contactForm-en-BE” isn’t a valid handle.
```

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

### Multi-site?

Yes

**Comment by engram-design** [comment]
These aren't valid handles for Formie, is there any option to change the handle of the Freeform form _before_ migrating to Formie? The recaptcha field failing to migrate is fine - there's no equivalent in Formie and it'll import the rest of the fields and form.

We can certainly generate a random handle if it fails, but we felt like we'd rather let people know about the issue than trying to find the form after it was created and needing to update their templates to a random handle.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
