### ISSUE TITLE
How to populate HTML field?

### ISSUE THREAD

**Issue by MangoMarcus** [verbb/formie#1643]
### Question

Is it possible to pre-populate a HTML field's value? It doesn't seem to work using populateFormValues

```twig
{% do craft.formie.populateFormValues(form, {
    myHtmlField: 'some html',
}) %}
```
The [documentation](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) doesn't mention the HTML field

Thanks!

**Comment by engram-design** [comment]
The HTML field is a cosmetic one, and doesn't have a "value", technically. In this case, you'll want to modify the [field settings](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields#override-field-settings).

```twig
{% do form.setFieldSettings('htmlField', {
    htmlContent: 'Some custom HTML',
}) %}
```

**Comment by MangoMarcus** [comment]
@engram-design That did it, thanks for the speedy response!
