### ISSUE TITLE
Page Tab classes

### ISSUE THREAD

**Issue by samuelbirch** [verbb/formie#1644]
### Describe the bug

There is an active class applied to the page tabs, would it be possible to have a class applied to previous tabs - ones that have already been active?

We are using the tabs for a stepped form (1, 2, 3, etc) and want to hight the tabs that have already been completed.

We are using the ajax form.

### Steps to reproduce

1. use a paged ajax form
2. view classes on the tabs

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.5.11

### Plugin version

2.0.42

### Multi-site?

Yes

**Comment by engram-design** [comment]
I think we'd need to name it something else, to distinguish between the current page and completed pages. I wouldn't personally consider a previously completed page as "active". I think a `fui-tab-completed` would be appropriate.

**Comment by AlexShearcroft** [comment]
Sounds like a great suggestion, we too would benefit from this addition.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
