### ISSUE TITLE
Form can't be saved with Heading text having more than 255 characters

### ISSUE THREAD

**Issue by nestordedios** [verbb/formie#1645]
### Describe the bug

When I add a Heading text (to the Heading field) larger than 255 characters the form will not save after I click on the save button and I will get an error that the field has exceeded 255 characters.

![image](https://github.com/verbb/formie/assets/6607455/c4e12a56-d0d0-429d-b002-8427ef029d89)

I would expect that when I enter a large text the form will be saved with no errors.

### Steps to reproduce

1. Add a Heading field to a form
2. Add the text following text with 256 characters (Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis,.)
3. Save the form

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

### Multi-site?

No

**Comment by engram-design** [comment]
For now, this is largely unavoidable because the heading text is used as the name/label of the field. There's a limit to that column in the `fields` database table.

We would need to shift this to its own setting (in the `settings` column) and auto-generate a name/label for the field.

**Comment by nestordedios** [comment]
Ah ok, that explains it. Do you know when this addition will be implemented?

**Comment by engram-design** [comment]
No plans to do this in the short-term, sorry. I might recommend using a HTML field with manual HTML for headings, if you need a longer-than 255 character heading. At least for the moment, until we can shift that setting out.

**Comment by nestordedios** [comment]
Yes, I understand it does not seem to be a quick fix.
Thank you for the feedback and for the recommendation. I'll make use of the HTML field instead 👍

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
