### ISSUE TITLE
Multiple instances of PayPal buttons displaying

### ISSUE THREAD

**Issue by strandofgenius** [verbb/formie#1646]
### Describe the bug

When using the dynamic payment field option for PayPal it shows multiple instances of the payment buttons when I select an option to show the buttons, selecting default, and back to an option to show the buttons.

<img width="771" alt="Screen Shot 2023-11-30 at 3 58 10 PM" src="https://github.com/verbb/formie/assets/11370639/b456c418-5ea1-4a07-9c10-d354342ac003">

### Steps to reproduce

1. Add a dropidown field for dynamic payment value
2. Add a PayPal payment field
3. Set conditional to only display payment field by a value other than the default "select an option"
4. On the front end select a drop down option to show the payment buttons
5. Select the default option to hide buttons
6. Select an option to show buttons again

### Form settings

Default form setup

### Craft CMS version

Craft 4.5.11

### Plugin version

2.0.43

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.43"`.

**Comment by engram-design** [comment]
Fixed in [2.0.44](https://github.com/verbb/formie/releases/tag/2.0.44)
