### ISSUE TITLE
Selected checkbox values adding up to more than 255 characters throws a validation error

### ISSUE THREAD

**Issue by ellukesmith** [verbb/formie#1648]
### Describe the bug

When using checkboxes, if you have a lot of options, and a user selects all or most of those options, you can encounter a possible validation error stating that the field should contain no more than 255 characters.

Ideally, a CMS admin should be able to add multiple options without worrying about the lengths of all the values - but if this is not possible, it would be great if the admin flagged the character length issue when the user is adding the option values.

### Steps to reproduce

1. Create a checkbox field in Formie
2. Add enough options that the total character count of their values exceeds 255 characters
3. Test the form, selecting all the available options before submitting

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

### Multi-site?

Yes

**Comment by engram-design** [comment]
Good point, there are limits to just about every field's content - at least until Craft 5 where the field limits will cease to be an issue.

For now, we have a plugin setting named `enableLargeFieldStorage` which you can set to `true` in your [configuration](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) that will change several fields to use `text` as their content column. Set that and re-save the form to opt-in to the larger column setting.

**Comment by ellukesmith** [comment]
Thanks @engram-design - that solution should do the job fine for our client.
