### ISSUE TITLE
Custom error messages on fields prevents other field errors from rendering

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1651]
### Describe the bug

When setting a field as required, you are given the option to set a custom error message. If you add one, this message will show for _any_ field error — even for more specific validation errors such as min value, max value, invalid email address, etc.

I suppose that behavior is expected given the first sentence of the help text:

> When validating the form, show this message **if an error occurs**.

However, I think this is confusing and not desired. I would expect this custom message to replace only the default message and not the more specific validation errors.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

**Comment by engram-design** [comment]
Yep, I agree that there needs to be a better way to handle this. Unfortunately, I haven't come up with anything I'm happy with for error message definitions. I'd rather not have a table of texts for clients to fill out for every [possible error](https://github.com/verbb/formie/blob/c70ee88b528ee1708f6a63318c8c5dea6f05d5dc/src/web/assets/frontend/src/js/formie-form-theme.js#L74-L104) for a failed validation. That just seems a bit unwieldy for clients to manage.

But that maybe a separate issue/feature request - to be able to manage all error messages in the field settings?

For now, we'll just look at overriding the `required` validation message text.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)

**Comment by chrismlusk** [comment]
@engram-design I've updated to 2.1.0, and this still seems to be an issue as far as I can tell.

To recreate, I have a Phone Number field with a custom error message. When I enter the value "abc", I expect to see "Invalid number" on blur. However, I still see my custom error message.

**Comment by engram-design** [comment]
Sorry about that, fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.0"`.
