### ISSUE TITLE
Uploaded files from within form groups won't be deleted (data retention)

### ISSUE THREAD

**Issue by mandrasch** [verbb/formie#1656]
### Describe the bug

Hi,

we have several upload fields in form group fields.

I have set these settings locally to verify that garbage collection is working (in DDEV):

<img width="478" alt="image" src="https://github.com/verbb/formie/assets/777278/11019aff-1e0b-4815-8094-7b35f25d8c6f">

When I run `craft gc --interactive=0` after 3 minutes, the submission is successfully deleted from Formie > Submissions. But the files are still in my storage/form-uploads folder. The files are still in the local file system as well as in the database as asset in that volume.

### Steps to reproduce

1. Create form with form groups and upload fields within them
2. Save submission
3. Run garbage collection --> check if uploaded fields were successfully deleted

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.11.1

### Plugin version

2.0.42

### Multi-site?

Yes

### Additional context

Thanks very much in advance for support!

Docs: 
- https://craftcms.com/docs/4.x/gc.html 
- https://verbb.io/craft-plugins/formie/docs/developers/console-commands#garbage-collection

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.43"`.

**Comment by engram-design** [comment]
Fixed in [2.0.44](https://github.com/verbb/formie/releases/tag/2.0.44)

**Comment by mandrasch** [comment]
Nice, thanks very much for the quick fix! 👍 👍
