### ISSUE TITLE
Error when creating form from stencil with product field, breaking the whole control panel

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/formie#1657]
### Describe the bug

Typed static property verbb\formie\Formie::$plugin must not be accessed before initialization

 in /var/www/html/vendor/verbb/formie/src/fields/formfields/Products.php at line 100 

### Steps to reproduce

1. Create a stencil with a product field
2. Create a form from that stencil

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

### Multi-site?

Yes

### Additional context

commerce 4.3.2
PHP 8.2.13

**Comment by engram-design** [comment]
Can't seem to replicate that, sorry. Can you shoot through the full stack trace to `support@verbb.io` so I can take a look? Something is seemingly triggering a check before Craft/Formie is initialised.

I've also pushed a potential fix for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.43"`.

**Comment by WHITE-developer** [comment]
The fix in 2.0.44 does the trick, thanks!

**Comment by engram-design** [comment]
Just a quick note to update to [2.0.44.1](https://github.com/verbb/formie/releases/tag/2.0.44.1) due to a bug when creating new forms, in case you hit that.
