### ISSUE TITLE
Position the fui-alert succes/error to the top|bottom of the form

### ISSUE THREAD

**Issue by kevinmu17** [verbb/formie#166]
**What are you trying to do?**
I want to be able to select a position (top|bottom) of the alerts when submitting a form.

**What's your proposed solution?**
![Screen Shot 2020-10-09 at 12 14 48](https://user-images.githubusercontent.com/8747373/95571635-0e03d080-0a29-11eb-83b6-3f0dc2aefe6a.png)
Adding this option to the "Behaviour" tab (or Appearance tab :))

**Additional context**
This feature will be handy when having big forms, on mobile this alert box will be out of screen when pressing the submit button. so a user has to scroll up to see whats going on.

**Comment by engram-design** [comment]
Added in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)
