### ISSUE TITLE
Incorrect use of `<label>` with hidden inputs

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1660]
### Describe the bug

After adding a Hidden Field to a form, the following error appears in the console:

> **Incorrect use of \<label for=FORM_ELEMENT\>**
> The label's `for` attribute doesn't match any element `id`.

Inspecting the markup, I do see that the value for the hidden input's `id` does in fact match the label's `for` value. However, I did find this line about the label element in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#:~:text=Elements%20that%20can%20be%20associated):

> Elements that can be associated with a `<label>` element include ... `<input>` **(except for type="hidden")**

### Craft CMS version

4.5.12

### Plugin version

2.0.44.1

**Comment by engram-design** [comment]
Right, so according to https://github.com/verbb/formie/issues/1638 we opted to show hidden field labels, which I actually thought was valid according to my knowledge of accessible forms, but from that article, it seems like they're really not required?

So it would seem like we need to revert that?

**Comment by chrismlusk** [comment]
#1638 is slightly different, because that issue refers to fields where you can customize the Appearance options to have a visible field with a hidden label.

But this issue is about the Hidden Field field type (and possibly other fields where the Visibility setting is changed to "Hidden").

**Comment by engram-design** [comment]
Great point. Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.44.1"`.

**Comment by engram-design** [comment]
Updated in [2.0.45](https://github.com/verbb/formie/releases/tag/2.0.45)
