### ISSUE TITLE
Adding form steps count in custom source's default table columns views

### ISSUE THREAD

**Issue by yingban** [verbb/formie#1664]
### What are you trying to do?

Hi,

I have a matrix block where the client could only selects single step forms.
So I thought about creating a custom source with a form criteria "steps < 2".

### What's your proposed solution?

Including the number of steps in the default tables columns and enabling it for form criteria filtering would solve my problem.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)

**Comment by yingban** [comment]
Hi @engram-design,

Thanks for the release.

Should it be selectable in the dropdown on new custom source setting?
![Screenshot 2024-01-03 at 12 34 46](https://github.com/verbb/formie/assets/3421450/06d0d4c4-0020-44bd-9405-071dc2939d7e)

**Comment by engram-design** [comment]
That'd be an additional feature, but added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.
