### ISSUE TITLE
Limit Submissions not working as expected with custom ajax form

### ISSUE THREAD

**Issue by KarolJurczykDS** [verbb/formie#1665]
### Describe the bug

1. When sending custom ajax form `isWithinSubmissionsLimit` method is not triggering, most likely because there is no `draft/incomplete` flag set in this scenario (other two checks - requireUser and scheduleForm - are working fine):
https://github.com/verbb/formie/blob/craft-4/src/elements/Submission.php#L440

2. When rendering custom ajax form `isAvailable` and/or it's inner methods are not available in graphql schema, so it's impossible to check if it should be rendered or not
https://github.com/verbb/formie/blob/craft-4/src/elements/Form.php#L2078

### Steps to reproduce

1. 
FORM
    Limit Submissions = true
    Number of Submissions = X total

POST
    /actions/formie/submissions/submit

PAYLOAD
    fields[firstName]: Karol
    fields[lastName]: DS
    ...
    handle: testForm```

2. In CraftCMS: `/admin/graphiql`

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.5.5

### Plugin version

2.0.36

### Multi-site?

No

### Additional context

We're using NextJS with custom formie component
- form data is queried with GraphQL from CraftCMS `/api` endpoint
- submission is sent back to CraftCMS using `/actions/formie/submissions/submit` endpoint

**Comment by engram-design** [comment]
I've added handling for both of those. Note that some checks like the required user might be tricky with headless scenarios and maintaining a user session.

To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.44.1"`.

**Comment by KarolJurczykDS** [comment]
Works like a charm, thanks, can close it now

**Comment by engram-design** [comment]
Updated in [2.0.45](https://github.com/verbb/formie/releases/tag/2.0.45)
