### ISSUE TITLE
View incomplete submissions - "A server error occurred" / chart not shown.

### ISSUE THREAD

**Issue by mandrasch** [verbb/formie#1668]
### Describe the bug

Hi, I just updated locally from

formie 2.0.42 => 2.1.0

After the update I just see a blank area where the chart is normally located in Submissions > Incomplete? 

![image](https://github.com/verbb/formie/assets/777278/5470f3b7-ca9a-41c4-94d6-3523467ee1fe)

I couldn't find a related error message in devtools network tab as well as server logs. 

The form has form groups and multiple upload fields / it's a multi step form. 

Thanks in advance for looking into it!

### Steps to reproduce

1. View incomplete submissions

### Form settings

- Multi-page form: Yes
- Submission Method:Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.13

### Plugin version

2.1.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Looks like there was an issue uploading your image, but can you also check your log files for more detail on the error? I know you mentioned checking them, but it might be worth loading the submission index, deleting your `/storage/logs` folder entirely, and then reloading the page - just to make things clearer. I can't seem to reproduce that on my end.

Do regular, complete submissions display normally?

**Comment by mandrasch** [comment]
Hi! 

yes, other completed submissions work fine.

Sorry, screenshot fixed:

![image](https://github.com/verbb/formie/assets/777278/4e029533-cca3-45a5-af0f-22d1c731dea0)

I just saw the error output:

![image](https://github.com/verbb/formie/assets/777278/d78a9a99-a769-4f48-ab46-df0418b8568c)

Weird thing is - first request get's canceled, second one works fine:

![image](https://github.com/verbb/formie/assets/777278/9aebfbcb-a077-4d54-85b8-f847deb55e56)

It's not that high-priority for us, just wanted to let you know. 👋 

We will deploy this update in first weeks of the next year, I could give an update here if this also happens on production.

**Comment by engram-design** [comment]
Ah, so it's just the graph throwing an issue. Would you be able to inspect one of the elements shown in the table, and show the `data-date-created` attribute?

![CleanShot 2023-12-30 at 08 53 16@2x](https://github.com/verbb/formie/assets/1221575/5290a483-e193-4062-b38b-459d695ce27b)

According to the JS logs, there's something invalid about that date...

**Comment by mandrasch** [comment]
Hi!

Output here (redacted it a bit with XXX):

```
<div class="element small hasstatus" title="2023-12-29 09:57:32 - XXX" data-date-created="2023-12-29T09:57:32.000000Z" data-type="verbb\formie\elements\Submission" data-id="XXX" data-site-id="6" data-status="new" data-label="2023-12-29 09:57:32" data-editable="" data-deletable=""><div class="label"><span class="title"><a href="XXX?site=default">2023-12-29 09:57:32</a></span></div><span class="icon" data-icon="draft" role="img" aria-label="Status: Entwurf"></span></div>
```

**Comment by mandrasch** [comment]
Okay, found it:

Elements here find two occurences, but submissions in incomplete state = only 1

![Bildschirmfoto 2024-01-05 um 13 27 54](https://github.com/verbb/formie/assets/777278/eca66e3d-99c2-4a4e-b07c-b35fabefcefa)

Second element is the div from the User column (I have connect user activated for this form)

![image](https://github.com/verbb/formie/assets/777278/ea77cadf-728f-4610-8580-9781927be2cb)

When I hide the user column here 

![image](https://github.com/verbb/formie/assets/777278/ffef6f9d-0300-4f79-a67a-30ea22652ec2)

- the chart shows as expected

**Comment by engram-design** [comment]
Ah, that makes sense now! Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.

**Comment by mandrasch** [comment]
Cool, thanks very much! 👍
