### ISSUE TITLE
Single-line Text Field: Move "Include in Email Notifications" to Settings tab

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1675]
The "Include in Email Notifications" setting for Single-line Text fields is under the Advanced tab, which is different than all other fields as far as I can tell.

Moving this to the Settings tab will improve the UX by placing the setting in a consistent spot.

**Comment by engram-design** [comment]
Good call, never noticed that! To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.

**Comment by engram-design** [comment]
Updated in [2.1.2](https://github.com/verbb/formie/releases/tag/2.1.2)
