### ISSUE TITLE
Hiding the label on checkboxes does not hide the label

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1683]
### Describe the bug

When using a Checkbox field, if you try to hide the label, it doesn't hide it.
Field:
![image](https://github.com/verbb/formie/assets/1250017/e88859b7-aba5-46eb-8ee1-430dec1a52c9)

Settings:
![image](https://github.com/verbb/formie/assets/1250017/9d3b9cc8-a28d-464b-ae93-d61551e1c878)

Appearance settings:
![image](https://github.com/verbb/formie/assets/1250017/9ac24d0d-ec77-4d92-a00f-205480377ee3)

Front end:
![image](https://github.com/verbb/formie/assets/1250017/0cdee3e2-2db0-4571-910b-594e306dce9c)

Front end code:
![image](https://github.com/verbb/formie/assets/1250017/81d90521-7a7a-44d6-86e5-f1cb821c74e0)

### Steps to reproduce

1. Add a checkbox field
2. Try to hide the label with Settings > Appearance

### Form settings

- Multi-page form: No
- Submission Method: Redirect
- Client-side Validation: Formie validation only
- Custom Form Templates: No - theme override

### Craft CMS version

4.5.12

### Plugin version

Formie 2.1.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.

**Comment by engram-design** [comment]
Fixed in [2.1.2](https://github.com/verbb/formie/releases/tag/2.1.2)
