### ISSUE TITLE
Calculation field used as dynamic payment amount for stripe not working

### ISSUE THREAD

**Issue by siebird** [verbb/formie#1684]
### Describe the bug

Using two fields to calculate a total amount for a registration form.

1. The first field `amount` is a hidden field and the value is set via an entry field.
2. The second field is `adventures` and is a dropdown with 6 options with the values being numeric.

The calculation field in number format takes the two fields above to perform the total amount. The values are calculating correctly `amount + (adventures - 2) * 25`. 

However, when I go to submit the form I get the following error:

`Missing `amount` from payload: {$amount}.`

However, switching to the calculation field to string it concatenates the string and the error is not thrown.

### Steps to reproduce

1. Setup a form with stripe payments
2. Create the fields above. Pass in the value via the templates
3. Try submitting a payment

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.6.0

### Plugin version

2.1.1

### Multi-site?

No

**Comment by engram-design** [comment]
That's strange, I can't replicate that behaviour and payments are going through correctly, setting up everything according to your steps.

When you say you switch things to use string concatenation - do you just mean changing the formatting to not be a number? That'd probably produce an invalid value for the calculation field that's all.

And does the error actually say `Missing amount from payload: {$amount}.` with `{$amount}` being shown? If so, that's _very_ odd as `$amount` should be a number.

Would you be able to send through a support request via Formie > Settings > Get Support - just in case your form is structured differently with Group fields?

**Comment by siebird** [comment]
I forgot to mention. I have the field set to visible so it's read only. Not sure if that will replicate it.

The error is thrown is what I posted. It's the variable and not a value.

**Comment by engram-design** [comment]
Thanks for sending that through, very helpful! Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.

**Comment by engram-design** [comment]
Fixed in [2.1.2](https://github.com/verbb/formie/releases/tag/2.1.2)

**Comment by siebird** [comment]
Thanks for getting this fixed. You're awesome!
