### ISSUE TITLE
Change Recipients field using Pre-Populating values

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1685]
Currently, when setting a value via pre-population on a recipients field, the value must be supplied as an email address which is a privacy issue. We would rather have the value supplied as an index like 0, 1, 2, 3, etc.

This may be a breaking change, and maybe we will handle setting both an email value and a numerical value.

**Comment by lindseydiloreto** [comment]
Great, thanks for noting this! 🙏 

It may also be worth allowing a match with the "Option Label" (if possible)...

![Recipients](https://github.com/verbb/formie/assets/5309692/b991d349-f6a5-4d2c-b6ef-a56b49e1af29)

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)

**Comment by lindseydiloreto** [comment]
Very cool, thanks @engram-design! 🎉
