### ISSUE TITLE
Pre-populated entry field from query parameter resets to empty on page refresh

### ISSUE THREAD

**Issue by DenyEs** [verbb/formie#1688]
### Describe the bug

On a multi-page form, I have an entry field on first page that's being pre-populated based on the query parameter, let's say /contact-us?entry=1708

When I visit the page on the first try, field gets populated but when I save and proceed to the next page and the page refreshes, it's gone. 

I do have a field limit set to one, but when I try to submit the same form but change it to ajax, field stays retained. When I save, leave and come back again, I can proceed with my steps but the field is empty (AJAX or not).

I managed to replicate the same issue on multuple sites.

Let me know if anything sounds confusing and needs clarification

### Steps to reproduce

1. Create a multi-page form
2. Add an entry field and configure a parameter from Settings tab
3. Add another page
4. After you submit the first page, go to the control panel and find the incomplete entry - field is still populaed
5. Submit another page of the form
6. Check the submission in the CMS again - field becomes empty

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax or Page Reload - happens with both if you leave and come back
- Custom Form Templates: No

### Craft CMS version

4.6.1

### Plugin version

2.1.2

### Multi-site?

No

**Comment by engram-design** [comment]
I can't seem to replicate that, sorry! Are you changing the URL after the first page is submitted to remove the query param that would set the entries field? Otherwise, that would set it on every request. But it also only sets the default value of a field, if the field already has a value, then it uses that value instead.

**Comment by DenyEs** [comment]
I am not removing the query params from the URL no. I can see the values got set in the CMS submission but when I click save and continue and save the next page, it resets them all.

**Comment by engram-design** [comment]
Hmmm. Are you able to submit a support request via Formie > Settings > Get Support? Wondering if it might be something specific to your form setup.

**Comment by DenyEs** [comment]
Sure, I will send it through with a screen recording as well to showcase the issue. I just need to compress the video as it's too big to send

**Comment by DenyEs** [comment]
@engram-design Done mate, you should have a support request now. Thank you!

**Comment by engram-design** [comment]
Thanks for that, and the video showing it on your end. That's pretty odd compared to what I'm seeing! https://share.cleanshot.com/0BqmgQrC

**Comment by DenyEs** [comment]
Oh yeah that's really odd, I can rule out my local network or browser settings as the client reports the same behaviour. Must be something within the application itself but I am not doing anything special when it comes to rendering a form. I will try to dig deeper on Monday and I will keep you updated if I will come across a solution and what caused it

**Comment by engram-design** [comment]
Yeah, seems a bit odd behaviour. I'll keep looking into it on my end as well. One thing to check on in the network request for the pages to see if something is different from mine below.

First page:
<img width="740" alt="image" src="https://github.com/verbb/formie/assets/1221575/a4d2c951-0c74-4ce1-be3e-ceca7609caa7">

Second page:
<img width="769" alt="image" src="https://github.com/verbb/formie/assets/1221575/d41ef2ee-bf60-4958-82d8-3b845d10d761">

You can see that `fields[chooseEntry][]` is set to `20` for both pages. I'm wondering if something is going amiss on your second page submission - somehow?

**Comment by DenyEs** [comment]
I just checked it and and I can see field[chooseEntry[]]: 1708 in the payload the first time I submit, but it's empty after the second page is submitted - field[chooseEntry[]]:

Every other field is absolutely fine

**Comment by DenyEs** [comment]
Managed to figure it out Josh. The problem was limit set on an entry field. I don't want users to be able to choose any other entry when I define an entry in the URL as a parameter so I set limit to 1.

I suppose that on the first load it's able to get an entry based in it's ID but when I submit the second time, it resets field to empty as it's no longer able to get it (?) It defaults to the first entry it finds based on the section I selected, it ignores the ID in the URL.

When I remove the limit on the field, I am able to get through the submission without the value of entry field being lost on the 2nd, 3rd.... page submission.

I don't think my approach to this is incorrect and it should still be able to get an entry when it's present in the URL right?

Let me know what you think

**Comment by engram-design** [comment]
I thought I'd actually tested that, but you're right, that's the issue. It's because we limit values _after_ we take into account the default value. I was (stupidly) testing the first available entry for the field.

Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.2"`.

**Comment by DenyEs** [comment]
Awesome! Thank you Josh, just tested it and it works as it should!

**Comment by engram-design** [comment]
Fixed in [2.1.3](https://github.com/verbb/formie/releases/tag/2.1.3)
