### ISSUE TITLE
<small> tag shouldn't wrap <p>

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#169]
It looks like instructions are wrapped in a small tag using the default template. I'm pretty sure this isn't valid HTML as the small tag is an inline element. Consider changing the tag to a div.

![image](https://user-images.githubusercontent.com/25124/95708090-1d904d00-0ca7-11eb-8b91-09e2c9a8f6d0.png)

**Comment by engram-design** [comment]
Fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20).
