### ISSUE TITLE
utf8_encode-deprecation in PHP 8.2

### ISSUE THREAD

**Issue by alexgit2k** [verbb/formie#1698]
### Describe the bug

The Formie plugin is using `utf8_encode` which is deprecated in PHP 8.2: https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

https://github.com/verbb/formie/blob/1519da306cbd925b81db89086c88c16095788161/src/elements/Form.php#L1343

### Steps to reproduce

1. 
2. 

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

-

### Plugin version

-

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by alexgit2k** [comment]
Thanks! Change in 8d5aaff

I think it should rather be `mb_convert_encoding($url, 'UTF-8', 'ISO-8859-1');`, because [utf8_encode](https://www.php.net/manual/en/function.utf8-encode.php) converted from ISO-8859-1 to UTF-8, and without the third parameter at `mb_convert_encoding` the `default_charset` is used as source-encoding which defaults to UTF-8.

**Comment by engram-design** [comment]
Good call, just updated that now.

**Comment by alexgit2k** [comment]
For the record, commit 4441668.

**Comment by engram-design** [comment]
Updated in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
