### ISSUE TITLE
Order of 'Input Container" and "Input" is inconsistent with rest of the rendered markup

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1701]
### Describe the bug

The structure of a form's rendered HTML is:

```html
<div class="fui-thing">
    <div class="fui-thing-container">
```

Until you get to the input, where the order is flipped:

```html
<div class="fui-input-container">
    <input class="fui-input">
```

It's a small thing — and I realize any solution requires a breaking change — but man it confuses me every time.

**Comment by engram-design** [comment]
Yeah, that's a fair enough annoyance. I wanted to not have a new term for the inner container to keep things consistent and simple. But yes, a typical field structure looks like:

```html
<div class="fui-field" data-field-type="single-line-text">
    <div class="fui-field-container">
        <label class="fui-label">Test</label>
        
        <div class="fui-input-container">
            <input class="fui-input">
        </div>
    </div>
</div>
```

Where you have the `fui-field` class as the top-level, then an inner container of `fui-field-container` which wraps everything about the field. Then a `fui-input-container` which acts as the container to the various inputs for different fields.

So, yes - one really acts like the inner container (or wrapper) for the field, inside the main field element, the other is the outer container for the input. Naming things is hard!

Not all fields have this, options fields for example like Checkboxes have a fieldset.

```html
<div class="fui-field" data-field-type="checkboxes">
    <fieldset class="fui-fieldset">
        <legend class="fui-legend">Checkboxes</legend>
            <div class="fui-input-container">
                <input type="hidden" name="fields[checkboxes]" value="">
                
                <div class="fui-layout-wrap">
                    <div class="fui-checkbox">
                        <input class="fui-input fui-checkbox-input">
                        <label class="fui-checkbox-label">Option 1</label>
                </div>
            </div>
        </div>
    </fieldset>
</div>
```

I'm open to suggestions on naming, but the structure can't really change as it's important to have an inner wrapper for fields. I'd rather give people too many structural elements in HTML to allow for greater flexibility in their own customisation. Removing elements is quite easy in Theme Config, but adding them is much trickier.

This would need to be included in Formie 3 for Craft 5 as a breaking change.

**Comment by chrismlusk** [comment]
> Naming things is hard!

I completely empathize with you. I mean, I chickened out and didn't offer a suggestion in my issue 😅 

After taking another look at the docs, specifically the Theme Config page, it seems that you already have an established pattern of using both "wrapper" and "container" terms — with "wrapper" meaning outside and "container" meaning inside. For example: `formWrapper` → `form` → `formContainer`.

So, my suggestion is to follow that pattern and rename `fui-input-container` as `fui-input-wrapper`.

**Comment by engram-design** [comment]
That's a great point (Theme Config came after the initial structure planning, so I clearly wanted to change it up).

Consider that penciled in for Formie 3.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
