### ISSUE TITLE
Progress bar not updating wenn going back to the first step (Ajax)

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1702]
### Describe the bug

Ajax only: The progress bar is not updating when going back to the first step by using the back button.

The `data.nextPageIndex` is `0` on page 1, therefore the condition to update the progress bar is not met. 
Fix:
```js
 if ($progress && data.nextPageIndex >= 0) {
 ...
 }
```
https://github.com/verbb/formie/blob/craft-4/src/web/assets/frontend/src/js/formie-form-theme.js#L813

### Steps to reproduce

1. Create a multi-page form (ex 3 pages)
2. Set submission method to Ajax
3. Enable display page progress
4. Use the back button to go from page 3 to page  2 and then from 2 to 1
5. The Progress-bar is not updating from step 2 to 1

### Form settings

- Multi-page form: Yes 
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates:  No

### Craft CMS version

4.7.1

### Plugin version

2.1.3

### Multi-site?

no

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
