### ISSUE TITLE
Brevo Double Opt-In Error: An active DOI template does not exist

### ISSUE THREAD

**Issue by TurboThomsen** [verbb/formie#1704]
### Describe the bug

API error: “{"code":"invalid_parameter","message":"An active DOI template does not exist"}”

But the Template exists and is active.

### Steps to reproduce

1. E-Mail Marketing: Entry with Brevo Provider + Key
2. Form with Email Marketing Integration + Double Opt in (Template ID + Redirection URL)
3. Form "successfully submitted"
4. Error in Queue-Manager

I followed the docu https://developers.brevo.com/docs/other-common-questions#doi-double-opt-in-template

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.5.11.1

### Plugin version

2.1.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
What value are you using for the "Template ID"? Is it valid?

**Comment by TurboThomsen** [comment]
![image](https://github.com/verbb/formie/assets/103662584/53a4db31-8765-4742-bfd8-f7f4f4917944)

153 without the #

if I set it to "#153" then I get:
API error: “{"code":"invalid_parameter","message":"Invalid template id"}”

Sry. Maybe it's more an issue on brevo.
This is an account from a customer. I wasn't there when the template was created.
The template contains {{ params.DOIurl }}

**Comment by engram-design** [comment]
Seems to be working for me. Here, my ID is `4`.

<img width="670" alt="image" src="https://github.com/verbb/formie/assets/1221575/cb031f44-f5b6-4d52-8718-5ca51a70a794">

Note that in the "Setup" stage of the template, I have added `optin` to the tag. This is according to the Brevo docs.

<img width="1124" alt="image" src="https://github.com/verbb/formie/assets/1221575/49c38c3b-9647-4e24-9c7d-e2878da2c02e">

**Comment by TurboThomsen** [comment]
Thx for the help. That was the issue.
