### ISSUE TITLE
Successful payments when submission marked as spam

### ISSUE THREAD

**Issue by siebird** [verbb/formie#1706]
### Describe the bug

Spam workflow/rules should run first before triggering payments. 

We had a list of spam keywords set in Formie. Any form that has payments (Stripe) captured payment when the submission was marked as spam, thus causing duplicate payments at Stripe. 

### Steps to reproduce

1. Set a list of spam keywords
2. Create a form with payments (stripe)
3. Submit a payment with spam keyword in it

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.7.1

### Plugin version

2.1.3

**Comment by engram-design** [comment]
While they do indeed run first, they don't prevent payment processing. That's probably a dumb move on our part.

Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by siebird** [comment]
Definitely an edge case on why we found it.

I ignorantly put ~1000 profanity keyword list into the settings and it was causing more issues than solving.

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
