### ISSUE TITLE
HTML fields are rendered with a `<label>`

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1707]
### Describe the bug

When using an HTML field, the rendered markup includes the label as a `<label>` element even though this field doesn't include a form control.

And while I don't think the HTML spec specifically forbids using the `<label>` element like this, I wonder if a `<span>` would be more appropriate? Or, at the minimum, the `for` attribute should not be rendered, since that _is_ invalid:

> **Incorrect use of \<label for=FORM_ELEMENT\>**
> The label's `for` attribute doesn't match any element `id`.

Also, if the Label Position setting is "Hidden" for an HTML field, that label gets rendered with the `data-fui-sr-only` attribute. However unlike other fields with hidden labels where the label needs to be discoverable by screen readers, I would expect HTML fields to not render this label at all since it's essentially an internal label at this point.

### Craft CMS version

4.7.1

### Plugin version

2.1.3

**Comment by engram-design** [comment]
That's a valid point! I think for now we'll just remove the `for` attribute and properly hide the label in this case. We'll still keep it using a `<label>` element for now (and easy enough to customise that in Theme Config if you like). We already do a similar thing for cosmetic fields, but the HTML field is a special case where it's cosmetic, but can also have a field label.

Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
