### ISSUE TITLE
Stencil option is reset when the handle is invalid

### ISSUE THREAD

**Issue by MoritzLost** [verbb/formie#1712]
### Describe the bug

When creating a new form, if you enter an invalid handle, the form will reload. The **Name** and **Handle** fields will retain their values, but the **Stencil** dropdown will be reset to the default option **Blank form**. This is easy to miss and might cause frustration, since the form will not use the previously selected stencil option.

### Steps to reproduce

1. Go to **Formie** → **Forms** and click on **New Form**
2. Enter anything in the **Name** field, select **Contact Form** in the **Stencil** field and enter an invalid handle under **Advanced** like `foo-bar`.
3. Click on **Next** or hit enter.

### Form settings

N/A

### Craft CMS version

4.7.1

### Plugin version

2.1.3

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by MoritzLost** [comment]
@engram-design Thanks!

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
