### ISSUE TITLE
Can't remove classes from alerts

### ISSUE THREAD

**Issue by MoritzLost** [verbb/formie#1717]
### Describe the bug

I'm trying to replace the classes on alerts with my custom classes. I've put this in my `config/formie.php`:

```php
<?php

return [
    'themeConfig' => [
        'alertError' => [
            'resetClass' => true,
            'attributes' => [
                'class' => 'alert alert--error',
            ],
        ],

        'alertSuccess' => [
            'resetClass' => true,
            'attributes' => [
                'class' => 'alert alert--success',
            ],
        ],
    ],
];
```

I'm rendering my form without any additional parameters:

```twig
{{ craft.formie.renderForm('contactform') }}
```

The contact form is just created from the default contact form stencil without any modifications (AJAX is enabled).

But when I hit submit, the error alert (for missing fields) is output like this:

```html
<div class="fui-alert alert alert--error fui-alert-top-form" role="alert" data-fui-alert="true">Couldn’t save submission due to errors.</div>
```

My custom classes are being added, but the default classes are still there.

---

I've also noticed that when I remove `resetClass`, the default classes are output _twice_:

```html
<div class="fui-alert fui-alert fui-alert-error fui-alert-top-form alert alert--error fui-alert-top-form" role="alert" data-fui-alert="true">Couldn’t save submission due to errors.</div>
```

So maybe the classes are added in two places, and `resetClass` only removes them in one?

---

As a side-note, I think there's an error in the example for resetting classes: https://verbb.io/craft-plugins/formie/docs/theming/theme-config#resetting-classes

The `resetClass` property is nested under `attributes`, it should be under `field`. Cost me a couple minutes to figure out :)

### Steps to reproduce

1. Use the config listed above.
2. Create a new form based on the default contact form stencil and render it on a page.
3. Hit submit.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.7.1

### Plugin version

2.1.3

### Multi-site?

No

**Comment by MoritzLost** [comment]
Oh, just noticed there's an existing issue for that: https://github.com/verbb/formie/issues/1434

Leaving this open as the info in this issue might be helpful for debugging. Feel free to close @engram-design 

The example in the docs should be fixed though.

**Comment by engram-design** [comment]
Bah, you're right about the docs, updated. Will follow up in https://github.com/verbb/formie/issues/1434
