### ISSUE TITLE
Ability to show custom table columns on submissions view

### ISSUE THREAD

**Issue by howells** [verbb/formie#172]
**What are you trying to do?**
I'd love to be able to show a handful of additional custom fields for submissions in the submissions view, like other Craft index views.

**What's your proposed solution?**
When Customize is selected, additional form fields are shown which can be selected.

**Additional context**
Additional fields could be available here: https://cln.sh/cx3kZg

**Comment by engram-design** [comment]
Fixed in [1.2.21](https://github.com/verbb/formie/releases/tag/1.2.21).

**Comment by howells** [comment]
Ace, thanks!
