### ISSUE TITLE
[JS / Validate When Typing] Hide form error message after validation success

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#173]
**Description**
It would be nice that after fixing all the errors in the fields (in the Validate When Typing mode), the general message also disappears. But that doesn't happen. It seems like a bug...
Could you fix it?

![изображение](https://user-images.githubusercontent.com/496132/96020323-84079d80-0e56-11eb-88ad-d66c114f28df.png)

[Video ](https://drive.google.com/file/d/1VJ9_40d5J3jl9zQKxHMXhzPEpEL4Uny6/view)

**Steps to reproduce**
1. Enable Validate When Typing option
2. Make some fields required
3. Try to submit form

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.21
- Craft version: 3.5.7
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Improved in [1.2.22](https://github.com/verbb/formie/releases/tag/1.2.22).
