### ISSUE TITLE
Wrong rebrand logo path inside Formie

### ISSUE THREAD

**Issue by ArnoMoqo** [verbb/formie#1730]
### Describe the bug

We have this weird issue with sending email templates. We have a general email template thad we also use for the general Craft emails like signup or forget email. We use the same template for sending formie notification.

Inside our template we have the following snippet:
```twig
{% if craft.rebrand.isLogoUploaded() %}
    <img class="em_full_img" src="{{ craft.rebrand.getLogo().url }}" width="{{ craft.rebrand.getLogo().size[0] }}" height="{{ craft.rebrand.getLogo().size[1] }}" alt="{{ systemName }} logo" border="0" style="display:block;font-family:Arial, sans-serif; font-size:15px; line-height:20px; color:#424242; max-width:{{ craft.rebrand.getLogo().size[0] }}px;"/>
{% else %}
    <p class="em_full_img" style="display:block;font-family:Arial, sans-serif; font-size:30px; font-weight: bold; text-transform:uppercase; line-height:20px; color:#000;">{{ systemName }}</p>
{% endif %}
```

The problem is, in the web version & the emails from Craft CMS the rebrand logo url is like this: `cpresources/fcd4a62/logo.svg?v=1708079245` however when i preview an email inside Formie or when we received the email send by Formie this url looks like this: `assets/c9ea879d/logo.svg`-> non existing so we get an 404.

<img width="1273" alt="Screenshot 2024-02-16 at 11 40 50" src="https://github.com/verbb/formie/assets/117268595/4925e86e-9566-4734-b02c-447dd2301598">

### Steps to reproduce

1. Create a new default email template where you use the rebrand from Craft CMS control panel
2. Use this template inside Formie
3. Watch Formie render the wrong url

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.7.3

### Plugin version

2.1.3

### Multi-site?

No

**Comment by lennonpuype** [comment]
@engram-design Is there any news on this issue?

**Comment by engram-design** [comment]
I've been struggling to replicate this, unfortunately. How do you run your queue that sends out email notifications? Using the Craft default, or via the CLI? I have tested with both, and the URL seems to render correctly. In all instances, we're getting a `/cpresources/23ed5d53/icon.svg?v=1709126149` URL.

**Comment by ArnoMoqo** [comment]
Hi, we can't seem to replicate it on a constant base. Seems to be fixed for now after clearing our caches..
