### ISSUE TITLE
Inconsistent database behavior for sent notifications (e.g. cc & bcc)

### ISSUE THREAD

**Issue by medoingthings** [verbb/formie#1731]
### Describe the bug

Background ist the workaround needed due to this issue here: https://github.com/verbb/formie/issues/1711

I now collect email addresses, put them in a comma-separated list into the `bcc` field, in order to send the notification to 14+ dynamic recipients.

I managed to send the emails, but as soon as the comma-separated recipient list exceeds 255 characters, the following error is thrown on form submit:
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'bcc' at row 1
```
I noticed that the database table `formie_notifications` uses the type `TEXT` for the field `bcc` and `cc` (and more), but the table `formie_sentnotifications` uses `VARCHAR(255)` for the same fields, resulting in an error while trying to log the sent notification. 

The emails are still sent, but the error is thrown and no record created under "Sent Notifications". 

Would be great if you could change the field types so that the `cc` and `bcc` fields can hold way more than 255 characters, without throwing an error on submit.

### Steps to reproduce

1. Add a form
2. Add a notification
3. Put a comma-separated list of email addresses (minimum 256 characters!) into the notifications `bcc` field
4. Submit the form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.7.2.1

### Plugin version

2.1.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by engram-design** [comment]
Updated in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
