### ISSUE TITLE
GraphQL: Internal server error when querying Agree field description

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#174]
**Description**
When I query a form with an agree field and try to include the field description, I get the following error: 

```
{
      "debugMessage": "Expected a value of type \"String\" but received: [{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"This should be a description for the agree field.\"}]}]",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 106,
          "column": 13
        }
      ],
      "path": [
        "form",
        "pages",
        0,
        "rows",
        5,
        "fields",
        0,
        "description"
      ]
    }
```
This seems to have cropped up somewhere between 1.2.19 and 1.2.21

**Additional info**
- Plugin version: 1.2.21
- Craft version: 3.5.12.1
- Multi-site:  No

**Additional context**

**Comment by engram-design** [comment]
Sorry about that. Should be fixed in [1.2.22](https://github.com/verbb/formie/releases/tag/1.2.22), but you'll need to change your query to use `descriptionHtml`. I hope that doesn't cause too much inconvenience.
