### ISSUE TITLE
Email notifications fail to submit

### ISSUE THREAD

**Issue by controlnocontrol** [verbb/formie#1741]
### Describe the bug

A form with required name required fields that have conditions will fail to send email notifications.

### Steps to reproduce

1. Create required radio fields with A, B, C options (labels and values)
2. Add Name field with Use Multiple Name Fields, First Name and Last Name enabled
3. Add a condition to Name field in step 2 using the radio field in step 1 (condition: IS, value: A
4. Create Email notification
5. Submit the form choosing radio value B or C.
6. Go to Formie > Sent Notifications
7. Observe failed notification.  It throws the error "Notification email parse error for “To: hello@email.com”. Template error: “Impossible to access an attribute ("firstName") on a null variable.” /path/to/craft/vendor/verbb/formie/src/templates/_special/email-template/fields/name.html:12"

Fix:
Update name.html template line 6:
from: {% if field.settings.useMultipleFields %}
to: {% if field.settings.useMultipleFields **and value** %}

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.9.10

### Plugin version

1.6.36.1

### Multi-site?

No

**Comment by engram-design** [comment]
Looks like this fix just needed to be backported from Formie 2. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.36.1"`.

**Comment by engram-design** [comment]
Updated in [1.6.37](https://github.com/verbb/formie/releases/tag/1.6.37)
