### ISSUE TITLE
Pipedrive integration "Map to Lead" sometimes getting mapped to Pipedrive deal instead of lead

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#1742]
### Describe the bug

We have a Formie/Pipedrive integration configured for one of our forms, and it's working properly the majority of the time. The integration is configured to map the submission to a lead in Pipedrive, but about 20% of the time the submission gets mapped to a deal in Pipedrive instead of a lead.

Pipedrive support was unfortunately not able to help with the issue. I'll attach a screenshot of the integration settings below. Please let me know what additional information I can provide to help troubleshoot. Thanks!

![Screenshot 2024-02-28 at 8 55 03 AM](https://github.com/verbb/formie/assets/18213990/83413448-d27a-4ad7-ad16-e8ac50979c2a)

### Steps to reproduce

1. Configure a Pipedrive integration.
2. Set up a form to use the Pipedrive integration and map submissions to a lead.
3. Submit form multiple times.
4. Some of the submissions will be mapped to a deal in Pipedrive instead of a lead.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.8.0

### Plugin version

2.1.5

### Multi-site?

No

**Comment by engram-design** [comment]
Well I'm not _quite_ sure how it's possible for a deal to be created when mapping to a lead, short of something on Pipedrive's end. Maybe to deal with duplicates, or something?

The [code](https://github.com/verbb/formie/blob/13a3d9afb5d647029e778b14028ffab8415cee4a/src/integrations/crm/Pipedrive.php#L326-L367) for creating a lead really is pretty straightforward. There also doesn't seem to be any mention of this in the [docs](https://developers.pipedrive.com/docs/api/v1/Leads#addLead).

I've probably got to put this one on Pipedrive's end, as there's nothing obvious I can see from our end we're doing wrong!

**Comment by jwrudzin** [comment]
@engram-design Got it, thanks for the quick reply. I'll close this issue for now, and will reopen if Pipedrive support is able to provide any additional useful information.
