### ISSUE TITLE
Automatic Integrations?

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/formie#1743]
### Question

So we have an integration setup that adds a new Entry to a section of the website. However, this only fires when click integration from the form submission. is there any way to have this trigger automatically instead?

I haven't seen a setting for it and it would be really nice to set this up.

Thanks for the help!

**Comment by DynamiteGoesBoom** [comment]
Ahh nevermind, it looks like it does fire right away but takes a moment to process it

**Comment by engram-design** [comment]
All integrations run via the queue, but you can disable this if you like. I’d not advise it though, as it slows down form submission time making bad UX for users filling out the form.

There’s also [plans](https://github.com/verbb/formie/issues/1152) to add an exception to this for element integrations.
