### ISSUE TITLE
Add support for querying sub-fields via GQL

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1747]
Sub-fields like multi-Name and Address only return strings, while their data is a model. Let's look to see if we can use:

```gql
{
  formieSubmissions(id: 1234) {
    ... on contactForm_Submission {
      nameField

      nameField {
        firstName
        lastName
      }
    }
  }
}
```

This may be a breaking change for some users.

**Comment by davidwebca** [comment]
Hi! Is this related to the fact that I can't query "options" on checkbox and radio buttons anymore in GraphQL?

**Comment by engram-design** [comment]
Sounds like a different issue, if you can file a new issue?

**Comment by davidwebca** [comment]
Done!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
