### ISSUE TITLE
MailChimp integration resulting in failed jobs

### ISSUE THREAD

**Issue by mikos** [verbb/formie#175]
**Description**
We have a contact form with MailChimp integration enabled. Whenever we get a submission and the user hasn't checked the "agree" field we get a failed job titled `Triggering form “mailchimp” integration.` When the field is checked the integration works without issue.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.21
- Craft version: 3.5.12.1
- Multi-site: No

**Comment by engram-design** [comment]
Ah, yep we shouldn't be raising an error when they opt-out. Should be fixed in [1.2.22](https://github.com/verbb/formie/releases/tag/1.2.22) and those queue jobs are free to be released.
