### ISSUE TITLE
Typo in file name ModifyFrontEndSubfieldsEvent

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1757]
### Describe the bug

The file ModifyFrontEndSubfieldsEvent.php needs to be renamed to ModifyFrontEndSubFieldsEvent.

`git mv src/events/ModifyFrontEndSubfieldsEvent.php src/events/ModifyFrontEndSubFieldsEvent.php`

### Steps to reproduce

1. Create a form with subfields
2. Render it in the frontend
3. Get this error `Class "verbb\formie\events\ModifyFrontEndSubFieldsEvent" not found`

### Form settings

No settings have been changed 

### Craft CMS version

5

### Plugin version

3

### Multi-site?

no

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.3"`.
