### ISSUE TITLE
Link to uploaded file in notification email?

### ISSUE THREAD

**Issue by mikos** [verbb/formie#176]
Is it possible to add a link to a file uploaded in a form to the notification email?

If not, can it be made possible?

**Comment by engram-design** [comment]
Previously, file upload fields had no email content, as the assets are added as attachments. But this has been changed to show the URL(s) of the uploaded files as well. See [1.2.23](https://github.com/verbb/formie/releases/tag/1.2.23)

**Comment by mikos** [comment]
@engram-design Is it possible to show the URL of the uploaded file(s) without including attachments? We're dealing with attachments that could be 1GB in size.

**Comment by engram-design** [comment]
You could disable "Attach File Uploads" in the email notification settings?

**Comment by mikos** [comment]
@engram-design Thanks! I'll give it a go!
