### ISSUE TITLE
Campaign Monitor - ConsentToTrack missing

### ISSUE THREAD

**Issue by wolispace** [verbb/formie#1761]
### Question

Is there a specific way of setting the ConsentToTrack for Campaign Monitor integration on a form, or are we supposed to use the Agree field and format it a specific way?

I'm getting the error `“{"Code":-213,"Message":"Please provide a consent to track value."}` but have not found any documentation about how this is to be done.  Maybe different wording is used in the Formie documentation, or I just missed it.

Thanks

**Comment by engram-design** [comment]
What version of Formie are you on? We did add "Consent to Track" in https://github.com/verbb/formie/commit/8b5b27745c517c57e1010921d91b6987bf559280 for Formie [2.0.38](https://github.com/verbb/formie/releases/tag/2.0.38)

<img width="1053" alt="image" src="https://github.com/verbb/formie/assets/1221575/0bf8a139-804f-4388-82b1-3be4454cb193">

**Comment by wolispace** [comment]
Ah.. the 'Consent To Track' etc.. fields did not show until I hit that little 'refresh/reload' icon.

Thanks
