### ISSUE TITLE
Paragraphs are stripped from success message HTML

### ISSUE THREAD

**Issue by tremby** [verbb/formie#1766]
### Describe the bug

Success message as entered in the form configuration distinctly shows line breaks and paragraphs.

But how that is output to the application (at least via Graphql) has turned all paragraph breaks into `<br>` tags.

The output then doesn't look as expected.

Example: set up like this
![image](https://github.com/verbb/formie/assets/199635/cacc97a5-13c3-4057-8edf-68412a4b8a51)
I get this output: `p1 line 1<br>p1 line 2<br>p2 line 1`

### Steps to reproduce

1. Have a form with a success message, with newlines and paragraphs
2. See the rendered HTML via Graphql `submitActionMessageHtml`

### Form settings

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

### Craft CMS version

4.8.0

### Plugin version

2.1.5

### Multi-site?

yes

### Additional context

This might also apply to other fields. Error message?

I looked at the source code. It uses the `getHtmlContent` function, which has a `$nl2br` option defaulting to true. It isn't overridden in this case.

If I patch `_getHtmlContent` to include `false` as its third argument for its `getHtmlContent` call, the output is as I'd expect.

It seems to me that either paragraphs shouldn't be allowed/displayed in the editor, or else they should make it through to the frontend unscathed. At the very least a new paragraph should be *two* `<br>` tags, no?

**Comment by engram-design** [comment]
Yeah, so some rich text doesn't allow for paragraph nodes, but the editor we use (Tiptap) enforces at least a paragraph, so we have to strip things out. Things like the description for an Agree field _should_ have paragraph tags stripped out.

But for these more "block" HTML, I agree that they should allow paragraphs. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.6"`.

**Comment by engram-design** [comment]
Fixed in [2.1.7](https://github.com/verbb/formie/releases/tag/2.1.7)
