### ISSUE TITLE
Group - Allow a repeater to be nested

### ISSUE THREAD

**Issue by robwkirby** [verbb/formie#177]
I'm enjoying this plugin! One thing I've found myself needing to do though is nest a repeater field inside a group field to be able to easily style a form with sections/steps. I can achieve what I need with custom CSS classes but it's not really a user friendly solution.

I can see that it works this way to prevent nesting a repeater in another repeater but I think there are times when nesting a repeater in a group, or even a group inside a group might be useful.

**Comment by engram-design** [comment]
I'll just say that I don't think this'll happen until Craft 4. A repeater/group field acts almost exactly the same way as a Matrix field, which itself can't be nested. Once there's a concept of field instances in Craft, I believe this should be accomplished.

**Comment by engram-design** [comment]
Going to close for now, as this'll likely be a Craft 4/5 thing. Will re-open when this kicks off after a major refactor on Formie's end.
