### ISSUE TITLE
Formie payments error:`Key "0" for array with keys "6" does not exist.` when clicking an entry in submissions.

### ISSUE THREAD

**Issue by 0xElectric** [verbb/formie#1770]
### Describe the bug

In form `submissions`, when clicking an entry that has the `payment` field (Stripe payment provider) in its form, it's returning error:

`Key "0" for array with keys "6" does not exist.`

![Screenshot from 2024-03-17 11-27-37](https://github.com/verbb/formie/assets/101079915/bf1de05f-1338-4f40-870c-4dec87020e98)

### Steps to reproduce

1. Setup webhooks endpoint and webhook signing secret
2. Setup stripe credentials, publishable and secret keys
3. Create a form with a `payment field` and use `stripe payment provider`, `Collect User` enabled
4. Render the form in frontend using `{{ craft.formie.renderForm(form) }}`
5. 5 Test payments using test cards https://docs.stripe.com/testing
6. Go to CMS admin -> formie -> submissions -> Click the new submission entry related to the form
7. Error will show

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.8.2

### Plugin version

2.1.6

### Multi-site?

NO

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.6"`.

**Comment by engram-design** [comment]
Fixed in [2.1.7](https://github.com/verbb/formie/releases/tag/2.1.7)
