### ISSUE TITLE
Default error message "Couldn’t save submission due to errors." not translated despited existing translation.

### ISSUE THREAD

**Issue by melissadoyon** [verbb/formie#1771]
### Describe the bug

Since updating form 2.1.3 to 2.1.7, I have noticed that the error message displayed at the top of my forms in not being translated despite the existing translation formie.php file.

### Steps to reproduce

1. Create a form
2. Create a translation file named formie.php inside translations folder (ex. translations/fr/formie.php).
3. Submit form without filling it on a language other than english.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.8.3

### Plugin version

2.1.7

### Multi-site?

No

### Additional context

Other translations seems to work just fine.

**Comment by engram-design** [comment]
One change we did make was adding the support for `<p>` HTML tags for the error message. As such, you _may_ need to update your translation string to include the `<p>` tag.

So you might have had:

```php
'Submission saved.' => 'Submission saved override.' 
```

Which would be:

```php
'<p>Submission saved.</p>' => '<p>Submission saved override.</p>' 
```

Sorry about that, I didn't realise this would be a breaking change. See https://github.com/verbb/formie/issues/1766

**Comment by melissadoyon** [comment]
Thanks for the clarification. I tested with the `<p>` tag and it works.
