### ISSUE TITLE
Formie language different from backend.

### ISSUE THREAD

**Issue by yingban** [verbb/formie#1772]
### Describe the bug

Hi,
I just updated to 2.1.7.

I have the website in de-CH and the back end in en, the craft back end is in english, but Formie is in german. So I guess it takes the website language instead the back end language.

### Steps to reproduce

1. Setup a website with language as "de-CH"
2. Setup user panel language to "en"

### Form settings

- Multi-page form: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.7.4

### Plugin version

2.1.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.7"`.

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/formie/releases/tag/2.1.8)
