### ISSUE TITLE
Forms with summary fields cannot be saved because of handle error

### ISSUE THREAD

**Issue by yingban** [verbb/formie#1773]
### Describe the bug

Hi,

I just updated to Formie 2.1.7.

The forms including summary fields, cannot be saved anymore because a handle issue.

### Steps to reproduce

1. Update to Formie 2.1.7
2. Try to re save a form including a summary field

### Form settings

- Multi-page form: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.7.4

### Plugin version

2.1.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
What's the exact error you receive? I can seemingly save summary fields okay on my end.

**Comment by yingban** [comment]
`Unable to save form: [[{"handle":["«Zusammenfassung-Handle6d04223dd8ff35fc697c8ed489e48b60» ist kein gültiger Kurzname."]}],{"handle":["«Zusammenfassung-Handle6d04223dd8ff35fc697c8ed489e48b60» ist kein gültiger Kurzname."]},{"fields.Zusammenfassung-Handle6d04223dd8ff35fc697c8ed489e48b60":[{"handle":["«Zusammenfassung-Handle6d04223dd8ff35fc697c8ed489e48b60» ist kein gültiger Kurzname."]}]}].`

it seems to be solved with your dev version.
So it guess it was a translation issue.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.7"`.

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/formie/releases/tag/2.1.8)
