### ISSUE TITLE
Saving form permissions issue

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#178]
**Description**
When saving a form when logged in as a user that does not have permission to view, for example, the appearance or behaviour tab, the settings from those tabs are lost and reset back to the default settings.

**Steps to reproduce**
1. Create a form as an admin
2. Change some appearance or behavior settings
3. Log in as a user with no appearance or behaviour permissions
4. Save the form

**Comment by engram-design** [comment]
Fixed in [1.2.23](https://github.com/verbb/formie/releases/tag/1.2.23)
