### ISSUE TITLE
Custom CRM integration issues upgrading from Formie 2 to 3

### ISSUE THREAD

**Issue by steverowling** [verbb/formie#1787]
### Describe the bug

I have created a custom CRM integration for Raiser's Edge NXT (which uses the SKY API from Blackbaud: https://www.blackbaud.co.uk/training-support/support/howto).

I had it working on Formie 2, but now I'm attempting to upgrade to Formie 3, I can't get it working.

The CRM integration uses OAuth2 to authenticate with the SKY API from Blackbaud and I think I must be missing some configuration steps somewhere. It seems to have got a lot more complicated than it was with Formie 2 and the docs are a little sparse on how to convert a working integration on Formie 2 to Formie 3, especially moving the OAuth2 elements to use the Auth module.

I've looked through the providers in the Auth module, but none of them appear to give me any clues as to what I've done wrong. One thing I am struggling with is with the `getResourceOwnerDetailsUrl()` and `createResourceOwner()` functions. With the working Formie 2 implementation, I didn't need to specify these and the integration worked and connected to the API successfully and I could make API queries to different endpoints. However, now I can't even get an initial connection to work. In fact, I never see the connect or refresh button on the integration because the error shown below is thrown as soon as the page reloads after I save the integration.

The integration does appear to save in the database, and to my eyes, looks correct, but something is obviously amiss somewhere.

It would be great to have a guide on how to convert a Formie 2 OAuth2 custom integration to Formie 3, using the Auth module for the OAuth elements.

### Steps to reproduce

1. Go to Formie > Settings > Integrations (CRM) and click New Integration.
2. Select custom integration (Raiser's Edge NXT), fill out setting fields and click save.
3. The following error occurs:

Error: Call to a member function getTokens() on null in /var/www/html/vendor/verbb/formie/src/base/Integration.php:437
Stack trace:
#0 /var/www/html/vendor/verbb/formie/src/base/Integration.php(360): verbb\formie\base\Integration->getToken()
#1 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): verbb\formie\base\Integration->getIsConnected()
#2 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(modules\renxt\integrations\RaisersEdgeCrm), 'getIsConnected', Array, 'method', false, false)
#3 /var/www/html/storage/runtime/compiled_templates/6b/6bab8dde24d6ed295b049ece98bed6b4.php(69): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(modules\renxt\integrations\RaisersEdgeCrm), 'getIsConnected', Array, 'method')
#4 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a1338e6e1ed8b01eece7f7fe4886876d->doDisplay(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#7 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#8 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('formie/settings...', Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('formie/settings...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('formie/settings...', Array, 'cp')
#12 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#13 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#14 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#16 /var/www/html/web/index.php(12): yii\base\Application->run()
#17 {main}

### Form settings

None, this is just attempting to add a custom CRM integration which uses OAuth2 to authenticate.

### Craft CMS version

5.0.0-beta.11

### Plugin version

3.0.0-beta.4

### Multi-site?

No

**Comment by engram-design** [comment]
So there are major changes to OAuth integrations in [Formie 3](https://github.com/verbb/formie/blob/craft-5/docs/get-started/upgrading-from-v2.md#integrations) as we've switched to the [Auth Module](https://verbb.io/packages/auth) to handle things. Sorry that the docs are a bit sparse at the moment while we're in beta.

Would you like to send your custom integration to `support@verbb.io` and we can update it for you? We might also use this as the basis for a user guide to explain things in greater detail than a changelog.

**Comment by steverowling** [comment]
> So there are major changes to OAuth integrations in [Formie 3](https://github.com/verbb/formie/blob/craft-5/docs/get-started/upgrading-from-v2.md#integrations) as we've switched to the [Auth Module](https://verbb.io/packages/auth) to handle things. Sorry that the docs are a bit sparse at the moment while we're in beta.
> 
> Would you like to send your custom integration to `support@verbb.io` and we can update it for you? We might also use this as the basis for a user guide to explain things in greater detail than a changelog.

Hi Josh, that would be great, thanks! Do you just need the custom integration class?

**Comment by engram-design** [comment]
Yep, just any classes you were using (both for Formie 2, and if you've had a crack at Formie 3, that's handy too). I'm not sure if you started creating an Auth module client/provider, but include that too.

**Comment by engram-design** [comment]
For future reference (and this might turn into a user guide), have a look at the example integration here - https://github.com/verbb/example-formie-oauth-integration
