### ISSUE TITLE
Error after updating from 1.2.21

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#179]
**Description**
I get the following error everywhere in the control panel after the most recent updates to 1.2.22 or 1.2.23

yii\base\InvalidCallException: Setting read-only property: verbb\formie\fields\formfields\Agree::descriptionHtml in /path/to/project/vendor/yiisoft/yii2/base/Component.php:206
Stack trace:
#0 /path/to/project/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('descriptionHtml', 'Business')
#1 /path/to/project/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\formie\fields\formfields\Agree), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /path/to/project/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array)
#4 /path/to/project/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('verbb\\formie\\fi...', Array, Array)
#5 /path/to/project/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\formie\\fi...', Array, Array)
#6 /path/to/project/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#7 /path/to/project/vendor/craftcms/cms/src/services/Fields.php(561): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#8 /path/to/project/vendor/craftcms/cms/src/services/Fields.php(586): craft\services\Fields->createField(Array)
#9 /path/to/project/vendor/craftcms/cms/src/services/Fields.php(615): craft\services\Fields->_fields(NULL)
#10 /path/to/project/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2005): craft\services\Fields->getAllFields()
#11 /path/to/project/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1360): craft\elements\db\ElementQuery->customFields()
#12 /path/to/project/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#13 /path/to/project/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#14 /path/to/project/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#15 /path/to/project/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#16 /path/to/project/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1505): craft\db\Query->one(NULL)
#17 /path/to/project/vendor/craftcms/cms/src/elements/User.php(413): craft\elements\db\ElementQuery->one()
#18 /path/to/project/vendor/yiisoft/yii2/web/User.php(692): craft\elements\User::findIdentity(1)
#19 /path/to/project/vendor/craftcms/cms/src/web/User.php(485): yii\web\User->renewAuthStatus()
#20 /path/to/project/vendor/yiisoft/yii2/web/User.php(194): craft\web\User->renewAuthStatus()
#21 /path/to/project/vendor/craftcms/cms/src/web/User.php(241): yii\web\User->getIdentity()
#22 /path/to/project/vendor/mmikkel/cp-field-inspect/src/CpFieldInspect.php(159): craft\web\User->getIsAdmin()
#23 /path/to/project/vendor/mmikkel/cp-field-inspect/src/CpFieldInspect.php(96): mmikkel\cpfieldinspect\CpFieldInspect->doIt()
#24 [internal function]: mmikkel\cpfieldinspect\CpFieldInspect->mmikkel\cpfieldinspect\{closure}(Object(yii\base\Event))
#25 /path/to/project/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#26 /path/to/project/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#27 /path/to/project/vendor/craftcms/cms/src/services/Plugins.php(270): yii\base\Component->trigger('afterLoadPlugin...')
#28 /path/to/project/vendor/craftcms/cms/src/base/ApplicationTrait.php(1416): craft\services\Plugins->loadPlugins()
#29 /path/to/project/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#30 /path/to/project/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#31 /path/to/project/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#32 [internal function]: yii\base\Application->__construct(Array)
#33 /path/to/project/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array)
#34 /path/to/project/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#35 /path/to/project/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#36 /path/to/project/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#37 /path/to/project/vendor/craftcms/cms/bootstrap/web.php(51): require('/Users/andrew/S...')
#38 /path/to/project/web/index.php(20): require('/Users/andrew/S...')
#39 {main}

**Steps to reproduce**
1. For me, just update from 1.2.21 ...

### Form settings
not applicable

**Additional info**
- Plugin version: Update from 1.2.21
- Craft version: 3.5.13.1
- Multi-site: Yes
**Additional context**

**Comment by engram-design** [comment]
I’m not _quite_ sure how its trying to set “descriptionHtml” as its a calculated attribute for Agree fields. It's possible you updated to 1.2.20 before I pushed the fix in 1.2.21 for this.

Are you able to shoot through the rows in your `fields` database table that match type = `verbb\formie\fields\formfields\Agree`. Specifically, I’m interested in the “settings” column.

I think I know what’s going on, but would like to check your field setup first before pushing a migration.

**Comment by engram-design** [comment]
If you can, can you give [1.2.23.1](https://github.com/verbb/formie/releases/tag/1.2.23.1) a crack? Think that should sort it out.

**Comment by AndrewMac** [comment]
Hot damn, you're fast! ;
Yes, I can indeed check the database ...
But I did give the update to 1.2.23.1 a go, and it's working just fine now.
Would you still like to see the settings?

Cheers, Andrew

**Comment by AndrewMac** [comment]
Oh, and yes. You're right: I think I almost certainly did update to 1.2.20 before 1.2.21 came out

**Comment by engram-design** [comment]
Nah all good, I figured I knew what the issue was! And yep, if you updated in the space between 1.2.20 and 1.2.21 (roughly 24 hours) you'll get this issue. Sorry about that!

**Comment by AndrewMac** [comment]
No problem. I'm really impressed by how quickly you're getting improvements done. I'm moving my forms from Freeform now!

And thanks for the new "User" integration. I noticed it the other day, even though I didn't actually see it in any release notes ;-)

**Comment by engram-design** [comment]
Glad you're enjoying Formie!

No worries, and yeah "Added User element integration." was hidden away at the bottom of the [changelog](https://github.com/verbb/formie/blob/craft-3/CHANGELOG.md#added-2), so easily missed
