### ISSUE TITLE
Unable to find the template “formie/integrations/address-providers/google/_settings”.

### ISSUE THREAD

**Issue by RyanRoberts** [verbb/formie#1790]
### Describe the bug

I'm getting this every time I try to add an Address integration, all the other integrations are working.

https://github.com/verbb/formie/assets/108874/32fc48ed-31ec-486e-b588-cf83db3d8c0f

### Steps to reproduce

See the video.

### Form settings

I don't think this is applicable. 

### Craft CMS version

4.8.6

### Plugin version

dev-craft-4 as 2.1.7

### Multi-site?

No

### Additional context

I fully accept this could be something I've done, somehow 🫠

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.7"`.

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/formie/releases/tag/2.1.8)
