### ISSUE TITLE
[5.x] Email Notifications for Repeater field: No recipient email address found.

### ISSUE THREAD

**Issue by ArnoMoqo** [verbb/formie#1795]
### Describe the bug

When inserting a repeater field with an email field inside you have the option to select this field in the email notification. Whenever we do thad we get the following error in the email notification: `Notification email error. No recipient email address found.`

<img width="1040" alt="Scherm­afbeelding 2024-03-29 om 12 07 00" src="https://github.com/verbb/formie/assets/117268595/1bbbc7a6-1647-462f-857f-e3f42c02a519">
<img width="856" alt="Scherm­afbeelding 2024-03-29 om 12 07 08" src="https://github.com/verbb/formie/assets/117268595/3a81ecb0-1d65-4d88-a610-877fa7a4311d">
<img width="858" alt="Scherm­afbeelding 2024-03-29 om 12 07 14" src="https://github.com/verbb/formie/assets/117268595/662989ac-3f3f-4fc6-aa62-f45da6490580">

### Steps to reproduce

1. Create a repeater field with an email inside the form
2. Use this email field as email notification
3. See the error appear

### Form settings

- Multi-page form: No
- Custom Form Templates: No

### Craft CMS version

5.0.0

### Plugin version

3.0.0-beta.5

### Multi-site?

No

### Additional context

Clean Craft 5 and Formie install

**Comment by engram-design** [comment]
Ah, now that's actually incorrect behaviour at the moment. You shouldn't be able to pick Repeater values like this. It's a feature request on our list though - https://github.com/verbb/formie/issues/1728 and https://github.com/verbb/formie/issues/1255

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.5"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.6](https://github.com/verbb/formie/releases/tag/3.0.0-beta.6)
