### ISSUE TITLE
[5.x] GraphQL field types are missing fields 

### ISSUE THREAD

**Issue by benfeather** [verbb/formie#1798]
### Describe the bug

After upgrading to Craft 5, I started getting GQL errors when fetching Formie fields. 
It looks like the field types are missing properties, as an example here is the address field type:

![CleanShot 2024-04-03 at 09 26 19@2x](https://github.com/verbb/formie/assets/43571410/c7bd3e1f-9a43-4b62-a4c2-9d09e29c4cef)
![CleanShot 2024-04-03 at 09 26 42@2x](https://github.com/verbb/formie/assets/43571410/292922ab-3ebd-4ddb-bf9f-5dc98188d776)
![CleanShot 2024-04-03 at 09 27 21@2x](https://github.com/verbb/formie/assets/43571410/fa748dd5-f57d-4cfc-b49c-bf9060ee42c0)

As per the docs, the address field type should include the "autocompleteLabel" prop.

![CleanShot 2024-04-03 at 09 28 16@2x](https://github.com/verbb/formie/assets/43571410/5c31107e-9854-4adf-b435-2e2ddf04768c)

### Steps to reproduce

1. Spin up a craft install in DDEV
2. Install Formie
3. Request the form fields using GQL

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.0.0

### Plugin version

dev-craft-5 as 3.0.0-beta.4

### Multi-site?

Yes

### Additional context

I'm using the dev-craft-5 version as it fixes the stripe dep issue with the official stripe plugin.

**Comment by engram-design** [comment]
That's correct, sub-fields have been radically revamped in Formie 3. Have a read through the [upgrade](https://github.com/verbb/formie/blob/craft-5/docs/get-started/upgrading-from-v2.md#sub-fields-1) docs
