### ISSUE TITLE
Email Preview: variable "All non empty field" never shows the field "name"

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1799]
### Describe the bug

I discovered an issue with the mail variable `All non empty fields`
In the email preview, the field type `Name` is never displayed if the option `Use multiple name fields` is activated.

### Steps to reproduce

1. Create a new form
2. Add a field type `name`
3. Enabled the option `Use Multiple Name Fields` 
4. Add a new email notification 
5. Add to the email content the variable `All non Empty Fields`
6. Refresh the email preview
7. the field is never shown, even when the field is mandatory

### Form settings

- Multi-page form: No

### Craft CMS version

4.8.6

### Plugin version

2.1.9

### Multi-site?

no

**Comment by engram-design** [comment]
I believe this affects only the preview, as at least my testing shows that real submissions work correctly.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.9"`.

**Comment by engram-design** [comment]
Fixed in [2.1.10](https://github.com/verbb/formie/releases/tag/2.1.10)
