### ISSUE TITLE
Option 'Collect IP Addresses' does not work

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#18]
### Description
Even though I checked the option 'Collect IP Addresses' no IP Address is displayed in submission. 

### Steps to reproduce
1. Active option 'Collect IP Addresses' in form settings
2. Submit form in FE
3. Display submission in CP

### Expected 
IP Address displayed in right panel

### Actual 
No IP Address displayed in right panel

### Hint
There does not seem to be a column for the IP address in the 'craft_formie_submissions' DB table

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Additional info
- Plugin version: 1.0.4
- Craft version: 3.4.24

**Comment by engram-design** [comment]
Looks like this got left behind with some last minute changes before release, sorry! Fixed in [1.0.5](https://github.com/verbb/formie/releases/tag/1.0.5)
