### ISSUE TITLE
Adding "after" param to submission query results in Twig Runtime Error

### ISSUE THREAD

**Issue by AmandaLutzTO** [verbb/formie#180]
Added "after" param to submission query as described in [documentation](https://verbb.io/craft-plugins/formie/docs/getting-elements/submission-queries#after) and resulted in Twig Runtime Error:
Calling unknown method: verbb\formie\elements\db\SubmissionQuery::after()

**Steps to reproduce**
1. Add "after" param to submission query

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.21
- Craft version: 3.4.16
- Multi-site: No

**Additional context**
Same issue with "before" param
Param "dateCreated" works as expected

**Comment by engram-design** [comment]
Whoops, sorry the docs are wrong here. You should use `dateCreated`.
