### ISSUE TITLE
Craft 5: Changes to `Form Templates` for form are not reflect in CP dropdown

### ISSUE THREAD

**Issue by cmalven** [verbb/formie#1800]
### Describe the bug

When I change `Form Templates` option under `Appearance` for a form, the template is changed internally, but the next time I view the form, the dropdown is set to the default value of `Default Form Template`. This means that if I make any other changes to the form and save without also updating this dropdown, the template will be reset.

### Steps to reproduce

1. Create a custom form template
2. Create a new form
3. Assign the custom form template to the `Form Templates` dropdown for the form and save
4. Refresh the form page

Expected:
`Form Templates` reflects the saved custom template

Actual:
`Form Templates` reverts to default value

https://github.com/verbb/formie/assets/610118/d4b6c1ba-a0e5-4fcf-9f5e-8c06694ea05c

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5.0.0

### Plugin version

3.0.0-beta.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.5"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.6](https://github.com/verbb/formie/releases/tag/3.0.0-beta.6)
