### ISSUE TITLE
Craft 5: Can't update "Action on Submit" or "Redirect Entry" for form

### ISSUE THREAD

**Issue by cmalven** [verbb/formie#1801]
### Describe the bug

After initially saving my form, I am unable to change the `Action on Submit` or `Redirect Entry` values for the form. Clicking on any element of either of these inputs does nothing.

### Steps to reproduce

1. Create a new form
2. Set the initial values for `Action on Submit` to `Redirect to entry` and set the entry to any entry
3. Save and refresh the form and navigate to `Behavior` tab
4. Interaction with `Action on Submit` and `Redirect Entry` fields have no effect

https://github.com/verbb/formie/assets/610118/124ac6a7-ead6-4e2e-ac6b-06db170ef18a

### Form settings

- Multi-page form: no
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.0.0

### Plugin version

3.0.0-beta.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.5"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.6](https://github.com/verbb/formie/releases/tag/3.0.0-beta.6)
