### ISSUE TITLE
Field Heading absent in Mail with variable "All Non Empty Fields"

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1807]
### Describe the bug

The field heading is absent in the email with the variable `All Non Empty Fields`, even though in the email preview the field is present.

The field has the properties `IsCosmetic` set to true and `hasContentColumn` to false.

### Steps to reproduce

1. Create a new form
2. Add a field Heading
3. Enable Include in Email Notifications
4. Create a new notification with the variable `All Non Empty Fields`
5. Generate the email preview
6. The Heading is visible
7. Send the mail, the Heading is not present 

### Form settings

- Multi-page form: No

### Craft CMS version

4.8.6

### Plugin version

2.1.9

**Comment by engram-design** [comment]
This is by design, as Heading fields and other cosmetic fields don't technically have a value, so their values are considered empty here. You're unable to use `All Fields` or `All Visible Fields`?

**Comment by Megafry** [comment]
Thanks for the reply, I was able to use `All Visible Fields`.
Still, there is a discrepancy between the email preview and the mail with the variable `All Non Empty Fields`.
but this is not an issue worth fixing.

Best regards
