### ISSUE TITLE
Backend: CRM Setting Error

### ISSUE THREAD

**Issue by Mchei** [verbb/formie#1809]
### Describe the bug

I was trying to config a CRM Integration on the Forime Backend, and a "PHP Compile Error Shows up"

PHP Compile Error – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Declaration of verbb\formie\integrations\crm\Agile::getClassHandle() must be compatible with verbb\formie\base\Integration::getClassHandle(): string

For CraftCMS 5, have tried reinstall formie. 

### Steps to reproduce

Formie > Settings > CRM > New Integration 

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5.0

### Plugin version

3.0.0-beta.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.5"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.6](https://github.com/verbb/formie/releases/tag/3.0.0-beta.6)
