### ISSUE TITLE
Getting JS Error this.getPlaceholders is not a function after update

### ISSUE THREAD

**Issue by lennonpuype** [verbb/formie#1811]
### Describe the bug

During a simple render by doing `{{ craft.formie.renderForm(form) }}` I get a Javascript error: Uncaught TypeError: this.getPlaceholders is not a function.

![Screenshot 2024-04-10 at 09 54 54](https://github.com/verbb/formie/assets/30866096/5365aa86-05d8-4690-a5ed-cd85a7e80b64)

Regarding to the files where the errors are happening, I found this is because of the Duplicate and Javascript Captcha of the form. When I disable these they I don't get the error. For now I have just disabled them, but this is of course e temporary solution for now.

### Steps to reproduce

1. Create a form
2. Make sure the Captcha's Duplicate & Javascript are enabled in the integrations tab
3. Render the form by using `{{ craft.formie.renderForm(form) }}`

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.0.3

### Plugin version

3.0.0-beta.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.6"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.7](https://github.com/verbb/formie/releases/tag/3.0.0-beta.7)
