### ISSUE TITLE
Missing field showing up in interface when language is set to German

### ISSUE THREAD

**Issue by MoritzLost** [verbb/formie#1815]
### Describe the bug

I'm seeing an issue when I set my account language to German. The form editor shows a new field group with a field _Fehlendes Feld_  (German for _Missing field_) in the interface. This field is not visible when the language is set to English.

![formie-sidebar-english](https://github.com/verbb/formie/assets/10146880/e0dbf0d0-26e8-4c2e-8496-be160b8e02b9)
![formie-sidebar-german](https://github.com/verbb/formie/assets/10146880/a3049f8d-38a9-433a-86c5-b689ee7e465e)

As a sidenote, a couple of strings in the interface are not translated, even though the translations do exist in `src/translations/de/formie.php`. I guess those just aren't marked as translatable. Might be worth it to make sure all interface strings are translatable now that the core has German translations.

### Steps to reproduce

1. Set the account language to German.
2. Open the form editor.

### Form settings

- Multi-page form: No

### Craft CMS version

4.8.8

### Plugin version

2.1.10

### Multi-site?

No

**Comment by engram-design** [comment]
Both items fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.10"`.

**Comment by MoritzLost** [comment]
@engram-design Quick like lightning ⚡Thanks!

**Comment by engram-design** [comment]
Fixed in [2.1.11](https://github.com/verbb/formie/releases/tag/2.1.11)
