### ISSUE TITLE
Cannot preview or send test email for notifications for emails containing an "address" field

### ISSUE THREAD

**Issue by amphibian** [verbb/formie#1818]
### Describe the bug

When adding an email notification, I cannot preview the email or send a test email due to an error:

```
Notification email parse error for Subject: New membership submission from {field:fullName}”.
Template error: “Calling unknown method: verbb\formie\fields\Address::autocompleteEnabled()” 
/var/www/html/craftcms/vendor/verbb/formie/src/templates/_special/email-template/fields/address.html:6
```

I do have a regular address field in my form template, and am using "all non-empty fields" as my email contents..

### Steps to reproduce

1. Create an email notification for a form which contains an address field.
2. Try to preview that notification.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.0.4

### Plugin version

3.0.0-beta.5

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.6](https://github.com/verbb/formie/releases/tag/3.0.0-beta.6)
