### ISSUE TITLE
Only display forms that the user can actually edit

### ISSUE THREAD

**Issue by hw-01010** [verbb/formie#1820]
### What are you trying to do?

I want to create a system in which each user can only see and edit the forms they created.

Currently, when I create a form with one user, it also shows up for every other user, even if they don't have edit permissions. When I open the form, it throws a 403 error - which is expected but not really user-friendly.

For the user who gets the error, I use the following settings:
![image](https://github.com/verbb/formie/assets/112609658/76e40221-35df-448e-bb9d-9d258ab1f8a6)

### What's your proposed solution?

It would be nice to have the same settings/functionalities as for Entries.
![image](https://github.com/verbb/formie/assets/112609658/3b6d1491-bdfa-4cc6-899a-fef6e95cfcdd)

But it would also suffice to just not display the forms which the user can't edit.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.10"`.

**Comment by engram-design** [comment]
Fixed in [2.1.11](https://github.com/verbb/formie/releases/tag/2.1.11)
