### ISSUE TITLE
Field styling issue: Height of calendar field vs. input field is not equal

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1821]
### Describe the bug

I have found a small, non-critical styling issue. The calendar field has a slightly bigger height than the plain text input fields when shown in the frontend. I haven't used any templates but embedded the default Formie form.

<img width="1034" alt="Screenshot 2024-04-09 at 20 31 04" src="https://github.com/verbb/formie/assets/4956295/3b8a22a7-4471-4923-9333-a94f5f3061f7">

### Steps to reproduce

1. Add both field types to a form
2. Embed the form into a template
3. Check the form fields in the browser

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.0.4

### Plugin version

3.0.0-beta.5

### Multi-site?

Yes

**Comment by engram-design** [comment]
Looks like this is a Chrome/Webkit browser bug, with no immediate fix other than setting fixed heights on inputs, which I'm not a massive fan. Will look into it!

**Comment by philipschilling** [comment]
Yes, I used Chrome. Sorry for not mentioning it ;-)

**Comment by philipschilling** [comment]
On Apple iPhone 12 Pro with iOS 12.4.1 in Safari & Chrome browser the date field is not rendered correctly:
![IMG_3766](https://github.com/verbb/formie/assets/4956295/2f489c03-4501-4202-b859-2ccf28fea01e)

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)
