### ISSUE TITLE
Date field label not showing

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#1825]
### Describe the bug

I have a weird one, when you have a date field with the following configuration, the label does not show:
1. date disabled
2. time enabled
3. flatpickr disabled

### Steps to reproduce

1. Add a date field
2. Disable date
3. Enable time
4. Disable flatpickr

### Craft CMS version

4.8.9

### Plugin version

2.1.10

### Multi-site?

No

**Comment by engram-design** [comment]
Hey mate, is this related to the theme configs, or just Formie in general?

**Comment by jaydensmith** [comment]
@engram-design I removed the theme config so I'm pretty sure it's not that. The label text doesn't appear in the HTML.

<img width="293" alt="Screenshot 2024-04-14 at 7 24 56 PM" src="https://github.com/verbb/formie-theme-configs/assets/16344913/0d1bae41-f535-46e2-97e7-65daa87fa102">

**Comment by jaydensmith** [comment]
@engram-design sorry I realised I posted this on the wrong repo

**Comment by engram-design** [comment]
So this is a time-only field? Did you enter a value for the "Time Label"? That seems to be working for me. Here's some combos just to verify, all are without Flatpickr:

<img width="815" alt="image" src="https://github.com/verbb/formie/assets/1221575/beb42909-c027-4e1f-b9e7-abeee54628e2">

**Comment by jaydensmith** [comment]
@engram-design ah I didn't see the separate label field, thanks.
