### ISSUE TITLE
The advanced field "Headline" is almost not visible in form builder in the backend

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1826]
### Describe the bug

The advanced field "Headline" is almost not visible in form builder in the backend:
<img width="1180" alt="Screenshot 2024-04-15 at 12 30 40" src="https://github.com/verbb/formie/assets/4956295/470de999-09f5-4023-9dac-a854ca481d66">

In my opinion the Heading Text shall be shown in the form builder and the headline should have a min-height.

### Steps to reproduce

1. Open a form
2. Add an advanced field of the type "headline"
3. Add text to the headline field and save

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.0.4

### Plugin version

3.0.0-beta.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.7"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.8](https://github.com/verbb/formie/releases/tag/3.0.0-beta.8)
