### ISSUE TITLE
Add mapping for salutation title field in Mailchimp integration

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1827]
### What are you trying to do?

In German language, we can use formal (Dear Mr. Maier) vs. informal (Dear Tobias) salutation. To send out Mailchimp newsletter with formal salutation, I need to import the salutation title which is currently not possible when setting up a form.

<img width="1253" alt="Screenshot 2024-04-15 at 15 46 19" src="https://github.com/verbb/formie/assets/4956295/2d3a98bc-adde-4c74-98d8-c3edca1df967">

### What's your proposed solution?

Either add another mapping for a salutation title field or allow the option to add any extra mappings for custom fields. For me this is not critical but nice-to-have.

**Comment by engram-design** [comment]
So these fields are pulled in from Mailchimp's [merge fields](https://mailchimp.com/developer/marketing/docs/merge-fields/) endpoint, so theoretically if you have a custom field for salutation, it should appear there. Similar to First Name, Last Name and Phone Number.

Can you confirm if you have such a field setup?

**Comment by philipschilling** [comment]
No, I don't have this field setup in Mailchimp yet. I have only the default fields but it is strange that the default fields _address_ and _birthday_ haven't been imported (Though I don't need them!).

So, to sync the fields, I would need to delete the integration and just set it up again?

<img width="1065" alt="Screenshot 2024-04-16 at 08 17 35" src="https://github.com/verbb/formie/assets/4956295/89432bda-4d02-412a-87a7-d7c2882e4c60">

**Comment by engram-design** [comment]
Address and Birthday aren't [supported fields](https://github.com/verbb/formie/blob/4c169642bf0ff72f0680b38ddd8424ea7a263e31/src/integrations/emailmarketing/Mailchimp.php#L310-L322) which is why they don't show up for mapping.

You don't need to delete the integration. Simply add the Salutation custom field in Mailchimp, head back to the Formie form's integrations tab and click the refresh button next to the list. New fields should appear then.

**Comment by philipschilling** [comment]
It works ;-). I thought that the refresh icon would only update the name of the audience but good to know that it also updates the fields.
