### ISSUE TITLE
Manage all forms permission not working anymore

### ISSUE THREAD

**Issue by mihob** [verbb/formie#1830]
### Describe the bug

It looks like the "Manage all forms" permission is no longer working.

If I assign a group with this permission to a user, only forms that he has created himself are displayed.

Interestingly, the number of forms in the index is displayed correctly:

<img width="910" alt="image" src="https://github.com/verbb/formie/assets/48485580/bc0e825f-e2db-49a9-8496-7412ff6db77e">

### Steps to reproduce

1.  Create a group with the Manage all forms permission
2. Assign the group to a user

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.8.9

### Plugin version

2.1.11

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.11"`.

**Comment by engram-design** [comment]
Fixed in [2.1.12](https://github.com/verbb/formie/releases/tag/2.1.12)
