### ISSUE TITLE
Adding sort order to hubspot integration

### ISSUE THREAD

**Issue by joepagan** [verbb/formie#1831]
### What are you trying to do?

View a list of hubspot forms alphabetically

### What's your proposed solution?

Add an option to sort

### Additional context

Client of ours using formie has 325 forms in their account and it's quite hard for them to identify which are the correct ones.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.11"`.

**Comment by joepagan** [comment]
Thanks so much!

**Comment by engram-design** [comment]
Fixed in [2.1.12](https://github.com/verbb/formie/releases/tag/2.1.12)
