### ISSUE TITLE
'Submission UID' not shown in preview

### ISSUE THREAD

**Issue by WilliamDEdwards** [verbb/formie#1833]
### Describe the bug

When the 'Submission UID' variable is used in a notification's 'Email Content', it is not shown under the 'Preview' tab.

I would expect it to be faked.

### Steps to reproduce

1. Create email notification with email content containing 'Submission UID'
2. Look under 'Preview' tab

### Form settings

Not relevant in this case, because we're only checking the preview.

### Craft CMS version

4.8.9

### Plugin version

2.1.11

### Multi-site?

No

**Comment by WilliamDEdwards** [comment]
I now see this is the case with more variables, such as 'User IP Address' and 'User ID'.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.11"`.

**Comment by engram-design** [comment]
Fixed in [2.1.12](https://github.com/verbb/formie/releases/tag/2.1.12)

**Comment by WilliamDEdwards** [comment]
@engram-design Thank you for the extremely fast fix.
