### ISSUE TITLE
Missing German translations in form editor

### ISSUE THREAD

**Issue by MoritzLost** [verbb/formie#1836]
### Describe the bug

Thanks for the last update, the German interface looks much better already! I still found a couple of missing translations. Screenshots below. Not sure if the translations still need to be marked as translatable, or if the German translations are just missing. Happy to supply the missing translations in case it's the latter.

![Screenshot 2024-04-17 at 15 32 30](https://github.com/verbb/formie/assets/10146880/d2de0423-49c7-479b-8125-db62ca385618)

- Edit Pages
- Page Label
- The label for this page
- Whether to enable conditional logic to control how this page is shown.

 ![Screenshot 2024-04-17 at 15 33 12](https://github.com/verbb/formie/assets/10146880/39467aba-4530-45e1-a9c1-caa482602ed0)

- Edit Notification
- Email Preview
- The example below shows a preview of this email notification.

![Screenshot 2024-04-17 at 15 33 30](https://github.com/verbb/formie/assets/10146880/61a35fc2-8560-42a9-9e8f-f20165babd14)

- I want to [] this notification if [] of the following rules match.
- Not Send
- All
- Any

### Steps to reproduce

1. Set the account language to German

### Form settings

N/A

### Craft CMS version

4.8.9

### Plugin version

2.1.11

**Comment by engram-design** [comment]
Looks like these translations are missing from the file. Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.11"`.

**Comment by engram-design** [comment]
Updated in [2.1.12](https://github.com/verbb/formie/releases/tag/2.1.12)

**Comment by MoritzLost** [comment]
@engram-design Thanks, I'm working on a PR to add the German translations for those strings as well.
