### ISSUE TITLE
Flatpickr triggers a full-page validation after date selection

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1837]
### Describe the bug

My customer noticed the following issue:
After selecting a date via Flatpickr, all fields from the current page get validated, this should not happen.
I added an export of my form to reproduce the issue.

Possible source of the issue: inputHandler function in bouncer.js

### Steps to reproduce

1. Create a new form with 2 pages
2. Enabled "Validate When Typing" 
3. Set "Submission Method" to Ajax
4. On page 2, add a Date and text field
5. Make all fields mandatory
6. In the frontend go to page 2
7. Update the date field with flatpickr
8. All mandatory fields are now validated.

Or use this export:
[formie-export.json](https://github.com/verbb/formie/files/15024631/formie-formbug-251e3771-ac06-4050-bfb2-fcb3e3eb278f.json)

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.8

### Plugin version

2.1.12

### Multi-site?

no

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.12"`.

**Comment by engram-design** [comment]
Fixed in [2.1.13](https://github.com/verbb/formie/releases/tag/2.1.13)
