### ISSUE TITLE
Advanced field "Headline" shown twice in form submissions

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1839]
### Describe the bug

When I use the advanced element "headline" in a form, the headline is shown twice in a form submission:
<img width="1032" alt="Screenshot 2024-04-20 at 15 03 52" src="https://github.com/verbb/formie/assets/4956295/c54b7780-6e73-4d82-b4d5-46b6e11f20f3">

In the notification email the headline is now shown at all and I am not sure, if it is a bug or shouldn't be shown there.

### Steps to reproduce

1. Add to a form the advanced field "headline"
2. Send a form submission
3. Open the submission in the Formie control panel where the headlines are shown twice (see screenshot)

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.0.4

### Plugin version

3.0.0-beta.8

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.8"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.9](https://github.com/verbb/formie/releases/tag/3.0.0-beta.9)
