### ISSUE TITLE
Error on formie update since version 1.2.22 (15.10.2020)

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#184]
**Description**
When updating formie since version 1.2.22, I get critical error and update fails. Then I need to revert composer from git. Regarding the response from craft, this seems to be an issue with formie.

-----------------------------------------------------------

Stav: Internal Server Error

Reakce: <pre>Exception &#039;yii\base\InvalidCallException&#039; with message &#039;Setting read-only property: verbb\formie\fields\formfields\Agree::descriptionHtml&#039; 

in /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/Component.php:206

Stack trace:
#0 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component-&gt;__set(&#039;descriptionHtml&#039;, &#039;Bitte kontaktie...&#039;)
#1 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\formie\fields\formfields\Agree), Array)
#2 [internal function]: yii\base\BaseObject-&gt;__construct(Array)
#3 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass-&gt;newInstanceArgs(Array)
#4 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container-&gt;build(&#039;verbb\\formie\\fi...&#039;, Array, Array)
#5 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get(&#039;verbb\\formie\\fi...&#039;, Array, Array)
#6 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#7 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/services/Fields.php(561): craft\helpers\Component::createComponent(Array, &#039;craft\\base\\Fiel...&#039;)
#8 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/services/Fields.php(586): craft\services\Fields-&gt;createField(Array)
#9 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/services/Fields.php(615): craft\services\Fields-&gt;_fields(NULL)
#10 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2005): craft\services\Fields-&gt;getAllFields()
#11 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1360): craft\elements\db\ElementQuery-&gt;customFields()
#12 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery-&gt;prepare(Object(craft\db\mysql\QueryBuilder))
#13 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder-&gt;build(Object(craft\elements\db\UserQuery))
#14 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query-&gt;createCommand(Object(craft\db\Connection))
#15 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query-&gt;one(NULL)
#16 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1505): craft\db\Query-&gt;one(NULL)
#17 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/elements/User.php(413): craft\elements\db\ElementQuery-&gt;one()
#18 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/web/User.php(692): craft\elements\User::findIdentity(1)
#19 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/web/User.php(485): yii\web\User-&gt;renewAuthStatus()
#20 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/web/User.php(194): craft\web\User-&gt;renewAuthStatus()
#21 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/web/User.php(372): yii\web\User-&gt;getIdentity()
#22 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User-&gt;getId()
#23 /Users/myaccount/websites/thiswebsite/vendor/mmikkel/child-me/src/ChildMe.php(91): yii\base\Component-&gt;__get(&#039;id&#039;)
#24 /Users/myaccount/websites/thiswebsite/vendor/mmikkel/child-me/src/ChildMe.php(69): mmikkel\childme\ChildMe-&gt;doIt()
#25 [internal function]: mmikkel\childme\ChildMe-&gt;mmikkel\childme\{closure}(Object(yii\base\Event))
#26 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#27 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger(&#039;craft\\services\\...&#039;, &#039;afterLoadPlugin...&#039;, Object(yii\base\Event))
#28 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/services/Plugins.php(270): yii\base\Component-&gt;trigger(&#039;afterLoadPlugin...&#039;)
#29 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/base/ApplicationTrait.php(1416): craft\services\Plugins-&gt;loadPlugins()
#30 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application-&gt;_postInit()
#31 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#32 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct(Array)
#33 [internal function]: yii\base\Application-&gt;__construct(Array)
#34 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass-&gt;newInstanceArgs(Array)
#35 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container-&gt;build(&#039;craft\\web\\Appli...&#039;, Array, Array)
#36 /Users/myaccount/websites/thiswebsite/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get(&#039;craft\\web\\Appli...&#039;, Array, Array)
#37 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#38 /Users/myaccount/websites/thiswebsite/vendor/craftcms/cms/bootstrap/web.php(51): require(&#039;/Users/lexislav...&#039;)
#39 /Users/myaccount/websites/thiswebsite/web/index.php(20): require(&#039;/Users/lexislav...&#039;)
#40 {main}</pre>
`
### Form settings
Please pick from the options below.

**Additional info**
- Plugin version: since 1.2.22
- Craft version: 3.5.X
- Multi-site: Yes

**Comment by engram-design** [comment]
This should've been fixed in [1.2.23.1](https://github.com/verbb/formie/releases/tag/1.2.23.1)

**Comment by lexislav** [comment]
I’am getting the error even with 1.2.23.1

Downgrading verbb/formie (1.2.23.1 => 1.2.21)
Fix the problem…


This is what I see after update on craftinstall.local/admin, before downgrading back to 1.2.21:
Edit: fixed image
![PastedGraphic-1](https://user-images.githubusercontent.com/7147349/96419304-3e4f2a00-11f4-11eb-9894-aa72a7548284.jpg)

**Comment by engram-design** [comment]
The migration added in 1.2.23.1 should go through all your Agree fields and remove the `descriptionHtml` property which shouldn't be in there. Did you run `./craft migrate/all` after the update to 1.2.23.1?

You can manually go through and edit your `fields` database table, looking for any field of type `verbb\\formie\\fields\\formfields\\Agree` and remove that `descriptionHtml` property from the `settings` column as well.

**Comment by lexislav** [comment]
No, I haven't tried to run migrations manually before. And it did the job! Thanks

**Comment by engram-design** [comment]
It depends on how you're updating the plugin. Normally when you update the plugin from composer or the command line, the next time you visit the control panel it'll prompt you to apply any updates. You shouldn't _have_ to run them manually, but glad that did the trick.
