### ISSUE TITLE
[5.x] Cannot load existing fields 

### ISSUE THREAD

**Issue by zsavajji** [verbb/formie#1844]
### Describe the bug

Hi, 
I noticed after creating some fields in a form that when i go load fields from the existing list it goes straight to error. This is maybe related to not having any more field to add except the ones in the current form.

![formie](https://github.com/verbb/formie/assets/6460348/c2657247-0b4e-4a41-beb1-053f2a6ba060)

The stacktrace goes as following:
[formie_error.log](https://github.com/verbb/formie/files/15090591/formie_error.log)

In case of a brand new form, the error does not appear but I am unable to add any existing fields, with no apparent console logs or requests.

![formie2](https://github.com/verbb/formie/assets/6460348/6588613b-efdd-457f-889b-b5c304fc641a)

If I can I help with more cases or tests, please let me know.

### Steps to reproduce

1. Create a form with some fields
2. Save
3. Try to add more existing fields
4. Error is produced

 
1. Create a form with some fields
2. Add another form and try to add some existing fields 
3. No fields added

### Form settings

- Multi-page form: No
- Submission Method: Unrelated, but AJAX
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.0.5

### Plugin version

3.0.0-beta.8

### Multi-site?

Yes

### Additional context

This happens on a development installation of Craft 5.0.0 that's being developed and updated as new versions become available.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.8"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.9](https://github.com/verbb/formie/releases/tag/3.0.0-beta.9)
