### ISSUE TITLE
Add Pardot CRM Integration

### ISSUE THREAD

**Issue by mariovass** [verbb/formie#185]
**What are you trying to do?**
We are looking to integrate Pardot to some of our forms with Formie would be amazing if you can build this integration in. It currently works on FreeForm Pro. 

https://developer.pardot.com/
https://docs.solspace.com/craft/freeform/v3/api-integrations/crm/pardot.html#pardot-crm-api-integration

**Comment by engram-design** [comment]
The only reason we haven't implemented this integration is because I couldn't figure out how to sign up for a Pardot account to test. Seems like we have to setup a meeting with them. We've tested with Salesforce, but it seems like a different system.

**Comment by engram-design** [comment]
If anyone is willing to offer some assistance with an account (just for testing), we'll gladly add support for Pardot!

**Comment by mariovass** [comment]
@engram-design I will check back with my team and see if we can get you API access please pop over your email and we can work on this together

**Comment by engram-design** [comment]
Best to get in touch via `web at verbb.io`

**Comment by karensg** [comment]
I am in contact with Pardot team as well. I can arrange a test account for you, guys, if this is still relevant.

**Comment by engram-design** [comment]
@karensg Certainly still interested in getting this done, as I haven't heard back from @mariovass . Feel free to shoot us an email!

**Comment by karensg** [comment]
Have some issues convincing Pardot about setting up a staging environment.. Still in progress.

**Comment by engram-design** [comment]
Please to announce Pardot has been added in [1.4.25](https://github.com/verbb/formie/releases/tag/1.4.25)
