### ISSUE TITLE
Custom error message is not shown

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1852]
### Describe the bug

I added custom error messages to my fields but they are not shown in the frontend:

<img width="341" alt="Screenshot 2024-04-25 at 15 48 45" src="https://github.com/verbb/formie/assets/4956295/36858423-eb5d-436b-b8e4-989b35f06ec1">
<img width="947" alt="Screenshot 2024-04-25 at 15 48 18" src="https://github.com/verbb/formie/assets/4956295/1164f968-5ca0-44cb-b0c6-5a8083ea5024">

### Steps to reproduce

1. 
2. 

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.0.5

### Plugin version

3.0.0-beta.8

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.8"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.9](https://github.com/verbb/formie/releases/tag/3.0.0-beta.9)
