### ISSUE TITLE
User mapping field submission fails

### ISSUE THREAD

**Issue by atelierbim** [verbb/formie#1858]
### Describe the bug

Setup a register form mapped to users. The form submits but the queue displays an error:
Failed to trigger integration: ["Element integration failed for submission “607063”. Error: verbb\\formie\\base\\Integration::getFieldMappingValues(): Argument #2 ($fieldMapping) must be of type array, null given, called in \/var\/www\/html\/vendor\/verbb\/formie\/src\/integrations\/elements\/User.php on line 213 \/var\/www\/html\/vendor\/verbb\/formie\/src\/base\/Integration.php:493"].

### Steps to reproduce

1.  Create a register form
2. Front end fill the form and submit
3. The submission appears on the Formie Submissions but not in Craft's user group.

<img width="1040" alt="Capture d’écran 2024-05-01 à 15 07 03" src="https://github.com/verbb/formie/assets/64537972/f4189625-7f55-4b11-8355-29692972f4b3">
<img width="886" alt="Capture d’écran 2024-05-01 à 15 07 17" src="https://github.com/verbb/formie/assets/64537972/3d711746-d4c5-4984-a0d1-90321667d406">
<img width="1045" alt="Capture d’écran 2024-05-01 à 15 07 44" src="https://github.com/verbb/formie/assets/64537972/fabee2ca-bf82-4e0b-be7f-f9a0cee4fe8b">
<img width="1239" alt="Capture d’écran 2024-05-01 à 15 08 01" src="https://github.com/verbb/formie/assets/64537972/95e7bbeb-75bb-4ed5-8e7d-4b7a04ecadb7">
<img width="1242" alt="Capture d’écran 2024-05-01 à 15 08 24" src="https://github.com/verbb/formie/assets/64537972/99b48030-6add-40d8-9007-3a3efda887a6">
<img width="1243" alt="Capture d’écran 2024-05-01 à 15 08 35" src="https://github.com/verbb/formie/assets/64537972/9fd96450-d5d2-44c5-89f4-fb798131150e">
<img width="997" alt="Capture d’écran 2024-05-01 à 15 08 43" src="https://github.com/verbb/formie/assets/64537972/ff37b81a-5efb-45a3-90f1-1feb613497b8">

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes or No
- Custom Form Templates: No

### Craft CMS version

5.1.0

### Plugin version

3.0.0-beta.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)
