### ISSUE TITLE
Salesforce integration - API client error

### ISSUE THREAD

**Issue by j-greig** [verbb/formie#186]
**Description**
1. Have successfully set up Salesforce integration via admin/formie/settings/crm and gotten a green 'Connected Dot'
2. After creating a new form and enabling the Salesforce integration, clicking "Refresh Integration", the error is 

Sales Force: API error: “Client error: `GET https://um1.salesforce.com/services/data/v49.0/query?q=SELECT%20ID%2CName%20FROM%20User%20LIMIT%2020` resulted in a `401 Unauthorized` response: [{"message":"This session is not valid for use with the REST API","errorCode":"INVALID_SESSION_ID"}] ” /home/forge/clientname.ghdev.xyz/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

(One though, is it possible our client hasn't enabled the API access option on their SalesForce account?)

**Additional info**
- Plugin version: 1.2.21
- Craft version: 3.5.12.1
- Multi-site: No

<img width="2014" alt="Screen Shot 2020-10-19 at 2 12 07 pm" src="https://user-images.githubusercontent.com/616194/96455408-17edb680-1215-11eb-8530-e7f1abbbce9d.png">

Thanks!

**Comment by engram-design** [comment]
Are you able to double check your Salesforce settings that they follow the below? From a cursory Google, it seems related to their account, as I have no issues connecting with my account.

![Screen Shot 2020-10-20 at 9 14 33 am](https://user-images.githubusercontent.com/1221575/96517457-b2510700-12b4-11eb-9a94-388463aae6c9.png)

**Comment by j-greig** [comment]
Thanks, I've tripled checked the settings and everything appears to be connected. 

I've also tested the Rest API via https://workbench.developerforce.com/ and everything seems to work fine there... not sure what to try next... 

Thanks!

**Comment by engram-design** [comment]
Looks like this was a OAuth issue, where the docs failed to mention the need for the **Access and manage your data (api)** permission to be granted.
