### ISSUE TITLE
Issue with field upload inside of group

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1863]
### Describe the bug

We have discovered the following Issue with Ajax multi-page form:
When an upload field is placed in a group the upload happens, but it is missing in the submissions and also in the mail attachment. 

### Steps to reproduce

1. Import the example: [formie.json](https://github.com/verbb/formie/files/15198440/formie-uploadInGroup-0f0eae80-5040-4f66-961c-4fbf78d2eaea.json)
2. Add a pdf to both fields.
3. Go to the page 2 (both pdf have been uploaded to the server).
4. Submit the form.
5. Open the submission, the pdf from the upload field placed in a group is missing.
6. The pdf is also missing in the mail.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax

### Craft CMS version

4.8.10

### Plugin version

2.1.13

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.13"`.

**Comment by engram-design** [comment]
Updated in [2.1.14](https://github.com/verbb/formie/releases/tag/2.1.14)
