### ISSUE TITLE
Value of date field not shown in subject line of form submission notification mails

### ISSUE THREAD

**Issue by philipschilling** [verbb/formie#1866]
### Describe the bug

I added a placeholder for a date field in the subject line of a form submission notification mail:
<img width="1115" alt="Screenshot 2024-05-05 at 11 42 46" src="https://github.com/verbb/formie/assets/4956295/95ee13c8-561b-446e-ad20-f9e81dadbca8">

The field remains empty though the value is shown in the email body where I used the placeholder "All Non Empty Fields":
<img width="290" alt="Screenshot 2024-05-05 at 11 43 34" src="https://github.com/verbb/formie/assets/4956295/34b3653f-391d-4423-8d35-7a31ea93515f">

### Steps to reproduce

1. Open in Control Panel "Formie > Forms > [Name of Form]"
2. Open tab "Email Notifcations" and open an existing notification or create a new one
3. Under the tab "Content" add in the field "Subject" a date field
4. Apply + Save and submit a test submission

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.1.1

### Plugin version

3.0.0-beta.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)
