### ISSUE TITLE
[V5]: Campaign integration

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/formie#1867]
### Describe the bug

We have the problem that the lists we have created in Campaign are not displayed as a target in the list selection in Campaign Integration.

In Craft CMS 4 it worked normally. We suspect that there has been a change in Campaign for Craft 5

<img width="645" alt="Bildschirmfoto 2024-05-06 um 00 33 40" src="https://github.com/verbb/formie/assets/69263307/daaa01a5-a0a7-434e-ac6d-28d1e61bc90e">
<img width="912" alt="Bildschirmfoto 2024-05-06 um 00 33 46" src="https://github.com/verbb/formie/assets/69263307/7f519aee-45f7-43f8-9e47-5d51b8e33ef2">

### Steps to reproduce

1. Try to Conect Formie wirh a Campaign List

### Form settings

- Multi-page form: No

### Craft CMS version

5.1

### Plugin version

3.0.0-beta.9

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by alexanderloewe** [comment]
Thx 🙏

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)
