### ISSUE TITLE
[5.x] Generated GraphQL types for name/address fields don't exist.

### ISSUE THREAD

**Issue by benfeather** [verbb/formie#1868]
### Describe the bug

The GQL types for fields with nested fields throw an error when used in a mutation. 

Here is the data for the name field in my demo form:

![CleanShot 2024-05-06 at 15 30 31@2x](https://github.com/verbb/formie/assets/43571410/dcd518ae-7fad-4b78-8d79-a1636852c2b1)

It has the type: `kitchenSink_nameMulti_FormieNameInput`

But if I use that type in GraphiQL, it throws an error:

![CleanShot 2024-05-06 at 15 32 04@2x](https://github.com/verbb/formie/assets/43571410/540d95fa-3a73-4e40-a295-86291c610d80)

![CleanShot 2024-05-06 at 15 32 26@2x](https://github.com/verbb/formie/assets/43571410/cd9d1669-a853-4f22-a7df-0909b19308b3)

The address field appears to do the same.

### Steps to reproduce

N/A

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.1.1

### Plugin version

dev-craft-5 as 3.0.0-beta.9

### Multi-site?

Yes

**Comment by benfeather** [comment]
I got the mutation code from the docs:

https://verbb.io/craft-plugins/formie/docs/developers/graphql#submissions-1

```
// Query
mutation saveSubmission($yourName:contactForm_yourName_FormieNameInput $yourAddress:contactForm_yourAddress_FormieAddressInput) {
    save_contactForm_Submission(yourName: $yourName, yourAddress: $yourAddress) {
        yourName
        yourAddress
    }
}

// Query Variables
{
    "yourName": {
        "firstName": "Peter",
        "lastName": "Sherman"
    },
    "yourAddress": {
        "address1": "42 Wallaby Way",
        "city": "Sydney",
        "zip": "2000",
        "state": "NSW",
        "country": "Australia"
    }
}
```

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by benfeather** [comment]
Looks good to me, Thanks!
