### ISSUE TITLE
Add disabled state to GraphQL [FieldInterface]

### ISSUE THREAD

**Issue by jan-thoma** [verbb/formie#1869]
### What are you trying to do?

Make it possible to query the deactivated Status on GraphQL Requests.

### What's your proposed solution?

```
fragment formieField on FieldInterface {
    name
    handle
    displayName
    uid
    id
    required
    defaultValue

    ...on Field_Dropdown {
        instructions
        options {
            isOptgroup
            isDefault
            isDeactivated #add this
            label
            value
        }
    }
}
```

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.13"`.

**Comment by engram-design** [comment]
Updated in [2.1.14](https://github.com/verbb/formie/releases/tag/2.1.14)
