### ISSUE TITLE
Mollie payment integration

### ISSUE THREAD

**Issue by srosenbrand** [verbb/formie#1870]
### What are you trying to do?

Any plans for integrating Mollie as a payment provider in the short future?

### What's your proposed solution?

Mollie payment integration

**Comment by engram-design** [comment]
Duplicate of https://github.com/verbb/formie/issues/1084 but yes there are plans to do this, but not in the short term (next few months). In addition it’s only going to be possible in Formie 3 for Craft 5 due to how their payment system works.

**Comment by srosenbrand** [comment]
Thanks for the update! Any suggestions on how to get this working before official release (without spending days learning Mollie API)? We are using Craft 5 with Formie 3 (beta) already in production.
