### ISSUE TITLE
[5.x] Entry element integration fails

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#1871]
### Describe the bug

Hi, we've encountered an issue when trying to use Formie's element integration to create a new entry with a submission

Initially we were getting a this error
`2024-05-07 10:55:28 [ERROR] Element integration failed for submission “40”. Error: Getting unknown property: craft\models\EntryType::sectionId /var/www/html/vendor/yiisoft/yii2/base/Component.php:154`

but I saw a fix for that was pushed [here](https://github.com/verbb/formie/commit/01ee1df02b8606576632ff07a7bdb1efd596389f) so I tried to pull in the latest updates from the craft-5 branch and got the following error

`2024-05-07 10:58:28 [ERROR] Element integration failed for submission “40”. Error: Call to a member function getSiteSettings() on null /var/www/html/vendor/craftcms/cms/src/elements/Entry.php:1037`

The form I was using to test only has a single text field mapped to the title

<img width="966" alt="Screenshot 2024-05-07 at 11 05 36 AM" src="https://github.com/verbb/formie/assets/21274925/a4480e94-b4f5-4931-8ec5-4d106ee4a654">

Let me know if you need any more info

### Steps to reproduce

1. Create an Entry element integration to make a new entry on submission
2. Try to run the integration

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.1.1

### Plugin version

3.0.0-beta.9

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)

**Comment by d-karstens** [comment]
Cheers for the quick fix!
