### ISSUE TITLE
[5.x] option `resetClasses` generates javascript errors with `classList.remove`

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1873]
### Describe the bug

The option `resetClasses` generates javascript errors with multi-page forms
Dom Elements no longer have classes, therefore the javascript breaks
```js
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
```
removeLoading(), removeTabErrors()

### Steps to reproduce

1. Create a new form
2. Add multiple pages
3. Add new mandatory fields
4. Open the form in the frontend 
6. Go to the next page
7. Check the console for errors

### Form settings

- Multi-page form: Yes 
- Submission Method: Ajax 

### Craft CMS version

5.1.1

### Plugin version

3.0.0-beta.9

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.9"`.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.10](https://github.com/verbb/formie/releases/tag/3.0.0-beta.10)
