### ISSUE TITLE
[5.x] Add existing field option doesn't work.

### ISSUE THREAD

**Issue by benfeather** [verbb/formie#1874]
### Describe the bug

I'm unable to add an existing field to a new form:

https://github.com/verbb/formie/assets/43571410/c2d7265d-4006-488a-96d2-d6787d4ba1bc

There are no errors logged in the browser console. However, there are some depreciation errors in the logs that pop up when I try to add an existing field, so this may be related. 

![CleanShot 2024-05-08 at 10 32 00@2x](https://github.com/verbb/formie/assets/43571410/0f436c73-4c22-4882-bace-28ac43854080)

Here is the stack trace:

![e1](https://github.com/verbb/formie/assets/43571410/23c4235d-ccac-456e-badb-21f2f32c3b0d)

![e2](https://github.com/verbb/formie/assets/43571410/d5ba5209-6170-4f56-b8df-76fa1ddd9d4e)

### Steps to reproduce

N/A

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.1.2

### Plugin version

3.0.0-beta.10

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.10"`.

**Comment by benfeather** [comment]
That works, thanks!
