### ISSUE TITLE
Successful Submission Message Position

### ISSUE THREAD

**Issue by am0** [verbb/formie#188]
**What are you trying to do?**
The validation message has an option to select whether it appears at the top or the bottom of the form, and in order to save having to manually style it into the same place, it would be useful if there was also a position option for this on the Submission message.

**What's your proposed solution?**
Add the same type of select menu as the validation message with the same options- "Top of form" and "Bottom of form" and have the message appear in the relevant place when rendered.

I can do this with a bit of CSS but I imagine this would be a useful feature for those wanting the error and success messages appearing in the same place. Thanks!

**Comment by engram-design** [comment]
Sure thing, I wanted to keep these as separate settings anyway. Just added for the next release.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.24",
  "...": "..."
}
```

Then run `composer update`.

**Comment by am0** [comment]
@engram-design Fantastic, that works a treat. Thanks so much!

**Comment by engram-design** [comment]
Added in [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25)
