### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by DarioDiGiacomo** [verbb/formie#1882]
### Describe the bug

If installed formie in Craft CMS v5. After I create a new form their comes a error message without any explanation.

![image](https://github.com/verbb/formie/assets/114081282/1fc95142-38c6-42c4-b0f5-76e639e7c353)

I cant do anything inside the form itself, but every other page works fine I guess.

![image](https://github.com/verbb/formie/assets/114081282/6cd47edb-7719-4a1f-965c-0bf55e10228c)

### Steps to reproduce

**1. + New form**
![image](https://github.com/verbb/formie/assets/114081282/687cffe6-715f-44f1-8240-0ea340e0fa69)

**2. Create the form**
![image](https://github.com/verbb/formie/assets/114081282/a7d90041-403d-49da-8cb4-06f8869c0e2c)
![image](https://github.com/verbb/formie/assets/114081282/4669cecc-4fe4-4d9a-b673-afec5b5c2423)
(It doesn't matter which stencil I use)

![image](https://github.com/verbb/formie/assets/114081282/747bfe18-cd40-4084-887e-90d2a9218ffe)

### Form settings

All the settings are default

### Craft CMS version

Craft CMS 5.1.2

### Plugin version

3.0.0-beta.10

### Multi-site?

No

**Comment by engram-design** [comment]
Something looks to be wrong with the JS and CSS as things don't seem to be rendering properly at all.

Can you check your browser console in Web Developer Tools (for Chrome)? There should be some sort of error with the JS. I would also try clearing your Craft caches in Utilities > Clear Caches

**Comment by DarioDiGiacomo** [comment]
I only get a error about my favicon

![image](https://github.com/verbb/formie/assets/114081282/0b57e490-9e53-4bb6-a6cb-6c1ead68bf3c)

I've also tried to install it on a other project, both with the code but with no succes :(

![image](https://github.com/verbb/formie/assets/114081282/cb4a4097-896a-4822-96d8-e19c55dce251)

**Comment by engram-design** [comment]
I meant opening your developer tools when editing a Formie form, not the front-end of the site. Are there any error there when you try to edit or create a form in the Craft control panel?

**Comment by DarioDiGiacomo** [comment]
No i also don't get any erros of css or js here

I also can't make any new fields
![image](https://github.com/verbb/formie/assets/114081282/88e42af9-8d92-4baa-af77-c8d0e00db107)

![image](https://github.com/verbb/formie/assets/114081282/448bb1a2-6ea5-4685-9f41-6eeb23933d7d)

**Comment by engram-design** [comment]
I can tell the JS isn't loading correctly because that second screenshot for the new form isn't styled correctly. Might have something to do with Windows, so will spin up a site just in case.

**Comment by DarioDiGiacomo** [comment]
Okay, I can't wait for an answer. It's a bit strange it happened. no one in my class has the same issue.

I tried to install it on another project just with the try button. and then i got this error

![image](https://github.com/verbb/formie/assets/114081282/cf748f59-465a-4cb1-85a6-9166c00608b1)
Maybe it was a important to know..

**Comment by engram-design** [comment]
Can you have a look at the logs in `/storage/logs/formie.log`?

**Comment by DarioDiGiacomo** [comment]
2024-05-14 02:32:38 [ERROR] Couldn’t save form - [["*Handle* cannot be blank."],{"handle":["*Handle* cannot be blank."]}].
2024-05-14 02:32:38 [INFO] Request context:
$_GET = [
    'p' => 'admin/formie/forms/new'
]

$_POST = [
    'action' => 'formie/forms/save'
    'redirect' => 'c28fab55f8c0db525f201ee2b4649b7dceda83d508c1f643d367479e4cfed944formie/forms/edit/{id}'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'title' => 'blank form '
    'applyStencilId' => ''
    'handle' => ''
]
2024-05-14 02:32:50 [ERROR] Couldn’t save form - [["*Handle* cannot be blank."],{"handle":["*Handle* cannot be blank."]}].
2024-05-14 02:32:50 [INFO] Request context:
$_GET = [
    'p' => 'admin/formie/forms/new'
]

$_POST = [
    'action' => 'formie/forms/save'
    'redirect' => 'c28fab55f8c0db525f201ee2b4649b7dceda83d508c1f643d367479e4cfed944formie/forms/edit/{id}'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'title' => 'blank form'
    'applyStencilId' => ''
    'handle' => ''
]
2024-05-14 05:29:48 [ERROR] Couldn’t save form - [["handle \"test\" has already been taken."],{"handle":["handle \"test\" has already been taken."]}].
2024-05-14 05:29:48 [INFO] Request context:
$_GET = [
    'p' => 'admin/formie/forms/new'
]

$_POST = [
    'action' => 'formie/forms/save'
    'redirect' => 'c28fab55f8c0db525f201ee2b4649b7dceda83d508c1f643d367479e4cfed944formie/forms/edit/{id}'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'title' => 'test'
    'applyStencilId' => '1'
    'handle' => 'test'
]
2024-05-14 05:29:54 [ERROR] Couldn’t save form - [["handle \"test\" has already been taken."],{"handle":["handle \"test\" has already been taken."]}].
2024-05-14 05:29:54 [INFO] Request context:
$_GET = [
    'p' => 'admin/formie/forms/new'
]

$_POST = [
    'action' => 'formie/forms/save'
    'redirect' => 'c28fab55f8c0db525f201ee2b4649b7dceda83d508c1f643d367479e4cfed944formie/forms/edit/{id}'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'title' => 'test'
    'applyStencilId' => '1'
    'handle' => 'test'
]


The only error in here is about forgetting a handle

**Comment by engram-design** [comment]
That would make sense as the handle is auto-generated for new forms with JS. If there's an issue loading the JS - which is the issue here - that's going to fail.

Really tricky to figure out what's going on without a look at your environment and install. I'm spun up a Windows machine, and that seems to be okay. Can you let me know what your setup is for development?

**Comment by DarioDiGiacomo** [comment]
I use wampserver with a virtualhost for craft cms, is that what u mean?

**Comment by engram-design** [comment]
Yup, just wanted to check in case it made a difference.

**Comment by DarioDiGiacomo** [comment]
If it's easier to talk another way if that would be faster than on github, that's fine with me.

**Comment by engram-design** [comment]
If you're on the Craft Discord, let's maybe chat there?

**Comment by DarioDiGiacomo** [comment]
Alright i just joined the discord, didn't know it existed. Where can i find u? U can find my under @daarieoo

**Comment by engram-design** [comment]
Managed to get to the bottom of this, and should be resolving in a [dependency](https://github.com/nystudio107/craft-plugin-vite/pull/25) we use.

**Comment by DarioDiGiacomo** [comment]
Alright, what do have i have to do know?

**Comment by engram-design** [comment]
This should be fixed in Craft 4.9.5 and 5.1.5. See https://github.com/craftcms/cms/issues/15043
