### ISSUE TITLE
Unable to save Integrations > reCAPTCHA — Couldn’t save integration settings

### ISSUE THREAD

**Issue by afairhurst** [verbb/formie#1886]
### Describe the bug

Formie > Settings > reCAPTCHA Settings

Unable to save settings. Alert reads 'Couldn’t save integration settings'. Nothing in Formie logs.

### Steps to reproduce

Navigate to reCAPTCHA Settings

- Toggle Enabled to 'Yes' (Tested using Environmental Variable or Dropdown value)
- Add Google reCAPTCHA Site Key (Tested using Environmental Variable or Actual key)
- Add Google reCAPTCHA Secret Key (Tested using Environmental Variable or Actual key)
- Click 'Save'

### Form settings

Simple contact form

### Craft CMS version

Craft CMS 5.1.3

### Plugin version

3.0.0-beta.10

### Multi-site?

No

### Additional context

Also unable to save other captcha settings such as enabling Javascript.
Using default Formie config
Tested on Local and Live environments — fails to save settings in both

**Comment by engram-design** [comment]
Difficult to say what it might be, as it could be any of the captchas (they are all saved together). I've just added logging for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.10"`. If you want to give that a go and try re-saving the captchas?

**Comment by afairhurst** [comment]
Hi,

Thanks for looking in to this.

My current version of Formie is already 3.0.0-beta.10.

Thank you,

Andrew

**Comment by afairhurst** [comment]
I've now tracked down the issue to a error in my Formie config php file:

I had written:
'alertEmails' => ['Name', 'email@domain'],

However it should've been:
'alertEmails' => [['Name', 'email@domain'],],

This has fixed the issue for me.

Thank you
