### ISSUE TITLE
`userId` parameter on the Submission Query producing weird results

### ISSUE THREAD

**Issue by jalendport** [verbb/formie#1890]
### Describe the bug

I'm seeing some weird behavior where the `userId` parameter is in most cases preventing the query from returning any items, when it in fact should be. The parameter works fine if you define a single user id (e.g. `.userId(1)`, but if I try to pass in multiple user ids (e.g. `.userId([1, 2])`), or negate either a single user id or multiples (e.g. `.userId('not 1')` or `.userId(['not', 1, 2])` then it returns 0 elements, which is not correct or expected.

### Steps to reproduce

Try to use the following query: `craft.formie.submissions().form('formName').userId('not 1').count()`

### Form settings

Shouldn't matter...

### Craft CMS version

Craft Pro 4.9.3

### Plugin version

2.1.14

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.14"`.

**Comment by engram-design** [comment]
Fixed in [2.1.15](https://github.com/verbb/formie/releases/tag/2.1.15)
