### ISSUE TITLE
Postal code field behaving as auto-complete field with Loqate address look-up integration

### ISSUE THREAD

**Issue by jonnykates** [verbb/formie#1891]
### Describe the bug

When adding an 'address' field to a form with a Loqate provider connected, the 'Auto-Complete' sub-field is not behaving as the look-up input. Instead, it appears that the 'Postal Code' sub-field behaves as we would expect the auto-complete to.

Formie field config:
![Screenshot 2024-05-17 at 10 29 38](https://github.com/verbb/formie/assets/1444970/10e3b307-9cfa-4d56-9efc-57a81545933e)

No auto-complete behaviour on front-end:
![Screenshot 2024-05-17 at 10 30 11](https://github.com/verbb/formie/assets/1444970/4fbcdb90-6232-44fa-a4d4-40be68607b69)

Postal-code field behaving as auto-complete:
![Screenshot 2024-05-17 at 10 31 23](https://github.com/verbb/formie/assets/1444970/8c81cfa9-e6f3-4d70-a27b-cc24c529af30)

### Steps to reproduce

1. Connect a Loqate address provider with a valid API key
2. Create a Formie form and add an address field
3. Configure the 'Auto-Complete' sub-field to use the Loqate provider
4. Render the form somewhere on the front-end
5. The auto-complete input does not suggest addresses
6. The postal code input instead suggests (and populates relevant sub-fields when selected) addresses

### Form settings

- Multi-page form: Yes or **No**
- Submission Method: Ajax or **Page Reload**
- Client-side Validation: Yes or **No**
- Custom Form Templates: Yes or **No**

### Craft CMS version

Craft Pro 5.1.3

### Plugin version

3.0.0-beta.10

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.10"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.11](https://github.com/verbb/formie/releases/tag/3.0.0-beta.11)
