### ISSUE TITLE
Entry integrations enabling entries even when section settings have default status as disabled

### ISSUE THREAD

**Issue by justinholtweb** [verbb/formie#1895]
### Describe the bug

With an entry integration to a section where the section settings specify the new entries should be disabled by default, Formie seems to save the new entries as enabled. 

### Steps to reproduce

1. Create a section where new entries are set to disabled by default.
2. Create a Formie integration for a form. Feed those submissions to the section. See that even though the section settings specify that new entries should be disabled, those entries that are seeded from Formie submissions are enabled. 

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.9.4

### Plugin version

2.1.15

### Multi-site?

No

### Additional context

This previously worked fine on a past version of Craft and Formie. Client just recently reported this problem. The plugin is licensed.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.15"`.

**Comment by engram-design** [comment]
Fixed in [2.1.16](https://github.com/verbb/formie/releases/tag/2.1.16)
