### ISSUE TITLE
[5.x] Date / time field, available days config not working

### ISSUE THREAD

**Issue by ZapaNOR** [verbb/formie#1897]
### Describe the bug

If I try to save a form with a date / time field that has a custom config for available days, the selection does not get saved, and all days are now unselected after a refresh. If I select "All", it is saved with all days selected.

![Screenshot 2024-05-21 at 14 24 43](https://github.com/verbb/formie/assets/53942798/f9ecabfa-9d96-47a0-a680-1a8e2ff5f6a6)

### Steps to reproduce

1. Create a form
2. Add a date / time field
3. Unselect time (only date)
4. Chose available days

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.1.4

### Plugin version

3.0.0-beta.11

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.11"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.12](https://github.com/verbb/formie/releases/tag/3.0.0-beta.12)
