### ISSUE TITLE
Form fields won't load on edit page

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1899]
### Describe the bug

When attempting to edit a form, the form layout doesn't load — the page is stuck on the loading spinner. I don't see any console errors or network errors, either. However, **this only happens on production**. Everything works fine in local dev. 

![edit-form](https://github.com/verbb/formie/assets/5922913/676fecfe-c659-4737-a39e-81752d3f2558)

When checking the other tabs, _most_ fields are rendered, but there are some that do not:
- Behavior > Action on Submit — the dropdown is empty
- Email Notifications — the whole panel is empty
- Settings > Advanced — none of the advanced fields are shown

I've tried Chrome, Safari, Firefox... private mode... cleared caches... etc. to no avail.

### Craft CMS version

4.9.4

### Plugin version

2.1.15

**Comment by engram-design** [comment]
Quick one - do you use Cloudflare, and do you have their RocketLoader enabled? In the past, that's interfered with Formie's JS. Certainly seems like a JS loading issue here.

**Comment by chrismlusk** [comment]
The site does use Cloudflare, but RocketLoader is not enabled.

**Comment by engram-design** [comment]
Hmmm, might be worth poking around any settings in there related to JS, in case anything is enabled. Very odd no JS errors are shown in the console though.

**Comment by chrismlusk** [comment]
Will do. It's odd because as far as I know, nothing has been updated in a few days. We made a heap of form field changes last week — the only deployment was a stencil update, though — and everything was working as expected.

I'll see if I can track down anything helpful and report back. Thanks!

**Comment by chrismlusk** [comment]
Well, I didn't do anything, but the edit pages are loading as expected again. No clue! I'll close this for now.
