### ISSUE TITLE
[Craft 5.x] Phone dial-code not showing anymore on phone field

### ISSUE THREAD

**Issue by lenvanessen** [verbb/formie#1900]
### Describe the bug

The Craft 4 version of Formie would show the dial code in the country dropdone for a Phone field, whilst the new one doesn't anymore. Any way we can re-enable this?

### Steps to reproduce

.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5.1.3

### Plugin version

3.0.0-beta11

**Comment by engram-design** [comment]
This is actually enabled by default now, but some display issues with the [intl-tel-input](https://github.com/jackocnr/intl-tel-input) package were going on.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.11"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.12](https://github.com/verbb/formie/releases/tag/3.0.0-beta.12)
