### ISSUE TITLE
Hubspot Integration. Assign to Company

### ISSUE THREAD

**Issue by bfjare** [verbb/formie#1902]
### Question

We have a form we want to assign to a company not a contact and update its information.  Is this possible to do with the contact endpoint or would that need to be added to make sure it posts to the company endpoint.

$url = 'https://api.hubapi.com/companies/v2/companies?hapikey=' . $apiKey;

**Comment by engram-design** [comment]
We'd need to add it as a separate data object, like we currently have with Contacts and Deals. I'll add it to our roadmap.

**Comment by bfjare** [comment]
I would be interested in sponsoring this to expedite the feature it would save us a lot of dev time.

**Comment by engram-design** [comment]
Best to drop us a line at `support@verbb.io` although our schedule is pretty packed for a bit!

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.20"`.

**Comment by engram-design** [comment]
Added in [2.1.21](https://github.com/verbb/formie/releases/tag/2.1.21)
