### ISSUE TITLE
Opayo payment integration error - Unprocessable Entity

### ISSUE THREAD

**Issue by akabucko** [verbb/formie#1907]
### Describe the bug

Once upgrading the Formie plugin to version 2.1.10 or above, Opayo payment integration stopped working causing an error on the form letting users pay with the following error:

`Client error: POST https://pi-test.sagepay.com/api/v1/transactions resulted in a 422 Unprocessable Entity response:
{"statusCode":"3078","statusDetail":"The CustomerEMail format is invalid.","transactionId":"(truncated...)`

I have a multi-step form that pays invoices through the Opayo payment integration. The bug seems to have been introduced in the 2.1.10 update and in the changelog, there is a fix for Opayo which could have introduced the issue - `Fixed Opayo payments not sending customer email address.` In the error above the email field is 'CustomerEMail'. Could the naming convention here be causing a problem? If not, is there anything you would advise me to check to fix the issue? 

I've currently downgraded to 2.1.9 which is working fine while I investigate the issue too but thought I'd mention it incase its a bug.

### Steps to reproduce

1. Fill in the Opayo integration form passing validation checks
2. Once the user submits an error validation message appears
3. Error message - `Client error: POST https://pi-test.sagepay.com/api/v1/transactions resulted in a 422 Unprocessable Entity response: {"statusCode":"3078","statusDetail":"The CustomerEMail format is invalid.","transactionId":"(truncated...)`
4. The user is unable to submit the form and pay through Opayo.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No
- Opayo Payment: Yes

### Craft CMS version

4.9.4

### Plugin version

2.1.10

### Multi-site?

No

**Comment by engram-design** [comment]
Interesting. So that [commit](https://github.com/verbb/formie/commit/67b5ec3ddce25c1b7ce12231924c41f3711f2a92) was about failing to send the email address correctly at all, it simply wasn't being sent.

I was working with an agency on Opayo and some other fixes. At the time during testing, I noticed that the emails started to throw an error, despite them not having done so to that point. 

I didn't _think_ that the casing mattered - `customerEmail` vs `CustomerEMail`, but maybe it does?!

Out of interest, does the change at https://github.com/verbb/formie/blob/67b5ec3ddce25c1b7ce12231924c41f3711f2a92/src/integrations/payments/Opayo.php#L792 make a difference? The Opayo docs are a bit here, there and everywhere on the matter.

**Comment by akabucko** [comment]
> Interesting. So that [commit](https://github.com/verbb/formie/commit/67b5ec3ddce25c1b7ce12231924c41f3711f2a92) was about failing to send the email address correctly at all, it simply wasn't being sent.
> 
> I was working with an agency on Opayo and some other fixes. At the time during testing, I noticed that the emails started to throw an error, despite them not having done so to that point.
> 
> I didn't _think_ that the casing mattered - `customerEmail` vs `CustomerEMail`, but maybe it does?!
> 
> Out of interest, does the change at
> 
> https://github.com/verbb/formie/blob/67b5ec3ddce25c1b7ce12231924c41f3711f2a92/src/integrations/payments/Opayo.php#L792
> 
> make a difference? The Opayo docs are a bit here, there and everywhere on the matter.

That seems to be the change that has caused the issue, once I've made the code change it gives me the same error again and won't let me submit the form (screenshots attached).

`Client error: POST https://pi-test.sagepay.com/api/v1/transactions resulted in a 422 Unprocessable Entity response: {"statusCode":"3078","statusDetail":"The CustomerEMail format is invalid.","transactionId":"552A1C99-6E0E-8436-A0FD-DD26 (truncated...`

The Opayo docs aren't the best, are they? Do you think this is a casing issue then?

Thanks for your help on this!

<img width="720" alt="frontend-error-message" src="https://github.com/verbb/formie/assets/26873231/4e9d76ef-537c-4dd1-8c00-b580098db38e">
<img width="711" alt="code-change-formie" src="https://github.com/verbb/formie/assets/26873231/24a2510e-c90d-4f91-a941-e7f7be4117ad">

**Comment by engram-design** [comment]
Just to be clear, if you manually modify that line from:

```php
$payload['customerEmail'] = $this->getFieldSetting('billingDetails.billingEmail');
```
to:
```php
$payload['customerEMail'] = $this->getFieldSetting('billingDetails.billingEmail');
```

That makes the error go away and the email be sent to Opayo?

**Comment by MattAppleton** [comment]
Just following this up, we seem to be experiencing a very similar error...

`Opayo: Payment error: “Client error: `POST [https://pi-live.sagepay.com/api/v1/transactions](https://pi-live.sagepay.com/api/v1/transactions%60)[`](https://pi-live.sagepay.com/api/v1/transactions%60) resulted in a `422 Unprocessable Entity` response:
{"statusCode":"3078","statusDetail":"The CustomerEMail format is invalid.","transactionId":"8E11E8B1-1F5B-F8C5-6508-B5A3 (truncated...)`

**Comment by MattAppleton** [comment]
@engram-design 

I just tried this edit on line 792, which now reads

`$payload['customerEMail'] = $this->getFieldSetting('billingDetails.billingEmail');`

and now the form works!

**Comment by engram-design** [comment]
Thanks for confirming, fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.20"`.

**Comment by engram-design** [comment]
Fixed in [2.1.21](https://github.com/verbb/formie/releases/tag/2.1.21)

**Comment by akabucko** [comment]
Just reopening this backup, I am receiving the same error again from the Opayo payment integration code on the Craft 4 version of Formie:

`Client error: POST https://pi-test.sagepay.com/api/v1/transactions resulted in a 422 Unprocessable Entity response: {"statusCode":"3078","status details":"The CustomerEMail format is invalid.","transactionId":"7D98E11A-6EA3-EA77-588D-6602 (truncated...)`

Seems to be an issue with the customerEMail formatting again. I've gone into the code and added the following fix [here](https://github.com/verbb/formie/blob/craft-4/src/integrations/payments/Opayo.php#L797):

Old:
`        $payload['customerEMail'] = $this->getFieldSetting('billingDetails.billingEmail');`

New:
```
$billingEmail = $this->getFieldSetting('billingDetails.billingEmail');

        if ($billingEmail) {
            $integrationField = new IntegrationField();
            $integrationField->type = IntegrationField::TYPE_STRING;

            $email = $this->getMappedFieldValue($billingEmail, $submission, $integrationField);
            
            // Only set if we have a valid email
            if (filter_var($email, FILTER_VALIDATE_EMAIL)) {
                $payload['customerEMail'] = $email;
            }
        } else {
            // Provide a default valid email if none provided
            $payload['customerEMail'] = 'customer@example.com';
        }
```
This submits the form without any errors and logs it in Opayo with the correct customer email. Could you have a look and see what you think?

### Steps to reproduce

1. Fill in the Opayo integration form passing validation checks
2. Once the user submits an error validation message appears
3. Error message - `Client error: POST https://pi-test.sagepay.com/api/v1/transactions resulted in a 422 Unprocessable Entity response: {"statusCode":"3078","statusDetail":"The CustomerEMail format is invalid.","transactionId":"(truncated...)`
4. The user is unable to submit the form and pay through Opayo.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No
- Opayo Payment: Yes


### Craft CMS version

4.14.12

### Plugin version

2.1.43

### Multi-site?

No

**Comment by engram-design** [comment]
Following up in https://github.com/verbb/formie/issues/2351
