### ISSUE TITLE
ReCAPTCHA was unable to load

### ISSUE THREAD

**Issue by lukasNo1** [verbb/formie#1911]
### Describe the bug

I have a weird bug with recaptcha.

 After the form is loaded, when you click on the recaptcha v2 checkbox, it just loads for around 15 seconds and then an error is thrown in the console (which is not very helpful cause the error is "undefined").

The bug happens on all forms across all browsers. It happens locally in an uncached environment and on production with fullpage cache and the refreshForCache script.

Have you ever encountered this bug?

![image](https://github.com/verbb/formie/assets/19799373/7ddbfdfe-dbfb-4633-a470-90773d5c3112)

### Steps to reproduce

Not sure.

### Form settings

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.9.5

### Plugin version

2.1.18

### Multi-site?

no

**Comment by engram-design** [comment]
Not something I've seen in action yet, but easy enough to replicate by disabling the internet. It also seems like a timeout issue just reaching the reCAPTCHA servers.

Have you tried on another network, or via a VPN just to check it's not just a network connectivity issue?

**Comment by lukasNo1** [comment]
Yes, I tried it over a vpn, it was also reported to me by several users of the website

**Comment by lukasNo1** [comment]
ahh damn... i think i found the problem. The project already loaded the https://www.google.com/recaptcha/api.js once for another usecase and then formie added it a second time.
