### ISSUE TITLE
[Craft 5] Creating new form throws error on "Name" field

### ISSUE THREAD

**Issue by HannahDeWachter** [verbb/formie#1912]
### Describe the bug

I work with a “starter package” which I use for every project and we recently upgraded it to Craft 5. In this package we have a Formie Stencil with following fields: Name (multiple: First Name and Last Name), E-mail, Multi-line text.

When trying to create a New Form or wanting to open the Stencils in Formie Settings I get following error: 
`Setting unknown property: verbb\formie\fields\Name::vid`

### Steps to reproduce

1. Having a Stencil with following fields: Name, E-mail, Multi-line text.
2. Upgrade to Craft 5
3. Click "New Form"

### Form settings

- Multi-page form: No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes

### Craft CMS version

5.1.8

### Plugin version

3.0.0-beta.14

### Multi-site?

Yes

**Comment by engram-design** [comment]
So `vid` would be a deprecated property that's been removed in Formie 3, and the [migration](https://github.com/verbb/formie/blob/craft-5/src/migrations/m240318_000000_migrate_stencils.php) _should_ be taking care of things like this.

For now, you can go to `/config/project/formie/stencils` and remove all `vid` instances just to get going again.

**Comment by HannahDeWachter** [comment]
Thanks @engram-design! This fixed it indeed.
