### ISSUE TITLE
Stripe payments displaying at 100x transacted value in submission CP view

### ISSUE THREAD

**Issue by jonnykates** [verbb/formie#1921]
### Describe the bug

We have a form with a Stripe integrated 'Payment' field which derives its amount value from a 'Radio Buttons' field on the form. When the form is submitted, the user's payment card is charged the correct amount based off the `value` of their radio button field section. However, when the form submission is browsed in `/admin/formie/submissions/`, the value in the right-hand payments meta area seems to be 100 times the amount charged. Smells a bit like pence/cents values are being displayed as pounds/dollars.

The PI in Stripe:
![Screenshot 2024-06-10 at 14 42 41](https://github.com/verbb/formie/assets/1444970/1da821d5-5c08-4bc2-bd71-d254585de651)

The payment meta on the submission in CP:
![Screenshot 2024-06-10 at 14 41 32](https://github.com/verbb/formie/assets/1444970/cdfb6d35-a461-446b-bf59-4a2d724dffdf)

### Steps to reproduce

1. Set up and enable a Stripe Formie integration
1. Create a form with a Radio Buttons field with some integer values in (other field types may be affected, I haven't tested)
2. Add a payment field to the form, and derive the amount to charge from the radio buttons field
3. Submit the form - the Stripe payment intent should be for the correct amount
4. Navigate to the submission in the Craft CP - the value displayed is 100x the transacted amount

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.1.9

### Plugin version

3.0.0-beta.14

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.14"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.15](https://github.com/verbb/formie/releases/tag/3.0.0-beta.15)
