### ISSUE TITLE
Formie will not update a User, but instead tries to create a new User

### ISSUE THREAD

**Issue by MattWilcox** [verbb/formie#1923]
### Describe the bug

We have a "Membership Subscription" form in Formie, where an existing User is logged in. They must fill out the form:

- They have to agree to the Terms to show the payment field
- They must pay the subscription

Things work up to that point.

However, we want the integration to change the User's Group if the payment completes sucessfully; going from "Public Member" to "Subscribed". From what I can tell, the settings seem to allow for that use case. However, Formie is always trying to create a new user instead of saving the change to the group membership of the current user.

![Screenshot 2024-06-11 at 10 20 07](https://github.com/verbb/formie/assets/814039/2a7d145e-731b-43f7-8051-e1810003f1c7)

The email field is required it seems, so we've added it as a hidden field set to the current user.

![Screenshot 2024-06-11 at 10 23 38](https://github.com/verbb/formie/assets/814039/4b43582a-82f6-4d4b-85e2-6d1499f600ec)

The integration is set up as follows:

![Screenshot 2024-06-11 at 10 20 27](https://github.com/verbb/formie/assets/814039/73aae264-7186-4fc4-9d24-327f2282e8da)

The form is rendered with:

```
{% set form = craft.formie.forms({ handle: 'sparkUser' }).one() %}
{{ craft.formie.renderForm(form) }}
```

And the error we get when submitting the completed form is:

![Screenshot 2024-06-11 at 10 25 24](https://github.com/verbb/formie/assets/814039/a4fdfade-e7ce-4f95-977c-f34579d32067)

Which reads to me as though it's still trying to make a new user instead of updating the current user.

### Steps to reproduce

As above

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.1.8

### Plugin version

3.0.0-beta.14

### Multi-site?

No

**Comment by engram-design** [comment]
This would be because you have nothing in the "Update Element Mapping" setting. You need to select _something_ to be used to compare against an existing user, otherwise how will Formie know how to define an existing user? This'll probably be the "email" field you have mapped.

**Comment by MattWilcox** [comment]
Ahhh, I assumed that the "User Attribute Mapping" would be what is used to find the existing user (which is why i set the email mapping there), and that the "Update Element Mapping" was just for choosing fields you wanted to have updated on the already selected user (which is none in our case).

Not that they were entirely separate things. Will change that and re-rty - thanks.

**Comment by engram-design** [comment]
Yeah, sorry for the confusion there! The tricky thing with that approach would be that you might want to control them independently, so one of the fields might always change (like a Date or something), but you want to match against a user with an email, but if it tries to find a User with that email + date value it'll never match.

I believe I had a similar issue explaining that writing Feed Me at the time 🥲

**Comment by MattWilcox** [comment]
Makes sense, just a different sense than the one I had in my head, lol! Cheers :)
