### ISSUE TITLE
Create calculation based on other calculation field

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/formie#1926]
### What are you trying to do?

We want to add a calculation based on another calculations field but the first calculation field is not appearing in the fields dropdown:
![image](https://github.com/verbb/formie/assets/42932673/a743dd63-3115-4f44-8ff5-18e115aa04d4)

### What's your proposed solution?

Is it possible to add a previous calculation field in the selectable fields in another calcuation?

### Additional context

Craft version: 4.8.4
Formie version: 2.1.7

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Added in [2.1.19](https://github.com/verbb/formie/releases/tag/2.1.19)
