### ISSUE TITLE
Condition with a calculation field

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/formie#1928]
### Describe the bug

We are experiencing issues when we want to set a condition with a calculation field.
Is this not possible like this?

![image](https://github.com/verbb/formie/assets/42932673/f4caf444-2ea6-410a-a32a-d67aed08174f)

### Steps to reproduce

1. Create a calculation field
2. Create another field and set the condition to show this field to the first calculation field > number.
3. The second field is never showing

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.8.4

### Plugin version

2.1.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Fixed in [2.1.19](https://github.com/verbb/formie/releases/tag/2.1.19)
