### ISSUE TITLE
Support CSS Layers

### ISSUE THREAD

**Issue by MattWilcox** [verbb/formie#1933]
### What are you trying to do?

I just want to override the default CSS _from my own CSS_.

Because of the way Formie adds its own CSS files, I'm having to fight specificity because my own CSS is trying to apply on the `:root` but Formie's stuff comes later and smashes it.

If it wrapped its own code in a named CSS layer, I could slot Formie's CSS anywhere in my preferred layer ordering, negating cascade issues.

https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

### What's your proposed solution?

Wrap all the Formis CSS in 

```
@layer formie {
    ...
}
```

So that in my own CSS I can more easily over-ride things without the crutch of loading order or chaining specificity.

**Comment by engram-design** [comment]
I've actually had zero experience with CSS Layers so far, so I'll have to do some reading and check browser compatibility!

**Comment by MattWilcox** [comment]
Been using it for a while, just in the one specific way - I *believe* it'd be just "wrap your existing CSS in a named layer", but yeah... not 100% confident on that.

For example, my initial CSS has 

```css
@layers reset, default, design, utilities;
```

Which sets the order that they apply in, and specificity *between* them doesn't matter. Whichever layer was last declared in that list wins regardless.

So ideally, if Formie came wrapped in one named `formie` I'd set my own CSS layer order as

```css
@layers reset, formie, default, design, utilities
```

So your code is loaded with less priority than my own code, meaning I could easily over-write it from any of my later layers (default, design, utilities).

https://caniuse.com/css-cascade-layers

**Comment by engram-design** [comment]
I've just added this as a plugin setting for the next release, to allow it as an opt-in setting while we continue to test it a bit more.

To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.15"`. 

Then, add `'useCssLayers' => true,` to your [configuration](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) file.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.16](https://github.com/verbb/formie/releases/tag/3.0.0-beta.16)

**Comment by MattWilcox** [comment]
Agh, sorry - missed that update; great stuff, thanks!

**Comment by MattWilcox** [comment]
I have had a thought, that may make this even more helpful:

Would it be possible to use a preference to set the layer name? This would allow people to use the nesting capability of CSS Layers too if needed (I don't, but some might), so they could pass "third-party.formie" to the plugin which could then output:

```
@layer third-party.formie {
    ...
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/@layer#nesting_layers

Could potentially just replace `'useCssLayers' => true` with `'cssLayersName' => 'anything'` and require people to choose a layer name to opt-in?

**Comment by engram-design** [comment]
I don't think that'll be possible I'm afraid, as we've have to pass in a variable to a CSS file, which isn't going to work. Having the CSS rendered inline is also not an option due to how you an configure how to output the CSS.

I'll look into options.

**Comment by MattWilcox** [comment]
No worries, was just a thought :)
