### ISSUE TITLE
[3.x]: Issue with summary and subfield

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1936]
### Describe the bug

The field summary shows the subfield `Middle Name` from the field `Name` even though it is not enabled.
The field  `Adresse` has the same issue.
The subfield `Prefix` is always empty,

### Steps to reproduce

1. Add the field name
2. Enable `Use Multiple Name Fields`
3. Enable the fields `First Name`, `Last Name`, and `Prefix` 
4. Add the field summary
5. Fill out the form
6. The summary shows the field `Middle Name`
7. The field `Prefix` is empty  

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax and Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.2.0

### Plugin version

3.0.0-beta.15

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.15"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.16](https://github.com/verbb/formie/releases/tag/3.0.0-beta.16)
