### ISSUE TITLE
[2.x]: Translation problem with subfield prefix and mail var `All Form Fields`

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1938]
### Describe the bug

I have a form on a German site.
in the frontend, the dropdown options get translated to Herr, Frau, ... 
The values are in English `mr`,`mrs`... which is alright since these values are fix and shared over multiple sites/languages.
In the Email with the variable `All Form Fields` the field doesn't get translated.

I also try to add them to /de/formie.php without success. 
```
'mr' => 'Herr',
'mrs' => 'Frau',
'ms' => 'Frau',
```

### Steps to reproduce

1. Change the site to german 
2. Import this form [formie.json](https://github.com/user-attachments/files/15883422/formie-prefix-c000c2b5-eefc-4e01-9bc7-768546648079.json)
3. Submit the form 
4. Open the notification
5. The value of the field prefix is not translated

#### Small side note
The email preview shows the label and not the value of the field.

### Form settings

- Multi-page form: Yes
- Custom Form Templates: No

### Craft CMS version

4.10.1

### Plugin version

2.1.19

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.19"`.

**Comment by engram-design** [comment]
Fixed in [2.1.20](https://github.com/verbb/formie/releases/tag/2.1.20)
