### ISSUE TITLE
Address -> Country field isn't saving

### ISSUE THREAD

**Issue by chrisrowe** [verbb/formie#1946]
### Describe the bug

When the Option Value is set to "Full Name" ie United States, over "Abbrivated" ie US the submissions don't include this field.

### Steps to reproduce

Complete the form

### Form settings

Defaults

### Craft CMS version

4.8.10

### Plugin version

2.1.18

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Fixed in [2.1.20](https://github.com/verbb/formie/releases/tag/2.1.20)
