### ISSUE TITLE
[2.x] Translate issue frontend validation.

### ISSUE THREAD

**Issue by Numkil** [verbb/formie#1948]
### Describe the bug

JS Frontend validation is not working for me when trying to translate validation errors to dutch [nl-BE].

I see that in the html of the form a script tag window.FormieTranslations has been created. Which Does contain the correctly translated dutch validation error messages. So the static translation stuff seems to be working correctly. 

However when the validation errors are displayed I still get shown the English errors instead of the translated ones. 

<img width="1125" alt="Screenshot 2024-06-18 at 12 17 03" src="https://github.com/verbb/formie/assets/5604686/b01aac37-6754-49c8-ba67-12751f890176">

### Steps to reproduce

1. Create a basic form in the backend with option 'frontend js validation' enabled.
2. Go to a page with the formie form with locale nl-BE
3. Submit form without filling in any fields
4. see errors being displayed in english instead of dutch

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.10.1

### Plugin version

2.1.19

### Multi-site?

yes

**Comment by engram-design** [comment]
Strange, I just did a quick test with German and that's working correctly 
<img width="425" alt="image" src="https://github.com/verbb/formie/assets/1221575/95e7b007-f4e8-4bf5-892e-552bb6992fbf">

And in a `/translations/de/formie.php` file:

```php
<?php
return [
    'Please fill out this field.' => 'Please fill out this field - translated.',
];
```

**Comment by Numkil** [comment]
Yeah im not sure whats happening either.

In the HTML of the form I see this. Which does seem to point to the issue being somewhere in the javascript side. 

![Screenshot 2024-06-20 at 09 45 07](https://github.com/verbb/formie/assets/5604686/dce1cf22-cd28-482f-aa09-1ed316fbdbe5)

![Screenshot 2024-06-20 at 09 36 35](https://github.com/verbb/formie/assets/5604686/9b310ffc-b475-48c0-a3cd-19a14c4dd666)

There are no console errors either. Wondering what else I could have misconfigured or something for it to not be working.

**Comment by Numkil** [comment]
I figured it out. I was some custom JavaScript interfering with the formie translations. Sorry about the confusion
