### ISSUE TITLE
Encrypted phone number exceeds 255 character limit

### ISSUE THREAD

**Issue by mjniland1** [verbb/formie#1955]
### Describe the bug

We have a form that contains a phone number with encryption turned on. The form was working as intended up until a recent update and now the form throws the error: "Phone Number should contain at most 255 characters." when a user attempts to submit it. Setting `enableLargeFieldStorage` to `true` in the formie.php config and then re-saving the form appears to have solved the issue for the time being.

### Steps to reproduce

1. Create a form that contains a phone number 
2. Enable encryption on that phone number field
3. Attempt to submit the form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.9.7

### Plugin version

2.1.18

### Multi-site?

No

**Comment by engram-design** [comment]
This is a good call with _any_ field that uses content encryption - we probably should enforce `TEXT` storage for content as a good measure for this.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Fixed in [2.1.20](https://github.com/verbb/formie/releases/tag/2.1.20)
