### ISSUE TITLE
Bug: number doesn't respect max value

### ISSUE THREAD

**Issue by sa-mussen** [verbb/formie#1959]
### Describe the bug

I have a form with a number field with a max value. 
However, the form allows submissions even when the entered value exceeds this max value. 

The expected behavior here is an error message, preventing the form from being submitted.

### Steps to reproduce

1. Create form with number field
2. Set min and max values in number field
3. Save form
4. Submit the form with an input higher than the max value

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes (but took the renderOptions off and it was the same issue)

### Craft CMS version

5.2.3

### Plugin version

3.0.0-beta.16

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.16"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.17](https://github.com/verbb/formie/releases/tag/3.0.0-beta.17)
