### ISSUE TITLE
Entries field selection not showing on the Submissions listing

### ISSUE THREAD

**Issue by j-greig** [verbb/formie#196]
The selection for the Entries field is not showing in the Submissions list.

It does show correctly when you click to view the individual submission however.

![image](https://user-images.githubusercontent.com/616194/97564003-d232aa00-19db-11eb-89a1-b920d6952c2a.png)

**Comment by engram-design** [comment]
Fixed in [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25)
