### ISSUE TITLE
Refresh Tokens Cached on Craft Cloud

### ISSUE THREAD

**Issue by shennyg** [verbb/formie#1963]
### Describe the bug

Hey there. I'm launching a Craft Cloud site tomorrow and getting past some final QA bugs.

Looks like https://PROJECT-NAME-production-5cd1c590.preview.craft.cloud/actions/formie/forms/refresh-tokens?form=footerSignup is a GET and returning a cache HIT. Craft Cloud is cached using CloudFlare.

I am on Formie version 2.1.17 and I don't see any changes in the changelog since related to refresh tokens. I am looking at the latest on v4: https://github.com/verbb/formie/blob/craft-4/src/controllers/FormsController.php#L371-L398

It looks like we need to add `$this->response->setNoCacheHeaders();` More info from Craft on opting out of caching here: https://craftcms.com/knowledge-base/cloud-static-caching#opting-out

As a hotfix I've done this, we are using your [Cached Forms Advanced Usage](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms#advanced-usage) approach:

```
 -       fetch('/actions/formie/forms/refresh-tokens?form={{ form.handle }}')
+        fetch('/actions/formie/forms/refresh-tokens?form={{ form.handle }}&cache-workaround=' + Math.random())
```

Thanks so much!

### Steps to reproduce

1. setup site in craft cloud
2. set to production mode so caching is enabled
3. setup advanced usage style cached form
4. submit form twice and get a CSRF error

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.10.2

### Plugin version

2.1.17

### Multi-site?

No

**Comment by engram-design** [comment]
I'm not a Craft Cloud expert (yet), but I'm surprised that any control action endpoints are being cached - I don't think they _should_ be. Probably only an issue for GET requests. I'll check out the `setNoCacheHeaders()` option, that's probably a quick-and-easy fix.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.20"`.

**Comment by shennyg** [comment]
Thanks @engram-design

**Comment by timkelty** [comment]
> but I'm surprised that any control action endpoints are being cached - I don't think they should be.

Craft Cloud doesn't discriminate on any specific paths/actions for caching. It will cache any 200 GET response unless no-cache headers have been set.

The problem is here:

```
        // Ensure that the session has started, just in case
        Session::exists();
```

That comment is not accurate – The `\craft\helpers\Session` methods specifically _don't_ start a session if they don't need to, including that one. If you want to ensure a session has started, you should call  `\craft\web\Session::open`, which in turn would set no-cache headers when starting a session, and the request wouldn't be cached.

That all said, I'm wondering if maybe `\craft\web\Request::getCsrfToken` should just set no-cache headers so the caller wouldn't have to worry about cache 🤔

**Comment by timkelty** [comment]
@engram-design as of [4.10.4](https://github.com/craftcms/cms/releases/tag/4.10.4)/[5.2.5](https://github.com/craftcms/cms/releases/tag/5.2.5), any request that generates a CSRF token will get no-cache headers applied.

**Comment by engram-design** [comment]
Appreciate the heads-up there, not sure why I went with `Session::exists()`. And thanks for that change!

**Comment by engram-design** [comment]
Fixed in [2.1.21](https://github.com/verbb/formie/releases/tag/2.1.21)

**Comment by jamesmacwhite** [comment]
For info to revisit this, it is proposed in Craft CMS 4.14 and 5.6 that all action controllers will send no cache headers by default which will be done by the Craft CMS Web Application class, to essentially prevent this scenario and others happening.

It does change the default static caching behaviour of Craft Cloud but ultimately, likely defends against this issue occurring in other contexts, which has happened and will probably continue to happen.

Having any GET request cached might be too aggressive and I think a few cases more recently have highlighted that having it happen on action controllers, is potentially going to lead to bad things.

More info: https://github.com/craftcms/cloud/discussions/54

**Comment by engram-design** [comment]
Thanks for looping me in on that @jamesmacwhite and those upcoming changes.
