### ISSUE TITLE
Notification conditions bug when updating status of the submission inside the control panel

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#1964]
### Describe the bug

I have a set of custom status to be set on submissions. When changing the status in the CP and saving, the wrong notification gets send our.

Inside of my form, I have conditions attached to the notification, which checks on the status. When I update the status, it sends our the notification option + 1 from the list.

So I have:
- new
- needsApproval
- approved
- completed

When I select needsApproval, the approved email notification gets sent out.

### Steps to reproduce

1. Create a set of custom status (Status A, Status B)
2. Create a notification with condition it sends out when Status A gets selected
3. Go to the submissions in the CP and click on one
4. Select Status A inside of the status dropdown and save the submission
5. See the mail for Status B coming in

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.2.4.1

### Plugin version

3.0.0-beta.16

### Multi-site?

yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.16"`.

**Comment by cookie10codes** [comment]
thx @engram-design

**Comment by cookie10codes** [comment]
@engram-design there's still a dump somewhere (after I proceed to the next page in my form, I receive a response of 1 😄 )
