### ISSUE TITLE
Prevent the user from creating fields with the handle "Status"

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#1967]
### What are you trying to do?

When a user creates a field, prevent them to name the field handle `status`. This interferes with the possible conditions on the email notifications, as it picks the fields above the actual status

### What's your proposed solution?

When a user creates a field, prevent them to name the field handle `status`. This interferes with the possible conditions on the email notifications, as it picks the fields above the actual status

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.20"`.

**Comment by engram-design** [comment]
Fixed in [2.1.21](https://github.com/verbb/formie/releases/tag/2.1.21)
