### ISSUE TITLE
Permissions claim for email notifications sub-tab items not respecting setting

### ISSUE THREAD

**Issue by jonnykates** [verbb/formie#1977]
### Describe the bug

Formie's user permissions claims include some settings to reveal the 'email notification advanced tab', and the 'email notifications templates tab';

![Screenshot 2024-07-11 at 13 50 36](https://github.com/verbb/formie/assets/1444970/1ecb5747-dd1f-4196-9829-88863cb50c70)

These claims do not seem to be respected when applied to a user group. See screenshot below impersonating a non-admin user that is in a user group that should have permission to see these tabs;

<img width="1792" alt="Screenshot 2024-07-11 at 13 51 44" src="https://github.com/verbb/formie/assets/1444970/2c2a8521-703a-43e5-874a-38f71fc45ab2">

### Steps to reproduce

1. Create a user group and give them access to see the advanced and templates tabs on email notifications
2. Impersonate a non-admin user with those user group claims
3. Expected behaviour would be to see the 'advanced' and 'templates' tab when editing an email notification for a form

### Form settings

- Multi-page form: No (n/a)
- Submission Method: Page Reload (n/a)
- Client-side Validation: Yes (n/a)
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.2.5

### Plugin version

3.0.0-beta.16

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.16"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.17](https://github.com/verbb/formie/releases/tag/3.0.0-beta.17)
