### ISSUE TITLE
Ability to access submitted field data on the Redirect Entry that a user is redirected to

### ISSUE THREAD

**Issue by j-greig** [verbb/formie#198]
**What are you trying to do?**
On submitting a form, we'd like to access the field data that was submitted on the entry that the user is redirected to.

In our particular case, the user will have selected an entry in an Entry Field, and we want to access the slug of this selected entry on the "Download your brochure" page that they are taken to, so that we can retrieve the correct PDF download for this entry.

**What's your proposed solution?**
Whatever you think would work best :)

**Comment by engram-design** [comment]
The only real way to achieve this at the moment is to modify the redirect URL in your templates to add a query string of the submission ID to the entry URL. For example:

```twig
{% set form = craft.formie.forms.handle('contactForm').one() %}

{% do form.setSettings({
    redirectUrl: form.getRedirectUrl() ~ '?submissionId={id}',
}) %}

{{ craft.formie.renderForm(form) }}
```

Then on your resulting page, you can check for `craft.app.request.getParam('submissionId')` and go from there to fetch the submission.

See [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25) where the above is implemented.

**Comment by j-greig** [comment]
Awesome, thank you again : )

One question.... something is wrong in my implementation below because the id in the slug just comes out as `?submissionId={id}` rather than the actual ID ... what have I done wrong?

`{# FORM BLOCK #}
{# Get the selected Formie form #}
{% set formSelection = block.form.one() %}
{% set formHandle = formSelection.handle %}
{% set form = craft.formie.forms.handle(formHandle).one() %}

{% do form.setSettings({
    redirectUrl: form.getRedirectUrl() ~ '?submissionId={id}',
}) %}

<section class="py-24 px-8 md:px-12">
	<div class="{{ siteWidth }}">
		<div class="md:flex md:items-center">
			{# Text #}
			<div class="w-full md:w-6/12 pr-4">
				<h2 class="{{ ss.h3 }}">{{ block.headline }}</h2>
				<div class="max-w-md">
					{{ block.description|retcon([
						['attr', 'h2', { class: 'text-3xl' }],
						['attr', 'h3', { class: 'text-2xl' }],
						['attr', 'p',  { class: ss.body }],
						['attr', 'a',  { class: 'underline' }]
					]) }}
				</div>
			</div>
			{# Form #}
			<div class="w-full mt-12 md:mt-0 md:w-6/12 md:p-8 flex justify-center items-center">
				<div class="w-full sm:w-8/12 md:w-auto">
					{{ craft.formie.renderForm(form) }}
				</div>
			</div>
		</div>
	</div>
</section>
`
