### ISSUE TITLE
Phone field - Countryallowed & selection & default-country missing in Graphql Shema 

### ISSUE THREAD

**Issue by The-Dan-Main** [verbb/formie#1983]
### Describe the bug

With Craft 4, it was possible to query for "pre-dial" (country enabled, selection of countries, default country). With craft 5, those options are missing in the shema & field-type and are not open for query, even though they exist. 

### Steps to reproduce

1. Craft 5.2.8
2. Formie 3.0.0-beta.17

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates: GraphQL

### Craft CMS version

5.2.8

### Plugin version

3.0.0-beta.17

### Multi-site?

no

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.17"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.18](https://github.com/verbb/formie/releases/tag/3.0.0-beta.18)
