### ISSUE TITLE
[3.x] 'Available Days' not working

### ISSUE THREAD

**Issue by vandres** [verbb/formie#1985]
### Describe the bug

Settings the 'Available Days' days is not working and makes the calendar "disabled".

The problem seems to be in `getDisabledWeekdays`. `this.availableDaysOfWeek` is an array of numbers, but the `date.getDay()` is cast to string. Both should be casted to the same.

```
    getDisabledWeekdays(date) {
        if (this.availableDaysOfWeek !== '*') {
            return (this.availableDaysOfWeek.includes(date.getDay().toString())) ? false : true;
        }

        return false;
    }
```

### Steps to reproduce

1. Add date field
2. Select advanced calendar
3. Change 'Available Days' to 'Friday' 
4. Look at the form in the frontend (locale DE)

![Bildschirmfoto 2024-07-22 um 16 14 51](https://github.com/user-attachments/assets/0d8f6ca3-4768-456e-9f5d-f4c0c1481b3e)
![Bildschirmfoto 2024-07-22 um 16 14 25](https://github.com/user-attachments/assets/7d9a78fd-633d-4eaa-8a02-7a8881d3b361)

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

### Craft CMS version

5.2.8

### Plugin version

3.x

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by vandres** [comment]
Works for me. Thanks!
