### ISSUE TITLE
Custom Email Marketing integration, with manual opt-in

### ISSUE THREAD

**Issue by vandres** [verbb/formie#1987]
### Question

We would like to create a custom Email Marketing integration for us. We are using Mad Mimi as a provider.

The API for Mad Mimi is straight forward, but has a major flaw. It cannot trigger the opt-in functionality. This is only possible over their provided web forms.

Since we are already using Formie (3.x), we would love to reuse the forms for the subscription. But instead of sending the payload directly over the API, we would need to trigger the opt-in:

1. user fills out form
2. forms get validated
3. upon success, generate some kind of token
4. generate verification url
5. send email with that url to the user
6. upon verification validate the token
7. after validation send the payload

I would assume step 3,4 and 6 is on our side. But how to best integrate it with Formie to use it for the other parts?

**Comment by engram-design** [comment]
I've not used (or heard of) Mad Mimi, but I would think that their [lists/add-membership](https://madmimi.com/developer/lists/add-membership) endpoint would suffice to add a user to a list?

I'm not across the opt-in mechanics they provide, but from your steps that is indeed a little tricky and complicated. I'd say steps 3-7 will need to be triggered by yourself in a module.

Steps 3-4 will be on your end to figure out, and you can use Craft's mailer to send out an email from Craft itself for steps 5. I'm not sure if the opt-in email should come from the provider or if you need to send it. Typically for modern systems, you don't have to send this yourself. I imagine the verification URL will be on the provider end? Or will it be a custom controller endpoint on your end?

Then for step 6 I guess you'll need to listen to the provider via webhook or similar for when things are verified. Or, if you handle that yourself, that's a bit easier. You'll then be able to complete step 7 by sending the payload as normal.

So where you might normally have logic in `sendPayload()` this would just be steps 4-5. You'll just need some sort of way to handle the "callback" from the opt-in - however that looks.

**Comment by vandres** [comment]
Thank for the reply! 

Yeah, I will need to create some custom controller in our module as a verification endpoint for the link. I was just hoping, I could somehow reuse the Formie mailer. In conclusion, I will need to do step 3-7 on our side and will use `sendPayload()` as an entry point.

You are right, normally the provider (Mad Mimi) should handle the verification kind of things. But after talking to their support, there is not an API way to either let them handle the verification progress or at least send an email.
