### ISSUE TITLE
Stripe: 'Billing Details' mapped fields do not save

### ISSUE THREAD

**Issue by jonnykates** [verbb/formie#1992]
### Describe the bug

I have a connected Stripe integration. When I add a payment field to my form and navigate to the 'Settings' tab, there is an area to map other fields from my form into the 'Billing Details' for Stripe.

I'm able to select fields from these dropdowns, however when I save the form they are wiped out. Sometimes, it even crashes the entire application.

### Steps to reproduce

1. Connect a payment integration to Stripe (I haven't tested other payment providers)
2. Create a form with a payment field, and fields to capture the submitter's name, email, and address
3. On the payment field, navigate to the 'settings' tab and select your other fields in the 'Billing Details' section
4. Click 'Apply' on the payment field settings modal to close it
5. If you now click on your payment field again to open the settings, the application hangs
6. If you **don't** re-open the payment field settings and instead save the form the mapped billing detail values have been removed

I can't see anything in the Craft logs to debug what is happening at step #5.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.2.8

### Plugin version

3.0.0-beta.18

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.19](https://github.com/verbb/formie/releases/tag/3.0.0-beta.19)
