### ISSUE TITLE
[3.0.0-beta.18] - Unable to migrate Freeform forms

### ISSUE THREAD

**Issue by zizther** [verbb/formie#1994]
### Describe the bug

When trying to migrate Freeform forms to Formie I get the error message `Cannot use Solspace\Freeform\Library\Composer\Components\FieldInterface as FieldInterface because the name is already in use` `vendor/verbb/formie/src/migrations/MigrateFreeform.phpat line 34`

### Steps to reproduce

N/A

### Form settings

N/A

### Craft CMS version

5.2.8

### Plugin version

3.0.0-beta.18

### Multi-site?

No

### Additional context

Using Freeform 5.5.4

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.19](https://github.com/verbb/formie/releases/tag/3.0.0-beta.19)
