### ISSUE TITLE
[3.0.0-beta.19] Unable to select form from index when user isn't admin

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/formie#1996]
### Describe the bug

If a user isn't full admin, they can't go to a form from the form index anymore. A direct link is working.

### Steps to reproduce

1. Have a user which isn't full Craft admin
2. Try to open a form
3. You can't, only an empty slideout

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

Craft Pro 5.2.9

### Plugin version

3.0.0-beta.19

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.19"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.20](https://github.com/verbb/formie/releases/tag/3.0.0-beta.20)
