### ISSUE TITLE
Forms templates - toggling off "Output CSS" doesn't toggle off "Output Theme"

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#2]
### Description
If I create a form template, by default both Output CSS and Output Theme are activated. If I disable Output CSS, then Output Theme gets hidden, but is still toggled. So the theme is still being outputted in the front-end. 

It should be unticked when you untick Output CSS.

### Steps to reproduce

1.
2.

### Additional info

- Plugin version: 1.0.1
- Craft version: 3.4.28.1

**Comment by jaydensmith** [comment]
Thanks, @bleepsandblops, fixed in [1.0.2](https://github.com/verbb/formie/releases/tag/1.0.2).
