### ISSUE TITLE
Field Limit validation Value is not working

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#2000]
### Describe the bug

Field Limit validation Value is not working.
Both option - characters and words.

### Steps to reproduce

1. Install formie
2. Configure field limit
3. Test it

![изображение](https://github.com/user-attachments/assets/eae0c336-297d-461e-a2e1-ac890d11b7c0)
![изображение](https://github.com/user-attachments/assets/afc2727a-421a-40a6-9cd5-01f8a5cf8293)
![изображение](https://github.com/user-attachments/assets/e9e046dd-cfe8-405e-ae4f-b5427f9d4d1e)
![изображение](https://github.com/user-attachments/assets/558f111a-749f-440c-a9a5-64bd9cfea6e6)
![изображение](https://github.com/user-attachments/assets/3ceb408b-937d-4692-b39f-e900c17f4f18)

### Form settings

- Multi-page form: Yes or No - Both
- Submission Method: Ajax or Page Reload - Both
- Client-side Validation: Yes or No - Both
- Custom Form Templates: No

### Craft CMS version

Craft Solo 5.2.9

### Plugin version

3.0.0-beta.20

### Multi-site?

No

**Comment by engram-design** [comment]
Do note that we don't enforce the values client-side (and don't in Formie 2.x either). I'm wondering if - judging by the other errors there in fields - that this is client-side validation, and there's no messages for this showing?

**Comment by umkasanki** [comment]
Yes. These screenshots are made with a save and validation on client-side.
But with the server side we have the same behavior, - also don't see any limit errors.
Just to know: This issue also occurred on Formie 2.1.23 with Craft 4.


https://github.com/user-attachments/assets/a6615265-c400-4df7-a95c-144b6bdc49f3

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.20"`. 

This includes client-side validation, and while server-side is working, there was an issue with min-words - all others were working correctly.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)

**Comment by umkasanki** [comment]
Could you also fix it for Craft 4?

**Comment by engram-design** [comment]
I'll see what I can do about this, but the validation is radically different for Formie 2 for Craft 4. The server-side fixes are in place at least.
