### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Class verbb\formie\fields\Address contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (craft\base\Grippable::getHandle, craft\base\CpEditable::getCpEditUrl

### ISSUE THREAD

**Issue by SantiagoMena** [verbb/formie#2002]
### Describe the bug

PHP Fatal Error 'yii\base\ErrorException' with message 'Class verbb\formie\fields\Address contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (craft\base\Grippable::getHandle, craft\base\CpEditable::getCpEditUrl)'

in /var/www/html/vendor/verbb/formie/src/fields/Address.php:35

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

### Steps to reproduce

1.  Upgrade "craftcms/cms": "^5.3.0-beta.1"
2.  run  craft entry-types/merge

### Form settings

Error on Upgrade "craftcms/cms": "^5.3.0-beta.1", missing implementation on /formie/src/fields/*

public function getHandle(): ?string
public function getCpEditUrl(): ?string

### Craft CMS version

5.3.0-beta.1

### Plugin version

3.0.0-beta.20

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.20"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
