### ISSUE TITLE
Refresh Tokens 404 Not Found

### ISSUE THREAD

**Issue by olihar** [verbb/formie#2004]
### Describe the bug

I have a formie form set up, which submits via Ajax to display a message. This was all working correctly.
However, I need to run some javascript before the form is submitted.
I have created a javascript file and have the following

`document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('#formOne form');
    if(form){
        form.addEventListener('onBeforeFormieSubmit', (e) => {
            e.preventDefault(); // Prevent the form from submitting
            // Save for later to trigger real submit
            submitHandler = e.detail.submitHandler;
            console.log('Form submission intercepted');
            initiateJavascript(submitHandler);
        });
    }

    function initiateJavascript(submitHandler) {
        //custom code runs then

                onSuccess: () => {
                    console.log('Payment successful');
                    submitHandler.submitForm();
                },
                onExit: (error, metadata) => {
                    console.error('Payment failed', error);
                    submitHandler.formSubmitError();
                }

    }
});`

onSuccess and onExit work as expected either submitting the form or returning an error.
However, although the form looks like it has submitted - it shows the success message. The entry isn't saved.
On looking in the browser console I get the following error 

https://preview.domain.com/actions/formie/forms/refresh-tokens?form=formOne 404 (Not Found)

this website is actually held in a folder since it's just a test dev environment. so the url should really be

https://preview.domain.com/siteFolder/web/actiions/formie/forms/refresh-tokens?form=formOne 404 (Not Found)

the site url is set to

https://preview.domain.com/siteFolder/web/

how do I get the js to reflect the sub folder in the refresh-tokens url?

### Steps to reproduce

1. Use javascript to submit form on success or failure of another javascript function
2. Success/Error works but doesn't submit the details
3. Browser console shows actions/formie/forms/refresh-tokens?form=formOne error
4. The actions/formie url isn't taking into account that the site is held in a folder despite the site url showing the folder

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.10.7

### Plugin version

2.1.23

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.23"`.

**Comment by olihar** [comment]
thank you, I'm getting the error in the browser console

domain.com/siteFolder/index.php?craft-path=actions/formie/forms/refresh-tokens?form=formOne 

page not found but the form seems to be submitting?

On a side note - and let me know if I need to open a new question.
But I have a module that generates an ID on EVENT_BEFORE_SUBMISSION_REQUEST and saves it in the session.
I then have a controller that gets the ID from the session and creates some JSON with the ID
My javascript then fetches the ID via ajax - however this is setup on onBeforeFormieSubmit event - I need to retrieve the ID before the form submits.
Problem is the onBeforeFormieSubmit event checks the JSON before the EVENT_BEFORE_SUBMISSION_REQUEST has successfully generated the ID.
How do I ensure the ID is generated in the module before the JSON is fetched.
Is it possible with this flow or do I need to completely restructure?

**Comment by engram-design** [comment]
The form will submit fine, this is the after-submit action, where it's going to try and refresh the captcha and CSRF tokens in case you want to submit the form again immediately after.

Can you please confirm what the base URL for you site is? Not the path to your site, the top-level URL to your homepage. I understood that to be `domain.com/siteFolder`. The `craft-path` also looks unusual.

You can actually confirm the correct path by going to in your browser the URL in question. For example - `https://domain.com/siteFolder/actions/formie/forms/refresh-tokens?form=formOne`. Maybe if you do some trial-and-error to find the correct URL? It's strange however, as we are using the `actionUrl` in Craft to determine what the path is to an action endpoint.

So you're right about those events, the JS `onBeforeFormieSubmit` is going to fire before you hit the server for anything, and the PHP `EVENT_BEFORE_SUBMISSION_REQUEST` event is once you hit the server. I think you might be better off creating your own JS `fetch()` in the `onBeforeFormieSubmit` to your own controller action to retrieve what you need.

**Comment by olihar** [comment]
Thank you, I approached this differently to solve the JS firing before the php event and the error went away so I think it must have been me misconfiguring something. When I went to my correct path the JSON was showing correctly.
