### ISSUE TITLE
Unable to create new stencil

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#201]
**Description**
When I try to add a stencil, I get the error
![изображение](https://user-images.githubusercontent.com/496132/97728537-bb2aaf80-1ae2-11eb-8080-20cd9296f577.png)

**Steps to reproduce**
1. Go to settings / stencils
2. Try to add new stencil

### Form settings
Please pick from the options below.

- Multi-page form: Yes or No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.24
- Craft version: 3.5.7
- Multi-site: Yes 

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25)
