### ISSUE TITLE
Slack integration fails when clicking connect - "Invalid client_id parameter"

### ISSUE THREAD

**Issue by andrewhawkes** [verbb/formie#2021]
### Describe the bug

I'm following the instructions in the integrations UI for setting up Slack.
I have followed the instructions and when I click connect, I get the following error from Slack:
```Invalid client_id parameter```

I have entered the redirect URL etc within Slack and it's publically available.

### Steps to reproduce

1. Set up Slack app and enter credentials
2. Click connect on the integration settings - it then fails

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.10.7

### Plugin version

2.1.23

### Multi-site?

no

**Comment by engram-design** [comment]
Are you able to confirm the "Client ID" value being used is correct? If you're using an .env variable, I might suggest removing that temporarily just to rule out that being an issue.

**Comment by shifuma** [comment]
Reporting that I see the same thing. With an environment variable I get the `Invalid client_id parameter` error, however, using the value directly I get `invalid_team_for_non_distributed_app`

**Comment by engram-design** [comment]
So _something_ odd is going on with the clientId being parsed as an `.env` variable. I have for example:

`SLACK_CLIENT_ID="2833563543.1341693891393"`, which when parsed results in `2833563543.1342` which is clearly truncated. I can see why this is an issue with the way that Craft normalized variables, as it thinks this is a float value, not a string. I'll make an issue with Craft about this.

As for the `invalid_team_for_non_distributed_app` error, that's a new one, and might not be related.

**Comment by andrewhawkes** [comment]
@engram-design sorry I haven't had a chance to look through this yet. But I am using env vars and I did notice the client ID did look truncated in the URL.

**Comment by engram-design** [comment]
Yup, just shot an issue on Craft about this https://github.com/craftcms/cms/issues/15533 and interested to see what comes of that. Otherwise, we'll need to come up with some unique handling of our own just for this case.

I'm interested to know if there's any further issues just hard-coding the client ID such as what @shifuma mentions?

**Comment by engram-design** [comment]
Should be fixed in [Craft 4.11.4](https://github.com/craftcms/cms/releases/tag/4.11.4)
