### ISSUE TITLE
Issue with mandatory field added via form template.

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2025]
### Describe the bug

I added a new mandatory field to my form template, the user can save the form without filling it out.

### Steps to reproduce

1. Add a new field to a form template
2. Make the field mandatory
3. Create a new form
4. Save the form
5. The mandatory field is not validated 

![image](https://github.com/user-attachments/assets/f10b899a-dc50-4c80-b139-c3f401ac3a6d)

### Form settings

Backend only

### Craft CMS version

4.11.3

### Plugin version

2.1.26

### Multi-site?

NO

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.26"`.

**Comment by engram-design** [comment]
Fixed in [2.1.27](https://github.com/verbb/formie/releases/tag/2.1.27)
