### ISSUE TITLE
Recent Form Submissions Widget visible to users with no Formie access

### ISSUE THREAD

**Issue by alexjcollins** [verbb/formie#2030]
### Describe the bug

It's possible for a user to add a Recent Form Submissions dashboard widget and see a list of submissions even if they don't have access to Formie. When clicking a submission, the user is correctly restricted, but it's possible that restricted information could be made visible to the user through the submission title.

### Steps to reproduce

1. Create a Craft control panel user with no Formie access
2. Log in as that user
3. Add a Recent Form Submissions widget to the dashboard

### Form settings

N/A

### Craft CMS version

5.3.4

### Plugin version

3.0.3

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/formie/releases/tag/3.0.4)
