### ISSUE TITLE
Email field doesn't validate inside of a repeater field

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#2031]
### Describe the bug

I'm using a repeater field with an email address field inside. The form itself submission method is "Page Reload (Server-side)" and doesn't validate on submit if that helps for replicating. 

If any additional info needed, let me know

### Steps to reproduce

1. Create a repeater field
2. Add an Email address field inside of the repeater
3. Add "x" as value
4. It gets submitted

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.3.4

### Plugin version

3.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/formie/releases/tag/3.0.4)

**Comment by cookie10codes** [comment]
thanks!
