### ISSUE TITLE
Add form as a type to the craft link field type

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [verbb/formie#2033]
### What are you trying to do?

Hi, 

Previously we used hyper for our buttons. Here we could add the option to select a form which would give the button a form popup behaviour.

### What's your proposed solution?

We would like to start using the new craft link field type ( craft 5 ). Is it possible to have forms added there as an option to select?

**Comment by engram-design** [comment]
Happy to add this functionality, but don't forget that Forms themselves can't actually be linked to, as they themselves don't have a URL. You'll need to use `{{ entry.linkField.getElement() }}` which returns a Form element, and you can render your form from that value.

Added for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.3"`.

**Comment by bob-pixeldeluxe** [comment]
Awesome, thanks!

**Comment by engram-design** [comment]
Added in [3.0.4](https://github.com/verbb/formie/releases/tag/3.0.4)
