### ISSUE TITLE
Klaviyo integration: only 10 lists shown

### ISSUE THREAD

**Issue by JoeriE** [verbb/formie#2039]
### Describe the bug

Hello,

I have a Klaviyo integration activated in my Formie settings. I want to map a form with the 'Email marketing' integration but I cannot see all my subscriber lists. Formie only shows 10 lists in the dropdown, but the Klaviyo has 20+ lists and the correct lists is not showing:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/b31da67d-d2d2-49c6-9cd0-3b2747865c6e">

### Steps to reproduce

1. Enable Klaviyo integration at 'Email marketing'
2. Make a form and add Klaviyo integration

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

### Craft CMS version

4.9.6

### Plugin version

2.1.16

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.26"`. Lists are now also alphabetically sorted.

**Comment by engram-design** [comment]
Fixed in [2.1.27](https://github.com/verbb/formie/releases/tag/2.1.27)
