### ISSUE TITLE
When sending an email notification - Add option to attach a PDF of submission data based on twig template.

### ISSUE THREAD

**Issue by TSeine** [verbb/formie#204]
**What are you trying to do?**
A description of what you want to happen.
When sending an email notification - Add option to attach a PDF of submission data based on twig template. 

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

**Additional context**

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
