### ISSUE TITLE
 fieldInputWrapper: false does not work when used on specific field type in themeConfig

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/formie#2040]
### Describe the bug

I want to hide the fieldInputWrapper on certain field types but it only works as a global setting.

### Steps to reproduce

1. Set fieldInputWrapper: false on for example singleLineText
2. Check if the div is still there
 

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

Craft Pro 5.3.5

### Plugin version

3.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/formie/releases/tag/3.0.4)

**Comment by angelokeirsebilck** [comment]
Name field not working.

This is my themeConfig.

`themeConfig: {
                        resetClasses: true,
                        formTitle: {
                            attributes: {
                                class: 'text-lg leading-6 font-medium text-gray-900'
                            }
                        },
                        alertError: {
                            attributes: {
                                class: 'not-prose bg-error/10 border border-error text-center text-balance !text-sm text-error !p-4 mb-4'
                            }
                        },
                        alertSuccess: {
                            attributes: {
                                class: 'not-prose bg-success/40 border border-success text-center text-balance !text-sm text-success !p-4 mb-4'
                            }
                        },
                        error: {
                            attributes: {
                                class: 'text-error'
                            }
                        },
                        errors: {
                            attributes: {
                                class: 'text-error'
                            }
                        },
                        buttonWrapper: {
                            attributes: {
                                class: [
                                    'flex justify-start ',
                                    "{{ buttonsPosition == 'right' ? 'justify-end' }}",
                                    "{{ buttonsPosition == 'center' ? 'justify-center' }}",
                                    "{{ buttonsPosition == 'left-right' ? 'justify-between' }}",
                                    "{{ buttonsPosition == 'right-save-left' ? 'justify-start flex-row-reverse' }}",
                                    "{{ buttonsPosition == 'center-save-left' ? 'justify-center flex-row-reverse' }}",
                                    "{{ buttonsPosition == 'center-save-right' ? 'justify-center' }}",
                                    "{{ buttonsPosition == 'save-right' ? 'justify-between' }}",
                                    "{{ buttonsPosition == 'save-left' ? 'justify-between flex-row-reverse' }}"
                                ]
                            }
                        },
                        buttonContainer: {
                            attributes: {
                                class: 'flex justify-start '
                            }
                        },
                        saveButton: {
                            attributes: {
                                class: ['btn btn-primary group mt-4']
                            }
                        },
                        backButton: {
                            attributes: {
                                class: ['btn btn-primary group mt-4']
                            }
                        },
                        submitButton: {
                            attributes: {
                                class: ['btn btn-primary group mt-4']
                            }
                        },
                        page: {
                            attributes: {
                                class: ["{{ form.hasMultiplePages() and page.id != currentPage.id ? 'hidden' : false }}"]
                            }
                        },
                        pageTabs: {
                            attributes: {
                                class: 'border-b border-gray-200 -mb-px flex space-x-8 mb-6'
                            }
                        },
                        pageTab: {
                            attributes: {
                                class: 'py-4 px-1'
                            }
                        },
                        pageTabLink: {
                            attributes: {
                                class: [
                                    'whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm',
                                    "{{ (page.id == currentPage.id) ? 'border-indigo-500 text-indigo-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300' }}",
                                    "{{ page.getFieldErrors(submission) ? 'text-red-500' : false }}"
                                ]
                            }
                        },
                        pageTitle: {
                            attributes: {
                                class: 'text-lg leading-6 font-medium text-gray-900 mb-4'
                            }
                        },
                        progress: {
                            attributes: {
                                class: 'flex h-[1.2rem] text-sm text-white bg-slate-200 mt-4'
                            }
                        },
                        progressContainer: {
                            attributes: {
                                class: 'flex flex-col justify-center text-center font-medium bg-indigo-600'
                            }
                        },
                        subFieldRow: {
                            attributes: {
                                class: 'flex flex-wrap gap-2 md:gap-0 flex-col md:flex-row -mx-2 '
                            }
                        },
                        nestedFieldRows: {
                            attributes: {
                                class: 'border py-4'
                            }
                        },
                        nestedFieldRow: {
                            attributes: {
                                class: 'flex flex-wrap gap-2 md:gap-0 flex-col md:flex-row'
                            }
                        },
                        row: {
                            attributes: {
                                class: ['flex flex-wrap gap-2 md:gap-0 flex-col md:flex-row -mx-2', "{{ row.getIsHidden() ? 'hidden' }}"]
                            }
                        },
                        field: {
                            attributes: {
                                class: 'px-2 flex-1 mb-6'
                            }
                        },
                        name: {
                            fieldInputWrapper: false,
                            field: {
                                attributes: {
                                    class: '!mb-0'
                                }
                            }
                        },
                        fieldLabel: {
                            attributes: {
                                class: ['mb-4 block text-xl text-black', _globals.get('blockBgColor') == 'bg-dark' ? 'text-white']
                            }
                        },
                        fieldRequired: false,
                        fieldInstructions: {
                            attributes: {
                                class: 'mb-1 text-sm text-gray-500'
                            }
                        },
                        fieldInput: {
                            attributes: {
                                class: [
                                    'outline-none shadow-none border placeholder:text-transparent border-x-0 border-t-0 aria-invalid:border-error focus:outline-none focus:ring-0 focus:border-primary focus:shadow-none border-black w-full py-3 px-0',
                                    "{{ (submission.getErrors(field.handle) ?? null) ? 'border-error' }}"
                                ]
                            }
                        },
                        fieldError: {
                            attributes: {
                                class: 'text-error text-xs mt-1'
                            }
                        },
                        fieldAddButton: {
                            attributes: {
                                class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-[15px] text-slate-700 bg-slate-200 hover:bg-slate-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500'
                            }
                        },
                        fieldRemoveButton: {
                            attributes: {
                                class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-[15px] text-slate-700 bg-slate-200 hover:bg-slate-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500'
                            }
                        },
                        fieldLimit: {
                            attributes: {
                                class: 'mt-2 text-sm text-gray-500'
                            }
                        },
                        dropdown: {
                            fieldInput: {
                                attributes: {
                                    class: ''
                                }
                            }
                        },
                        fileUpload: {},
                        agree: {
                            field: {
                                attributes: {
                                    class: '!mb-0 '
                                }
                            },
                            fieldOption: {
                                attributes: {
                                    class: 'flex items-center mb-1'
                                }
                            },
                            fieldOptionLabel: {
                                attributes: {
                                    class: [
                                        'ml-3 leading-4 prose-custom prose text-black prose-p:text-base',
                                        _globals.get('blockBgColor') == 'bg-dark' ? 'text-white prose-bgDark'
                                    ]
                                }
                            },
                            fieldInput: {
                                resetClass: true,
                                attributes: {
                                    class: 'accent-primary text-primary focus:ring-primary'
                                }
                            }
                        },
                        phoneNumber: {
                            fieldInputWrapper: false,
                            field: {
                                attributes: {
                                    class: 'not-prose'
                                }
                            }
                        },
                        emailAddress: {
                            fieldLabel: {
                                attributes: {
                                    class: ''
                                }
                            },
                            fieldInputWrapper: false
                        },
                        singleLineText: {
                            fieldLabel: {
                                attributes: {
                                    class: ''
                                }
                            },
                            fieldInputWrapper: false
                        },
                        multiLineText: {
                            fieldInputWrapper: false,
                            fieldInput: {
                                attributes: {
                                    class: '!border !px-2',
                                    rows: '3'
                                }
                            }
                        },
                        checkboxes: {
                            fieldLabel: {
                                attributes: {
                                    class: 'font-bold'
                                }
                            },
                            fieldContainer: {
                                attributes: {
                                    class: '!mb-0'
                                }
                            },
                            fieldInputWrapper: {
                                attributes: {
                                    class: ['relative', '{{ field.layout == "horizontal" ? "[&>div]:flex [&>div]:gap-x-4 [&>div]:flex-wrap"}}']
                                }
                            },
                            fieldOption: {
                                attributes: {
                                    class: 'flex items-center mb-1'
                                }
                            },
                            fieldOptionLabel: {
                                attributes: {
                                    class: ['ml-3 text-black', _globals.get('blockBgColor') == 'bg-dark' ? 'text-white']
                                }
                            },
                            fieldInput: {
                                resetClass: true,
                                attributes: {
                                    class: 'accent-primary text-primary focus:ring-primary'
                                }
                            }
                        },
                        hiddenField: {
                            field: {
                                resetClass: true,
                                attributes: {
                                    class: 'hidden'
                                }
                            }
                        },
                        radioButtons: {
                            fieldInputWrapper: {
                                attributes: {
                                    class: ['relative', '{{field.layout == "horizontal" ? "[&>div]:flex [&>div]:gap-x-4 [&>div]:flex-wrap"}}']
                                }
                            },
                            fieldOption: {
                                attributes: {
                                    class: 'flex items-center mb-1'
                                }
                            },
                            fieldOptionLabel: {
                                attributes: {
                                    class: ['ml-3 text-black', _globals.get('blockBgColor') == 'bg-dark' ? 'text-white']
                                }
                            },
                            fieldInput: {
                                resetClass: true,
                                attributes: {
                                    class: 'accent-primary text-primary focus:ring-primary'
                                }
                            }
                        },
                        recipients: {
                            field: {
                                attributes: {
                                    class: ["{{ row.getIsHidden() ? 'hidden' : false }}"]
                                }
                            }
                        },
                        repeater: {
                            nestedField: {
                                attributes: {
                                    class: 'relative'
                                }
                            },
                            nestedFieldWrapper: {
                                attributes: {
                                    class: 'mb-4'
                                }
                            },
                            fieldRemoveButton: {
                                attributes: {
                                    class: 'absolute top-0 right-0 m-1 inline-flex items-center px-2 py-1.5 border border-transparent text-xs font-medium rounded-[15px] text-slate-700 bg-slate-200 hover:bg-slate-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500'
                                }
                            }
                        },
                        html: {
                            fieldContainer: {
                                attributes: {
                                    class: [
                                        '{{field.handle == "recaptcha" ? "text-xs mt-2 prose prose-custom" : "prose prose-custom"}}',
                                        _globals.get('blockBgColor') == 'bg-dark' ? 'text-white'
                                    ]
                                }
                            }
                        },
                        signature: {
                            fieldInputContainer: {
                                attributes: {
                                    class: 'relative'
                                }
                            },
                            fieldCanvas: {
                                attributes: {
                                    class: 'w-full h-[8rem] border bg-slate-100'
                                }
                            },
                            fieldRemoveButton: {
                                attributes: {
                                    class: 'absolute top-0 right-0 m-1 inline-flex items-center px-2 py-1 border border-slate-300 text-xs font-medium rounded-[15px] text-slate-700 bg-slate-200 hover:bg-slate-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500'
                                }
                            }
                        },
                        table: {
                            fieldTable: {
                                attributes: {
                                    class: 'min-w-full divide-y divide-gray-300'
                                }
                            },
                            fieldTableHeaderColumn: {
                                attributes: {
                                    class: 'px-3 py-3.5 text-left text-sm font-semibold text-gray-900'
                                }
                            },
                            fieldTableBody: {
                                attributes: {
                                    class: 'divide-y divide-gray-200 bg-white'
                                }
                            },
                            fieldTableBodyColumn: {
                                attributes: {
                                    class: 'whitespace-nowrap px-3 py-4 text-sm text-gray-500'
                                }
                            }
                        }
                    }`

**Comment by engram-design** [comment]
You mentioned the Phone field not working as well. Can you confirm this, as that's working for me?

If you've got multi-name fields, I believe I may know the issue. These have been changed from Single-Line Text fields to their own [extended classes](https://github.com/verbb/formie/tree/craft-5/src/fields/subfields).

This is both good and bad from our perspective, in that you can now target sub-fields like `nameFirst` and `nameLast`, but bad in the sense that you have to duplicate your `singleLineText` theme config.

A minimal example working for me:

```twig
{{ craft.formie.renderForm(form, {
    themeConfig: {
        singleLineText: {
            fieldInputWrapper: false,
        },
        phoneNumber: {
            fieldInputWrapper: false,
        },
        name: {
            fieldInputWrapper: false,
        },
        nameFirst: {
            fieldInputWrapper: false,
        },
        nameLast: {
            fieldInputWrapper: false,
        },
    },
}) }}
```

`name` covers non-multi Name fields, `nameFirst` and `nameLast` covers multi Name fields (you can include other sub-fields if enabled).

I'll see what can be done to streamline this so that we can inherit theme config from the `singleLineText` and still also use the sub-field key for even more fine-grained control.

**Comment by angelokeirsebilck** [comment]
Yes, phoneNumber works now after the update.

Did not know about the sub name fields, works as intended, thanks.
