### ISSUE TITLE
Missing the general permission to manage Form Usage 

### ISSUE THREAD

**Issue by maikueo** [verbb/formie#2049]
### Describe the bug

<img width="324" alt="image" src="https://github.com/user-attachments/assets/561cb865-2ae6-4ce2-af40-204fc54142e5">

It seems that the checkbox to be able to allow permission for users to see the Usage tab is missing.
In the screenshot I've highlighted the missing option, which I've quickly tried adding manually in Formie.php, line 231 and works as expected.

### Steps to reproduce

1. go to User Permissions configuration page
2. Under Formie's permissions, the general "Manage form usage" option is missing 

### Form settings

- Any form

### Craft CMS version

4.3.2

### Plugin version

2.1.28

### Multi-site?

yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.28"`.

**Comment by engram-design** [comment]
Fixed in [2.1.29](https://github.com/verbb/formie/releases/tag/2.1.29)
