### ISSUE TITLE
Encrypt stored form data

### ISSUE THREAD

**Issue by jt-systems** [verbb/formie#205]
**What are you trying to do?**
It seems prudent that form submission data be utilise Craft's security methods  `[encryptByKey()]` so that sensitive data submitted though forms was not stored in the database in human readable form. 

**What's your proposed solution?**
Use the `SECURITY_KEY` stored in the .env file and Craft's [security methods ](https://docs.craftcms.com/api/v3/craft-services-security.html#public-properties)to encrypt stored form data in the database.

**Additional context**
We often deal with ~5k+ form submissions per day and are regularly asked about data security - currently we roll our own database encryption methods externally to Craft, however it seems like a relatively simple and available solution to encrypt at source.

**Comment by engram-design** [comment]
I'd say this is pretty highly debatable whether _all_ content should be stored in encrypted form. I'm not really keen on enforcing this for all fields.

Maybe the best way is to introduce an option per-field (or maybe per-form) to encrypt field data.

Personally, I find it pretty handy to be able to edit form data in the database, and appreciate the lack of overhead from encrypting/decrypting. It's also nice to detach the data from Craft itself (so it's not reliant on Craft to decrypt the data).

We'll shortly be introducing methods to not store data at all - if that helps?

**Comment by jt-systems** [comment]
Agreed - some data you wouldn't want/need to be stored encrypted; boolean values/ radios / checkboxes, to name a few. 

However a per field "encrypt this" option would prove a useful addition in storing submitted data that is deemed sensitive or personally identifiable (email addresses, names, telephone, DoB Etc)

On the [GDPR](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/) front it would certainly tick a few safeguarding / data protection boxes for those of us in the EU too.

**Comment by jt-systems** [comment]
On your last point about not storing data at all: If I'm assuming the approach correct (apologies if not) such a move would remove the ability to resend notifications, run reports, export the data store or query the datastore at all - so (for us at least) I'm not sure it would prove useful.

**Comment by engram-design** [comment]
@WeArePercipio Yep, so we've got some privacy/data-retention changes coming soon to help with that.

I think the course of action going forward will be to add a setting to each field to encrypt values, so you can opt-in to this feature.

And that's correct, essentially not saving it in the database at all. It's useful for some people, but it's also overly reliant on emails. Just figured I'd drop that in as an option, but totally fine if it doesn't suit your needs.

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0), you can now control this per-field.
