### ISSUE TITLE
[3.x] Duplicating a form with repeater, uses a reference instead of copy

### ISSUE THREAD

**Issue by vandres** [verbb/formie#2051]
### Describe the bug

We are having a form with a repeater. Our editor duplicated the form and edited the fields in that clone. When she was removing one of the fields in the repeater, the field also disappeared in the original form. We tested, and it works vice versa. Every change to the repeater is synced.

### Steps to reproduce

1. Create a form with a repeater (we've set minimum to 1)
2. Add some fields within the repeater
3. Duplicate the form
4. Change fields in the repeater
5. The changes appear in both forms

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

### Craft CMS version

5.3.x

### Plugin version

3.x

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.5"`.

**Comment by vandres** [comment]
Can confirm, it's working now as expected. Thanks!
