### ISSUE TITLE
Wrong autocomplete value for telephone

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/formie#2052]
### Describe the bug

We did an audit of one of our websites and the autocomplete value "tel-national" for the phone number input field (<input type="tel") got flagged as wrong.

Did some research and apparently the following is the case:
- autocomplete="tel" can be used in type="tel"
- autocomplete="tel-national" can only be used in type="text"

Source: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

<img width="1328" alt="Screenshot 2024-09-04 at 08 48 49" src="https://github.com/user-attachments/assets/2e3bcafb-08dd-467e-ab32-a2eaa9970f77">

**Solution:**
Either change the input field to text and keep the autocomplete, or change the autocomplete to 

### Steps to reproduce

See above

### Form settings

Any form with a phone number field

### Craft CMS version

4 and 5

### Plugin version

2.1.28 & 3.0.5

**Comment by engram-design** [comment]
Thanks for pointing out the reference doc, I was completely unaware of that. For now, to ensure this isn't a breaking change, we'll switch the autocomplete to `tel` as the `type` is going to be more important to stay the same.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.28"` or `composer require verbb/formie:"dev-craft-5 as 3.0.5"`.

**Comment by engram-design** [comment]
Fixed in [2.1.29](https://github.com/verbb/formie/releases/tag/2.1.29) and [3.0.6](https://github.com/verbb/formie/releases/tag/3.0.6)
