### ISSUE TITLE
[3.x] Form with Repeater field with a file upload field in it has error on submission

### ISSUE THREAD

**Issue by zizther** [verbb/formie#2057]
### Describe the bug

I have a form which contains a repeater field, within the repeater field there are several fields, one being a File Upload field.

When submitting the form I always get this error `Call to a member function isEmpty() on array` `vendor/verbb/formie/src/base/ElementField.php at line 144`.

The File Upload field is required and set to only allow TXT and Word docs, with a maximum file size of 5mb.

I have tried this form without the File Upload field in the Repeater and it works fine.
The form also submits fine when the File Upload field is outside the Repeater field

### Steps to reproduce

1. Setup a multi page form
2. On one page add a Repeater field with a File Upload field within it
3. Setup the form to submit via AJAX
4. View the form on the frontend and try to submit content

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.1

### Plugin version

3.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.5"`.

**Comment by zizther** [comment]
I can confirm this issue is resolved with this fix.
Thanks for sorting so quickly

**Comment by engram-design** [comment]
Fixed in [3.0.6](https://github.com/verbb/formie/releases/tag/3.0.6).
