### ISSUE TITLE
Submission does not render the entry inside a repeater

### ISSUE THREAD

**Issue by jessedobbelaere** [verbb/formie#2064]
### Describe the bug

I've set up a Repeater field with 1) Entry field to my products 2) a Quantity field.
The values are passed from the shopping cart to this order form.

This is what the form looks like:

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/aa100a94-c60c-4c9d-9370-e7e7de006bac">

✅ When submitted in the frontend, the e-mail notifications are showing the product entries from the repeater successfully . 
🔴 But the submission page does not show the two entries I submitted:

![Screenshot 2024-09-11 at 22 24 14@2x](https://github.com/user-attachments/assets/b203951d-82b5-489b-a988-89b083d2ce80)

The database submission record does have the right entry IDs. So it's simply a bug in the submission page?

![Screenshot 2024-09-11 at 22 17 35@2x](https://github.com/user-attachments/assets/55e2e90f-1e1b-41a6-afe0-fc78c0009929)

Any idea why the submission does not show the entry?

### Steps to reproduce

1. Repeater field with entry field
2. Submit the form
3. Open the submission in the Craft backend
4. Entry is not rendered in the repeater in the submission

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.4.2

### Plugin version

3.0.6

### Multi-site?

Yes

### Additional context

Both in local ddev and production
The form is on a child website (not the primary). The entries are also located on the child website though.

**Comment by engram-design** [comment]
A quick test on my end shows that's working correctly. 
<img width="460" alt="image" src="https://github.com/user-attachments/assets/4903f6a5-6c70-47df-8b58-1d9769d37a12">

Is the entry from the same site that the submission was made on, or a different site? Just wondering if it might be cross-site entries, because that might be an issue. We don't actually record the picked entry's site, just the ID.

I've also added a fix for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.6"`.

**Comment by jessedobbelaere** [comment]
So I have a multi-site:
- Site 1: Lawnmowers (primary site)
- Site 2: Robot lawn mowers (secondary site)

The form is located on site 2, using exclusively entries owned by site 2. When i go to Formie > Submissions I switch the site selector to site 2 and open the submissions and the entry field is not populated.

The fix you mentioned in the craft-5 branch seems to fix the issue here in my local env 👏

**Comment by engram-design** [comment]
Yep, I believe the issue was for non-primary sites, it wasn't resolving to the correct element.

**Comment by engram-design** [comment]
Fixed in [3.0.7](https://github.com/verbb/formie/releases/tag/3.0.7)
