### ISSUE TITLE
Submission marked as spam - “Failed Captcha “Javascript”: “””

### ISSUE THREAD

**Issue by wolispace** [verbb/formie#2072]
### Question

Looking at the submission payload I don't see a value for JSCHK, yet I do see reference to it on the page:

```html
</script><script>window.Formie__JSCHK_2761094692="66f0ecb5cbcf18.15069309";
--
  | window.Formie__JSCHK_2686854661="66f0ec520a6ef1.06761608";</script></body>
  | </html>

And within the: 
`data-fui-form="{&quot;formHashId&quot;:&quot;fui-contact-akwaek&quot;,&quot;formId&quot;:276109,&qu...`

I get no JS errors on the page.

The forms are using the "Default Formie Template"

I have searched the Formie documentation for JSCHK and found nothing. Nor could I find any info on the Javascript test (what iwas was doing and how it works).

This is an inherited site and my first time touching Formie. 

Do you have any suggestions on how I can debug why I don't see JSCHK in the payload?


### Additional context

_No response_

**Comment by engram-design** [comment]
So it looks like it's enabled for the form, with the JS being rendered, but the actual placeholder where the `<input>` is rendered isn't working. You can confirm this by looking for the following HTML:

```
<div class="formie-jscaptcha-placeholder" data-jscaptcha-placeholder="">
    <input type="hidden" name="__JSCHK_1748317" value="66f1e724d573b5.32116228">
</div>
```

If you're not seeing that, then there might be something wrong with the rendering of your form. Can you let me know if you're using custom rendering for that? I know you mentiontioned using the "Default Formie Template", but you can still [custom render](https://verbb.io/craft-plugins/formie/docs/theming/custom-rendering) a form. If that's the case, you might be missing the `{% hook 'formie.buttons.before' %}` template hook where captchas add their HTML.

What version of Formie is this?

**Comment by wolispace** [comment]
Thanks for the quick response.

I can confirm there is no `<input type="hidden" name="__JSCHK` on the page: searching source for 'JSCHK' shows 4 matches, two in the data-fui-form and two at the bottom of the page.

As for rending we have three twigs that reference form.formie and they all look like they are pretty standard:

```html
{% extends "_layouts/main.twig" %}

{% block main %}
  {% include "skeletons/bannerInsidePages.twig" %}
  {{ craft.formie.renderFormCss("contact") }}
  
  <div class="contact">
    {{ craft.formie.renderForm("contact") }}
  </div>
  {% include "skeletons/internalPage.twig" %}
{% endblock %}
```

```html
{% set myQuery = block.form.one() %}
<div class="centered-wrapper">
  {{ craft.formie.renderForm(myQuery) }}
</div>
```

```html
<div class="newsletter">
  {{ craft.formie.renderFormCss("newsletter") }}
  {{ craft.formie.renderForm("newsletter") }}
</div>
```

This is Formie version 2.1.28. I see we are two behind, so have just updated, but still the same (only 4 instances of JSCHK in source).

I also tried an incognito tab incase it was related to me being logged in. Still only 4 instances.

The site does not use a cache plugin like Blitz and does not use Vue.

Any other thoughts?

**Comment by engram-design** [comment]
That all looks pretty standard. Can you ensure you have it enabled in the Form Integration settings?

![CleanShot 2024-09-25 at 11 36 12@2x](https://github.com/user-attachments/assets/caf9eebb-ee76-4338-9500-b08e57bf4c78)

Otherwise, I'm really not sure what's going on there. By all accounts, that should be rendering the placeholder for the captcha, especially if it's rendering the JS for that same captcha.

You could certainly add a debug statement (`Craft::dd('test');`) around [this line](https://github.com/verbb/formie/blob/00e66d20711a034c189342f991fbf88dc67b852e/src/integrations/captchas/Javascript.php#L62) just to test the HTML output.

**Comment by wolispace** [comment]
Found it.

Turns out our template (above) has
```
{{ craft.formie.renderFormCss("contact") }}
```

And it seems like the inclusion of this prevents it from including formie.js. 

Its possibly assuming: if you include css you will also renderFormJs() ?

The placeholder is present, just before the submit button, but it is empty, and no js errors.

By removing the renderFormCss (it was not doing anything anyhow) the formie.js is loaded and life gets back to normal.

(Oh the joys of using inherited code)

Thanks for your help debugging this.

**Comment by engram-design** [comment]
Now that shouldn't be the case, I'll double check that on my end! Typically if you include those other tags, you should also pass `renderCss/renderJs = false` to the `renderForm()` function, else they'll be rendered twice. But I'll check things out.
