### ISSUE TITLE
Date fields not saving selected date when using Flatpickr

### ISSUE THREAD

**Issue by ikullhem** [verbb/formie#2074]
### Describe the bug

I'm running into a weird issue with the Date fields when set to the Calendar (Advanced) option which uses Flatpickr. The fields will not save the selected date and are saved with an empty value. When viewing the submission in the admin, the field is populated with 01/01/2024 as the date. No value is output when used for the submission title though for example.

I have set up some tests using a regular text field and loading Flatpickr manually on those fields with the same config options as Formie uses, and those save fine. 

My tests were done on a blank html template, to make sure no other website code was conflicting.

Even with having my manual Flatpickr fields in the same form as the Formie Date field yielded the same results. The Date field won't save the value, but the text fields will.

### Steps to reproduce

1. Create form with Date field set to Calendar (Advanced)
2. Submit form with Date selected
3. Notice Date is not correctly saved with submission

### Form settings

- Multi-page form: No
- Submission Method: both Ajax and Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.6

### Plugin version

6.4.0

### Multi-site?

No

**Comment by engram-design** [comment]
While I can't replicate this, I do see some issues with the date picker option when viewing a submission. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.6"`.

Let me know if that doesn't work, and might be worth submitting a support request from Formie via Formie > Settings > Get Support, so I can at least replicate your field exactly as you have it, in case something is different.

**Comment by ikullhem** [comment]
Ok, I ran the update as you suggested. This is partially fixed.

The correct date is shown in the field when viewing the submission in the admin.

However, when using the date field as part of the submission title (either with just the field, or the field:date option) nothing is ouput for that variable in the submission title.

I have not yet checked the email submissions to see if it works there since it's a similar variable selection.

**Comment by engram-design** [comment]
Right you are! Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.6"`.

**Comment by engram-design** [comment]
Fixed in [3.0.8](https://github.com/verbb/formie/releases/tag/3.0.8)
