### ISSUE TITLE
Update Integrations left hand nav with current status of integration (enabled or not)

### ISSUE THREAD

**Issue by wolispace** [verbb/formie#2075]
### What are you trying to do?

When I toggle an integration on or off, the left hand hav remains in its initial state.

When I Save changes, still the left hand nav for that integration remains in its initial state.

### What's your proposed solution?

Each time you toggle an integration on or off, update its status in the left hand hav to match the current state.

This makes it really clear if the integration has been enable or not instead of leaving room for ambiguity, double checking, page reloading etc.

### Additional context

Version 2.1.30

**Comment by engram-design** [comment]
This is fixed/improved in Formie 3, I'll look at back-tracking that to Formie 2.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.30"`.

**Comment by wolispace** [comment]
Wow that was fast!

Thanks
