### ISSUE TITLE
Serialization of 'Closure' is not allowed on File Upload field

### ISSUE THREAD

**Issue by thomascoppein** [verbb/formie#2078]
### Describe the bug

We're using a multi step form with on step 3 an asset field.
When I fill in step 1 and go to step 2 and refresh the page I get an error message.
From then on I keep getting the `Serialization of 'Closure' is not allowed` error.
I need to delete my `CraftSessionId` cookie to regain access to the site.

### Steps to reproduce

1. Create a multi-step form
2. Add an asset field to a step
3. Fill in the first step of form
4. Refresh page

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

4.12.5

### Plugin version

2.1.30

### Multi-site?

Yes

### Additional context

I also have following plugins installed: SEOMatic, Retour, CKEditor, Asset Rev, Cookies, Feed Me, MatrixMate, Sprig, Super Table.
Here also screenshot of error message:
![Screenshot 2024-10-03 at 14 59 03](https://github.com/user-attachments/assets/6a269006-cbab-454b-9bc1-5d98586b91a1)

**Comment by engram-design** [comment]
That seems to be coming from a custom template as part of your project? `/templates/components/form/templates/fields/file-upload.html`

I can see the issue is that you're trying to set the `value` HTML attribute to an Asset Element Query, which isn't going to work.

```twig
{{ fieldtag('fieldInput', {
    value: value ?? false,
    hidden: false,
}) }}
```

You'd probably want to change that to:

```twig
{{ fieldtag('fieldInput', {
    value: value.ids(),
    hidden: false,
}) }}
```

**Comment by thomascoppein** [comment]
@engram-design has indeed fixed it. Thank you!
