### ISSUE TITLE
Table Field - Under "Type" Column - Dropdown option label/values do not save

### ISSUE THREAD

**Issue by TSeine** [verbb/formie#208]
**Description**
Table Field - Under "Type" Column - Dropdown option label/values do not save

**Steps to reproduce**
1. Add a Table field - set up columns
2. Select Dropdown Type
3. Add Dropdown Options

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload (Server-side)
- Client-side Validation: Yes
- Custom Form Templates: Yes but also tested using default Formie template

**Additional info**
- Plugin version: 1.2.25
- Craft version: 7.2.34
- Multi-site: No

**Additional context**
Even better is if you can make one of the column types a radio button!!!  Thanks

![Screen Shot 2020-11-09 at 7 20 01 PM](https://user-images.githubusercontent.com/73661752/98617353-73670d80-22c4-11eb-946d-908d8eabe10c.png)
![Screen Shot 2020-11-09 at 7 19 25 PM](https://user-images.githubusercontent.com/73661752/98617360-7661fe00-22c4-11eb-81f4-61375c430d2b.png)
![Screen Shot 2020-11-09 at 7 23 03 PM](https://user-images.githubusercontent.com/73661752/98617432-9a254400-22c4-11eb-9b8d-69bbbbb21c77.png)

**Comment by engram-design** [comment]
Should be fixed in [1.2.26](https://github.com/verbb/formie/releases/tag/1.2.26).

I'll have to look at adding radio field support, although we are reliant on the Craft table field supporting that itself to a degree.
