### ISSUE TITLE
Issue with calculations and field in groups

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2080]
### Describe the bug

The calculations field can't find fields nested in groups.

### Steps to reproduce

1. Import this form [formie-testMath.json](https://github.com/user-attachments/files/17277648/formie-testMath.json)
2. View the form in the frontend
3. In the console following error is visible:
calculations.js: 
```js
SyntaxError: Variable "field_group" is not valid
```

### Form settings

- Multi-page form: No
- Submission Method: -
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.6

### Plugin version

3.0.7

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.7"`.

**Comment by engram-design** [comment]
Fixed in [3.0.8](https://github.com/verbb/formie/releases/tag/3.0.8)

**Comment by beekmanbram** [comment]
Same issue in 3.0.9
