### ISSUE TITLE
[4.x] Failed jobs for sending notifications

### ISSUE THREAD

**Issue by anita-chouhan** [verbb/formie#2085]
### Describe the bug

I recently updated the Formie plugin to version 2.1.30 from 2.1.19 along with the Craft CMS version to 4.11.5 from 4.9.7. I am getting failed jobs in the queue manager for _Sending form notifications_.

### Steps to reproduce

1. Set up a _Craft CMS_ version 4.11.5 with _Formie_ 2.1.19.
2. Update the _Formie_ version in `composer.json` to 2.1.30.
3. Run `composer update` from the command line.
4. Add a simple form with one text field.
5. Add an email notification for form submission.
6. Try submitting the form from the website front-end.

### Form settings

- Multi-page form: No
- Submission Method: Reload
- Client-side Validation: No
- Custom Form Templates: No
- Submission Title Format: Empty

### Craft CMS version

4.11.5

### Plugin version

2.1.30

### Multi-site?

No

### Additional context

The email is still received in the inbox and there is entry for form submission as well. 

The below error is logged for this issue:

**Control panel**
<img width="589" alt="Screenshot 2024-10-09 at 6 06 14 PM" src="https://github.com/user-attachments/assets/fbf0522e-023d-4759-aec6-b67301b2f6f8">

**Log**
<img width="508" alt="Screenshot 2024-10-09 at 6 08 15 PM" src="https://github.com/user-attachments/assets/830e7dbf-0ace-428f-bc01-bab35da80b30">

**Comment by engram-design** [comment]
This seems to be related to a Sent Notification, so everything about the Email Notification should work, as this is a process after that's been sent.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.31"`.

**Comment by anita-chouhan** [comment]
Thank you for the quick fix, @engram-design, the notifications are working fine now.
