### ISSUE TITLE
Zoho integrations fails to load zoho fields in mapping tables

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/formie#2086]
### Describe the bug

My zoho integration is connected to craft. When trying to connect my form to Zoho inside the form integrations settings, no zoho fields are coming up in the mapping tables.

Checking the network tab, empty arrays are coming in as the response.

![image](https://github.com/user-attachments/assets/89c31ee0-bc2b-4e96-9b31-974d484f94d9)

I'm not using the Use Developer API setting but this is not necessary i guess?

### Steps to reproduce

1. Connect Formie to Zoho
2. Go to a form
3. Go to zoho settings
4. Toggle on all 
5. Refresh integration
6. No fields are available in the mapping tables

### Form settings

No special form settings

### Craft CMS version

Craft Pro 4.7.4

### Plugin version

2.1.30

### Multi-site?

No

**Comment by engram-design** [comment]
Anything in your `storage/logs/formie.log` files related to this? The "Use Developer API" is really only if you are using the developer account, but if you're using a client account, that'd be fine.

Can you let me know the "App's data center" setting in Zoho? It's possible that might be a factor, but it should be automatic, and it should throw an error if it's the wrong data center.

**Comment by angelokeirsebilck** [comment]
Ah I did not check the logs yet.. it throws an error.

`2024-10-10 07:53:30 [ERROR] Zoho New: API error: “{"code":"INVALID_TOKEN","details":{},"message":"invalid oauth token","status":"error"}`

@engram-design Is this something that is wrong on my end?

**Comment by engram-design** [comment]
Have you tried disconnecting and reconnecting Zoho from the CRM integration settings?

**Comment by angelokeirsebilck** [comment]
> Have you tried disconnecting and reconnecting Zoho from the CRM integration settings?

Nope, net yet. I can't try it without contacting my client, because they have to login with their zoho account after clicking connect.

I'll ask if they can reconnect it and let you know after.

UPDATE: @engram-design She disconnected and reconnected the integration but same error.

`2024-10-10 15:02:17 [ERROR] Zoho New: API error: “{"code":"INVALID_TOKEN","details":{},"message":"invalid oauth token","status":"error"}`

UPDATE2: I think it indeed might be an issue with the data center. The client is from Belgium and i can see in the logs that the urlAuthorize is .com. urlAccessToken is .eu though.

`{"urlAuthorize":"https:\/\/accounts.zoho.com\/oauth\/v2\/auth","urlAccessToken":"https:\/\/accounts.zoho.eu\/oauth\/v2\/token","urlResourceOwnerDetails":"",`

**Comment by engram-design** [comment]
Just added a Data Center setting for the integration, which should help with this. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.30"`.

**Comment by angelokeirsebilck** [comment]
Thanks for the update, I've tested this but still no fields are available in the mapping tables.

In the logs I can see the updated urlAuthorize, now "https:\/\/accounts.zoho.eu\/oauth\/v2\/auth". But it still gives the same error:

`2024-10-16 09:01:05 [ERROR] Zoho New: API error: “{"code":"INVALID_TOKEN","details":{},"message":"invalid oauth token","status":"error"}`

I've disconnected the integration and reconnected.

**Comment by engram-design** [comment]
After some documentation reading, I'm not actually sure my change was correct anyway:

> You must make the authorization request from https://accounts.zoho.com for the EU, AU, and IN domains. After the request is successful, the system automatically redirects you to your domain.

And apparently this message happens when the [access token](https://help.zoho.com/portal/en/community/topic/string-87-code-invalid-token-details-message-invalid-oauth-token-status-error-grtting-this-error) needs to be created again.

**Comment by angelokeirsebilck** [comment]
> After some documentation reading, I'm not actually sure my change was correct anyway:
> 
> > You must make the authorization request from https://accounts.zoho.com for the EU, AU, and IN domains. After the request is successful, the system automatically redirects you to your domain.
> 
> And apparently this message happens when the [access token](https://help.zoho.com/portal/en/community/topic/string-87-code-invalid-token-details-message-invalid-oauth-token-status-error-grtting-this-error) needs to be created again.

Where did you find that documentation regarding having to use the .com?

Here (https://www.zoho.com/crm/developer/docs/api/v7/access-refresh.html) they say you have to use the specific domains in order the get the tokens.

**Comment by engram-design** [comment]
Just from the [Multi DC](https://www.zoho.com/crm/developer/docs/api/v7/multi-dc.html) docs, but that's a different thing, you're right.

I've just created an account in my both AU and EU data centers, and that seems to be working for me, pulling in data.

Was the Zoho app created recently? It's connected to the organisation?

By the way, we recently changed things so that integrations will only return data for the objects you enable. So if you have no data objects enabled, you won't get a response. This is a change back-tracked from Formie 3. Just make sure you have "Map to Contact" or similar checked.

**Comment by angelokeirsebilck** [comment]
With the Zoho app? You mean the CRM integration in Formie? Or the Zoho account? I don't know when the Zoho account of my client is created, atleast before 2022-04.

I can confirm I have tried with objects enabled.

What do you mean with 'Its connected to the organisation?'

**Comment by engram-design** [comment]
I was referring to the [Zoho Console](https://api-console.zoho.eu/) and the app (or client) in there, whether that was recently created or using an existing one.

**Comment by angelokeirsebilck** [comment]
I've created a new one previous week together with the client through a video call, following the steps on the Formie Zoho CRM integration settings.

**Comment by engram-design** [comment]
Hmm, I’m at a bit of a loss then. My own EU zoho account was pretty straightforward to setup and that’s working. Wonder if it worth getting your client to get in touch with Zoho support with that error message response for more clarification?

**Comment by angelokeirsebilck** [comment]
> Hmm, I’m at a bit of a loss then. My own EU zoho account was pretty straightforward to setup and that’s working. Wonder if it worth gettin your client to get in touch with Zoho support with that error message response for more clarification?

I'll go through the setup process again with my client. I'll let you know.

**Comment by angelokeirsebilck** [comment]
Ok, that worked. Closing, thanks for the support.
