### ISSUE TITLE
How do I submit the reCaptcha token via AJAX api?

### ISSUE THREAD

**Issue by benfeather** [verbb/formie#2089]
### Question

What is the correct format to submit the client-side reCaptcha token (v3 Enterprise) using the JS API?

I have the form submission working using the format listed [here](https://verbb.io/craft-plugins/formie/docs/developers/front-end-js#submit-with-javaScript). But the submission is always marked as spam with the error "Failed Captcha 'Recaptcha': 'Client-side token missing.'"

```
{
    action: 'formie/submissions/submit',
    handle: 'contactForm',
    siteId: 1,
    fields: {
        yourName: 'Peter Sherman',
        emailAddress: 'psherman@wallaby.com',
        message: 'Hello there!',
    },
};
```

**Comment by engram-design** [comment]
If you include a [`g-recaptcha-response`](https://github.com/verbb/formie/blob/2ad0eed073b9b6b67b0242cc3ae7454156ba11ba/src/integrations/captchas/Recaptcha.php#L159C58-L159C78) value which is the [standard](https://developers.google.com/recaptcha/docs/verify) POST param, that should do the trick.

```
{
    action: 'formie/submissions/submit',
    handle: 'contactForm',
    siteId: 1,
    'g-recaptcha-response': 'xxxxxxxxxx',
    fields: {
        yourName: 'Peter Sherman',
        emailAddress: 'psherman@wallaby.com',
        message: 'Hello there!',
    },
};
```

**Comment by benfeather** [comment]
I think there might be a bug in the reCaptcha validation logic. 

I set some breakpoints in the Formie plugin and submitted the form.

The Recaptcha integration picks up the token from the submission and successfully validates it using the Enterprise Recaptcha API.
![formie-result](https://github.com/user-attachments/assets/a6f69c82-d359-4ea8-b9ec-7bd32d03c9d1)

However, the integration then checks for the "invalidReason" property on the response, which (at least for me) is always set to "INVALID_REASON_UNSPECIFIED" and will always be true.
![formie-fail-response](https://github.com/user-attachments/assets/9d8dbbdd-e96d-4927-a4f4-e41ba16bc70d)

I think the validation logic should be:
![formie-success-response](https://github.com/user-attachments/assets/23938a59-794a-46c6-ad04-3da87825865f)

After changing that line, the submission worked:
![formie-submissions](https://github.com/user-attachments/assets/a12b5049-4796-46ed-9c3e-bfb0ac0dba84)

**Comment by engram-design** [comment]
Well that'd be the first time I've come across that, I'm surprised there's an `invalidReason` if the thing is valid. But then the Enterprise type is new-ish.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.31"` or `composer require verbb/formie:"dev-craft-5 as 3.0.8"`.

**Comment by benfeather** [comment]
Awesome, that fixed the problem, thanks!
