### ISSUE TITLE
Notification subject HTML encoding special characters

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#2091]
### Describe the bug

If a character (such as an ampersand) is included in the subject line of a notification email, it is HTML encoded (e.g. & to &amp;). Not sure what other characters are affected.

### Steps to reproduce

1. Have a subject that includes &
2. Send email notification

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.7.1

### Plugin version

3.0.8

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.8"`.

**Comment by engram-design** [comment]
Fixed in [3.0.9](https://github.com/verbb/formie/releases/tag/3.0.9)
