### ISSUE TITLE
Issue with date field in group

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2093]
### Describe the bug

A form can not be submitted if a date field is inside of a group.

### Steps to reproduce

1. Import this form: [formie-dateIssue.json](https://github.com/user-attachments/files/17361827/formie-dateIssue-d4c8046f-2e7e-4f59-a36b-ec825749125f.json) or make a form with a mandatory date field inside a group.
2. Submit the form
3. 500: BaseArrayHelper.php - Undefined property: DateTime::$date

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5.4.4

### Plugin version

3.0.8

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.8"`.

**Comment by engram-design** [comment]
Fixed in [3.0.9](https://github.com/verbb/formie/releases/tag/3.0.9)
