### ISSUE TITLE
Craft CMS + Formie Form Repeater Field

### ISSUE THREAD

**Issue by Abdulkadiragoliya** [verbb/formie#2097]
### Describe the bug

I have checkbox list and each item has repeater field with many other fields inside it. Some fields inside repeater are conditional. I tried to give condition from admin form but in condition, repeater field not showing. so i have show/hide field using JavaScript.

As field which is going to show/hide are required, even its hidden, form couldn't be submit because of required field. How can I achieve this?

Show hide like this using JS

```
$("div[data-field-handle='fenceType'] select[data-fui-id='LandscapingFrontyardDesignChanges2-fencingWallsNonRetaining1-fenceType']").each(function(){ 
    $(this).change(function(){
              if ($(this).val().includes("Other")) { 
                 $(this).closest(".fui-row").next().find("div[data-field-handle='describeOtherFenceDesignType']").show(); } else{ 
                $(this).closest(".fui-row").next().find("div[data-field-handle='describeOtherFenceDesignType']").hide(); 
              } 
    });
});
```

### Steps to reproduce

1. On select value from dropdown, Field Will be show/hide based on selection
2. Wehn submit it should submit the form without validating hidden field

### Form settings

- Multi-page form: Yes 
- Submission Method: Ajax  
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

### Craft CMS version

4.5.12

### Plugin version

dev-craft-4

### Multi-site?

YES

**Comment by engram-design** [comment]
It might be beneficial to send a support request for your form via Formie > Settings > Get Support. This way, I can get your form and fields replicated on my end, so I can see your issue. I'm not quite sure on the issue from your description, sorry!

**Comment by Abdulkadiragoliya** [comment]
> It might be beneficial to send a support request for your form via Formie > Settings > Get Support. This way, I can get your form and fields replicated on my end, so I can see your issue. I'm not quite sure on the issue from your description, sorry!

Thank you so much for your reply.  I have created a ticked also via Formie > Settings > Get Support

I have a form with multiple Repeater fields, and each of these Repeaters contains several other fields. Some of these fields need to be shown or hidden conditionally. I initially tried to set the conditional logic using the form builder's "Condition" tab in the admin, but I couldn't find a way to apply it to the Repeater's fields. As a workaround, I implemented custom JavaScript to show/hide fields, and it works fine in controlling visibility.

However, the problem is that many of these fields are marked as "required." Even when a field is hidden, the form still triggers validation errors for those required fields. How can I prevent hidden fields from being validated?

I am attaching here photos for your reference
![form_admin_condition](https://github.com/user-attachments/assets/ed8b7bf9-e339-4b6a-af36-ba48ee584644)
![form_admin_Fields](https://github.com/user-attachments/assets/117880e6-f868-48ca-8580-a1e81506ef06)

**Comment by engram-design** [comment]
Ah, thanks for clarifying. So this is not possible in Formie 2, and was added in Formie 3 (see https://github.com/verbb/formie/issues/764 and https://github.com/verbb/formie/issues/1528). It's quite the large refactor, so back-tracking it to Formie 2 would prove challenging.

**Comment by Abdulkadiragoliya** [comment]
Thank you so much for your quick reply

if i update the my Formie plugin version to Formie 3. so after upgrade the version, do i need to recreate All the forms and fields?

Because i have created around 50 forms with many fields

**Comment by engram-design** [comment]
You won't need to re-create anything, just the ability to reference Repeater fields in conditions will be available.

**Comment by Abdulkadiragoliya** [comment]
I am currently using Craft CMS 4.5.12 and I don't see an available Formie update under Admin > Utilities > Updates. How can I upgrade Formie?

If I download the package directly from the GitHub repository (https://github.com/verbb/formie/tree/3.0.0), will it be compatible with Craft CMS 4.5.12?

Is upgrading via GitHub recommended, or would it be better to upgrade using Composer? I prefer upgrading through Composer.

**Comment by engram-design** [comment]
Formie 3 is only available for Craft 5 sorry, so it's going to have to be part of a larger update from Craft 4 to 5 for this.

**Comment by Abdulkadiragoliya** [comment]
So using javascript, how can I add/remove required validation from the
field?

**Comment by engram-design** [comment]
By removing the `required` attribute on inputs. You could also add/remove the `disabled` attribute on things, which disables sending these fields to the server entirely. 

Your show/hide logic should include this behaviour. Something like:

```js
$('input, select, textarea').prop('disabled', 'disabled');
```
Of course, targeting only the fields inside the Repeater field/row that are hidden.

**Comment by Abdulkadiragoliya** [comment]
Thank you for your response

I tried as you suggest and its working fine for select element but not working with textarea

```
if($(this).val() == "Wall") { 
			     $(this).parents(".fui-field-rows").find("div[data-field-handle='fenceType'] ").hide();
				 $(this).parents(".fui-row").next(".fui-row").find("div[data-field-handle='wallType']").show();
				 $(this).parents(".fui-row").next(".fui-row").find("div[data-field-handle='wallType']").next(".walltypeimage").show();
				 $(this).parents(".fui-row").nextAll(".fui-row").find("div[data-field-handle='describeOtherFenceDesignType']").hide();
				 $(this).parents(".fui-row").nextAll(".fui-row").find("div[data-field-handle='materialTypeDescription'] ").hide();
				 
				 //for required field logic
				 $(this).parents(".fui-field-rows").find("div[data-field-handle='fenceType'] select[data-fui-id='LandscapingFrontyardDesignChanges2-fencingWallsNonRetaining1-fenceType']").prop('disabled', 'disabled').removeAttr('required');
				 $(this).parents(".fui-row").next(".fui-row").find("div[data-field-handle='wallType'] select[data-fui-id='LandscapingFrontyardDesignChanges2-fencingWallsNonRetaining1-wallType'] ").prop('disabled', false).attr('required', true);
			 	 $(this).parents(".fui-row").nextAll(".fui-row").find("div[data-field-handle='describeOtherFenceDesignType'] textarea[data-fui-id='LandscapingFrontyardDesignChanges2-fencingWallsNonRetaining1-describeOtherFenceDesignType']").prop('disabled', 'disabled').removeAttr('required');
			     $(this).parents(".fui-row").nextAll(".fui-row").find("div[data-field-handle='materialTypeDescription']  textarea[data-fui-id='LandscapingFrontyardDesignChanges2-fencingWallsNonRetaining1-materialTypeDescription']").prop('disabled', 'disabled').removeAttr('required');
			   
			   
			   }

**Comment by engram-design** [comment]
What about it doesn't work? Are the attributes being toggled? Is there a server-side error being thrown? Because you'll likely need to employ server-side checks as well for required fields.
