### ISSUE TITLE
Required Names fields are not marked as required after update to Craft 5

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#2100]
### Describe the bug

After the update to Craft 5, the asterisk icons disappeared from the required fields of the Name type.

![image](https://github.com/user-attachments/assets/79a5ced4-451a-4097-8df2-e0b69d32cf5d)
![image](https://github.com/user-attachments/assets/15e19ab0-5656-4920-8979-ef8d9045f6e7)

Craft 5
![image](https://github.com/user-attachments/assets/76126dfd-845c-487d-84f9-0a693940a839)

Craft 4
![image](https://github.com/user-attachments/assets/7e84d55b-5e74-423c-ba7b-cbf66e56aa50)

### Steps to reproduce

1. Upgrade formie to v3
2. Use required Name field

### Form settings

- Multi-page form: No
- Submission Method: Ajax and Page Reload
- Client-side Validation: Yes and No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.4.8

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by samuelreichor** [comment]
@engram-design Unfortunately I have that same issue but I have formie 3.0.9 installed 🙈

**Comment by engram-design** [comment]
@samuelreichor Note that this isn't in a released version (I'll get it out shortly) as `dev-craft-5 as 3.0.9` and `3.0.9` aren't the same thing.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
