### ISSUE TITLE
[3.x] `defaultFileUploadVolume` not working

### ISSUE THREAD

**Issue by vandres** [verbb/formie#2102]
### Describe the bug

I would like to prepopulate the asset volume, so the editor can make less mistakes when using the file upload field. But somehow that field is buggy and/or inconsitent.

When I use the setting, or put it into the config file, it expects "folder:"

![Bildschirmfoto 2024-10-27 um 13 10 40](https://github.com/user-attachments/assets/b769190f-5281-4382-9537-00b7f754fe40)

When being in an upload field, it expect "volume".

![Bildschirmfoto 2024-10-27 um 13 10 01](https://github.com/user-attachments/assets/28c00015-3694-4dee-acb7-8ed5d29dd781)

I tried both in the `formie.php` config, and neither is used/accepted from the field.

### Steps to reproduce

1. Create a `formie.php` in the config folder
2. Prefill `defaultFileUploadVolume` with one of your volumes
3. Create a new form "Test"
4. Add an file upload field
5. Look at the setting "upload target"
6. It is empty

### Form settings

- Multi-page form: Yes 
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates:  No

### Craft CMS version

5.4.9

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by vandres** [comment]
I think, it would also be much more convienient, to use the volume handle, instead ot the ID. "forms" in our case.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by vandres** [comment]
Thanks - it's working for me! Any feedback ony my suggestion from the comment?

**Comment by engram-design** [comment]
We use the UID (not the ID) purely because the handle can be changed, and that would cause the un-linking of this setting. It's potentially something we can look at, but probably a breaking change.

I know it's a little tedious in the context of a `formie.php` config file.

**Comment by vandres** [comment]
Thanks for the explanation.
