### ISSUE TITLE
[3.x] Calendar (Avanced) missing from pre selection

### ISSUE THREAD

**Issue by vandres** [verbb/formie#2103]
### Describe the bug

I would like to preset Calendar (Avanced) for our editors. But it seems to be missing from the settings option.

Settings-Dialog:
![grafik](https://github.com/user-attachments/assets/1554b73b-0a60-4853-8719-d97581849cbe)

Date-Field
![grafik](https://github.com/user-attachments/assets/ad0c5fb0-b68a-45ba-ba32-24619c1e78e9)

### Steps to reproduce

1. Try to pre select Calendar (Avanced) in FOrmie settings
2. It's missing

### Form settings

- Multi-page form: Yes 
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates:  No

### Craft CMS version

5.4.9

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by vandres** [comment]
Can confirm, it's working.
