### ISSUE TITLE
Country sub-field is showing as "No response" in email notification

### ISSUE THREAD

**Issue by pascalminator** [verbb/formie#2106]
### Describe the bug

I used the "Address" field with the provided sub-fields (city, postal code, province/state, country) and they all return the correct values in the email notification, except for the "country" sub-field that always shows as "no response" instead of the actual value:
![image](https://github.com/user-attachments/assets/5131c470-e35a-4976-80a3-128c69a9b1b2)

This is weird because in the CMS, the country is showing properly:
![image](https://github.com/user-attachments/assets/7294bdee-6f53-49dd-a64d-42e530f7db9d)

I used the provided variables:
![image](https://github.com/user-attachments/assets/8d7e23a3-f9be-4df4-847c-956dda7af3fc)

### Steps to reproduce

1. Create a form with the address field and with the country sub-field
2. Select a country in the dropdown and send the form
3. Saved submission in the CMS is showing the country just fine but the received email shows "no response"

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.9

### Plugin version

3.0.9

### Multi-site?

No

### Additional context

It happens both in dev and production

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
