### ISSUE TITLE
Modify Zapier payload before send

### ISSUE THREAD

**Issue by cmalven** [verbb/formie#2108]
### Question

I need to be able to modify a Zapier integration web hook URL based on the contents of the submission prior to sending the payload. Based on the Formie docs, I would expect to be able to do this using:

```php
        Event::on(Zapier::class, Zapier::EVENT_BEFORE_SEND_PAYLOAD, function (
            SendIntegrationPayloadEvent $event
        ) {
            $submission = $event->submission;
            $payload = $event->payload;
            $integration = $event->integration;
            $endpoint = $event->endpoint;
            $method = $event->method;
            // ...
        });
```

But it doesn't seem like this is ever called. Am I missing something, or could you suggest an alternate way of achieving this?

**Comment by cmalven** [comment]
Interestingly enough, immediately after I sent this I finally saw the event trigger. I'm fairly certain the integration wasn't being triggered because the test submissions are being marked as spam.

**Comment by engram-design** [comment]
Integrations will be run through the Craft Queue, and by default that's only run when you visit the control panel. As such, it might not have triggered until then?
