### ISSUE TITLE
[Craft 4] Changing "Action on Submit" keeps old fields in view

### ISSUE THREAD

**Issue by shoored** [verbb/formie#2112]
### Describe the bug

When changing the `Action on Submit` from `Redirect to a URL` to `Redirect to an entry` some of the current form fields stay in place instead of disappearing.

When I then save the form and reload and try changing `Action on Submit` from `Redirect to an entry` to `Redirect to a URL` the same thing happens.

https://github.com/user-attachments/assets/15151bea-df07-4cdf-ae5e-edd53bbdea31

### Steps to reproduce

1. Edit a form
2. Change "Action on Submit" to something else
3. Old fields stay in view

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.12.8

### Plugin version

2.1.32

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.32"`.

**Comment by shoored** [comment]
You're on fire.

**Comment by engram-design** [comment]
Fixed in [2.1.33](https://github.com/verbb/formie/releases/tag/2.1.33)
