### ISSUE TITLE
Iterable API Error

### ISSUE THREAD

**Issue by robinsm** [verbb/formie#2115]
### Describe the bug

I have an issue when testing the Formie integration using Iterable. It seems to be reporting an error in the JSON payload sent to it from the Formie plugin.

### Steps to reproduce

1. Add an Iterable integration to a form
2. Configure field mappings and save
3. Test the form submission (on the frontend)
4. See the iterable API error in the Craft Queue Manager

`API error: “{"msg":"[/api/lists/subscribe] Invalid JSON body","code":"BadJsonBody","params":{"obj.subscribers[0].dataFields":"error.expected.jsobject"}}” /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111`

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.12.5

### Plugin version

2.1.31

### Multi-site?

Yes

**Comment by engram-design** [comment]
Hmmm, can't seem to replicate that on my end, but might be down to the difference in our mapping? Can you shoot through a screenshot or at least a list of what you're mapping?

**Comment by robinsm** [comment]
Sure, we're only mapping the email address as that's the only value we're collecting.

Please let me know if I can give you anything else.

<img width="1437" alt="🚧⚙_Best_of_PBS_-_General_Audiences" src="https://github.com/user-attachments/assets/9f8a07f7-a048-456f-86e8-a99bb20c5b59">

**Comment by engram-design** [comment]
Ah, it's when you're not mapping any custom fields. I was testing with first/last name.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.31"`.

**Comment by robinsm** [comment]
Thanks @engram-design , that's done the trick.
