### ISSUE TITLE
Not possible to add "Name" field and save forms while using user language "German"

### ISSUE THREAD

**Issue by steve-p96** [verbb/formie#2116]
### Describe the bug

I encountered a strange bug related to the language setting of the user account in the Craft CMS control panel. When the user language is set to "German," adding a "Name" field to a form and then attempting to save the form triggers an error.

![image](https://github.com/user-attachments/assets/cb72fb61-7925-4048-b5b1-4a437af35c21)

### Steps to reproduce

1. Set the user language to German in the Craft CMS control panel.
2. Create or edit a form.
3. Add a "Name" field to the form.
4. Attempt to save the form.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.4.6

### Plugin version

3.0.7

### Multi-site?

Yes

### Additional context

- This issue only occurs when the user language is set to German.
- I have tested the same steps with English, French, and Spanish languages, and the form saves correctly without any errors.

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
