### ISSUE TITLE
Users field type includes inactive users

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#2117]
### Describe the bug

When adding a user field type to a form it's including all users from the selected group including inactive users.

### Steps to reproduce

1. Add a users field to a form
2. Front end form includes inactive users.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.12.8

### Plugin version

2.1.32

### Multi-site?

Yes

### Additional context

I'd expect the users to be limited to active users only, or have another setting for the users field where you can specify the status types to include, defaulting to 'active'.

NB - I've tried with both custom & formie templates, same issue.

**Comment by javangriff** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.32"`.

**Comment by engram-design** [comment]
Fixed in [2.1.33](https://github.com/verbb/formie/releases/tag/2.1.33)
