### ISSUE TITLE
Saved elementSelectField does not (visually) persist between refreshes in payment integration settings schema in control panel

### ISSUE THREAD

**Issue by jedso** [verbb/formie#2118]
### Describe the bug

I am implementing a custom payment integration and added a `SchemaHelper::elementSelectField` via `defineSettingsSchema`, but while selecting an element _does_  successfully save, the frontend control panel does not reflect this on refresh (it is not populated with the saved element).

Here is a video example using the existing Stripe implementation:

```php
SchemaHelper::elementSelectField([
    'label' => 'Entry element select field test',
    'name' => 'testEntrySelect',
    'selectionLabel' => 'Select an entry',
    'config' => [
        'jsClass' => 'Craft.AssetSelectInput',
        'elementType' => 'craft\elements\Entry',
    ],
]),
```

https://github.com/user-attachments/assets/8099607f-956d-4d98-8d96-ba7993b6fc43

Now importantly, the element _is_  being saved because the value is accessible via PHP `$this->getFieldSetting('testEntrySelect', false);` (e.g. dumping it in `processSinglePayment`):
```
array (size=1)
  0 => 
    array (size=2)
      'id' => string '2132' (length=4)
      'siteId' => string '1' (length=1)
```

So this seems like a frontend control panel issue with Formie, as far as I can tell.

### Steps to reproduce

This reproduction involves editing the existing, built-in Stripe payment integration, though in my case was found during the process of writing a custom integration.
1. In `verbb/formie/src/integrations/payments/Stripe.php`, add the following as an item of `defineSettingsSchema()`
```php
SchemaHelper::elementSelectField([
    'label' => 'Entry element select field test',
    'name' => 'testEntrySelect',
    'selectionLabel' => 'Select an entry',
    'config' => [
        'jsClass' => 'Craft.AssetSelectInput',
        'elementType' => 'craft\elements\Entry',
    ],
]),
```
2. Now in a form with the Stripe payment integration, go into the 'settings' tab and attempt to add any entry.
3. Apply it, then save the form.
4. Refresh the page and notice how it is not pre-populated.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes (but reproduction uses existing Stripe form templates)

### Craft CMS version

5.4.8

### Plugin version

3.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
So element selects in Formie's field settings are a **pain** because they're mixing Formie's Vue and Craft's jQuery based concepts, which aren't really that compatible. The way around this is to provide the HTML for the element select field, server-rendered, and use that for the field. We do this in a few places like the default value for [Element fields](https://github.com/verbb/formie/blob/4be20662d25d75bd3ca779076c5222aaaf4f751a/src/base/ElementField.php#L312-L336). It's very gross, but there's no way around that unless I want to re-build the element select component in Vue...

I have had to make a few adjustments to make this possible from the context of an Integration class, which isn't the same as a custom field class. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

Adding the following to your integration class should do the trick.

```php
public function modifyFieldSettings(array $settings): array
{
    $testEntrySelect = $settings['settings']['providerSettings'][$this->handle]['testEntrySelect'] ?? [];

    if ($testEntrySelect) {
        if ($ids = ArrayHelper::getColumn($testEntrySelect, 'id')) {
            $entries = \craft\elements\Entry::find()->id($ids)->all();

            // Render the HTML needed for the element select field. jQuery needs DOM manipulation
            // so while gross, we have to supply the raw HTML, as opposed to models in the Vue-way.
            $settings['testEntrySelectHtml'] = Craft::$app->getView()->renderTemplate('formie/_includes/element-select-input-elements', ['elements' => $entries]);
        }
    }

    return $settings;
}
```

**Comment by jedso** [comment]
Awesome - this works great! Really appreciate it :pray:

I thought I might ask - is there a way to have this server-rendered chip have its action menu and preserve the ability to be removed? If I add the `showActionMenu` property, nothing happens on click. E.g.
```twig
{{ elementChip(element, {
    context: 'field',
    size: 'small',
    name: 'elementSelect',
    showActionMenu: true,
}) }}
```

Additionally, in a scenario where the element select is constrained to a 1 item limit, since the chip doesn't seem to be tied to the actual element select, you end up with a (visually) duplicated selection:

https://github.com/user-attachments/assets/821feceb-f75a-4aad-843f-3d6ff2817f34

If it's not easily doable to have a native-like chip, that's all good. I can definitely work with this fix as-is. Thanks again!

**Comment by engram-design** [comment]
Ah yes, probably needs a slight tweak from the latest Craft 5 updates, due to the changed behaviour of element select fields.

Should be possible in the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by jedso** [comment]
Works perfectly now! Top-notch work, thank you :pray:

**Comment by jedso** [comment]
Oh actually I've noticed a new error on form submission after playing around with the latest commit on the `craft-5` branch. Specifically:
```
{
    "name": "Database Exception",
    "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) `subquery`\nINNER JOIN `elements` `elements` ON `elements`.`id` = `subqu...' at line 10\nThe SQL being executed was: SELECT `elements`.`id`, `elements`.`canonicalId`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateLastMerged`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`siteId`, `elements_sites`.`title`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`content`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`fieldId`, `entries`.`primaryOwnerId`, `entries`.`typeId`, `entries`.`postDate`, `entries`.`expiryDate`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`\nFROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `siteSettingsId`, `structureelements`.`structureId`\nFROM `elements` `elements`\nINNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`\nINNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`\nLEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *\nFROM `structures` use index(primary)\nWHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))\nWHERE (`elements`.`id` IS NULL) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)\nORDER BY FIELD(`elements`.`id`,)) `subquery`\nINNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`\nINNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`siteSettingsId`\nINNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`\nLEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)\nORDER BY FIELD(`elements`.`id`,)",
    "code": "42000",
    "exception": "yii\\db\\Exception",
    "file": "/srv/site/vendor/yiisoft/yii2/db/Schema.php",
    "line": 676,
```
<details>
    <summary>Click to expand (abridged) trace</summary>
    <code>
[
        {
            "file": "/srv/site/vendor/yiisoft/yii2/db/Command.php",
            "line": 1325,
            "function": "convertException",
            "class": "yii\\db\\Schema",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/yiisoft/yii2/db/Command.php",
            "line": 1186,
            "function": "internalExecute",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/yiisoft/yii2/db/Command.php",
            "line": 417,
            "function": "queryInternal",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/yiisoft/yii2/db/Query.php",
            "line": 249,
            "function": "queryAll",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/craftcms/cms/src/db/Query.php",
            "line": 292,
            "function": "all",
            "class": "yii\\db\\Query",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php",
            "line": 1837,
            "function": "all",
            "class": "craft\\db\\Query",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/twig/twig/src/Extension/CoreExtension.php",
            "line": 1754,
            "function": "all",
            "class": "craft\\elements\\db\\ElementQuery",
            "type": "->"
        },
...
        {
            "file": "/srv/site/vendor/twig/twig/src/Environment.php",
            "line": 306,
            "function": "render",
            "class": "Twig\\TemplateWrapper",
            "type": "->"
        },
        {
            "file": "/srv/site/vendor/craftcms/cms/src/web/View.php",
            "line": 500,
            "function": "render",
            "class": "Twig\\Environment",
            "type": "->"
        },
        {
            "file": "/srv/formie/src/models/Notification.php",
            "line": 166,
            "function": "renderTemplate",
            "class": "craft\\web\\View",
            "type": "->"
        },
        {
            "file": "/srv/formie/src/base/Field.php",
            "line": 1339,
            "function": "renderTemplate",
            "class": "verbb\\formie\\models\\Notification",
            "type": "->"
        },
        {
            "file": "/srv/formie/src/base/Field.php",
            "line": 578,
            "function": "getEmailHtml",
            "class": "verbb\\formie\\base\\Field",
            "type": "->"
        },
        {
            "file": "/srv/formie/src/helpers/Variables.php",
            "line": 357,
            "function": "getValueForVariable",
            "class": "verbb\\formie\\base\\Field",
            "type": "->"
        },
        {
            "file": "/srv/formie/src/helpers/Variables.php",
            "line": 343,
            "function": "getParsedFieldValue",
            "class": "verbb\\formie\\helpers\\Variables",
            "type": "::"
        },
...
</code>
</details>

I've bisected it and the offending commit is de432c5.  It looks like in my case `$value` is in the format where there is no `id` key so `$ids = ArrayHelper::getColumn($value, 'id')` ends up producing an `$ids` value of `[ 0 => null ]` which causes submission to break:
 
![ids_value](https://github.com/user-attachments/assets/dd7e3066-365d-472a-bba1-bdc6a2045ed3)

**Comment by engram-design** [comment]
Ah, sorry about that! Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.
