### ISSUE TITLE
Craft CP resources being loaded in front-end

### ISSUE THREAD

**Issue by gijsstegehuis** [verbb/formie#2119]
### Describe the bug

When rendering a formie form all Craft cp resources get loaded on the front-end.
This causes the layout to fail rendering as it conflicts.

<img width="848" alt="Screenshot 2024-11-06 at 10 27 19" src="https://github.com/user-attachments/assets/2d60de5f-fafb-4ab2-beb9-eb5228b2a452">

### Steps to reproduce

1. Add a formie form
2. Disable all css/js output
3. Use `craft.formie.renderForm(form)` to render it

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.10.4

### Plugin version

2.1.32

### Multi-site?

No

### Additional context

Please note that we have all outputs set to false/manual:
```
outputCssLayout: false
outputCssLocation: manual
outputCssTheme: false
outputJsBase: false
outputJsLocation: page-footer
outputJsTheme: false
sortOrder: null
template: _form
useCustomTemplates: true
```

**Comment by engram-design** [comment]
That's _very_ odd, the only way I see that happening is if the Craft debug toolbar is enabled. Otherwise, we don't load anything control panel related on the front-end. Is that something you have enabled?

What about module code, or any other plugin that might be interfering with things?

**Comment by gijsstegehuis** [comment]
Thanks Josh. This lead me in the right direction.

We have a module that has the `View::EVENT_BEFORE_RENDER_TEMPLATE` listener.
Turns out this fires when Formie renders.
The funny thing though, is that within that hook the templateMode becomes CP instead of site.

This then causes the issues described above.
For now i can work my way around it, but you might want to have a look at the templateMode.

**Comment by engram-design** [comment]
That probably makes some sense then, because Formie is going to use Craft's template rendering to do a few things when rendering the form, particularly if you have specific templates set. But if you're supplying your own form template, it _shouldn't_ be switching to CP-based rendering, so I'll double check this...
