### ISSUE TITLE
Select/deselect all option in Checkboxes field

### ISSUE THREAD

**Issue by am0** [verbb/formie#212]
**What are you trying to do?**
With long lists of checkboxes, might be nice to have the option to select or deselect all of them at once with one checkbox.

**What's your proposed solution?**
In the field settings (probably under general, maybe appearance) have a dropdown option to either not enable (by default) the checkbox, or have it appear at the top or bottom of the list. On the front end would fire off a bit of JS to toggle all the checkboxes in that field.

**Additional context**
Niche suggestion again, (sorry!), which I handled it by injecting another checkbox with some JS, but might prove generally useful for anyone dealing with long lists of checkboxes.

Thanks!

**Comment by engram-design** [comment]
Added support for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.3.19](https://github.com/verbb/formie/releases/tag/1.3.19)
