### ISSUE TITLE
[Salesforce] Cannot deserialize instance of multipicklist from START_ARRAY

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/formie#2124]
### Describe the bug

We have a client who is using checkboxes in Formie and, when submitting the data to Salesforce, they receive the following error:

```
2024-10-31 10:05:23 [ERROR] Salesforce: API error: “[{"message":"Cannot deserialize instance of multipicklist from START_ARRAY value [line:1, column:842]","errorCode":"JSON_PARSER_ERROR"}]” vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
```

### Steps to reproduce

1. Setup a Salesforce connection
2. Setup a multi-selection checkbox that should send the data to Salesforce

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.11.5

### Plugin version

2.1.28

### Multi-site?

No

**Comment by engram-design** [comment]
Seems to be working on my end. Can you send through what your Checkboxes field options are in Formie, and what the options look like for your Multi-Picklist in Salesforce? They need to match exactly.

**Comment by aaronbushnell** [comment]
Thanks, @engram-design! Our client manages their Salesforce integration so I'll pass this along to them. Since it's working for you I'll close this out and reopen a different issue if there's something more specifically happening that pertains to the Formie codebase
