### ISSUE TITLE
Bug: entries field with default value - Array to String Conversion Error

### ISSUE THREAD

**Issue by DieterVanhove** [verbb/formie#2125]
### Describe the bug

**Description**: Encountering an array to string conversion error when trying to set a default value in the entries field. The error occurs in my entries.html file at the line:

`{% set value = originalField.getDisplayTypeValue(value) %}`

It seems this is triggered by an improperly formatted EntryQuery ID structure. The ID is being generated as a nested array with an additional siteId, like so:

`[{"id":"26852298","siteId":"2"}]`

However, I think it should be a simple array with just the id, in the following format:
`[{26852298}]`

I tested it with a simple array and it seems to work.

Please let me know if you need more information.

### Steps to reproduce

1. Create new form
2. add entries field
3. select default value 
4. render form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.4.9

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
