### ISSUE TITLE
Time fields displayed in the submission list are off

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#2126]
### Describe the bug

When displaying date fields with the time in a form's submission list, the time is incorrect. It looks to be caused by not accounting for the timezone.

### Steps to reproduce

1. Create a form with a Date/Time field that displays only the time
2. Make a submission of the form
3. View the Submission list page and display the Time field

### Form settings

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: No

### Craft CMS version

5.4.10 Pro

### Plugin version

3.0.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
Looks like Craft/Yii's localisation handling for dates is messing these up. Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
