### ISSUE TITLE
Under "Form Behaviour" allow HTML in the "submission message"

### ISSUE THREAD

**Issue by TSeine** [verbb/formie#213]
**What are you trying to do?**
Add html to submission message

**Comment by engram-design** [comment]
I'm not sure this is a good idea, firstly from a user point of view, having HTML in the message doesn't make it very editable. Secondly, there are some potential security issues to address.

If anything, my suggestion would be to implement a "Source" toggle for the rich text editor, similar to Redactor. So for advanced users (developers) you can control the HTML, but for regular users it's still rich text. Would that suit your needs?

Do note that you can also control the buttons in the rich text editor if you need lists, links and more: https://verbb.io/craft-plugins/formie/docs/get-started/configuration#rich-text-configuration

**Comment by engram-design** [comment]
Closing for now and awaiting feedback on what "allow HTML" entails, if it's more than the provided rich text buttons functionality.
