### ISSUE TITLE
Google Places API key field is duplicated twice on settings page

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#2130]
### Describe the bug

The API key field is duplicated on the settings page

![image](https://github.com/user-attachments/assets/2d3658cd-609f-4907-84c8-f676512ad4b2)

### Steps to reproduce

1. Go to Formie Settings
2. Add an address provider integration
3. Select Google Places
4. Two API key fields will be displayed

### Form settings

N/A

### Craft CMS version

5.4.10.1

### Plugin version

3.0.9

**Comment by jamesmacwhite** [comment]
This technically is more of a front-end settings issue, the project config data only writes the API key field out once.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
