### ISSUE TITLE
Microsoft Dynamics 365 CRM integration: LogicalName vs SchemaName and targetSchemas

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#2132]
### What are you trying to do?

I've revisited the base integration for Dynamics 365 CRM (looks like there's been a fair few updates since Formie 1.x), and I've been through and updated our existing extended integration with the Formie 3 updates, to sync up and check things out.

There's a couple of areas I wanted to raise based on my testing.

### Target schemas

The targetSchemas event probably needs a bit of a doc update. When it was originally written the _getEntityOwnerOptions function wasn't as dynamic and only fetched standard CRM entities, now it appears to get custom one's as well, without having to implement the event at all, so that's good. It is still useful to modify the order/filter values, which mostly seems the same.

One area is any custom event schema using `select` needs to be passed as an array now due to the use of `implode()`, rather than  string. I had a schema override from Formie v1 which used select, but it was a string and threw an error.

### LogicalName vs SchemaName

This is the bane of my life with any Dynamics 365 integration and it looks like there's better handling for this. However, I can see where this is unfortunately not working in one of more field context. The SchemaName has been selected but only the LogicalName would be valid in a POST.

Here's an example field definition:

```JSON
{
    "@odata.type": "#Microsoft.Dynamics.CRM.LookupAttributeMetadata",
    "AttributeType": "Lookup",
    "IsCustomAttribute": true,
    "IsValidForCreate": true,
    "IsValidForUpdate": true,
    "CanBeSecuredForCreate": true,
    "CanBeSecuredForUpdate": true,
    "LogicalName": "ccl1000_enquirytypeid",
    "SchemaName": "ccl1000_EnquiryTypeId",
    "MetadataId": "3c6f6ea0-52b7-400c-b3ac-b60dead21f6b",
    "DisplayName": {
        "LocalizedLabels": [
            {
                "Label": "Enquiry Type",
                "LanguageCode": 1033,
                "IsManaged": true,
                "MetadataId": "ae3b5ccc-c3f8-4f2a-9ffb-4161b8ed490c",
                "HasChanged": null
            }
        ],
        "UserLocalizedLabel": {
            "Label": "Enquiry Type",
            "LanguageCode": 1033,
            "IsManaged": true,
            "MetadataId": "ae3b5ccc-c3f8-4f2a-9ffb-4161b8ed490c",
            "HasChanged": null
        }
    },
    "RequiredLevel": {
        "Value": "ApplicationRequired",
        "CanBeChanged": true,
        "ManagedPropertyLogicalName": "canmodifyrequirementlevelsettings"
    }
}
```

To be valid, this should be sent as `ccl1000_enquirytypeid@odata.bind`  but the Formie 3 integration selects `ccl1000_EnquiryTypeId@odata.bind` as the payload value, this will throw a 400 error for our environment.

I can modify the integration class, given we already extend it, but just wanted to flag those areas. Basically, our environment will break your logic of any Custom Attribute field that is relational i.e. lookup should use SchemaName, because that isn't the case here.

I'd be happy to make a docs update for you as I wrote the original target schemas, but I did want to highlight the updated logical around LogicalName vs SchemaName.

### What's your proposed solution?

* Doc update for target schemas with latest changes
* Review of LogicalName vs SchemaName behaviour since Formie 3 updates.

**Comment by engram-design** [comment]
Related to https://github.com/verbb/formie/issues/1579#issuecomment-2308572593.

For the target schemas - sorry, I did want to make it not a breaking change. I actually thought it should continue to work, as I knew you were using your events to modify things. Another customer needed to handle custom schemas, and didn't have module experience for making events, so figured I'd make it easy for all.

The LogicalName vs SchemaName is indeed really bloody annoying. There doesn't seem to be an official consensus on what to use. From what I've read on various places, LogicalName should be used in all instances, apart from Lookup (relational) fields.

So in your case, you're saying a Lookup field isn't working using LogicalName? I can confirm the reverse **doesn't** work for either my or another clients account. I'm not sure why that's the case though.

I wonder if it's a different when it's on a custom object, or a system one?

**Comment by jamesmacwhite** [comment]
No worries. The target schemas stuff is working, it is just for any entity using select this now needs to be an array compared to a string as you are doing the implode with commas, so an array must be passed. I had just a single instance of using select. No drama, a small doc update is fine as this event is more advanced and people who use it should know why they are using it.

LogicialName vs SchemaName. So using that field JSON as an example. Because IsCustomAttribute is true that has selected the lookup to use SchemeName, rather than LogicialName under the current logic. That isn't correct for this field, it should be LogicalName. In Formie 1, I basically just went through and modified anything to return LogicalName because looking our CRM environment metadata, it looked all LogicalName. That however is not a safe rule to use generally and you are absolutely right. I've seen about 20 different views on when you should use either. Not helpful. Even Microsofts Copilot AI, can't answer it!

For me, because we extend the class for a few other areas. I'm happy to modify it for our needs, it is however just something I wanted to flag. The handling of fields is better, so appreicate the efforts in Formie 3, I feel some D365 environments just want to watch the world burn!

**Comment by jamesmacwhite** [comment]
Whether or not there is distinction between IsCustomAttribute and the Lookup type specifically as you mentioned given that is a distinguishing factor you could potentially check, however at this point, I'm not advocating to change it in core if you have clients using the current logic, given I extend the class anyway, I can influence anything. If you have clients relying on the base class, I don't want potentially environment specific areas of our organisation trying to change working logic.

Formie isn't alone in the struggles on the right handle names. Zapier's D365 integration has the same problem with us as well, sometimes you start to wonder we are probably the problem!
