### ISSUE TITLE
[Salesforce Integration] Bug with phone country code

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#2133]
### Describe the bug

I have such setup of SalesForce integration:

![изображение](https://github.com/user-attachments/assets/6884636f-9cf0-490f-beb4-2d99fe17eb0a)
![изображение](https://github.com/user-attachments/assets/0da2be61-167b-44eb-bd0f-d04d11a95ec9)
![изображение](https://github.com/user-attachments/assets/ccc33473-4c94-4fe1-9020-30db7dcb8ad5)

### Actual behavior

If user fill phone with country code all works as expected:
![изображение](https://github.com/user-attachments/assets/10075c23-795c-43c9-934c-77c9d6755d12)

Formie submission data:
![изображение](https://github.com/user-attachments/assets/d1919460-4573-44d3-b368-89d432667cc3)

SF submission data:
![изображение](https://github.com/user-attachments/assets/c358a08a-c6a4-4f23-a579-005382fd3758)

If the user fills a phone number without a country code, the SF submission will not include country data.:
![изображение](https://github.com/user-attachments/assets/e4f0b179-8ef1-46d0-bcdf-00ef76089637)

Formie submission data:
![изображение](https://github.com/user-attachments/assets/eec71a89-b58a-46f8-a5d9-3fe6b9c15b1a)

Formie submission data:
![изображение](https://github.com/user-attachments/assets/d261c7b9-0093-4721-abcd-15a3cc8d0e0a)

### Expected behavior
Since we have country data obtained from the Country code field, there is no need to re-enter the code in the Phone Number field.
Country data should be sent to the SF based on the data from the Country code field.

Could you fix it?

### Steps to reproduce

1. Update to Craft 5
2. Try to submit the form with SF interest

### Form settings

- Multi-page form: Yes
- Submission Method: Both
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.4.9

### Plugin version

dev-craft-5

### Multi-site?

Yes

**Comment by Romanavr** [comment]
I think I have encountered the similar issue.
Is it a bug or I'm doing something wrong?

**Comment by engram-design** [comment]
That's odd, refer to my testing:

Front-end
![image](https://github.com/user-attachments/assets/7fd1a94a-25c6-4d5c-9e15-02df39d376d3)

Submission content
![image](https://github.com/user-attachments/assets/0341f619-28d4-4d8c-8b0f-49638fe15d7d)

Field Mapping (for Lead)
![image](https://github.com/user-attachments/assets/2658641d-7b07-4679-ad6b-84d55ddb892c)

Payload sent to Salesforce
![image](https://github.com/user-attachments/assets/241c3614-c07a-4c28-b3b7-85d70b39a233)

So looks like your submission data is all looking good, does the submission look correct in the control panel?

**Comment by umkasanki** [comment]
You are right.
The problem was in my module.
