### ISSUE TITLE
Phone number field not available in Feed Me submissions mapping

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#2137]
### Describe the bug

The phone field does not appear in the Feed Me Submissions element mapping.

### Steps to reproduce

1. Create Feed Me feed with the Submission element type
2. On the mapping any phone field for a form is not available to map for submission importing.

### Form settings

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

5.4.10.1

### Plugin version

3.0.9 (dev-craft-5)

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
