### ISSUE TITLE
Craft 5.5.0 compatibility issues

### ISSUE THREAD

**Issue by gijsstegehuis** [verbb/formie#2141]
### Describe the bug

I've noticed you fixed the twig extensions problem in [3.0.5](https://github.com/verbb/verbb-base/releases/tag/3.0.5)
However, this version has another incompatiblity:

```
Class verbb\formie\fields\Address contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\PreviewableFieldInterface::previewPlaceholderHtml) in /app/user/vendor/verbb/formie/src/fields/Address.php on line 35
```

This issue didn't occur in v3.0.10

### Steps to reproduce

1. Install Craft 5.5
2. Add a formie form
3. Submit submission

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

5.5 Pro

### Plugin version

3.0.5

### Multi-site?

Yes

**Comment by gijsstegehuis** [comment]
Just noticed this is fixed with bumping `verbb/base`

**Comment by engram-design** [comment]
Yep, a `composer update` or a `composer require verbb/formie -W` should resolve the update in the `verbb/base` package.
