### ISSUE TITLE
Craft 5 Upgrade Fails Due to Undefined Method 'defaultCardAttributes()'

### ISSUE THREAD

**Issue by thilan-plato** [verbb/formie#2143]
### Describe the bug

Performed an upgrade to Craft 5 using the latest plugin version, but the migration fails with the following error,
`Exception: Call to undefined method verbb\formie\fields\Group::defaultCardAttributes() (/var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php:268)` 

### Steps to reproduce

1. upgrade to craft 5

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.5.0.1

### Plugin version

3.0.10

### Multi-site?

NO

**Comment by LukeAndrewColeman** [comment]
I'm also getting the same issue as above when upgrading from craft 4 to craft 5.

**Comment by viesrood** [comment]
Same error here.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.10"`.

**Comment by engram-design** [comment]
Fixed in [3.0.11](https://github.com/verbb/formie/releases/tag/3.0.11)
