### ISSUE TITLE
The setting available days from the field date gets lost after import.

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2144]
### Describe the bug

The setting `availableDaysOfWeek` doesn't get properly imported if the value is other then  All `*`.

### Steps to reproduce

1. Import this form:  [formie-date.json](https://github.com/user-attachments/files/17744215/formie-testDate-50260ddb-9d07-46cb-8b46-b77f4244b7a2.json)
2. Check the setting `Available Days`, all options are empty instead of `1,2,3,4,5`

### Form settings

- Multi-page form: No
- Submission Method: -
- Client-side Validation: -
- Custom Form Templates: -

### Craft CMS version

4.13.0

### Plugin version

2.1.33

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.33"`.

**Comment by engram-design** [comment]
Fixed in [2.1.34](https://github.com/verbb/formie/releases/tag/2.1.34)
