### ISSUE TITLE
1.6.45 to 1.6.46 breaking changes

### ISSUE THREAD

**Issue by scott-davidjones** [verbb/formie#2145]
### Describe the bug

I have a very old site using craft 3.x with formie 1.6 on a php 7.4 server - client is stubborn and wont upgrade. In an attempt to apply updates the formie version was upgraded to 1.6.46 (from 1.6.45)

The patch from a few weeks ago, contains php 8.x union types which break in php 7.4: https://github.com/verbb/formie/compare/1.6.45...1.6.46 

I know this is not a major issue for most people, but anyone who has stubborn clients like i do will not be able to apply this patch, and see how new the patch is, i'd be greatfull if it can be fixed.

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/94b63375-c35c-409d-a7ea-a729e326e800">

### Steps to reproduce

1. Use craft 3.x with formie 1.6.45 on a php7.4 system
2. Upgrade formie to version 1.6.46
3. attempt to load the site and be given a syntax error

### Form settings

n/a

### Craft CMS version

3.9

### Plugin version

1.6.46

### Multi-site?

no

### Additional context

n/a

**Comment by engram-design** [comment]
Fixed in [1.6.47](https://github.com/verbb/formie/releases/tag/1.6.47)
