### ISSUE TITLE
Submission notifications not being sent

### ISSUE THREAD

**Issue by jeroenboumans** [verbb/formie#2146]
### Describe the bug

Every form we're currently trying to submit gives back the following error:

```
2024-11-14 12:26:04 [ERROR] Failed to render dynamic string “{field:emailReferrer}”. 
Template error: “Property craft\web\View::$_twigExtensions does not exist”
.../vendor/verbb/base/src/services/Templates.php:74
```

It seems that the body cannot be parsed and fields are not _filled_

### Steps to reproduce

1. Create a form
2. Add an email field
3. Add the field to a notification in the body template
4. Submit the form

### Form settings

- Multi-page form: No
- Submission Method: tried both, same errors in log
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.5.0

### Plugin version

3.0.10

### Multi-site?

No

### Additional context

Tested both on staging and production

**Comment by jeroenboumans** [comment]
It seems that `verbb/base` was not up to date. Setting both to `^3.0` in the `composer.json` and running `composer update` fixed the issue.

**Comment by engram-design** [comment]
You shouldn't need to include the `verbb/base` package yourself, and a `composer update` or a `composer require verbb/formie -W` should get that package updated.
