### ISSUE TITLE
Class verbb\formie\fields\Address contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\PreviewableFieldInterface::previewPlaceholderHtml)

### ISSUE THREAD

**Issue by dmitryvatagin** [verbb/formie#2147]
### Describe the bug

Trying ti update craft 5.4.4 => 5.5.0.1

Error Output:
================
PHP Fatal Error 'yii\base\ErrorException' with message 'Class verbb\formie\fields\Address contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\PreviewableFieldInterface::previewPlaceholderHtml)'

in /var/www/html/vendor/verbb/formie/src/fields/Address.php:35

### Steps to reproduce

1. Try to update craft cms to version 5.5.0.1
2. Formie version dev-craft-5

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.4.4

### Plugin version

dev-craft-5

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be already fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10). I know you're on `dev-craft-5`, but that doesn't give an indication of the last time you ran a `composer update` to get the latest commits.

**Comment by dmitryvatagin** [comment]
@engram-design thank you, it works
