### ISSUE TITLE
Send Activation Email - always set to true

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#2148]
### Describe the bug

I've a form for registering to be a member - this must be approved by admin so we don't want the account activation email sent on submission to the user.

In the integration when I toggle the 'Send Activation Email' to false, save the form, and refresh the page it's set to true again?

### Steps to reproduce

1. Creater a user intergration
2. Activate it on a form
3. Click on the toggle to disable
4. Save form
5. Refresh page
6. Toggle is set to true again.

https://github.com/user-attachments/assets/78cdeee6-1a57-44fb-8d4f-c94c2568eb7e

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

Not the above matter as this is just in the from page in the cp.

### Craft CMS version

Craft Pro 4.13.0

### Plugin version

2.1.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.33"`.

**Comment by engram-design** [comment]
Fixed in [2.1.34](https://github.com/verbb/formie/releases/tag/2.1.34)
