### ISSUE TITLE
Locking editing of a specific form

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie#2149]
### Question

Is there any other way to lock a form from being edited by a specific user or user-group?

I know it is possible by setting permissions per form but that way when a new form gets created only the user that created the form can access and edit the form.

The reason we would like this is because we have project that have forms that are mapped to an external system using Events. But when the client changes/removes a field they don't match anymore. These type of forms we would like to lock.

**Comment by engram-design** [comment]
That's not possible at the moment, but if you have some PHP and module knowledge, that logic is certainly something you could bundle into a module.

**Comment by svondervoort** [comment]
Hey thanks for the tip. I'm not that experienced with PHP and modules but my colleagues are.
Could you push me in the right direction by giving a small run-down how to approach this so I can suggest it to my team?
