### ISSUE TITLE
Enhance javascript captcha to include configurable time on page

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#215]
Currently, the javascript captcha only checks if javascript is enabled. It would be nice to have a setting that requires a minimum number of seconds on the page.  The default could be zero which would match the current functionality. The idea here is that most bots will likely auto fill and submit in less than a few seconds whereas normal humans will likely take at least 30 seconds.

**Comment by engram-design** [comment]
Just added for the next release. To test this out early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.26",
  "...": "..."
}
```

Then run `composer update`.

**Comment by mattcdavis1** [comment]
great -thanks!

**Comment by engram-design** [comment]
Added in [1.2.27](https://github.com/verbb/formie/releases/tag/1.2.27)
