### ISSUE TITLE
Pardot Integration Error - invalid_request missing required code challenge

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie#2156]
### Describe the bug

Not sure if this is a Formie issue or a Pardot issue. But when setting up the integration and pressing the "Connect" button it gives the following error on the top of the page:
```
invalid_request missing required code challenge
```

Good to know is I've tried it locally and on a staging environment.

### Steps to reproduce

1.  Add the Pardot integration with correct credentials
2. Click the connect button

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates:  No

### Craft CMS version

4.12.0

### Plugin version

2.1.33

**Comment by svondervoort** [comment]
Apparently this is a Pardot issue where the Redirect URI must be a publicly available URL.

**Comment by engram-design** [comment]
That's interesting, I'm using a local dev server, with my Redirect URI set to `https://formie.test/formie/integrations/callback` and that's certainly working to connect.

All too happy to add the "Proxy Redirect" feature that we have on some integrations, which turns this into `https://proxy.verbb.io?return=https://formie.test/formie/integrations/callback`, which allows local development, but I have no idea why that's working for me!

**Comment by svondervoort** [comment]
Well I'm not 100% sure about my previous statement that it must be a publicly available URL. It might still be a Pardot configuration that changed between me testing it locally, on staging and on live. But at least when I then get the live DB it also works locally.

The weird thing though is that on the live environment it actually asked me to login to Pardot and on the others it didn't.
