### ISSUE TITLE
Submission title format does not provide the sub fields of a name field as options to select from the predefined list

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#2162]
### Describe the bug

Not sure if this is a bug, but when choosing fields for the submission title format, a name field does not provide the sub fields i.e. prefix, first name, middle name and last name as available options. You can select the name field itself as a single field however.

![image](https://github.com/user-attachments/assets/6855cc7c-489c-40da-a68c-9e842a2b7b38)

Compared to other fields like phone number/date of birth, the sub fields appears to be available, which made me report this as potential bug.

### Steps to reproduce

1. Create a form with a name field
2. For the form settings go to Settings and the Submission title format
3. Using the plus icon to choose the fields the name field does not provide its sub field as options, you can only select the main name field which would provide all values.

### Form settings

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

5.5.3

### Plugin version

dev-craft-5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.12"`.

**Comment by engram-design** [comment]
Fixed in [3.0.13](https://github.com/verbb/formie/releases/tag/3.0.13)
