### ISSUE TITLE
Autodelete drafts

### ISSUE THREAD

**Issue by pascalminator** [verbb/formie#2164]
### What are you trying to do?

I don't know if I'm just missing something in the settings, but I can't find anywhere an option to autodelete drafts. I configured the completed submissions in order for them to be autodeleted after 1 day, but it looks like I can't do the same with drafts.

### What's your proposed solution?

Add an option to let us delete drafts automatically after a specific period of time like we can already do with completed submissions.

**Comment by engram-design** [comment]
The "Maximum Incomplete Submission Age" plugin setting is for this, after X amount of days (default to 30), Craft's garbage collection will delete incomplete (draft) submissions. Note that garbage collection isn't run every time, so this may get triggered at a later date than after 30 days.

**Comment by pascalminator** [comment]
Indeed, I should've looked in the doc better.
