### ISSUE TITLE
Commit 21a838f introduced a bug where integration form lightswitch settings cannot be persistently turned off

### ISSUE THREAD

**Issue by jedso** [verbb/formie#2165]
### Describe the bug

I have a form with a recaptcha integration. The lightswitch fields, such as the "enable" lightswitch can never be persistently turned off. In this recaptcha integration, we have two lightswitch setting fields ("[enabled](https://github.com/verbb/formie/blob/e18554968b2f3800caa20c2ce0981b9fe71aaaf7/src/templates/forms/_panes/integrations.html#L60-L69)" switch and "[showAllPages](https://github.com/verbb/formie/blob/e18554968b2f3800caa20c2ce0981b9fe71aaaf7/src/templates/integrations/captchas/_form-settings.html#L6-L11)" switch). When switched off, neither of these fields end up in the request payload due to 21a838f. The value of these disabled lightswitches is an empty string so the logic in `formie-form.js` skips right over it.

https://github.com/user-attachments/assets/9dd411e9-f14c-4938-98ac-1dcc6a367412

### Steps to reproduce

1. Create a form with an integration that uses lightswitches in the pane settings 
2. Observe how enabling the lightswitch, and saving the form, works and is persistent
3. Now try to disable the same lightswitch, save the form, refresh the page and notice how the changes did not save

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.5.2

### Plugin version

3.0.12

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.12"`.

**Comment by engram-design** [comment]
Fixed in [3.0.13](https://github.com/verbb/formie/releases/tag/3.0.13)
