### ISSUE TITLE
"Select an option" showing in English on a Spanish site

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#2166]
### Describe the bug

I followed the discussion on https://github.com/verbb/formie/issues/60 but either couldn't get it working, or am trying to translate something that isn't supported. We have an English form for the English site, and a Spanish form for the Spanish site. When on the Spanish site, we've got Spanish labels etc, but in our Address field, "Select an option" for the Country subfield appears in English. There doesn't appear to be a way to change this in the control panel, and static translations in either `translations/es.php`, `translations/es/site.php` or `config/formie.php` don't change anything.

<img width="750" alt="image" src="https://github.com/user-attachments/assets/bdd0ff46-fe85-48dc-ba0e-0808f3ca185f">

<img width="576" alt="image" src="https://github.com/user-attachments/assets/493cbf4a-038a-4b99-be3b-44a7c39ac0c0">

### Steps to reproduce

1. Add a site for Spanish
2. Add a form with an address field
3. Select an option for Country is in English

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Custom Form Templates: Theme override

### Craft CMS version

5.5.3

### Plugin version

3.0.12

### Multi-site?

No

**Comment by darylknight** [comment]
Follow up: same issue with the File Upload field:

<img width="265" alt="image" src="https://github.com/user-attachments/assets/646373d7-f088-4339-a522-d613cc937a79">

**Comment by engram-design** [comment]
So [`Select an option`](https://github.com/verbb/formie/blob/d13d9592be4c4aee74f0663664976f225b028882/src/translations/en/formie.php#L1815) is certainly in our static translation file, so that should be all that's required.

Adding:
```
'Select an option' => 'Select an option (Spanish)',
```

Is working on my end at least: 
<img width="736" alt="image" src="https://github.com/user-attachments/assets/e8780edb-ddee-46af-97ba-f929a57dd597">

Note that Formie's translations need to be in `translations/es/formie.php`

**Comment by darylknight** [comment]
You're right, sorry I didn't realise `formie.php` needed to be in the `translations` folder. The file selection texts aren't working though.

**Comment by engram-design** [comment]
I believe that's a browser setting and not something we can change!

**Comment by darylknight** [comment]
I don't understand - are you going to update something in Formie, or is it something I need to do at my end? Or expect the users to do?

Edit - ah, did you mean "not" something we can change?

**Comment by engram-design** [comment]
Oop, sorry - I think I was typing on my phone at the time and that was indeed a typo. Yep, unfortunately this isn't something we have control over, other than creating a completely custom front-end file upload field (which is on our todo list), and up to the browser settings for the user viewing the form.

**Comment by darylknight** [comment]
Got it, thanks!
