### ISSUE TITLE
Multiple e-mail addresses via populated form fields not working.

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#217]
**Description**
I have a matrix block where I select a Formie form and add e-mail addresses in a plain text field.
Those e-mail addresses are sent to the form by using 
`{% do craft.formie.populateFormValues(form, { receivingEmailAddresses: to }) %}`.

In my form I have a hidden field with handle `receivingEmailAddresses`.

When I use this with a token in a notification mail, it only works when I use a single e-mail address. If not, I get this error:
`Notification email parse error for ReplyTo: {receivingEmailAddresses}”. Template error: “Address in mailbox given [x@y.com, a@b.be] does not comply with RFC 2822, 3.6.2.`

I tried different notations:
- Comma without a space
- Comma with a space
- Putting the emails between single quotes (to force a string or something) and a comma.

**Comment by engram-design** [comment]
If you're trying to use hidden fields as the source for emails, I'd recommend to swap it to a hidden Recipients field. A hidden field isn't geared towards treating it's content as emails.
