### ISSUE TITLE
Missing dateType on Field_Date in GraphQL

### ISSUE THREAD

**Issue by robin-veer** [verbb/formie#2171]
### Describe the bug

```graphql
query getForm {
  formieForm(id: 516252) {
    title
    handle
    settings {
      errorMessageHtml
    }
    pages {
      label
      rows {
        rowFields {
          label
          handle
          type
          displayName
          ... on Field_Users{
            displayType
          }
          ... on Field_Date{
            displayType
          }
        }
      }
    }
  }
}

```

When trying to get the `displayType` of the field date I noticed that this field is missing, despite it being mentioned in the [docs](https://verbb.io/craft-plugins/formie/docs/developers/field#date-time)

I would expect it to be available, in the same way it's available in for example Field_Users

### Steps to reproduce

1. Create a date field
2. Try and get the DisplayType value using Graphql

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.5.4

### Plugin version

3.0.14

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.14"`.
