### ISSUE TITLE
Add additional translations

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie#2176]
### What are you trying to do?

I noticed recently NL translations where added to the plugin by default.

### What's your proposed solution?

It would be great to include French, Italian, Spanish and maybe others to the mix as well.
We currently just run a file through Chat GPT for translation.

### Additional context

I also noticed ```"<p>Couldn’t save submission due to errors.</p>" => "<p>Kon inzending niet opslaan vanwege fouten</p>",``` is missing from the translations, but this might be because this is also manageable from the form itself.

**Comment by svondervoort** [comment]
For now only the ones for the frontend rendering would be ok: https://github.com/verbb/formie/blob/craft-5/src/services/Rendering.php#L292

**Comment by engram-design** [comment]
That would be from https://github.com/verbb/formie/pull/2062. 

And while I can certainly use [AI](https://github.com/verbb/plugin-translator) to generate translations. per our [discussion here](https://github.com/verbb/formie/pull/1838) with some people, It's never going to be 100% foolproof. I'm concerned that having badly translated content isn't a great look for the plugin, and might end up being more of a hindrance than help.

**Comment by svondervoort** [comment]
Thanks for the input. I understand having no translations (and falling back to the default EN) is better then having bad translations. So I guess for now it would be best to include them ourselves in the translations folder of the project?

**Comment by engram-design** [comment]
Yep, that's correct. I think if you want things translated, it's best to add them yourself specific to your own project. Very happy for a PR for anything, but I probably won't accept it if it's just the output from AI tools. So long as a native speaker has looked over it and made sense of it, more than happy to include it within the plugin!

We will likely start using [Crowdin](https://github.com/verbb/formie/issues/62) next year to assist with this to get some real people looking at translations.
