### ISSUE TITLE
Can't clone the date/time - dropdown field

### ISSUE THREAD

**Issue by hellomaud** [verbb/formie#2177]
### Describe the bug

Everytime I try to clone or import a existing date time (dropdown) field and I save my form I get this error: 

_Internal Server Error: Setting unknown property: verbb\formie\fields\subfields\DateYearDropdown::limit_

When the type isn't a dropdown, I don't get this error.

### Steps to reproduce

1. Make a new form
2. Add a date/time field
3. Make this the type: dropdown
4. Clone this field
5. Save the form

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5.5.0

### Plugin version

3.0.14

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.14"`.

**Comment by engram-design** [comment]
Fixed in [3.0.15](https://github.com/verbb/formie/releases/tag/3.0.15)
