### ISSUE TITLE
Overriding redirect settings from template is not respected if the form has errors.

### ISSUE THREAD

**Issue by mijewe** [verbb/formie#2185]
### Describe the bug

I'm overriding my Formie form's redirect settings in the template

```
{% if entry.samePageRedirect %}
    {% do form.setSettings({
        submitMethod: 'page-reload',
        submitAction: 'url',
        redirectUrl: craft.app.request.url ~ '?success=true',
    }) %}
{% endif %}
```

this is all good.

I have a (custom) field which uses PHP validation. So an invalid submission will submit fine on the front end, but fails the PHP validation and the page reloads with errors. Also all good.

Despite the HTML of the form correctly having the ?success=true redirect parameter, performing a valid submission does not redirect to the expected URL.

Instead, the user is redirected to whatever value is in the CMS settings.
In SubmissionsController.php, `$url = $form->getRedirectUrl(false);` is returning the CMS setting and not respecting the template overrides I've set.
In elements/Form.php,
```
// Allow specific override of redirect URL, likely from templates
if ($this->_redirectUrl) {
    return $this->_redirectUrl;
}
```
looks like it's supposed to handle this case, but that's returning `null` for me every time.

### Steps to reproduce

1. Override your form's redirect settings within a template.
2. Submit an invalid submission that will pass front end validation but fail back end validation.
3. Submit a valid submission.
4. Notice your redirect settings are not respected.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.13.5

### Plugin version

2.1.35

### Multi-site?

Yes

**Comment by engram-design** [comment]
So I'm testing this out by having a required field, but disabling client-side validation, but it's not going to redirect after submission because there are errors.

Maybe it's down to the custom validation that you're implementing if you can let me know about that?

As for `_redirectUrl` that's actually set using a different override:

```twig
{% do form.setRedirectUrl(craft.app.request.url ~ '?success=true') %}
```

Which is slightly different and a more hard-set for the redirect, which might be an option. But yeah, it shouldn't be redirecting anywhere if the submission fails to validate.

**Comment by mijewe** [comment]
> Maybe it's down to the custom validation that you're implementing if you can let me know about that?

Possibly! I've made a custom field which takes a regular expression, and validates against that.

```
public function getElementValidationRules(): array
{
    $rules = parent::getElementValidationRules();
    $rules[] = [RegularExpressionValidator::class, 'pattern' => $this->regexPattern];
    return $rules;
}
```

There's no FE validation (sidenote, because native html pattern validation doesn't support case insensitivity) so the user can submit a value that doesn't match the pattern which will fail the PHP validation.

**Comment by mijewe** [comment]
PS I was also having inconsistent redirect url behaviour on these forms regardless of whether the first submission was invalid - I didn't quite track it down but it felt like it could be to do with Blitz caching or the Servd environment, because I couldn't reproduce the issue locally.

I fixed this by switching to `{% do form.setRedirectUrl(craft.app.request.url ~ '?success=true') %}` as you suggested.

**Comment by engram-design** [comment]
Thanks for clarifying on the validation rule, that all seems pretty standard. I'll probably mark this as closed if you're using the `setRedirectUrl()` function if that'll work for you.
