### ISSUE TITLE
Issue with condition after import

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2186]
### Describe the bug

Conditions with numbers break after an export/import.

https://github.com/verbb/formie/blob/craft-4/src/controllers/ImportExportController.php#L227
The flag `JSON_NUMERIC_CHECK` encodes numeric strings as numbers.

The condition code now compares strings and numbers.
https://github.com/verbb/formie/blob/craft-4/src/web/assets/frontend/src/js/fields/conditions.js#L310

In the backend, the conditions work fine if I resave my submissions.

### Steps to reproduce

1. Import this form: [formie-number.json](https://github.com/user-attachments/files/18080451/formie-number.json)
2. In the frontend: check the option 14
3. The condition doesn't match because of the type difference `"14" === 14`
4. Change the condition in the backend to 8, it works `"8" === "8"`

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.13.5

### Plugin version

2.1.33

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.33"`. Best to export your forms fresh, as numbers shouldn't be strings.

**Comment by engram-design** [comment]
Fixed in [2.1.36](https://github.com/verbb/formie/releases/tag/2.1.36)
