### ISSUE TITLE
Soft-deleted stencils aren't being restored when applying project-config

### ISSUE THREAD

**Issue by jakobhaerter** [verbb/formie#2187]
### Describe the bug

When I create a new stencil and switch to another branch, the stencil stays soft-deleted after switching back and applying the project-config.

### Steps to reproduce

1. Create a new stencil
2. Stash the new stencil config
3. Apply the project-config – the stencil should be gone
4. Pop the stash
5. Apply the project-config again – the stencil should still be gone

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.5.3

### Plugin version

3.0.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.12"`.

**Comment by engram-design** [comment]
Fixed in [3.0.15](https://github.com/verbb/formie/releases/tag/3.0.15)
