### ISSUE TITLE
Pardot Integration "Map to Prospect" 500/cURL Error - "Could not resolve host"

### ISSUE THREAD

**Issue by leighgibbo** [verbb/formie#2189]
### Describe the bug

I've successfully connected the Pardot integration to Pardot using applicable keys/secrets etc.
I can click the "refresh integration" when "Map to Opportunity" is selected, and the respective Pardot fields populate the mapping table, however when attempting to "Map to Prospect", clicking the refresh button returns a cURL error, which looks like it's trying to fetch a Pardot API endpoint without the base URL included in the final guzzle request?

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/c1098db9-9391-44f2-93a6-09b53f6644ba" />

### Steps to reproduce

1. Configure Pardot integration and confirm it is connected and can refresh fields for other mappings like "Opportinity"
2. Enable the "Map to Prospect" and attempt to refresh form fields

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

5.5.5

### Plugin version

3.0.14

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.14"`.

**Comment by leighgibbo** [comment]
Josh you are a wizard! 🙏🙏🎉🎉

**Comment by engram-design** [comment]
Fixed in [3.0.15](https://github.com/verbb/formie/releases/tag/3.0.15)
