### ISSUE TITLE
Required Multi-line input (textarea) won't revert to "OK" status after typing 

### ISSUE THREAD

**Issue by ChatonMeow** [verbb/formie#2190]
### Describe the bug

If you submit an empty form with required fields, the required fields will be have the "fui-error" class and be outlined with the error color. For the standard Single-line text inputs, once you start typing in it, the error class will disappear. However, this isn't the case with Multi-line inputs (textarea). You type in it, but the error class will still be there.

The form will still submit though.
![Screenshot 2024-12-11 at 20 04 02](https://github.com/user-attachments/assets/5163e51b-680b-4f0e-9c2a-d999a4a860f0)

### Steps to reproduce

1. Create a form with "Validate Form on Submit" checked. 
2. Add a multi-line text input that is required.
3. Go to your website, and click the submit button. Your empty input should be in error state.
4. Write something in the input. It should still be in error state.

### Form settings

- Multi-page form: No
- Submission Method: Doesn't matter
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.9

### Plugin version

3.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.14"`.

**Comment by engram-design** [comment]
Fixed in [3.0.15](https://github.com/verbb/formie/releases/tag/3.0.15)
