### ISSUE TITLE
Usage Tab broken

### ISSUE THREAD

**Issue by frederik-station** [verbb/formie#2195]
### Describe the bug

In the usage tab of a form I don't see on which entries my form is used: 
<img width="602" alt="image" src="https://github.com/user-attachments/assets/29da37d3-05e0-4586-a5f6-c46ddc037fe5" />

It used to look like this on Craft 4:
<img width="602" alt="image" src="https://github.com/user-attachments/assets/6664ecd9-6fef-47fe-9297-8aaf17847d87" />

### Steps to reproduce

1. Create a Neo Field and add a Forms field to the field layout 
2. Use the Neo field on an entry and assign a form
3. Check the usage tab of that form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.5.6.1

### Plugin version

3.0.14

### Multi-site?

Yes

### Additional context

Migrated the site (including all the forms) from Craft 4 to Craft 5

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.14"`.

**Comment by frederik-station** [comment]
@engram-design that was fast! Thank you, it's working now 🙏
