### ISSUE TITLE
Data lost after form import

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2196]
### Describe the bug

After a form import, submissions data inside of groups are lost.
This used to work on version 2.
Are the data completely lost or can they be restored?

### Steps to reproduce

1. Import this form [formie-testGp.json](https://github.com/user-attachments/files/18193584/formie-testGp.json)
2. Add it to a page
3. Submit the form
4. Check the submission in the backend
5. Re-import the form 
6. All data in Group are now lost

### Form settings

- Multi-page form: No
- Submission Method: -
- Client-side Validation: -
- Custom Form Templates: -

### Craft CMS version

5.5.5

### Plugin version

3.0.15

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.15"`. 

This data will still be there for a submission however, the next save of a submission will discard it, so it's not _really_ there. Essentially, a new field was created with a new ID/UID where it shouldn't have been, and as submissions use the field's UID for content, it won't be picked up by the new field.

Unfortunately, you'll need to recover that data from before your import - so sorry about that.

**Comment by Megafry** [comment]
Thanks for the quick response.
The fix works, but not for the field name inside of groups and also the repeat fields.

[formie-testGp-2.json](https://github.com/user-attachments/files/18206999/formie-testGp-3f11d39f-dad9-436d-9cba-ea9801cdf0e6.json)

> Unfortunately, you'll need to recover that data from before your import - so sorry about that.

How can I do this in the easiest way?

**Comment by engram-design** [comment]
That should be properly fixed now.  To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.15"`. 

> How can I do this in the easiest way?

The only real way is through a database backup made before your import I'm afraid. You could also manually change the field UIDs to match what's in the submission.

**Comment by engram-design** [comment]
Fixed in [3.0.16](https://github.com/verbb/formie/releases/tag/3.0.16)
