### ISSUE TITLE
Getting unknown property: verbb\formie\elements\Submission::group10:selectoptions

### ISSUE THREAD

**Issue by lennonpuype** [verbb/formie#2197]
### Describe the bug

Hi, I am having an issue with a form with multiple pages. When having a list of checkboxes with a max of 5 I get this error when the checkboxes are inside a group and I go to the next page. Outside of the group I don't get this error.

### Steps to reproduce

1. Having a group with multiple checkboxes inside it
2. Set a max to the field
3. Go in the frontend to the next page and you get an error

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.5.7

### Plugin version

3.0.15

### Multi-site?

"Yes"

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.15"`.

**Comment by engram-design** [comment]
Fixed in [3.0.16](https://github.com/verbb/formie/releases/tag/3.0.16)
