### ISSUE TITLE
Syncing from scratch with stencils fails

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#22]
### Description
Syncing a Formie install from scratch (i.e. no templates or statuses) fails due to stencils syncing before the statuses and templates had been created.

**Comment by engram-design** [comment]
Can you comment on what "Syncing a Formie install" refers to? Project Config or otherwise?

Furthermore, as at least one status is generated for a new install, shouldn't it not be possible to have no statuses?

**Comment by engram-design** [comment]
Fixed in [1.0.6](https://github.com/verbb/formie/releases/tag/1.0.6)
