### ISSUE TITLE
Use form fields in AJAX submission forms

### ISSUE THREAD

**Issue by mufi-siebird** [verbb/formie#226]
**What are you trying to do?**
While using Client-AJAX, I tried to use custom fields but its not working. Its working if I set *Page Reload* option but not works with AJAX submission https://prnt.sc/vovmcu

**Comment by engram-design** [comment]
Should be added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.28",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
