### ISSUE TITLE
Unable to populate values of nested fields

### ISSUE THREAD

**Issue by Timusan** [verbb/formie#227]
It seems you cannot populate values of fields which are nested in other fields. Examples:

- A text field inside a field group
- The firstName subfield of a name field

If you try to set the value of a single line text field with the handle `textFieldOne` (for example) which is in a field group you suspect you can do this as per the [documentation](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms):

```
{% do craft.formie.populateFormValues(form, { textFieldOne: "Some Value" }) %}
```

However, doing so will throw  a `Call to a member function populateValue() on null` exception. If you drag this field to be top level (not wrapped by any other field) you can populate it as advertised.

So my guess was that we may have to ship the hierarchy with the template call like this:

```
{% do craft.formie.populateFormValues(form, { wrapperFieldHandle: {textFieldOne: "Some Value" }}) %}
```

Or maybe even something fancy like this:

```
{% do craft.formie.populateFormValues(form, { "wrapperFieldHandle.textFieldOne":  "Some Value" }) %}
```

Where `wrapperFieldHandle` is the top level field group handle which holds the single line text field. While the former does clear the exception (as the system can find a top level field with the handle `wrapperFieldHandle`) both of these calls still do not set the value of the `textFieldOne` field.

Looking at the `Rendered.php` code it looks as if it is not possible to populate the value of a nested field, is that correct? Or is this maybe missing in the docs?

**Comment by engram-design** [comment]
Yep, I believe this is a known issue at the moment, but I'll confirm shortly.

**Comment by engram-design** [comment]
I should make the comment this only is an issue for Group and Repeater fields. Populating fields with subfields (Name, Phone, Address) should work just fine.

For example with a Name field set to have multiple fields:

```
{% do craft.formie.populateFormValues(form, { myNameFieldHandle: { firstName: "Peter", lastName: "Sherman" } }) %}
```

**Comment by engram-design** [comment]
Added support for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.18",
  "...": "..."
}
```

Then run `composer update`. See also updated [docs](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms#repeater)

**Comment by engram-design** [comment]
Added in [1.3.19](https://github.com/verbb/formie/releases/tag/1.3.19)
