### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by MattWilcox** [verbb/formie#229]
At the moment it does not look as though Formie has multi-language support?

<img width="694" alt="Screen Shot 2020-11-24 at 20 21 58" src="https://user-images.githubusercontent.com/814039/100147099-c7f8b400-2e92-11eb-8114-282cfa3086c2.png">

**Comment by engram-design** [comment]
Correct, forms aren't multi-site enabled, so their content cannot be translated in the control panel, unless you use static translations (see https://github.com/verbb/formie/issues/60).

Closing in favour of https://github.com/verbb/formie/issues/84
