### ISSUE TITLE
[FR] Integration with payment processor and credit card fields?

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#23]
Obviously a longer-term question, but I'm wondering if you have any plans to include e-commerce features at some point? Before working with Craft we used WordPress + Gravity Forms and we frequently used their Stripe integration to create donation forms, event registration forms, etc. 

Since we're utilizing a custom JS front-end, we should be able to integrate Stripe checkout pretty easily with a couple of hidden fields, but I thought it was worth checking in to see if this was on your radar at all.

**Comment by engram-design** [comment]
It's something we've considered for a brief moment, but we honestly wanted to see how many people actually wanted this sort of feature. I know Freeform includes payment fields, but I just wasn't sure how much demand there'd be for it.

It's not on our immediate roadmap, but happy to leave this here to get some upvotes!

For others reading this issue, please add 👍 to the above issue to gauge interest.

**Comment by daltonrooney** [comment]
@engram-design I saw that you've added this to the 2.0 milestone, I was wondering if you had an estimate on when it might be implemented? We ended up writing our own Stripe integration for Formie and I'm wondering if we should release that as a plugin or if your integration will be out soon.

**Comment by engram-design** [comment]
@daltonrooney We've had to bump up to 2.0 due to Craft 4 being a bit of a major release with some breaking changes, so we were going to shift this up to 3.0 (or 2.x). However, I'd be super-keen to see what you have put together if it's worth discussing it? You're obviously welcome to release it as a plugin yourself, but this is something we'll certainly be including in Formie at one point.

Feel free to chat on the Craft Discord (`@crawf`), and potentially incorporating what you've done into Formie. We might be able to tackle this sooner, as part of 2.0

**Comment by daltonrooney** [comment]
Hiya @engram-design here's our repo if you're interested in taking a look: https://github.com/madebyraygun/one-click-payments

(I'm posting here since it looks like a few folks are following the issue and might also be interested. We also put it on packagist, but no plans to add to the Craft Plugin Store.)

Our implementation is specifically for a "donation" or "pay what you want" context, with only a single product in checkout at a time and variable product pricing. But we may continue to extend it for other uses as clients request.

**Comment by engram-design** [comment]
Nice one thanks @daltonrooney 

it’s been a while since I’ve checked in on this issue and there’s been a good amount of interest in it since it was posted. As such I might move it along the list for 2.0

**Comment by engram-design** [comment]
Very pleased to announce that Stripe payments (single and subscriptions) has been implemented in [2.0.0-beta.13](https://github.com/verbb/formie/releases/tag/2.0.0-beta.13). We'll also be including PayPal (single only) for the 2.0 release.

Would love to get feedback for anyone using the beta already!

**Comment by engram-design** [comment]
Added in [2.0.0](https://github.com/verbb/formie/releases/tag/2.0.0)
