### ISSUE TITLE
craft.formie.populateFormValues not working as of 1.3.0

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#235]
**Description**
`craft.formie.populateFormValues` not working as of 1.3.0. Recipient field still seems to work though.

```
{% do craft.formie.populateFormValues(form, {
    email: currentUser.email ?? null,
    recipient: entry.contactEmail,
}) %}
```

### Form settings
Please pick from the options below.

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.3.0
- Craft version: 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
I'm gonna be _that_ guy and say "are you suuuuuure"?

```
{% do craft.formie.populateFormValues(form, {
    emailAddress: '123@nothing.com',
}) %}
```

![image](https://user-images.githubusercontent.com/1221575/100223309-6bb79200-2f6f-11eb-8236-2ac08670841b.png)

**Comment by jaydensmith** [comment]
You're right, it's working now - problem between keyboard and chair.
