### ISSUE TITLE
Being able to use form data inside hidden fields

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#236]
**What are you trying to do?**
I have a Campaign Monitor integration which I'd like to send the full name of the subscriber.
I have two separate fields in my form, first name and last name (I prefer this over the combined option Formie provides).
However, in the integration I can only choose a single field per CM field.
So I'd like to have a hidden field in my form, where I combine the two fields to a full name so I can select that hidden field to send to CM.

**What's your proposed solution?**
Being able to use tokens or Formie field handles `{ firstName }` inside hidden fields.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
