### ISSUE TITLE
Saving submissions with checkboxes using mutations 

### ISSUE THREAD

**Issue by mylesthedev** [verbb/formie#237]
**Description**
I'm trying to save a form submission which has a field that is a checkbox.
It has multiple values that the user can select.

It seems GraphQL is expecting specific values, I'm not 100% if this is a limitation with GQL or how it has been implemented in Craft but I thought I would post this here incase others had similar questions.

Basically I need the field to accept any of the values or a combination of each one. 
Is that possible?

```
howDidYouHearAboutUs: String
The allowed values are [“Radio”, “TV”, “Social Media”, “Newspaper”, “Returning customer”, “Referred by a friend”]
``` 

**Steps to reproduce**
1. create form with checkbox and multiple values
2. attempt to save the submission using GQL mutations

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.1
- Craft version: 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
@mediabeastnz This this is technically a Craft GQL issue (https://github.com/craftcms/cms/issues/7197), but if not, I can easily add handling to this. We'll await the result.

**Comment by engram-design** [comment]
[Craft 3.5.17 is out now with this fix](https://github.com/craftcms/cms/issues/7197#issuecomment-745591220)
