### ISSUE TITLE
Notification conditional based on submission status

### ISSUE THREAD

**Issue by colinmeinke** [verbb/formie#238]
I recently had to write a module to extend formie to only send a notification when a submission status was changed to a certain state. It would be cool if the recently released notification conditionals also had the ability to add a condition based on status, as well as field values.

**Comment by engram-design** [comment]
Added in [1.3.2](https://github.com/verbb/formie/releases/tag/1.3.2)

**Comment by colinmeinke** [comment]
@engram-design amazing, thanks!
