### ISSUE TITLE
'Default Label Position' renders weird CSS class in FE

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#24]
### Description
Form CSS class is 'fui-labels-verbb\formie\positions\AboveInput'

### Steps

1. Create Form
2. Go to Form > Appearance
3. Select 'Default Label Position' > 'Above Input'
4. Save
5. Go to FE Form
6. Look at HTML

### Expected
`<form>` tag has CSS class `fui-labels-above-input`

### Actual
`<form>` tag has CSS class `fui-labels-verbb\formie\positions\AboveInput`

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Additional info
- Plugin version: 1.0.7

**Comment by engram-design** [comment]
Fixed in [1.0.8](https://github.com/verbb/formie/releases/tag/1.0.8)
