### ISSUE TITLE
Agree field chopping off the instructions' last character in some cases

### ISSUE THREAD

**Issue by am0** [verbb/formie#240]
**Description**
The agree field is chopping off the last character if it's (after a brief bit of testing) a lower-case b or an r. Possibly others.
I'm guessing that it's looking for <br /> tags to remove?

**Steps to reproduce**
1. Add an agree field
2. Have the last character be a b or an r, so for example, the input the word 'Organiser'
3. On the front end the instructions will show up as 'Organise'

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: Latest
- Craft version: latest
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.3.2](https://github.com/verbb/formie/releases/tag/1.3.2)
