### ISSUE TITLE
Ajax Form show wrong error in validation

### ISSUE THREAD

**Issue by amici-infotech** [verbb/formie#242]
**Description**
My area requires custom validation rules, I have added a validation from a custom plugin and it works good. When I enable AJAX validation in backend, it gives me wrong error. However, validation return right error in response, I always get wrong error message. Screenshot attached.

![image](https://user-images.githubusercontent.com/20450552/100603628-653c6800-332b-11eb-92ba-8d211cf60d1a.png)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.2
- Craft version: 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
