### ISSUE TITLE
Integrate Capsule CRM to Formie

### ISSUE THREAD

**Issue by mariovass** [verbb/formie#243]
I have been testing a bunch of new CRM's and am set on Capsule, its super slick and easy to use would be great if there was a integration where we can push form data to new opportunities.
https://developer.capsulecrm.com/

**Comment by engram-design** [comment]
Consider it added to our list to do!

**Comment by engram-design** [comment]
Added in [1.3.5](https://github.com/verbb/formie/releases/tag/1.3.5)
