### ISSUE TITLE
Phone number field with country dropdown inside repeater not working properly.

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#247]
**Description**
When using a phone number field with country dropdown inside a repeater field, the phone number field is not initializing properly - the country dropdown is not appearing.

**Steps to reproduce**
1. Add a phone number field with country dropdown to a form inside a repeater field.
2. Navigate to the form and add a repeater row - phone number field will not work properly.

### Form settings
- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.2
- Craft version: 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
