### ISSUE TITLE
Formie widgets for dashboard

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#248]
Would be very nice to have Formie widget for dashboard.
Ability to display entries or graph for specific form, for group of forms, for all forms, for website, webgroup etc.
So user can see easily just after login.

By my experience this is quite useful specially for user with limited access (HR etc.)

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0)
