### ISSUE TITLE
Rich text success message displayed as JSON string

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#25]
### Description
The 'flashNotice' does not seem to be converted from Rich Text to Html in 'Page Reload' mode

### Steps to reproduce
1. Create form in CP
2. Enter formatted text '**Thank** you for your message.' in 'Behaviour" > 'Submission Message'
4. Submit valid form in FE

### Expected
Message is '**Thank** you for your message.' 

### Actual
Message is '[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Thank"},{"type":"text","text":" you for your message."}]}]' 

### Hint
Works as expected in 'Ajax' mode

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Additional info
- Plugin version: 1.0.7

**Comment by engram-design** [comment]
Thanks for picking this up, not sure how I missed that. Fixed in [1.0.8](https://github.com/verbb/formie/releases/tag/1.0.8)
