### ISSUE TITLE
Formie violates GraphQL spec

### ISSUE THREAD

**Issue by andris-sevcenko** [verbb/formie#250]
**Description**
Because of how Formie generates the GraphQL type definitions for its fields, it ends up defining fields with the same name with different return types.

Since form fields implement the `FieldInterface` (which, by the way, is extremely ambiguous and will be probably be rendered invalid when Craft starts exposing fields over GraphQL), it's entirely possible for a query to query, for example, the "limit" setting on a Formie field in a way where the return type can not be inferred.

**Steps to reproduce**
1. Run the following query

```graphql
{ 
  form (id: 1) {
    fields {
      ... on Field_Address {
        limit
      }
      ... on Field_MultiLineText
      {
        limit
      }
    }
  }
}
````
 and you'll get
```graphql
{
  "errors": [
    {
      "message": "Fields \"limit\" conflict because they return conflicting types String and Boolean. Use different aliases on the fields to fetch both if this was intentional.",
      "category": "graphql",
      "locations": [
        {
          "line": 7,
          "column": 13
        },
        {
          "line": 11,
          "column": 13
        }
      ]
    }
  ]
}
```

This is because `Field_Address` has a field `limit` with type of `String`, while `Field_MultiLineText` has a field `limit` with type of `Boolean`. Since either can be returned, GraphQL cannot determine the return field type.

[Relevant reading](http://spec.graphql.org/draft/#sec-Field-Selection-Merging).

The best approach would be probably to use less ambiguous names for fields.

Related: craftcms/gatsby-source-craft#12

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
