### ISSUE TITLE
Overview of form entry before submit

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/formie#251]
**What are you trying to do?**
On the old website of one of our clients they had a multi-step form where on the last page you were shown an overview of the data you were about to submit. We've been trying to include this.

**What's your proposed solution?**
Up till now we're using the submission method using "Page-Reload (server-side)" so when we go to the next step of the form we can use the submission and render the fields and their values.

Using "submission.form.getFields()" for the fields and different other methods to get the value per field.
Right now we're still searching the docs for the best way to show it as a final page and just before the submit.
But we thought we share it here, to maybe include it as an option in the future.

**Comment by engram-design** [comment]
So I suppose my best recommendation would be to create an empty page to use as your summary page. You'd need to use template overrides, or some of the form hooks to take control of the last page to produce whatever you need.

We might introduce something for this, but its quite far away in terms of priorities.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
