### ISSUE TITLE
Add "current absolute URL" to hidden fields

### ISSUE THREAD

**Issue by marijana** [verbb/formie#253]
Would it be possible to add "current absolute URL" to hidden fields?
At the moment, the closes thing to this is "HTTP Refer URL" in "Default Value" field option.
It would be usefull in those cases where you want to have info from which entry or page the form was sent.
It would allow content editors to achieve this without having to rely on a developer to make those changes in templates.
Thanks!

**Comment by engram-design** [comment]
Added in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
