### ISSUE TITLE
Define checkboxes or radio buttons source or expand the category field's capabilities

### ISSUE THREAD

**Issue by Timusan** [verbb/formie#256]
It would be nice to have functionality in line with FreeForm where you can select the source of your values for both checkboxes and radio buttons. 

For example you can have a category tree that you might want to use to populate a list of checkboxes (think countries, product categories, ...). At this point, you need duplicate setup: You need to make your category tree to be used on entries, etc and you need to mimic this list when making your checkboxes on your form.

Since Formie adheres strongly to the principle of reusing as much from Craft as possible this duplicate setup is not very Formie-like and it is error prone. 

I am aware that you have a Category field type but it currently has a few drawbacks:

- You cannot select multiple items.
- It is always rendered as a drop down.
- It does not honer the hierarchy of category items.

So either we should be able to choose how a category field is rendered (render as drop down, select, radio), allow for multiple selections and honor the hierarchy of items ... or we should be able to select certain Craft items (such as a category tree) to be a source for certain fields (select, checkboxes, radio buttons, ...).

**Comment by engram-design** [comment]
Yep, this is on our roadmap!

**Comment by engram-design** [comment]
FYI, half of this is implemented in [1.3.17](https://github.com/verbb/formie/releases/tag/1.3.17) allowing element fields to have different rendering options.

But - we'll still be adding the concept of "sources" for checkbox/radio and select fields

**Comment by engram-design** [comment]
Finalised in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0)
