### ISSUE TITLE
Provide a drill down option on a category field

### ISSUE THREAD

**Issue by Timusan** [verbb/formie#257]
If you have a large category tree which you use on your form it would be nice to be able to drill down to show only a subsection of such a tree. I imagine this would go as follows:

- Drag your category field on your form (like now)
- Select your category (like now)
- A new drop down appears: Select your parent leaf (which is optional)

This new drop down would be recursive until you reach a level where all children have no children themselves. 
This way you can scope down what you want to present to the user while still maintaining the flexibility of having a category tree in your form.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
