### ISSUE TITLE
[FR] Send POST data to custom endpoints

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#26]
To handle a lot of obscure custom integration needs, I'd love to have a method for sending submitted POST data to a custom endpoint. We rely on this feature often in Sprout Forms, with the ability to send to a URL and map form fields.

**Comment by engram-design** [comment]
Yep, both things are on the roadmap!

**Comment by engram-design** [comment]
This is now supported in [1.2.0](https://github.com/verbb/formie/releases/tag/1.2.0) through a Webhook integration - particularly the Generic Webhook.

Refer to [docs](https://verbb.io/craft-plugins/formie/docs/integrations/webhooks#webhook).

But basically, provide a URL, and it'll send a [payload](https://verbb.io/craft-plugins/formie/docs/integrations/webhooks#payloads) to the URL you provide.
