### ISSUE TITLE
Allow target _blank attribute in HTML field

### ISSUE THREAD

**Issue by colinmeinke** [verbb/formie#268]
I have an HTML field in a form that includes a link to a terms and conditions page. I would link this to open in a new window, otherwise clicking it will navigate away from a potentially filled in form. I have added a `target="_blank` attribute, but this is being stripped by HTMLPurifier.

I already have a `config/htmlpurifier/Default.json` config that includes `"Attr.AllowedFrameTargets": ["_blank"]`, but Formie isn't respecting it.

Inside the `getRenderedHtmlContent` function Formie has `HTMLPurifier::process($this->htmlContent)`.

This function can take a config as a second argument: `HtmlPurifier::process($this->htmlContent, $config)`.

For example, this is how Redactor creates a config that allows for config file overrides https://github.com/craftcms/redactor/blob/v2/src/Field.php#L1010L1035.

Thanks!

**Comment by engram-design** [comment]
Added in [1.3.5](https://github.com/verbb/formie/releases/tag/1.3.5)
