### ISSUE TITLE
Adding dynamic recipients to admin form

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#271]
**What are you trying to do?**
I'm using a Craft setup with 28 subsites, each having their own admin. The admin emails are set as a global. It would be nice to add dynamic recipients to the notification. Now you can add the emails being used in the template and system emails but no dynamics allowed.

**What's your proposed solution?**
Allowing the field to pass {{ global.adminEmail }}

**Additional context**
<img width="1676" alt="Screenshot 2020-12-21 at 16 45 14" src="https://user-images.githubusercontent.com/20947573/102794618-ee374400-43ab-11eb-97fe-5188e64315dd.png">

**Comment by engram-design** [comment]
Added support for globals in [1.3.5](https://github.com/verbb/formie/releases/tag/1.3.5)
