### ISSUE TITLE
Add "fui-error" class on form labels when the related form field has an error

### ISSUE THREAD

**Issue by Antimated** [verbb/formie#273]
**What are you trying to do?**
I'm attempting to get form label to color red whenever a form field is has an error.

_What I have:_
![Schermafbeelding 2020-12-24 om 09 43 22](https://user-images.githubusercontent.com/2869409/103075819-b78c4400-45cc-11eb-9415-dcc653d49da5.png)

_What I want:_
![Schermafbeelding 2020-12-24 om 09 43 59](https://user-images.githubusercontent.com/2869409/103075849-c2df6f80-45cc-11eb-8df1-f5abf8a4291d.png)

**What's your proposed solution?**
Either add a "fui-error" class on the "fui-label" or on the surrounding "fui-field-container".

**Additional info**
I'm using Ajax in my form

**Comment by engram-design** [comment]
Added in [1.3.10](https://github.com/verbb/formie/releases/tag/1.3.10) - `fui-error` is now added to the `.fui-field` node.
