### ISSUE TITLE
Having the option to change form submit action

### ISSUE THREAD

**Issue by marijana** [verbb/formie#274]
Having the option to manually set action for form submit would be helpful to us. 
We often have the need to pass data outside of normal functions of the usual form. 

Thanks!

**Comment by engram-design** [comment]
Are you referring to the "Action on Submit" form setting? If so, you can override that at the template level.

Or - otherwise, can you clarify what you mean by "manually set action for form submit"?

**Comment by marijana** [comment]
Yes, "Action on Submit" form setting.
We allow users to create forms and do everything without need for changes on the template level.
That is why this would be usefull if added to "Action on Submit" in the "Behaviour" tab when creating/editing form.

**Comment by engram-design** [comment]
You should be able to override that in your templates, using `submitAction`.

```
{% set form = craft.formie.forms.handle('contactForm').one() %}

{% do form.setSettings({
    submitAction: 'message',
    submitActionMessage: 'Override success',
}) %}

{{ craft.formie.renderForm(form) }}
```

Refer to https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-forms#override-form-settings

Let me know if I've misunderstood your question.
