### ISSUE TITLE
How to apply a custom "uploadLocationSource" value to a File Upload field

### ISSUE THREAD

**Issue by tonyclemmey** [verbb/formie#275]
**Description**

Hello, I have just installed Formie with the idea of rendering a form with a file upload field (which of course works and uploads files to the volume set in the CP settings) but wanting to override the `uploadLocationSource` value/volume so it can be set dynamically by the page it is loaded on (frontend) or maybe in the future a drop-down list a frontend user could choose from.

I have tried to mock something up and when I do set `uploadLocationSource` in options, files stop uploading to the previous volume set in CP but do not appear in the volume desired.

Can this work? and if so what do I need to tweak here to achieve the custom `uploadLocationSource`

```
{# Set the uploads volume path dynamicaly #}
{% set uploadLocationSourceCustom = 'folder:' ~ volume.uid %}

{% set form = craft.formie.forms({ handle: 'testForm' }).one() %}
{% do craft.formie.registerAssets(form.handle) %}

<form id="{{ form.formId }}" method="post" data-config="{{ form.configJson }}" enctype="multipart/form-data">

    {{ csrfInput() }}
    {{ actionInput('formie/submissions/submit') }}
    {{ hiddenInput('handle', form.handle) }}


    {% for field in form.getFields() %}
    	{% namespace field.namespace %}

    		{% set uploadLocationSource = uploadLocationSourceCustom %}

    		{# Set required attributes for the field #}
            {% set options = {
               	uploadLocationSource: uploadLocationSource,
            } %}

    		{{ craft.formie.renderField(form, 'file-upload', options) }}

        {% endnamespace %}
	{% endfor %}

    <button type="submit" class="fui-btn fui-submit ">Submit</button>

</form>
```

**Additional info**
- Plugin version: @latest
- Craft version: @latest
- Multi-site: No

**Comment by engram-design** [comment]
This wasn't possible, but this functionality has been added in [1.3.8](https://github.com/verbb/formie/releases/tag/1.3.8).

Have a look at the [docs](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields#override-field-settings), but you now have a means to override the settings of a field. Where you're trying to set the `options` on a field, they're purely for rendering settings and providing the field templates with variables.

```
{% do form.setFieldSettings('fileUpload', {
    uploadLocationSource: uploadLocationSourceCustom,
}) %}
```

Should do the trick!
