### ISSUE TITLE
Retrieve Numeric Value of Phone Country Code

### ISSUE THREAD

**Issue by edhebert** [verbb/formie#277]
**What are you trying to do?**
In email notifications and entry integration, I would like to retrieve the numeric string for the phone country code for a location - for example,  "+1"  for the USA. Currently the phone:country variable returns the actual country, e.g. "United States".

**Comment by engram-design** [comment]
Added for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.7",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.3.8](https://github.com/verbb/formie/releases/tag/1.3.8).
