### ISSUE TITLE
429 Too Many Requests Constant Contact Integration

### ISSUE THREAD

**Issue by clarknelson** [verbb/formie#278]
**Description**
When adding constant contact to my form, I am unable to fetch the lists from constant contact:

![image](https://user-images.githubusercontent.com/4106671/103807198-afe08c80-501b-11eb-9c25-a90ed496c8f8.png)

The integration happens fine, I also see 500 error so maybe this is a problem with the plugin vs CC?

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.7
- Craft version: 3.5.17
- Multi-site: No

**Additional context**

Free version of the plugin, HTTP not HTTPS server

**Comment by clarknelson** [comment]
Sorry but switched to freeform.

**Comment by engram-design** [comment]
I’ll look into this. After waiting a little while (say an hour) was there any improvement?

When does the 500 error occur as well?

(apologies for the delay - we’re on a few weeks summer break)

**Comment by engram-design** [comment]
Also refer to https://v3.developer.constantcontact.com/api_guide/rate_limits.html and sounds like you might be hitting their API limits, which I would expect to also potentially happen with Freeform. Closing for now, but let me know if you want continue debugging.

**Comment by clarknelson** [comment]
thank you I will try your plugin again on the next website :)

**Comment by clarknelson** [comment]
Revisiting Formie, I am getting a 500 error for the following URL `/index.php?p=admin/actions/formie/integrations/form-settings` which looks something like this:

![image](https://user-images.githubusercontent.com/4106671/104494655-57ba0500-559c-11eb-9909-dc2cad17e265.png)

I have connected my constant contact account, I am getting this message when trying to fetch the lists in the form's integrations.

**Comment by engram-design** [comment]
So when you click on the refresh icon for "List" is redirects to a new screen, with that error message? If so, there might be a JS error on the page when editing your form, as it certainly shouldn't redirect you. Can you confirm any JS errors in your web dev tools?

Directly accessing that won't work.

I assume this is on a non-devMode enabled site, as its throwing a friendly error rather than a full stack trace?

**Comment by clarknelson** [comment]
I will the refresh button, it will process for a few seconds, and then I get this message in console:

![image](https://user-images.githubusercontent.com/4106671/104741706-2ada2f00-570f-11eb-8d3a-4e147ebfd455.png)

I didn't notice regarding dev mode, when enabled it provides more information (but same message as before):

![image](https://user-images.githubusercontent.com/4106671/104742128-afc54880-570f-11eb-8145-246ae61b0f72.png)

Constant Contact rate limits 4 requests per second, I am wondering if the code attempts to reconnect too many times

**Comment by engram-design** [comment]
I did notice that rate limit, but in theory we shouldn't be hitting that, but I'll do some investigating further.
