### ISSUE TITLE
Updating a User Custom Fields

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#282]
I am using Formie to register a user through its User Integrations.

later down the journey, I am asking them to complete more fields of their user profile (fields that weren't requested when they created their account) so I am attempting to use another form to update user custom fields, and just mapping the remaining fields. The form is submitting successfully and storing in submissions but it is not updating their User Custom fields. Is it possible to do this? 

if it helps, in my error log I see `[error][formie] Unable to validate “{type}” element integration. Error: {error}.`

Thanks

**Comment by engram-design** [comment]
I'll double check what might be going on here. I believe you _should_ be able to, so long as you ask them to provide their email address which can be used to find an existing user to update.

**Comment by engram-design** [comment]
Actually, now I recall my thinking on this - it's currently not possible to update a user. The reason for this is that it opens up the possibility for **anyone** to update content against a user, so long as they know (or guess) their email address. Suffice to say, that's a reasonably large security concern.

So for the moment, this isn't possible, until I can think of a better way to handle this.

And that error message should've been fixed in 1.3.6 - I'm not sure what version you're on?

**Comment by mark-chief** [comment]
Ok I see what you’re saying. 

In my case they would be logged in to their account to update it so could do some checks in the template but that doesn’t stop it being used elsewhere by someone else in another app incorrectly I guess. 

I’ll update my version too. Thanks!!!

**Comment by engram-design** [comment]
Yeah, I figured you'd have some sanity check on your end at the template level, but leaving the implementation wide-open to abuse concerns me!

So far, I'm considering adding a User UID requirement for you to map against a hidden field. That's opposed to an ID, which could be just as easily guessed and abused.

I'll come back to you about this.

**Comment by engram-design** [comment]
Added support for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.3.22](https://github.com/verbb/formie/releases/tag/1.3.22)
