### ISSUE TITLE
GQL - Sourcing Error

### ISSUE THREAD

**Issue by danieladarve** [verbb/formie#285]
**Description**
Added a formie form field to the globals config in craft, and tried source it using Craft's Gatsby Source Plugin (gatsby-source-craft) but I get the following error:

`Field "settings" of type "FormSettingsInterface" must have a sub selection.`

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates:  No

**Additional info**
- Plugin version: 1.3.7
- Craft version: 3.5.17.1
- Multi-site: No

**Comment by engram-design** [comment]
I can't say I'm yet familiar with Gatsby (or Craft's Gatsby Source Plugin), so will look into this. It sounds like it's not really related to the GQL Explorer, or general querying. cc @andris-sevcenko - should this be anything on your end, or all me and Formie's schema for a form?

**Comment by andris-sevcenko** [comment]
This is related to craftcms/gatsby-source-craft#12

A possibility for Formie to fix this has been added to the 3.6 branch, so should be possible to fix without custom fragments soon!

**Comment by engram-design** [comment]
Thanks for the clarification @andris-sevcenko much appreciated!

**Comment by danieladarve** [comment]
Thanks guys!

**Comment by engram-design** [comment]
Should be fixed in [1.3.9](https://github.com/verbb/formie/releases/tag/1.3.9)
