### ISSUE TITLE
Object of class craft\fields\data\MultiOptionsFieldData could not be converted to string - After upgrade to 1.3.8

### ISSUE THREAD

**Issue by Timusan** [verbb/formie#287]
**Description**

A form which previously threw the error regarding the form field (mentioned in ticket #279) now throws a new, previously unseen error: `Object of class craft\fields\data\MultiOptionsFieldData could not be converted to string` while validating or saving. Trying with a completely new, empty form with only a checkboxes field gives the same error.

**Edit**: Making the field required seems to make the validation work, but saving will still throw the exception making for no form with a Checkboxes field to be able to be saved. Radio buttons seem to work fine.

**Steps to reproduce**
1. Create a new form
2. Add a Checkboxes field
3. Submit 

### Form settings

- Multi-page form: No
- Submission Method: Ajax or Page Reload (Does not matter)
- Client-side Validation: Yes or No (Does not matter)
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.8
- Craft version: 3.5.17.1
- Multi-site: No

**Comment by Timusan** [comment]
After a bit of digging the culprit is clear. This commit breaks submission when using checkboxes (`src/helpers/Variables.php `): https://github.com/verbb/formie/commit/b72fe70e3a10eba1dc6c5bdbd39decbbd72e80e4#diff-43839de0e07c091a7a354e919b61558c35a10b8e3b39e6c921b893a10afbdef2

**Comment by Timusan** [comment]
Created possible PR: https://github.com/verbb/formie/pull/289

**Comment by engram-design** [comment]
Should be fixed in [1.3.9](https://github.com/verbb/formie/releases/tag/1.3.9)
