### ISSUE TITLE
Error on changing field handle - Syntax error or access violation: 1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by MariusStenbakk** [verbb/formie#288]
**Description**
Error on changing field handle. Error happens across all forms, fields and users.

**Steps to reproduce**
1. Make a new form with fields
2. Change a field handle

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.6
- Craft version: Craft Pro 3.5.17.1
- Multi-site: No
- MySQL version: 8.0.19

**Additional context**
2021-01-08 12:23:07 [-][2804][-][error][yii\db\Exception] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `fm...')
#2 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1659): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(805): craft\services\Fields->applyFieldSave('b748fbdf-8185-4...', Array, 'formie:b402d408...')
#4 /var/www/html/vendor/verbb/formie/src/services/Forms.php(165): craft\services\Fields->saveField(Object(verbb\formie\fields\formfields\SingleLineText))
#5 /var/www/html/vendor/verbb/formie/src/controllers/FormsController.php(156): verbb\formie\services\Forms->saveForm(Object(verbb\formie\elements\Form))
#6 [internal function]: verbb\formie\controllers\FormsController->actionSave()
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save', Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('formie/forms/sa...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('formie/forms/sa...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/web/index.php(26): yii\base\Application->run()
#16 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
The SQL being executed was: ALTER TABLE `fmc_byggestrom` CHANGE `field_firmaOrgnr` `field_orgnrfodselsdato` in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:677
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fm...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `fm...')
#2 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1659): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(805): craft\services\Fields->applyFieldSave('b748fbdf-8185-4...', Array, 'formie:b402d408...')
#4 /var/www/html/vendor/verbb/formie/src/services/Forms.php(165): craft\services\Fields->saveField(Object(verbb\formie\fields\formfields\SingleLineText))
#5 /var/www/html/vendor/verbb/formie/src/controllers/FormsController.php(156): verbb\formie\services\Forms->saveForm(Object(verbb\formie\elements\Form))
#6 [internal function]: verbb\formie\controllers\FormsController->actionSave()
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save', Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('formie/forms/sa...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('formie/forms/sa...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/web/index.php(26): yii\base\Application->run()
#16 {main}

**Comment by engram-design** [comment]
When you mention this happens across all forms, fields and users - you mean this error is thrown for _any_ field you try and rename the handle on? Or, is it just this specific field that is causing an error.

And to confirm, you're changing the handle from `firmaOrgnr` to `orgnrfodselsdato`?

**Comment by MariusStenbakk** [comment]
Hello, 

Thank you so much for replying! Were experiencing this issue on any fields were trying to rename the handle on. It might be relevant to state that the site is in production and have entries in all forms. 

Yes, that's correct. Were changing the handle from firmaOrgnr to orgnrfodselsdato.

**Comment by engram-design** [comment]
I wonder if this might be a MySQL 8 issue, as it's complaining about the SQL syntax, which I've not seen in this context before. I don't suppose you have a lower version to test on? If not, I'll do my best to spin up MySQL 8 to test on my end.

**Comment by MariusStenbakk** [comment]
Sorry about late response - been a lot going on over the last week. I can try an spin up a MySQL 7 server and give it a shot. I'll reply with the results.

**Comment by engram-design** [comment]
Quite alright, I also got a bit stuck getting MySQL 8 going as well.

**Comment by engram-design** [comment]
I've spent a good few hours with a MySQL 8 install, but unable to replicate this. Going to close this, as it's a little old, but feel free to re-open if this is still an issue.
