### ISSUE TITLE
Email notifications outputs HTML to subject field

### ISSUE THREAD

**Issue by MariusStenbakk** [verbb/formie#290]
**Description**
HTML tags from custom email template fields show up when field is used in subject

**Steps to reproduce**
1. Set custom email fields
2. Use one of those fields as part of subject in email notification

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.6
- Craft version: Craft Pro 3.5.17.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
This was fixed in [1.3.8](https://github.com/verbb/formie/releases/tag/1.3.8). See also https://github.com/verbb/formie/issues/284
