### ISSUE TITLE
Allow static ID to be set for forms

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#291]
**What are you trying to do?**
We are submitting form data to a third party service, but the submissions are failing because the service requires the form ID to be static. With the recent update to allow forms to appear multiple times on a page, the ID of forms now changes and is no longer static so our third party form submissions are no longer being accepted.

**What's your proposed solution?**
Ideally Formie would allow an optional static ID to be set for each form to override the default behavior. Understandably, this would mean that if a static ID is set on a form that form will not work properly if it appears multiple times on a page.

**Comment by engram-design** [comment]
Added in [1.3.9](https://github.com/verbb/formie/releases/tag/1.3.9). See https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-forms#override-form-id

**Comment by npegman** [comment]
Was this feature removed in V3?

**Comment by engram-design** [comment]
This was removed in Formie 2.x in favour of using [Theme Config](https://verbb.io/craft-plugins/formie/docs/theming/theme-config) to manage everything about the markup of a form.

```twig
{{ craft.formie.renderForm('contactForm', {
    themeConfig: {
        form: {
            attributes: {
                id: 'my-form',
            },
        },
    },
}) }}

{# Rendering #}
<div class="fui-i">
    <form id="my-form" class="fui-form">
        <div class="fui-form-container">
            <div class="fui-page">
                ...
```
