### ISSUE TITLE
Submitting a form from a locale other than the default locale prevents form submission.

### ISSUE THREAD

**Issue by Martinovdz** [verbb/formie#295]
**Description**
When you try to submit a form on a locale other than the default locale the form does not create a form submission.
Form email notifications will still be sent but without the submission values.
No submission will show up under Formie -> Submissions

If for example your default locale is nl then http://www.website.com/nl/ will work, but http://www.website.com/en/ will not.

**Steps to reproduce**
1. Create a basic form and render it on your desired template
2. Switch to any other locale
3. Fill out all the form fields
4. Submit the form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.9
- Craft version: 3.5.17.1
- Multi-site: No

**Comment by engram-design** [comment]
Not seeing this behaviour at all. In fact, if the email notifications are being sent, then the submission is being saved, as it cannot be sent without that being the case.

For example, I've submitted a form via `http://formie.test/fr` - "Site 4" in my screenshots, which is not the primary site. The email notification also has content (using "All Fields").

![Screen Shot 2021-01-15 at 10 54 52 am](https://user-images.githubusercontent.com/1221575/104663181-8fea5080-5720-11eb-92be-e24d18205a3b.png)
![Screen Shot 2021-01-15 at 10 55 08 am](https://user-images.githubusercontent.com/1221575/104663190-92e54100-5720-11eb-8b59-4c1f214842a9.png)


Does the submission appear as incomplete (changing the status dropdown in the submissions index)? It should also appear in the database, in the `formie_submissions` table.

**Comment by Martinovdz** [comment]
I did just notice the site switcher as shown in your screenshot (shame on me) and I can see the submissions now!
However, all of these submissions are empty. I haven't mentioned in my steps to reproduce that I was using form groups. I removed all my groups and added some random fields and now it seems to work! So there might be something wrong with form groups? The form groups show up in my submission but there are no fields inside them whereas in the default locale everything is there.

**Comment by engram-design** [comment]
So when you mention the fields are empty, is that when you go in to view the submission? Or is it just when adding those custom fields as columns in the submission index that aren't showing?

Form groups shouldn't have much to do with the field content for submissions, but happy to look into it. From my testing though, going in an editing a submission certainly had field content values.

**Comment by Martinovdz** [comment]
Yes, when looking at the submission I can only see the groups but nothing inisde of them. They're basically grey boxes with a title.

**Comment by engram-design** [comment]
Ah, do you mean Group fields? There's content in other fields (like plain text), but not for your fields in Group fields?

**Comment by Martinovdz** [comment]
Exactly! This group field to be exact. Sorry for my vagueness! :)
![image](https://user-images.githubusercontent.com/9590628/104723610-cc717880-572f-11eb-8626-241acc5c075b.png)

**Comment by engram-design** [comment]
Fixed in [1.3.10](https://github.com/verbb/formie/releases/tag/1.3.10)
