### ISSUE TITLE
Multi-page forms using Ajax - jump to top of next page 

### ISSUE THREAD

**Issue by stevefloat** [verbb/formie#296]
**What are you trying to do?**
When using a multi-page form where the submission method is Ajax, it would be helpful after each page submission that the browser jumps (or auto-scrolls) to the top of the form's `fui-form-container`. Currently in testing, it retains its current position on screen - meaning when the subsequent `fui-page` is displayed, it displays half way down the form and the user must scroll up to the top to continue. This is more evident on longer forms.

**What's your proposed solution?**
On each page submission, when the new page is loaded the event could trigger the equivalent of an href anchor link to the top of the `fui-form-container`.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by stevefloat** [comment]
Great! Thanks Josh.

**Comment by engram-design** [comment]
Added in [1.3.10](https://github.com/verbb/formie/releases/tag/1.3.10)

**Comment by stevefloat** [comment]
Great!

**Comment by brettburwell** [comment]
This is nifty for multi-page forms, but it'd be nice to have this option available for after submitting a single page Ajax form too. Or maybe better yet, scrolling to wherever the submission message happens to be positioned.

**Comment by engram-design** [comment]
@brettburwell That should actually be the case at the moment, so long as the form submit action is to show a message - but it will only scroll to the top of the form. The thinking is that if you have the message set to show at the bottom of the form - well you don't really need to scroll to it!

**Comment by brettburwell** [comment]
@engram-design Doh! This particular form has evolved over time, and actually was set to have the message positioned at the bottom. That change did the trick. Thanks so much for the quick reply and sorry for the trouble. 

Also, bravo on Formie. It's a _really_ lovely plugin and you can tell how much care went into it.

**Comment by engram-design** [comment]
No problem, and thanks for the kind words!
