### ISSUE TITLE
Google Analytics integration

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#297]
**What are you trying to do?**
It would be nice to have a setting on the default templates to add Google Analytics settings. Like the data-tag-category, data-tag-label and data-tag-action.

**What's your proposed solution?**
Adding an extra settings in the form builder to add those targets in?

**Comment by engram-design** [comment]
Are you able to provide some clarification and examples of how this might look from the front-end? I've not used data-attributes to hook into Google Analytics before, usually using GTM and `datalayer` to send data.

Could you also use the Input Attributes table when editing a field to add these data attributes?

**Comment by cookie10codes** [comment]
@engram-design Sorry Josh! Totally forgot to answer.

it's about these data attributes https://mixedanalytics.com/blog/value-data-attributes-javascript-gtm/

**Comment by engram-design** [comment]
Yep! You should be able to manage these through the input attributes on a field?

![image](https://user-images.githubusercontent.com/1221575/108349727-749ac580-7237-11eb-9a16-53a61c23ee1b.png)

Would that work for you?

**Comment by michtio** [comment]
That might work @engram-design I'll let @KoeketieneDesign have a testrun with that tomorrow! Thanks :)

**Comment by cookie10codes** [comment]
@engram-design we will need it on the submit button, is this also an option?

**Comment by engram-design** [comment]
@KoeketieneDesign Yep, you can add those on the button(s) as well.

**Comment by cookie10codes** [comment]
@engram-design awesome! Thanks for your support 💪🏼
