### ISSUE TITLE
UI issues on Safari

### ISSUE THREAD

**Issue by jamesedmonston** [verbb/formie#298]
**Description**

Hey, getting some UI issues whilst using the form editor in Safari (`14.0.2`). See video [here](https://www.youtube.com/watch?v=bnDfW9BE7Os).

**Steps to reproduce**
1. Create/edit form in Safari
2. Make form long enough to overflow
3. Scroll/hover UI elements

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.9
- Craft version: 3.5.17.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.3.10](https://github.com/verbb/formie/releases/tag/1.3.10)
