### ISSUE TITLE
Can't Migrate Freeform

### ISSUE THREAD

**Issue by wuhhh** [verbb/formie#302]
**Description**

Attempting to migrate any Freeform form result in an internal server error. 

**Steps to reproduce**
1. Navigate to `/admin/formie/settings/migrate/freeform`
2. Select a form to migrate
3. Click _Migrate forms_

### Form settings
Please pick from the options below.

- Multi-page form: Both tested

**Additional info**
- Plugin version: 1.3.10 (Freeform: 3.10.2)
- Craft version: 3.5.17.1
- Multi-site: No

**Comment by engram-design** [comment]
Are you able to shoot through the error it shows with `devMode` on, or post your `storage/logs/formie.log` file? It certainly depends on your form setup, but all my test forms seem to be passing.

**Comment by engram-design** [comment]
Should be fixed in [1.3.12](https://github.com/verbb/formie/releases/tag/1.3.12), but let me know if not. In particular, I'd need some more feedback on the error.
