### ISSUE TITLE
Allow for pagination variables in retrieving integration data

### ISSUE THREAD

**Issue by shoored** [verbb/formie#303]
**What are you trying to do?**
We have activated the Active Campaign integration for Email Marketing.
In the Integrations Settings for a form you can select the List you want to map to.
However, only the first 20 lists are shown. This is because Active Campaign has a default pagination limit of 20.
So at times we cannot select the desired list because it's not included in the results.

**What's your proposed solution?**
It would be nice to be able to set a certain limit on the returned results, or to be able to "load more". This could be an issue / enhancement for other integrations as well I presume. 

ActiveCampaign docs on API pagination / limiting of results:
[API Docs](https://developers.activecampaign.com/reference#pagination)

Any tips on how to work around this for now?

**Comment by engram-design** [comment]
No workaround for the moment, but can action this shortly.

It's probably going to be a setting for each provider, as each will be a bit different. The options are to either make this configurable, or get Formie to get _all_ pagination items so you're always looking at the full list of lists.

Do you have a preference? How many lists for example do you have on your account? I can't imagine people would have thousands of lists, but it could be possible. My concern would be about API request limits (if we have to do 10 requests to get 1000 lists). But, there's not other way, other than introducing filtering options, which again, is provider-specific.

**Comment by engram-design** [comment]
I've implemented the auto-pagination for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by shoored** [comment]
Thanks for the quick action!

> Do you have a preference? How many lists for example do you have on your account? I can't imagine people would have thousands of lists, but it could be possible. My concern would be about API request limits (if we have to do 10 requests to get 1000 lists). But, there's not other way, other than introducing filtering options, which again, is provider-specific.

It differs per client, but a pagination limit of 100 is more than sufficient in my opinion. Making this configurable would probably be a nice feature but I understand the concerns about API limits.

**Comment by engram-design** [comment]
Added in [1.3.11](https://github.com/verbb/formie/releases/tag/1.3.11)
