### ISSUE TITLE
Impossible to reach submission completion using `goToPageId`

### ISSUE THREAD

**Issue by joshuabaker** [verbb/formie#305]
### Context

- We’re building a set of React components and hooks for Formie to use in a [Next.js](https://nextjs.org/) project
- To avoid CORS issues, we submit to [an API route](https://nextjs.org/docs/api-routes/introduction), which acts as a proxy for the Formie API

### Issue

In short, we cannot find a request that will allow us to submit a specific page _and_ complete a submission due to constraints in the [`formie/submissions/submit` action](https://github.com/verbb/formie/blob/0556acb75abb58d5e502ecaef939a8bba49696c3/src/controllers/SubmissionsController.php#L312).

- When using `goToPageId` submissions are [always marked as incomplete](https://github.com/verbb/formie/blob/0556acb75abb58d5e502ecaef939a8bba49696c3/src/controllers/SubmissionsController.php#L392-L399).
- Using `goToPageId` will also remove all validation because the [`$goingBack` flag is set to `true`](https://github.com/verbb/formie/blob/0556acb75abb58d5e502ecaef939a8bba49696c3/src/controllers/SubmissionsController.php#L335)
- Because our requests are via another backend no session is set, which means the [session-dependant `getCurrentPage()`](https://github.com/verbb/formie/blob/0556acb75abb58d5e502ecaef939a8bba49696c3/src/elements/Form.php#L585) method will always fail

### Solutions

- The simplest solution I could find was to add a `pageIndex` parameter and pass this into the [`$form->getNextPage()`](https://github.com/verbb/formie/blob/0556acb75abb58d5e502ecaef939a8bba49696c3/src/controllers/SubmissionsController.php#L331) call
- An alternative would be to check if page selected via the `goToPageId` is the last page, however, this configuration all feels a bit illogical

**Comment by engram-design** [comment]
Yep, I can certainly see how there are some extra hoops to jump through in this scenario. I appreciate the PR, and looks good to me, if that'll suit your purposes!

**Comment by engram-design** [comment]
See also https://github.com/verbb/formie/issues/319
