### ISSUE TITLE
Integration issue with multiple field fields like Name or Address

### ISSUE THREAD

**Issue by mylesthedev** [verbb/formie#308]
**Description**
It seems that special fields like Name or Address (fields that are split up into seperate fields) don't pull through to integrations as a combined field value.

For example I'm using the Pipedrive integration and a form has a Name field but when I then map that field to the integration I get an error from Pipedrive saying it didn't pass validation - I then change it to just use the first name field from the Name field and it works correctly.

See screenshots below of current setup.

**Steps to reproduce**
1. Create name field with 2 seperate fields e.g. first name + surname
2. Integrate Pipedrive
3. Map name field to a required field in Pipedrive e.g. Name of person
4. Submit and see if integration works

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.10
- Craft version: Craft Pro 3.5.18
- Multi-site: No

**Additional context**

![Screen Shot 2021-01-21 at 11 46 21 AM](https://user-images.githubusercontent.com/909749/105250314-688efa00-5bde-11eb-9573-b91567a2dcf9.png)
![Screen Shot 2021-01-21 at 11 45 49 AM](https://user-images.githubusercontent.com/909749/105250316-6b89ea80-5bde-11eb-83ee-749fb42c8f18.png)
![Screen Shot 2021-01-21 at 11 45 37 AM](https://user-images.githubusercontent.com/909749/105250319-6c228100-5bde-11eb-8fc7-6adb88acdbbc.png)
![Screen Shot 2021-01-21 at 11 45 19 AM](https://user-images.githubusercontent.com/909749/105250321-6cbb1780-5bde-11eb-9d59-f559e46b61b1.png)

**Comment by engram-design** [comment]
Yep, this was a recent regression. Should be fixed in [1.3.11](https://github.com/verbb/formie/releases/tag/1.3.11)

**Comment by mylesthedev** [comment]
All over it 🙌
