### ISSUE TITLE
Existing notification emails not available when creating or editing a stencil

### ISSUE THREAD

**Issue by russback** [verbb/formie#309]
**Description**
I have created an admin notification on a form and have saved the form as a stencil. When I go to edit the stencil, there are no notifications set, and If I click to add an existing notification, no existing notifications are found. 

### Form settings

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.10
- Craft version: 3.5.18
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by russback** [comment]
Thanks @engram-design that's resolved that.

I'm not 100% clear on how this works. If I create a notification on a stencil or a form, and then use that notification on an another form, do changes made to the notification on one form affect the others? Or are we just duplicating notifications here?

I guess similarly, is a stencil just a copy solution? i.e. if you create a stencil from a form, do changes to the form update the stencil? And by extension, if you change a stencil, does that update forms you have created from it? I'm assuming not, but it would be helpful to confirm and clarify.

It might be useful to have an area where you can see the the notifications that have been created, and which form(s)/stencil they are linked to.

**Comment by engram-design** [comment]
New notifications are created each time. We would need to introduce synced notifications (like synced fields) for changes to be linked across forms and stencils.

And that's correct, stencils and forms are not linked in any way. Just like if you duplicated a form, the two forms aren't linked.

A notifications management/area is on the future feature list I believe.
