### ISSUE TITLE
500 TypeError when creating form from stencil

### ISSUE THREAD

**Issue by russback** [verbb/formie#310]
**Description**
Possibly linked to [issue 309](https://github.com/verbb/formie/issues/309).

When creating a form from the stencil I have created, I get the following TypeError:

Argument 1 passed to craft\services\Fields::applyFieldSave() must be of the type string, null given, called in /{MY_PATH}/vendor/craftcms/cms/src/services/Fields.php on line 805

### Form settings

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.10
- Craft version: 3.5.18
- Multi-site: Yes

**Comment by engram-design** [comment]
Hard to say without looking at your form/stencil. Would you be able to shoot through your stencil by looking at the stencil settings in `config/project/formie/stencils`?

**Comment by russback** [comment]
@engram-design does [this video](https://www.awesomescreenshot.com/video/2472434?key=5ac520431e2dd9a35358a8068c3ce0f0) help?

**Comment by engram-design** [comment]
@russback The video does help, but would be great to get the content of the stencil is possible. Feel free to hit me up on the Craft Discord (crawf) if you'd rather send privately.

**Comment by russback** [comment]
What specifically can I send you? Shots of each tab on each field’s settings popup?

**Comment by engram-design** [comment]
I mentioned in my previous post - Would you be able to shoot through your stencil by looking at the stencil settings in `config/project/formie/stencils`? Stencil data is stored in yaml files.

**Comment by russback** [comment]
Ah sorry, misunderstood what you meant there!

I've sent that to you on discord.

**Comment by engram-design** [comment]
Alright, got to the bottom of this. Looks like there was a bug when "Saving as Stencil" for a form. It wasn't stripping out some information correctly.

This is fixed in [1.3.12](https://github.com/verbb/formie/releases/tag/1.3.12) - however, you'll need to re-save all your stencils. Just go to edit a stencil and hit "Save" without changes, which should kick in those fixes.
