### ISSUE TITLE
Add Loqate (formerly PCAnywhere) as an address integration

### ISSUE THREAD

**Issue by russback** [verbb/formie#311]
**What are you trying to do?**
Elsewhere on the site I am building, we use [Loqate](https://www.loqate.com/en-gb/address-verification/address-capture/) for address lookups.

The Formie integrations are great, but the UX for address providers is slightly different and the client would need to manage an account in Loqate as well as Google (for example).

**What's your proposed solution?**
Add an integration with Loqate.

**Comment by engram-design** [comment]
Never heard of it, but seems pretty neat!

**Comment by russback** [comment]
I suspect it may be fairly UK-specific but it’s been around for over 15 years now and has always been very good.

**Comment by engram-design** [comment]
Just wanted to quickly clarify what you meant about this:

> The Formie integrations are great, but the UX for address providers is slightly different and the client would need to manage an account in Loqate as well as Google (for example).

Anything I should be mindful of? They'll need to configure Loqate settings in Formie.

**Comment by russback** [comment]
No nothing in particular, my point was just that ideally you would have one single address lookup solution on a site rather than two so the the UX is consistent and you can maintain one billing account.

**Comment by engram-design** [comment]
Oh! Gotcha, consider it on our todo list.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
