### ISSUE TITLE
Date picker not being shown on front end in Safari for Date field

### ISSUE THREAD

**Issue by steverowling** [verbb/formie#312]
**Description**
I've added a date field to a form and set it to display as Calendar. When viewing the form on the front end, the date field displays as a plain text input. Clicking into the field does not display the date picker, it just operates as a normal text input. There are no console errors in the Web inspector in Safari. If I submit the form, then I can see the date field working correctly in Safari when editing the submission in the Craft control panel.

If I open the front end form in Firefox or Chrome, the date picker is shown as expected and works correctly.

The problem is compounded by the fact that it is possible to enter any text input in the Date field in Safari and it is accepted is as valid, both by the client side JS and server side. However, if a valid date format isn't entered in the form, the date saved in the submission is null. This is further compounded by not being able to add a placeholder to a Date field.

This makes the Date field unusable for anyone using Safari.

I get that you are leveraging the native date input behaviour in browsers, however Safari doesn't (yet) support Date input, so forms using Date inputs appear completely broken on Safari. I know that there are alternative display options, such as dropdown for year, month and day, but these aren't as user friendly as a date picker. It is doubly odd since a date picker is shown when editing the date field in the Craft control panel in Safari.

**Steps to reproduce**
1. Add a Date field to a form and set it to use Calendar view
2. Open form in Safari, the Date field will display as a conventional text input. The Date field will accept any text input as valid, however only valid dates will be saved to the submission, with no client-side or server side error generated when invalid date strings are entered in the Date field in Safari.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.11
- Craft version: 3.5.18
- Multi-site: Yes

**Additional context**
Safari 14.0.2 on macOS Catalina 10.15.7

**Comment by andypullen** [comment]
@steverowling Safari on macOS doesn't yet support the html5 date or time input types (https://caniuse.com/input-datetime) so they'd have to use a javascript workaround. I think the best option for us now is to [build our own field templates](https://verbb.io/craft-plugins/formie/docs/template-guides/form-templates#overriding-field-templates). Hope that helps!

**Comment by steverowling** [comment]
@andypullen Yeah, I know Safari doesn't support HTML5 date or time inputs yet and I acknowledged as much in my original post. However, as a paid plugin, especially one that positions itself as `championing user experience` (see [introductory blog post](https://verbb.io/blog/introducing-formie)), I don't think it's too much to ask that there is consistency across browser functionality out of the box for all field types.

Right now, using the calendar-style input for date fields on Safari on macOS is completely broken and permits completely invalid input data to be saved on forms. I think that's a bug that should be addressed. And I say that as a huge fan and supporter of Verbb plugins! (I use SuperTable and Navigation on several sites.)

**Comment by andypullen** [comment]
@steverowling I completely agree — I was simply trying to point out the option of building out a field template in the meantime in case you hadn't looked into it yet. I've been evaluating the plugin, and I'm glad you opened this issue since I noticed the same.

**Comment by engram-design** [comment]
So whilst I didn't specifically test in Safari for this (I actually though the datepicker with a Webkit thing, not just Chrome, so would flow on to Safari), I've considered adding a complete JS front-end for the datefield. 

What's stopped me however is finding something that is:
- Highly accessible
- Cross-browser
- No-dependancy
- Flexible (has an API)
- Lightweight

I'll continue my research to address this. I would **love** to not have to worry about it and rely on browser standards, so this very well may be a polyfill for unsupported browsers, like Safari. For instance, since starting Formie, there's already been two iterations of the native datepicker functionality in Chrome, which is encouraging.

**Comment by steverowling** [comment]
Yeah, I totally get wanting to just be able to rely on the native browser support. I **wish** it was there for Safari too!

[flatpickr](https://github.com/flatpickr/flatpickr) could be a possible candidate.

**Comment by engram-design** [comment]
Added flatpickr.js in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0). You can opt-out of course.
