### ISSUE TITLE
Enable form migration when allowAdminChanges is false

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#313]
**What are you trying to do?**
On our production environment, we have allowAdminChanges in Craft's general.php settings set to false. This removes the GUI options for migrating forms, which is the environment in which we'll need to execute that task.

**What's your proposed solution?**
Enable form migrations (or allow the option to enable it) on environments with allowAdminChanges set to false.

**Additional context**
In our (admittedly quick) testing, it doesn't look like the form migration process (at least for Sprout Forms) does not affect the project config files.

**Comment by engram-design** [comment]
Added in [1.3.12](https://github.com/verbb/formie/releases/tag/1.3.12)
