### ISSUE TITLE
Sprout Form migration does not import fields

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#314]
Migrating forms from Sprout Forms does not populate the imported forms' fields. Both the field layout for imported forms and their submissions are blank.

**Steps to reproduce**
1. Open Formie > Settings > Migrations / Sprout Forms
2. Select a few forms with fields
3. Go through the process of migrating forms

### Imported Form settings
- Multi-page forms: No
- Submission Methods: Both

**Additional info**
- Formie version: 1.3.11
- Sprout Forms version: 3.13.1
- Craft version: 3.5.18
- Multi-site: Yes

**Additional context**
It doesn't look like there's anything unexpected or telling in the formie.log file, other than this error:
```
2021-01-17 14:00:32 [-][1][-][info][formie] Setting unknown property: verbb\formie\fields\formfields\Phone::countryRestrict /home/vagrant/willamette/vendor/yiisoft/yii2/base/Component.php:209
```

**Comment by engram-design** [comment]
Looks like this might've been a recent Craft change, as fields are no longer created on second save of a form (which the migration did internally), and I tested this even last week.

Should be fixed in [1.3.12](https://github.com/verbb/formie/releases/tag/1.3.12)
