### ISSUE TITLE
Webhook integration payload returns error

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#315]
**Description**
When sending a live payload or a test payload for a webhook integration, a 500 status code is returned and this error displays:
```
 Error: Request failed with status code 500
API error: “Return value of verbb\formie\base\Webhook::getWebhookUrl() must be of the type array, string returned” /home/vagrant/willamette/vendor/verbb/formie/src/base/Webhook.php:121
```
The craft job also fails with the error `Undefined variable: rawResponse`, and the job data of:
```
{
    "submissionId": 690046,
    "integration": {
        "webhook": "•••••••••",
        "name": "Newsletter Signup",
        "handle": "NewsletterSignup",
        "type": null,
        "enabled": "1",
        "sortOrder": "1",
        "cache": null,
        "tokenId": null,
        "uid": "aec6c284-29dc-4a82-9c32-f0e8a41f3fa8",
        "referrer": "•••••••••",
        "id": "1",
        "dateCreated": "2021-01-21T20:36:02-08:00",
        "dateUpdated": "2021-01-21T20:36:02-08:00"
    },
    "description": null
}
```

**Steps to reproduce**
1. Setup a webhook
2. Enable the webhook on a form
3. Save the form
4. Display the form on the site, and submit OR click the Send Test Payload button in the CP

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: both Ajax or Page Reload
- Client-side Validation: n/a
- Custom Form Templates: No

**Additional info**
- Plugin version: 3.5.18
- Craft version: 3.5.18
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.3.13](https://github.com/verbb/formie/releases/tag/1.3.13)
