### ISSUE TITLE
Form submissions are saved as incomplete when using a custom form.

### ISSUE THREAD

**Issue by danieladarve** [verbb/formie#319]
I am trying to submit custom React.js form via ajax that has multiple pages and repeater fields. However, when I submit the form, the form is saved as incomplete, and i am not sure what the reason is...

In the response I get a submission Id which I can see in the database. However only the fields in the 1st page are saved.

The payload I am sending contains all the fields in every page:

Consider the following simple function:
```
const onSubmit = async (siteId, formHandle, csrf, recaptchaResponse) => {
  const formData = new FormData();
  // Append FormData
  formData.append("handle", formHandle);
  formData.append("siteId", siteId);
  formData.append("action", "formie/submissions/submit");
  formData.append("g-recaptch-response", recaptchaResponse);
  formData.append("CRAFT_CSRF_TOKEN", csrf);
  // Page 1
  formData.append("fields[name]", "First Last Name");
  formData.append("fields[email]", "email");

  // Page 2 (Repeater)
  formData.append("fields[addresses]", "");
  formData.append(
    "fields[addresses][rows][new1][fields][street]",
    "123 Street"
  );
  formData.append("fields[addresses][rows][new1][fields][city]", "Melbourne");
  formData.append("fields[addresses][sortOrder][]", "new1");
  //  Row 2
  formData.append(
    "fields[addresses][rows][new2][fields][street]",
    "456 Street"
  );
  formData.append("fields[addresses][rows][new2][fields][city]", "Sydney");
  formData.append("fields[addresses][sortOrder][]", "new2");

  const craftResult = await post(process.env.CRAFT_BASE_URL, formData);
  const { data } = craftResult;
  // Do something
  console.log(data);
};
```

@engram-design is there something I am missing in terms of the payload? 

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.13
- Craft version:3.5.17.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
This is a good point, in that I don't think I've addressed this scenario. Basically, the controller will detect it's a multi-page form, and think you're only submitting information for the first page. Typically, this is what you'd do, so you can save incomplete submissions (in case something goes wrong, the user leaves or just for abandoned form data).

More to the point, this is what the built-in Ajax form does, but that's heavily opinionated.

Two approaches here: 1. I can add handling for you to force all form data and complete the form as part of your payload request, or 2. You modify your front-end code to submit the form via Ajax for each step in your form.

**Comment by danieladarve** [comment]
@engram-design thanks for getting back to me. 
Option 1 sounds great.
I am wondering for Option #2 if I am submitting each step, how do I specify in the payload which step am I currently on. And would this mean if someone is to leave a multipage form unfinished, an incomplete entry would be kept in the DataBase?

thanks

**Comment by engram-design** [comment]
From the response back from your initial payload, you'd get a number of different properties back, but it's all undocumented and would require some changes on my end in any case the more I think about it.

I'll see what I can do, standby...

**Comment by engram-design** [comment]
I've added `completeSubmission` to help with this. I was going to change this to be the default behaviour, but it'll be a breaking change that'll be for another day. I would instead prefer to have the payload provide which page you're submitting , rather than rely on the controller using sessions to determine which page, which I think would be cleaner.

Should be added in the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joshuabaker** [comment]
> rather than rely on the controller using sessions to determine which page, which I think would be cleaner

Both cleaner and enabling for headless applications (i.e. Next API routes), which are becoming increasingly more commonplace.

> I've added `completeSubmission` to help with this

What does `completeSubmission` do?

**Comment by engram-design** [comment]
@joshuabaker Yep, just holding off on breaking changes (it'll mess up people's templates and JS).

Adding `<input name="completeSubmission" value="true">` to your payload (or the alternate JS form data) will tell Formie you're supplying the full form payload data. It'll internally skip to the final page and process the submission.

I know your issue https://github.com/verbb/formie/issues/305 was similar.

**Comment by engram-design** [comment]
Added in [1.3.14](https://github.com/verbb/formie/releases/tag/1.3.14)

**Comment by danieladarve** [comment]
Thank you for sorting this out! @engram-design
