### ISSUE TITLE
Formie doesn't work with Craft 3.6 due to dependency on mrclay/minify

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#324]
**Description**
Formie stops working after upgrading Craft to 3.6. When you try to visit the Formie page in the control panel, you get a `Class 'Minify_HTML' not found` error.

**Steps to reproduce**
1. Upgrade to Craft 3.6
2. Visit Formie page in control panel

**Additional info**
- Plugin version: 1.3.13
- Craft version: 3.6.0.1

**Additional context**
It appears that the root of the problem is that Formie is using the `Minify_HTML` class that is part of the `mrclay/minify` package. This package was a dependency of Craft 3.5, but was removed in Craft 3.6. A possible solution to this would be to make `mrclay/minify` a direct dependency of `verbb/formie`.

**Comment by engram-design** [comment]
Should be fixed in the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.3.14](https://github.com/verbb/formie/releases/tag/1.3.14)

**Comment by mtnorthrop** [comment]
@engram-design Sorry to bother you about this, but I still have 
```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.13",
}
```
in my `composer.json` file. Since this issue has been fixed, what should I change this line to if I want to get back on the normal update system? Should I change it back to `1.3.13`,  `1.3.14`, or something higher? I'm not 100% sure about how the plugin update system works, and I don't want to break anything... :-/

**Comment by engram-design** [comment]
@mtnorthrop You can change this back to `"verbb/formie": "^1.3.13",` and it should do the trick! You'll want to run `composer update` after that, just to ensure the correct version gets pulled as well. By default, that'll pick from the most recent version compatible with your project.

**Comment by mtnorthrop** [comment]
Thanks for that; I appreciate your time!
