### ISSUE TITLE
Custom email notification templates only working some of the time

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#327]
**Description**
We have a custom email template for `fields/address.html` that we configured to include the text that is typed into the address autocomplete field. To the default `fields/address.html`, we added the following code:

```
{% if field.autocompleteEnabled %}
    <strong>{{ field.autocompleteLabel | t(language=submission.formLanguage) }}: </strong>{{ value.autocomplete ?? ('No response.' | t(language=submission.formLanguage)) }}<br>
{% endif %}
```

This is working properly the majority of the time, but for some reason some of the notification emails are being sent without the autocomplete field included, even though the user has typed text into the field. It seems that some of the notifications are using the default `fields/address.html` rather than our custom override template. It's seemingly random which ones use the custom template and which ones do not.

**Steps to reproduce**
1. Add the custom code above to a `fields/address.html` notification override template.
2. Create a form with an address autocomplete field that uses the custom templates.
3. Trigger a notification.

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.14
- Craft version: 3.5.18
- Multi-site: No

**Additional context**
Our override templates folder structure looks like the following:

-fields
-- address.html
-- checkboxes.html
-- date.html
-- email.html
-- file-upload.html
-- multi-line-text.html
-- phone.html
-- repeater.html
-- single-line-text.html
-index.html

Our `index.html` override is working properly even when `fields/address.html` is not - I can tell because there is some text in that file that is being included in the email notifications.

**Comment by engram-design** [comment]
Actually a good point that the autocomplete value is missing from email templates, added in now.

I'll see what I can do to replicate this seemingly sporadic issue.

I assume cross-checking the submission (it actually has an auto-complete value)? How about checking on the sent notification for an incorrect address field - that all looks okay? What does re-sending that do?

**Comment by engram-design** [comment]
Oh, I should also ask the content of your "Email Content" - whether you're using "All fields" or outputting fields individually.

**Comment by jwrudzin** [comment]
Yes, I have checked the submissions and they do have an auto-complete value. Checking the sent notification shows the same thing I'm seeing in the emails - the auto-complete field is missing. Also, resending the notification does not change anything, the email resends without the auto-complete field.

I'm using "all non-empty fields" for my email content.

I appreciate you looking into this for me!

**Comment by engram-design** [comment]
Thanks for that. For now, I've added the auto-complete field in default templates in [1.3.16](https://github.com/verbb/formie/releases/tag/1.3.16), so that might help as well.

**Comment by engram-design** [comment]
Going to close this, as autocomplete is now included in Formie's email template for Address fields. But still going to look at what is going on with overrides not working.
