### ISSUE TITLE
Enable ReCaptcha by default on all new forms

### ISSUE THREAD

**Issue by russback** [verbb/formie#329]
**What are you trying to do?**
Ensure that ReCaptcha is applied to all forms, but it is turned off by default when creating a new form.

**What's your proposed solution?**
A default setting for new forms, or adding integrations to stencils.

**Comment by engram-design** [comment]
Add support for this in the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.16.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.3.17](https://github.com/verbb/formie/releases/tag/1.3.17)
