### ISSUE TITLE
Enable logged in users to save progress

### ISSUE THREAD

**Issue by russback** [verbb/formie#340]
**What are you trying to do?**
Have a way for users to complete part or all of a form as a draft. A use case is a job application where the form is very long and takes time to complete. It's common that for these kind of forms you have the option to save and then submit when you're ready.

**What's your proposed solution?**
Enable a save method on a form that would save a submission in a draft status, related to the logged in user. Enable a way for a user to list their submissions, load a submission within a form, and to submit a draft submission.

**Comment by engram-design** [comment]
This should be possible to implement yourself at the moment. 

All multi-page submissions are saved after each page submission as incomplete. You could have a hidden field in your form, saving the users' ID, or use the "Collect User" setting for forms to associate the currently logged-in user with the form.

Then, you might have a template in the user's account to list all their incomplete forms, using the `isIncomplete` query param:

```
// Fetch incomplete submissions for the current user
{% set submissions = craft.formie.submissions().isIncomplete(true).userId(currentUser.id).all() %}

{% for submission in submissions %}
    <a href="{{ url('/my-form', { submissionId: submission.id }) }}">Continue</a>
```

As you can see above, there's a link off to 'my-form' with a query param. On that page, you'd be rendering your form, but you would populate it with the incomplete submission.

```
{% set submissionId = craft.app.request.getParam('submissionId') %}
{% set submission = craft.formie.submissions.id(submissionId).isIncomplete(true).one() %}

{% if not submission %}
    {% exit 404 %}
{% endif %}

{# Tell Formie we're editing a submission #}
{% do submission.form.setSubmission(submission) %}

{{ craft.formie.renderForm(submission.form) }}
```

This is also outlined in [the docs](https://verbb.io/craft-plugins/formie/docs/template-guides/editing-submissions)

**Comment by russback** [comment]
Sorry @engram-design I completely missed that!
