### ISSUE TITLE
Edit spam keywords in environments where allowAdminChanges is set to false

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#347]
It doesn't appear that it's possible to add spam keywords to Formie in an environment where `allowAdminChanges` is set to `false`. 

It would be helpful if it were possible to add spam keywords in these environments so that end users can improve their spam protection without needing the help of a developer.

**Comment by mtnorthrop** [comment]
Also, to add to that, it doesn't appear that the spam keywords filter is working. For example, I've added the word `porn` to the spam keywords list, but spam with that word is still being submitted through the form.

**Comment by engram-design** [comment]
Yeah, this is a tricky situation in that this is a plugin setting, and you can't edit a plugin setting with `allowAdminChanges` set to false. Otherwise, this setting becomes out of sync with project config.

As for the spam keywords, my tests show that it's working on my end. What sort of fields are you testing your banned keywords in? I've tested single and multi-line, but would be good to confirm your field setup.

**Comment by mtnorthrop** [comment]
I understand the issue with the plugin settings and `allowAdminChanges`. I don't know how this could be fixed from a technical point of view, even though I think it would be a valuable feature, if a solution could be found.

I've tested the spam keywords in my development environment, and have found that the issue I'm having seems to be due to case sensitivity. The sample submission included the word `Porn` in a single-line text field, and my keyword list only included `porn`. When I added `Porn` to the list as well, the submission was filtered as spam, as expected.

**Comment by engram-design** [comment]
Yep, the keyword case-sensitivity should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.17",
  "...": "..."
}
```

Then run `composer update`.

As for the spam keywords being content managed, for now, I've added support to include a field handle in this field. This will take the content of a field (please make it a multi-line text) that you might be able to put in Globals and reference that in the Spam Keywords field.

You might call your custom field `spamKeywords` and put it in a global set with a handle `formSettings` where you'd enter `{formSettings.spamKeywords}` on a new line in Formie's spam keywords settings. Sorry that's a bit of a long-way around for the moment

**Comment by mtnorthrop** [comment]
Many thanks for finding a solution for this!
