### ISSUE TITLE
SQL error being thrown when trying to delete a copy of a form.

### ISSUE THREAD

**Issue by JohnCBent** [verbb/formie#351]
**Description**
One of our clients has made a copy (of a copy) of an existing form. They attempted to delete it and the form would not delete. When I attempted to delete it I also found that the form persisted after the delete process completed. When I checked the logs too see if any errors were thrown I found this:

"2021-02-17 10:55:17 [-][1][-][error][yii\db\Exception] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP '"idx_jcbzfkiptdmoifwfjspnaargqwdafftjchyy"'; check that column/key exists in /home/forge/www.washtrust.com/vendor/yiisoft/yii2/db/Command.php:1299"

"idx_jcbzfkiptdmoifwfjspnaargqwdafftjchyy" is an index in the db table for the form. I've included the stacktrace for this error as an attachment. 

I can provide the database table for the form if needed. 

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.16.1
- Craft version: Craft Pro 3.6.2
- Multi-site: Yes

**Additional context**
The site is using a managed database provided by digital ocean. I'm not sure if that factors into this or not, but thought that might be helpful to know.
[stacktrace.txt](https://github.com/verbb/formie/files/5997064/stacktrace.txt)

**Comment by engram-design** [comment]
I can't immediately reproduce this, but I'd say it'd very much depend on your specific setup.

Are you able to let me know the column name this index refers to? See this snapshot of the database table for the `fmc_*` table:

![image](https://user-images.githubusercontent.com/1221575/108459928-a3627b80-72cb-11eb-9a03-b3dc3d0636e8.png)

I believe these long index IDs are now generated by Craft 3.6+.

**Comment by JohnCBent** [comment]
Here's a screenshot of the table for the form. The SQL error is being caused by the first index (highlighted in the screenshot).

<img width="1278" alt="db_ss" src="https://user-images.githubusercontent.com/62077820/108557383-85464c80-72c6-11eb-9b46-8692d6eecb93.png">

**Comment by engram-design** [comment]
Thanks for this, I'll see what else I can uncover about this one, as I'm struggling to replicate this behaviour no matter how many forms I duplicate.

**Comment by engram-design** [comment]
Fixed in [1.3.19](https://github.com/verbb/formie/releases/tag/1.3.19). See also https://github.com/verbb/formie/issues/360
