### ISSUE TITLE
Multi page issues after upgrading dev-craft-3 as 1.2.26 > 1.3.17

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#356]
**Description**

We've just upgraded from (dev-craft-3 as) 1.2.26 1.3.17:

```
    "verbb/formie": "dev-craft-3 as 1.2.26",
    "verbb/formie": "1.3.17",
```

After upgrading forms with multi-pages won't submit, seems to be due to validation?
**Steps to reproduce**
1. On the initial page view, we get console errors saying elements are not focusable - the elements reported are all in the hidden fui-page div's.
![image](https://user-images.githubusercontent.com/599005/108638158-b5723300-74f2-11eb-88f0-7addb883c3ee.png)

2. Clicking submit without entering any data the first 'name' field throws the browser default validation message.
![image](https://user-images.githubusercontent.com/599005/108639450-6d0a4380-74f9-11eb-95f1-ec2081cf8ec8.png)

3. Reloading the page and clicking submit - we now get the correct inline errors.
![image](https://user-images.githubusercontent.com/599005/108639425-4e0bb180-74f9-11eb-84ed-be7770b479a0.png)

4. Completing the form and clicking submit - nothing happens. No network requests and no errors.
5. Looking at the elements - there's an empty fui-alets-error div:
![image](https://user-images.githubusercontent.com/599005/108639410-37fdf100-74f9-11eb-9cc6-f8be101e6889.png)
6. I can see the other tabs in the explorer - if I remove the 'hidden' class the new tabs show but with the fields in their error state?
![image](https://user-images.githubusercontent.com/599005/108639705-bdce6c00-74fa-11eb-856b-03720127d09e.png)
7. If I disable client-side validation, on completing page 1, I get no 2nd-page form showing.
![image](https://user-images.githubusercontent.com/599005/108639829-70063380-74fb-11eb-891a-6b03ea99af8b.png)

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.17
- Craft version: Craft Pro 3.5.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
You should only really get those errors if `novalidate` is not included on the form. That's because HTML5 validation will kick in and warn that there are hidden required inputs - what you're seeing in step 1. Using Formie's JS and client side validation, it should automatically add `novalidate` for the form. That's also why you're seeing the default browser prompts.

Are you able to confirm it's adding this attribute to the `<form>` element? 

![image](https://user-images.githubusercontent.com/1221575/108640662-244d8d00-74ef-11eb-9caf-a0fc78bda899.png)

Formie's JS' validation handling should only target the currently visible page, but it looks like from your other points that it's validating other pages. I note you're using custom templates, can you double check them against [these](https://github.com/verbb/formie/tree/craft-3/src/templates/_special/form-template).

**Comment by anchovy** [comment]
@engram-design - thanks for the prompt response (as always!)
Updated to use the `id: "#{form.formId}-p-#{page.id}",` syntax and it's working a treat now.

**Comment by engram-design** [comment]
Aha, yep that was the most major change with the form templates.

**Comment by anchovy** [comment]
Also - had an npm error when building our webpack assets after the update:

```
ERROR in ./vendor/verbb/formie/src/web/assets/frontend/src/js/utils/globals.js
Module not found: Error: Can't resolve 'formdata-polyfill' in '/Users/...../vendor/verbb/formie/src/web/assets/frontend/src/js/utils'
 @ ./vendor/verbb/formie/src/web/assets/frontend/src/js/utils/globals.js 37:0-27
 @ ./vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib.js
 @ ./src/js/app.js
```

I manually installed the package via `$ npm install formdata-polyfill` and this fixed the issue.

**Comment by engram-design** [comment]
Are you including our JS as part of your own JS? That seems odd, as it's a dependancy in Formie (which we are including). I'll look into it.

**Comment by anchovy** [comment]
Hi / Yep - including the formie JS as part of our own JS:

`import { Formie } from '../../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib'`

**Comment by bleepsandblops** [comment]
I'm having the same issue, but doing `npm install formdata-polyfill` isn't fixing it... including Formie the same way @anchovy is

**Comment by bleepsandblops** [comment]
What worked for me in the end is doing `npm install` in the `/vendor/verbb/formie` directory
