### ISSUE TITLE
Documentation request - use submission data in email template

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#357]
**Description**

We want to display form submission data outside of the `{{ contentHtml }}` in an email template.
How do/can we access the submission data within the template file?

For example - we've got a nicely designed HTML file with two columns.
In the first column we want to display the image associated with an id collected within the field then show a URL with the link text being the title of an associated field....

Rough/quick/example....

```
<div class="row">
  <div class="col-6-md">
    <img src="/path/to/image/id_{{submission.fields.FieldName1.value}}.png" />
    <a href="http://....com/{{submission.fields.FieldName2.value}}">{{submission.fields.FieldName3.value}}</a>
  </div>
  <div class="col-6-md">
    <p>
      <strong>{{submission.fields.FieldName3.label}}</strong>: <strong>{{submission.fields.FieldName3.value}}</strong><br />
      <strong>{{submission.fields.FieldName4.label}}</strong>: <strong>{{submission.fields.FieldName4.value}}</strong><br />
  </div>
</div>
```

Can this be done?

Thanks in advance.

p.s. the link _Email Templates_ Template Guide in https://verbb.io/craft-plugins/formie/docs/feature-tour/email-templates is incorrect, it's pointing to itself, the Email Templates Feature Tour.

**Comment by engram-design** [comment]
Sure, you should have access to those variables, refer to the [updated docs](https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates#available-template-variables)
