### ISSUE TITLE
HTML - Add rich text editor option, allowing form editors to add content in a rich text field, but render HTML on the front-end.

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#36]

**Comment by engram-design** [comment]
Shelving this for the near future. Complexities with storing content as ProseMirror, and raw HTML. Can ProseMirror properly support things like iframe, style, script, etc without stripping things out? This field is advanced, and should be used for raw HTML. It kind of needs to be developer-focused as such.

**Comment by Kashkin** [comment]
I would love to see this revisited, potentially using Vizy to provide a Richtext editor to form editors.

**Comment by engram-design** [comment]
I'll say this is slightly unrelated - this was to allow a rich text editor for the HTML field in the control panel, but I just don't think its needed.

Porting the WYSIWYG features from Vizy (a better link function) is on the list.

In some ways, a WYSIWYG editor will likely get in the way for pasting HTML.
