### ISSUE TITLE
Add Verify email field type

### ISSUE THREAD

**Issue by mrtomtom** [verbb/formie#365]
**What are you trying to do?**
Have a "verify email" field that makes user enter their email again to confirm it is correct.

**What's your proposed solution?**
have a field type or rule that allows you to specify another field it must be equal to for the form to validate

**Additional context**
Many customers have an email address as part of their form and want to force customers to confirm the email address is correct by getting them to type it again.

**Comment by engram-design** [comment]
Thanks! This _might_ evolve into a general "verify" or "confirm" field, as I imagine a similar scenario needs to be added for passwords

**Comment by mrtomtom** [comment]
Yes, or perhaps rather than a field type if could be a condition you attach to a field "is equal to *Select other field*?

**Comment by engram-design** [comment]
Yep, I like it!

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
