### ISSUE TITLE
[FR] - Klaviyo Integration

### ISSUE THREAD

**Issue by ljclark** [verbb/formie#369]
**What are you trying to do?**

Klaviyo is one of the larger ESP's out there, and a lot of people also use it as a CRM - so it would be great to be able to pass form data to Klaviyo with relevant mapping for Formie Fields -> Klaviyo User properties. 

It'd also be great to be able to pass an 'Event' as part of the integration, so that when a user submits a form and that data is passed to Klaviyo, it also adds an event to their profile (this could help trigger automations etc). If you could customise the payload of that event, even better, but even just a payload of the entire form submission would be handy, then you can pick and choose what data you want to use within Klaviyo's interface. 

Klaviyo Docs: https://www.klaviyo.com/docs

**Comment by ljclark** [comment]
Hey - is there an eta on when you're expecting v1.5 to be released with this feature?

**Comment by engram-design** [comment]
@ljclark No strict ETA sorry, but you could expect it in the next 3-4 months as an estimate.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
