### ISSUE TITLE
An empty HTML field causes a TypeError when the form is rendered on the frontend

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#371]
**Description**
If you add an HTML field to your form, but leave the field's "HTML Content" field blank, you will get this error when the form is rendered on the frontend:
```
TypeError
Argument 1 passed to craft\web\View::renderString() must be of the type string, null given
```
If you add a single space to the HTML Content field, the form will render without error. If you then delete the space so the HTML Content field is empty again, the form will still render without error.

**Steps to reproduce**
1. Add HTML field to your form, but leave its HTML Content field blank.
2. Try to view the page your form is being rendered on.

**Additional info**
- Plugin version: 1.3.19.1
- Craft version: 3.6.7
- Multi-site: Yes

**Additional context**
I know this is an edge case and adding blank HTML fields to forms isn't actually a feature I need. (I stumbled across it because I was trying to find a way of forcing a two-column layout in my form, but leaving the second column blank. The goal was to have the field in the left column display at 50% width without adding another visible field in the right column. In the end I used a Section field and set "Border" to "None".) I'm only submitting this issue because typecasting the content of the HTML field to string or adding validation would add a bit of polish to this great plugin.

**Comment by engram-design** [comment]
Should be fixed in [1.3.21](https://github.com/verbb/formie/releases/tag/1.3.21), thanks for reporting!
