### ISSUE TITLE
form.getCaptchas() is listed as a method but does not exists

### ISSUE THREAD

**Issue by harrison-drift** [verbb/formie#375]
**Description**
I'm trying to get the Honeypot captcha from a form into a custom integration and noticed that `form.getCapthcas()` is listed in the docs as a method, but it's not actually present.

### Form settings

**Additional info**
- Plugin version: 1.3
- Craft version: 3.6.4
- Multi-site: No

**Comment by engram-design** [comment]
Sorry about that, this existed in some early versions before our big integrations refactor. You can use the following as alternative:

`{% set captchas = craft.formie.getPlugin().getIntegrations().getAllEnabledCaptchasForForm(form) %}`
