### ISSUE TITLE
Add form name as field mapping option

### ISSUE THREAD

**Issue by Mosnar** [verbb/formie#376]
**What are you trying to do?**

We want to apply tags in Mailchimp for the form that was filled out by a user; however, the only way to do this currently is to make a hidden field with the tag name. The issue here is that then notifications are sent with that tag field unless we explicitly define all of the fields to include in the notification, which is tedious.

**What's your proposed solution?**
Ideally, there'd be either a "Form Name" option or better yet, a Twig object template option so we can do something like: `{object.form.name}` (Object being the submission element)

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.21",
  "...": "..."
}
```

Then run `composer update`.

Would it also be helpful to have a setting in hidden fields for whether to output it automatically in email notifications? I was also going to introduce a "All Visible Form Fields" to sit alongside "All Form Fields" and "All Non Empty Fields", that would also exclude all hidden fields, and soon, all conditionally hidden fields. Although maybe it might be handy to have both options 😄

**Comment by Mosnar** [comment]
Awesome, thanks! I do think that would also be helpful, especially if makes sense to add given your current road-map.

**Comment by engram-design** [comment]
Added those two settings in the `dev-craft-3` branch as well.

**Comment by engram-design** [comment]
Added in [1.3.22](https://github.com/verbb/formie/releases/tag/1.3.22)
