### ISSUE TITLE
Provide a method for updating all next/previous buttons for an entire form

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#38]

**Comment by engram-design** [comment]
Keen to get your thoughts on how you were thinking this to look/work @jaydensmith

**Comment by jaydensmith** [comment]
@engram-design maybe when updating buttons there's an option "apply to all pages".
Or a form/plugin-wide setting?

**Comment by engram-design** [comment]
@jaydensmith The "Apply to all pages" sounds good!

**Comment by engram-design** [comment]
Going to shelve this unless there's further demand for this. It gets tricky when there are multiple buttons, and trying to figure out which one to update.

For example, "Update All" on the second page, where there are 2 buttons, what happens to the first and last page?
