### ISSUE TITLE
[FR]: Add relationships in form setup, not as a custom field.

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#380]
**What are you trying to do?**

Basically this: https://docs.solspace.com/craft/freeform/v3/overview/relations.html#overview

We're building a job board with Freeform for a client and applicants apply for jobs. In the application form submission we link the application to the job entry.

This could be achieved with a entries field but that would be displayed to users. We could hide the entries field but that would still allow the user to post if they knew the form input name.

Ideally the relationship data would be hashed as a hidden field and submitted / verified.

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0)

**Comment by leevigraham** [comment]
Perfect timing… just started on a new Formie project that needs this :)
