### ISSUE TITLE
Docs: Example for setting Field Settings needs clarification?

### ISSUE THREAD

**Issue by robzor** [verbb/formie#389]
**What are you trying to do?**
Modify a field's content before rendering the form. (in this case a hidden field). 

_note: I realise I need to use the populateFormValues function but this was before I found that out, and thought it might be helpful to log_

I think there is something missing from the documentation here: https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields#override-field-settings 

Using this example, I am getting this error:
`Too few arguments to function verbb\formie\elements\Form::setFieldSettings(), 1 passed in /vendor/twig/twig/src/Extension/CoreExtension.php on line 1507 and exactly 2 expected`

**What's your proposed solution?**
Update the docs, or clarify for stupid people like me :)

**Additional context**

![CleanShot 2021-03-08 at 11 17 20](https://user-images.githubusercontent.com/704032/110314528-df9e1780-7fff-11eb-8064-502c341028f8.png)

**Comment by engram-design** [comment]
Sorry about that, just updated the docs to show the correct syntax:

```
{% do form.setFieldSettings('plainText', {
    {# Override the name (label) for the field #}
    name: 'Overridden Label',
}) %}
```

**Comment by robzor** [comment]
No problem, just wanted to add that I'm loving the plugin! Great work :)

**Comment by engram-design** [comment]
Great to hear! Appreciate you taking the time to log this issue as well.
