### ISSUE TITLE
Using global settings set via environmental vars causes notification test to fail

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#390]
**Description**
The Notification > Advanced tab allows you to select _System Email_ and _System Reply-To_ as values for the 'From Email' and 'Reply-To' fields, but when these are set by environmental variables formie isn't evaluating them and the preview test emails fail.

![image](https://user-images.githubusercontent.com/599005/110393377-4dfddb00-80cf-11eb-9bc2-ede97cd48de5.png)
![image](https://user-images.githubusercontent.com/599005/110393394-57874300-80cf-11eb-8792-5da39ca35789.png)

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.3.18
- Craft version: Craft Pro 3.5.19.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [1.3.22](https://github.com/verbb/formie/releases/tag/1.3.22)
