### ISSUE TITLE
Name prefix addition

### ISSUE THREAD

**Issue by mark-adigital** [verbb/formie#391]
Hi - we've had a request to add 'Mx' as an option for the name prefix/title. I've looked into this and it appears to be set within the code, so either a simple addition of this option or possibly a way to manage these within the CMS (though I appreciate that would be a bigger job) would be really helpful. Thanks!

**Comment by engram-design** [comment]
Added an event to modify these options for the next version. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.22",
  "...": "..."
}
```

Then run `composer update`. Refer to [docs](https://verbb.io/craft-plugins/formie/docs/developers/events#the-modifyPrefixOptions-event).

**Comment by engram-design** [comment]
I should also mention I've added `Mx.` to the default list anyway, so you might not need the event after all.

**Comment by mark-adigital** [comment]
That's great, thanks @engram-design !

**Comment by engram-design** [comment]
Added in [1.3.23](https://github.com/verbb/formie/releases/tag/1.3.23)
