### ISSUE TITLE
Javascript rendering in wrong place

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#392]
**Description**
Suddenly there is a <script> tag rendering at the end of my form. It's something setting the value of `__JSCHK_`?
I can see it in other websites that it is rendered in the footer of the page (as instructed by the form's template settings) just above Formie translations. But suddenly when updating to 1.3.22 it gets rendered within the form.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 13.22
- Craft version: 3.6.10
- Multi-site: Yes

**Comment by engram-design** [comment]
Related to https://github.com/verbb/formie/issues/355 where the Javascript captcha now has an inline script to handle the captcha, when the form's HTML is being cached, the unique ID won't match between the script and the JS to update the value.

I'll see what I can do to improve this, if it's an issue for you?

**Comment by TomDeSmet** [comment]
It kind of is because I get console errors thrown by Vue who absolutely doesn’t like any script tags within its template tags. And as all of our sites are encapsulated within a mounted vue instance, those pop up everywhere now. 

I don’t think it’s a good idea to promote caching forms anyway? It’s kind of bound to go wrong somewhere. I think a better solution for #355 would be to actually implement the cache tag where needed and leave out the form?

**Comment by engram-design** [comment]
Ah, good point. As far as I know, it's a warning (although shown as an error), which is frustrating, but should effect functionality. Still, I know it needs to be fixed up.

I don't think I can discourage people from caching their forms, as any static cached sites are going to run into this issue. I'll see what I can do about this.

**Comment by engram-design** [comment]
Fixed in [1.3.24](https://github.com/verbb/formie/releases/tag/1.3.24)
