### ISSUE TITLE
Ability to re-send notifications from Submissions Edit screen.

### ISSUE THREAD

**Issue by bryantAXS** [verbb/formie#398]
**What are you trying to do?**
The ability to re-send notifications from the Submissions Edit screen.

**What's your proposed solution?**
On the Submissions Edit screen there could be a button allowing you to re-send notification. Additionally, there could be a "Resend" button on the Submissions listing page, similar to the one that's on the Sent Notifications page.

**Additional context**
We've run into issues recently with Email Notifications not being sent to the user, and having the ability to resend them for data that was successfully submitted would be very helpful. Both in debugging issues but also being able to "save face" a little and simply resend the notification instead of send over screen shots or copy + paste email content.

**Comment by engram-design** [comment]
Yep, on our list!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
