### ISSUE TITLE
Email Notification for Spam Submissions

### ISSUE THREAD

**Issue by bryantAXS** [verbb/formie#400]
**What are you trying to do?**
Being able to get notifications even for Spam submissions.

**What's your proposed solution?**
Allowing an admin to specify an email address for Spam-flagged notification to be sent. Ideally also sending over the form data so the email allows us to identify if it contains valid data or not.

**Additional context**
We've had issues recently for submissions that incorrect got flagged as Spam, which doesn't send out a notification. It would be nice to be able to send these spam flagged submissions over to a different email address for monitoring.

**Comment by shoored** [comment]
Adding to this, since I dont need this exact feature, it would be nice if when marking a spam message as non-spam, notifications do get send out again. If that makes sense.

Maybe this has some overlap?

**Comment by engram-design** [comment]
@shoored Slightly related, and on the todo list also related to https://github.com/verbb/formie/issues/398

**Comment by shoored** [comment]
@engram-design Ah sorry didnt see that one. That's really nice, thanks!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
