### ISSUE TITLE
Include querystring in form redirects

### ISSUE THREAD

**Issue by russback** [verbb/formie#404]
**What are you trying to do?**
I have a form that populates a hidden field with the value of a `utm_campaign` param in the URL, which works great.

The form redirects to an Entry on submission, but the querystring is lost, so if you want to do anything with `utm_campaign` for lead attribution purposes, you need to cookie it to retrieve it on the next page.

If Formie could include the querystring on redirect, that would be great.

**What's your proposed solution?**
Plugin version: 1.3.23
Craft version: 3.6.10
Multi-site: Yes

**Comment by engram-design** [comment]
I suppose this needs to be configurable, as some people might want this, others not.

You can handle this yourself at the moment by setting the redirect URL to include the param from the form. As you mention you're redirecting to an entry, not a URL, you'll probably need to alter this in your templates:

```
{% do form.setSettings({
    redirectUrl: form.getRedirectUrl() ~ '?utm_campaign={utmCampaign}',
}) %}
```

Where `utmCampaign` is the handle for the field in your form. If you were redirecting to a URL, you could add that directly into the "Redirect URL" value in the form settings.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
