### ISSUE TITLE
Microsoft CRM-integration

### ISSUE THREAD

**Issue by nitech** [verbb/formie#409]
Formie looks great. I was about to pick one of the other well known form plugins, when I did a little research and found your blog entry where you explain why you went about creating a new form plugin. 

Well done. 

We use Microsoft CRM. It would be nice if you could create a integration to that platform. Pretty please <3.

Best regards,
Simon

**Comment by engram-design** [comment]
Never heard of it until now. Just to confirm, it's called "Dynamics CRM/Dynamics 365", and I'll add it to our list.

**Comment by nitech** [comment]
Yup, that’s the correct app.

It’s a massively used system.

Thanks!

**Comment by bryantAXS** [comment]
We have a client who uses Dynamics as well. Would be a big win to have this included!

**Comment by BrandKits** [comment]
I have a group of businesses in Melbourne who also use Microsoft Dynamics extensively. The Dynamics Marketing [embedded forms tool](https://docs.microsoft.com/en-gb/dynamics365/marketing/embed-forms) is clunky, would love to use Formie instead to send data directly into their CRM.

**Comment by aarmitage** [comment]
+1 here - a couple of enterprise clients we have struggle with the existing middleware on pushing submissions into Dynamics.

**Comment by samuelbirch** [comment]
+1 here too. 
@engram-design I see you added the beta label recently, does that mean its in the works? - and if so do you have an eta on it?

**Comment by engram-design** [comment]
You're more than welcome to try the 1.5.0 beta, but do note that it's stable-ish (we're actively working on it), so things might break. I'd recommend installing it on a new install just for testing.

1.5.0 will be available by the end of the year, but no strict ETA. Anything marked as `beta` in the [1.5.0 milestone](https://github.com/verbb/formie/milestone/7) is available on the `feature/next` branch.

`composer require verbb/formie:dev-feature/next`.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
