### ISSUE TITLE
alertEmails config example

### ISSUE THREAD

**Issue by nickcobley** [verbb/formie#411]
In the Getting Started > Configuration documentation, here https://github.com/verbb/formie/blob/84b38683d61ff5d7ca1345da30f8ef3dfe82aab5/docs/get-started/configuration.md

You note the alertEmails config setting, however the example here only shows the name of the setting, not the format of the array.

I would suggest putting a note in the docs here showing the exact format of this setting, given it's not the easiest to test either.

**Comment by engram-design** [comment]
Updated the docs to clarify https://verbb.io/craft-plugins/formie/docs/get-started/configuration#alerts-configuration
