### ISSUE TITLE
Hide fields in the form builder

### ISSUE THREAD

**Issue by SanboKyo** [verbb/formie#413]
I would need the ability to hide fields in the form builder (like in Wheelform). 

Is it possible? Did I miss that? Or is there a workaround?

**Comment by engram-design** [comment]
I'm not familiar with Wheelform sorry, so you might have to fill me in on the details. There's no way to hide fields in the form builder, in the control panel, otherwise there would be no way to edit the fields.

As for conditional handling on the front-end, it's coming in 1.4.0.

**Comment by SanboKyo** [comment]
I want the users to be able to use only certain fields, therefore the fields should be hidden.

You can disable certain fields that should be hidden in the settings in Wheelform.

![Bildschirmfoto 2021-03-30 um 15 08 42](https://user-images.githubusercontent.com/26556339/112994896-fea94880-916a-11eb-8604-933584efcf23.jpg)

**Comment by engram-design** [comment]
Ah, I see! Good idea. The only way to handle this at the moment it to use the `registerFields ` event - https://verbb.io/craft-plugins/formie/docs/developers/events#the-registerFields-event - to modify the available fields.

**Comment by SanboKyo** [comment]
Thanks for the tip and that would be great if that feature is included in the 1.4.x milestone - the sooner the better. ; )

**Comment by okolvik-avento** [comment]
Just in case someone else comes over this issue.
Using registerFields is not possible. getRegisteredFieldGroups uses ArrayHelper:remove to filter out the fields that go in the field groups inside the cms. ArrayHelper:remove returns null by default if the key is not found, resulting in a field array that looks like [ null, SingleLineText, null] (as an example) and there is no null check or filter before trying to run $class->getBaseFieldConfig().

**Comment by engram-design** [comment]
@okolvik-avento This is fixed in https://github.com/verbb/formie/commit/7baba2b0e9e89df02e6d3e1e2c81bfd367f03e8b by the way, for the next release.

**Comment by engram-design** [comment]
And some example code:

```
use verbb\formie\fields\formfields;

Event::on(Fields::class, Fields::EVENT_REGISTER_FIELDS, function(RegisterFieldsEvent $event) {
    $excludedFields = [
        formfields\Address::class,
        formfields\Agree::class,
        // ...
    ];

    foreach ($event->fields as $key => $field) {
        if (in_array($field, $excludedFields)) {
            unset($event->fields[$key]);
        }
    }
 
    // Reset indexes
    $event->fields = array_values($event->fields);
});
```

**Comment by okolvik-avento** [comment]
Ah nice, i only checked the released code. Should have checked the repo too :D

**Comment by janhenckens** [comment]
Was about to create an issue for this, very nice to see it'll be available in the next release!

**Comment by engram-design** [comment]
Added in [1.4.2](https://github.com/verbb/formie/releases/tag/1.4.2)
