### ISSUE TITLE
Include active integrations in GraphQL settings

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#414]
**What are you trying to do?**
We're trying to use reCaptcha in a headless configuration. I've enabled the integration but there's nothing in the form settings retrieved via GraphQL tp indicate whether reCaptcha should be active.

**What's your proposed solution?**
How about an argument for `activeIntegrations` on the form query?

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.25",
  "...": "..."
}
```

Then run `composer update`.

```
{
    form (handle: "formName") {
        title
        handle
        settings {
            integrations {
                name
                handle
                enabled
                settings
            }
        }
    } 
}
```

**Comment by engram-design** [comment]
Added in [1.3.26](https://github.com/verbb/formie/releases/tag/1.3.26)

**Comment by daltonrooney** [comment]
This is working perfectly, thank you. Follow up question... is there any way to pass the `g-recaptcha-response` value via GraphQL? I don't see it in the explorer, and I get a `Unable to save submission` error without it.

Edit: please disregard! I submitted it as a post parameter and it works beautifully. 😀
