### ISSUE TITLE
Input attributes for name fields

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#417]
**What are you trying to do?**
I want to add input attributes to the individual fields of the "name" field type.

**What's your proposed solution?**
When you choose "Use multiple name fields", a list of individual fields appears. If I click on any of these fields I would like to see an option for "input attributes", in addition to the existing ones for label, placeholder and default value. Maybe also container attributes, too, just to keep things consistent with how most of the other fields behave.

**Additional context**
Although I normally use the multiple fields, I imagine others may not. And who knows, maybe one day I won't go for individual fields either. So if you could add "input attributes" to the parent field as well that would be great. It already has container attributes, just not input attributes.

**Comment by engram-design** [comment]
This was going to be tackled in 1.4.x, but will push this out, as there's a few things we need to consider. First a foremost, how the change in stored behaviour works.

For field that have sub-fields (Address, Name) which each have their own "General" options. In addition to this on the "Settings" options, this same mechanism is used, but as these are slightly more advanced settings, they're in a different area so as not to overwhelm novice users with things. Adding a third-layer (for attributes, handle and more) is inevitable, so we will likely revisit the UI for sub-fields entirely.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
