### ISSUE TITLE
Fatal errors in log files

### ISSUE THREAD

**Issue by shoored** [verbb/formie#418]
**Description**
In my Sentry issue logs I see this one pop-up quite a lot:

`Catchable Fatal Error: Object of class craft\fields\data\MultiOptionsFieldData could not be converted to string`

I don't get any errors while working with Formie. It seems to generate this error when submitting a form / creating the submission and previewing emails. 

Sorry this is so generic..

The error occurs in
`verbb/formie/src/helpers/Variables.php` on line 425
`$values["{$prefix}{$field->handle}"] = (string)$submissionValue;`

`verbb/formie/src/services/Submissions.php` on line 560
`$fieldValues[] = (string)$value;`

**Steps to reproduce**
1. Work with Formie
2. Encounter errors in logfiles

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No
- Custom Email Template: Yes for some notifications. Merely the HTML wrapper, no custom logic

**Additional info**
- Plugin version: 1.3.25
- Craft version: 3.5.19.1
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.3.26](https://github.com/verbb/formie/releases/tag/1.3.26)
