### ISSUE TITLE
Email notification test

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#421]
I have run into an issue with notification being sent #397 (I believe more issues is opened right now).
With no record in logs. Submission saved, but no notification send and listed in records.

These features woul be quite handy right now:
- to resend notifications for submissions
- test email notification would be very usefull

**Comment by engram-design** [comment]
You can already test an email notification through the Preview:

![image](https://user-images.githubusercontent.com/1221575/113460831-c3a65e00-9465-11eb-9ec2-418153450e96.png)

Resending a notification for a submission is definitely on the [roadmap](https://github.com/verbb/formie/issues/398).

**Comment by lexislav** [comment]
Yes, it’s down there - just need to scroll a bit.
Thanks
