### ISSUE TITLE
Integration with SugarCRM

### ISSUE THREAD

**Issue by mark-adigital** [verbb/formie#423]
Hey - we were wondering if integration with [SugarCRM](https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_9.0/Integration/Web_Services/REST_API/) could go on the list you have? It's not an urgent request as we can use forms directly into Sugar without using Formie in the shorter term, but be nice to have this flexibility eventually. Thanks.

**Comment by engram-design** [comment]
Sure, we'll add it to our list.

**Comment by engram-design** [comment]
FYI, same deal as Maximizer, apparently there is issues with their system, so a 1-2 week delay.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
