### ISSUE TITLE
Form Submission search not searching against most recent submissions

### ISSUE THREAD

**Issue by dhmax88** [verbb/formie#425]
When using the search bar on the submissions tab, I've noticed the most recent submissions are not being searched against.

**Steps to reproduce**
1. Go to submissions tab
2. Search using keywords found in a message field

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.26
- Craft version: 3.6.11.2
- Multi-site: No

**Comment by engram-design** [comment]
Hmmm, I can seemingly find submissions based on searching for content found in single-line, multi-line and a few other fields' values. Can you confirm what sort of field you're searching against?

In addition, can you look in your `searchindex` db table against the `elementId` value of a submission you'd expect to be returned in search, to ensure there are searchable content rows?

**Comment by dhmax88** [comment]
Looking in the searchindex table, the submission elements are nowhere to be seen... do I need to re-index? The field is a multi-line field (message).

**Comment by engram-design** [comment]
How old are these submissions? Editing a submission and hitting save should kick the search indexes into gear.

I've only just added console commands to resave and reindex submissions/forms in https://github.com/verbb/formie/commit/e284e39aa1e56f68a91042205255c34c4f510064

But I can confirm multi-line text should appear in the searchindex table 
![image](https://user-images.githubusercontent.com/1221575/114019217-784ede00-98b1-11eb-86d5-c4d2cecabae7.png)

**Comment by dhmax88** [comment]
Thanks Josh. I have dropped the updated Formie.php file into my vendor folder and run the command, it resaves all submissions but doesn't result in them being searchable again. 

I think the issue has been caused by the form being flooded with spam, and the Craft queue getting clogged up. If I go into an individual submission, change the email address (for instance) and save, it does then appear when searched for.

**Comment by engram-design** [comment]
Did you run `./craft resave/formie-submissions --update-search-index=1`?

How many jobs in your queue do you have? But glad re-saving works, you shouldn't need to change anything for it to update - at least in my testing.

You can also change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.26",
  "...": "..."
}
```

Then run `composer update` to get the update, instead of modifying your vendor files as well.

**Comment by dhmax88** [comment]
Ah, I didn't include the `--update-search-index=1` 

Thank you so much, that did the job!
