### ISSUE TITLE
Heading and HTML fields in submissons

### ISSUE THREAD

**Issue by SanboKyo** [verbb/formie#426]
Heading and HTML fields (and maybe some other) should not be in the submissions.

Headings and HTML fields will be shown with label and content in the control panel view and an empty column in the submission export (csv).

**Comment by engram-design** [comment]
Why shouldn't these field types be shown in the submission? It's often common for content editors to use headings to separate content, so it's useful to have them in the submission in the control panel. HTML fields are debatable, but I'm not looking to remove this as a breaking change.

**Comment by SanboKyo** [comment]
Okay, but maybe only label or content for headings in control panel? But an empty column in the csv is useless (as the same static text in every row would be) - or am I mistaken?


![Bildschirmfoto 2021-04-07 um 15 17 49](https://user-images.githubusercontent.com/26556339/114005638-04381a00-9860-11eb-8fd2-5f2a845d02be.jpg)

**Comment by engram-design** [comment]
Yep, the label double up should be sorted in https://github.com/verbb/formie/commit/6088b84879dad765cb72901bf765636604a9c6a9 and export columns in https://github.com/verbb/formie/commit/6ac95c31e9ee0afc5ba63ac2af979ebee4705dc1

**Comment by engram-design** [comment]
Fixed in [1.3.27](https://github.com/verbb/formie/releases/tag/1.3.27)
