### ISSUE TITLE
Add a EVENT_BEFORE_SUBMISSION event

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#427]
**What are you trying to do?**
I'm trying to modify the post data on the server-side, but all the existing hooks are only run after validation has been completed...

**What's your proposed solution?**
Add a hook to SubmissionsController::actionSubmit() which is called as soon as it's established that there is a valid form i.e.

```
    /**
     * Submits and saves a form submission.
     *
     * @return Response|null
     * @throws Throwable
     */
    public function actionSubmit()
    {

        $this->requirePostRequest();
        $request = Craft::$app->getRequest();

        $goingBack = false;
        $currentPage = null;

        /* @var Settings $settings */
        $formieSettings = Formie::$plugin->getSettings();

        $handle = $request->getRequiredBodyParam('handle');

        Formie::log("Submission triggered for ${handle}.");

        /* @var Form $form */
        $form = Form::find()->handle($handle)->one();

        if (!$form) {
            throw new BadRequestHttpException("No form exists with the handle \"$handle\"");
        }
        
        $event = new SubmissionEvent([
            'form' => $form,
            'formieSettings' => $formieSettings,
            'request'=>$request
        ]);
        $this->trigger(self::EVENT_BEFORE_SUBMISSION, $event);

        //now feed the modified(?) $event->request back into $request.
        $request = $request->event;
     
```

**Additional context**

**Comment by engram-design** [comment]
You could use the inherited Yii `EVENT_BEFORE_VALIDATE`?

```
use verbb\formie\elements\Submission;
use yii\base\Event;

Event::on(Submission::class, Submission::EVENT_BEFORE_VALIDATE, function(Event $event) {
    $submission = $event->sender;
  
    $submission->addError('emailAddress', 'This did not validate');
    $event->isValid = false;
});
```

**Comment by engram-design** [comment]
@anchovy Any thoughts on using the above existing hook, or you'd prefer a new event in the controller regardless?

**Comment by anchovy** [comment]
Hi @engram-design I think I'd prefer a new event in the controller - this way it's defined in the docs and is only called for on formie validation events. If the `$event` also has the form handle & id attributes as well as the submission data about to be validated that would be great.

**Comment by engram-design** [comment]
Added [beforeSubmissionRequest](https://verbb.io/craft-plugins/formie/docs/developers/events#the-beforeSubmissionRequest-event) for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.3](https://github.com/verbb/formie/releases/tag/1.4.3)

**Comment by anchovy** [comment]
@engram-design I'm using this event on another project where I'm pre-validating a field. In the event, if I set a field to contain an error it's not getting passed through to the SubmissionsController?

```
Event::on(SubmissionsController::class, SubmissionsController::EVENT_BEFORE_SUBMISSION_REQUEST, function(SubmissionEvent $event) {

    $request = Craft::$app->getRequest();
    $postParams = $request->getBodyParams();
    
    // 0 - first page.
    $pageId = $request->getParam('pageIndex') ? $request->getParam('pageIndex') : 0;

    $fields = $postParams['fields'];
    $error = false;

    if($fields['mustEqualApple'] != 'Apple') $error = true;

    if($error)
    {
        $event->submission->addError($theirTokenKey, 'This is not a apple');
        dump($event->submission->getErrors());
    }

});
```
And add to the SubmissionsControoler at line 456:
```
        dump('Class '.__CLASS__.' line '. __LINE__);
        dump($submission->hasErrors());
        dump($submission->getErrors());
        die;
```


Testing I get 
![image](https://user-images.githubusercontent.com/599005/117238828-b4119f00-ae81-11eb-8b5b-b083088e20c5.png)

When I'd expect to get true and the same array with one error that I get from my controller?

**Comment by engram-design** [comment]
Right, so the problem here is that you're adding errors before the validation kicks in. From what I've found this just doesn't work, because the validation of the element kicks in to clear any errors you might've set before it's validation. I suppose this is expected, because you'd want to ensure you do a "fresh" validation test every time you want to validate a model.

You can see that's exactly what Yii does here: https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L347-L353 with `$this->clearErrors();` right before `beforeValidate()` is called.

There should be no reason you can't use the exact some code in `Submission::EVENT_BEFORE_VALIDATE` which works as it's called in `beforeValidate()`.

**Comment by engram-design** [comment]
This should also be fixed in https://github.com/verbb/formie/commit/9973a05579c62655dbb39e559c91d841ce34ee5a
