### ISSUE TITLE
JS Error for multiple forms on same page

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#43]
### Description
Two forms on one page: The first form is not submittable and throws a JS error:

```
formie-base-form.js?v=1596058850:1 Uncaught TypeError: Cannot read property 'submitMethod' of undefined
    at t.value (formie-base-form.js?v=1596058850:1)
    at formie-base-form.js?v=1596058850:1
value @ formie-base-form.js?v=1596058850:1
(anonymous) @ formie-base-form.js?v=1596058850:1
setTimeout (async)
(anonymous) @ formie-base-form.js?v=1596058850:1

```

### Steps to reproduce
1. Create two form on one page
2. Click submit button of first form

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Additional info
- Plugin version: 1.0.8

**Comment by engram-design** [comment]
Should be fixed in [1.0.9](https://github.com/verbb/formie/releases/tag/1.0.9) along with a few other same-page issues.

Thanks for all your bug-reporting by the way!

**Comment by mizmiz** [comment]
The first form does nothing at all now

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [1.0.9.1](https://github.com/verbb/formie/releases/tag/1.0.9.1)

**Comment by mizmiz** [comment]
Nope

**Comment by engram-design** [comment]
Both forms are ajax, and you're not using custom templates? Can you try clearing the Craft cache?

I would also try a `composer update` again, as I pushed a revision shortly after my response here. Depends how quick you were to update, you might have beat me to it.

**Comment by mizmiz** [comment]
Ah, I see. I was testing with a custom template. Seems to work fine now.

**Comment by engram-design** [comment]
Gotcha, there were some template changes you may need to add on your end https://github.com/verbb/formie/commit/e8c00672825b754fadf7e46b96112c7d708707d5#diff-0ccb56180dd6dfb1a85eb6fa7f0f3d7f

**Comment by mizmiz** [comment]
Yeah, that I missed
