### ISSUE TITLE
Integration with Maximizer CRM

### ISSUE THREAD

**Issue by mark-adigital** [verbb/formie#431]
This feels a lot like déjà vu, but we were hoping integration with [Maximizer CRM](https://www.maximizer.com/support/crm-api/) could also be added to your list? The project where we would need this is a few months off yet, so it's not an urgent requirement. Thanks.

**Comment by engram-design** [comment]
Added to our list!

**Comment by mark-adigital** [comment]
Hey, just wondered if there was any inkling as to when 1.5.0 may be released? That project where we needed to integrate with Maximizer has actually been and gone and fortunately we were able to integrate via MailChimp as a stopgap, but it would be good to be able to give the client some idea as to when direct integration might be possible if you have a timing in mind? Cheers

**Comment by engram-design** [comment]
I'm just waiting for Maximizer to get back to me with correct API details. I can't seem to connect with what they've provided.

1.5.0 will be available by the end of the year, but no strict ETA. Anything marked as `beta` in the [1.5.0 milestone](https://github.com/verbb/formie/milestone/7) is available on the `feature/next` branch.

**Comment by mark-adigital** [comment]
Ah, typical!

That's great - thanks for the update.

**Comment by engram-design** [comment]
@mark-adigital Wondering if you (or your client) has API access that might allow me to test? Ideally, it'd be a sandbox, or test account, rather than a live account (which I'd rather not touch). They've taken weeks and just getting radio silence from the API team. Would love to get this sorted.

**Comment by mark-adigital** [comment]
Sounds like a good idea @engram-design  I don't currently have access to the client's Maximizer account but of course would likely need that to get the live API keys eventually anyway so have just asked the client for that and will update this thread once I hear back.

**Comment by engram-design** [comment]
No problem, feel free to get in touch privately via `web at verbb.io` or `crawf` on Discord. Hopefully they'll get back to me soon.

**Comment by engram-design** [comment]
Happy to say finally got some action on this, so no need to get in touch, should be ready to go soon.

**Comment by mark-adigital** [comment]
Ah great, thanks for the update. Obviously one of those typical times where as soon as you asked it started to move on its own!

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
