### ISSUE TITLE
Trying to create a new EmailMarketing integration from docs

### ISSUE THREAD

**Issue by nickdunn** [verbb/formie#432]
I'm trying to write my own email marketing integration however I'm failing in getting just the basics working.

I've started with the example from https://verbb.io/craft-plugins/formie/docs/developers/custom-integration. This yielded an error:

    Declaration of modules\cswebsitemodule\AdestraEmailMarketing::getFormSettingsHtml(): string should be compatible with verbb\formie\base\EmailMarketing::getFormSettingsHtml($form): string

So I think the docs need updating to include the `$form` param.

I then have the most barebones class I can think of:

        <?php
        namespace modules\cswebsitemodule;

        use verbb\formie\base\EmailMarketing;
        use verbb\formie\elements\Form;
        use verbb\formie\elements\Submission;
        use verbb\formie\models\IntegrationCollection;
        use verbb\formie\models\IntegrationField;
        use verbb\formie\models\IntegrationFormSettings;

        use Craft;

        class AdestraEmailMarketing extends EmailMarketing
        {
            public static function displayName(): string
            {
                return Craft::t('formie', 'Adestra/MessageFocus');
            }

            public function getDescription(): string
            {
                return Craft::t('formie', 'This is an example email marketing integration.');
            }

            public function getSettingsHtml(): string
            {
                return "";
            }

            public function getFormSettingsHtml($form): string
            {
                return "";
            }

            public function fetchFormSettings()
            {
                $settings = [];
                return new IntegrationFormSettings($settings);
            }

            public function sendPayload(Submission $submission)
            {
                return true;
            }
        }

However when I go to add a new Email Marketing integration I get an error:

    yii\base\InvalidConfigException: The config passed into Component::createComponent() did not specify a class: {"listId":null,"optInField":null,"fieldMapping":null,"name":null,"handle":null,"type":null,"enabled":null,"sortOrder":null,"cache":[],"tokenId":null,"uid":null,"referrer":"","id":null,"dateCreated":null,"dateUpdated":null} in /var/www/craft/vendor/craftcms/cms/src/helpers/Component.php:96
    Stack trace:
    #0 /var/www/craft/vendor/verbb/formie/src/services/Integrations.php(461): craft\helpers\Component::createComponent(Object(modules\cswebsitemodule\AdestraEmailMarketing), 'verbb\\formie\\ba...')
    #1 /var/www/craft/vendor/verbb/formie/src/controllers/IntegrationSettingsController.php(249): verbb\formie\services\Integrations->createIntegration(Object(modules\cswebsitemodule\AdestraEmailMarketing))
    #2 /var/www/craft/vendor/verbb/formie/src/controllers/IntegrationSettingsController.php(134): verbb\formie\controllers\IntegrationSettingsController->_editIntegration(NULL, Object(verbb\formie\integrations\emailmarketing\ActiveCampaign), 'Email Marketing', 'emailMarketing')
    #3 [internal function]: verbb\formie\controllers\IntegrationSettingsController->actionEditEmailMarketing(NULL, NULL)
    #4 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
    #5 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
    #6 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-email-mark...', Array)
    #7 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-email-mark...', Array)
    #8 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('formie/integrat...', Array)
    #9 /var/www/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('formie/integrat...', Array)
    #10 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
    #11 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
    #12 /var/www/craft/web/index.php(22): yii\base\Application->run()
    #13 {main}

Any idea what I'm doing wrong?

**Comment by nickdunn** [comment]
Ok I think I solved it. When registering the integration I need to pass the namespace/path to my class not an instance of the class itself.

Docs:

    Event::on(Integrations::class, Integrations::EVENT_REGISTER_INTEGRATIONS, function(RegisterIntegrationsEvent $event) {
        // ...
        $event->emailMarketing[] = new ExampleEmailMarketing();
        // ...
    });

Working:

    Event::on(Integrations::class, Integrations::EVENT_REGISTER_INTEGRATIONS, function(RegisterIntegrationsEvent $event) {
        $event->emailMarketing[] = 'modules\cswebsitemodule\AdestraEmailMarketing';
    });

**Comment by nickdunn** [comment]
I'm hitting a few issues trying to add an integration via a module. Would it make more sense for me to add this directly to Formie and issue a pull request?

**Comment by engram-design** [comment]
Yep, sorry about that - just updated the docs to reflect the correct handling. What other issues are you hitting? 

As for a PR, depends on the changes you're making, if they're for an existing integration, or adding a new one?

**Comment by nickdunn** [comment]
Thanks :-)

My next issue was getting my own settings templates registered so that I can still use the same Formie macros. I haven't created Craft plugins or modules before so this new ground for me.

I'd like to create a new email marketing integration for Adestra (https://uplandsoftware.com/adestra/) which my client is using which follows a similar pattern to others in terms of API token, select a list etc. 

So maybe I should create it directly within Formie which reduces the overhead of also learning module development at the same time...

**Comment by engram-design** [comment]
Ah cool! I'd say continue going with your custom module, to get it all working, then more than welcome to send a PR, or even just post the class here. Otherwise, I can add it to our feature list to do (but no ETA).

So the settings template (when going to Formie > Settings > Email Marketing) are slightly easier than the form template (the template shown in the form when mapping fields), but in both cases, I'd certainly recommend looking at [existing examples](https://github.com/verbb/formie/tree/craft-3/src/templates/integrations/email-marketing) and copy from those.

**Comment by nickdunn** [comment]
Ok, I'll see how far I get! I had copied the Twig from the Mailchimp one that I'm using as a guide, but the problem I had was registering my own Twig template in my module, and making sure it had access to the same Formie macros. 

I started with this in my module:

        Event::on(View::class, View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS, function(RegisterTemplateRootsEvent $e) {
            $e->roots[$this->id] = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates';
        });

But wasn't then sure where to go, whether I need to register an alias/path to have them recognised; then how to reference this path in the `Craft::$app->getView()->renderTemplate(...)` call.

**Comment by engram-design** [comment]
Yep, so that should setup the template root of your module, to resolve to a `templates` directory. Then, you can use:

```
public function getSettingsHtml(): string
{
    return Craft::$app->getView()->renderTemplate('my-module-handle/_plugin-settings', [
        'integration' => $this,
    ]);
}

public function getFormSettingsHtml($form): string
{
    return Craft::$app->getView()->renderTemplate('my-module-handle/_form-settings', [
        'integration' => $this,
    ]);
}
```

Where you might have:

- `mymodulehandle`
    - `src`
        - `templates`
            - `_plugin-settings.html`
            - `_form-settings.html`

**Comment by nickdunn** [comment]
This is exactly the setup I had but it wasn't finding the template.

Module registered in my app:

        'modules' => [
            'cswebsitemodule' => [
                'class' => \modules\cswebsitemodule\CsWebsiteModule::class,
            ],
        ],
        'bootstrap' => ['cswebsitemodule'],

Module registering the template root:

        Event::on(View::class, View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS, function(RegisterTemplateRootsEvent $e) {
            $e->roots[$this->id] = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates';
        });

With this directory structure:

    cswebsitemodule
      src
        templates
          _plugin-settings.html

Then loading the template:

    public function getSettingsHtml(): string
    {
        return Craft::$app->getView()->renderTemplate("cswebsitemodule/_plugin-settings", [
            'integration' => $this,
        ]);
    }

With the error:

> Unable to find the template “cswebsitemodule/_plugin-settings”.

**Comment by nickdunn** [comment]
Ah! `View::EVENT_REGISTER_CP_TEMPLATE_ROOTS` not `View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS`.

Working.

Thanks for the pointers.

**Comment by nickdunn** [comment]
The last thing I haven't figured out to do is load my integration's SVG. The example in the doc suggests `return __DIR__ . '/assets/adestra.svg';` which obviously outputs the path on disk not a URL. I presume I need to set up some kind of Craft Asset but this is beyond me at the moment. Do you have any pointers?

EDIT: assets now registered following https://nystudio107.com/blog/enhancing-a-craft-cms-3-website-with-a-custom-module.

The working integration in case you want to pull it in as a supported platform:

```
<?php
namespace modules\cswebsitemodule;

use verbb\formie\base\Integration;
use verbb\formie\base\EmailMarketing;
use verbb\formie\elements\Form;
use verbb\formie\elements\Submission;
use verbb\formie\models\IntegrationCollection;
use verbb\formie\models\IntegrationField;
use verbb\formie\models\IntegrationFormSettings;

use Craft;

class AdestraEmailMarketing extends EmailMarketing
{
    public $apiKey;
    public $workspaceId;
    public $coreTableId;

    public static function displayName(): string
    {
        return Craft::t('formie', 'Adestra MessageFocus');
    }

    public function getDescription(): string
    {
        return Craft::t('formie', 'Sign up users to your Adestra lists.');
    }

    public function getIconUrl(): string
    {
        return __DIR__ . '/assets/adestra.svg';
    }

    public function defineRules(): array
    {
        $rules = parent::defineRules();

        $rules[] = [['apiKey'], 'required'];
        $rules[] = [['workspaceId'], 'required'];
        $rules[] = [['coreTableId'], 'required'];

        return $rules;
    }

    public function getSettingsHtml(): string
    {
        return Craft::$app->getView()->renderTemplate("cswebsitemodule/_plugin-settings", [
            'integration' => $this,
        ]);
    }

    public function getFormSettingsHtml($form): string
    {
        return Craft::$app->getView()->renderTemplate("cswebsitemodule/_form-settings", [
            'integration' => $this,
        ]);
    }

    public function fetchFormSettings()
    {
        $settings = [];

        try {
            $response = $this->request('GET', '/core_tables/' . Craft::parseEnv($this->coreTableId));
            $fields = $response['table_columns'] ?? [];

            $response = $this->request('GET', 'lists', [
                'query' => [
                    'search:workspace_id' => Craft::parseEnv($this->workspaceId),
                    'search:table_id' => Craft::parseEnv($this->coreTableId),
                    'paging:page_size' => 250,
                ],
            ]);
            $lists = $response['lists'] ?? [];

            $listFields = [];

            foreach ($fields as $key => $field) {
                $listFields[] = new IntegrationField([
                    'handle' => $field['name'],
                    'name' => $field['name'],
                    'type' => IntegrationField::TYPE_STRING
                ]);
            }

            foreach ($lists as $list) {
                $settings['lists'][] = new IntegrationCollection([
                    'id' => $list['id'],
                    'name' => $list['name'] . ' (' . $list['id'] . ')',
                    'fields' => $listFields,
                ]);
            }
        } catch (\Throwable $e) {
            Integration::apiError($this, $e);
        }

        return new IntegrationFormSettings($settings);
    }

    public function sendPayload(Submission $submission): bool
    {
        try {
            $fieldValues = $this->getFieldMappingValues($submission, $this->fieldMapping);
            $contactData = [];

            foreach ($fieldValues as $name => $value) {
                $contactData[Craft::parseEnv($this->coreTableId) . '.' . $name] = $value;
            }

            $payload = [
                'table_id' => (int)Craft::parseEnv($this->coreTableId),
                'dedupe_field' => 'email',
                'options' => [
                    'list_id' => (int)$this->listId
                ],
                'contact_data' => $contactData
            ];

            $response = $this->deliverPayload($submission, 'contacts', $payload, 'POST');

            if ($response === false) {
                return true;
            }
        } catch (\Throwable $e) {
            Integration::apiError($this, $e);

            return false;
        }

        return true;
    }

    public function fetchConnection(): bool
    {
        try {
            $response = $this->request('GET', '/workspaces/' . Craft::parseEnv($this->workspaceId));
            $workspaceName = $response['name'] ?? '';

            if (!$workspaceName) {
                Integration::error($this, 'Unable to find “{name}” in response.', true);
                return false;
            }
        } catch (\Throwable $e) {
            Integration::apiError($this, $e);

            return false;
        }

        return true;
    }

    protected function getClient()
    {
        if ($this->_client) {
            return $this->_client;
        }

        return $this->_client = Craft::createGuzzleClient([
            'base_uri' => 'https://app.adestra.com/api/rest/1/',
            'headers' => [
                'Authorization' => 'TOKEN ' . Craft::parseEnv($this->apiKey)
            ]
        ]);
    }
}
```

```
{% import '_includes/forms' as forms %}

{% set handle = integration.handle %}
{% set formSettings = integration.getFormSettings().getSettings() %}
{% set listId = form.settings.integrations[handle].listId ?? '' %}

<field-select
    label="{{ 'Opt-In Field' | t('formie') }}"
    instructions="{{ 'Choose a field to opt-in to {name}. For example, you might only wish to subscribe users if they provide a value for a field of your choice - commonly, an Agree field.' | t('formie', { name: integration.displayName() }) }}"
    id="opt-in-field"
    name="optInField"
    :value="get(form, 'settings.integrations.{{ handle }}.optInField')"
></field-select>

<integration-form-settings handle="{{ handle }}" :form-settings="{{ formSettings | json_encode }}" source="{{ listId }}" inline-template>
    <div>
        <div class="field">
            <div class="heading">
                <label id="sourceId-label" for="sourceId" class="required">{{ 'List' | t('formie') }}</label>

                <div class="instructions">
                    <p>{{ 'Select your {name} list to create contacts on.' | t('formie', { name: integration.displayName() }) }}</p>
                </div>
            </div>

            <div class="input ltr">
                <div class="select">
                    <select v-model="sourceId" name="listId" required>
                        <option value="">{{ 'Select an option' | t('formie') }}</option>

                        <option v-for="(option, index) in get(settings, 'lists')" :key="index" :value="option.id">${ option.name }</option>
                    </select>
                </div>

                <button class="btn fui-btn-transparent" :class="{ 'fui-loading fui-loading-sm': loading }" data-icon="refresh" @click.prevent="refresh"></button>
            </div>

            <ul v-if="!isEmpty(get(form, 'settings.integrations.{{ handle }}.errors.listId'))" class="errors" v-cloak>
                <li v-for="(error, index) in get(form, 'settings.integrations.{{ handle }}.errors.listId')" :key="index">
                    ${ error }
                </li>
            </ul>
        </div>

        <div v-if="error" class="error" style="margin-top: 10px;" v-cloak>
            <span data-icon="alert"></span>
            <span v-html="errorMessage"></span>
        </div>

        <integration-field-mapping
            label="{{ 'Field Mapping' | t('formie') }}"
            instructions="{{ 'Choose how your form fields should map to your {name} fields.' | t('formie', { name: integration.displayName() }) }}"
            id="field-mapping"
            name-label="{{ integration.displayName() }}"
            name="fieldMapping"
            :value="get(form, 'settings.integrations.{{ handle }}.fieldMapping')"
            :rows="getSourceFields('lists')"
        ></integration-field-mapping>

        <ul v-if="!isEmpty(get(form, 'settings.integrations.{{ handle }}.errors.fieldMapping'))" class="errors" v-cloak>
            <li v-for="(error, index) in get(form, 'settings.integrations.{{ handle }}.errors.fieldMapping')" :key="index">
                ${ error }
            </li>
        </ul>
    </div>
</integration-form-settings>
```

```
{% import '_includes/forms' as forms %}
{% import 'verbb-base/_macros' as macros %}

{% set instructions %}
### Step 1. Connect to the {name} API
1. Find your Adestra API key and copy into the **API Key** field below.
1. Find your Workspace ID and copy into the **Workspace ID** field below.
1. Find your Core Table ID and copy into the **Core Table ID** field below.

### Step 2. Test Connection
1. Save this integration.
1. Click on the **Refresh** button in the right-hand sidebar.
{% endset %}

<div class="fui-settings-block">
  {{ instructions | t('formie', { name: integration.displayName() }) | md }}
</div>

{{ forms.autosuggestField({
    label: 'API Key' | t('formie'),
    instructions: 'Enter your {name} API key here.' | t('formie', { name: integration.displayName() }),
    name: 'apiKey',
    required: true,
    suggestEnvVars: true,
    value: integration.settings.apiKey ?? '',
    warning: macros.configWarning('apiKey', 'formie'),
    errors: integration.getErrors('apiKey'),
}) }}

{{ forms.autosuggestField({
    label: 'Workspace ID' | t('formie'),
    instructions: 'Enter your {name} Workspace ID here.' | t('formie', { name: integration.displayName() }),
    name: 'workspaceId',
    required: true,
    suggestEnvVars: true,
    value: integration.settings.workspaceId ?? '',
    warning: macros.configWarning('workspaceId', 'formie'),
    errors: integration.getErrors('workspaceId'),
}) }}

{{ forms.autosuggestField({
    label: 'Core Table ID' | t('formie'),
    instructions: 'Enter your {name} Core Table ID here.' | t('formie', { name: integration.displayName() }),
    name: 'coreTableId',
    required: true,
    suggestEnvVars: true,
    value: integration.settings.coreTableId ?? '',
    warning: macros.configWarning('coreTableId', 'formie'),
    errors: integration.getErrors('coreTableId'),
}) }}
```

**Comment by engram-design** [comment]
Thanks for posting that, amazing! I'll update the docs to reflect the use of assets for icons. You don't need to use an asset bundle, but just provide a path to the icon within your module.

```
return Craft::$app->getAssetManager()->getPublishedUrl("@modules/mymodule/resources/icon.svg", true);
```

I'll keep this open so I can add this to core!
