### ISSUE TITLE
Add systemName to variables list

### ISSUE THREAD

**Issue by janhenckens** [verbb/formie#433]
**What are you trying to do?**
Use the overall system name in email copy

**What's your proposed solution?**
Adding `systemName` to the variables list in rich text & subject fields.

**Additional context**
Since 99% of the sites we make are multilingual, we like to label the site name with the language (eg: Project Site FR), while the system name would just be "Project Site". Having the language label in email notifications isn't really pretty so systemName would work better there.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.27",
  "...": "..."
}
```

Then run `composer update`.

**Comment by janhenckens** [comment]
@engram-design awesome, thanks!

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0)
