### ISSUE TITLE
Email marketing list name is not remembered on refresh

### ISSUE THREAD

**Issue by nickdunn** [verbb/formie#434]
Most of the mail marketing integrations expose a "List" field. When you choose from this list and save, then return to the integration at a later date, the chosen list isn't pre-selected in the dropdown, and therefore the Field Mapping table underneath it is blank.

This has the effect of the making the user thing the config hasn't been saved correctly.

**Comment by nickdunn** [comment]
Inside `_form-settings.html` for a given integration, it seems that:

    {% set listId = form.settings.integrations[handle].listId ?? '' %}

Always defaults to `''` because `form` does not exist.

**Comment by nickdunn** [comment]
Ignore. I wasn't passing form from my class:

```
    public function getFormSettingsHtml($form): string
    {
        return Craft::$app->getView()->renderTemplate("cswebsitemodule/_form-settings", [
            'integration' => $this,
            'form' => $form <------
        ]);
    }
```

**Comment by engram-design** [comment]
Updated the docs FYI
