### ISSUE TITLE
Initial install migration fails

### ISSUE THREAD

**Issue by rickmerkelbach** [verbb/formie#435]
**Description**
Installing Formie 1.4.0 from scratch fails due to some issues with the install migration.

It seems a few issues slipped in during the last merge. Craft throws an `ParseError: syntax error, unexpected 'public' (T_PUBLIC), expecting end of file` error when trying to install through the Plugin Store, caused by an extra `}` in src/migrations/Install.php on [line 373](https://github.com/verbb/formie/blob/0dacc65a49c0558a29e64188687fe5bf18756e3f/src/migrations/Install.php#L373). 

After removing the extra `}` it fails because it tries to create the "formie_submissions", "formie_syncs" and "formie_syncfields" twice. Duplicate submission table creation on [line 300](https://github.com/verbb/formie/blob/0dacc65a49c0558a29e64188687fe5bf18756e3f/src/migrations/Install.php#L300). After fixing these issues it installs as usual.

**Steps to reproduce**
1. Install Formie for the first time

**Additional info**
- Plugin version: 1.4.0
- Craft version: 3.6.12
- Multi-site: No

**Comment by nathansnelgrove** [comment]
Can also confirm the same problem; downgrading the plugin immediately fixed it.

**Comment by engram-design** [comment]
Sorry about that, a bad merge on my part. Fixed in [1.4.0.1](https://github.com/verbb/formie/releases/tag/1.4.0.1)
