### ISSUE TITLE
Ability to View Spam Reasons and IP Address on Index

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/formie#436]
It would be great to be able to see the spam reason as well as the IP address on the submissions index view. 

Right now it's only limited to the fields we can create.

![Screen Shot 2021-04-20 at 8 40 33 PM](https://user-images.githubusercontent.com/3707869/115484886-30b54400-a219-11eb-971f-60ad2d0cb982.png)

Additionally, I'm not sure if this is a Craft issue but when you're filtering by Spam Only view, it doesn't take the back button into context which is annoying. if I'm digging into a submission for more info or to delete it, I get dumped back to All view. Would be nicer to see the  current view "context"  being "sticky" until you change it.

**Comment by engram-design** [comment]
Added those columns in https://github.com/verbb/formie/commit/b44a8fda965482d64021c2aaf64e2da51266ffd6

I'll see what I can do about the persistent status. I know that Craft itself doesn't seem to do it on its own element indexes with status/draft, but it's bugged me too!

Edit: I see you've added this here - https://github.com/craftcms/cms/issues/7815

**Comment by engram-design** [comment]
Added in [1.4.1](https://github.com/verbb/formie/releases/tag/1.4.1)
