### ISSUE TITLE
Saving submissions in the CP throws an exeption: 

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#437]
**Description**

Saving a submission in the CP throws an exception

**Steps to reproduce**
1. Save an existing submission in the CP

### Form settings
Please pick from the options below.

- Multi-page form: Yes

**Additional info**
- Plugin version: 1.4.0.1
- Craft version: 3.6.12
- Multi-site: No

**Additional context**

![Screen Shot 2021-04-22 at 12 32 30-fullpage](https://user-images.githubusercontent.com/25124/115490051-a87a8180-a2a0-11eb-850d-fc26149cdd04.png)

![image](https://user-images.githubusercontent.com/25124/115490071-b0d2bc80-a2a0-11eb-8cd2-62e39d19c957.png)

**Comment by engram-design** [comment]
Fixed in [1.4.1](https://github.com/verbb/formie/releases/tag/1.4.1)
