### ISSUE TITLE
Form validation broken… field layout different in form and submission

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#438]
**Description**

Updating to 1.4.0.1 cause my form validation to start behaving weirdly. It looks like the wrong fieldLayout is being loaded for the submission which results in a mis match of validation / post data.

The screenshot shows the submission breakpoint evaluation…

* `$this` is the submission
* The submission fieldLayout->id is 328
* The form fieldLayoutId is 326

![image](https://user-images.githubusercontent.com/25124/115492885-065d9800-a2a6-11eb-9fae-d1d89cad0aa3.png)

![image](https://user-images.githubusercontent.com/25124/115492992-3efd7180-a2a6-11eb-920b-bc4e5f6aaa03.png)

**Steps to reproduce**
1. not sure how this happened :)

### Form settings
Please pick from the options below.

- Custom Form Templates:  No

**Additional info**
- Plugin version: 1.4.0.1
- Craft version: 3.6.12
- Multi-site: No

**Comment by leevigraham** [comment]
Additionally once removing the validation the form submission no longer saves: 
![image](https://user-images.githubusercontent.com/25124/115493680-8801f580-a2a7-11eb-8577-a41a3ef44b27.png)

**Comment by leevigraham** [comment]
Ok nailed this one down…

I was accessing the form in a behaviour before it was defined:

![image](https://user-images.githubusercontent.com/25124/115494415-f2676580-a2a8-11eb-8d7a-430866a605e5.png)

This triggered the `getForm()` method which assumes the submission has a `_formId`. In my case it didn't because it was being constructed. 

The `getForm()` method still tries to load a form but without an ID loads the first available form.

![image](https://user-images.githubusercontent.com/25124/115494378-de236880-a2a8-11eb-999c-8de1925c8645.png)

Maybe the `getForm` method should check for an ID before doing the query… alternatively require a form object during construction.

**Comment by engram-design** [comment]
Added handling for this in [1.4.1](https://github.com/verbb/formie/releases/tag/1.4.1)
