### ISSUE TITLE
Provide a Mailchimp integration setting to set the interest category for a submission

### ISSUE THREAD

**Issue by nilsenpaul** [verbb/formie#439]
**What are you trying to do?**
Whenever my site's visitors subscribe to a mailing list through one of the Formie forms (with Mailchimp integration), I'd like to be able to define a Mailchimp interest category (group) on a 'per form' basis. See https://mailchimp.com/developer/marketing/api/interest-categories/ for more info on getting the interest categories for a list/audience.

**What's your proposed solution?**
Please add a dropdown for this, and communicate the prefered interest category to the Mailchimp API when submitting the data.

**Comment by engram-design** [comment]
Added in [1.4.2](https://github.com/verbb/formie/releases/tag/1.4.2). Please note you'll need to provide the interest category IDs for this to properly work. Supplying the name of the group (like "Donations") won't work. This is because it's not unique enough across a Mailchimp account.
