### ISSUE TITLE
User Registration - Adding User Group

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#440]
**Description**
When using the User Integration, with the "Update Users" light switch enabled and a different user group from their current one is specified, it will remove them from their current group and assign them to the new one. It would be good if the specified user group in this form would be appended to their permissions. Or at least have an option here to specify that preference.

So if they are in group A, and then complete the form which has group B specified in the settings, then they end up being in group B and not Groups A + B. 

I have a quite urgent use case where I was hoping to use formie to add a user to another group, but retain their existing group too by simply allowing them to complete a form.

Thanks!

**Additional info**
- Plugin version: 1.4.0.1
- Craft version: 3.6.12
- Multi-site: Yes or No

**Comment by mark-chief** [comment]
Do you think this will be possible? Different client to what i have been bugging you with today :) #legend

**Comment by engram-design** [comment]
Yep, added to my list to address in the next release (or two)

**Comment by engram-design** [comment]
Added in [1.4.2](https://github.com/verbb/formie/releases/tag/1.4.2)
