### ISSUE TITLE
Freeform Migration Error

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#442]
**Description**
Attempting to migrate a large form from Freeform using the handy built in tool. I am getting the below error.

<img width="1797" alt="Screenshot 2021-04-22 at 17 51 32" src="https://user-images.githubusercontent.com/18699249/115753963-a9401000-a393-11eb-9858-bc0f2d18c99f.png">

**Additional context**
Formie: 1.4.1
Craft 3.6.11

**Comment by engram-design** [comment]
Are you on MySQL or Postgres? It looks like the data for a submission is exceeding the maximum row size for the `MulticarPreparerBookingForm1` form. Specifically, the field with a handle `text45`.

Can you provide any information about the settings for this field in Freeform?

Can you also look in your content table `fmc_multicarpreparerbookingform1_2` to see if there are any submissions successfully imported? It may come down to just one submission causing an issue.

**Comment by mark-chief** [comment]
Hey Josh,

MySQL.

`text45` is a really simple text field with no special settings, see below.

<img width="347" alt="Screenshot 2021-04-23 at 08 49 32" src="https://user-images.githubusercontent.com/18699249/115838295-6e7cbd00-a411-11eb-96ef-db3886fa5674.png">

<img width="944" alt="Screenshot 2021-04-23 at 08 55 03" src="https://user-images.githubusercontent.com/18699249/115838470-9d932e80-a411-11eb-8c04-9c1204a158c1.png">


There are no submissions in that form yet, so `fmc_multicarpreparerbookingform1_2` is completely empty.

**Comment by engram-design** [comment]
Hmmm. Would you be able to run the following query? I'm wondering if the text values for these values are longer than 255 characters, which sounds like they might be.

Can you run the following query:

```
SELECT field_140 FROM freeform_submissions;
```

I'm interested in the length of content for submissions.

Can you also report back the column info for this column `field_140` in the submissions table? It should be something like `VARCHAR` with a length of 100.

![image](https://user-images.githubusercontent.com/1221575/115862243-3f009b80-a477-11eb-8438-dd7c78999243.png)

**And finally** how many fields does this form have?

**Comment by mark-chief** [comment]
Screenshot of the SELECT query result:
<img width="470" alt="Screenshot 2021-04-23 at 12 04 21" src="https://user-images.githubusercontent.com/18699249/115862490-21f2ab00-a42c-11eb-9ba2-ceec306cba72.png">

Column info for field_140:
<img width="1388" alt="Screenshot 2021-04-23 at 12 06 05" src="https://user-images.githubusercontent.com/18699249/115862672-51091c80-a42c-11eb-95c6-6d93b010812e.png">

It has over 100-130+ fields. I've removed all rich text fields that were also breaking the migration as not supported.

**Comment by engram-design** [comment]
Ah, I would say your 100-130 fields is hitting the MySQL row limit (as the error points), which is similar to Craft itself. Basically, too many fields on a single form. Freeform has a similar limitation with this, although it's ~130 fields across the entire install.

Are any of the columns setup for `fmc_multicarpreparerbookingform1_2` - I know there's no rows, but just thought to see what types of column types there are. Too many TEXT/BLOB columns will really chew through the row limit.

I'm not sure how feasible trying some of these [suggestions](https://github.com/craftcms/cms/issues/2009#issuecomment-333394434) might be, but worth a shot.

**Comment by mark-chief** [comment]
Yes thats the issue I'm having with FF at the moment, client has maxed out the fields so i have tried to change from VARCHAR to TEXT as suggested by them but it's not working - so figured I'd give Formie a go as I have emailed you in the past and you reckoned at the time it would be fine.

It's a beast of a form tbh, they wont have another one this size.

Heres the columns types

<img width="377" alt="Screenshot 2021-04-23 at 12 32 17" src="https://user-images.githubusercontent.com/18699249/115865247-fd98cd80-a42f-11eb-933a-3d9a7f2d98a4.png">

**Comment by engram-design** [comment]
I think I recall the conversation @mark-chief but didn't realise a single form had this many fields. I think you mentioned 20-30 fields, but 100+ forms - which would be fine, as its not the overall total amount of fields that's the issue, its how many fields for a single form (which I think I mentioned).

At the moment, there's nothing for it, other than trying to reduce the number of fields in a single form - which might not be feasible for you...

I'll see what else I can come up with.

**Comment by mark-chief** [comment]
Yes i get you, appreciate it. The email I sent was for _ANOTHER_ client with lots of smaller forms so you are 100% right! Appreciate the help and effort on the plugin too, coming together nicely, especially with the new conditionals :)

**Comment by engram-design** [comment]
Ah, gotcha. This should all be a non-issue in Craft 4 at least, but still a good while away yet.

**Comment by engram-design** [comment]
Closing for now as it's a bit more of a Craft/long-term issue.
