### ISSUE TITLE
Allow placement of text below submit

### ISSUE THREAD

**Issue by jhealey5** [verbb/formie#443]
**What are you trying to do?**
Had a few clients request the ability to add checkboxes and html fields below the submit button, no way to do this currently. Whilst we could add separate fields outside of formie, it would make sense to keep everything in the form within the form.

**What's your proposed solution?**
Allow dragging of items below the button.

**Comment by engram-design** [comment]
Similar to https://github.com/verbb/formie/issues/108

**Comment by engram-design** [comment]
After many months (years?!) of considering this, I'm going to mark this as something we're not going to implement. There's a whole lot of complexity to making this happen, along with handling where captchas sit.

Ultimately, it's the UX concerns that something like this brings, and we're steering users towards best practices. For example, if we were to allow something like this, there's nothing stopping a client from moving a submit button into the middle of the form, which is pretty bad for many reasons.
