### ISSUE TITLE
Cloning a group should update the handle of the fields inside

### ISSUE THREAD

**Issue by alexgilbertDG** [verbb/formie#444]
**Description**
Cloning a group should update the handle of the fields inside so that they are unique.

**Steps to reproduce**
1. Clone a group with field inside
2. Try to save (Unable to save)

The new group with the new fields have the same handle so it caused an error.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.3.25
- Craft version: Craft Pro 3.6.12
- Multi-site: Yes

**Comment by engram-design** [comment]
This should be fixed already in [1.3.27](https://github.com/verbb/formie/blob/craft-3/CHANGELOG.md#1327---2021-04-11)
