### ISSUE TITLE
User/Entry fields with limit are only showing limit # of options

### ISSUE THREAD

**Issue by AmandaLutzTO** [verbb/formie#445]
**Description**
Using default Formie template, when I set a Limit (Limit the number of selectable entries.) to a User or Entries element field, the front end will render with that many options instead of limiting the number of selected options. Haven't checked Categories element field.

A twig dump of field.getFieldOptions() shows "Select an entry" array item, then limited # of options.

**Steps to reproduce**
1. Add User or Entries element field to a form
2. On field Settings tab enter value for Limit

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No (although happening there too)

**Additional info**
- Plugin version: 1.4.1 (was also happening on 1.3.27, thought maybe upgrade would fix)
- Craft version: 3.6.12
- Multi-site: No

**Additional context**
Yes our site is using custom templates but first thing I did was test with default Formie template.

**Comment by engram-design** [comment]
Fixed in [1.4.2](https://github.com/verbb/formie/releases/tag/1.4.2)
