### ISSUE TITLE
Error after latest update

### ISSUE THREAD

**Issue by havardlj** [verbb/formie#450]
I get the following error after the latest update:

`Neither the property "getVisibleFields" nor one of the methods "getVisibleFields()", "getgetVisibleFields()"/"isgetVisibleFields()"/"hasgetVisibleFields()" or "__call()" exist and have public access in class "verbb\formie\variables\Formie".`

Is this a bug in the new version, or is this me?

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload (AJAX when finished)
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.2
- Craft version: 3.6.12
- Multi-site: No

**Comment by engram-design** [comment]
Are you using `craft.formie.getVisibleFields()` in your templates, and if so, that was removed in [1.4.0](https://github.com/verbb/formie/blob/craft-3/CHANGELOG.md#removed) due to a much more complicated way of determining whether a field is hidden or not, due to conditions.

**Comment by havardlj** [comment]
Removing it completely from page.html seems to have done the trick, thank you
