### ISSUE TITLE
Provide import/export functionality for forms

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#465]
Allow importing/exporting of forms, fields and their pages from one environment to another.

Because forms are elements, and they're updated per-environment by clients, we can't have them synced.

This utility will be a hard-replace, rather than complex behaviour like being able to opt-in on what fields to import, etc.

**Comment by juban** [comment]
@engram-design Looking forward for that one.
Right now, how would you suggest to proceed to create a migration script to init a new form programmatically ?

**Comment by engram-design** [comment]
Right now, there's not an easy way to handle this and even a migration script would be pretty difficult, because you would need to migrate the records in the elements/elements_sites/content/formie_forms tables, which can be tedious.

You could certainly create everything about a form programatically, but there's no mechanism to serialize (and unserialize) everything about a form, which would be stored in a project-config-type situation (not exactly, but similar). You'd also need to define a way to store that information somehow, and have a reference to the environment it was created on.

That's all not without mentioning how to consolidate the same form between environments...

**Comment by juban** [comment]
Yes, looks like it's not easy. 
I've tried some stuff yesterday with no luck. By looking at the `buildFormFromPost`, I though I would be able to dump the content of a request from the FormsController and "replay" it in a migration script, but that's not strait forward either. I guess I'm in a case where setting forms manually on each environments will be much faster ^^
Anyway, thank you for your help. Hope to see the import/export functionality soon.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
