### ISSUE TITLE
Add "Value from Cookie" option for hidden field's default value

### ISSUE THREAD

**Issue by Mosnar** [verbb/formie#466]
**What are you trying to do?**

I would like to map the HubSpot tracking cookie (`hubspotutk`) to a HubSpot form submission's "Tracking ID."

**What's your proposed solution?**

Add a new default value type for hidden fields that allows entering a cookie name to grab the value from.

**Comment by engram-design** [comment]
Yep, currently you have to do this with JS. I've got something like this at the moment:

```
{# Look for any forms on the page wanting to use the HubSpot tracking and add it #}
<script>
var $trackingInputs = document.querySelectorAll('[name="fields[hubspotTracking]"]');

for (var i = 0; i < $trackingInputs.length; i++) {
    $trackingInputs[i].value = document.cookie.replace(/(?:(?:^|.*;\s*)hubspotutk\s*\=\s*([^;]*).*$)|^.*$/, "$1");
}
</script>
```

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.5](https://github.com/verbb/formie/releases/tag/1.4.5)
