### ISSUE TITLE
Upload Location path - subfolder throwing error when {author.username} used

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#468]
**Description** 
Setting the subfolder path throws an error on submission.

**Steps to reproduce**
1. Add a file upload field - set the subpath to `{author.username}`
![image](https://user-images.githubusercontent.com/599005/118035346-3557bd00-b3bf-11eb-817f-4098022646ba.png)
2. upload a file and submit.
3. Error received: 
![image](https://user-images.githubusercontent.com/599005/118035609-8962a180-b3bf-11eb-8d67-8be7247f8831.png)

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.3
- Craft version: Craft Pro 3.6.12
- Multi-site: No

**Additional context**
Alternatively, it would be good if we could dynamically set the subfolder path before rendering the form, then we could use any variable or custom field.?

```
{% set formHandle = 'companies' %}
{% set form = craft.formie.forms({ handle: formHandle}).one() %}

{# dynamically set the upload path based on the logged in user #}
{% do form.setFieldSettings('footerLogo', {
     uploadLocationSubpath: currentUser.CUSTOM_FIELD
}) %}

{{ craft.formie.renderForm( form ) }}  
```

**Comment by engram-design** [comment]
Ugh, that's my fault for blinding copy-pasting those field instructions - there is no `slug` or `author` variable for the context of a form submission.

I think you should be able to dynamically set the upload path like you've demonstrated, so will look into that.

**Comment by anchovy** [comment]
@engram-design cool, thanks.

**Comment by engram-design** [comment]
Yep, you can't use `setFieldSettings()` because that only really support setting field settings on form render, not form submission. I need to figure out a way to store field settings against a submission in a session, so that they can be used in the way you describe, and so the settings persist when the submission integrations/email notifications are run in a queue.

it's a larger task, but will keep you in the loop.

**Comment by engram-design** [comment]
See https://github.com/verbb/formie/issues/478

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
