### ISSUE TITLE
Provide Easier Access to Form Content Values

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#469]
**What I'm  trying to do**
I want to get access to all form content values excluding structural elements like groups and sections. I'm having to write code [like this](https://gist.github.com/mattcdavis1/afccee40ccbe240d6590b68fa098a20f) in order to do so.

**My proposed solution**
* Formie should provide a flattened array of form fields
* Each field should be identifiable as either a content field or a structure field.

**Comment by engram-design** [comment]
Are you able to clarify what you're trying to do? 

The problem with representing a submission as a flat array, is not all values for fields are simple values. Single-line text, Number, Dropdown, etc can all be expressed as strings, but Element fields need to return an element query, Group/Repeater fields return their own nested field query object.

There are a number of different properties on a field that let you know if it's a content or structure field - although in Formie itself, there's no real definition of the "structure" field. Using something like `$field->isCosmetic()` is often a good choice for fields that don't require user input, and are read-only.

Groups in particular are complicated in that they are more than just wrappers around fields, due to how fields need to work nested in another field.

We also follow the Craft standard approach of using Field Layouts for elements, so anything you normally do with Craft and other elements, should be the same for Formie Forms and Submissions.

If you do something like the following:
```
$submission = Submission::find()->id(1234)->one();

Craft::dd($submission->getFieldValues());
```

This would output the normalised field values for each field as an array. 

Or, if you wanted to loop through each field to get the field class **and** the content for that field in the submission, you could do:
```
$submission = Submission::find()->id(1234)->one();

$fields = [];

foreach ($submission->getFieldLayout()->getFields() as $field) {
    $fields[] = [
        'field' => $field,
        'content' => $submission->getFieldValue($field->handle),
    ];
}

Craft::dd($fields);
```

Do that help at all?

**Comment by mattcdavis1** [comment]
Sure - what I'm trying to do is post the form data to an external service (CRM).  I want to extract the data in a way that I can run the same logic for any form with no custom logic.  The `getSerializedFieldValuesForIntegration` doesn't return usable data for this. You have to add custom logic to know which fields contain content data or run something like the [gist that I posted above](https://gist.github.com/mattcdavis1/afccee40ccbe240d6590b68fa098a20f). 

I just want clean data, that can be accessed simply. This could be accomplished by:
* The plugin handling recursion logic to flatten the array
* Adding an property to indicate whether a field is structural or contains content
* Either ensuring that the __toString() magic method returns a usable string value or creating a non magic method for retrieving a string version of the field value. For repeating fields these could be returned as an HTML list or something like that. 
* Each field should be responsible for returning the best possible string version of its value.

**Comment by engram-design** [comment]
Gotcha, so basically a combination of using `getSerializedFieldValuesForIntegration()` for the content and `getFields()` for information about the field (type, handle, cosmetic, etc). With the addition of flattening Group fields, which I believe your Gist does. I'll note that you wouldn't want to flatten a Repeater field's values for instance.

The `getSerializedFieldValuesForIntegration()` is for taking care of your last 2 points, although not as a plain string for every field. A Checkboxes field for instance has multiple values and should be an array. Which is where each integration takes care of that. Some integrations support an array of content, others don't which we check for per-integration (and comma-delimit if only a string is supported, for example). I'm not sure about returning a HTML list, which would be pretty opinionated and tricky to cater to everyone's needs - but I see what you're getting at.

I'll consider the best approach for this. It'd be super-helpful if you're able to post your ideal format, given the sorts of fields you're dealing with to fill in any gaps on what I'm thinking on this.

**Comment by mattcdavis1** [comment]
I think the format would be:

* `$formieForm->toScalar($flatten)` which would return an optionally flattened array of scalar values. To accommodate this, each field would need to implement the toScalar() method. For those that do not want an opinionated string result for multiple-value fields this function could be used. 
* `$formieForm->toString($flatten)` would be used to get an optionally flattened array of string values where field authors determine the most appropriate string representation of their field's value.

None of this should be very complicated if the field level functions are added because it shifts the responsibility to the field type to return it's representation which is a very manageable scope and an appropriate location for that responsibility. Once the field-level function is in place the form level representation is simple. All you'd need to do is loop through each field and request its scalar or string value. 

There would be a bit of complexity at the field level for something like a group field but still relatively straightforward.

**Comment by engram-design** [comment]
Good thinking on `toScalar` - I was trying to think of a better word than `toString` that would be more opinionated than just converting something to a string. For instance, I'm not sure I actually want a `__toString()` magic function on some fields, when they will never be strings. I'll have to ponder this some more. At least this method (using `toScalar` and `toString`) will keep this separated.

It's also been on my list to refactor how integrations, exports and variables are handled. Right now, it's pretty unorganised and a bit of a mish-mash, so this will help to consolidate that functionality as well. As you say, not difficult, and most of the work is there just need a good re-organise.

Adding it on the todo list!

**Comment by mattcdavis1** [comment]
great - thanks!

**Comment by engram-design** [comment]
Completely revamped the content values for [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
