### ISSUE TITLE
Update submission data > update Entry 

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#475]
After changeing and saving submission data in admin > update Entry

![Snag_ab9b46](https://user-images.githubusercontent.com/76176291/119928224-72a17a80-bf7b-11eb-8398-f09427100147.png)

**Comment by engram-design** [comment]
Can you explain the issue in a bit more detail? In addition, I can't see what fields in Formie you're mapping to fields in your entry. It's important to map "Update Element Mapping" to something that's unique, but you must also provide a value for that in your submission.

For example, you could map against the ID, but you need to ensure you have a field in your form with the appropriate Entry ID value.

**Comment by wmdhosting** [comment]
1. User submit  on front end.. 
2. Submission created..  > Entry created   all ok..
3. I change some submission data.. in Formie submission page.. Save
4. Entry does not update.. 

I use ID for slug..   to check for existing... entry..
![Snag_c43a7f](https://user-images.githubusercontent.com/76176291/119930158-34a65580-bf7f-11eb-8979-d9943eb2164a.png)

**Comment by engram-design** [comment]
Ah, I see. Yes the integration for elements only triggers on form submission, not on submission save events. This is specifically to prevent unexpected results or overwriting data on the destination element.

For example, say you edited the submission 1-2 months after the user was created. Maybe they're updated a particular field you're mapping content from a form submission. If you re-saved their original form submission, it would overwrite any changes they've made on their account (that have fields mapped in the Formie integration settings).

Similarly, for Entry element integrations. What if the entry has been edited directly. I don't believe Formie should assume that every time a submission is saved, it should overwrite content.

At the very least, I could introduce a button on a submission edit page for the integration to be re-triggered on-demand. This would be similar to [resending an email notification](https://github.com/verbb/formie/issues/398)

**Comment by wmdhosting** [comment]
Ok thx :) 

Yes, button will be ok...

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
