### ISSUE TITLE
More date-time field and Flatpickr options

### ISSUE THREAD

**Issue by shoored** [verbb/formie#481]
**What are you trying to do?**
I'm recreating a form with Formie that I previously built with another form plugin and custom rendering.
The form uses a datepicker with Flatpickr, which Formie now also supports out of the box, very nice.

In my previous setup, the Flatpickr instance has the config option set to allow multiple dates and it hides the input but always shows the calendar.

**What's your proposed solution?**
- It would be great if the date-time field has the option to allow for multiple dates to be selected (`mode: multiple`) or maybe even general Flatpickr config settings
- It would be great if the Flatpickr instance has the ability to always show the calendar and maybe hide the corresponding input as well
- It would be great if the min start date could also be a Twig value, ie `{{ now }}` (perhaps via field options in Twig)

**Additional context**
Screenshot of the current / old setup

![image](https://user-images.githubusercontent.com/26165948/120639910-2a4df500-c472-11eb-9294-205ea3568ab6.png)

**Comment by shoored** [comment]
Perhaps these things are already possible with custom form rendering. But since Formie is so advanced and has many options already, I'm a bit lost in how to change only this small part of the form / field. I cannot seem to hook intro the field outer wrapper where the `data-field-config` is defined.

**Comment by engram-design** [comment]
I'll be adding a few more config options to the field to allow this to be content-managed from the control panel.

For the moment, you can use JS events to modify the config of Flatpickr, or mess around with the field instance's JS. Refer to the docs on how this can be done - https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#date-fields

> It would be great if the date-time field has the option to allow for multiple dates to be selected (mode: multiple) or maybe even general Flatpickr config settings

I don't think that'll be possible, as the date field itself it pretty geared towards a single date value, with things like validation, etc. I would almost recommend using a hidden field, and rolling Flatpickr on that hidden input to store the multiple value on that.

> It would be great if the Flatpickr instance has the ability to always show the calendar and maybe hide the corresponding input as well

Should be possible with the above Flatpickr modification, but will make its way into the UI.

> It would be great if the min start date could also be a Twig value, ie {{ now }} (perhaps via field options in Twig)

As above.

**Comment by shoored** [comment]
You were right about the multiple dates thing, Formie won't validate that. Which makes sense. So I had to roll my own Flatpickr instance on a hidden field and that works well.

Though, I could still see how additional config options make sense in general and/or for other customers. Sorry that I totally missed the custom Javascript option for date fields.

**Comment by engram-design** [comment]
Added for the next release. Date fields now have a table of option/value settings to provide [Flatpickr.js options](https://flatpickr.js.org/options) from within the field settings. This only really handles simple options, and anything more advanced like callbacks or JS functions should use the JS events to hook into that. Otherwise, executing stored JS poses security risks (if you could imagine providing a JS object in the field settings), but just as important - it's extremely client-unfriendly to have that. 

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
