### ISSUE TITLE
Conditional required fields

### ISSUE THREAD

**Issue by jhealey5** [verbb/formie#482]
It's really great to see we now have conditional logic! 🎉 

However, when setting one of those conditional fields to be required, it looks as if the conditional logic doesn't respect that and a required field that's hidden prevents the form submitting.

Is it possible to get the required attribute added/removed as part of the logic process?

**Comment by engram-design** [comment]
That's exactly what should be occurring. Any required field hidden or shown through conditional logic should have the `disabled` attribute toggled.

https://github.com/verbb/formie/blob/1a51c3b012590a506a6b2df7f11d37e3470c33fc/src/web/assets/frontend/src/js/fields/conditions.js#L149-L162

Can you comment on your setup?

**Comment by jhealey5** [comment]
Ah sorry you're right, I'm not sure why it wasn't working during my initial tests but it seem to be now!

Can close this up, thank you!
