### ISSUE TITLE
Submission Deleted event

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#483]
**What are you trying to do?**
We're using Formie as a simple event registration form. When someone successfully signs up for an event, we use `EVENT_AFTER_SUBMISSION` to decrement an inventory field in the related Entry. Conversely, we'd also like to increment the inventory field if the submission is deleted. (Effectively cancelling the registration and making the spot available for someone else).

**What's your proposed solution?**
An `EVENT_BEFORE_SUBMISSION_DELETE` event should do the trick, as long as we can get the related entry ID from the submission before it's deleted.

**Comment by engram-design** [comment]
There's already an inherited element event for this, just undocumented until now, as its an event provided by Craft for all elements.

```
use verbb\formie\elements\Submission;
use yii\base\Event;

Event::on(Submission::class, Submission::EVENT_BEFORE_DELETE, function(Event $event) {
    $submission = $event->sender;
    $event->isValid = false;
});
```

https://verbb.io/craft-plugins/formie/docs/developers/events#the-beforeDeleteSubmission-event
