### ISSUE TITLE
Rename user uploaded files

### ISSUE THREAD

**Issue by stevefloat** [verbb/formie#487]
**What are you trying to do?**
When using the File Upload field, it would be really helpful to have the option to rename the uploaded file (perhaps this is already possible but couldn't find any references in the documentation).

**What's your proposed solution?**
It would be nice to have an option to pick values from other fields in the form, to use in the file name. Like is possible for the Submission Title Format.

Thanks!

**Comment by stevefloat** [comment]
Hi @engram-design - I just wanted to nudge a little on this. Only so I could get an idea if this may be possible.

I appreciate this may not be on your road map, but I have a client who needs this as a feature so I just need to get an idea of options. And if it's something you may consider in a future release.

Many thanks - and appreciate your input!
Stephen.

**Comment by engram-design** [comment]
Certainly happy to add this to our todo list for a future release, but can't provide an ETA sorry. There's definitely some things to consider, particularly dealing with duplicate name collisions. 

I think you might be able to achieve this yourself using the events available. One approach would be to listen for the on-submission success, lookup the File Upload field, get all the assets uploaded, and rename them, based on whatever you need to have the filename renamed as.

**Comment by stevefloat** [comment]
Thanks for getting back quickly - appreciate it!

Will have a look to see what we might be able to do, following your suggested approach.

Best wishes,
Stephen

**Comment by engram-design** [comment]
After some more thinking through this, I'm not exactly sure how best to implement this. Particularly as we have to deal with the possibility of multiple files being uploaded. How would you see this working for your needs?

Would it be a matter of providing a format, similar to the Submission Title, but requiring a suffix value?

For example, you might have the following "File Upload Naming Format" value:

```
form_applications_{myField}_{dateCreated}_{suffix}
```

Where `{myField}` might be a reference to another field, `{dateCreated}` the date the file was uploaded, and a `{suffix}` that would be required in order to deal with multiple files. Resulting in:

```
form_applications_josh-crawford_2022-09-04-10-34-13.pdf
```

Or, when multiple files are present:
```
form_applications_josh-crawford_2022-09-04-10-34-13_1.pdf
form_applications_josh-crawford_2022-09-04-10-34-13_2.pdf
form_applications_josh-crawford_2022-09-04-10-34-13_3.pdf
```

**Comment by stevefloat** [comment]
Hi Josh. Thanks for thinking this through.
What we needed was the ability to completely rename the file to the value of a field in the form. So in your example of having a "File Upload Naming Format" I would have liked to specify:
`{userId}`
as the filename (where userId is a field in my form), which would result in a file like:
`0123456789.jpg`
In my scenario, I didn't want to store duplicate files but for any newly upload files to replace the existing one. Again in your example, would leaving off a `{suffix}` do just that and replace the asset file?
Or, could you offer an option to handle multiple files - for instance:

- [x] Replace any file with this name, or
- [ ] Create a new file with a suffix

In the end we did as you suggested and have some logic listening for the on-submission success event and processing the filename then. However it would be good for the future knowing if this option was built in.

**Comment by engram-design** [comment]
Thanks for the feedback! Yep, that all makes sense. And as for the duplicate handling, I hadn't actually gotten that far, more thinking for multi-uploads fields, where users can upload more than one file at a time, and how to handle the renaming of that. If you set this to `{userId}` and you uploaded 3 files, you'd end up with `0123456789_1.jpg`, `0123456789_2.jpg`, `0123456789_2.jpg`.

I can't think of an instance where you'd want those 3 files overwriting one another by enforcing just the `0123456789.jpg` filename.

I'll give this some further thought.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
