### ISSUE TITLE
Email notification - test email doesn't work

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#49]
### Description
Getting a 
Notification email could not be sent for submission “”.
error when I try and send an email test from the preview screen.

### Steps to reproduce

1. Create a form
2. Create a notification
3. Try sending a test email from the preview screen.

Tried on a form with 0 submission, then with 1 submission. Tried an empty email, then All Form Fields email. Default Formie email template.

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.4.22.1

**Comment by bleepsandblops** [comment]
Apologies - this was an issue with the mail config on the site.

However, the error message could be improved to remove the "submission """ and say instead "test submission" or something equivalent, but this is super minor.

**Comment by engram-design** [comment]
Appreciate the feedback, will make sure we update that.
