### ISSUE TITLE
Order subfields in Address field

### ISSUE THREAD

**Issue by Diewy** [verbb/formie#490]
**What are you trying to do?**
When adding an address field it is not possible to rearrange the fields. I would like to have the postal code before the city.

I tried the following solutions: 
1) Overriding the [address field template](https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/fields/address/index.html): Since it works with a loop for the different fields, it doesn't look like an easy or stable solution.
2) Order the fields in CSS: Since the `.fui-row` class is using flexbox it is possible to assign specific order to `.fui-address-zip` and `.fui-address-city`, which works visually but doesn't have the right tabindex.

Plus, both solutions force you to have the postal code before the city field for all forms. For an international website, it would be better to be able to make form-specific adjustments.

**What's your proposed solution?**
Adding a new feature to let users order subfields in the address field.

**Additional context**
In Europe, it is common to have the postal code before the city.

**Comment by juban** [comment]
Ugly, but for now, you can do something like that as a workaround (could be site dependent):

```twig
    <div class="fui-field-rows">
        {% for row in field.getFrontEndSubfields() %}
            {% set visibleFields = field.getVisibleFrontEndSubfields(row) %}

            <div class="fui-row {{ not visibleFields ? 'fui-row-empty' }}">
                {% if row.city is defined %}
                    {% set row = row|reverse %}
                {% endif %}
                {% for handle, autocomplete in row %}
                    {% include 'fields/address/_field' %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
```

**Comment by carolineboeykens** [comment]
Is there any news on this? This feature would be really nice (I'm also in Europe)

**Comment by engram-design** [comment]
@carolineboeykens Scheduled for 2.1.x (likely timed for early next year).

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
