### ISSUE TITLE
Support UI Elements in the field layout for Form Templates

### ISSUE THREAD

**Issue by Kashkin** [verbb/formie#492]
**What are you trying to do?**
I'd like to provide more context to content authors using Craft's UI Elements.

**What's your proposed solution?**
Add support for Craft's UI Elements.

![image](https://user-images.githubusercontent.com/3699310/122013223-1f457e00-cdfd-11eb-9fc8-8dc799c4f74e.png)

**Comment by engram-design** [comment]
Just to be clear, you're not looking for Craft's UI elements to be added to the form builder, or are you? If so, I'm not quite sure on how to handle them, as they're be CP-only content, which would be confusing alongside fields displaying on the front-end. Heading a Horizontal Rule are taken care of at the moment, but not Tip/Warning/Custom Elements.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
