### ISSUE TITLE
Customise field error messages

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#493]
**What are you trying to do?**
I've found a way to manually render fields into HTML elements, but the errors that are connected to the fields don't appear to be customisable (have yet to find documentation on it). It appears to be JS related as the errors appear before a page reload.

**What's your proposed solution?**
Some way to hook into the error messages if they exist and output either the default error message or allow some custom CSS and HTML to be used.

**Comment by engram-design** [comment]
For client-side validation, you'll need to use [static translations](https://craftcms.com/docs/3.x/sites.html#static-message-translations) to modify these values.

See https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/formie-form-theme.js#L63-L93 for a full list of what Formie uses for validation messages.

If your field is required, you can manage this error message in the field on the form builder.

Providing a file at `translations/en/formie.php` with the following content should do the trick. Note you'll need to use the appropriate language value for your site.

```
<?php

return [
    'This field is required.' => 'Please fill out this field.',
];
```
