### ISSUE TITLE
Create Sent Notifications for failed notifications

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#495]
We should be creating a sent notification earlier in the process, and adding a status to determine if it was successful or not. This will greatly assist with troubleshooting emails, as there'll be data recorded against the delivery of the email.

Otherwise, we only have the submission data to work with, and no real reference as to why it failed (other than the stuck queue job - which only exists if using queue processing).

**Comment by shoored** [comment]
Was just about to file an issue when I read your FR. I'm having exactly this issue where email notifications are failing when attachments are enabled and I can't really see why they are failing. 

Though, if you'd like me to file another issue for this .. issue .. I'd be happy to.

**Comment by engram-design** [comment]
@shoored Are you using the queue system? Is there a failed job, and is there an error message for the task?

**Comment by shoored** [comment]
@engram-design Yes using a server daemon in the background. Notifications without file upload fields and notifications where attachments are disabled do get sent.

Errors are `Failed to send notification email: {"error":"Notification email could not be sent for submission “223350”."}.`

I must say I'm still on 1.3.27 for this particular site. 
Will try to upgrade first to see if that fixes things.

**Comment by engram-design** [comment]
Yep, so that's the general "mailer" error where Craft can't send your email. What mailer service are you using, sendMail or a third-party service?

**Comment by shoored** [comment]
Hm files do get attached when I sent from my local environment. 
Both using Postmark as the service.

I think it might be a path issue. Will fiddle some more

**Update**: It's working. Somehow paths got mixed up even though files did get saved on the server. Formie could not get the correct path for attaching the files. 

Could have probably debugged this a bit better myself, sorry about that.

**Comment by engram-design** [comment]
@shoored Glad to hear 👍

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
