### ISSUE TITLE
Enable 'Allow Multiple' option for the Entries field when displayed as a dropdown

### ISSUE THREAD

**Issue by am0** [verbb/formie#496]
**What are you trying to do?**
Currently, unlike the dropdown field, the entries field doesn't have the 'Allow Multiple' toggle as an option.

**What's your proposed solution?**
When 'Dropdown' is selected in the appearance field's option panel under Appearance, show the option to display the 'Allow Multiple' lightswitch.

**Additional context**
Had a request from a client to be able to select multiple options from a long list of entries. When there's +100 of them, the UX isn't brilliant as a dropdown but is far better than a big grid of checkboxes, but currently can't do a multi-select with this.

One thought I had was that it's possibly a bit confusing with the 'limit' option being on the Settings tab, so there might be a tiny bit of confusion where people have selected a limit of 1, and then enable multi-select while forgetting that they've limited it to 1? But I guess at least if it's displayed on the form preview and the front end as a multi-select they'd likely work it out.

Thanks again.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
