### ISSUE TITLE
Bulk add options (Drop down field) append to (instead of remove) existing options

### ISSUE THREAD

**Issue by thijskaspers** [verbb/formie#497]
Feature request for small improvement. As the title states: The "Bulk add options" (at a Drop down field) removes existing options, so you can never use it twice if you'd like to add more options. Why not append instead of overwrite?

**Comment by engram-design** [comment]
Yep, agreed I think adding them as appended makes more sense, which is now the default behaviour. Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
