### ISSUE TITLE
Bug when de-activating JS on a template

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#50]
### Description
Getting this when rendering the form:
_Return value of verbb\formie\elements\Form::getFrontEndOutputJs() must be of the type boolean, null returned_

Looking at the db, the column outputJs is saved as NULL instead of 0.

### Steps to reproduce

1. Create a template, de-activate JS
2. Create a form and assign to template. 
3. Try rendering the form.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
Fixed in [1.1.1](https://github.com/verbb/formie/releases/tag/1.1.1)
