### ISSUE TITLE
Wrong craft.formie.renderPage(form, page) doc

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#505]
**Description**
As seen on https://verbb.io/craft-plugins/formie/docs/template-guides/available-variables#craft-formie-renderPage:
```
{% set form = craft.formie.forms({ handle: 'contactForm' }).one() %}

{% for page in form.getPages() %}
    {{ craft.formie.renderPage(form, page) }}
{% endif %}
```

The last line is incorrect, and should be `{% endfor %}`.

**Comment by engram-design** [comment]
Fixed!
