### ISSUE TITLE
Phone number field country flags not displaying when using registerAssets or renderFormCss + renderFormJs

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#506]
**Description**
When setting up a custom form, the phone number field country flags are not displaying when using `registerAssets` or `renderFormCss` + `renderFormJs`. They remains blank.

This happens even if `registerAssets` or `renderFormCss` + `renderFormJs` are initialized at the top of the template, just after `craft.formie.forms()`.

If the standard method `craft.formie.renderForm()` is used, the flags are showing up.

![](https://i.imgur.com/okEWGya.png)

**Additional info**
Plugin version: 1.4.7
Craft version: 3.6.17
Multi-site: No

**Comment by engram-design** [comment]
I can't seem to replicate this - are there any network errors? It should be trying to fetch the [flags](https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/img/flags.png) from a CDN, handled by the [intl-tel-input](https://github.com/jackocnr/intl-tel-input) library.

I've tested with a completely manual-rendered form with loading in the CSS/JS on-demand with those tags. If the JS is working for the field, then it should be showing the flags.

**Comment by romainpoirier** [comment]
I finally found that I was missing the `.fui-i` class somewhere in my custom template, as a `<form>` wrapper to reach this:
```
.fui-i .iti__flag {
    background-image: url(https: //cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/img/flags.png)
}
```

Without the `.fui-i` class, it was getting this instead:
```
.iti__flag {
    height: 15px;
    box-shadow: 0 0 1px 0 #888;
    background-image: url(../img/flags.png);
    background-repeat: no-repeat;
    background-color: #dbdbdb;
    background-position: 20px 0;
}
```
Where the reference was the missing  `../img/flags.png` (`/cpresources/img/flags.png`) instead of the remote CDN url.

**Comment by engram-design** [comment]
Ah, I should've checked that. Completely forgot those flag images are loaded via CSS and not JS like I thought.
