### ISSUE TITLE
Phone country labels displayed wrong on error

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#513]
When an error has occurred, the CSS for the phone country dropdown is a bit messed up.
This also happens when I remove all styling except the Formie base styles. So I think it has nothing to do with my custom styling which is pretty bare.

<img width="237" alt="Screen Shot 2021-07-05 at 10 36 04 AM" src="https://user-images.githubusercontent.com/16959207/124442878-78119200-dd7d-11eb-8edb-5d7f06521343.png">

**Comment by engram-design** [comment]
So this certainly doesn't happen with the stock theme and form templates. Are you using custom templates? You've made sure to test by removing **all** CSS on the page, apart from the `phone-country.css` file and if you're using it, the `formie-theme.css`?

**Comment by engram-design** [comment]
Closing for now, if this is still an issue, maybe we can tee up a time to go through your project?
