### ISSUE TITLE
Email notification failed sending because of DateTime field format error

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#524]
**Description**
Email notification fail sending because of DateTime field format error.

This is what I get in the `Edit Notification` window:
```
Error sending test email.
Notification email “Test” could not be sent for submission “new”. The mailer service failed to send the notification: “”.
```

And this is what I get in the `formie.log` file:
`[-][1][-][error][formie] Failed to render email field content for myDateField: Object of class DateTime could not be converted to string`

**Steps to reproduce**
1. Setup a form with a Date/Time field (in my case, the `Visibility` is set to `Disabled`)
2. Setup an `Email Notification`
2. Setup `Email Content` using the `All Non Empty Fields` special variable
3. Send email preview using `Preview` > `Send Test Email`

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3 as 1.4.9
- Craft version: 3.7.0
- Multi-site: No

**Comment by engram-design** [comment]
I can't seem to replicate this. Can you send through your date field settings?

**Comment by romainpoirier** [comment]
I can't replicate this error anymore 🙈  So for the moment your can close this ticket. Sorry about that!

**Comment by romainpoirier** [comment]
I think that was because my email was blocked by Mandrill (too many attempts). Then this error followed, and probably it could not write it inline as text as it's a DateTime object.

Maybe you can just fix what is logged to convert the DateTime object to a String:
`[-][1][-][error][formie] Failed to render email field content for myDateField: Object of class DateTime could not be converted to string`

**Comment by engram-design** [comment]
It could very well have been fixed in https://github.com/verbb/formie/commit/e6ad7f71017b5fea560b7871c20be059a3860a19 I just wasn't 100% sure!

I'll continue keeping an eye on it and test.
