### ISSUE TITLE
Setting unknown property:  craft\records\Element::canonicalId

### ISSUE THREAD

**Issue by Timusan** [verbb/formie#525]
**Description**

Formie crashes when submitting a form with the following stacktrace:

```
2021-07-15 12:23:26 [-][-][ta5dj0k4sn50ivem3anjcb4vtm][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property:
 craft\records\Element::canonicalId in /var/www/websites/production/htdocs/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /var/www/websites/production/htdocs/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set()
#1 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(54): yii\db\BaseActiveRecord->__set()
#2 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/services/Elements.php(2535): craft\db\ActiveRecord->__set()
#3 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/services/Elements.php(773): craft\services\Elements->_saveElementInternal()
#4 /var/www/websites/production/htdocs/vendor/verbb/formie/src/controllers/SubmissionsController.php(508): craft\services\Elements->saveElement()
#5 [internal function]: verbb\formie\controllers\SubmissionsController->actionSubmit()
#6 /var/www/websites/production/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/websites/production/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#8 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#9 /var/www/websites/production/htdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#10 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction()
#11 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/web/Application.php(584): craft\web\Application->runAction()
#12 /var/www/websites/production/htdocs/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest()
#13 /var/www/websites/production/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#14 /var/www/websites/production/htdocs/public/index.php(22): yii\base\Application->run()
#15 {main}
```

This looks to be happening while trying to sent the notification for the submission:

![image](https://user-images.githubusercontent.com/1012919/125774058-60f5fcd5-868a-4ef6-94c4-d7755fda7ba4.png)

**Steps to reproduce**

Unsure - This happens after the 1.4.10 upgrade on a general contact form containing the following fields:

- First name (Name)
- Last name (Single-line text)
- Message (Multi-line text)
- E-mail (Email)
- Name business (Multi-line text)
- Cellphone (Telephone)
- Nieuwsletter signup checkbox (Agree)

Not ruling out a strange configuration error on our part ... but it is stranger it happens right after the upgrade.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.10
- Craft version: 3.7.1
- Multi-site: No

**Comment by engram-design** [comment]
Hmmm, is there a field with the handle `canonicalId` in your form? From what you've mentioned, it doesn't sound like that's the case, but there's nothing in Formie that uses `canonicalId`.

**Comment by Timusan** [comment]
Nope, just double checked, including the email notifications, nothing that hints towards `canonicalId` ...

**Comment by engram-design** [comment]
Is there any field at all in the `fields` database table with that handle? That otherwise seems pretty odd.

It looks like this might be coming from Craft, as this is seemingly added in Craft 3.7+ https://github.com/craftcms/cms/search?q=canonicalId it almost sounds like the upgrade didn't work correctly?

**Comment by Timusan** [comment]
Sorry for the late reply, this seemed to be an upgrade issue indeed, after the recent Craft updates and the latest Formie update the issue disappeared. Well, it is to say, that particular error disappeared from the logs, the form still fails to send the email and it is caused by this:

`[yii\base\ErrorException:128] yii\base\ErrorException: Private methods cannot be final as they are never overridden by other classes in /var/www/websites/production/htdocs/vendor/hoa/stream/Stream.php:195`

An issue which is already reported here: https://github.com/hoaproject/Stream/pull/30 but gets zero attention so it seems. I'm guessing Formie is not at fault here and it is something deeper within the Yii framework.

I have downgraded the server running the project to PHP 7.4 and this makes Formie able to work again.

**Comment by engram-design** [comment]
Ah interesting, I'll keep an eye on that PR, thanks for investigating!

**Comment by engram-design** [comment]
If you're unable to downgrade from PHP 8, you should be able to get around this issue by adding the following to your `composer.json`.

```
"require": {
    "hoa/stream": "dev-1.17.02.21-php8 as 1.17.02.21"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/mathroc/Stream"
}],
```

I'd love to include this in Formie's `composer.json` file, but these changes will only work in the root `composer.json` file - https://stackoverflow.com/questions/35699807/nested-dependencies-and-private-repositories-with-composer
