### ISSUE TITLE
Form validation fails if a required field with pre-filled value has the disabled attribute

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#526]
**Description**
Form validation fails if a required field with pre-filled value has the disabled attribute.
> Couldn’t save submission due to errors.

**Steps to reproduce**
1. Setup an _Email_ field
2. Add `{{currentUser.email ?? null}}` as _Default Value_
3. Add Name: `disabled` + Value: `disabled` in _Input Attributes_

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3 as 1.4.10
- Craft version: 3.7.0
- Multi-site: No

**Comment by engram-design** [comment]
Hmm, I'm not exactly sure if this should be considered a bug. There's both client and server-side validation for required fields. If you add a `disabled` attribute on a required field it won't be sent with the POST request, and it'll throw a validation error client and server side. 

Even if you were to handle the client-side (by removing the `required` attribute on the input if you add a `disabled` one), we'd also have to do the same for server-side validation, which I guess could be done by checking the Input Attributes.

However, what if through JavaScript you added a `disabled` attribute on the input through some logic of your own. There's no way server-side to detect you've just added a `disabled` attribute and it doesn't need to be checked.

I'd probably recommend using a hidden input, hiding the field, removing the required state, or adding a fallback value.

EDIT: I might recommend you use the `readonly` attribute, which acts similar to `disabled` but is still sent with the POST payload, but cannot be user-edited.

**Comment by romainpoirier** [comment]
You're totally right, thank you for all these clarifications. In my case the `readonly` attribute is the perfect solution, as I want my field to still be displayed to the user without being editable.

**Comment by engram-design** [comment]
No problem, I'll say that's the solution for this one.
