### ISSUE TITLE
Email Notification condition set to "Send if status change" isn't sending

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#527]
**Description**
The email notification condition set to _Send_ if _All_ : _Status_ is _Status name_ is not sending. Even the Queue Manager doesn't catch these sending.

**Steps to reproduce**
1. Setup custom statuses like _Selected_
2. Setup a new form
3. Add a new Email Notification to send if _All_ : _Status_ is _Selected_ 
4. Fill and submit form on front-end
5. Update form submission status to _Selected_ on back-end
6. The email is not sent

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3 as 1.4.10
- Craft version: 3.7.0
- Multi-site: No

**Comment by engram-design** [comment]
Related to https://github.com/verbb/formie/issues/367 there's no actions performed when changing the status of a submission. Email notifications are only fired on submit.

**Comment by romainpoirier** [comment]
Oh, ok.. That's a shame. like in #367 (sorry for the duplicate) I was expecting to use conditional rules to send notifications based on the status update.

Example:
1. Form is submitted → status is set by default to `New` → email notification is sent to site admin
2. Submission is reviewed by admin → status is updated to `Selected` by admin → email notification is sent to user

Questions:
- Is there currently any possibility to build this feature by myself, using a custom module catching the `afterSaveStatus` events?
- Do you have any information about when you plan to add this feature?

**Comment by engram-design** [comment]
Yep, unfortunately only on-submission are email notifications fired, but that'll certainly change soon once we work in a concept of status histories.

You should certainly be able to handle this yourself through the [events](https://verbb.io/craft-plugins/formie/docs/developers/events#the-afterSaveSubmission-event). Something like the below should give you a start, ensure you change the `statusId` and `notificationId` to your needs.
 
```
Event::on(Submission::class, Submission::EVENT_AFTER_SAVE, function(Event $event) {
    $submission = $event->sender;

    if (!$submission->isIncomplete && $submission->statusId = 2) {
        $notification = Formie::$plugin->getNotifications()->getNotificationById(123);

        $sentResponse = Formie::$plugin->getEmails()->sendEmail($notification, $submission);
    }
});
```

You could also make it more complicated by listening to `Submission::EVENT_BEFORE_SAVE` to check against the current status (before it is updated) to the new status in `Submission::EVENT_AFTER_SAVE` - but that's your call.

No ETA sorry, but it'll be in the near-term 1.4.x releases (think the next 2-4 months).

**Comment by engram-design** [comment]
Closing this one in favour of the conversation continuing in https://github.com/verbb/formie/issues/367#issuecomment-967149364
