### ISSUE TITLE
Can't update status of incomplete submission using setStatus on EVENT_AFTER_INCOMPLETE_SUBMISSION

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#528]
**Description**
As there're currently no way to set a status from the CP when the submission is still incomplete in a multi-pages forms (see #508), I'm trying the handle this using Formie events:

```
Event::on(Submissions::class, Submissions::EVENT_AFTER_INCOMPLETE_SUBMISSION, function(SubmissionEvent $event) {
    $submission = $event->submission;
    $success = $event->success;

    if ($success) {
        $status = Formie::$plugin->getStatuses()->getStatusById(3);
        $submission->setStatus($status);
    }
});
```

However, while the `$success` is caught, the `setStatus` doesn't update.
In the `craft_formie_submissions` table, the `statusId` column remains `NULL` when `isIncomplete` is `1`.

So there's stil no way to update the status of an incomplete submission, even from a custom module?

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3 as 1.4.10
- Craft version: 3.7.3.2
- Multi-site: No

**Comment by engram-design** [comment]
Yep, the event `EVENT_AFTER_INCOMPLETE_SUBMISSION` fires after the submission has been saved, so you'd need to save it again in this call.

`Craft::$app->getElements()->saveElement($submission)`

**Comment by romainpoirier** [comment]
The status shown in the CP is still `Incomplete`, but I can see that the dot for status color get the correct one, and in the DB `statusId` is correctly set when `isIncomplete` = `1`. Thank you!

**Comment by romainpoirier** [comment]
By the way, it would be super nice if you can still display the correct status instead or in addition to the `Incomplete` state. As explained, there's currently only the dot color as reference. Even when filtering submissions, it is only showing up when filtering on `Incomplete` and not on the forced one by `$submission->setStatus($status)`.

Maybe this is a reference to #508 in the context of multi-pages forms.

**Comment by engram-design** [comment]
Yep, at the moment incomplete (and spam) is treated as another status when they're really in addition to status.

**Comment by engram-design** [comment]
@romainpoirier FYI, if you're still interested on your last comment, have created a new issue with some comments. https://github.com/verbb/formie/issues/573#issuecomment-947565925

In addition there's now a "Status" column for submissions, which I think will help when selecting Spam/Incomplete you'll also be able to see the status.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
