### ISSUE TITLE
Add an option to disable form submission saving in CMS

### ISSUE THREAD

**Issue by rickbergmans** [verbb/formie#53]
Some forms contain personal data that we only want to e-mail, but don't want to save.

**Comment by engram-design** [comment]
This is on our todo list, but there are some complications. Namely emails are sent out using Craft's queue system, which really relies on the submission being saved, as the queue can be triggered any time after submission takes place.

I'll also make the comment that emails aren't exactly the most reliable delivery method, and without email delivery, the submission is essentially lost, which might be pretty important.

My other question is would it be good enough to not show the submission in the control panel, but have it in the database? Or having it even in the database (essentially hidden), is still not good enough for sensitive info?

We also have other privacy settings planned regarding data retention and how long to save submissions for before deleting them.

**Comment by rickbergmans** [comment]
Having it hidden will help us out for now, but only partly fix the problem on the long run. I understand that e-mail isnt the best method, which is why we have failed delivery notifications on (nice feature!).

I would love a privacy setting to delete submissions automatically after a week or so. That way we can act when an email wasn't sent, without losing the form data. With an option to hide the submission tab in the CP, our client, or someone with access tot the CP, can't see the submissions in the meantime. 

I think that's the best way to fix our problem :)

Thanks!

**Comment by engram-design** [comment]
Sure thing, I might even lower it to a day, just for those times were you really don't want it hanging around in your site. I think it's largely unavoidable to store it for at least _some_ time in order for notifications, integrations and a few other things to kick in.

Be on the lookout for a bunch of privacy-related settings coming soon.

**Comment by rickbergmans** [comment]
Thank you!

**Comment by joeRob2468** [comment]
Just to add on to this, disabling form submission saving would help us avoid swamping the site assets with any file uploads users can submit (since those assets don't get auto-deleted as far as I know, and will take up space on the server when they could just be sent via attachments on an email notification and then deleted).  Not sure if it's possible, but if you can't avoid saving submissions entirely, it might be nice to save submissions for a day (or a week, maybe a configurable storage period) while notifications and stuff go through, then remove the linked assets from the server and remove the submission.

**Comment by engram-design** [comment]
Good point regarding submission assets, I've not tested that, but I'll ensure that's the case.

**Comment by coenfuze** [comment]
Would like too see this options as well with the ability to set a purge scheduler for example: 7, 14, 30, 90, 360 days.
Keep up the good work!

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
