### ISSUE TITLE
Not able to access assigned Entry field while using custom submission query

### ISSUE THREAD

**Issue by parwinderD4D** [verbb/formie#533]
**Description**
Hi Team,
What I am trying to do we have added Entry under the form which has a default value. This Entry show under From Submission on the backend.

So based on these submissions we are generating certificates. With the help of the submission query by following this [documentation ](https://verbb.io/craft-plugins/formie/docs/getting-elements/submission-queries#example) we fetch the submission data as mentioned in the documentation example. `{{ submission.title }}`  and its work properly.

But when i try to get Entry data  as mentioned below 
`{% if submission.assignedWebcast %}
{% set assignedWebcasts = submission.assignedWebcast.one() %}
{{ assignedWebcasts.title }}
{% endif % }`

Please check the attached screen-shots 

1. http://prntscr.com/1j2qmld / http://prntscr.com/1j2pxe9 [ Entry Field Assign on From  ]
2. http://prntscr.com/1j2oxoh  [ Backend Submission Screenshot ]
3. http://prntscr.com/1j2o57b  [  Error Screenshot ]

### Form settings
- Custom Form Templates: Yes for submission data

**Additional info**
- Plugin version: 1.4.9
- Craft version: 3.6.17
- Multi-site: Yes

Looking Forwards 
Thanks

**Comment by engram-design** [comment]
Just a quick note - it looks like there's a casing difference that might be the issue. If your field settings, your field handle is `assignedwebcast` and in your templates you're trying to use `assignedWebcast` - note the difference in casing. Can you confirm?

**Comment by parwinderD4D** [comment]
oh, you are right, I did a silly mistake. My bad😱 

It's working fine now.

Thank you for your help
