### ISSUE TITLE
Can't add forms - Return value of verbb\formie\elements\Form::getDefaultStatus() = null

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#534]
**Description**
1. Installed formie locally with no issues - pushed to dev and it didn't show up on the nav in cp.
_NB - no errors were through during deployment otherwise deployment script would have rolled back the changes and notified us._
2. Manually tried to install again via the cl and it complained about existing formie tables.
3. Enabled changes on dev to view the plugins - plugins page said it formie wasn't installed.
4. Manually deleted all the formie tables from the DB
5. Manually installed the plugin again (`./ craft plugin/install formie`) 
6. The plugin now displays in the nav. 
7. Adding a form throws an error - see below
7. Refreshing the forms page the form is listed, but clicking on the form to edit throws an error 

Error log has the following:
```
2021-08-05 13:16:09 [-][1][htc5c5cn5m63d76mmsumefod60][error][TypeError] TypeError: Return value of verbb\formie\elements\Form::getDefaultStatus() must be an instance of verbb\formie\models\Status, null returned in /home/site/vendor/verbb/formie/src/elements/Form.php:447
Stack trace:
#0 /home/site/vendor/yiisoft/yii2/base/Component.php(140): verbb\formie\elements\Form->getDefaultStatus()
#1 /home/site/vendor/craftcms/cms/src/base/Element.php(1533): yii\base\Component->__get()
#2 /home/site/vendor/craftcms/cms/src/helpers/Template.php(90): craft\base\Element->__get()
#3 /home/site/storage/runtime/compiled_templates/a1/a19781b3297128d6dc6ea3da29d1e3c82d930ec6f5d0b9d25bc3e2e1a137f2b3.php(65): craft\helpers\Template::attribute()
#4 /home/site/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b9a28d1b2eef5a4c2ec35d27a092a5e2b729aa28a24dbe43cd1d202bf7c41036->doDisplay()
#5 /home/site/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#6 /home/site/storage/runtime/compiled_templates/e2/e2e290cd4d87289194f7cb664130868859e923e492e14b66d209d9d35c6279b4.php(239): Twig\Template->display()
#7 /home/site/vendor/twig/twig/src/Template.php(182): __TwigTemplate_7e8858631cee2b9569202b4c1f6c834cd7fbd8f3ce87bad1436ca1860a628546->block_content()
#8 /home/site/storage/runtime/compiled_templates/2e/2e782e3b4f8df0b386764db0d0da4565135e6f15df1549168802a8339109b4ab.php(497): Twig\Template->displayBlock()
#9 /home/site/vendor/twig/twig/src/Template.php(182): __TwigTemplate_b870cad9d5429877c800dd9f2adc19ff7e6e0dfb8706aed22d90681d3e4645b7->block_main()
#10 /home/site/storage/runtime/compiled_templates/2e/2e782e3b4f8df0b386764db0d0da4565135e6f15df1549168802a8339109b4ab.php(316): Twig\Template->displayBlock()
#11 /home/site/vendor/twig/twig/src/Template.php(182): __TwigTemplate_b870cad9d5429877c800dd9f2adc19ff7e6e0dfb8706aed22d90681d3e4645b7->block_body()
#12 /home/site/storage/runtime/compiled_templates/4a/4a9f1e12a1f1a783e5e3b81c0a7d4760894c16a411e95c763fef44108211e099.php(90): Twig\Template->displayBlock()
#13 /home/site/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d2f13f7274188c83ee4213c89005dd357dd614e593551ee55a5bbf120c0345b2->doDisplay()
#14 /home/site/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#15 /home/site/storage/runtime/compiled_templates/2d/2d9193e779bbc98d3f5a4457d7a6c2f3172efb1155c8d2d2ace96ffb6fd1fb49.php(56): Twig\Template->display()
#16 /home/site/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c389f7d100d49a667ed42a3594ad999dc0e759ae2adbe2688624baa4f2c9885e->doDisplay()
#17 /home/site/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#18 /home/site/storage/runtime/compiled_templates/2e/2e782e3b4f8df0b386764db0d0da4565135e6f15df1549168802a8339109b4ab.php(158): Twig\Template->display()
#19 /home/site/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b870cad9d5429877c800dd9f2adc19ff7e6e0dfb8706aed22d90681d3e4645b7->doDisplay()
#20 /home/site/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#21 /home/site/storage/runtime/compiled_templates/e2/e2e290cd4d87289194f7cb664130868859e923e492e14b66d209d9d35c6279b4.php(61): Twig\Template->display()
#22 /home/site/vendor/twig/twig/src/Template.php(405): __TwigTemplate_7e8858631cee2b9569202b4c1f6c834cd7fbd8f3ce87bad1436ca1860a628546->doDisplay()
#23 /home/site/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#24 /home/site/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#25 /home/site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#26 /home/site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#27 /home/site/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render()
#28 /home/site/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate()
#29 /home/site/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate()
#30 /home/site/vendor/verbb/formie/src/controllers/FormsController.php(120): craft\web\Controller->renderTemplate()
#31 [internal function]: verbb\formie\controllers\FormsController->actionEdit()
#32 /home/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#33 /home/site/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#34 /home/site/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#35 /home/site/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#36 /home/site/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#37 /home/site/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#38 /home/site/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#39 /home/site/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#40 /home/site/web/index.php(22): yii\base\Application->run()
#41 {main}
```

**Additional info**
- Plugin version:  1.4.12
- Craft version: Craft Pro 3.6.10
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Strange, normally in those scenarios as step 2 I try and run `./craft project-config/apply --force`. It sounds like the plugin was installed, but the project config wasn't applied correctly.

I would hazard a guess that you have no default statuses anymore, because of this failed install. Unfortunately, these are only added upon plugin install, so you'd really have to install the plugin again. But they also might be missing from your project config yaml files - it's hard to say without looking at your project files. If they did exist as yaml files, then applying the project config should kick it into gear.

My solution would be :
1. Uninstall locally
2. Run `./craft project-config/rebuild` then push to production
3. Run `./craft project-config/apply --force` on production
4. Verify plugin is uninstalled and DB tables are gone.
5. Install locally
2. Run `./craft project-config/rebuild` then push to production
3. Run `./craft project-config/apply --force` on production

**Comment by anchovy** [comment]
Hi @engram-design - thanks for the prompt response as always!

I did originally re-apply everything; didn't make any difference, but I'veg ot it working; I did a bit of a mixture as I didn't want to lose the forms I'd set up locally... 

so I...

Dev (for testing)
1. ran `git status` to ensure everything was clean
2. uninstalled via the command line: `./craft plugin/uninstall formie`
2. installed via the command line: `./craft plugin/install formie`
3. verified it worked & I could add/edit forms
4. ran `git checkout` on all the changed config/project files.
5. ran `git status` to check everything was clean
6. ran `git pull` just to make sure there would be no issues for the next release.

Once I was happy on DEV I did the same on LIVE and it's all working now.

Thanks
Ben

**Comment by engram-design** [comment]
Thanks for confirming @anchovy I'll keep an eye on it, but its all mostly down to Craft's handling on the project config. Sounds like production just got out of sync pretty badly someone - it happens to us pretty often.

Just ensure you pull your production database down to dev and rebuild PC just to be safe!
