### ISSUE TITLE
Repeater - Minimum instances

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#54]
**Description**

Setting the "Minimum instances" setting in a repeater field to "0" still renders a first instance of that field on form load.

Expected behaviour would be that if the Minimum instance was "0", then it would be hidden on load, and only display if added by the user.

P.S amazing plugin!

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.1.1.1
- Craft version: 3.4.15
- Multi-site: No

<img width="1107" alt="Screenshot 2020-08-14 at 13 26 17" src="https://user-images.githubusercontent.com/18699249/90249132-d9610780-de31-11ea-8fcf-5c6574e1d798.png">
<img width="1472" alt="Screenshot 2020-08-14 at 13 27 45" src="https://user-images.githubusercontent.com/18699249/90249363-3957ae00-de32-11ea-85b4-1a9c05cdf90b.png">

**Comment by engram-design** [comment]
Fixed in [1.1.2](https://github.com/verbb/formie/releases/tag/1.1.2)
