### ISSUE TITLE
Sending form notification task throwing error: Calling unknown method: craft\\console\\Request::getBodyParam()

### ISSUE THREAD

**Issue by mark-adigital** [verbb/formie#542]
Hey - just hoping you may be able to help resolve this error.

### Context/error encountered

We're using Formie 1.4.13 on a single-site Craft CMS 3.6.10 install (however this error was also present with an older version of Formie). We're also using the [AsyncQueue plugin v. 2.3.0](https://github.com/ostark/craft-async-queue/blob/master/README.md) to handle the execution of tasks.

The tasks to send notifications hang for quite a while before failing with the error: 

> Calling unknown method: craft\\console\\Request::getBodyParam() /srv/users/becbc/apps/becbc/vendor/yiisoft/yii2/base/Component.php:301"

### Form settings

Our forms are all single page submit via AJAX with client side validation, and we aren't using custom templates.

Thanks!

**Comment by mark-adigital** [comment]
Hopefully you've not wasted too long looking into this - upon further investigation I think the issue is with the AsyncQueue plugin and not Formie. Sorry about that.

**Comment by engram-design** [comment]
Interesting, thanks for reporting back! I'll keep an eye on things - I can't say I'm 100% across what the AsyncQueue plugin does. Just let me know if it's an issue!

**Comment by mark-adigital** [comment]
Thanks Josh - got to the bottom of it in the end, I'd written a module that was where the `getBodyParam()` method was being called. To make the task work with the Async plugin, I had to add a conditional around that to check if it was a console request.
