### ISSUE TITLE
Field type 'recipient' not saving values

### ISSUE THREAD

**Issue by stevefloat** [verbb/formie#544]
When using the field type of 'Recipient', the value of the submission isn't being saved.

I've just updated to version 1.4.13. Previously, when using version 1.3.25, this field worked well and I saw no issues.

I've tested using this field's Display Type as a Dropdown (preferred option) and Radio buttons however in both instances the value of the field is not being saved in the user's submission.

Furthermore, I'm currently testing Google Sheets integrations and this seems to break the Google Sheet integration. If I choose not to include the 'Recipient' type field the data is passed correctly to the Google Sheet. However if I try and include the 'Recipient' field value, the data never appears in the sheet.

Thanks in advance for your help,
Stephen

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.13
- Craft version: 3.6.18
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.4.14](https://github.com/verbb/formie/releases/tag/1.4.14)

**Comment by stevefloat** [comment]
Lovely, thanks.
