### ISSUE TITLE
GraphQL: String cannot represent value: instance of multi-line text

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#545]
**Description**
I'm trying to run a query which includes a multi-line text field. The query works fine without the multi-line text field, but when I include it, I get the error `String cannot represent value: instance of multi-line text`

**Steps to reproduce**

This works:

```
query adminCourseRegistrations() {
  registrations:formieSubmissions(form: "courseRegistration") {
    id
    ... on courseRegistration_Submission {
        registrationKey
    }
  }
}
```

This doesn't: 
```
query adminCourseRegistrations() {
  registrations:formieSubmissions(form: "courseRegistration") {
    id
    ... on courseRegistration_Submission {
        registrationKey
        notes
    }
  }
}
```

**Additional info**
- Plugin version: 1.4.13
- Craft version: 3.6.16

**Comment by engram-design** [comment]
I can't seem to replicate this unfortunately, although I am testing on Craft 3.7.7. I'll back-track and test further.

What kinda of field would `registrationKey` be?

**Comment by daltonrooney** [comment]
Well that’s probably good news then. We’re planning to upgrade Craft to 3.7.x soon anyway, maybe that’s part of the problem. I’ll give you an update as soon as I have more info. 

The `registrationKey` field is just a plain text field. We have a bunch of other fields on the form too (all working in GraphQL queries), but I simplified it for this example.

**Comment by engram-design** [comment]
Hmmm, so testing with:

```
{
    submissions (form: "multiLine") {
        id

        ... on multiLine_Submission {
          single
          multi
        }
    }
}
```

```
{
  "data": {
    "submissions": [
      {
        "id": "5742",
        "single": "Some single line text",
        "multi": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. \r\n\r\nIt has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \r\n\r\nIt was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      }
    ]
  }
}
```

**Comment by engram-design** [comment]
Don't suppose you've got any update on this? I'd hate to push you to Craft 3.7.x without knowing that'll for sure fix the issue, but can't seem to replicate it on my end.

**Comment by daltonrooney** [comment]
I'm testing an update to 3.7.11 but still getting a related error:

query:

```
{
  formieSubmission(id:31285) {
    id
    ... on courseRegistration_Submission {
      notes
    }
  }
}
```

response:

```
{
  "errors": [
    {
      "message": "String cannot represent value: []",
      "extensions": {
        "category": "graphql"
      }
    }
  ],
  "data": {
    "formieSubmission": {
      "id": "31285",
      "notes": null
    }
  }
}
```

The error seems to be the same whether the notes field has a value or not. The field does export to CSV from the submissions admin page with no problems.

**Comment by engram-design** [comment]
Are you querying this from the graphiql explorer in the control panel, or through your actual front-end code?

query:
```
{
  formieSubmission(id:5853) {
    id
    ... on gqlMulti_Submission {
      multi
    }
  }
}
```

response:
```
{
  "data": {
    "formieSubmission": {
      "id": "5853",
      "multi": ""
    }
  }
}
```

I'll assume you've cleared your caches, including the GQL cache?

Are you able to send through your settings for the `notes` field - just in case there's anything in there that might change the behaviour?

**Comment by engram-design** [comment]
Closing for now. Feel free to get in touch with me via email or Discord if we need to figure this one out!
