### ISSUE TITLE
Failed to send notification email with recipient field

### ISSUE THREAD

**Issue by mark-adigital** [verbb/formie#546]
Hi - I'm hitting an issue where the to emails for a notification include a recipient field along with the system email and one static address. The task to send the notification throws this error:

`Failed to send notification email: {"error":"Notification email parse error for “To: {systemEmail},{field.descriptionOfPlannedUse.hirePoint},email@address.com”. Template error: “Address in mailbox given [id:0] does not comply with RFC 2822, 3.6.2.”/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355"}.`

I've also tried removing the other addresses from the notification and the error persists, so I don't think that's the cause of the issue.

The form is single page, submits with a page reload, uses client side validation and no custom templates.

Craft is 3.7.8, and Formie is 1.4.13. The install is not multi-site.

**Comment by engram-design** [comment]
Should be fixed in [1.4.14](https://github.com/verbb/formie/releases/tag/1.4.14)

**Comment by mark-adigital** [comment]
Great - thanks!
