### ISSUE TITLE
Generate Dynamic PDF Based on From Submission Data

### ISSUE THREAD

**Issue by parwinderD4D** [verbb/formie#547]
**What are you trying to do?**
Hi  Team,
Whats we trying to do, Users have to fill a form and after submission, we have to provide an option to download a  PDF Certificate.

**What's your proposed solution?**
We have two options here to make it workable
1. We can attach the PDF Certificate with the confirmation notification email. This PDF will be generated based on the info submitting by the users such as  First and Last name, Address,  License Number,  etc. 

2. In the 2nd option, once the user submits the form it will redirect to a custom link which includes the form submission id in the query string for E.g: **www.example.com/thanks-message/?submission-id=234**  where we will display a Thanks message along with the download certificate link. To make it work we need a form submission id, as you can see in the example URL. Based on that id we can easily get submission data by using craft DB query as mentioned under the [documentation](https://verbb.io/craft-plugins/formie/docs/getting-elements/submission-queries#id).

So could you please advise how I can do that in both cases?
For the 2nd case, we have the option of the redirect on the custom page which is present under the form setting but the problem is we don't have option to pass recently created from submission id as query string which makes 2nd option possible 

If you have any idea to make our functionality workable please let me know.

Looking Forward.

Parwinder

**Comment by engram-design** [comment]
I will say having a PDF as an attachment in on the roadmap - https://github.com/verbb/formie/issues/204 - but that's slightly unrelated to this. 

For 1. You can achieve this through [event hooks](https://verbb.io/craft-plugins/formie/docs/developers/events#email-events), generating the PDF yourself and attaching it to the email.

As for the redirect, you can achieve that at the moment in a few ways.

- Set the "Redirect URL" in the behaviour tab for a form: `/thanks-message?submission-id={id}`
- Do the same thing in your [templates](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-forms#override-form-settings)

Once on `thanks-message` template, you'll do a submission element query to fetch the submission, and build the template as required.

**Comment by parwinderD4D** [comment]
Thanks for your suggestions. 2nd option is working for me  `/thanks-message?submission-id={id}`
