### ISSUE TITLE
Access Field Settings for Field in Group

### ISSUE THREAD

**Issue by jimirobaer** [verbb/formie#549]
**Description**

I cannot access the fields in a group when I want to override the settings of some fields with `setFieldSettings`.

I would do this for normal fields, as is documented:
```
{% do form.setFieldSettings('testField', {
    name: 'string'
}) %}
```

... which does not work (and I have tried variants on this) with a Group field:

```
{% do form.setFieldSettings('testGroup', {
    testField: {
        name: 'string'
    }
}) %}
```

Dumping the contents from the Group fields shows that the fields reside in a protected variable `_fieldLayout`, which I can't access using the documented syntax.

```
...

["_fieldLayout":"verbb\formie\fields\formfields\Group":private]=>
  object(verbb\formie\models\FieldLayout)#2497 (16) {
    ["_pages":"verbb\formie\models\FieldLayout":private]=>
    NULL
    ["_fields":"verbb\formie\models\FieldLayout":private]=>
    array(1) {
      [0]=>
      object(verbb\formie\fields\formfields\Phone)#2487 (57) {
        ["countryEnabled"]=>
        bool(true)
        ["countryCollapsed"]=>
        bool(true)
        ["countryShowDialCode"]=>
        bool(true)
        ["countryDefaultValue"]=>
        string(0) ""
        ["countryAllowed"]=>
        array(0) {
        }
        ["searchable"]=>
        string(1) "1"
        ["_isFresh":"craft\base\Field":private]=>
        NULL
        ["_errors":"yii\base\Model":private]=>
        NULL
        ["_validators":"yii\base\Model":private]=>
        NULL
        ["_scenario":"yii\base\Model":private]=>
        string(7) "default"
        ["_events":"yii\base\Component":private]=>
        array(0) {
        }
        ["_eventWildcards":"yii\base\Component":private]=>
        array(0) {
        }
        ["_behaviors":"yii\base\Component":private]=>
        array(0) {
        }
        ["id"]=>
        string(2) "96"
        ["dateCreated"]=>
        object(DateTime)#2422 (3) {
          ["date"]=>
          string(26) "2021-08-19 16:02:50.000000"
          ["timezone_type"]=>
          int(3)
          ["timezone"]=>
          string(15) "Europe/Brussels"
        }
        ["dateUpdated"]=>
        object(DateTime)#2468 (3) {
          ["date"]=>
          string(26) "2021-08-19 16:28:01.000000"
          ["timezone_type"]=>
          int(3)
          ["timezone"]=>
          string(15) "Europe/Brussels"
        }
        ["groupId"]=>
        NULL
        ["name"]=>
        string(5) "Phone"
        ["handle"]=>
        string(9) "testField"
...
```

**Steps to reproduce**
1. Create a Field Group in Formie's editor
2. Use the documented syntax for `setFieldSettings` on a Group, which does not work.

There's also no documentation for 'Group' under https://verbb.io/craft-plugins/formie/docs/developers/field#field-settings.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version:
- Craft version:
- Multi-site: Yes or No

**Additional context**

I'm using the Override Field Settings feature to translate fields with strings. This works fine for other fields.

**Comment by jimirobaer** [comment]
Temporarily fixed by entering the Static Message Translations directly as labels on each grouped field in the Formie editor. This works, but I prefer to change them in my templates because it looks a little nicer to clients.

**Comment by engram-design** [comment]
Yep, this is somewhat of a known issue for complex fields like Group and Repeater. This will be addressed in https://github.com/verbb/formie/issues/478

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)

**Comment by bavocorteville** [comment]
@engram-design How does this work exactly? Can't find it in the docs.
The following code doesn't seem to work.

```twig
{% do form.src.setFieldSettings('group', {
    'field': {
        name: 'Overridden Label',
    }
}) %}

{% do form.src.setFieldSettings('group["field"]', {
    name: 'Overridden Label',
}) %}
```

**Comment by engram-design** [comment]
I thought that was documented somewhere, but seems not.

```
{% do form.setFieldSettings('group', {
    fields: {
        myFieldHandle: {
            name: 'Overridden Label',
        },
    },
}) %}
```
