### ISSUE TITLE
Submissions Export not fully working

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#55]
**Description**
Apologies as I know I have emailed separately but I thought I would log more info here.

I am trying to export data using the 'Export' button in Submissions. The data in the downloaded file is not formatted correctly and includes code. More importantly, it is also missing data.

This applies to all download formats JSON, CSV, XML.

In my screenshot below it shows x3 peoples details, the first lot are just normal fields and then theres two people in the repeater field. Only the people in the repeater field are included in the export. I have included the exported data from the same submission so you can compare.

<img width="1062" alt="Screenshot 2020-08-14 at 15 34 00" src="https://user-images.githubusercontent.com/18699249/90260679-c1927f00-de43-11ea-84cc-a176ab3d0c99.png">

[elements (4).csv.zip](https://github.com/verbb/formie/files/5075153/elements.4.csv.zip)
Link to Google Sheet of export https://docs.google.com/spreadsheets/d/1YQJdEBel83P2ILNtm0Wh37uQQEwyPpHi2D2IVYXdjDc/edit?usp=sharing

**Steps to reproduce**
1. Submissions
2. Export
3. Export Type: Expanded
4. Format CSV / XML / JSON

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method:  Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.1.1
- Craft version: 3.4.15
- Multi-site:  No

**Comment by mark-chief** [comment]
Another screenshot showing a repeater field "`testRepeater`", I'd expect the export to handle the repeater field differently by splitting each field in its own column, instead of including JSON(?) in a single cell. So `testName` and `testNumber` would have their own columns in the CSV.

I cant see the current format as being manageable by any systems trying to consume the data that is exported.

<img width="870" alt="Screenshot 2020-08-14 at 16 16 56" src="https://user-images.githubusercontent.com/18699249/90264882-b17d9e00-de49-11ea-99f7-eea932a2cb01.png">

The problem lies with repeater fields and fields with subfields like name and Address etc..

Thanks

**Comment by engram-design** [comment]
Thanks for letting me know about this, actually completely forgot about this, and wasn't sure how important it was to people!

Should be much improved in [1.1.2](https://github.com/verbb/formie/releases/tag/1.1.2).

For fields that have multiple rows (Table/Repeater) new lines in the export will be created.
