### ISSUE TITLE
[v1.4.14] Key "dataId" for array with keys "id, labelId, field, renderOptions" does not exist.

### ISSUE THREAD

**Issue by cherrykoda** [verbb/formie#551]
**Description**

Upgrading to latest Formie causes error. Composer install after deleting vendor did not help.

**Steps to reproduce**
1. Update to Formie 1.4.14
2. Browse to page containing a form

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.14
- Craft version: Craft Pro 3.7.10
- Multi-site: No

**Additional context**
![image](https://user-images.githubusercontent.com/3789834/130394336-c20701ac-3661-4090-8722-39d1e27e2c4c.png)

**Comment by cherrykoda** [comment]
I downgraded to v. 1.4.12 and had the same issues, I did narrow it down to the 'name' fields. I've replaced them with plaintext for now and am sticking on 1.4.12 until I know its safe to upgrade.

**Comment by engram-design** [comment]
I can't seem to replicate this. The new `dataId` was added to all fields - https://github.com/verbb/formie/commit/cd8b80a83d8422ee0d4060ea7a685bc5d086a992#diff-ba26d5dbf9dcd3281c9b0b3c16f822eff1d2943c2134518d4ecea26d10907be4

I note you mention you have custom template setup, but your screenshot resolves to formie's default templates. Are you overriding the `field.html` template? If so, you will likely need to incorporate the change in the template as above

**Comment by engram-design** [comment]
Are you able to confirm the above @cherrykoda ?

**Comment by cherrykoda** [comment]
confirmed, thank you!
