### ISSUE TITLE
PHP Compile Warning

### ISSUE THREAD

**Issue by robinbraibant** [verbb/formie#555]
**Description**
When submitting a form, I get the following warning:  _PHP Compile Warning – yii\base\ErrorException
Private methods cannot be final as they are never overridden by other classes_ 
This warning gets thrown by hoa/stream/Stream.php. Seems like there is something wrong with the PHP 8.0 compatibility.

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.14
- Craft version: 3.7.10
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
If you're on PHP 8, this is related to https://github.com/verbb/formie/issues/525#issuecomment-886756395

**Comment by engram-design** [comment]
There is a [PR](https://github.com/hoaproject/Stream/pull/30) to fix this but not looking like it'll be merged.

If you're unable to downgrade from PHP 8, you should be able to get around this issue by adding the following to your `composer.json`.

```
"require": {
    "hoa/stream": "dev-1.17.02.21-php8 as 1.17.02.21"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/mathroc/Stream"
}],
```

I'd love to include this in Formie's `composer.json` file, but these changes will only work in the root `composer.json` file - https://stackoverflow.com/questions/35699807/nested-dependencies-and-private-repositories-with-composer

**Comment by robinbraibant** [comment]
Thank you for the feedback!

**Comment by engram-design** [comment]
This will also be addressed in https://github.com/verbb/formie/issues/582 with the switch out from the `hoa/ruler` project.
