### ISSUE TITLE
reCAPTCHA not loading

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#560]
**Description**
I've added the reCAPTCHA integration to a site and form, but the logo doesn't appear in the bottom right as it is set. 
In the console there's the following error:
`Uncaught TypeError: Cannot read property 'getAttribute' of undefined`
Which points to line 991 in recaptcha-v3.js:
`var o = this.$placeholder.getAttribute("data-recaptcha-id");`

A wild guess is that the attribute isn't being added to the form, but not sure how it should be?

I have the following markup:
```
{% set attributes = {
            id: form.formId,
            method: 'post',
            data: {
                config: form.configJson,
            },
        } %}

        <form class="form" {{ attr(attributes) }}>
```
... which I assume would add the attrib's in? I can see the site key and secret are being injected into the <form> element on page load.

**Steps to reproduce**
1. Enable reCAPTCHA for Formie
2. Enable reCAPTCHA for custom form

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.5
- Craft version: Pro 3.6.10
- Multi-site: No

**Comment by engram-design** [comment]
If you're custom rendering, you'll need to include the template hook for captcha integrations to output the placeholders.

```
{% hook 'formie.buttons.before' %}
```

Which is stated here - https://verbb.io/craft-plugins/formie/docs/template-guides/custom-rendering#captchas

These placeholder HTML elements need to be attached to the form's HTML so that inline captchas work, and multiple forms (and captchas) on a page work.

Let me know if that helps?

**Comment by jamiematrix** [comment]
Thanks @engram-design !

That looks to have done the trick. I had turned on honeypot, which (without that line of Twig) stopped all forms being submitted despite the direct working.

I was sure I saw something about adding an extra line in for custom rendering, but completely missed that section of the docs (I was looking at everything Form related).

**Comment by engram-design** [comment]
No problem I'll try and add this in a few more spots in the docs to make it more obvious!
