### ISSUE TITLE
Send email notification/s upon submission

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#564]
**Description**
In my limited knowledge of Craft plugins, the default behaviour is the queue manager is only processed when admin pages are accessed (I was able to make a custom plugin send emails out of office hours). Assume this to be the case with Formie? A client has queried why when the checked the submissions list there were submissions but no emails had been received at the same time. It was only when they checked the submissions that the emails were received. 

I'm guessing this is an intended behaviour following Craft's methods, and isn't likely to change?

**Steps to reproduce**
1. Fill out form to send notification
2. Don't visit admin pages

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**

- Plugin version: 1.4.5
- Craft version: Pro 3.6.10
- Multi-site: No

**Comment by jamiematrix** [comment]
May have found a config setting to do just as we're after https://verbb.io/craft-plugins/formie/docs/get-started/configuration#submissions

**Comment by engram-design** [comment]
Yep, so email notifications use Craft’s queue system. This is for good UX when people submit a form, that they don’t wait for the email to be delivered (which is notoriously slow) and any integrations that are fired which again might also be slow. However, by default, Craft’s queue will only be run when you visit the control panel.

Have a read through the docs - https://verbb.io/craft-plugins/formie/docs/feature-tour/email-notifications#sending-emails that state this behaviour, and you can turn off running things via the queue via the Config settings - https://verbb.io/craft-plugins/formie/docs/get-started/configuration - or through Formie’s settings in the control panel. I’d strongly advise to look at keeping this on, and using a cron job, or daemon to run the queue as suggested in this article - https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

It's frustrating how Craft's queue system works, but the benefits of using it are much better for users on your site. We often see 10s **minimum** delay when using SMTP email providers, and 3-5s for third-party providers like SendGrid or Mailgun. Not to mention integrations which are slower and follow the same scenario.

Having failed jobs in the queue is also nicer when things _do_ fail from time to time, that you don't need to wade through log files, and they're easy to retry.

**Comment by jamiematrix** [comment]
I thought that may be the case, and I've been wondering how to word it to the client with the benefits of using the queue system - my guess is they don't see it as a job the site is doing, its 'just sending an email'. I'm pretty sure they'll prefer to bypass it. If there are performance issues down the line I could change to use a CRON job instead.

**Comment by engram-design** [comment]
For sure, you’re totally welcome to bypass the queue entirely and have it act ‘normally’. We’ve just found it to have a noticeable enough delay to frustrate some users.

See how you go!

**Comment by jlabs** [comment]
Just visiting this again as I've had another client with the same issue. Only this time the email notification took 5 days to come through.

I can see in Formie that the submission was on 25th September at 1430, but the notification sent at 2am on 30th September. The site is fairly active, so I'd expect the queue would have triggered earlier than 5 days. 

I've checked SMTP and run a mailer test - that came through immediately.

**Comment by engram-design** [comment]
@jlabs Again, you don't _have_ to use the queue to send out emails, but we strongly recommend it to the point that it's enabled by default. Most, if not all mailers are slow and lead to a bad UX where the user is waiting for a form submission to finish.

It's up to you to setup an efficient and timely queue-processing mechanism, of which there are [plenty of options](https://verbb.io/craft-plugins/formie/docs/get-started/troubleshooting).

By default Craft's queue is only run when you visit the control panel, so in your case, there was no control panel access in 5 days.
