### ISSUE TITLE
Ability to create submission via mutations

### ISSUE THREAD

**Issue by mylesthedev** [verbb/formie#57]
**What are you trying to do?**
Create a submission using GraphQL mutations.

**What's your proposed solution?**
Add support for mutations like sections/entries have.

**Comment by engram-design** [comment]
Added in [1.1.4](https://github.com/verbb/formie/releases/tag/1.1.4)

[See docs](https://verbb.io/craft-plugins/formie/docs/developers/graphql#mutations).

**Comment by mylesthedev** [comment]
Legend, I owe you a beer for that!
