### ISSUE TITLE
ActiveCampaign Email Integration Tags / Form id

### ISSUE THREAD

**Issue by aloco** [verbb/formie#571]
**What are you trying to do?**
We would like to set one or more tags to contacts which are signed up via the Active Campaign Integration so we know where the contacts are coming from.
We would like to set a form id which is sent to Active Campaign which helps in triggering double opt in and other stuff. https://elementor.com/help/activecampaign-elementor-integration/

**What's your proposed solution?**
Besides selecting the list, tags can be selected or created, similar to Craft CMS tags. In addition, you can enter the form id or select from an existing form from Active Campaign

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`. Be sure to also update your list, by hitting the refresh button in the Integrations settings for the form.

Do also note that selecting existing values like tags, or entering in arbitrary text is currently not supported, but it's on our roadmap to add support all of those things.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
