### ISSUE TITLE
Allow creating submissions from control panel

### ISSUE THREAD

**Issue by michaelhue** [verbb/formie#575]
**What are you trying to do?**
A client would like to be able to add new submissions and submission drafts from inside the Control Panel. 

**What's your proposed solution?**
Saving incomplete drafts is already possible when editing submissions. The only thing that's missing is a "New submission" button in the element index and the matching controller action.

**Additional context**
I went ahead and implemented a simple workaround as a custom module. It consists of:
- A controller action to save an empty submission.
- An asset bundle providing JS code to extend the `Craft.Formie.SubmissionIndex` for building the "New submission" button (adapted from Craft's `EntryIndex`). The button is currently only visible when a form is selected in the sidebar to keep it simple.
- I also added a `Submission::EVENT_AFTER_SAVE` listener to update a submission's title after each save. This is not needed but I wanted the Control Panel submissions to have meaningful titles once filled out.

The code is here, feel free to use anything you need:
https://gist.github.com/michaelhue/88ea58a18977e8be7e67d13a3b29b179

![Bildschirmfoto 2021-09-14 um 18 01 03](https://user-images.githubusercontent.com/31861/133294127-a802fafe-a0f2-4813-b7b9-2831c04b7337.png)

Thank you!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
