### ISSUE TITLE
Submission errors when the Submission Title Format is blank

### ISSUE THREAD

**Issue by andypullen** [verbb/formie#579]
**Description**
The error below is being returned for all of our forms that have blank Submission Title Format fields, instead of defaulting to the submission date/time.

Adding a title format fixes the issue.

The error that's returned is:
```
{
    "success": false,
    "submissionId": null,
    "currentPageId": "4363",
    "nextPageId": null,
    "nextPageIndex": 0,
    "totalPages": 1,
    "redirectUrl": "",
    "submitActionMessage": "Thanks for your submission. We'll be in touch shortly!",
    "errors": {
        "title": [
            "Title cannot be blank."
        ]
    },
    "errorMessage": "Couldn’t save submission due to errors."
}
```

### Form settings
Please pick from the options below.

- Multi-page form: N/A
- Submission Method: both
- Client-side Validation: both
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.16
- Craft version: 3.7.13
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.4.17](https://github.com/verbb/formie/releases/tag/1.4.17)
