### ISSUE TITLE
Undefined class constant 'EVENT_REGISTER_GQL_MUTATIONS'

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#58]
**Description**
Undefined class constant 'EVENT_REGISTER_GQL_MUTATIONS'

**Steps to reproduce**
1. Update Plugin to latest version

**Additional info**
- Plugin version: 1.1.5
- Craft version: 3.4.24
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Rookie error sorry, you'll need to downgrade to Formie 1.1.3, or upgrade to Craft 3.5+.

`composer require verbb/formie:1.1.3`

I'll fix those releases up shortly.

**Comment by mizmiz** [comment]
Thanks

**Comment by engram-design** [comment]
Fixed in [1.1.6](https://github.com/verbb/formie/releases/tag/1.1.6).
