### ISSUE TITLE
Replace abandoned `hoa/ruler` dependancy

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#582]
https://github.com/beberlei/assert looks suitable, active and maintained.

**Comment by leevigraham** [comment]
Came to request the same thing.

Here's what you're looking for: https://symfony.com/doc/current/components/expression_language/syntax.html

We've used a bunch in an online store for custom discounts:

All products by Audio-Technica:
    `"audio-technica" in product.brands`
3CS Outerwear products that are not Men's Pants or Snowboard Bags
    `"3cs-outerwear" in product.brands and "snowboard-pants-mens" not in product.categories and "snowboard-bags" not in product.categories`
Rome Snowboard Bindings with a cost price greater than $200
    `"rome-snowboards" in product.brands and "snowboard-bindings" in product.categories and product.cost_price > 200`
Specifically the Boardworld Beanie and Socks
    `product.url_title in ["boardworld-beanie-black", "boardworld-premium-snowboard-socks"]`

**Comment by engram-design** [comment]
Oooh, good one! I've been on the search for alternatives, but certainly want to pick something more reliable. I'll give it a run through our tests to see if it'll be suitable.

So long as it allows for custom validators, it should suit.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
