### ISSUE TITLE
Pass custom fields to Formie

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#59]
We use Sprout forms now and would like to switch to Formie.
We have a page builder in Craft which has a form block. There you can choose a form and add e-mail adresses in a plain text field. In Sprout, we pass those e-mail addresses to the form with the `addFieldVariables()` function.

Is something like that possible in Formie?

**Comment by engram-design** [comment]
I've not even seen `addFieldVariables()` and we've been using Sprout Forms for years. Would you just use it like:

```
{% do craft.formie.addFieldVariables({ formieFieldHandle: "Some Value" }) %}
```

And then it would populate the `formieFieldHandle` field in your form, with whatever you provide? If so, happy to add that as a feature.

Currently, you can only achieve this right now with JS:
```
{% js %}
    document.querySelector('#formie-form-1 .my-field').value = 'Some value';
{% endjs %}
```

**Comment by TomDeSmet** [comment]
I think that's exactly what Sprout does :) Would be superb!

**Comment by engram-design** [comment]
Added in [1.1.6](https://github.com/verbb/formie/releases/tag/1.1.6). See the [docs](https://verbb.io/craft-plugins/formie/docs/template-guides/available-variables).
