### ISSUE TITLE
Custom validation rules throwing error when field not in form

### ISSUE THREAD

**Issue by rckywng** [verbb/formie#590]
**Description**
I have set custom validation rules in a module using the `SubmissionRulesEvent`. These rules work as expected when the fields exist in the form.

However, when I try to submit a form that does not include the fields set up in the custom rules, Craft is throwing an invalid field error (`craft\errors\InvalidFieldException`).

**Steps to reproduce**
1. Add custom rules to `SubmissionRulesEvent` (can be basic, like the ones in the examples: https://verbb.io/craft-plugins/formie/docs/developers/field#custom-validation).
2. Create a form that does not contain the fields set out in the custom rules.
3. Make a submission to the form.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Either
- Client-side Validation: Either
- Custom Form Templates: Yes, have styles turned off

**Additional info**
- Plugin version: 1.4.19
- Craft version: 3.7.14
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
This is somewhat expected behaviour, because this event is called at the end of the validation method, allowing you to have full control over the rules (add, remove, modify). But as you've pointed out, if you add a field-level validation for a field handle that doesn't exist on the submission, you'll get issues.

There's a few options:

1. I can make a breaking change to this event, where you must provide `fields` for your rules. Formie will then filter out and field rules that aren't valid for the submission.
2. A new event specifically for adding field validations, which does the same thing, just a new, separate event
3. You add handling for this yourself.

Let me know if you have a preference.

For option 3. you can add the following which would take care of this in your module.

```
Event::on(Submission::class, Submission::EVENT_DEFINE_RULES, function(SubmissionRulesEvent $event) {
    if ($fieldLayout = $event->submission->getFieldLayout()) {
        foreach ($fieldLayout->getFields() as $field) {
            if ($field->handle === 'emailAddress') {
                $event->rules[] = [['field:emailAddress'], 'required'];
            }
        }
    }
});
```

**Comment by rckywng** [comment]
I was thinking of adding some conditions to filter the fields as in your example, although I wasn't sure how to get the fields. So, I will use this as a temp solution at least, thanks.

I do think option 1 or 2 would be better as it is a bit clunky writing conditions for multiple fields. Option 1 sounds like it might be slightly better, but I am not sure whether you should introduce breaking changes for this. I would personally be happy with either, so I'll let you decide if you want to implement one of these.

As it is, the expected behaviour was unclear to me from the docs. So perhaps this could be explained a bit more.

**Comment by engram-design** [comment]
I'll give this some thought. I've added some clarifications to the docs in the meantime - https://verbb.io/craft-plugins/formie/docs/developers/field#custom-validation

**Comment by rckywng** [comment]
Thanks, I'll keep an eye on updates but happy with the current solution for now.

I did not notice changes to the docs. Not sure if they have been pushed.

**Comment by engram-design** [comment]
Looks like something went wrong with the docs sync. Should be updated now.

**Comment by engram-design** [comment]
Also fixed for the next release, where Formie will automatically filter out any fields you define that aren't valid. Probably a good idea to keep your checks in, as per the docs. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
