### ISSUE TITLE
Allow spam settings to be stored in database (not project config)

### ISSUE THREAD

**Issue by nickdunn** [verbb/formie#591]
**What are you trying to do?**
My client wants to use the spam keywords functionality. They often receive some targeted spam in waves which means they need to quickly react by adding keywords to block each attack. At the moment they can't do this because the spam keywords are stored in project config which requires source control and a site deployment to update, so they have to ask a developer to make the change.

It would be great if some config like this could be local to each database and available when allowAdminChanges is disabled.

**Comment by engram-design** [comment]
Yep, valid use-case! I'll see what I can do about consolidating those, though it might be a tad tricky in practice.

**Comment by engram-design** [comment]
Going to close this, as it's just too difficult (impossible) to implement to have these settings both in the project config and the database per-environment. At least, not without a breaking change for people using this feature right now.

**However** one workaround with this is that you can actually use Twig in the "Spam Keywords" setting. I'd suggest creating a multi-line text field in globals, and then include a reference to that. That way, you can provide your client access to edit the global.

For example, adding `{forms.spamKeywords}` in the "Spam Keywords" setting, where `forms` would be your Global Set and `spamKeywords` to be your multi-line field.

**Comment by nickdunn** [comment]
**Love** this idea, thanks!
