### ISSUE TITLE
Tag js type error

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#601]
**Description**
After updating to 1.4.20 we've been getting the following console error using tag fields

![Screen Shot 2021-10-14 at 5 35 49 pm](https://user-images.githubusercontent.com/21274925/137268687-bbfa23fc-2b10-4bea-a480-75778b02df2a.png)

Looks like this is due to this change, which I think should be `detail.options` instead https://github.com/verbb/formie/commit/1a8b4373c536a9543920083bbc937182ce5aec2a#diff-c8a2f98c383409dd823d09a5b2f7db302830167414e1841247438d61fd4f5851R38

**Steps to reproduce**
1. Update Formie to 1.4.20
2. Use a tag field on the front end

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.20
- Craft version: 3.7.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Ah, totally right that's a typo. Fixed in https://github.com/verbb/formie/commit/2773ca647a164a494032ec7afe582c79cc7fc4a1

**Comment by engram-design** [comment]
Fixed in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
