### ISSUE TITLE
formSubmitError() from onFormieValidate listener causes error message (fui-alert) to only appear briefly then disappear

### ISSUE THREAD

**Issue by bliswebagency** [verbb/formie#604]
**Description**

We are using JS client-side validation to prevent submission based on custom conditions.

We are using a listener for onFormieValidate, and a condition calls formSubmitError() if failed or submitForm() if successful. The call to submitForm() works but formSubmitError() will briefly flash the default fui-alert message, then suddenly the message disappears.

Placing the formSubmitError() in a setTimeout and a 1 second delay works as a temporary workaround, but is there a better way to address this?

**Steps to reproduce**
1. Create a form
2. Create validation listener similar to below

````
$form.addEventListener('onFormieValidate', function(e){
    submitHandler = e.detail.submitHandler;
    e.preventDefault();
       $('[name="fields[organisationName]"]').each(function(){
            if ($(this).val() !== "testValue"){
                $(this).addClass('fui-error');
                submitHandler.formSubmitError();
                // fui-alert appears on form
                alert('Error: failed validation. Blocking execution with popup.');
                // fui-alert disappeared
            } else {
                $(this).removeClass('fui-error');
                submitHandler.submitForm();
            }
        });
})
````

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.19
- Craft version: 3.7.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
I can't seem to replicate that (with 1.4.21), if you can double check my recording to ensure it's correct - https://d.pr/v/DOo9B3

Are you using any captchas on the form? I imagine you have "Validate Form on Submit" enabled, but do you also have "Validate When Typing" enabled?

**Comment by bliswebagency** [comment]
Thank you for looking into this. We will verify the status of captcha and the "validate when typing" field and let you know what we find.

**Comment by bliswebagency** [comment]
Thank you, enabling "validate when typing" and disabling "validate form on submit" fixes the disappearing fui-alert issue.

**Comment by engram-design** [comment]
I'll look into this.

You can also add custom validation rules via [registerFormieValidation](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#the-registerFormieValidation-event) which hooks into the validation library provided by [bouncer.js](https://github.com/cferdinandi/bouncer)
