### ISSUE TITLE
Multiline form fields can't exceed 255 characters

### ISSUE THREAD

**Issue by rickmerkelbach** [verbb/formie#61]
We're having some issues with forms that contain multiline fields and users trying to submit more than 255 characters with those fields. When setting the field's character limit the client-side validation seems to work fine (showing the amount of characters left) but it always returns an "Can't contain more than 255 characters" error on submission. The column in the database is set to a VARCHAR (255) so storing more characters would result in an SQL error if the server-side validation would pass.

**Steps to reproduce**
1. Add a multiline field to a form
2. Set the field's character limit to > 255 or no limit at all
3. Fill the form field with more than 255 characters
4. Submit the form

**Form settings**
- Multi-page form: No
- Submission Method: Ajax and Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.1.5
- Craft version: 3.5.5
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.1.6](https://github.com/verbb/formie/releases/tag/1.1.6) - you'll need to re-save any form that contains a multi-text field to make use of this change however.
