### ISSUE TITLE
Make field groups available in "existing fields" panel.

### ISSUE THREAD

**Issue by wolfwohlwend** [verbb/formie#612]
**What are you trying to do?**
We're grouping fields into field groups a lot. When building new forms it would be very handy if we could reuse these blocks exactly as we can with "Existing Fields".

**What's your proposed solution?**
List existing groups in the existing fields panel.

**Comment by engram-design** [comment]
The only reason you can't select group fields at the moment is that through this interface you can add synced fields, and a group field doesn't support being a synced field (yet).

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
