### ISSUE TITLE
Can't use the {submissionId} variable in the File Upload upload location subfolder path

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#629]
**Description**

I can't use the` {submissionId} `variable in the `File Upload` upload location subfolder path:
```
The Input file field’s Asset Location setting has an invalid subpath (“forms/{submissionId}”):
forms/{submissionId}
```

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.23
- Craft version: 3.7.18.2
- Multi-site: Yes

**Comment by engram-design** [comment]
I believe it should just be `{id}` instead of `{submissionId}`

**Comment by romainpoirier** [comment]
It works, thank you!
