### ISSUE TITLE
[FR] Add form settings to GraphQL FormInterface

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#63]
There are certain form settings which don't seem to be available in GraphQL queries. In particular I'm interested in the form success and error messages, but some of the appearance settings might be nice too.

```
 form {
   title
   handle
   successMessage
   errorMessage
}
```

What do you think?

**Comment by engram-design** [comment]
Added in [1.1.7](https://github.com/verbb/formie/releases/tag/1.1.7). See [docs](https://verbb.io/craft-plugins/formie/docs/developers/graphql#the-formSettingsInterface-interface)

**Comment by daltonrooney** [comment]
Amazing, thank you!
