### ISSUE TITLE
Add a visual indicator within the form builder for fields/groups with conditional logic

### ISSUE THREAD

**Issue by Kashkin** [verbb/formie#630]
**What are you trying to do?**
When editing forms, it is not obvious which fields contain conditional logic. A user needs to click on a field, navigate to the Conditions tab, and review the settings—for every field.

**What's your proposed solution?**
A visual indicator that appears in the back-end would make ongoing form management easier, particularly within distributed teams.

Something like the synced tag might work.
![image](https://user-images.githubusercontent.com/3699310/140256251-9aa22ead-1e58-4822-943f-56d1b2d91b01.png)

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
