### ISSUE TITLE
Improve the richtext Description within Agree field to support Entry and Asset links

### ISSUE THREAD

**Issue by Kashkin** [verbb/formie#632]
**What are you trying to do?**
Link to an Entry or an Asset, and use Craft's method for ensuring links don't break when an Element is renamed/moved, etc.

**What's your proposed solution?**
Potentially leveraging the work done in Vizy to provide this functionality.

![image](https://user-images.githubusercontent.com/3699310/140256883-f80902fc-8f66-4455-a909-cc5555dc232e.png)

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)

**Comment by ishetnogferre** [comment]
Is it possible to also include this functionality on the "instructions" field of dropdowns or checkboxes?

**Comment by engram-design** [comment]
@ishetnogferre Possibly, although instructions would need to be converted to rich text instead of their simple text at the moment. I'd suggest opening a new issue!
