### ISSUE TITLE
Submission Export as Excel XLSX

### ISSUE THREAD

**Issue by mini71** [verbb/formie#638]
Our clients usually expect exports as xslx.
Although it' not a big deal to explain them how to convert from csv, it would be a nice feature.

**Comment by engram-design** [comment]
No problem, I think that should be achievable. It'll still technically be a CSV file, but the file extension would be different.

**Comment by engram-design** [comment]
Unfortunately, looks like this won't be possible until a change in Craft core - https://github.com/craftcms/cms/discussions/10104

**Comment by christophpaster** [comment]
@engram-design - will this be reopened because of https://github.com/craftcms/cms/discussions/10104? Thank you very much!

**Comment by engram-design** [comment]
I don't believe any change will be needed on our end to support XLSX exports, as it's just a new format added for Craft.
