### ISSUE TITLE
Option to store submission data in a seperate database

### ISSUE THREAD

**Issue by mini71** [verbb/formie#639]
It would be helpful to meet GPDR if submissions could be stored in seperate database (config option).
We often create a dump from production to let devs work with real content. Such a dump should not contain any PII data.

**Comment by engram-design** [comment]
I'll say this is probably not going to be a possibility, but I'd have to research it a bit further. I don't believe Craft will allow us to store the content tables for submissions in a completely separate database.

**Comment by mini71** [comment]
Ah ok, I missed the point that you are using Crafts structure (of course ;-)
