### ISSUE TITLE
Multi-page custom submit labels not saving

### ISSUE THREAD

**Issue by siebird** [verbb/formie#640]
**Description**
Trying to change the default 'Submit' button label to 'Next Page' on all multi-page pages. Values are not being saved.

Single page forms are working when changing the value of the label.

**Steps to reproduce**
1. Create multipage form
2. Change submit button label value to something custom 'Next Page'
3. Click Apply
4. Save Form
5. Value is not saved

### Form settings
- Multi-page form: Yes
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.4.24
- Craft version: 3.7.20
- Multi-site: No

**Comment by engram-design** [comment]
I can't seem to replicate this sorry! Are you able to reproduce it consistently? Does the affect new forms, or editing existing ones? Do values get "reset" as soon as you close the model, as soon as you hit "Save" on the form, or just when you hard-refresh the page they've not persisted?

**Comment by siebird** [comment]
It's working now after I cleared the control panel resource cache.
