### ISSUE TITLE
Submissions by user..

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#642]
Is it posiblle  > if i create group of users > that will fill forms. 
when they login. to see only..  their sumbissions..

**Comment by engram-design** [comment]
Sure, you can query submissions owned by a user via `userId` - https://verbb.io/craft-plugins/formie/docs/getting-elements/submission-queries#userId

```
{% set submissions = craft.formie.submissions()
    .form('contactForm')
    .userId(1)
    .all() %}
```

But you must use the "Collect User" setting for form. This will record any user currently logged in as the owner of the submission when they make it. They also need to be logged in when they fill out the form.

If you don't want to use this, and would prefer to query based on a field like an email field, you can do that too.

```
{% set submissions = craft.formie.submissions()
    .form('contactForm')
    .myEmailField(currentUser.email)
    .all() %}
```
