### ISSUE TITLE
Add an option to change a forms default name attribute

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#65]
**What are you trying to do?**

It would be great to have an option to change a forms name attribute, eg from the default `name="fields[emailAddress]"` to `customname[emailAddress]`

**What's your proposed solution?**

Could potentially be passed as an option in the renderForm() function

**Additional context**

I'm trying to integrate Formie with a Craft Commerce project, and it seems like changing the name attribute to shippingAddress[] would allow for this. Would be very convenient, as we are using Formie for other forms on the site and loving the functionality

**Comment by engram-design** [comment]
Added in [1.1.8](https://github.com/verbb/formie/releases/tag/1.1.8)

You can now use `{{ craft.formie.renderForm(handle, { fieldNamespace: 'shippingAddress' }) }}` which should do the trick.

As a bonus, you can do the same thing for `renderPage` and `renderField`, if you want really fine-grained control.

**Comment by d-karstens** [comment]
Thank you, much appreciated!
