### ISSUE TITLE
Empty values for fields in groups, used in Integration payloads

### ISSUE THREAD

**Issue by PieterxJan** [verbb/formie#650]
**Description**
When using an integration to Zapier, the fields included in groups are always empty in the payload. 

**Steps to reproduce**
1. Create a form with fields in a group.
2. Activate a Webhook or Zapier integration
3. Either dump your payload to a service like webhook.site or var_dump it in `generatePayloadValues()` 

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Both
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.25
- Craft version: Craft Pro 3.6.17
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.4.26](https://github.com/verbb/formie/releases/tag/1.4.26)
