### ISSUE TITLE
Webhook URL issue if set from both general + from form settings

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#659]
**Description**
If a Webhook URL is set from the general Formie settings (`/formie/settings/webhooks`), and then set from the form settings (`/admin/formie/forms/edit/{id}#tab-integrations`), there's bug if the URL is not the same on both.

If the general is setup, the other seems ignored. The issue is that we can only set one general Webhook URL, and it's the main one that is retrieved. In my case, the right URL was reached, but the data retrieved is empty.

What's the difference between the general and the other and how to get the right form related Webhook URL?

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.27
- Craft version: 3.7.23
- Multi-site: Yes

**Comment by engram-design** [comment]
So the form-specific setting overrides the general integration setting. That's just in case the integration only has a single endpoint, and doesn't need to be form specific.

When you create a new form, it'll default to the general webhook URL setting, but you can of course override that on your form.

From my testing that seems to resolve to the correct URL, even for newly created forms. Are you seeing something different, where it's not sending the payload to the correct URL?

**Comment by engram-design** [comment]
Just checking if this is still an issue?

**Comment by romainpoirier** [comment]
Thank you for the follow up. I didn't remember how and when it was fixed, but it's not an issue anymore.
