### ISSUE TITLE
Provide hook for final submit event on multi-pages form

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#66]
**What are you trying to do?**
I'm hiding the form after submission using some custom JS. Using `onAfterFormieSubmit`, it triggers after every page, and I have no way of knowing if it's the final submit or not.

**What's your proposed solution?**
Provide special hook or some kind of parameter I can test to see if the final submit has been done.

**Comment by engram-design** [comment]
Updated in [1.1.8](https://github.com/verbb/formie/releases/tag/1.1.8)

The `onAfterFormieSubmit` JS event now supplies this information for you to use to determine this sort of thing, and more.

```
$('form').on('onAfterFormieSubmit', function(e) {
    console.log(e.detail)
});
```
Would produce something like
```
currentPageId: "1690"
nextPageId: "1690"
nextPageIndex: 1
submissionId: 1589
success: true
totalPages: 3
```
Showing this is a 3-page form. The `nextPageIndex` actually contains the current page ID. At the time this event fires, it's not yet incremented. Just in case that confuses you.

So, the response you'd get on the final form, when the page (and form) was successfully submitted would look like:
```
currentPageId: "1689"
nextPageId: null
nextPageIndex: 0
submissionId: 1589
success: true
totalPages: 3
```
You can pick a number of ways to determine from the above, but Formie itself uses `submitted = !nextPageId`.

**Comment by bleepsandblops** [comment]
Works great, thanks a lot for the quick fix
