### ISSUE TITLE
Send Test Payload sometimes generate error

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#660]
**Description**
Example:
`[error][formie] My Webhook: API error: “Setting unknown property: verbb\formie\models\FakeElement::disclaimer” /vendor/yiisoft/yii2/base/Component.php:210. Payload: “[]”. Response: “”`

This seems mostly get when using HTML fields, or fields within groups and/or with conditionals.

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.27
- Craft version: 3.7.23
- Multi-site: Yes

**Comment by engram-design** [comment]
I believe this should be fixed for the next release in https://github.com/verbb/formie/commit/f97ef1372cc100dc7e6e290e9c192eb05e473186

**Comment by engram-design** [comment]
Fixed in [1.4.28](https://github.com/verbb/formie/releases/tag/1.4.28)
