### ISSUE TITLE
Placeholder option missing from Dropdown field

### ISSUE THREAD

**Issue by jayhlee** [verbb/formie#664]
I can't seem to find the Placeholder setting for a Dropdown field, as mentioned in the [docs](https://verbb.io/craft-plugins/formie/docs/feature-tour/fields#dropdown). 

Has this setting changed? Or am I just missing it altogether? If so, sorry! Giving Formie a whirl for the first time.

**Comment by engram-design** [comment]
Good point that there's technically not a placeholder, but the best course of action is to create an empty option as the default option.

![image](https://user-images.githubusercontent.com/1221575/143967943-4798213e-9a24-48e6-818c-f00011d8411f.png)

I'll have the docs updated

**Comment by jayhlee** [comment]
Perfect. And I'm figuring that if the Dropdown field is set to be a Required Field, an empty option value (which is set as the default option) that's submitted would throw an error?

**Comment by engram-design** [comment]
Yep, that's correct!
