### ISSUE TITLE
Showing "All" submissions in control panel should show all submissions

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#673]
Currently, you can't view completed submissions, spam and incomplete submissions in the one view. This should be what "All" does.

We should also change the default submission status to be the default status, rather than All for this reason, as by default, people will want to view their default-status submissions, not everything (including lots of spam).

**Comment by engram-design** [comment]
This will also tie into [form groups](https://github.com/verbb/formie/issues/662)

**Comment by Diewy** [comment]
Also, an option to see the submissions of all sites. It is confusing to fill in the form on the frontend, go look for it in the control panel and not find it because another site is selected.

Preferably by default. Since the forms aren't filtered on site, I think the submissions shouldn't be neither.

Thanks.

**Comment by engram-design** [comment]
Yeah, this might be tricky to implement, and maybe a bit confusing. You'll likely want some way to differentiate which site a submission was from. That could probably be a "Site" column, but there's cases where some installs have vastly different sites where content shouldn't be visible across them. At the moment, it acts this way to mimic what other elements do, where elements are shown for a single site, until using the dropdown to change it.

As for forms not being filtered on site - that's more that they don't support that yet. But when we do add support for that, it'll be a similar thing (same as editing entries).

**Comment by Diewy** [comment]
I see. Maybe there is a possibility to make it a setting, like the default page.

Anyways, thanks for the clarifying!

**Comment by wmdhosting** [comment]
Perhaps to add option.  to show submissions by statustes  like its done in commerce. 
![image](https://github.com/verbb/formie/assets/76176291/74c790d8-13a6-4b18-bf85-ac33dd1d9d42)

And option to show Incomplete submissions in same way..

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
