### ISSUE TITLE
Add a save current state button for non-multiple pages forms

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#675]
**What are you trying to do?**
It is currently possible to have incomplete submissions when using multi-pages forms, which is very nice.
I have a Formie project where I only have one page of form, but where I would need to let the user save the current state of its submission before to submit it.
This is a form with only one Users field, where the user can add some people he would like to add, save its list, and lately do its final submit.

**What's your proposed solution?**
As I don't think it's possible with the current Formie version, it would be super nice to add a Save current state button in addition to the Submit button.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by romainpoirier** [comment]
Perfect, thank you! Do you plan to add it to Formie V1?

**Comment by engram-design** [comment]
No immediate plans sorry, Formie v1 is pretty much bug fixes for the near future, as it's difficult to maintain two versions as they start to split more and more apart from each other. It does make it more difficult to merge these architectural changes.

We'll see!

**Comment by engram-design** [comment]
Added in [2.0.0](https://github.com/verbb/formie/releases/tag/2.0.0)
