### ISSUE TITLE
Error Class 'craft\commerce\fields\Products' not found when editing a form

### ISSUE THREAD

**Issue by lesaff** [verbb/formie#68]
**Description**
I got this error when trying to edit a new form. I don't use Craft Commerce.

```
Class 'craft\commerce\fields\Products' not found
```

**Steps to reproduce**
1. Create a new form
2. Click on the form name to edit

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.1.8
- Craft version: Craft Pro 3.5.7
- Multi-site: No

**Additional context**
```
Error
Class 'craft\commerce\fields\Products' not found
1. in /Users/rudy/Sites/resourcemaven/vendor/verbb/formie/src/fields/formfields/Products.phpat line 16
78910111213141516171819202122232425use verbb\formie\elements\Form;
use verbb\formie\helpers\SchemaHelper;
 
use Craft;
use craft\helpers\UrlHelper;
use craft\commerce\elements\Product;
use craft\commerce\Plugin;
use craft\commerce\fields\Products as CommerceProducts;
 
class Products extends CommerceProducts implements FormFieldInterface
{
    // Traits
    // =========================================================================
 
    use FormFieldTrait {
        getFrontEndInputOptions as traitGetFrontendInputOptions;
    }
    use RelationFieldTrait;
 
2. in /Users/rudy/Sites/resourcemaven/vendor/composer/ClassLoader.php at line 444– include()
438439440441442443444445 * Scope isolated include.
 *
 * Prevents access to $this/self from included files.
 */
function includeFile($file)
{
    include $file;
}
```

**Comment by engram-design** [comment]
That's odd. I've created a brand new install with Formie as the only plugin and not getting this error. There are checks to prevent this and the Variant field from registering unless Commerce is enabled. There isn't a Products field on this form, but copying settings from another site - or something similar to that?

The only thing I can think of is that by including the class itself it's somehow autoloading it. If you can, can you test out the following just to see if that helps?

Change your `verbb/formie` requirement in `composer.json` to:
```
"require": {
  "verbb/formie": "dev-craft-3",
  "...": "..."
}
```
Then run `composer update`.

**Comment by lesaff** [comment]
I just tried your suggestion and still no luck.

https://www.dropbox.com/s/q85fjo1vorrzd53/formie-error.mov?dl=0

I had a Craft Commerce Pro trial installed at one point and uninstalled it already. Would that trigger the autoload?

**Comment by engram-design** [comment]
Ah, that makes a tiny bit more sense that you had it installed at one point.

We're using `Craft::$app->getPlugins()->isPluginEnabled('commerce')` which is supposed to detect if the plugin is installed and enabled.

Maybe if you can try a `./craft project-config/rebuild`? For some reason, Craft still thinks Commerce is installed. I'm wondering if when it's been uninstalled it hasn't disabled it, so it still thinks it's enabled.

Give it a few minutes, and run `composer update` again - I've just added checks to see if Commerce is both installed and enabled - something I didn't think was required.

**Comment by lesaff** [comment]
@engram-design I had to disable commerce manually in the `project.yaml`. It's working now. Thanks for your help.

**Comment by engram-design** [comment]
Glad to hear, I'll bundle these changes in the next release in any case.
