### ISSUE TITLE
Stencils cause error when runnning project-config

### ISSUE THREAD

**Issue by idleog** [verbb/formie#680]
When running ./craft project-config/apply an error occurs and stencils are not loaded and tehrefore not present in projct configuration.

**Steps to reproduce**
1. make some changes in stencil, deploy the project config to staging or production
2. run project-config/apply on staging/production (via console or in CP)

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.0
- Craft version: 3.7.25.1
- Multi-site: No

error message in console: `Applying changes from your project config files ...
- updating meta.__names__ ... done
- updating formie.formTemplates.21ee5465-05b8-4704-984e-387d08cf0248 ... done
- updating dateModified ... done
- adding formie.stencils.7e2143b8-83e4-40dd-88c7-3bc39eefb1fa.data.pages.0.rows.0.fields.0.settings.options.5 ... 
  - adding formie.stencils.7e2143b8-83e4-40dd-88c7-3bc39eefb1fa ... 
error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zfach_suchtcraft`.`formie_stencils`, CONSTRAINT `fk_jjlbeuqtqnbbyryaffajbbxvzjglviyygouo` FOREIGN KEY (`templateId`) REFERENCES `formie_formtemplates` (`id`) ON DELETE SET NULL)
The SQL being executed was: INSERT INTO `formie_stencils` (`name`, `handle`, `data`, `templateId`, `defaultStatusId`, `uid`, `dateCreated`, `dateUpdated`) VALUES ('SUZ Standard', 'testformular1', '{\"availability\":\"always\",\"availabilityFrom\":null,\"availabilitySubmissions\":null,\"availabilityTo\":null,\"dataRetention\":\"forever\",\"dataRetentionValue\":\"\",\"fileUploadsAction\":\"retain\",\"notifications\":[{\"attachAssets\":\"[]\",\"attachFiles\":true,\"attachPdf\":false,\"bcc\":null,\"cc\":null,\"conditions\":\"{\\\"sendRule\\\":\\\"send\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"content\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Dia Angaben können hier eingesehen werden: \\\"},{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"Submission CP URL\\\",\\\"value\\\":\\\"{submissionUrl}\\\"}}]},{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Zeit:\\\"},{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"Date (dd/mm/yyyy)\\\",\\\"value\\\":\\\"{dateInt}\\\"}},{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"Time (24h)\\\",\\\"value\\\":\\\"{time24}\\\"}},{\\\"type\\\":\\\"hard_break\\\"},{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"IP: \\\"},{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"User IP Address\\\",\\\"value\\\":\\\"{userIp}\\\"}}]}]\",\"enableConditions\":false,\"enabled\":true,\"formId\":1329,\"from\":\"info@example.com\",\"fromName\":\"Suchtfachstelle Zürich\",\"id\":\"stencil61b0b50978268\",\"name\":\"Push Nachricht an Suchtfachstelle\",\"pdfTemplateId\":null,\"recipients\":\"email\",\"replyTo\":\"info@example.com\",\"replyToName\":null,\"subject\":\"Eine Formular wurde ausgefüllt: {formName}\",\"templateId\":null,\"to\":\"joe.doe@example.com\",\"toConditions\":\"{\\\"toRecipients\\\":[]}\",\"uid\":\"3c4804d4-0b15-4e8d-bfbe-a4fafb735a88\"},{\"attachAssets\":\"[]\",\"attachFiles\":true,\"attachPdf\":false,\"bcc\":null,\"cc\":null,\"conditions\":\"{\\\"sendRule\\\":\\\"send\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"content\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"marks\\\":[{\\\"type\\\":\\\"bold\\\"}],\\\"text\\\":\\\"Vielen Dank für Ihre Anmeldung. Sie werden innerhalb einer Woche eine Bestätigung von uns erhalten!\\\"}]},{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"marks\\\":[{\\\"type\\\":\\\"bold\\\"}],\\\"text\\\":\\\"Suchtfachstelle Zürich\\\"}]},{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Veranstaltung: \\\"},{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"Form Name\\\",\\\"value\\\":\\\"{formName}\\\"}}]},{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Folgende Angaben wurden vom Formular übermittelt:\\\"}]},{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"variableTag\\\",\\\"attrs\\\":{\\\"label\\\":\\\"All Form Fields\\\",\\\"value\\\":\\\"{allFields}\\\"}}]}]\",\"enableConditions\":false,\"enabled\":true,\"formId\":1329,\"from\":\"info@example.com\",\"fromName\":\"Suchtfachstelle Zürich\",\"id\":\"stencil61b0b5097826c\",\"name\":\"Bestätigung an Absender\",\"pdfTemplateId\":null,\"recipients\":\"email\",\"replyTo\":\"info@example.com\",\"replyToName\":null,\"subject\":\"Bestätigung: {formName}\",\"templateId\":null,\"to\":\"{field.eMail}\",\"toConditions\":\"{\\\"toRecipients\\\":[]}\",\"uid\":\"30f34918-7fee-405c-a323-484016eb4010\"}],\"pages\":[{\"id\":\"new1847546856\",\"label\":\"Page 1\",\"rows\":[{\"fields\":[{\"columnSuffix\":\"ewytnjrz\",\"handle\":\"auswahlDaten\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new2007760909\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":false,\"label\":\"Auswahl Daten\",\"name\":\"Auswahl Daten\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"auswahlDaten\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Auswahl Daten\",\"labelPosition\":\"\",\"layout\":\"vertical\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"multi\":true,\"options\":[{\"isDefault\":false,\"label\":\"Mittwoch, 2. Juni, 12.15 bis 13.15 Uhr - Coping statt Doping\",\"value\":\"Mittwoch, 2. Juni, 12.15 bis 13.15 Uhr - Coping statt Doping\"},{\"isDefault\":false,\"label\":\"Montag, 7. Juni, 12.15 bis 13.15 Uhr - Hin- statt Wegsehen\",\"value\":\"Montag, 7. Juni, 12.15 bis 13.15 Uhr - Hin- statt Wegsehen\"},{\"isDefault\":false,\"label\":\"Donnerstag, 17. Juni, 12.15 bis 13.15 Uhr - Scham- statt Sprachlos\",\"value\":\"Donnerstag, 17. Juni, 12.15 bis 13.15 Uhr - Scham- statt Sprachlos\"},{\"isDefault\":false,\"label\":\"Mittwoch, 10. November, 12.15 bis 13.15 Uhr - Coping statt Doping\",\"value\":\"Mittwoch, 10. November, 12.15 bis 13.15 Uhr - Coping statt Doping\"},{\"isDefault\":false,\"label\":\"Dienstag, 16. November, 12.15 bis 13.15 Uhr - Hin- statt Wegsehen\",\"value\":\"Dienstag, 16. November, 12.15 bis 13.15 Uhr - Hin- statt Wegsehen\"},{\"isDefault\":false,\"label\":\"Donnerstag 25. November, 12.15 bis 13.15 Uhr - Scham- statt Sprachlos\",\"value\":\"Donnerstag 25. November, 12.15 bis 13.15 Uhr - Scham- statt Sprachlos\"}],\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"toggleCheckbox\":\"\",\"toggleCheckboxLabel\":null,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\Checkboxes\",\"vid\":\"new6789-1474\"}],\"id\":\"new1565787251\"},{\"fields\":[{\"columnSuffix\":\"ceimciby\",\"handle\":\"anrede\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new2136013598\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":false,\"label\":\"Anrede\",\"name\":\"Anrede\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"anrede\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Anrede\",\"labelPosition\":\"\",\"layout\":\"horizontal\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"options\":[{\"isDefault\":false,\"label\":\"Frau\",\"value\":\"frau\"},{\"isDefault\":false,\"label\":\"Herr\",\"value\":\"herr\"}],\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\Radio\",\"vid\":\"new5885-1840\"}],\"id\":\"new2120666820\"},{\"fields\":[{\"columnSuffix\":\"suvvqlbu\",\"handle\":\"name1\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new1705976652\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Name\",\"name\":\"Name\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":\"\",\"formId\":1329,\"handle\":\"name1\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Name\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new2366-6113\"}],\"id\":\"new433370701\"},{\"fields\":[{\"columnSuffix\":\"krrgejmq\",\"handle\":\"vorname\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new1664924272\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Vorname\",\"name\":\"Vorname\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"vorname\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Vorname\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new5196-1813\"}],\"id\":\"new1810728477\"},{\"fields\":[{\"columnSuffix\":\"bqwaltzq\",\"handle\":\"funktion\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new1306601195\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Funktion\",\"name\":\"Funktion\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"funktion\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Funktion\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":false,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new6691-972\"}],\"id\":\"new486692147\"},{\"fields\":[{\"columnSuffix\":\"gaatwjpd\",\"handle\":\"institution\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new780542670\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Institution\",\"name\":\"Institution\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"institution\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Institution\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":false,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new8525-6410\"}],\"id\":\"new484521381\"},{\"fields\":[{\"columnSuffix\":\"wvjfnnof\",\"handle\":\"strasseNummer\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new492387101\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Strasse / Nummer\",\"name\":\"Strasse / Nummer\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"strasseNummer\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Strasse / Nummer\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new9041-8395\"}],\"id\":\"new172124869\"},{\"fields\":[{\"columnSuffix\":\"awtpbcie\",\"handle\":\"plzOrt\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new198691879\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"PLZ / Ort\",\"name\":\"PLZ / Ort\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"plzOrt\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"PLZ / Ort\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new3206-8731\"}],\"id\":\"new1460886472\"},{\"fields\":[{\"columnSuffix\":\"csbrsbyr\",\"handle\":\"telefon\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new795237256\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"Telefon\",\"name\":\"Telefon\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"telefon\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Telefon\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\SingleLineText\",\"vid\":\"new2165-4593\"}],\"id\":\"new15362277\"},{\"fields\":[{\"columnSuffix\":\"edsxayqv\",\"handle\":\"eMail\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new144157097\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":true,\"label\":\"E-Mail\",\"name\":\"E-Mail\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"eMail\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"E-Mail\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"uniqueValue\":false,\"validateDomain\":false,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\Email\",\"vid\":\"new6188-9508\"}],\"id\":\"new1828903522\"},{\"fields\":[{\"columnSuffix\":\"fdvevloq\",\"handle\":\"bemerkungen\",\"hasConditions\":false,\"hasLabel\":true,\"id\":\"new1045566582\",\"isCosmetic\":false,\"isNested\":false,\"isSynced\":false,\"isTextInput\":false,\"label\":\"Bemerkungen\",\"name\":\"Bemerkungen\",\"settings\":{\"columnWidth\":12,\"conditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"cssClasses\":null,\"defaultValue\":null,\"enableConditions\":null,\"enableContentEncryption\":false,\"errorMessage\":null,\"formId\":1329,\"handle\":\"bemerkungen\",\"includeInEmail\":true,\"instructions\":null,\"instructionsPosition\":\"\",\"isNested\":false,\"label\":\"Bemerkungen\",\"labelPosition\":\"\",\"limit\":null,\"limitAmount\":null,\"limitType\":\"characters\",\"matchField\":null,\"placeholder\":null,\"prePopulate\":null,\"required\":true,\"richTextButtons\":[\"bold\",\"italic\"],\"useRichText\":null,\"visibility\":\"\"},\"supportsNested\":false,\"type\":\"verbb\\\\formie\\\\fields\\\\formfields\\\\MultiLineText\",\"vid\":\"new6598-1570\"}],\"id\":\"new2032834409\"}],\"settings\":{\"backButtonLabel\":\"Back\",\"buttonsPosition\":\"left\",\"cssClasses\":null,\"enableJsEvents\":false,\"enableNextButtonConditions\":false,\"enablePageConditions\":false,\"jsGtmEventOptions\":[{\"label\":\"event\",\"value\":\"formPageSubmission\"},{\"label\":\"formId\",\"value\":\"testformular\"},{\"label\":\"pageId\",\"value\":\"277\"},{\"label\":\"pageIndex\",\"value\":0}],\"nextButtonConditions\":\"{\\\"showRule\\\":\\\"show\\\",\\\"conditionRule\\\":\\\"all\\\",\\\"conditions\\\":[]}\",\"showBackButton\":false,\"submitButtonLabel\":\"Formular abschicken\"}}],\"requireUser\":false,\"settings\":{\"availabilityMessage\":null,\"availabilityMessageDate\":null,\"availabilityMessageSubmissions\":null,\"collectIp\":\"\",\"collectUser\":\"\",\"dataRetention\":null,\"dataRetentionValue\":null,\"defaultEmailTemplateId\":\"\",\"defaultInstructionsPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"defaultLabelPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"displayCurrentPageTitle\":\"\",\"displayFormTitle\":\"\",\"displayPageProgress\":\"\",\"displayPageTabs\":\"\",\"errorMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Formular konnte nicht abgeschickt werden. Bitte vervollständigen Sie die Angaben. \\\"}]}]\",\"errorMessagePosition\":\"bottom-form\",\"fileUploadsAction\":null,\"integrations\":{\"honeypot\":{\"enabled\":\"1\",\"showAllPages\":\"\"}},\"loadingIndicator\":\"\",\"loadingIndicatorText\":\"\",\"progressPosition\":\"end\",\"redirectUrl\":null,\"scrollToTop\":\"1\",\"storeData\":null,\"submissionTitleFormat\":\"{formName}: {timestamp}\",\"submitAction\":\"message\",\"submitActionFormHide\":\"\",\"submitActionMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Herzlichen Dank, Ihr Formular wurde verschickt! Sie bekommen in Kürze eine Bestätigung per E-Mail. \\\"}]}]\",\"submitActionMessagePosition\":\"bottom-form\",\"submitActionMessageTimeout\":\"\",\"submitActionTab\":null,\"submitActionUrl\":\"\",\"submitMethod\":\"ajax\",\"userDeletedAction\":null,\"validationOnFocus\":\"\",\"validationOnSubmit\":\"1\"},\"userDeletedAction\":\"retain\"}', 3, 1, '7e2143b8-83e4-40dd-88c7-3bc39eefb1fa', '2021-12-08 13:42:56', '2021-12-08 13:42:56')`

**Comment by engram-design** [comment]
I'll have to chat with @andris-sevcenko about this one, as it looks like there's a Stencil with a Form Template, but because the Form Template doesn't exist yet (also stored in project config), you'll get this error. We need to have a way where we force all Form/Email/PDF Templates to be processed first, then apply the stencil.

I believe Craft do this in a few instances for their own situations.

**Comment by andris-sevcenko** [comment]
A whole bunch of examples in the helper - https://github.com/craftcms/cms/blob/develop/src/helpers/ProjectConfig.php

**Comment by engram-design** [comment]
Thanks @andris-sevcenko !

**Comment by idleog** [comment]
Hi all
thanks for your answers! 

Can you approximately say how long this fix will take? Because this is quite blocking development as I cannot deploy any changes in the config files to the staging server anymore.
Or is there a workaround to avoid the exception?

Thanks a lot for your help and for your great plugin!
Peter

**Comment by engram-design** [comment]
I'm wondering if you're able to send through your project config YAML files to `web at verbb.io`? I've tried to replicate your issue by editing/creating stencils and form templates between environments, but it seems to process things in order correctly.

**Comment by idleog** [comment]
here my project files!

Thanks
Peter



------
goeldiweb.ch <https://www.goeldiweb.ch/>

Mobil +41 78 819 32 58
Zürich +41 44 508 07 68
Glarus +41 55 508 04 06

**Comment by engram-design** [comment]
Ah, I see the issue here. You have a single Form Template, but it has an ID of `3`. When applying that on another environment, the ID becomes `1`, so we have the classic project config issue of referring to Form Templates by the ID in a stencil, when their ID will likely change on the environment it's applied on.

As a workaround, I would manually change your local `formie_formtemplates` (if there's only 1) to the ID of 1, instead of 3 (verify that it is 3 locally). Then run `./craft/project-config/rebuild` to build this change to project config. Go and edit the stencil, ensuring you select the right form template, and save. That should put all references to this form template to `1` so you can press on.

This will require some changes to refer to the handle or UID of form templates. But as stencils are an extension of forms, I'm hesitant to rush this change for fear of breaking something with forms,

**Comment by idleog** [comment]
ok, thanks, that helps.
In other words, if I delete all form templates and make a new one afterwards (on local environment) , and then I put the config to the staging server it shouldnt be a problem neither, right?

Cheers
Peter
------

**Comment by engram-design** [comment]
Close - you'll need to reset the table's `AUTO_INCREMENT` when you delete them all, so that the IDs of form templates are sequential.

Like I said, just a stop-gap for now so you can keep going, but we'll need to address this soon.

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.1",
  "...": "..."
}
```

Then run `composer update`. This update will re-save your stencils with the correct UID references to templates, so this shouldn't happen again.

**Comment by idleog** [comment]
Great, thanks a lot!

**Comment by engram-design** [comment]
Fixed in [1.5.2](https://github.com/verbb/formie/releases/tag/1.5.2)
