### ISSUE TITLE
Integration getting deleted when project-config applied

### ISSUE THREAD

**Issue by samuelbirch** [verbb/formie#685]
Every time i do a deployment and the project-config/apply is run, it seems that the saved integration is deleted. I can see in the database the integration with a dateDeleted value.

**Comment by samuelbirch** [comment]
a project-config/rebuild fix the issue - it wrote out the integration config file.

It seems when saving an integration it doesn't create the config file.

**Comment by engram-design** [comment]
I can't seem to replicate this, as every change to an integration, adding a new one, or deleting an existing one triggers a project config change for me. Are you able to verify this after your rebuild, by adding or deleting an integration and checking the yaml shows a diff before deploying?

**Comment by engram-design** [comment]
Closing for the moment, as I believe this is related to project config getting out of sync in some fashion (not Formie's implementation). Formie will trigger Yaml generation with just about any action on integrations.
