### ISSUE TITLE
Entry integration - Option to update search index, default to true

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#690]
**What are you trying to do?**
I'm using a Formie form to update users details which is working great - but after an update the search index isn't updated and therefore changes are not searchable.

Currently I've got to run the following for changes to be searchable:
`$ ./craft resave/users --update-search-index --element-id XX`

**What's your proposed solution?**
Add an integration option for entries - I believe the default should be true i.e

_**Update Search Index**
Will update the search index for this element._

This could either be aded to the integration as a whole (webadmin/formie/settings/elements), or on an individual integration/form bases.

**Additional context**

PHP version | 8.0.8
Database driver & version | MySQL 8.0.27
Craft edition & version | Craft Pro 3.7.25.1
Formie | 1.5.2

**Comment by engram-design** [comment]
Good point, we want to provide an option for element integrations to opt-out of this behaviour (as you say, make it on by default) as per https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L2451

**Comment by anchovy** [comment]
Hi @engram-design - any update to this?

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.3](https://github.com/verbb/formie/releases/tag/2.0.3)
