### ISSUE TITLE
User input from Single-line Text field not being sanitised

### ISSUE THREAD

**Issue by rickmerkelbach** [verbb/formie#694]
**Description**
User input for "Single-line Text" fields is not being sanitised in _{htmlContent}_, allowing HTML injection.

**Steps to reproduce**
Add a single line text field to any form
Add an Email notification
Submit  `<a href="https://www.evil-link-here.test">click here</a>` into a Single-line Text field
Email arrives with a clickable "click here" link (other HTML input also works)

![Artboard](https://user-images.githubusercontent.com/53075916/146804938-48f4b348-683a-4985-b32d-e0938eb4722b.png)

**Proposed solution**
Sanitise user input on Single-line Text fields before rendering in email notifications. (I assume in /base/FormFieldTrait.php?)

**Info**
Plugin version: 1.5.3
Craft version: 3.7.26

Multi-site: Yes
Multi-page form: No
Submission Method: Any
Client-side Validation: Yes
Custom Form Templates: No

**Comment by engram-design** [comment]
Great point. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by rickmerkelbach** [comment]
Thanks for the quick fix! The same notification now arrives escaped:

![Screenshot 2021-12-21 at 09 13 32](https://user-images.githubusercontent.com/53075916/146895286-e5a48c3a-53e2-4815-a1fb-63d7c638cc2f.png)
