### ISSUE TITLE
Add FileInput support to save_*_Submission in Graphql

### ISSUE THREAD

**Issue by Tam** [verbb/formie#695]
**What are you trying to do?**
Upload a file to a submission.

**What's your proposed solution?**
Add `FileInput` support to the `save_*_Submission` mutations to allow for file uploading while creating a submission.

**Additional context**
This is preferred over uploading the file before saving the submission to account for validation errors that might occur in the form that would alter the need for the uploaded file.

**Comment by engram-design** [comment]
I'll see what we can do here. Lots of people are handling this in a few different fashions, but it _might_ not be possible to handle file uploads with GraphQL. I'll have to look into it.

**Comment by engram-design** [comment]
This has been implemented in [1.5.19](https://github.com/verbb/formie/releases/tag/1.5.19)
