### ISSUE TITLE
Send a different notification more easily when the status of a submission has changed

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#699]
**What are you trying to do?**
I would like to send a notification when the status of a submission has changed. Currently, the default (and single one) notification is only fired once at the first submit (so when a submission become `isIncomplete` from `true` to `false`).

In my context, after the submission is submitted I'm waiting for a Webhook from Stripe to change the submission status to paid. When the Webhook is called, I would like to send a confirmation notification that its has been paid, or only send the first default notification at this time (so not on submit, when we're still waiting for the Webhook response).

I can setup this notification manually from a module using this:
```
Event::on(Submission::class, Submission::EVENT_AFTER_SAVE, function(Event $event) {
    $submission = $event->sender;

    if (!$submission->isIncomplete && $submission->statusId = 2) {
        $notification = Formie::$plugin->getNotifications()->getNotificationById(123);

        $sentResponse = Formie::$plugin->getEmails()->sendEmail($notification, $submission);
    }
});
```

But this is not very handy. I would like to be able to setup it more easily, as I have a lot of forms.

**What's your proposed solution?**
First, it would be very handy to be able to retrieve the notification id (or handle) from the CP. Currently, it's only possible from the database (`formie_notifications` table).

It would be also very handy to setup multiple notifications per submission, in particularly when changing the status of the submission to a new one.

It would be wonderful if these additional notifications could be setup from the CP.

I understand this would be tricky.

**Additional context**
See [#367](https://github.com/verbb/formie/issues/367#issuecomment-967149364).

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
