### ISSUE TITLE
Custom prefix list for "name" common field

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#703]
**What are you trying to do?**
I want to add the prefix drop down to the "name" common field, but not wanting all the options. If I had a custom dropdown list and add the options myself then the drop down takes up 50% width and the "name" common field takes up the remaining 50% - which doesn't look great.

**What's your proposed solution?**
Allow a config file override to allow for custom prefix options or a way to supply custom prefixes

**Additional context**
I can edit the src to change the values, but that would obviously get overwritten with future updates

**Comment by engram-design** [comment]
You can modify the prefixes using the [`modifyPrefixOptions`](https://verbb.io/craft-plugins/formie/docs/developers/events#the-modifyPrefixOptions-event) event.

```
use verbb\formie\events\ModifyNamePrefixOptionsEvent;
use verbb\formie\fields\formfields\Name;
use yii\base\Event;

Event::on(Name::class, Name::EVENT_MODIFY_PREFIX_OPTIONS, function(ModifyNamePrefixOptionsEvent $event) {
    $event->options[] = ['label' => Craft::t('formie', 'Mx.'), 'value' => 'mx'];
});
```

**Comment by jamiematrix** [comment]
Thankyou! Missed that part of the docs!

Is there a way to remove values/labels from the prefix options? Apologies if this is a very simple solution.

**Comment by engram-design** [comment]
Yup! You'll want to override the `$event->options` variable. My example above uses `$event->options[]` which just appends values. Instead, you'll want to replace the list altogether:

```
$event->options = [
    ['label' => Craft::t('formie', 'Mr.'), 'value' => 'mr'],
    ['label' => Craft::t('formie', 'Ms.'), 'value' => 'ms'],
    ['label' => Craft::t('formie', 'Mx.'), 'value' => 'mx'],
];
```

**Comment by jamiematrix** [comment]
Thank you! Again :)
I had made some guess work but had the syntax wrong.
