### ISSUE TITLE
Redirect Entry redirecting to primary site

### ISSUE THREAD

**Issue by bavocorteville** [verbb/formie#706]
**Description**

I have a multisite with a page section where the propagation method is set to custom. I've added an entry there (for all sites) that I want to link to a form. When I want to link an entry that is not from my primary site and I save the form, then the entry from the primary site is displayed as the redirect entry and not the selected entry from another site. On the front-end the redirect is wrong (primary site entry, not the chosen one).

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.3
- Craft version:3.7.27.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Refer to https://github.com/verbb/formie/issues/693#issuecomment-997786282, but we'll eventually need to record the siteId of the chosen entry as well.

**Comment by bavocorteville** [comment]
Oops, should have searched better. Will fix it that way for now, thanks!
However, it remains confusing for the client, so taking the siteId into account would be great.

**Comment by janhenckens** [comment]
I'll add another vote for doing this in on the plugin, a coworker of mine ran into this again too.

**Comment by engram-design** [comment]
@janhenckens Yup, leaving this open to remind me to add this in for 1.5.x

**Comment by Antimated** [comment]
@engram-design Any updates on this? I bumped into the same issue.

**Comment by TomDeSmet** [comment]
Bump, I would swear this worked in the past as our client has used this several times already.
I hope for a speedy fix!

I'm using Craft CMS 3.7.44 and Formie 1.6.0.

**Comment by engram-design** [comment]
This is trickier than I first thought, as [relations don't store the target site](https://github.com/craftcms/cms/issues/3584) and due to us using the element select field, we don't get this information from it, only the element IDs.

Still looking into it, but @TomDeSmet I don't think this ever would've worked.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/formie/releases/tag/2.0.9)
