### ISSUE TITLE
User Registration Form JS error

### ISSUE THREAD

**Issue by mentiondev** [verbb/formie#708]
**Description**
User Registration form is not loading properly. Prints a JS error in the console

Console log:
```
Uncaught TypeError: Cannot read properties of null (reading 'registeredJs')
    at t.value (formie.js?v=1641600764:1)
    at formie.js?v=1641600764:1
    at NodeList.forEach (<anonymous>)
    at t.value (formie.js?v=1641600764:1)
    at HTMLDocument.<anonymous> (formie.js?v=1641600764:1)
```

I've prettified the js section that is having the error below, it is the line that says `var n = r.registeredJs || [];`
```
key: "initForm",
  value: function(t) {
    var e = this,
      r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : {};
    if (Object(o.b)(r) && (r = JSON.parse(t.getAttribute("data-config"))),
      Object(o.b)(r))
      console.error("Unable to parse `data-config` form attribute for config. Ensure this attribute exists on your form and contains valid JSON.");
    else {
      var n = r.registeredJs || [];
      r.Formie = this;
      var i = new p(r);
      this.forms.push(i),
        i.fieldConfigs = this.parseFieldConfig(t, t),
        n.length && (i.$registeredJs = document.createElement("div"),
          i.$registeredJs.setAttribute("data-fui-scripts", r.formId),
          document.body.appendChild(i.$registeredJs),
          n.forEach((function(r) {
            var n = document.createElement("script");
            r.src && (n.src = r.src,
                n.defer = !0,
                n.onload = function() {
                  if (r.module) {
                    var n = i.fieldConfigs[r.module];
                    n && Array.isArray(n) && n.length && n.forEach((function(t) {
                        e.initJsClass(r.module, t)
                      })),
                      r.settings && e.initJsClass(r.module, r.settings),
                      "FormieConditions" === r.module && e.initJsClass(r.module, {
                        $form: t
                      })
                  }
                }
              ),
              i.$registeredJs.appendChild(n)
          })))
    }
  }
```

I am using the user registration code from the docs:
```
{% set form = craft.formie.forms.handle('register').one() %}

{% do craft.formie.registerAssets(form) %}

<form method="post" accept-charset="UTF-8">
    {{ actionInput('users/save-user') }}
    {{ csrfInput() }}

    {{ craft.formie.renderPage(form, null, {
        fieldNamespace: '',
    }) }}
</form>
```

**Steps to reproduce**
1. Create Register form
2. Template code for Registration Form from the docs is used
3. Form fields load, but a JS error (see above) is stopping it from working.

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.5
- Craft version: 3.7.28
- Multi-site: No

**Additional context**
I'm creating a member section fro my website. So want to use Formie for the various registration forms.

**Comment by engram-design** [comment]
My apologies that the docs didn't include the required `id` and `data-config` attributes on the form, which will cause this error.

Have now updated the docs https://verbb.io/craft-plugins/formie/docs/template-guides/craft-forms#user-registration

**Comment by mentiondev** [comment]
Hi Josh, that's great thanks, and is now submitting the user registration form to craft. But the form still isn't behaving as expected, as the **Action on Submit** selections don't seem to be working. i.e. I want to display a message once submission is complete, but it is just returning an empty form. And if i change it to be redirect to page. it doesn't redirect either. So assuming I'm still missing some thing in the template code to make all of the form selections from the cms function properly?

```
{% set form = craft.formie.forms.handle('register').one() %}

{% do craft.formie.registerAssets(form) %}

<form method="post" accept-charset="UTF-8" id="{{ form.formId }}" data-config="{{ form.configJson }}">
    {{ actionInput('users/save-user') }}
    {{ csrfInput() }}

    {{ craft.formie.renderPage(form, null, {
        fieldNamespace: '',
    }) }}
</form>
```

**Comment by engram-design** [comment]
For any of the Craft-based forms (in those docs) you're not actually submitting to Formie's controller endpoint, so things like the redirection won't happen, because you're not creating a submission, or doing anyone on the form. Not only that, but you're also rendering the form manually.

As such, you'll want to setup the redirect using `redirectInput()`.

```
{{ actionInput('users/save-user') }}
{{ redirectInput(form.getRedirectUrl()) }}
```

As for showing a message, I'd recommend taking a look at the default templates - https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/form.html#L45-L64

**Comment by mentiondev** [comment]
Thanks for being so helpful. Much appreciated.
