### ISSUE TITLE
Label of Repeater is not hidden

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#711]
**Description**
Label of `Repeater` is not hidden. It is hidden while using another type (like `Single-line Text` field).

**Steps to reproduce**
1. Add a new `Repeater` field
2. Set the `Label`
3. Set the `Label Position` to `Hidden`
4. `Save` and check the form
5. The `Label` is still shown

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.5
- Craft version: 3.7.28
- Multi-site: Yes

**Comment by engram-design** [comment]
Can you check your form templates - you mention you're using custom ones. The default ones display as expected (the first repeater and group fields have their label set to Hidden)

![image](https://user-images.githubusercontent.com/1221575/149308382-5d047197-91a1-4a00-b3c4-5a5b57fa5231.png)

**Comment by romainpoirier** [comment]
Thank you, that was because I haven't added styles to the `.fui-sr-only` class.

**Comment by engram-design** [comment]
Ah, yes so in these cases where there's a `<legend>` element involved, we need to have that for accessibility, and rely on the `.fui-sr-only` class. This is also applicable to a few other field types.
