### ISSUE TITLE
HTML field is stripping some tags

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#712]
**Description**
I have an HTML field with this content:

```
<details>
	<summary>
		<span>
			<span>
				Requirements
			</span>
			<span></span>
		</span>
	</summary>
	<div>
		<ul>
			<li>Upload <strong>1 single PDF</strong></li>
			<li>Try not to exceed <strong>20 pages</strong></li>
			<li>It must be written <strong>in English</strong></li>
		</ul>
	</div>
</details>
```

But after `renderForm`, even with or without the _Default Formie Template_, the `details` and `summary` tags are changed to `div`.

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.5
- Craft version: 3.7.28
- Multi-site: Yes

**Comment by engram-design** [comment]
For safety, we use `HTMLPurifier` when outputting content. You can modify these through an event - https://verbb.io/craft-plugins/formie/docs/developers/events#the-modifyPurifierConfig-event. Or, like Craft, you can provide a JSON file in `config/htmlpurifier/Default.json`.

I believe these are being filtered out as they aren't standard HTML tags, but tweaking these settings should help.

**Comment by romainpoirier** [comment]
They are standard HTML tags: https://www.w3schools.com/tags/tag_summary.asp

I have added this to my custom module file, but unfortunately these tags are still converted to `div`:
```
Event::on(Html::class, Html::EVENT_MODIFY_PURIFIER_CONFIG, function(ModifyPurifierConfigEvent $event) {
	$event->config->getHTMLDefinition(true)->addAttribute('details', null, new HTMLPurifier_AttrDef_Text());
	$event->config->getHTMLDefinition(true)->addAttribute('summary', null, new HTMLPurifier_AttrDef_Text());
});
```

Any idea what's still wrong?

**Comment by romainpoirier** [comment]
I've finally ended up with this, which works:
```
Event::on(Html::class, Html::EVENT_MODIFY_PURIFIER_CONFIG, function(ModifyPurifierConfigEvent $event) {
	$event->config->getHTMLDefinition(true)->addElement(
		'details',
		'Block',
		'Flow',
		'Common',
		array(
			'open' => new \HTMLPurifier_AttrDef_HTML_Bool(true)
		)
	);
	$event->config->getHTMLDefinition(true)->addElement(
		'summary',
		'Inline',
		'Inline',
		'Common'
	);
});
```

**Comment by engram-design** [comment]
Oh, right you are! I'll look at the default purifier config to see what might be going on there. I would've thought any standard tag be allowed by default. But we'll ensure that they are.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
