### ISSUE TITLE
Possible to limit submission to once per email, or any other unique field?

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#729]
**What are you trying to do?**
I'd only like people to submit the form once per email address, or some other unique field like a customer number.

Example use case (but not the one I need it for) useful for competition forms where you an only enter once per email, or account Id etc

Thanks :)

**Comment by engram-design** [comment]
There's an option for the Email Address field called **Unique Value** which when included in the form will check if there's an existing submission with this value (for this field, and this form).

```
Whether to limit user input to unique values only. This will require that a value entered in this field does not already exist in a submission for this field and form.
```

Sounds like what you're after?
