### ISSUE TITLE
Spam Submission Limit Not Emptying

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/formie#732]
In Formie's preferences under Spam, there's a ``Spam Submission Limit``.  

I have mine currently set to 100 but there's currently 978 spam submissions on one of our forms.

The [docs](https://verbb.io/craft-plugins/formie/docs/feature-tour/data-retention#recommended-approach) mention that Formie does some garbage collection but after running the command manually it still doesn't appear to dump them.

On the Form's settings, the Data Retention is set to Forever. Is the spam garbage collection taking that setting into account as well or maybe I'm missing something else or is this a bug?

**Comment by engram-design** [comment]
As you've mentioned, we use Craft's garbage collection to queue up some things - one of which is deleting spam over the limit. I think this must be coming down to when the garbage collection is being run (or not run).

And the data retention stuff is completely separate to spam (as in spam overrides that setting).

According to the [garbage collection docs](https://craftcms.com/docs/3.x/gc.html) it can be completely random when this is actually run, and I believe this happens only when visiting the control panel.

To test this, running `php craft gc` manually should clear up a bunch of the spam, and a few of the other garbage collection tasks.

**Comment by RitterKnightCreative** [comment]
Thanks Josh, running ``craft gc`` definitely worked.  With a 1/100,000 chance of triggering GC when you hit the CP, seems like there's a pretty good chance it would never run. Probably best to do it manually maybe along with updating.
