### ISSUE TITLE
Client-side validation for fields with Match Field set

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#736]
**What are you trying to do?**
Would like client-side validation for fields with **Match Field** setting defined. Right now, matching fields are only validated server-side. It would make form submissions a little bit easier for users if matched fields were validated in their browser.

**Comment by engram-design** [comment]
I'll consider this, but the server-side check will always probably need to be there, as for multi-page forms where the matching field is on another page, it's unreliable to rely on client-side validation in that instance. But otherwise, seems pretty valid to include it.

**Comment by engram-design** [comment]
Going to shelve this for when we tackle https://github.com/verbb/formie/issues/556

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
