### ISSUE TITLE
Form JS not rendering on custom route

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/formie#744]
**Description**
We created a custom route for users to register to the activities. The route works like this: 
`$event->rules['activiteiten/<slug>/inschrijven'] = 'statik/activity/render-register-template';`

In the controller we fetch the activity and render the register template:

```
public function actionRenderRegisterTemplate($slug)

    {
        $entry = Entry::findOne(['section' => 'activities', 'slug' => $slug]);

        return Craft::$app->view->renderTemplate('_activities/_register', ['entry' => $entry]);

    }
```

In the template we show the register form:

```
{% set registerForm = registerBlock.form.one() %}

  {% do craft.formie.populateFormValues(registerForm, { activiteit: entry.title }) %}

  {% do craft.formie.populateFormValues(registerForm, { datumActiviteit: entry.eventDate.formatted() }) %}

  {{ craft.formie.renderForm(registerForm) }}
```

We have a reCaptcha on this form, but the JS for this form is not loading so all the submissions are in spam.

This is our network with our JS files
![Screenshot 2022-02-02 at 12 00 49](https://user-images.githubusercontent.com/42932673/152143440-b35266cc-5fa1-4fab-81bf-5cadedde9f77.png)

But it should be this: (this is from another form where it does work, but it is not on a custom route)
![Screenshot 2022-02-02 at 12 00 54](https://user-images.githubusercontent.com/42932673/152143479-ae658385-7ead-4f19-b7d5-636838fddc1f.png)

We tried adding: `{% do craft.formie.registerAssets(registerForm.handle) %}`
But this does not help.

Can you help us out here?

**Steps to reproduce**
1. Create a form and enable the reCaptcha in integrations.
2. Add a custom route in your module
3. Render the template from your module controller
4. Render the form on the template
5. JS and reCaptcha are not loading

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.22
- Craft version: 3.7.18
- Multi-site: No

**Comment by carolineboeykens** [comment]
While submitting this issue we found out that it had something to do with the JavaScript Render Location from our custom form template:
![Screenshot 2022-02-02 at 12 30 01](https://user-images.githubusercontent.com/42932673/152145691-8fa79e44-3c3b-44ee-aa10-528eaf5ebb66.png)

When we set this to 'Inside Form' it is working! 💪 

Just to be sure, is this normal behaviour? How could we have prevented this?

So the issue is when:
- the form is on a custom route
- with a reCaptcha
- the JavaScript is rendered from the footer.

**Comment by engram-design** [comment]
That's quite interesting, I wouldn't have _thought_ a custom route would do anything different. The render location at the Page Footer uses Craft's `Craft::$app->getView()->registerJsFile()` function which is turn uses Yii's handling to output it, usually at the bottom of the page before the `</body>` tag. But you're totally right, that seems to be what's happening.

Calling `{% do craft.formie.registerAssets(form) %}` will also probably do the same thing.

**However** I believe you might be using the wrong function to render your page template. If it doesn't cause an issue with Formie, I reckon It'll cause some issues with other plugins.

You should use the following:

```
return Craft::$app->view->renderPageTemplate('_activities/_register', ['entry' => $entry]);
```

The difference with `renderPageTemplate()` compared to `renderTemplate()` is that it expects the template you're pointing it to, to represent the entire page. As such, it'll call Yii's `beginPage()` and `endPage()` functions to render CSS/JS for Formie (but as I mentioned, likely any other plugin that adds stuff to the page header/footer). So instead, `renderTemplate()` is really on there for rendering a partial, and doesn't really do the extra bits a front-end page might need. If you come from plugin development, and are used to using `renderTemplate()` from your controllers for control panel based pages, that's a different story.

https://github.com/craftcms/cms/blob/3319da9a4c2e641e046f501834eb02623b9bc4e1/src/web/View.php#L440-L471

If nothing else though, I learnt something new! 😄
