### ISSUE TITLE
Multiple Emails on notifications not working

### ISSUE THREAD

**Issue by cherrykoda** [verbb/formie#746]
**Description**

When multiple emails are added to the email field for notifications, only the first email address is being used. I have tried both with and without a space after the comma.

**Steps to reproduce**
1. Make a new form
2. Add multiple email addresses to the notifications settings
3. Submit a form
4. Check the sent notifications tab in Formie, in addition to the email boxes of the addresses.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Default
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3
- Craft version: Craft Pro 3.7.28
- Multi-site: No

**Additional context**
Im on the dev-craft-3 branch due to a bugfix on checkboxes. unsure if I can move back to release branches.

**Comment by engram-design** [comment]
Spaces will be trimmed safely for multiple items, so no stress there. Are you using fields to populate the Recipient value for an email notification? As is - are you using the variable-picker to pick fields? If so, can you let me know the types of fields you're using.

If you're just using static emails like `email1@test.com, email2@test.com`, that's another story.

I'll also make note that if you have the [`testToEmailAddress`](https://craftcms.com/docs/3.x/config/config-settings.html#testtoemailaddress) config setting enabled for Craft, that'll override all behaviour and route emails to just the recipients provided there.

**Comment by cherrykoda** [comment]
This is for static emails, which I entered into the email field manually for notifications. I am not using testToEmailAddress and the site is not in devmode either.

![image](https://user-images.githubusercontent.com/3789834/152627114-3a8d309a-5cee-4b73-bb8b-dfe8f1c25cd2.png)

![image](https://user-images.githubusercontent.com/3789834/152627133-6e630dbc-36be-4047-89a9-e52166e07c56.png)

**Comment by engram-design** [comment]
There was [a bug](https://github.com/verbb/formie/commit/e41d22ff5682dcf19352f3c0109d4a79bf132117) where the sent notification was only recording the first recipient, but the email notifications themselves were being send successfully. This is as per your screenshot of your sent notification.

Just wanted to confirm your second email is actually *not* receiving the email from Formie? My testing shows the emails are going where they should, but the sent notification was only recording the first email.

**Comment by cherrykoda** [comment]
I think I've found today there is also an issue within our email setup. Thank you for fixing the sent data listing, it was definitely a red herring on the real issue!

**Comment by engram-design** [comment]
Aha, glad you got to the bottom of it!

**Comment by bymayo** [comment]
@engram-design Sorry to open an old issue - But we're having this issue but with Formie v3.1.2. The notifications send to the first email (Let's call it john@verbb.com) in the comma separated list, but not the others (jane@verbb.com).

I can't see it in "Send Submissions" neither, I can only see the notification to the first email address (john@verbb.com).

They are saying they receive emails to john@verbb.com but not to jane@verbb.com + others.

Should the multiple recipients still be logged under the "Sent Notifications" page?

I've tried a space after the comma, and no space but makes no difference.

**Comment by engram-design** [comment]
A quick test and things are all okay on my end with this. One thing to check is if your project makes use of the `testToEmailAddress` Craft config setting? If you do, that's going to override any recipient set in the email.

**Comment by bymayo** [comment]
@engram-design Doh, what an amateur mistake! That was the issue.
