### ISSUE TITLE
Unable to parse response `SyntaxError: Unexpected token < in JSON at position 442`.

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#747]
**Description**

I am getting this error message when using forms with a mailchimp integration (oddly enough its only occurring on the homepage).

Submission: Ajax Client Side
Integrations: Mailchimp, Honeypot, recaptcha

The process still works as the double opt-in email is triggered and contact added to mailchimp, but the error is making people think it didn't work. I am not sure it is handling the response from mailchimp correctly?

Craft: 3.6.17
Formie: 1.5.8

```
Unable to parse response `SyntaxError: Unexpected token < in JSON at position 442`.
Couldn’t save submission due to errors.
```
<img width="1044" alt="Screenshot 2022-02-04 at 10 52 54" src="https://user-images.githubusercontent.com/18699249/152517253-cc4e86e3-00db-4bd3-a346-ce42e06300b1.png">

Thanks as always!

**Comment by engram-design** [comment]
That usually reflects that the response back from the server (Craft) isn't JSON, but a HTML response.

Any integrations or email notifications are run on the queue (by default), so can you let me know if you've opted to **not** run integrations via the queue? So anything hooked up to Mailchimp would typically not throw an error, even if there was one, which is important for UX (as you've mentioned).

I see you have the debug bar open. Can you inspect the response from the XHR request when submitting the form? If it's a serious error, there should also be something in your error logs (`storage/logs/formie.log`).

If you inspect the request's response using Chrome developer tools (Network tab) you should be able to see a preview of the response, and what it looks like.

**Comment by mark-chief** [comment]
Hi, 

Thanks for your help on this. I viewed the XHR response and actually saw a load of suspicious code being injected in to the page (From October last year, Pre-Formie, and on very old version of craft) I've cleaned out the server and removed the malicious files and working as expected.

**Comment by engram-design** [comment]
@mark-chief Thanks for letting me know!
