### ISSUE TITLE
Add configurable option for email notifications to use element `cpEditUrl` or `url`

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#753]
Currently, email notifications for the following element fields:

- Categories
- Entries
- File Upload
- Products
- Variants

Produce a link to their `cpEditUrl` URL. All have the possibility to have front-end URLs, and we should allow this to be configurable per-email notification. For example, for admin emails, it might be good to link to the CP URL, but for client emails, it might be better to link to the front-end.

Where this setting is stored is tricky. It's possible this is a setting that needs to be configured on the field, but then that doesn't allow flexibility to customise that per-email notification. On the other hand, managing this setting across the entire notification isn't ideal either, affecting all element fields.

**Comment by zizther** [comment]
@engram-design Is there any update on when this would look to be added?

**Comment by engram-design** [comment]
It's available now for Formie 3's beta, and will likely not be available in Formie 2 for Craft 4.x

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
