### ISSUE TITLE
Custom sources on Entries fields do not populate

### ISSUE THREAD

**Issue by Mosnar** [verbb/formie#76]
**Description**

I register a custom element source to narrow down a specific entry type and I use this in various places across the CMS. I select this as a source in an Entries field in Formie; however, none of the pages are displayed on the frontend form. It looks like Formie isn't actually processing the sources properly - but rather, just looking at the key and fetching the section by the  section UID in the key.

### Form settings
Please pick from the options below.

- Multi-page form: N/A
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

**Additional info**
- Plugin version: 1.2.0
- Craft version: 3.5.8 Pro
- Multi-site: Yes or No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.2.1](https://github.com/verbb/formie/releases/tag/1.2.1)
