### ISSUE TITLE
Add support for repeater sub-fields in condition rules

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#764]
**What are you trying to do?**
Would be nice to be able to select repeater sub-fields in condition rules.

**What's your proposed solution?**
I envision this working similarly to groups. When selecting a field for condition rules, they would be listed as *Repeater Name: Field Name*.

**Comment by engram-design** [comment]
Yeah, this is on the longer-term roadmap. It just gets tricky as repeaters by nature have multiple collections of fields to contend with. For instance, being able to determine if "Field One is 'Some Value'" requires multiple repeater block lookups, which get's complicated if you have multiple conditions setup. It's a little similar to the current checks with Checkboxes (as they have multiple values).

**Comment by idawgik** [comment]
I'd like to add my support for this feature request. I'm working on a project right now with some big forms, and part of it includes a big repeater section. There are multiple "If other, please specify" fields in the repeater that I would love to only show based on matching conditions.

**Comment by DenyEs** [comment]
I just came across the usecase for this, I guess I will have to manage without it for now. Good to know it's on the roadmap tho :)

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
