### ISSUE TITLE
Automatically run integrations when submission marked as not spam

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#766]
**What are you trying to do?**
Would help save some extra steps if any applicable integrations ran automatically when a spam submission is marked as not spam.

**Comment by engram-design** [comment]
Yeah, this does bring up an interesting point (similar with email notifications). I'm wondering about the "magic" of this from a UX point of view, and maybe there's a better way to allow people to opt-in to this behaviour, as opposed to it being automatic. I'd kinda hate there being an unintended consequence (getting an email out of the blue) without at least being given the heads-up first.

I'll think about some options here, but fundamentally, I think it makes sense to make this easier for spam-redeemed submissions.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
