### ISSUE TITLE
Possible composer issue with Craft 4?

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#769]
**Description**
First off, I don't have any prerelease version of Craft 4 installed, so this might not be anything to worry about. But I thought it might be worth mentioning anyhow, just in case ...

I was recently working through a composer issue I had between Formie and a plugin that required league/oauth2-google ^2.6, and found that Formie required ^3.0:

```
nitro composer depends league/oauth2-google
… checking /Users/andrew/Sites/site/composer.json ✓
verbb/formie  1.5.9  requires  league/oauth2-google (^3.0)
composer depends completed
```

Then, purely by chance, a little bit later I was checking out the Craft 4 composer.json file:
https://github.com/craftcms/cms/blob/4.0/composer.json
and saw this line:

```
"league/oauth2-client": "^2.6.0",
```

Is that something that might cause a bit of a problem for Formie when Craft 4 is released?

**Comment by engram-design** [comment]
Yep, going to let the dust settle on the alpha, and wait for the beta, but very likely a few things for us to consolidate for Craft 4! I think we can easily move our constraints though back to `^2.6` in line with Craft 4.

**Comment by engram-design** [comment]
Actually, looking at `league/oauth2-google` we'll need to bump this up to `^4.0` for PHP 8 compatibility with Craft 4, so I'd suggest your other plugin also needs to do the same!

**Comment by AndrewMac** [comment]
Thanks, and I completely understand. Formie is way more important than those other plugins, so I'll drop them for now and let the developer know. Cheers! :-)
