### ISSUE TITLE
Support for Constant Contact “V3” Authorization URLs

### ISSUE THREAD

**Issue by AugustMiller** [verbb/formie#770]
Hey, Josh + Verbb Team!

We just got notified by a client that the current OAuth2 URLs are being EOL'd on March 31, 2022.

It's unclear _why_, or why the timeframe is so short… but here's Constant Contact's writeup about the change:
https://developer.constantcontact.com/api_guide/auth_update_apps.html

I think this is only a matter of updating the two URLs in `verbb\formie\integrations\emailmarketing\ConstantContact`:

Method | New URL
--- | ---
`getAuthorizeUrl()` | https://authz.constantcontact.com/oauth2/default/v1/authorize
`getAccessTokenUrl()` | https://authz.constantcontact.com/oauth2/default/v1/token

Replacing them locally, it connects just fine with the new endpoints. What I'm _not_ sure about is whether this constitutes a breaking change to Formie—i.e. one that would upset existing integrations due to API key/secret incompatibility. Part of the "upgrade" process is copying the entire CC “application” into the new scheme, but the API Key stays the same (they do ask you to roll the _secret_, though).

Let me know what you think!

_Edit: I will PR this ASAP if you're down to make the change in a dot release!_

**Comment by engram-design** [comment]
They don't waste their time! Should be easy as you mention. 

I'm reasonably confident from messing about with the API that this shouldn't be a breaking change for existing apps due to the API keys being unchanged, and it _seems_ to be okay with using the new endpoints on existing apps. I haven't gone through the process of creating a new app, and maybe my auth token hasn't expired yet.

Anyway, keen for others to test. I may very well likely add a date-check in the code for the 31/03/2022 check so it's done automatically as a bit of a safeguard.

To get this change early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by AugustMiller** [comment]
Yooo! Thanks for looking at this so quick. 😍

Pulled down the dev branch and tried it out—the legacy keys _do_ continue to work with normal API calls, but _do not_ work for the new Auth + Token endpoints.

So, my guess is that this will cause some latent problems for users, after an access token expires and the app needs to perform a refresh—only to find that the refresh token is incompatible with the new endpoints (From CC: `invalid_client`).

Date check seems fine… might also be worth emitting Deprecation notices or something to alert devs? Can't even imagine how many of these CC emails are getting junked by the accountholders without a second thought!

Holler if you want to hash anything out! 💞

**Comment by engram-design** [comment]
@AugustMiller Yeah, you're right, seems like I wasn't hitting the token expiry (hence not prompting for a new token), but removing everything and starting fresh does throw that issue.

Added a date check, but will also add a note to the changelog as a heads-up for ConstantContact users that _shouldn't_ be a breaking change. https://github.com/verbb/formie/commit/3819d5658e757987314816b86dc484f36bccc23d

**Comment by AugustMiller** [comment]
TIL `DateTimeHelper::isInThePast()`!

Glad you implemented these methods instead of properties. 😉 Thanks again for your quick action here. I'll let you know if we get any more comms from CC.

**Comment by engram-design** [comment]
Fixed in [1.5.10](https://github.com/verbb/formie/releases/tag/1.5.10)

**Comment by AugustMiller** [comment]
Hey, sorry to revisit this… In swapping out our keys, I think we've discovered another pain-point in this migration process.

Each key pair appears to be non-interoperable with the other auth system, so old keys won't work with the new endpoints, and new keys won't work with the old endpoints. This means that there's a sort of precise "inflection" point that will likely require a developer's input—or that the date-based cutover is only tenable if the API keys are _also_ swapped at that moment. 😩

I'm wondering if this basically means we need a second ~~V3~~ (uhh, see below) integration class that can be switched on-demand?

(Aside: there's no name for this new auth system… “V3” is the current _API_ version, but both generations of authorization were built on OAuth2, despite one of the old auth URLs including a `v3` segment, and both new auth URLs including a `v1` segment. I can't imagine we're the only two people confused by whatever is going on over there… 🤔)

For reference, I added this to our project, and it seems to work—but requires that the person updating to another 1.5.x release is aware of the change and actually makes the update to their integration config!

```php
<?php

namespace modules\myproject\formie\integrations\emailmarketing;

use Craft;
use craft\helpers\DateTimeHelper;
use craft\helpers\StringHelper;

use verbb\formie\integrations\emailmarketing\ConstantContact as BaseConstantContact;

class ConstantContact extends BaseConstantContact {
    /**
     * @inheritDoc
     */
    public function getAuthorizeUrl(): string
    {
        return 'https://authz.constantcontact.com/oauth2/default/v1/authorize';
    }

    /**
     * @inheritDoc
     */
    public function getAccessTokenUrl(): string
    {
        return 'https://authz.constantcontact.com/oauth2/default/v1/token';
    }

    /**
     * @inheritDoc
     */
    public static function displayName(): string
    {
        return Craft::t('formie', 'Constant Contact (Patch)');
    }

    /**
     * @inheritDoc
     */
    public function getSettingsHtml(): string
    {
        // Force use of the base class's template—in order to tell the items apart, I've overridden the `Display Name` that was used to dynamically build this, which breaks the relationship to the template:
        return Craft::$app->getView()->renderTemplate('formie/integrations/email-marketing/constant-contact/_plugin-settings', [
            'integration' => $this,
        ]);
    }
}
```

…and this, in `Module::init()`:
```php
use yii\base\Event;
use verbb\formie\events\RegisterIntegrationsEvent;
use verbb\formie\services\Integrations;
use modules\myproject\formie\integrations\emailmarketing\ConstantContact as ConstantContactIntegration;

Event::on(
    Integrations::class,
    Integrations::EVENT_REGISTER_INTEGRATIONS,
    function (RegisterIntegrationsEvent $e) {
        $e->emailMarketing[] = ConstantContactIntegration::class;
    });
```

**Comment by engram-design** [comment]
I will mention that I _did_ just [add](https://github.com/verbb/formie/commit/582cfe9354040df3ea6f33d21fef53f96df607e1) a `FORMIE_INTEGRATION_CC_NEW_ENDPOINT` .env variable for you to opt-in to the new endpoints, as some other users had already upgraded their apps, and their old ones removed. So that should help in the lead up until April 1st.

But your patch integration would also work!
