### ISSUE TITLE
Modify existing Campaign contact after submission

### ISSUE THREAD

**Issue by andreasbecker** [verbb/formie#776]
I have a Formie form and use the Campaign integration. The form has an email field and a text field. Both fields are mapped to a Campaign contact. So when the form is submitted, a new contact is created in Campaign with both fields filled. What I'm trying to do is the following: if the form is being submitted again with the same email address I want to update the already existing contact in Campaign and concatenate the string in the text field.

How would I accomplish this? Probably, I need to listen to an event. But which one?

**Comment by engram-design** [comment]
So it _should_ be looking for an existing contact, by their email, and if found use that to update.

https://github.com/verbb/formie/blob/37ab9aba6c012f8286ac9d7651b83542483ef38d/src/integrations/emailmarketing/Campaign.php#L111-L119

Is this something you're not seeing? As in, multiple contacts are created when filling in the form with the same email?

**Comment by andreasbecker** [comment]
No, it's working as expected and updates my text field by overwriting its content. But I wanted to keep the old value of the field and concatenate the new one. I tried to hook into the `EVENT_BEFORE_SEND_PAYLOAD` event. But that doesn't seem to fire after submission.

**Comment by engram-design** [comment]
Ah, gotcha! So yes, you'll want to modify the behaviour to update the custom field values before `$contact->setFieldValues($fieldValues);` is called.

```
use verbb\formie\events\ModifyFieldIntegrationValuesEvent;
use verbb\formie\integrations\emailmarketing\Campaign;
use yii\base\Event;

Event::on(Campaign::class, Campaign::EVENT_MODIFY_FIELD_MAPPING_VALUES, function(ModifyFieldIntegrationValuesEvent $event) {
    // Modify the field values that are used to populate the Campaign contact
    $event->fieldValues['someField'] = 'Some Value';
});
```

Here, you can modify `$event->fieldValues` that becomes `$fieldValues` in that snippet shown above.

**Comment by andreasbecker** [comment]
Thank you. That was helpful.
