### ISSUE TITLE
Conditionally save spam submissions

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#777]
**What are you trying to do?**
We get a lot of obvious spam submissions that we'd rather not have saved, which are almost always flagged due to javascript being disabled. It would be great if there were a way to only save certain types of spam submissions for review, while for the rest simply simulating a successful submission on the front end and jettisoning the actual submission content.

**What's your proposed solution?**
One way this could be solved would be to have **Save Spam Submissions** settings for each captcha (or maybe even for different filters within captchas).

Another way would be to raise an event after captchas and spam filters have run and prior to saving the submission. The event would provide a `saveSubmission` event property set to the **Save Spam Submissions** setting that can be overridden.

**Comment by engram-design** [comment]
Not a bad idea having individual spam-saving settings per captcha. I'll mention that we do have an event where you can hook into this behaviour:

```php
use verbb\formie\events\SubmissionEvent;
use verbb\formie\services\Submissions;
use yii\base\Event;

Event::on(Submissions::class, Submissions::EVENT_AFTER_SUBMISSION, function(SubmissionEvent $event) {
    // Has this been flagged as spam?
    if ($event->submission->isSpam) {
        // Check the spam reason and act on it.
        if ($event->submission->spamReason === 'Something') {
            $event->success = true;
        }
    }
});
```

Or:

```
use verbb\formie\elements\Submission;
use verbb\formie\events\SubmissionMarkedAsSpamEvent;
use yii\base\Event;

Event::on(Submission::class, Submission::EVENT_BEFORE_MARKED_AS_SPAM, function(SubmissionMarkedAsSpamEvent $event) {
    $submission = $event->submission;
    $isNew = $event->isNew;
    $isValid = $event->isValid;
    // ...
});
```

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
