### ISSUE TITLE
Can't install plugin when running PHP 7.1

### ISSUE THREAD

**Issue by metamachineco** [verbb/formie#78]
I have a site running on PHP 7.1. When I try to install Formie i get the following error:
![formie](https://user-images.githubusercontent.com/49475229/91980112-0e70c380-ed27-11ea-9c55-5fde30f64e42.png)

**Steps to reproduce**
1. Craft installation running PHP 7.1
2. Tell Composer to load the plugin `composer require verbb/formie`
3. In the Control Panel, go to Settings → Plugins and click the “Install” button for Formie.

**Additional info**
- Plugin version: 1.2.1
- Craft version: 3.5.8
- Multi-site: No

**Additional context**
Updating PHP to 7.4 fixed the issue.

**Comment by engram-design** [comment]
Should be fixed in [1.2.2](https://github.com/verbb/formie/releases/tag/1.2.2)
