### ISSUE TITLE
Recaptcha loaded using async and defer?

### ISSUE THREAD

**Issue by nickdunn** [verbb/formie#782]
**Description**

The Google reCAPTCHA script tag uses both async and defer.

```
<script id="FORMIE_RECAPTCHA_SCRIPT" src="https://www.recaptcha.net/recaptcha/api.js?onload=formieRecaptchaOnLoadCallback&amp;render=explicit&amp;hl=en-GB" async="" defer=""></script>
```

My understanding is if both are specified async takes priority (https://stackoverflow.com/a/55389033). In this example though, do we actually want defer i.e. delay the loading of reCAPTCHA for as long as possible.

I've spotted it in my core web vitals reports and it got me wondering.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/39560/155993752-25a82dc0-00cd-45bb-b43b-5ffefbb643ca.png">

**Comment by engram-design** [comment]
Hmm, good point, but purely going off what they suggest https://developers.google.com/recaptcha/docs/display.

Generally, I think the `defer` option for scripts loaded in the footer does nothing.

> The `defer` attribute tells the browser not to wait for the script. Instead, the browser will continue to process the HTML, build DOM. The script loads “in the background”, and then runs when the DOM is fully built.

If the script tag is at the bottom of the page, the HTML/DOM has already been processed.

`async` is probably the desired option here, but from your report it's just mentioning about reducing the overall third-party scripts, not the way they're loaded?

**Comment by engram-design** [comment]
We'll just make this configurable!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.3](https://github.com/verbb/formie/releases/tag/2.0.3)
