### ISSUE TITLE
Refreshing fields for ActiveCampaign integration return error 500

### ISSUE THREAD

**Issue by giorgiopogliani** [verbb/formie#785]
**Steps to reproduce**
1. Create a form with an Active Campaign integration (I am currently on a lite plan)
2. Refreshing fields in integration results in a 500 error: API error: “{"message":"Forbidden"}”

**Additional info**
- Plugin version: 1.5.10
- Craft version: 3.7.27.2
- Multi-site: Yes

**Additional context**
I found the problem in `verbb\formie\integrations\crm\ActiveCampaign` [here](https://github.com/verbb/formie/blob/582cfe9354040df3ea6f33d21fef53f96df607e1/src/integrations/crm/ActiveCampaign.php#L93), the `dealGroups` request was failing for some reason. After I commented that request everything worked as usual.

**Comment by engram-design** [comment]
Are you able to have a look in your `storage/logs/formie.log` file for the full error? It should give us some more information about the error, but for my account this seems to be okay. There might very well be a difference in our two ActiveCampaign accounts.

**Comment by engram-design** [comment]
Additionally, if you want to run the following command which does the same thing as that line does:

```
curl --request GET \
     --url 'https://xxxxxx.api-us1.com/api/3/dealGroups?limit=100' \
     --header 'Accept: application/json' \
     --header 'api-token: xxxxxxx'
```

Replacing the appropriate values with your own. If you don't get an error, the issue must've been something else.

**Comment by DavidKabelitz** [comment]
@engram-design 
we had the same issue with Pardot Integration from Salesforce. The log at Salesforce shows that login was successful. So the Plugin is connected. While testing the connection at the form itself, clicking to "Refresh" we got a 500 error back.

That's the error from the logs:
`Partdot Integration: API error: "Syntax error" /var/www/craft/vendor/yiisoft/yii2/helpers/BaseJson.php:147
20	12:53:32.448	
< 0ms >
error	verbb\formie\errors\IntegrationException	verbb\formie\errors\IntegrationException: API error: “Syntax error” /var/www/craft/vendor/yiisoft/yii2/helpers/BaseJson.php:147 in /var/www/craft/vendor/verbb/formie/src/base/Integration.php:169
Stack trace:
#0 /var/www/craft/vendor/verbb/formie/src/integrations/crm/Pardot.php(315): verbb\formie\base\Integration::apiError(Object(verbb\formie\integrations\crm\Pardot), Object(yii\base\InvalidArgumentException))
#1 /var/www/craft/vendor/verbb/formie/src/base/Integration.php(387): verbb\formie\integrations\crm\Pardot->fetchFormSettings()
#2 /var/www/craft/vendor/verbb/formie/src/controllers/IntegrationsController.php(156): verbb\formie\base\Integration->getFormSettings(false)
#3 [internal function]: verbb\formie\controllers\IntegrationsController->actionFormSettings()
#4 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction(‘form-settings’, Array)
#7 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction(‘formie/integrat...’, Array)
#8 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction(‘formie/integrat...’, Array)
#9 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/craft/web/index.php(21): yii\base\Application->run()
#12 {main}`

**Comment by engram-design** [comment]
@DavidKabelitz It's a different issue just for Pardot, but fixed for the next release.
