### ISSUE TITLE
Allow inner group/repeater fields to be used in integration field mapping

### ISSUE THREAD

**Issue by mikos** [verbb/formie#79]
**Description**
When setting up field mapping on a Mailchimp integration on a form with fields within groups you can only select the groups to map and not the fields within them.

**Steps to reproduce**
1. Create a form with fields within groups
2. Attempt to set up field mapping on a Mailchimp integration

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.1
- Craft version: 3.5.8
- Multi-site: No

**Comment by engram-design** [comment]
Yep, so groups and repeater fields are unavailable to be mapped for integrations for the moment. We'll work on adding this support.

**Comment by engram-design** [comment]
Should be fixed/added in [1.2.7](https://github.com/verbb/formie/releases/tag/1.2.7)
