### ISSUE TITLE
Import validation error with a field containing a placeholder with only a number

### ISSUE THREAD

**Issue by Tim-Wils** [verbb/formie#790]
Couldn't find if this was already fixed in the last month, because my export was done on 2022/02/04. The import was done today with the latest version. Here goes anyways, please close this if it's already fixed :)

**Description**
Importing a form with a field containing only a number as a placeholder results in a Validation Error, because placeholder needs to be null or a string and is exported as an integer.

**Steps to reproduce**
1. Create a form
2. Create a single line text field (like a housenumber) with a placeholder with only a number (70 in my case)
3. Export the form as a JSON.

The JSON will look like this:
`..."matchField": null,
"placeholder": 70,
"defaultValue": null,...`

And should be this:
The JSON will look like this:
`..."matchField": null,
"placeholder": "70",
"defaultValue": null,...`

**Comment by engram-design** [comment]
Yup, so looks like that's an issue until Craft 4, where stricter typing has been introduced. For now, it'll be best to ensure that's a string value in your export. This should be working correctly in 2.0.0-beta.1.
