### ISSUE TITLE
Add Envelope-From and Header-From fields for Email Notification

### ISSUE THREAD

**Issue by watarutmnh** [verbb/formie#792]
**What are you trying to do?**
Email notification has "From Email" field to set the senders email address.
It could be set the collected email address from submission.
However, because the domain of the email address is different from the domain of the system, it may be evaluated as spoofing email an not reach the recipient.

**What's your proposed solution?**
I would suggest to have Envelope-From and Header-From fields.
Header-From can be freely described by the sender due to the specifications of the email, it is possible to display information different from the actual sender.

**Comment by engram-design** [comment]
First I've heard of these settings for emails! I think they're pretty advanced for even tech-savvy clients, so we might want to hide them under Advanced > Headers or something similar. Which might be nice to be able to add other header information as well.

But yes, typically for mail delivery (in general), it should be sent from the same domain (or authorised one) as the mailer service. This might be an SMTP server, or a third-party service like Sendgrid or Mailgun. Having it sent by the recipient is risky for the reasons you've stated. For this reason, I'd recommend using the sender email in the Reply To field for optimum delivery.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.12](https://github.com/verbb/formie/releases/tag/2.0.12)
