### ISSUE TITLE
Allow Repeater and Table field `templateHtml` from GraphQL to contain row templates

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#793]
The Table and Repeater field both use a script tag `<script type="text/template" data-repeater-template="{{ field.handle }}”>` as a template for new rows. On a non-headless setup, this uses Craft’s Twig `{% script %}` tag to add it to the body of the page. This is because some JS frameworks (Vue 2/3) can’t handle inline `<script>` tags within an application instance. Hence the need to add it to the body, or header.

However for headless scenarios, this doesn't work, and is missing from the `templateHtml` param. We need to provide this alongside GQL queries.

**Comment by Ocupe** [comment]
@engram-design thanks for opening the issue and sorry for the multiple requests. 🤦‍♂️ It was not my intention to build pressure or annoy you.

I await with anticipation a solution for headless repeater. :)
Let me know if I can help in any way, test anything, or otherwise assist.

**Comment by engram-design** [comment]
Totally fine! I'll have to do some investigation to see what we can do here, and will let you know.

**Comment by lukasIO** [comment]
does anything speak against a separate `scripts` field that simply holds the js resource paths? then everyone could insert script tags in any framework however they like as long as the cors headers are correct.

**Comment by engram-design** [comment]
@lukasIO That would be the idea, to provide the JS for the form and fields with the GQL queries, likely as a `scripts` parameter. This should be easy enough for the fields (which this issue is about), because the JS is quite self-contained. But other JS like the Formie theme stuff is a much different issue, that heavily relies on the markup of the form.

**Comment by lukasIO** [comment]
Makes sense, the way we handled this in the past was to load other formie scripts statically. I didn't want to expand the scope of the issue at all, I only meant to address the repeater (and table field) scripts.

**Comment by Ocupe** [comment]
@engram-design is there a workaround we can use until an official solution is found?

**Comment by engram-design** [comment]
I've just added this behaviour for the next version. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.12",
  "...": "..."
}
```

Then run `composer update`. 

You'll need to include the new `includeScriptsInline` render option when calling `templateHtml`, like so:

```
{
  form (handle: "gql") {
    templateHtml(options: "{\"includeScriptsInline\": true}")
  }
}
```

As `options` requires a JSON-string of render options passed to it. Now scripts will be rendered inline.

I'll also say that using server-side rendered HTML probably goes against a typical headless project, because you're expected to BYO templates for the form as part of your headless front-end templates. It's certainly possible to do so, but you'll likely have more flexibility rolling your own forms yourself (take a peek at the [Formie Headless Demo](https://github.com/verbb/formie-headless))

**Comment by lukasIO** [comment]
@engram-design thanks for your fix. Is there any additional setting we have to set (other than `includeScriptsInline`) ? 
Currently the resulting `templateHTML` does not include the row template for the repeater fields.

**Comment by engram-design** [comment]
That should be all you have to do, unless you're using template overrides. Then you'll want to ensure the changes I've made [here](https://github.com/verbb/formie/commit/f59d9c3b0039083ccab8e511f5c970ba46d004be) are made in your custom templates.

Otherwise, they certainly should be showing inline with the HTML.

**Comment by lukasIO** [comment]
thanks for the fast response. we'll double check on our side, might be that the gql client we are using is messsing with the additional options.

**Comment by engram-design** [comment]
Fixed in [1.5.13](https://github.com/verbb/formie/releases/tag/1.5.13) - let me know if it's still an issue @lukasIO

**Comment by lukasIO** [comment]
@engram-design sorry for the delay, just had a look again. 
The frontend-part is working as expected (i.e. clicking on "add row" creates more rows of the repeater field and `remove` removes them again). However the newly added rows don't show up in the submission in craft. 
If I have a minimum of three rows for the repeater field, then those three will show up with the data that I have submitted. If I try to add more, the rest is seemingly ignored. 
The fields are there (I can see them in the dom tree). 
Do you have an idea what we could be doing wrong?

for context: 
we are using the submissions api with
```
formEl.setAttribute('action', CMS_HOST + '/actions/formie/submissions/api');
```
and the formie submission settings set to AJAX.

**Comment by engram-design** [comment]
Are you able to inspect the HTML generated by the adding of new rows and send through? Or, have a look at the request payload being sent to the server (inspecting the Network request in web developer tools). It sounds like something might not be getting processed correctly.

The HTML for these fields does contain a placeholder `__ROW__` that should be getting replaced with JS when you create a new row. This is to ensure data is formatted correctly when sending it to the server.

**Comment by lukasIO** [comment]
Thanks, I just sent both the html tree and the request payload to you via mail with the subject `Additional context re: verbb/formie/issues/793`

**Comment by engram-design** [comment]
@lukasIO Thanks for sending that through. It looks as though the fields are being double-namespaced to include “fields” twice:

What it’s showing:
```
fields[fields][images][rows][new1][fields][caption]
```
What it should be:
```
fields[images][rows][new1][fields][caption]
```

Should be fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.15",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukasIO** [comment]
@engram-design confirmed it's working now! thank you!
