### ISSUE TITLE
Submit Button disabled attribute

### ISSUE THREAD

**Issue by joepagan** [verbb/formie#795]
**Description**

I feel like an absolute mug for asking about something seemingly simple but here we are.

I have an issue where a form's submit button has the disabled attribute set on it, despite all the frontend form inputs being populated, it never seems satisfied.

I can see there is some JS functionality where it is disabled while it is loading, then it should be removed, not sure if that removal isn't working or if this is something else.

Maybe some validation is missing and it's not being reported on the frontend?

- No form setting appears to force it on
- No global formie setting appears to force it on
- reCAPTCHA is on
- no console errors
- all fields populated does change
- the twig templates are not overriding any value
- manually removing the disabled attribute via dev tools allows a successful submission

Do you have any suggestions on what else I can look for?

**Steps to reproduce**
1. create form
2. view on frontend, populate fields
3. submit button still disabled

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: "verbb/formie": "1.5.8",
- Craft version: "craftcms/cms": "3.7.32",
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Strange. Are you able to inspect the Network tab in web developer tools for the Ajax request to submit once you've pressed submit? And just to be clear, is the button disabled **before** you hit submit, or after? It should be disabled once you press it to prevent multiple submissions, but it should never be disabled beforehand.

**Comment by joepagan** [comment]
Sorry for the noise on this, I completely forgot I had some custom logic to disable these buttons while waiting for a CSRF. 
A completely self-made problem.

I have been so used to working with loading all my js in the footer for years that on this vite app where it loads in the head I needed a domcontentloaded event to remove the disabled attribute.
