### ISSUE TITLE
Composer requirements: Formie incompatible with Social Poster

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#80]
**Description**

The latest update to Formie appears to have incompatible composer requirements with Social Poster.

I get a bit fight over guzzlehttp/oauth-subscriber:
Formie wants ^0.4
Social Poster wants ^0.3

To update to Formie 1.2 I had to first remove Social Poster.
But then I can't reinstall Social Poster.

**Steps to reproduce**
1. Install Social Poster
2. Try to install Formie

- or vice versa

### Form settings
n/a

**Additional info**
- Plugin version: Social Poster 2.1, Formie 1.2
- Craft version: Craft Pro 3.5.8
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.2.3](https://github.com/verbb/formie/releases/tag/1.2.3)
