### ISSUE TITLE
Cannot use `title` as a form handle

### ISSUE THREAD

**Issue by joshuabaker** [verbb/formie#803]
### Description 

It’s currently not possible to save a field with the handle `title`.

<img width="573" alt="Screenshot 2022-03-21 at 15 42 59@2x" src="https://user-images.githubusercontent.com/160484/159298353-b3d85b13-8df4-4bbb-94e9-cf6a1d227e71.png">

This is a really common use case.

Might this be conflicting with the form ‘Name’ field that uses `name="title"` in the control panel?

### Additional info
- Plugin version: 1.4.23
- Craft version: Craft Pro 3.7.20
- Multi-site: Yes

**Comment by engram-design** [comment]
We're just inheriting reserved words from Craft, of which `title` is a reserved word and cannot be used as a regular Craft field. To confirm this, try and create a regular Craft field with the handle `title`.

This is because when you access `form.title` it doesn't know if it's referring to the Form element's title, or the custom field `title`. Nothing to do with the attributes for the HTML.

**Comment by joshuabaker** [comment]
Thanks, Josh. I’m familiar with both of those. 😊

Am I assuming this is a wontfix?

The case here is that a `title` field (Mrs, Ms, Mr, etc) is actually an incredibly common use case for forms, and the downstream dependency is to match a predefined set of field handles within another system.

**Comment by engram-design** [comment]
More like, I don't think I _can_ fix it even if I wanted to! When you call `submission->title` we've got no way of knowing how to deal with it (do you want the field or the title of the submission).

And yeah, that's a fair call. I'm not sure if you're using an integration, but the mapping does help to alleviate that, as they don't need to be the same. But it's entirely based on your use-case and what you're trying to do of course.

I'll continue to think about it our options, but I don't think there's anything I can do that's elegant, backwards-compatible and isn't anti-Craft.

**Comment by engram-design** [comment]
Yeah, sorry I don't think this is something we can fix, just a limitation of Craft and how custom fields in elements work. Sorry!
