### ISSUE TITLE
Custom HTML email templates not loading – No such file or directory

### ISSUE THREAD

**Issue by toddpadwick** [verbb/formie#809]
I am attempting to set up custom email templates.
We have saved the following templates in the craft templates directory:
`_emails/templates/default.twig` // this is our main email template, which extends a layout and also renders the contentHtml data.
Our email layout is saved here:
`_emails/_layouts/main.twig` // this contains all the HTML CSS, and wrapper, which we can then use for multiple email notifications.

When we create a new email template in formie, it successfully finds this template in the path finder.

But when we try and preview the notification when creating a form, we get this error:

```
Notification email template parse error for “_emails/templates/default.twig”. Template error: 
“file_get_contents(/app/templates/_emails/templates/default.twig): Failed to open stream: No such file or directory” 
/app/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:60
```

I've tried not extending the layout and just having the contentHtml in the template, but that doesn't work either.

**Comment by engram-design** [comment]
I can't replicate this I'm afraid - with your exact template setup. Does sending a notification work when actually filling out a form? I'm wondering if this might be similar to your other issue https://github.com/verbb/formie/issues/791 being on Fortrabbit - or maybe this is locally?
