### ISSUE TITLE
Add Integration support for Campaign plugin

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#81]

**Comment by engram-design** [comment]
Added in [1.2.6](https://github.com/verbb/formie/releases/tag/1.2.6)

**Comment by AndrewMac** [comment]
Thanks so much for the quick work on this. I tried this integration (on a test site, it must be said) and I got the error below. Any idea what I might have done wrong? Thanks!

yii\base\UnknownPropertyException: Setting unknown property: verbb\formie\events\IntegrationEvent::isNew in /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\BaseObject->__set('isNew', true)
#1 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\formie\events\IntegrationEvent), Array)
#2 /Users/andrew/Sites/dev/craft-test/vendor/verbb/formie/src/services/Integrations.php(312): yii\base\BaseObject->__construct(Array)
#3 /Users/andrew/Sites/dev/craft-test/vendor/verbb/formie/src/controllers/IntegrationsController.php(82): verbb\formie\services\Integrations->saveIntegration(Object(verbb\formie\integrations\emailmarketing\Campaign))
#4 [internal function]: verbb\formie\controllers\IntegrationsController->actionSaveIntegration()
#5 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#7 /Users/andrew/Sites/dev/craft-test/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('save-integratio...', Array)
#8 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-integratio...', Array)
#9 /Users/andrew/Sites/dev/craft-test/vendor/craftcms/cms/src/web/Application.php(280): yii\base\Module->runAction('formie/integrat...', Array)
#10 /Users/andrew/Sites/dev/craft-test/vendor/craftcms/cms/src/web/Application.php(583): craft\web\Application->runAction('formie/integrat...', Array)
#11 /Users/andrew/Sites/dev/craft-test/vendor/craftcms/cms/src/web/Application.php(259): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /Users/andrew/Sites/dev/craft-test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /Users/andrew/Sites/dev/craft-test/web/index.php(21): yii\base\Application->run()
#14 {main}

**Comment by engram-design** [comment]
Should be fixed in [1.2.7](https://github.com/verbb/formie/releases/tag/1.2.7) - let me know if not!

**Comment by AndrewMac** [comment]
Hello again, and sorry. Yes, 1.2.7 does solve that problem. But now I have run into something else ... I get the Campaign list showing up in Formie, along with all the Campaign fields. Only problem is that I don't have my Formie fields showing up in the 'field mappings' section—and yes, there are definitely fields in the form. I have tried with name and email fields, and also plain text fields. And I've also tried refreshing the Campaign selection field, as well as removing the integration and creating a new one.

But it's all the same, so without being able to map the email address I'm stuck.

By the way, the same thing happens with a MailChimp integration I set up as a test, to check it wasn't just the Campaign integration. Do you happen to know if anyone else has reported a similar issue? Or do you have any ideas on what might be going wrong. 

Other than this teensy little issue, Formie is looking better and better all the time!

Screenshot below:

![CleanShot-2020-09-07 2](https://user-images.githubusercontent.com/70342/92382630-3fe6f600-f150-11ea-9aa4-cdb1f4839d58.png)

**Comment by engram-design** [comment]
Huh, that's odd. Any JS errors? Have you refreshed the page after the form has been saved? It should be grabbing all available fields from the Vuex store - in fact that list should refresh in real-time as you manage your fields. No reports of this yet, and haven't seen this happen!

And the field type shouldn't matter - it should show all fields.

**Comment by engram-design** [comment]
Ah, I can reproduce this, and I think I know why

**Comment by engram-design** [comment]
Should be fixed in [1.2.7.1](https://github.com/verbb/formie/releases/tag/1.2.7.1), sorry about that.
