### ISSUE TITLE
Twig support for field instructions

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#814]
**What are you trying to do?**
I have a multilingual (English/Thai) site that uses Formie. I need to have all form text in both Thai and English, but I cannot get the field instructions to translate. Those instructions only seem to support the default Formie text input. The best solution would be to allow the instructions field to support Twig, so I could set it to a global variable that lets editors/translators set the text of the instructions.

**What's your proposed solution?**
Formie field instructions support Twig variables.

**Comment by engram-design** [comment]
You should be able to use static translations to translate any field text with the `site.php` file. Is that not working?

As for supporting Twig, that's already on our list https://github.com/verbb/formie/issues/661

**Comment by AndrewMac** [comment]
Thanks so much, as always, for your quick response. I worked out that the static translation was working, but in this case it had a teensy little typo that meant it didn't quite match what was in the site.php translation file.

So static translation is working, and that's okay for now, but it will be great if you are one day able to add Twig support. It looks like our team ran into this issue because the instruction text was a few sentences long, and our editor changed a single letter in Formie but didn't let me know of the text change ... which it took me a while to notice.

So, if you ever do get Twig support added it will help with that kind of issue a lot. The editors can do what they want with their language in a global field, and the developer can relax ;-)

Cheers, Andrew

**Comment by engram-design** [comment]
Yep, the long-term solution will be proper multi-site support for forms and their fields, which is quite a bit of work, and I think reliant of Craft's concept of field instances (scheduled for Craft 4, but pushed out to Craft 5). As such, we're going to have to wait until then for proper, full multi-site, and multi-language support for fields, and all their settings.

But in the short-term, we'll be adding Twig capabilities to instructions, among other settings for fields.

**Comment by engram-design** [comment]
Closing and following up in https://github.com/verbb/formie/issues/661 (I'm not going to go ahead with this).
