### ISSUE TITLE
Email Preview Notification 500 error

### ISSUE THREAD

**Issue by helleholmsen** [verbb/formie#815]
Hi!

I'm getting this error in the email preview notification tab:
<img width="1097" alt="Skjermbilde 2022-04-04 kl  11 48 47" src="https://user-images.githubusercontent.com/31032804/161519245-0abedb37-a11c-47b0-bb68-48dc82996cb4.png">

craft cms v. 3.7.37
formie v. 1.5.12

**Comment by engram-design** [comment]
Are you able to submit a support request within Formie on this one? I'll need some information about your field setup. You can find this via Formie > Settings > Get Support.
