### ISSUE TITLE
How can i load the form spesific js on ajax load?

### ISSUE THREAD

**Issue by helleholmsen** [verbb/formie#817]
On a normal page load it works, but on ajax load the form specific js wont work. I have tried:

`{{ craft.formie.renderFormJs('myForm') }}`

it does not render anything. And i have tried this in my own js file:

`import { Formie } from "../../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib";`
```
     if (Formie) {
        Formie.initForms();
      }
```

but it gives me this error:

`Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1__vendor_verbb_formie_src_web_assets_frontend_src_js_formie_lib__.a.initForms is not a function`

**Comment by engram-design** [comment]
I'm not really sure what you mean by "ajax load" sorry. Do you mean you want to initialise the form theme JS on-demand when you load the form's HTML via Ajax? 

There should be no problem calling `Formie.initForms();` after your ajax callback (whatever form that takes) as per the [docs](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules). I can see you're importing the `formie-lib` class which you can use to initialize forms. I'm not sure why that's throwing a webpack-style error though.

**Comment by helleholmsen** [comment]
Hi! Sorry if I was unclear. I'm using ajax for loading the whole page, not just the form. So for example, when I'm doing a regular page load the phone field looks like this (like it should):
<img width="797" alt="Skjermbilde 2022-04-05 kl  13 30 10" src="https://user-images.githubusercontent.com/31032804/161744663-daab133e-587b-4fa0-871a-13938d1f0783.png">

But on ajax load the field looks like this:

<img width="789" alt="Skjermbilde 2022-04-05 kl  13 29 59" src="https://user-images.githubusercontent.com/31032804/161744690-b30ccb3e-618a-4e79-bd98-2a4260f175af.png">

So I'm guessing I need some way to load the Formie js (the script highligted) on an ajax request:
<img width="1305" alt="Skjermbilde 2022-04-05 kl  13 43 02" src="https://user-images.githubusercontent.com/31032804/161746577-8cb88b35-a9b1-41ea-b139-93b0bd7f7686.png">

**Comment by engram-design** [comment]
Gotcha, yep so the HTML is lazy-loaded via Ajax, and you want to initialise the JS once it's loaded.

I'm not a Webpack expert by any means, but that error seems strange. There certainly is an export `Formie` in that [file](https://github.com/verbb/formie/blob/5176a188ee60858bb9c5ed4c8241bcab66b62364/src/web/assets/frontend/src/js/formie-lib.js#L6)

I've done this a few times with success:

```
const { Formie } = await import('~/../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib');
const formie = new Formie();

const $form = document.getElementsByTagName('form');

formie.initForm($form);

```

**Comment by helleholmsen** [comment]
It still won't work. The error message it's giving me now is:

`Uncaught TypeError: $form.getAttribute is not a function`

Also, do I need to change the javascript render location to "manual" in order to get the 
`{{ craft.formie.renderFormJs('contactForm') }}` to work? It wont render anything. 

<img width="1588" alt="Skjermbilde 2022-04-05 kl  14 26 49" src="https://user-images.githubusercontent.com/31032804/161753604-1f9caed8-bb05-43ea-8436-f87949e23934.png">

**Comment by helleholmsen** [comment]
I'm also trying to do it manually just to test, but it's still not working:

```
      function loadScript(href_script, callback) {
        var script = document.createElement("script");
        script.src = href_script;
        script.onload = callback;
        var x = document.getElementsByTagName("script")[0];
        x.parentNode.insertBefore(script, x);
      }

      //load formie scripts
      if ($(".form--formie").length > 0) {
        loadScript(
          "//localhost:3002/cpresources/ad991129/formie.js?v=1649059415"
        );
      }
```

**Comment by helleholmsen** [comment]
Me again. When doing it manually it kind of works, but it's still not loading for example:

`<script src="//localhost:3002/cpresources/4c3db3f5/phone-country.js?v=1649059414" defer=""></script>`

so how can i load those scripts manually?

**Comment by engram-design** [comment]
I would recommend you render your CSS/JS inline with the form. That way, when you load the HTML for the form, you'll get the CSS and JS for it.

Alternatively, you can render the CSS/JS on the parent page, but that's a little wasteful if the page doesn't contain a form. This is because we add CSS to the header and JS to the footer with Craft/Yii's asset rendering. But that won't carry across for Ajax-loaded content (it doesn't know to load in CSS/JS into the header/footer - it just handles the HTML).

So I've just put a quick example together.

First, create a new Form Template, set the CSS/JS to "Manual" as their render location.

Your parent HTML template might look like:

```twig
<div class="form-wrap"></div>
<button class="js-load-form">Load Form</button>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$('.js-load-form').on('click', (e) => {
    e.preventDefault();

    $('.form-wrap').load('form.html', function() {
        Formie.initForms();
    });
});
</script>
```

I'm using jQuery for simplicity here, but whatever you're using to load the form template with would be similar. In the callback, you'll had access to `window.Formie` where you can init your form. You can double check the CSS/JS is loaded inline with your form, as it should show the similar output to the below:

```
<div class="form-wrap">
    <link href="http://formie.test/cpresources/f22d593e/formie-theme.css?v=1648511444" rel="stylesheet">
    <script src="http://formie.test/cpresources/430c0f29/formie.js?v=1648508521" defer=""></script>
    <script type="text/javascript"></script>
    <div class="fui-i"></div>
```

The **form.html** file would look like:
```
{{ craft.formie.renderFormCss('contactForm') }}
{{ craft.formie.renderFormJs('contactForm') }}
{{ craft.formie.renderForm('contactForm') }}
```

**Comment by helleholmsen** [comment]
Thank you again for your response. But the problem is, if I render the CSS and JS inside the form it still wont load additional js like these scripts:

```
<div data-fui-scripts="105088">
  <script src="//localhost:3002/cpresources/4c3db3f5/phone-country.js?v=1649059414" defer=""></script>
  <script src="//localhost:3002/cpresources/4c3db3f5/checkbox-radio.js?v=1649158171" defer=""></script>
</div>
```

**Comment by engram-design** [comment]
I've actually ended up refactoring things a little with the `renderFormCss()` and `renderFormJs()` functions to better handle things. Firstly, you won't be required to set the render location on your Form Templates anymore - these functions will override that.

Secondly, it'll now capture CSS/JS files that would otherwise be added to the header/footer of the page, which won't happen in this instance where loaded via Ajax.

To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by helleholmsen** [comment]
Thank you. I tried that, but it still wont load the additional scripts :/

**Comment by helleholmsen** [comment]
Is there maybe a way to load all the scripts on page load if there isn't a form on that page? That way the scripts will always be there but it might be a solution for now.

**Comment by engram-design** [comment]
So there's no `data-fui-scripts` added to the page once you call `Formie.initForms();`?

If you call those CSS/JS render function on the parent template, where you're loading from, does that help?

How're you Ajax-loading your template by the way?

**Comment by helleholmsen** [comment]
Ok, so this is how my contact.twig looks like (its just a single section):

```
{% extends (craft.app.request.isAjax and not craft.app.request.isLivePreview) ? "layouts/ajax-layout" : "layouts/base" %}
{% set form = entry.formFormie.one() ?? null %}

{% block content %}
  <div class="js-ajax-wrapper">
    {% if form %}
      <div class="form form--formie grid-item">
        {{ craft.formie.renderForm(form) }}
      </div>
      {{ craft.formie.renderFormJs(form) }}
    {% endif %}
  </div>
{% endblock %}

```

ajax-layout looks like this:
```
{% block content %}
  {% block content %}{% endblock %}
{% endblock %}
```

Then I'm just doing a regular jquery post request to get the data and add it to a container. 
When it comes to the JS I'm importing Formie like this:

`import { Formie } from "../../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib";`

I have tried:

```
if (window.Formie) {
  window.Formie.initForms();
}
```

It gives me this error message:
`Uncaught TypeError: window.Formie.initForms is not a function`

and
```

if (Formie) {
  Formie.initForms();
}
```

gives me:

`Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1__vendor_verbb_formie_src_web_assets_frontend_src_js_formie_lib__.a.initForms is not a function`

Console logging "Formie" gives me this:
```
ƒ Formie() {
        _classCallCheck(this, Formie);

        this.forms = [];
    }
```

**Comment by engram-design** [comment]
So I mentioned this in my example in https://github.com/verbb/formie/issues/817#issuecomment-1088631059 that `Formie` is the class in that file, but needs to be instantiated.

```
import { Formie } from "../../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib";

const formie = new Formie();
formie.initForms();
```

**Comment by helleholmsen** [comment]
Oh ok! Thank you! Finally got it working now :) I set the JavaScript Render Location to be inside the form and in the twig template:

```
{% set form = entry.formFormie.one() ?? null %}
{% if form %}
  {{ craft.formie.renderFormCss(form) }}
  {{ craft.formie.renderFormJs(form) }}
  <div class="form form--formie grid-item">
    {{ craft.formie.renderForm(form) }}
  </div>
{% endif %}
```

And on ajax load:
```
if ($(".form--formie").length > 0) {
  const formie = new Formie();
  formie.initForms();
}
```

Thank you so much for your help!

**Comment by engram-design** [comment]
Ah, no problem - thanks for your persistence with this. Sorry for the lengthly back-and-forth!

**Comment by helleholmsen** [comment]
@engram-design i was a bit fast in saying that it worked. right now i have another problem. the site im working on is a multisite and on one of the pages i get this error:

`Mixed Content: The page at 'https://www.akjfof.com/contact' was loaded over HTTPS, but requested an insecure script 'http://www.akjfof.com/cpresources/f0381778/phone-country.js?v=1649240829'. This request has been blocked; the content must be served over HTTPS.`

![slack-imgs](https://user-images.githubusercontent.com/31032804/162181720-48558a7c-bf50-46d8-aa8a-fc2397bf76b7.jpg)

Where is this url coming from and why is it wrong?

**Comment by engram-design** [comment]
I don't think that'll be a Formie issue, as those assets are using the `siteUrl` setup by Craft. I would double check all your Site Base URLs are setup correct, and are consistently using HTTPS (or HTTP - just pick which one you're going with).

For instance https://github.com/verbb/formie/blob/ef68449087c545d8b4d5ffa1c5d47e3c4390b000/src/fields/formfields/Phone.php#L141

Here, `Craft::$app->getAssetManager()->getPublishedUrl()` will resolve according to your primary site base URL.

It also depending on how you're ajax-loading the page. If you're requesting it over HTTP, then it's going to consider it on a non-SSL request.

Can you share your primary site settings?

**Comment by helleholmsen** [comment]
.env file:

```
PRIMARY_SITE_URL="https://www.akj.com/"
PRIMARY_SITE_URL_TOKEN="https://www.akjtoken.com/"
REPORTS_SITE_URL="https://reports.akj.com/"
FOF_SITE_URL="https://www.akjfof.com/"
```

<img width="1810" alt="Skjermbilde 2022-04-07 kl  14 08 05" src="https://user-images.githubusercontent.com/31032804/162195163-358ecf45-d8f7-42e2-baaa-c37ee226a4d8.png">

So it should be the same for all sites. It's just so weird that it's happening for all sites. The htaccess file should also be the same.

**Comment by engram-design** [comment]
How strange, as you say that all looks correct. Are you using JS to load your template? Are you able to share a snippet of it? Or at least look a the XHR request in the Network tab of web developers tools to see if that itself is being loaded via non-HTTPS?

Craft's asset manager should be using the primary site URL for assets. It's default value is [`@web/cpresources`](https://craftcms.com/docs/3.x/config/config-settings.html#resourcebaseurl) - I'm not sure if you're doing anything with `@web`, but maybe something to try is to override that in your general.php config:

```
'aliases' => [
    '@web' => \craft\helpers\App::env('PRIMARY_SITE_URL'),
],
```

I don't _think_ you need to do this, but worth a shot at least debugging.
