### ISSUE TITLE
Add recipients field

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#82]
Provide a hidden/select/radio/checkboxes field to be used as a notification recipient(s).

Values should be encoded so they aren't visible in the source.

**Comment by daltonrooney** [comment]
Funny enough, my client asked for something like this just this week. They want to be able to choose a notification recipient based on the value of a dropdown field. In Sprout the interface for notifications is completely separate from the interface for forms, so we could get pretty granular on notification routing based on the content of specific fields:

<img width="381" alt="Screen Shot 2020-09-04 at 11 23 44 AM" src="https://user-images.githubusercontent.com/742045/92274014-54519700-eea1-11ea-9748-ebe546cc1e51.png">

In this case, we'd like to have a dropdown like:

I'm interested in...
Sales -> sales@example.com
Support -> support@example.com
Media -> media@example.com

Is that kind of functionality in the works?

**Comment by engram-design** [comment]
Yep, so slightly separate features. One is to be able to use the value of a field in notifications. Whether that field is a dropdown, radio, or even a hidden field and populated via Twig/JS.

The other is being able to conditionally control when the notification is set, which will be a separate conditional builder - https://github.com/verbb/formie/issues/86

**Comment by bartrylant** [comment]
This, or set the notification recipient(s) as a form option. Like this:

```
{% set options = {
    recipient: 'theboss@company.com',
} %}

{{ craft.formie.renderForm('contactForm', options) }}
```

**Comment by engram-design** [comment]
@bartrylant I have considered this, but the issue I have is that what if there are multiple email notifications setup? Does the recipient get added to all of email notifications? 

For this reason, I'd stick with a recipients field that you can select in your notifications editor. You can then use [`craft.formie.populateFormValues`](https://verbb.io/craft-plugins/formie/docs/template-guides/available-variables#craft-formie-populateFormValues) to populate this field in your templates

**Comment by engram-design** [comment]
A recipients field has been added in [1.2.12](https://github.com/verbb/formie/releases/tag/1.2.12)

See docs on setting in a template - https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms#recipients

But otherwise, it acts like any other field. You set how you'd like it displayed (hidden/select/radio/checkboxes), which you can then use in your email notifications.

It has one major benefit over using a regular hidden or email field in that the raw emails aren't rendered client-side, so they're safe from being scraped by bots.
