### ISSUE TITLE
UTM params not saved

### ISSUE THREAD

**Issue by ai5679** [verbb/formie#826]
**Description**
We added UTM parameter fields to a form but they not working correctly. The fields are not captured in submissions. 

**Steps to reproduce**
1. Add a new hidden field with a query param
2. Submit the form
3. Check the submitted form, the params are not captured. The screenshots are attached below. 

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.13
- Craft version: Craft Pro 3.7.38
- Db: PostgreSQL 11.14
- PHP: 7.4.28
- Multi-site: Yes 

**Additional context**
Testing with the following form: https://cms.dev.bkbn.com/en/get-a-quote?utm_campaign=stagingtest1
![image](https://user-images.githubusercontent.com/102757620/162929545-f7e31ca4-feba-4625-872b-327bbd233e98.png)
![image](https://user-images.githubusercontent.com/102757620/162929594-ad325f53-0a73-49b0-aa4a-7fd41a7364c7.png)
![image](https://user-images.githubusercontent.com/102757620/162929813-4e7f9591-436f-4d4d-95ca-6cf5f59e373b.png)
![image](https://user-images.githubusercontent.com/102757620/162929653-1e025b6a-4b8f-4a3e-b5c6-1289a413910a.png)
![image](https://user-images.githubusercontent.com/102757620/162929715-4b929311-d64f-4889-8375-fdf4479f3ab3.png)
![image](https://user-images.githubusercontent.com/102757620/162929765-9e51eb1d-310b-493a-b747-eb14caf83b63.png)

**Comment by engram-design** [comment]
So the hidden field just sets the default value for the field, so you should see the value populated in the field, before you even submit. For example, refer to the below on my setup, replicating yours.

<img width="853" alt="Screen Shot 2022-04-12 at 9 45 35 pm" src="https://user-images.githubusercontent.com/1221575/162953103-d4f9b872-dbca-468c-99a8-f3bf4b000ed5.png">

Do note that there's one instance this might not work, which is for a multi-page form, where you have an incomplete submission on. For example, you've halfway through a form submission, then you add this field, and refresh the page. Because the submission isn't "fresh" the default value won't be populated. I note your form isn't multi-page, but just thought to mention.

Can you confirm if you're not seeing your hidden field value populated, and if not - anything else about your setup worth mentioning, like being headless or not, anything custom template-wise.

**Comment by umkasanki** [comment]
We don't use headless and multipage forms. Just simple twig + bit of js.
Our page code:
```
{% extends "_layout/index.twig" %}

{% block main %}
  {% cache %}
    {% for block in entry.contactsBody.all() %}
      {% include '_inc/sections/' ~ block.type.handle with {
        block: block
      } only %}
    {% endfor %}
  {% endcache %}
{% endblock %}
```
Form section code:
```
{#{% set form = craft.formie.forms.handle('contactForm').one() %}#}
{% set formWidth = block.formWidth != null ? block.formWidth.value : 'small' %}
{% set fieldsStyle = block.fieldsStyle == null ? 'large' : block.fieldsStyle.value %}
{% set formType = formType ?? block.formType %}

{% for form in block.form.limit(1).all() %}
    {% do form.setSettings({
        displayFormTitle: false,
    }) %}

    {% set options = {
        formClasses: [
            'js-content-form',
            fieldsStyle == 'large' ? 'fui-enlarged-form'
        ],
        formDataAttributes: {
            'type': formType != '' ? formType|ascii|kebab : 'no-type-form'
        },
    } %}

    <div id="{{ block.sectionId ? block.sectionId|ascii|kebab : '' }}" class="pb-15 xl:pb-40 js-fade-in">
        <div class="container px-4 mx-auto {{ formWidth == 'small' ? 'sm:max-w-sm' }}">
            <div class="text-24 leading-32 mb-6 lg:text-36 lg:leading-46 lg:mb-20 lg:text-center">
                <h2>{{ block.heading ?? 'Contact Us'|t }}</h2>
            </div>
            {{ craft.formie.renderForm(form, options) }}

            <div id="contact-us-success"
                 class="js-succes-banner mt-10 lg:mt-4 lg:text-center hidden"
                 data-form="{{ form.id }}">
                <div class="text-48 leadimg-60 lg:text-104 lg:leading-114 font-display">
                    <p>{{ 'Thank you'|t }}</p>
                </div>
                <div class="text-24 leading-38 mt-2 mt-4 lg:mt-6 lg:mt-40">
                    <p>{{ 'Your message has been sent!'|t }}</p>
                </div>
            </div>
        </div>
    </div>

    {# Ensure we load polyfills for older browsers that don't support `fetch()` #}
    <script src="https://cdn.polyfill.io/v2/polyfill.js?features=fetch,Promise"></script>

    <script>
        // Wait until the DOM is ready
        document.addEventListener('DOMContentLoaded', (event) => {
            // Fetch the form we want to deal with
            let $form = document.querySelector('#{{ form.formId }}');

            // Find the CSRF token hidden input, so we can replace it
            let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

            // Fetch the new token for the form and replace the CSRF input with our new one
            fetch('/actions/formie/csrf/input')
                .then(result => { return result.text(); })
                .then(result => {
                    $csrfInput.outerHTML = result;
                    $form.classList.add('csrf-refreshed');
                });
        });
    </script>
{% endfor %}
```
js:
```
export default () => {
  const form = document.querySelector('.js-content-form');
  const successBanner = document.querySelector('#contact-us-success');

  if (form === null || successBanner === null) {
    return false;
  }
  const submitBtn = document.querySelector('.fui-submit');

  form.addEventListener('onAfterFormieSubmit', (e) => {
    e.preventDefault();

    // const data = e.detail;
    form.classList.add('is-loading');
    submitBtn.disabled = true;

    form.querySelector('.fui-page').classList.add('hidden');
    successBanner.classList.remove('hidden');
    submitBtn.disabled = false;
    form.classList.remove('is-loading');
  });
};
```
![изображение](https://user-images.githubusercontent.com/496132/163189177-603b22f6-9670-43aa-84c4-4f7fa18762ca.png)
But field is empty
![изображение](https://user-images.githubusercontent.com/496132/163189073-bc3a0c12-316f-483b-9e33-6387d404e466.png)

Could it be a cache problem?
![изображение](https://user-images.githubusercontent.com/496132/163189675-8d9206a1-e730-4744-9a25-f410773ccfd6.png)

**Comment by engram-design** [comment]
Are you able to remove the `{% cache %}` tag, as that might be caching the HTML the form generates? Or, at least clear the cache to see, as we don't use JS to populate the field value.

**Comment by umkasanki** [comment]
Got it.
What you think about using [No-cache plugin](https://github.com/ttempleton/craft-nocache/blob/main/README.md) for this case?

**Comment by engram-design** [comment]
I've not used it - but maybe worth a spin? Let me know if clearing your cache fixes this, but also something we probably need to address in some fashion eventually.

**Comment by umkasanki** [comment]
Yes, clearing the cache helped.
Disabled form caching for now with this plugin
