### ISSUE TITLE
Multi page form - After the 2nd page it goes back to the first page

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#828]
**Description**
I've got a 4 page form, completing the form always scrambles up the order...

When I fill out the form, the following sequence occurs:
First page
Second page
First page (should go to the 3rd page)
Second page
Third page
Forth page

I've tried removing a page so it's only a 3 page form and I've tried moving the 2nd page to be the first page etc but it still follows the same order.

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.12
- Craft version: Craft Pro 3.7.37
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Do you have any conditions setup for fields, or pages? Have you also tried in Incognito or similar to rule out any session strangeness? I can confirm there's nothing inherently an issue with 4-page forms, as I've just spun up a new (simple) form and had no issue navigating to the end, or navigating between pages.

Is there anything special on the first or second pages worth noting?

And I assume your custom form templates are minimal? If not, which alterations have you made?

**Comment by anchovy** [comment]
Hi @engram-design, narrowed it down to using an event...

```
        Event::on(Submission::class, Submission::EVENT_BEFORE_VALIDATE, function(Event $event) {


            $submission = $event->sender;

            $request = Craft::$app->getRequest();
            $postParams = $request->getBodyParams();

            $pageId = $event->sender->form->getCurrentPage()->id;

            $formHandle = $postParams['handle'];
            $fields = $postParams['fields'];

            //default is we've got no error.
            $errors = [];


            switch($formHandle.$pageId)
            {
                case 'companies1':
                   //do some stuff here.
                break;

                case 'companies2':
                   //submitting the 2nd page of the form 
                   //update a related entry.

                break;

                case 'companies3':
                   //submitting the 3rd page of the form validating some fields.
                  if( true ){
                    $errors[] = ['field'=>'fieldHandle','message'=>'Error message here'];
                  }
                break;
            }

            if(count($errors))
            {
                foreach($errors as $error)
                {
                    $submission->addError($error['field'], $error['message']);
                }
                $event->isValid = false;
            }
            else 
            {
                $event->isValid = true;  
            }
        });

```

The entry update in 'companies2' didn't through any error at all - but caused the strange sequence in the form.
I removed the update and have managed it another way and the form is working as expected.
