### ISSUE TITLE
Duplication of new rows when using more than one repeater in a form.

### ISSUE THREAD

**Issue by olemagnus** [verbb/formie#83]
**Description**
Duplication of new rows when using more than one repeater in a form.
If two repeaters are used, the "Add another row" button will create two new rows. For each repeater that is used, it adds extra rows. I.e. a form with 5 repeaters will add 5 rows when the "Add another row" button is pressed on the front end.
I expect to only add one row regardless of how many repeaters are used.

**Steps to reproduce**
1. Create a new default form.
2. Add two repeaters.
3. Render the form with `{{ craft.formie.renderForm('handle') }}`.
4. Go to the page with the form and press "Add another row". Two fields should show up, instead of one.

### Form settings
Please pick from the options below.

- Multi-page form: Yes and No (doesn't matter, 2 on one page and 4 on another will accumulate to 6)
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.4
- Craft version: 3.5.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [1.2.5](https://github.com/verbb/formie/releases/tag/1.2.5)
