### ISSUE TITLE
System / commerce  mails

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#833]
Formie is just great :) and as much i see / understand there is allmost everythign on place

that can enable us to manage all system / commerce mails in formie 

There are some plugins that do that, but definitly i would love to do that with formie :)

**Comment by engram-design** [comment]
That's probably out of scope for this plugin to become an email management plugin, sorry. For system emails, they can be managed through Utilities > System Messages. Similarly with Commerce emails, they're entirely their own thing apart of their plugin, heavily tied with order statuses and histories. I wouldn't be a fan of overriding their behaviour with ours.

Finally, Formie relies on the email settings setup within Craft, so we also don't want to take over that.

Never say never, but no plans for the near future while we focus on other functionality!

**Comment by wmdhosting** [comment]
OK..  Didnt thinked about taking over.. 

Just to manage mails. templates..  in there using all exiting..  things from craft as you do now..... 

somethign like this one.. 
https://dev-korisnik.wmd.hr/admin/plugin-store/dynamic-email-template-pro

But there is allready much more usefull workflow things in Formie..

**Comment by engram-design** [comment]
Ah, I see. I've not come across that plugin before, I'll check it out
