### ISSUE TITLE
Outdated CSRF token from GraphQL response, submission not working

### ISSUE THREAD

**Issue by Saboteur777** [verbb/formie#834]
**Description**

Hey! I am getting the form data via the GraphQL endpoint, with this query:

```
          {
            form(id: ` + this.formId + `) {
              ...FormFragment
            }
          }

          fragment FieldFragment on FieldInterface {
            id
            name
            label: name
            handle
            instructions
            required
            type
            displayName
            typeName
            inputTypeName
            limit
            limitType
            limitAmount
            placeholder
            errorMessage
            labelPosition
            instructionsPosition
            cssClasses
            enableConditions
            conditions
            enableContentEncryption
            visibility

            containerAttributes {
              label
              value
            }

            inputAttributes {
              label
              value
            }

            ... on Field_Checkboxes {
              defaultValue
              layout
              toggleCheckbox
              toggleCheckboxLabel

              options {
                label
                value
              }
            }

            ... on Field_Dropdown {
              multiple
              defaultValue

              options {
                label
                value
              }
            }

            ... on Field_Email {
              defaultValue
            }

            ... on Field_Hidden {
              defaultValue
              defaultOption
              queryParameter
              cookieName
            }

            ... on Field_MultiLineText {
              defaultValue
            }

            ... on Field_Number {
              min
              max
            }

            ... on Field_Phone {
              defaultValue
              countryEnabled
              countryDefaultValue
              countryShowDialCode

              countryOptions {
                label
                value
              }
            }

            ... on Field_SingleLineText {
              defaultValue
            }
          }

          fragment FormFragment on Form {
            id
            title
            handle
            siteId

            csrfToken {
              name
              value
            }

            settings {
              displayFormTitle
              displayPageTabs
              displayCurrentPageTitle
              displayPageProgress
              submitMethod
              submitAction
              submitActionTab
              submitActionUrl
              submitActionFormHide
              submitActionMessageHtml
              submitActionMessageTimeout
              redirectUrl
              errorMessageHtml
              loadingIndicator
              loadingIndicatorText
              validationOnSubmit
              validationOnFocus
              defaultLabelPosition
              defaultInstructionsPosition
              progressPosition

              integrations {
                settings
              }

              redirectEntry {
                id
                uri
                slug
                sectionHandle
              }
            }

            pages {
              name
              id

              settings {
                submitButtonLabel
                backButtonLabel
                showBackButton
                buttonsPosition
              }

              rows {
                fields {
                  ...FieldFragment
                }
              }
            }
          }
```

As you can see, the `csrfToken` is queried, but the value it returns is outdated. For comparison, I get the CSRF token from the `users/session-info` action endpoint, and the CSRF token value is not the same as the one GraphQL returns. You can view it in action here: https://starschema.com/products/aws-cloud-migration-solution (top right, Get in touch button)

Open Dev Tools and submit the form, the values will be logged to the Console. 

**Steps to reproduce**
1. Query a form with GraphQl
2. Try to submit the form in incognito mode multiple times.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.14
- Craft version: Craft Pro 3.7.38
- Multi-site: No

**Comment by engram-design** [comment]
I believe this is normal behaviour when requesting a CSRF token multiple times, you won't get the same result back, as technically they're different requests. For instance, if you queried `users/session-info` multiple times, or Formie's GQL query (or both as you're doing), you'll get different tokens. This would also be common when using Blitz to refresh tokens which I've seen.

It'll be important to ensure your front-end can maintain a cookie session with your server, if you've done that? Judging from the response calls I think that's all okay:

index.php?p=actions/users/session-info
```
cookie: PHPSESSID=jrjagf4ckug36ndah84u89g1cr; CRAFT_CSRF_TOKEN=4913061f0827aa30d2d300c341223e8f7c3c2ca05de554d6b89b38b0ef0a90a8a%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A40%3A%22LgG1rsvz8-sH8H9BrIIohcc4AWdy04GuLz-JcgHB%22%3B%7D; ajs_anonymous_id=9b03c33d-cff3-49ac-8ff1-464ff85f2ccd; _ga=GA1.2.1224264547.1650455006; _gid=GA1.2.417308059.1650455006; _gat=1; _fbp=fb.1.1650455006960.1879430434; _hjSessionUser_2181469=eyJpZCI6IjU5MjA5N2M3LWY3OGQtNWE5NC1hMTIyLTFhNTEwMTA1MTFjYSIsImNyZWF0ZWQiOjE2NTA0NTUwMDY4NTMsImV4aXN0aW5nIjpmYWxzZX0=; _hjFirstSeen=1; _hjIncludedInPageviewSample=1; _hjSession_2181469=eyJpZCI6ImM3MGI5OTA5LTcyZWYtNDZhMS1iNDFjLWQxMDQ3ZTdjZWYzNyIsImNyZWF0ZWQiOjE2NTA0NTUwMDc1MTYsImluU2FtcGxlIjp0cnVlfQ==; _hjAbsoluteSessionInProgress=1; _gali=primaryMenu
```

It looks like there's no policy for `same-site` cookies. It's important for a cookie session to persist, in order for the server to validate the stored CSRF token on the server, with the one on the front-end.

But tokens should be unique per-form as well, as they're only valid once.

Some of my additional findings here: https://github.com/craftcms/cms/discussions/9685

**Comment by Saboteur777** [comment]
Thanks for the quick reply, Josh! Initially I used the token provided by the GraphQL query, but users reported issues submitting the forms. It turned out they were getting bad request errors, because the CSRF token was not working. So as a stopgap I added a query for the `users/session-info` controller, but I would rather avoid doing this. This seemed a bug to me, hence this issue. 

The tokens are requested alongside the forms, and forms are requested only if a trigger component (like the get in touch button) instructs the form component to do so. I thought doing this would be sufficient, but if I understand right, I should configure axios to send cookies (equivalent of `credentials: 'include'`) with the request (https://stackoverflow.com/questions/43002444/make-axios-send-cookies-in-its-requests-automatically). This requires CORS headers to be set up. 

Right? 

Regarding the GraphQL mutations: according to the [docs](https://verbb.io/craft-plugins/formie/docs/developers/graphql#mutations), form fields should be hardcoded into the form component (including the handles) - which is not suitable for our use case. Am I missing something here?

**Comment by engram-design** [comment]
That's correct - at least for my research. The CSRF token is created just fine in any situation on the server, but it's not persisted unless there's the ability to create a same-site cookie.

I should also mention there's the [`enableCsrfValidationForGuests`](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) config setting you might like to turn off for an easy solution. CSRF tokens are really there (again, to my understanding) to prevent authorised users doing things they shouldn't, or when dealing with any sort of state-altering function like editing profile details. It's not exactly a security issue when talking about form submissions as guests.

But, you can certainly get it working - it's just a little more effort.

As for mutations, that's correct, you need to create your mutations query to contain the fields (and types) that you're sending. This is where our [`formie-headless`](https://github.com/verbb/formie-headless#graphql-mutations) project can help out, with its helpers to generate those for you. As you know, forms being client-managed will change, so they can't be hardcoded.

Lastly, you can also use regular ol' REST to submit form data to Formie's `formie/submissions/submit` endpoint if you like.

**Comment by Saboteur777** [comment]
Thanks for the detailed answer! The [enableCsrfValidationForGuests](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) config setting would be handy in this case, but as I am going to implement captcha support, which needs sessions, I will migrate to mutations from the current REST-based solution. 

The `formie-headless` repository is really useful, thanks for having it!

**Comment by engram-design** [comment]
Ah gotcha. Yeah captchas are another annoying situation. reCAPTCHA should be fine, as you don't need to maintain a session for that, but if you want to use the JavaScript or Duplicate captchas, you'll need to maintain a session.
