### ISSUE TITLE
getCurrentPageIndex not working

### ISSUE THREAD

**Issue by chrisrowe** [verbb/formie#835]
**Description**
I'm trying to show `Step 2 of 5` for example, but `form.getCurrentPageIndex` isn't returning anything.
This is true of new submissions and when editing an existing submission

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.14
- Craft version: 3.7.38
- Multi-site: No

**Additional context**
I DM'd you about this via Discord to jog your memory https://discord.com/channels/@me/966625692236251136/966661730337955890

**Comment by engram-design** [comment]
We figured this out over Discord!
