### ISSUE TITLE
Double-opt-in for Campaign integration

### ISSUE THREAD

**Issue by sarahschuetz** [verbb/formie#837]
Is there a way to implement a newsletter registration for Craft Campaign using double-opt-in?
At the moment, submitted email addresses are activated and subscribed immediately.

**Comment by sarahschuetz** [comment]
Probably it would need to be somewhat similar to Campaigns `actionSubscribe` in their `FormsController` using the `PendingContactModel`:
https://github.com/putyourlightson/craft-campaign/blob/9d1504469527e07f55828c4d12fa4d79feb01159/src/controllers/FormsController.php#L90

Would be great if you could extend the integration :)

**Comment by engram-design** [comment]
Yep, good point! I'm not sure if this was a recent addition on their part, or if I've just missed this along the way. Formie will now respect this setting made in Campaign.

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.14",
  "...": "..."
}
```

Then run `composer update`.

**Comment by sarahschuetz** [comment]
Nice! Works perfectly ☺️
Thanks for the quick fix! Love your plugin by the way 🙌

**Comment by engram-design** [comment]
No problem, and thanks for the kind words! 😄

**Comment by engram-design** [comment]
Added in [1.5.15](https://github.com/verbb/formie/releases/tag/1.5.15)
