### ISSUE TITLE
"Css Classes must be a string"

### ISSUE THREAD

**Issue by tremby** [verbb/formie#838]
**Description**

I'm putting together a "kitchen sink" form to evaluate the plugin. I am unable to save when I put anything in the "custom CSS classes" field. I get the error "Css Classes must be a string." I have tried a single word, space-separated words, a string in doublequotes.

**Steps to reproduce**
1. Define a new form
2. Add a single line text field
3. Configure it to have a custom CSS class by putting something in the custom CSS class field
4. Attempt to save

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax or Page Reload whatever is default
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-4 at df609e2
- Craft version: 4.0.x-dev at a59b90
- Multi-site: Yes

**Additional context**
headless

**Comment by engram-design** [comment]
Fixed in the latest `craft-4` branch!

**Comment by tremby** [comment]
Great; thank you.
