### ISSUE TITLE
Editor for multi-line text with rich text doesn't format text correctly

### ISSUE THREAD

**Issue by olemagnus** [verbb/formie#85]
**Description**
Editor for multi-line text with rich text doesn't format text correctly. using bold and italic works as expected. Quote, heading and lists doesn't do anything at all. 
This happens in both the frontend and in the control panel. 

**Steps to reproduce**
1. Add a multi-line text field.
2. Turn on rich text.
3. Select Heading 2, unordered list etc.
4. Render the form.
4. Write some text and press the formatting buttons and see nothing happens. 

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.5
- Craft version: Craft Pro 3.5.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Hmm, that's odd, just tested out the "kitchen sink": https://d.pr/v/aUoDpf

Are there and JS errors on the page? Can you let me know your browsers and version?

**Comment by olemagnus** [comment]
After doing some more testing it seems like the issue is just styling. I'm using Tailwind.css and its reset styling rules make it look like nothing happens because the text field doesn't use classes, just plain elements.

**Comment by engram-design** [comment]
Ah, that makes sense. I’ll get some classes setup to force some styles for the editor.

**Comment by olemagnus** [comment]
While testing this I also found there is no way to get out of a blockquote.

**Comment by engram-design** [comment]
@olemagnus Looks like escaping from a blockquote is a [known issue](https://github.com/jaredreich/pell/issues/89). But from my testing, it looks like you can use the Paragraph button to toggle it back to a paragraph. But then, I've managed to get it to _not_ work, so it seems flaky at best.

For this reason, I've added a "Clear Formatting" button.

Check out [1.2.6](https://github.com/verbb/formie/releases/tag/1.2.6) which also includes the forced-formatting of items in the rich text field.
