### ISSUE TITLE
GQL output format for "calculations" field -> "formula" field

### ISSUE THREAD

**Issue by tremby** [verbb/formie#850]
**Description**

The GQL output format for a "calculations" field type's "formula" field comes back as a JSON string describing what looks like a Prosemirror data structure. This seems to me like it's probably not intended.

I'm getting back for example

```json
[
  {
    "type": "paragraph",
    "content": [
      { "type": "variableTag", "attrs": { "label": "Number", "value": "{field.number}" } },
      { "type": "text", "text": "*5" }
    ]
  }
]
```

Even if that's intended, I can also add new paragraphs and new lines with enter or shift-enter, and then get output like this:

```json
[
  {
    "type": "paragraph",
    "content": [
      { "type": "variableTag", "attrs": { "label": "Number", "value": "{field.number}" } },
      { "type": "text", "text": "*5" }
    ]
  },
  {
    "type": "paragraph",
    "content": [
      { "type": "variableTag", "attrs": { "label": "Number", "value": "{field.number}" } },
      { "type": "text", "text": "*" },
      { "type": "variableTag", "attrs": { "label": "Number", "value": "{field.number}" } },
      { "type": "hard_break" },
      { "type": "variableTag", "attrs": { "label": "Number", "value": "{field.number}" } },
      { "type": "text", "text": "+1" }
    ]
  }
]
```

i.e. multiple paragraphs, and multiple lines per paragraph. Is *that* intentional?

I see from [the docs](https://verbb.io/craft-plugins/formie/docs/feature-tour/fields#calculations) that quite a few operators are available, and string concatenation etc, but it doesn't give any hints on how paragraphs and newlines might be interpreted. Not sure how deep a rabbit hole I'm staring down here...

**Steps to reproduce**
1. Make a form
2. Add a "calculations" field
3. Add a formula
4. Query for it via GQL

### Form settings
Please pick from the options below.

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: craft-4 at ea1134671
- Craft version: 4.0.x at 9d2c37d6
- Multi-site: Yes

**Comment by engram-design** [comment]
Yep, so we have the ProseMirror schema as a bit of a wrapper around the conditions, but that shouldn't be included in the response. It should instead be rendering a string. This will still be a JSON string, which contain the formula, but also any variables used

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
Alright, certainly an improvement. In a case where I've put a placeholder then `*3` I get back:

```json
{
  "formula": "field_number*3",
  "variables": {
    "field_number": {
      "name": "fields[number]",
      "type": "verbb\\formie\\fields\\formfields\\Number"
    }
  }
}
```

That seems pretty reasonable. Looks like I get all the keys from `variables`, and do a search for those within `formula`, with the intention to replace. For the replacement I can change logic based on the `type`, and I look up the field via `name`. Am I meant to parse out what's within the square brackets and assume that's a field handle? If I'm along the right lines, it'd be nice to receive that handle straight up rather than have to parse it out of `fields[handlename]`.

---

But the field is still letting me add line breaks and new paragraphs. Is this intentional, or just something you can't switch off in Prosemirror? The output doesn't look intentional -- this is what I get when I have `[number]*3` on line 1, then a line break and then `4*[number]`, then a paragraph break and then `[number]-1`:

```json
{
  "formula": "field_number*34*field_numberfield_number-1",
  "variables": {
    "field_number": {
      "name": "fields[number]",
      "type": "verbb\\formie\\fields\\formfields\\Number"
    }
  }
}
```

**Comment by engram-design** [comment]
Yeah so the `name` property refers to the `name` attribute used as the input for the field (`<input type="text" name="fields[number]">`) which is critical for Twig, but not so much for you. As such, it'll be in HTML name attribute notation with the square brackets. It's so that it can handle grabbing values that are nested in other fields (repeater/group) and not reliant on things like ID, class, data attributes. Instead our JS selector targets the name attribute to fetch the values of that input to populate/replace the formula like you describe.

Yep, multi-lines are supported, just in case you've got a large and complex formula you want to construct. It can get a pain scrolling left/right in that small box. But the formula will exclude line breaks, as you've shown. So you might have:

```
([number]+3*([number1]*30)*
[number2]*[someLongFieldhandle3]+[number4]) / 2
```

**Comment by tremby** [comment]
> Yeah so the `name` property refers to the `name` attribute used as the input for the field (`<input type="text" name="fields[number]">`) which is critical for Twig, but not so much for you. As such, it'll be in HTML name attribute notation with the square brackets. It's so that it can handle grabbing values that are nested in other fields (repeater/group) and not reliant on things like ID, class, data attributes. Instead our JS selector targets the name attribute to fetch the values of that input to populate/replace the formula like you describe.

Right. That's well and good, and I understand the reasoning. But if that's how it's going to be given to me in the calculations formula context I'd like a way to get that same `fields[number]` string from some member of the field, which would provide a solid link between the two with no guesswork and without needing to know the convention the Formie UI uses. I'd then be able to choose whether to actually use that as the `name` attr or invent my own, whatever works in my implementation, and I still have that positive link between formula and field.

> Yep, multi-lines are supported, just in case you've got a large and complex formula you want to construct. It can get a pain scrolling left/right in that small box. But the formula will exclude line breaks, as you've shown.

Ahh OK I see. Something to that effect in the docs would be a help. (Or if it's already in the docs, sorry!)

**Comment by engram-design** [comment]
I've just added `handle` in that array, alongside `name` and `type` - if that'll help? However, how would you like to be able to access sub-fields? For example, if this field references the first name in a multi-name field, you'll have `myNameField[firstName]` as the value. Will that work, or would you like that modified?

**Comment by tremby** [comment]
> I've just added `handle` in that array, alongside `name` and `type` - if that'll help?

Yeah, that gives the positive link I was looking for. Thanks.

> However, how would you like to be able to access sub-fields? For example, if this field references the first name in a multi-name field, you'll have `myNameField[firstName]` as the value. Will that work, or would you like that modified?

Good question. I hadn't thought too much about the multi-field fields. Honestly I was planning to disable some/most of them for this project until a particular need arose. But your suggested syntax looks reasonable to me, so would separating the parts by a dot or slash or colon or similar.

I definitely did want to support repeater and group (and *maybe* table) but didn't look too hard at them yet -- how do they fit in when it comes to calculations?

**Comment by engram-design** [comment]
Only Group will really be supported. Table and Repeater I haven't really figured out. Because these are repeatable values, there's not a way of determining how to treat those values.

If you had `10 * [repeaterNumberField]` then that could turn into `10 * [11, 2, 42, 57]`, and there's not a way to define what to do with those array of numbers. You'll get a similar scenario for if these were strings.
