### ISSUE TITLE
No way to get options for "checkboxes", "radio", "dropdown" from GQL

### ISSUE THREAD

**Issue by tremby** [verbb/formie#851]
**Description**

I can't find any way to get the available options for fields of type "checkboxes", "radio", and "dropdown".

**Steps to reproduce**
1. Make a form
2. Add fields of types "checkboxes", "radio", "dropdown"
3. Configure options for each
4. Query for the form via GQL, look in graphiq explore mode for available fields, check everything
5. See output; options are nowhere to be seen

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 at ea11346715c
- Craft version: 4.0.x at 9d2c37d6b
- Multi-site: Yes

**Comment by engram-design** [comment]
You should be able to query `options` which is a `FieldAttribute` so use `{ label, value }` as sub-selections.

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
I can get the options now! Thanks.
