### ISSUE TITLE
GQL response for "blockedDomains" of "email" field looks unintentional

### ISSUE THREAD

**Issue by tremby** [verbb/formie#852]
**Description**

The response for the `blockedDomains` field of "email"-type fields looks to me like it's not intended.

**Steps to reproduce**
1. Add an email field
2. Query for it via GQL including its `blockedDomains` field
3. See response
4. Add some domains to the list of blocked domains for that field
5. Query again
6. See response

It's giving back a JSON string. An empty array if no domains are set as blocked, and things of this form if some blocked domains are defined:

```json
[
  {
    "domain": "",
    "value": "example.com"
  },
  {
    "domain": "",
    "value": "example.net"
  }
]
```

This doesn't look intentional to me. I think an output type of `[String!]!` would make more sense, wouldn't it?

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 at ea11346
- Craft version: 4.0.x at 9d2c37d
- Multi-site: Yes

**Comment by engram-design** [comment]
That's really just how we store the data for that table in Craft, but yes this could be improved to be an array of strings in this case. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
Much better, thank you.
