### ISSUE TITLE
Misconfiguring form "action on submit" to "redirect to URL" with no URL is allowed, and leads to GQL error

### ISSUE THREAD

**Issue by tremby** [verbb/formie#853]
**Description**

If you set a form to "redirect to a URL" but leave the URL blank, then query for `redirectUrl`, there's a GQL error:

```
craft\\web\\View::renderString(): Argument #1 ($template) must be of type string, null given, called in /srv/my-project/vendor/verbb/formie/src/elements/Form.php on line 1189
```

Better would be a validation error in the control panel when misconfiguring the form in this way.

**Steps to reproduce**
1. Set a form's "action on submit" setting to "redirect to a URL" but leave the target URL blank
2. Save the form
3. Query for `redirectUrl` on that form via GQL.
4. See error.

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 at ea113467
- Craft version: 4.0.x at 9d2c37d
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.
