### ISSUE TITLE
GQL representation of "loading indicator" options is ambiguous

### ISSUE THREAD

**Issue by tremby** [verbb/formie#855]
- With a fresh form, without touching the options, the default is no loading indicator, and on GQL I get `loadingIndicator: null, loadingIndicatorText: null`.
- If I switch to "spinner", I get `loadingIndicator: true, loadingIndicatorText: null`. I don't see the "spinner" option explicitly set on any GQL field.
- If I switch to "text" but fill in no text, I get `loadingIndicator: true, loadingIndicatorText: null`, which is the same as the previous line. No explicit indication that I'm in "text" mode.
- If I switch to "text" and fill in text, I get `loadingIndicator: true, loadingIndicatorText: "the text"`.
- If I switch back to "spinner", I get `loadingIndicator: true, loadingIndicatorText: "the text"` -- the text is still present, so I again can't tell it's supposed to be "spinner" mode.
- If I switch now to "none", I get `loadingIndicator: null, loadingIndicatorText: "the text"`.

Other than the obvious issue of not being able to tell what kind of spinner I'm supposed to have, it's also weird that the possible options for `loadingIndicator` seem to be `null` and `true` rather than `false` and `true`. I've seen the same thing on the `submitActionFormHide`, `validationOnFocus`, and `validationOnSubmit` fields so far.

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 at ea113467
- Craft version: 4.0.x at 9d2c37d6
- Multi-site: Yes

**Comment by engram-design** [comment]
Good point, this was incorrectly cast as a boolean, when it shouldn't have been. 

Those other similar properties are correctly `[Boolean!]` at least for the moment, to match the corresponding PHP property. I actually only just realised this was how to write nullable types with GraphQL, so I'll be sure to update the docs, along with potentially changing boolean properties to non-nullable.

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
OK, now I can tell the difference between no loader (`null`), spinner, and text. Thanks!

Yeah, look out for list types too. For a non-nullable list of non-nullable strings, you'd want `[String!]!`, whereas `[String]!` could legally contain `["this", null, "that"]`, and `[String!]` could legally just itself be `null`.
