### ISSUE TITLE
No GQL field for "error message position" setting

### ISSUE THREAD

**Issue by tremby** [verbb/formie#856]
Apologies if I'm missing something, but I don't see a GQL field for the "error message position" setting.

**Additional info**
- Plugin version: craft-4 at ea113467
- Craft version: 4.0.x at 9d2c37d6b

**Comment by engram-design** [comment]
Good point, it's missing! Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.
