### ISSUE TITLE
Conditional notifications

### ISSUE THREAD

**Issue by daltonrooney** [verbb/formie#86]
**What are you trying to do?**
Send a notification or response depending on the value of a form field. This may be related to https://github.com/verbb/formie/issues/82

**What's your proposed solution?**
When setting up a notification, it would be nice if we could match one or more conditions based on the value of a field in the form. In my example for #82 I had a dropdown like:

I'm interested in...
Sales -> sales@example.com
Support -> support@example.com
Media -> media@example.com

I also need to create a notification that is sent to the submitter, but only if "media" is selected. Sales and Support inquiries are sent to a CRM which generates its own auto-response.

**Additional context**
Sprout forms makes this possible using Twig tags. We've also used Gravity Forms (WordPress), they have a point and click interface which supports multiple conditions:

<img width="478" alt="Screen Shot 2020-09-04 at 1 21 05 PM" src="https://user-images.githubusercontent.com/742045/92282031-b0bcb280-eeb1-11ea-98eb-28071a678640.png">

**Comment by engram-design** [comment]
Yep, this is on the roadmap. We'll be using a conditional builder rather than Twig, which is much more client-friendly

**Comment by daltonrooney** [comment]
When you say it's on the roadmap, I assume it's not going to be added in the next week or so? 😉 

Just kidding, I realize this requires plenty of work & planning to get right. 

I do need to make one particular notification conditional, I was looking at the [beforeSendNotification](https://verbb.io/craft-plugins/formie/docs/developers/events#the-beforeSendNotification-event) event. I'm assuming I can loop through the $event->submission property looking for a particular value, and if there's no match, set $event->isValid to false?

**Comment by engram-design** [comment]
Nope, not in the next few weeks for sure, sorry. You can completely use that event to prevent sending, exactly as you've described.

**Comment by daltonrooney** [comment]
In case anyone else is trying to do something similar, I created a module with an event watcher like this:

```
Event::on(Submissions::class, Submissions::EVENT_BEFORE_SEND_NOTIFICATION, function(SendNotificationEvent $event) {
  
  //Only running this for certain forms
  if ($event->submission->formId != 4568) return $event;
  
  $notificationId = $event->notification->id;
  
  //This is the dropdown with the value we're looking for
  $roleValue = $event->submission->role->value;
  
  //Suppress this notification unless the value we're looking for matches the value that was submitted
  if ( $notificationId == 1 && $roleValue != 'sales@example.com') $event->isValid = false;
  
  return $event;
});
```

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/formie/releases/tag/1.3.0)
