### ISSUE TITLE
Number field's min and max settings seem to allow decimal values but these are truncated at save

### ISSUE THREAD

**Issue by tremby** [verbb/formie#860]
**Description**

Min and max for number field allow typing for example "3.3", but this is truncated to "3" on save.

I'm not sure if it's an intentional limitation (if so, some validation on those fields wouldn't be amiss), or an oversight.

**Steps to reproduce**
1. Make a number field
2. Set number of decimal places on it to 1 or more
3. Enable limits
4. Type in some limits with decimal places such as 1.1 to 5.9
5. Click apply
6. Click to edit the field again, see that 1.1 and 5.9 are still present
7. Apply again
8. Save
9. Edit the number field again, see the limits are now truncated to 1 and 5

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 e5325be
- Craft version: 4.0.x 897930b
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Yup, just an oversight, it's assumed that the min/max values will always be an int, not a float. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
Thanks!
