### ISSUE TITLE
Google sheets integration error: Cannot assign verbb\formie\jobs\TriggerIntegration to property verbb\formie\base\Integration::$_queueJob of type ?bool

### ISSUE THREAD

**Issue by jubalj** [verbb/formie#869]
**Description**
Google worksheet integration fails on new form submission with - "Cannot assign verbb\formie\jobs\TriggerIntegration to property verbb\formie\base\Integration::$_queueJob of type ?bool" error in craft queue.

**Steps to reproduce**
1. Create new integration for google from Settings> Misc
2. Configure integration in google cloud console
3. Within new form setup "Integration" tab, which recognises link to google sheet and is able to pull out Field Mappings
4. Make a submission in the formie form
5. Error noted in craft Queue Manager

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

**Additional info**
- Plugin version:2.0.0-beta.5
- Craft version: 4.0.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.6](https://github.com/verbb/formie/releases/tag/2.0.0-beta.6)
