### ISSUE TITLE
FR: Add settings to limit submissions

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/formie#872]
**What are you trying to do?**
For some forms, we'd like to limit:
- either the amount of submissions that are allowed (e.g. only 150 people can fill in the form) 
- either until when people can fill in the form aka an expiration date.

**What's your proposed solution?**
- A number field to limit submissions
- A date field for when the form should "expire"
- A text field to have a message shown when the form has expired or the limit has been reached.

**Comment by engram-design** [comment]
Yep, we've got this planned!

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/formie/releases/tag/2.0.9)
