### ISSUE TITLE
Fix GraphQL mutations and being unable to map to complex fields like multi-name and address

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#88]

**Comment by monochromat13** [comment]
I just bumped into this issue on a project. Wondering if there's an ETA on a fix? Or should I use simple fields instead?

**Comment by engram-design** [comment]
Still working on it! Should be sorted probably within a week

**Comment by monochromat13** [comment]
Awesome, appreciate it!

**Comment by engram-design** [comment]
Added in [1.2.14](https://github.com/verbb/formie/releases/tag/1.2.14)
