### ISSUE TITLE
On-Premise Dynamics 365 Integration

### ISSUE THREAD

**Issue by aarmitage** [verbb/formie#880]
Hello,

Thank you for adding the Microsoft Dynamics 365 integration with Formie. I tried setting it up this week to demonstrate to a client and it's worked a charm following the detailed instructions you've provided within the plugin.

However, it turns out the particular client we had in mind (and I daresay it probably applies to other corporates) aren't using the cloud version of Dynamics and have an on-premise instance. 

> We currently have Dynamics365 on prem and are looking to upgrade to V9 on premise.

I think I know what the answer will be, given that on-premise instances could have all sorts of specific configurations, but do you know if the plugin would be able to support an on-premise integration? Or could we potentially customise/extend the cloud integration you've built? I'm conscious that we could be opening ourselves up to all kinds of pain given the series of steps involved with cloud.

Thank you Verbb!

**Comment by engram-design** [comment]
Great to hear it's working for you. More than happy to add that capability, although the tricky thing will be testing. I can certainly implement it from a documentation-only level, but would need some assistance to check all works with a real (preferably sandboxed) on-premises account. 

From my _very_ quick investigation:

> For on-premises instances, Dynamics CRM or Dynamics 365 must be setup as an [Internet-Facing Deployment (IFD)](https://technet.microsoft.com/en-us/library/dn609803.aspx) with [claims-based authentication for external access](https://technet.microsoft.com/en-us/library/gg188592.aspx) using ADFS or Active Directory authentication or be accessible from the IP address of your web server.

**Comment by aarmitage** [comment]
That sounds great! Let me liaise with the client and their IT team on those infrastructure points you've included and see if that would be an option for them and their version.

Thank you 🙏

**Comment by engram-design** [comment]
Going to close this for now, but let me know if you'd like this picked up. I think this might be a challenge if we get to it, and might require a bit more of a hands-on approach with knowing their on-premises account setup. I believe it's pretty heavily tied with Active Directory, so there may be some challenges with gaining access from our end to ensure things are working.

But feel free to revive this topic, or shoot us an email at `support at verbb.io`
