### ISSUE TITLE
Conditional Address field throw error on submit

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#881]
**Description**
That was not an easy one to isolate.
Submitting a form with a an address field and a condition applied to it throws a type error.

```php
TypeError
craft\helpers\Typecast::properties(): Argument #2 ($properties) must be of type array, null given, called in /app/vendor/craftcms/cms/src/base/Model.php on line 69
```

**Steps to reproduce**
1. Create a form with a radio button with two options (a and b)
2. Add an Address field with a condition show if radio is b
3. Try submitting the form if radio is not selected or is a (ie address is not visible)

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 4-beta.6
- Craft version: 4

**Comment by engram-design** [comment]
Duplicate of https://github.com/verbb/formie/issues/878#issuecomment-1123750942

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
Yep, fixed! Thanx!
