### ISSUE TITLE
Stencil Validation Not Showing Validation Errors on Save

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#89]
**Description**
Saving a stencil with certain validation errors fails to save with a generic fail message.  If you have 20-30 fields in the Stencil there's now way to determine how to resolve the issue.

**Steps to reproduce**
1. Create a Stencil with a group and place a text input in the group
2. For the text input handle, add a space at the end (to produce validation error)

Expected: A specific error telling me what i need to fix
Actual: A generic fail error of "Unable to Save Form"

### Form settings
Please pick from the options below.

Latest versions of Craft and Formie

**Comment by engram-design** [comment]
Should be fixed in [1.2.7](https://github.com/verbb/formie/releases/tag/1.2.7)
