### ISSUE TITLE
getSettingGqlType method does not exist error when editing a form or viewing field settings

### ISSUE THREAD

**Issue by simonkuran** [verbb/formie#895]
**Description**
I get the following PHP error whenever I try to edit a form or go to Formie > Settings > Fields:
`An alias (traitGetSettingGqlType) was defined for method getSettingGqlType(), but this method does not exist`

**Additional info**
- Plugin version: 2.0.0-beta.7
- Craft version: 4.0.3
- Multi-site: Yes

**Comment by mtnorthrop** [comment]
I have the same issue, and am also on Craft 4.0.3 and Formie 2.0.0-beta.7.

The stacktrace says the error is in `verbb\formie\fields\formfields\Products`, and it looks like the problem might the traits here:
https://github.com/verbb/formie/blob/b4f49714c9e82471dd491913f9e95142e4921d96/src/fields/formfields/Products.php#L44-L45

In `verbb\formie\base\FormFieldTrait`, we have a `getSettingGqlTypes()`, but we don't have a `getSettingGqlType()`.

_Edit:_
Looking further, I see this also effects a number of other `formfields` classes. A quick directory search shows that all of these classes are trying to use `FormFieldTrait::getSettingGqlType()`: Categories, Entries, Products, Tags, Users, and Variants.

**Comment by engram-design** [comment]
Yep, sorry about that, this was an incorrect merge from Formie v1 where this change was made, but doesn't apply for Formie v2 - I completely missed that.

Fixed in [2.0.0-beta.8](https://github.com/verbb/formie/releases/tag/2.0.0-beta.8)
