### ISSUE TITLE
[2.0.0-beta.7] Asset files like recaptcha-v3.js not found

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#896]
**Description**
This error appears when trying to view a form on the frontend that has a reCaptcha integration:

```
Invalid Argument – [yii\base\InvalidArgumentException]
The file or directory to be published does not exist: /var/www/html/vendor/verbb/formie/src/web/assets/captchas/dist/js/recaptcha-v3.js
```
It appears this is due to the fact that the asset files were moved to a new location in this release. The `recaptcha-v3.js` file, for example, is now located at `verbb/formie/src/web/assets/frontend/dist/js/captchas/`.

The exception is thrown by `yii\web\AssetManager`, on line 467.

**Additional info**
- Plugin version: 2.0.0-beta.7
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.8](https://github.com/verbb/formie/releases/tag/2.0.0-beta.8)
