### ISSUE TITLE
Manual render categories field

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#899]
Apologies if this is a really simple solution.

I have a field in a form that is a categories set. The form has all the fields manually rendered using `{% set fieldname = form.getFieldByHandle('handle') %}`

I'm not sure how to render the category options using the category set defined in the form builder within admin. I can obviously query the category set the typical Craft way, but thought I should be creating that Craft category query using the category chosen with the form builder.
I can see the form field has the category source e.g. `group:...` - assume that's what I should use?

**Comment by engram-design** [comment]
Have a look at how we render categories (which is the same for other elements) https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/fields/categories.html there's a little bit of work involved to cater for different layouts (dropdown, checkboxes, etc).

But in the template, there's already a `value` variable, which is an element query (CategoryElementQuery in your case), which you can modify.

```
{% set categories = value.all() %}

{# Or, add your own query params #}
{% set categories = value.limit(10).all() %}
```

The element query will be prepped with all the settings, as defined by the field settings.

Does that help?

**Comment by jamiematrix** [comment]
Thanks for the reply. It has helped somewhat, but forgive my ignorance ...
How would I set `value`?

This is what I have for the field:
`{% set location = form.getFieldByHandle('location') %}`
Using `location.getFieldOptions()` I can get an array of options (label and value) with the field label being the first option.

I've tried `{% set locationValue = location.getDisplayTypeValue(craft.categories) %}` but that only returns the first category albeit with more data (selected, valid)

**Comment by engram-design** [comment]
Ah, I see. Calling `field.getElementsQuery()` should do the trick, which will return a CategoryQuery object

**Comment by jamiematrix** [comment]
Seems to have done the trick to get the available options, thanks.

Worth noting for anyone else looking for the same - the `<select>` element needs `name="fields[fieldHandle][]"` and the options `value` needs to be the category ID

Thank you @engram-design
