### ISSUE TITLE
enableTemplateCaching causes issues with form styling and javascript

### ISSUE THREAD

**Issue by mylesthedev** [verbb/formie#9]
### Description
When the config `enableTemplateCaching` is set to true both the CSS and JS assets don't load.

### Steps to reproduce

1. set `enableTemplateCaching` to true
2. view form styles

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.4.29

**Comment by engram-design** [comment]
That seems strange, and I can't seem to immediately replicate that on my end. Anything special you're doing on your site?

So toggling this config setting on/off seems to fix it?

**Comment by mylesthedev** [comment]
Yeah basically. I'm just using the built in styles and Ajax form.
Not doing anything special I don't think.

When the caching of templates is on the scripts just don't get included. Weird huh?

**Comment by engram-design** [comment]
I take it you're using the `{% cache %}` tag in your templates, surrounding the `craft.formie.renderForm()` variable - or are using the field element field?

**Comment by engram-design** [comment]
If you can confirm if you're using `{% cache %}` tags, and if you are, I believe you'll need to update to [1.0.4](https://github.com/verbb/formie/releases/tag/1.0.4)

We've added `craft.formie.registerAssets()` to handle the case for cached forms. Craft will cache the HTML generated by the form, but it won't cache the CSS and JS registered by Formie.

Check out the docs as well - https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms
