### ISSUE TITLE
[FR] Allow to use .env to for API Key

### ISSUE THREAD

**Issue by hongc-cc** [verbb/formie#90]
**What are you trying to do?**
Allow user to use .env for API key in integration.
e.g. $MAILCHIMP_KEY

Now the key is leaked in project config file.

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

**Additional context**

**Comment by engram-design** [comment]
Added in [1.2.8](https://github.com/verbb/formie/releases/tag/1.2.8)
