### ISSUE TITLE
[2.0.0-beta.9] Potential bug: Uncaught TypeError: __webpack_require__.n is not a function

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#900]
**Description**
Formie's JS might conflict with a website's frontend JS, if the website's JS has been compiled by Webpack. This error could appear in the browser's dev tools console: `Uncaught TypeError: __webpack_require__.n is not a function`.

In my case, I fixed the issue by changing the [output.chunkLoadingGlobal](https://webpack.js.org/configuration/output/#outputchunkloadingglobal) setting in my Webpack config to something unique, following the advice I found here: https://stackoverflow.com/questions/67541708/webpack-5-webpack-encore-how-to-run-multiple-webpack-instances-on-the-same-pa

Although I'm no expert in Webpack, but I'm assuming the problem was that both Formie and my own project were using the default for this setting, and hence the error.

I imagine many Formie users who use Webpack to manage their site's assets might run into this same problem, so maybe changing Formie's `output.chunkLoadingGlobal` configuration to something unique would prevent users from running into this issue.

**Additional info**
- Plugin version: 2.0.0-beta.9
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Hmm, that's quite interesting, and not something I've come across before to-date, as we've been running Laravel Mix for some time for front-end asset bundles.

But just pushed up a fix to use `chunkLoadingGlobal`

**Comment by mtnorthrop** [comment]
It's the first time I've ever come across an issue like this as well. The issue didn't appear for me until 2.0.0-beta.9, though, and I've just tested the change by putting `"verbb/formie": "dev-craft-4 as 2.0.0-beta.9"` in my `composer.json` and updating, and everything works now. Thanks for taking care of that!

**Comment by engram-design** [comment]
Appreciate the heads-up!

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.10](https://github.com/verbb/formie/releases/tag/2.0.0-beta.10)
