### ISSUE TITLE
Set Repeater field required

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#901]
**What are you trying to do?**
Currently, we can't set a Repeater field required, while it would be very useful to force at least one item to be added.

**Comment by engram-design** [comment]
You can use the min/max blocks to control this, as "required" by itself is a bit vague.

**Comment by romainpoirier** [comment]
Perfect, thank you!

**Comment by engram-design** [comment]
Going to close this in favour of using the min/max blocks
