### ISSUE TITLE
Disable field but remain visible on form

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#902]
Is there a way to have a field visible in a form but not editable? 

I'm pre-selecting a dropdown of entries from a querystring but want to disable the field if the querystring is present. Setting the field to "disabled" removes the field from the form - I guess that is technically disabled.
Alternative is to use Javascript to target the `<select>` and apply the `disabled` attribute

**Comment by engram-design** [comment]
I'd recommend adding [`readonly`](https://www.w3schools.com/tags/att_input_readonly.asp) to the "Input Attributes" setting for the field.

> A form will still submit an input field that is readonly, but will not submit an input field that is disabled!

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1221575/170133378-8dded2bb-ccc5-4ad5-b74f-4d28009b9584.png">

**Comment by jamiematrix** [comment]
I went for `disabled` in name and `true` in value for the dropdown - works for me. 

Thank you for pointing the right direction :)

**Comment by engram-design** [comment]
No problem, `disabled` will not send any data to Formie for the submission (so the value will always be empty), whereas `readonly` will send the data to be saved, but in both cases, you can't modify it on the front-end.

**Comment by jamiematrix** [comment]
Ah! 
`readonly` has no effect on the dropdown's - only setting to `disabled` still renders the dropdown but makes them non-interactive ... for me at least

**Comment by engram-design** [comment]
Oh, I've just realised that `<select>` elements don't have a `readonly` attribute according to the HTML spec - so yep, you are in fact limited to `disabled`. There's not much we can do about that!

If you're just pre-selecting a value, but don't want the user to be able to modify the value, is there a reason for it to be a dropdown field at all? Or even visible to the user?

Otherwise, I'll _probably_ say it's a out of scope for Formie to handle this, and if you want a non-interactive select that isn't disabled, you'll likely need to roll your own solution.

**Comment by jamiematrix** [comment]
If it could be swapped out for a text input (as readonly) that would suffice - is that possible with `setFieldSettings`? 

We've been asked for the option to be preselected on the form and to be shown to customers but not let them edit.

**Comment by engram-design** [comment]
Could you use a text input in any case, or does it have to be a select at all? As in, in some circumstances, do you want your users to be able to change the select field, but just in some other instances, you want it forced? I would've recommend changing the field type with `setFieldSettings` as you'll likely get some very unexpected results.

I think the most simple approach to this might be using CSS and setting `pointer-events: none` on the select, allowing users to not be able to change the select.

**Comment by jamiematrix** [comment]
I'm waiting to hear back about if some connection to entries is needed (the select's options list is from a list of entries). If it isn't then I can query the entry from the querystring and enter the title (or whatever information they want) into a textfield instead.

The CSS alternative is a good one, thank you

**Comment by jamiematrix** [comment]
Is it possible to remove all other dropdown items apart from the one specified in the query string?

**Comment by engram-design** [comment]
Sure, you can use [`setFieldSettings`](https://verbb.io/craft-plugins/formie/docs/v1/template-guides/rendering-fields#override-field-settings) for that purpose (I just mentioned changing the field type might make things explode).

```
{% do form.setFieldSettings('dropdownField', {
    options: [
        { label: 'This is the only option', value: 'my-option', isDefault: false },
    ],
}) %}
```
