### ISSUE TITLE
[2.0.0-beta.9] MailChimp Per Form Integration Settings Don't Persist & Integration does not 

### ISSUE THREAD

**Issue by BrandonJamesBorders** [verbb/formie#907]
**Description**
Integration settings don't save, or the values don't get updated when the form is reloaded within the control panel. 

**Steps to reproduce**
1. Crete a form
2. Setup integration and map input fields. 
3. Click Save
![image](https://user-images.githubusercontent.com/6044898/170735215-fa795091-5ef4-4b7e-ba6a-62029cf80a3c.png)
4. Leave / Reload the form page and observe that the field mapping is no longer present
![image](https://user-images.githubusercontent.com/6044898/170735313-f052b10b-a7c9-425d-b062-49dbe788937e.png)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: GraphQL
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 2.0.0-beta.9
- Craft version: 4.0.3
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.10](https://github.com/verbb/formie/releases/tag/2.0.0-beta.10)
