### ISSUE TITLE
Add "Date Created" or "Submission Date" to available variables for email notifications, etc

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#908]
Currently, there's only "Timestamp" and "Date" which all refer to the current date, but this might not always be accurate, especially as notifications are send via the queue, it can happen some time afterwards.

Instead, we should promote the "date created" of a submission to gain a semi-accurate time of a submission. I say semi-accurate as there are some cases for multi page forms where the user can come back to an incomplete submission much later on, that could be different (the submission element is created as soon as someone submits on the first page).

**Comment by leevigraham** [comment]
Temporary workaround: `{{ submission.dateCreated | date('Y-m-d') }}` :)

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.2](https://github.com/verbb/formie/releases/tag/2.0.2)
