### ISSUE TITLE
E-Mail Notification error when sending email notification with attachment

### ISSUE THREAD

**Issue by idleog** [verbb/formie#910]
Sending E-Mail notifications with attached upoaded files fails. 
**Maybe important: This only happens when no backend user is logged in in backend of craft cms (queue to run email notification is triggered by cronjob then). When a user is logged in, the email notification works properly.** 

Following error-message is shown in the failed status message for sending form notification:

`Failed to send notification email: {"error":"Notification email “Push Nachricht an Suchtfachstelle” could not be sent for submission “19777”. The mailer service failed to send the notification: “Swift_IoException: Unable to open file for reading [uploads/file-sample_1MB_2022-05-30-064803_zpkm.pdf] in /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131\nStack trace:\n#0 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php(77): Swift_ByteStream_FileByteStream->getReadHandle()\n#1 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/Base64ContentEncoder.php(40): Swift_ByteStream_FileByteStream->read(8192)\n#2 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(555): Swift_Mime_ContentEncoder_Base64ContentEncoder->encodeByteStream(Object(Swift_ByteStream_FileByteStream), Object(Swift_Transport_StreamBuffer), 0, 76)\n#3 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Object(Swift_Transport_StreamBuffer))\n#4 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(570): Swift_Mime_SimpleMimeEntity->toByteStream(Object(Swift_Transport_StreamBuffer))\n#5 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Object(Swift_Transport_StreamBuffer))\n#6 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(604): Swift_Mime_SimpleMimeEntity->toByteStream(Object(Swift_Transport_StreamBuffer))\n#7 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(162): Swift_Mime_SimpleMessage->toByteStream(Object(Swift_Transport_StreamBuffer))\n#8 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream(Object(Swift_Transport_StreamBuffer))\n#9 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(502): Swift_Transport_AbstractSmtpTransport->streamMessage(Object(Swift_Message))\n#10 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'info@suchtfachs...', Array, Array)\n#11 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'info@suchtfachs...', Array, Array)\n#12 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)\n#13 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2-swiftmailer/src/Mailer.php(155): Swift_Mailer->send(Object(Swift_Message))\n#14 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/mail/BaseMailer.php(263): yii\\swiftmailer\\Mailer->sendMessage(Object(craft\\mail\\Message))\n#15 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/craftcms/cms/src/mail/Mailer.php(175): yii\\mail\\BaseMailer->send(Object(craft\\mail\\Message))\n#16 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/verbb/formie/src/services/Emails.php(373): craft\\mail\\Mailer->send(Object(craft\\mail\\Message))\n#17 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/verbb/formie/src/services/Submissions.php(197): verbb\\formie\\services\\Emails->sendEmail(Object(verbb\\formie\\models\\Notification), Object(verbb\\formie\\elements\\Submission), Object(verbb\\formie\\jobs\\SendNotification))\n#18 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/verbb/formie/src/jobs/SendNotification.php(67): verbb\\formie\\services\\Submissions->sendNotificationEmail(Object(verbb\\formie\\models\\Notification), Object(verbb\\formie\\elements\\Submission), Object(verbb\\formie\\jobs\\SendNotification))\n#19 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2-queue/src/Queue.php(246): verbb\\formie\\jobs\\SendNotification->execute(Object(craft\\queue\\Queue))\n#20 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage('2325', 'O:34:\"verbb\\\\for...', '300', '1')\n#21 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute('2325', 'O:34:\"verbb\\\\for...', '300', '1', '3476440')\n#22 [internal function]: yii\\queue\\cli\\Command->actionExec('2325', '300', '1', '3476440')\n#23 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#24 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#25 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/console/Controller.php(182): yii\\base\\Controller->runAction('exec', Array)\n#26 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/base/Module.php(552): yii\\console\\Controller->runAction('exec', Array)\n#27 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction('queue/exec', Array)\n#28 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/craftcms/cms/src/console/Application.php(89): yii\\console\\Application->runAction('queue/exec', Array)\n#29 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction('queue/exec', Array)\n#30 /home/zfach/public_html/www.suchtfachstelle.zuerich/vendor/yiisoft/yii2/base/Application.php(384): yii\\console\\Application->handleRequest(Object(craft\\console\\Request))\n#31 /home/zfach/public_html/www.suchtfachstelle.zuerich/craft(23): yii\\base\\Application->run()\n#32 {main}”."}. `

**Steps to reproduce**
1. Create form with upload file field, define email notifications with attached uploaded filed
2. Fill out the form with an attached file.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.12
- Craft version: 3.7.38
- Multi-site: No

**Comment by engram-design** [comment]
Can you verify if the path `uploads/file-sample_1MB_2022-05-30-064803_zpkm.pdf` actually exists? This file should be uploaded and created as an asset when the submission is created, before an email notification tries to send. It sounds like this file hasn't been uploaded and created properly.

That's quite interesting it fails when being run via cron. I can't immediately think of why this would make a difference, but I'll look into it.

Anything special about your File Upload field settings that's worth noting for me to reproduce?

**Comment by idleog** [comment]
Thanks for your quick answer!

Yes, the path `uploads/file-sample_1MB_2022-05-30-064803_zpkm.pdf` exists. User permission: -rw-------

I think the difference is not wheter it is run by cron or not, but if there is a logged in backend user in the session.

I don't see any special field settings.

Cheers
Peter

**Comment by engram-design** [comment]
Hmmm, so I've just run a few tests running the queue job via the command line and cron, but haven't been able to replicate it.

If you could, would you be able to send through a support request from Formie (Formie > Settings > Get Support) which will send through your form and email notification settings, just in case they're different to mine. Just be sure to reference this issue.

If you can also send through your asset volume settings (path, URLs, whether public or not) as the path should be absolute, not relative to the project root. For example, using `@webroot/uploads` instead of just `uploads`.

**Comment by idleog** [comment]
I've sent a support request, but the 2nd hint with the absolute path for asset volumes seems to be the crucial thing. I don't know why I didn't use @webroot/.. in this case (normally I do that), but after changing that the notifications worked! 

Only question remaining (out of curiosity): why did the email notification workeed if a backend user was logged in?

Thanks a lot anyway for your quick and great help!
Peter

**Comment by engram-design** [comment]
Ah, nice one! I was just looking at your support request.

So I believe that when running the email notification from the control panel, the CWD will be your Craft's project root - wherever your `index.php` is stored that runs the Craft control panel (typically `web/index.php`). It'll try and find the file `uploads/file-sample_1MB_2022-05-30-064803_zpkm.pdf` relative to `web` which will be found.

But when running from cron, the CWD will likely either be the root of the server, or the directory the cron job runs from, which won't resolve to your project path, or your uploads path.

Hope that makes sense?

**Comment by idleog** [comment]
yes, that makes sense! 
Thanks again!
