### ISSUE TITLE
Cannot change form handle

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#911]
**Description**
When trying to change a form's handle, saving the form reverts its value to the previous one.

**Steps to reproduce**
1. Change a form's handle in the form settings page
2. Save and witness the value reverting to its previous value

**Additional info**
- Plugin version: beta 10
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
Thanx.
