### ISSUE TITLE
Combo styling in CP (Safari)

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#913]
**Description**
This is a really minor issue but in Safari (latest version), combos in the form designer are not styled.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/14908712/170968013-a56dff7d-bfeb-407a-b4a0-fec9117ce227.png">

(just saw this but in the same image you can see the zip field of the address field shows increments, safari only as well)

**Additional info**
- Plugin version: beta 10
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
Thanx.
