### ISSUE TITLE
Email notification not working at all (no recipient error)

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#914]
**Description**
I get a `Notification email error. No recipient email address found.` every time I try to create a new notification.
I did enter a valid recipient email address. Is it me forgetting to do something?

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/14908712/170991026-4090eae8-7c5c-45d3-8ade-c24e3d76c2f3.png">

This gets logged:

```
2022-05-30 14:23:21 [ERROR] Notification email error. No recipient email address found.
2022-05-30 14:23:21 [INFO] Request context:
$_GET = [
    'p' => 'admin/actions/formie/email/preview'
    'v' => '1653913400811'
]

$_POST = []
```

**Additional info**
- Plugin version: beta 10
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Closing as duplicate to https://github.com/verbb/formie/issues/909
