### ISSUE TITLE
Add possibility to add custom configuration fields to form "Appearance", "Behaviour", "Email Notification" etc.

### ISSUE THREAD

**Issue by benediktblank** [verbb/formie#915]
**What are you trying to do?**
I want to add some custom configuration in the forms "Appearance" and/or "Behaviour" tabs or in the "Email Notification" configuration

**What's your proposed solution?**
Similar to the way the form fields work, it would be great to also be able to add fields to these tabs. And more importantly, the values should be saved and returned via GQL API.

**Additional context**
Is that already possible and not documented or is it missing?

**Comment by engram-design** [comment]
Adding additional form settings won't be possible, sorry - and it's not something we plan on making possible. The main reason is how form settings are stored, and we can't have your own data mixed in with the core FormSettings data.

There's _maybe_ the possibility of adding Twig hooks for you to include your own Twig or fields for each tab, but you'd still be required to manage getting/setting your custom settings data.

We could also introduce a `customSettings` array to `form->settings`, but that gets messy. The real issue will be returning those via GQL, they'd just have to be a JSON-encoded string, as we have no idea what your custom data is.

Your best-bet is to add custom fields to a Form Template, which will appear in tabs, just after the "Fields" tab.

**Comment by benediktblank** [comment]
Alright, I understand.

It would also be fine for me to handle the saving of the data myself I guess.
But if there is no way to return the data via to formie GQL, there would be no point in adding these fields in the first place.

Would you rather recommend, that I use the "Integration" feature, as a way to add more Form configuration fields?
Maybe that's the better/easier way right now?
As it's already integrated into GQL as well and the saving of the fields is also covered I think.

> Your best-bet is to add custom fields to a Form Template, which will appear in tabs, just after the "Fields" tab.

How would I do that?

**Comment by engram-design** [comment]
Head to Formie > Settings > Form Templates and create a new template. You can leave pretty much all the defaults as-is, just give it a name, and look at the "Form Fields" tab, where you can add any custom fields you like.

They'll then appear in the form builder, and you can access these via GQL.

Here's a quick example where I've just thrown in a "Heading" UI element:

![image](https://user-images.githubusercontent.com/1221575/171108734-43dde309-dfa0-4ee2-bd24-2cd8d279c36b.png)

**Comment by benediktblank** [comment]
Ah ok, I see. But I had to configure the template under "Appearance->Form Templates" in my form, or else it wasn't in use and still used the Formie default.
After I change that to my template, the additional tab appeared and that looks pretty good.
And that's being returned via GQL automatically as well? I have to check that out but that seems like just what we need I guess.
Thank you

**Comment by engram-design** [comment]
Sorry, yes that's correct, you'll need to configure your form to use that form template. And yep, you should be able to access that via GQL like any other field (but directly on the form element)

```
{
    form (handle: "contactForm") {
        title
        handle
        myCustomField
}
```

**Comment by benediktblank** [comment]
Alright, thanks again, I think that's pretty great and fit's our need.
I assumed "Form Templates" meant the template the form uses in the Frontend. That's why I never had a look at that setting at all. Never would have guessed it could change the form builder itself and add a tab and fields there. Really cool. Will check it out further now.

**Comment by benediktblank** [comment]
@engram-design Is there a way to import/export "Email Templates" and "Form Templates" (the settings) as part of the project-config or as a separate JSON?

**Comment by engram-design** [comment]
Yeah, it kinda serves two purposes - one for the templates, CSS/JS on the front-end, and another to define any additional custom fields on the form.

No way to import email/form templates sorry. The reason being is that these are stored in project config, unlike forms and fields (which you're importing/exporting). As such, you shouldn't need to import/export these templates, as they're synced in project config.

**Comment by benediktblank** [comment]
Ah I see, they **are** exported via the project-config. That's great as well. I missed that completely somehow and thought they were not exported at all. Thanks for the info.

**Comment by benediktblank** [comment]
> And yep, you should be able to access that via GQL like any other field (but directly on the form element)
> 
> ```
> {
>     form (handle: "contactForm") {
>         title
>         handle
>         myCustomField
> }
> ```

Can you verify that this works? I'm unable to query my field like that. It's not included in the GQL structure and trying to query it anyway results in an error.
![image](https://user-images.githubusercontent.com/69143768/171123354-26e7432d-db75-49d5-911d-c6a2c557a57e.png)

![image](https://user-images.githubusercontent.com/69143768/171123258-7df62dc3-0277-4a1e-9eea-bc7b239988d8.png)

![image](https://user-images.githubusercontent.com/69143768/171123522-5c901145-c25b-4405-bc41-dc9c36ec4edc.png)

**Comment by engram-design** [comment]
Looks like you're right, this doesn't actually work. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.18",
  "...": "..."
}
```

Then run `composer update`. 

Just be aware to cast the form correctly as well:

```gql
{
    form (handle: "contactForm") {
        title
        handle

        ... on contactForm_Form {
            myCustomField
        }
    }
}
```

**Comment by benediktblank** [comment]
Wow, once again, you're awesome. Thank you. I will have a look now.

**Comment by benediktblank** [comment]
> Just be aware to cast the form correctly as well:
> 
> ```graphql
> {
>     form (handle: "contactForm") {
>         title
>         handle
> 
>         ... on contactForm_Form {
>             myCustomField
>         }
>     }
> }
> ```

Yes, now it works with the "on contactForm_Form" handle.
Before I had just the "Form" handle there. That "global" (so to speak) handle is now gone and there are handles for each of my forms now instead. Just like Craft does with the handles for each Section.
That's better to handle now too. I always wondered why Formie did that different.

**Comment by benediktblank** [comment]
I'm really, really happy with these Form Templates.
Using the regular CraftCMS Fields here gives me so many options now.

But I've noticed that the configured values in these fields are not exported, neither in the project-config nor when exporting the form with the Formie export functionality. Would that also be possible somehow?

**Comment by engram-design** [comment]
Sure, that's something we can look at adding support for. I assume you're still on Craft 3?

**Comment by benediktblank** [comment]
Yeah, still on Craft 3 at the moment but an update is planned.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.3](https://github.com/verbb/formie/releases/tag/2.0.3)
