### ISSUE TITLE
Entries field with custom source shows every sources

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#917]
**Description**
It looks like when using an `entries` field with a single custom source (mine is a structure conditionally defined with its type and a level of 1), well the resulting combo box shows all entries from all sources. Not what I expected ;)

Ping me if you need a more precise context to reproduce.

**Additional info**
- Plugin version: beat 10
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Custom sources should work in the same way that normal sources work, so that seems strange. Would you be able to post your custom source registration (the event code)?

**Comment by JeanLucEsser** [comment]
Sure, could you just point me in the right direction to give you what you need. What do you mean by the event code? How do I find this.

**Comment by engram-design** [comment]
You mentioned a custom source, so I imagine you're registering ones via `Element::EVENT_REGISTER_SOURCES`?

```php
Event::on(Entry::class, Element::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $event) {
    $event->sources[] = [
        'heading' => Craft::t('formie', 'Statuses'),
    ];

    foreach (Entry::statuses() as $status => $label) {
        $event->sources[] = [
            'key' => 'status:'.$status,
            'label' => $label,
            'criteria' => ['status' => $status]
        ];
    }
});
```

The above creates custom sources for entries, for each of their status. You'd have something similar, but to your specific needs. Or am I misunderstanding the issue?

**Comment by engram-design** [comment]
Hmm, okay - so after modelling a brand new custom source, unlike the ones above (which do work correctly):

```php
Event::on(EntryElement::class, Element::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $event) {
    $event->sources[] = [
        'key' => 'custom-blog',
        'label' => 'Custom Blog',
        'criteria' => ['id' => '23'],
    ];
});
```

Where we create a "Custom Blog" entry source, showing just a single entry (with ID "23"), seems like I can replicate that.

**Comment by engram-design** [comment]
Looks like this was just an issue with the Entries field, as all other element fields are correct. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
I was modeling custom sources directly via the CP interface, sorry I didn't mention this.
Will test your release in a couple hours and report back.

**Comment by engram-design** [comment]
Oh, of course! That being a new Craft 4 feature. Still, the same thing applies to sources defined in an event or through the sources builder.

**Comment by JeanLucEsser** [comment]
Doesn't look like it is fixed.

### Here is a capture of my custom source:
(it is a 2 level structure, custom source shows only level 1)

<img width="695" alt="image" src="https://user-images.githubusercontent.com/14908712/171181641-469b2be5-91f1-4714-b368-0cbbdf12491a.png">


### This is my entries field setting, only the custom source is selected:
(options order is post date asc)

<img width="301" alt="image" src="https://user-images.githubusercontent.com/14908712/171182174-416929b9-dada-4226-acce-16bd6e1c8e59.png">


### Front result shows all entries from all sources:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/14908712/171182858-91fe7408-c356-4b8a-b0d7-5f4fb110fa31.png">

**Comment by engram-design** [comment]
Right, so it looks like sources defined that way _are_ different, using conditionals, so we need to parse them differently.

Fixed in the same `craft-4` branch if you can run that command again.

**Comment by JeanLucEsser** [comment]
Fixed! Closing this. Thanx.
