### ISSUE TITLE
Can only install one of: league/oauth2-client[2.5.0, 2.4.1].

### ISSUE THREAD

**Issue by bartrylant** [verbb/formie#92]
When trying to install Formie with Composer, I get:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: league/oauth2-client[2.5.0, 2.4.1].
    - Can only install one of: league/oauth2-client[2.5.0, 2.4.1].
    - Can only install one of: league/oauth2-client[2.5.0, 2.4.1].
    - verbb/formie 1.2.7.1 requires league/oauth2-client ^2.5 -> satisfiable by league/oauth2-client[2.5.0].
    - Installation request for verbb/formie 1.2.7.1 -> satisfiable by verbb/formie[1.2.7.1].
    - Installation request for league/oauth2-client (locked at 2.4.1) -> satisfiable by league/oauth2-client[2.4.1].

Composer file:
[composer.json.zip](https://github.com/verbb/formie/files/5188752/composer.json.zip)

**Comment by engram-design** [comment]
Fixed in [1.2.8](https://github.com/verbb/formie/releases/tag/1.2.8)
