### ISSUE TITLE
[Craft 4] Invalid JSON data error after form submit with email notification

### ISSUE THREAD

**Issue by studiobruikbaar** [verbb/formie#921]
**Description**
I want to send a notification mail after a form submission. When the notification mail is disabled, the form works as expected. But when enabled, I get the following error message:

```
yii\base\InvalidArgumentException: Invalid JSON data. in /Users/jeroenkroes/dev/37pk/vendor/yiisoft/yii2/helpers/BaseJson.php:123
Stack trace:
#0 /Users/jeroenkroes/dev/37pk/vendor/verbb/formie/src/services/Notifications.php(421): yii\helpers\BaseJson::decode(Array)
#1 /Users/jeroenkroes/dev/37pk/vendor/verbb/formie/src/services/Submissions.php(172): verbb\formie\services\Notifications->evaluateConditions(Object(verbb\formie\models\Notification), Object(verbb\formie\elements\Submission))
#2 /Users/jeroenkroes/dev/37pk/vendor/verbb/formie/src/services/Submissions.php(146): verbb\formie\services\Submissions->sendNotifications(Object(verbb\formie\elements\Submission))
#3 /Users/jeroenkroes/dev/37pk/vendor/verbb/formie/src/controllers/SubmissionsController.php(544): verbb\formie\services\Submissions->onAfterSubmission(true, Object(verbb\formie\elements\Submission))
#4 [internal function]: verbb\formie\controllers\SubmissionsController->actionSubmit()
#5 /Users/jeroenkroes/dev/37pk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /Users/jeroenkroes/dev/37pk/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /Users/jeroenkroes/dev/37pk/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('submit', Array)
#8 /Users/jeroenkroes/dev/37pk/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('formie/submissi...', Array)
#9 /Users/jeroenkroes/dev/37pk/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('formie/submissi...', Array)
#10 /Users/jeroenkroes/dev/37pk/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /Users/jeroenkroes/dev/37pk/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /Users/jeroenkroes/dev/37pk/web/index.php(21): yii\base\Application->run()
#13 /Users/jeroenkroes/.composer/vendor/laravel/valet/server.php(234): require('/Users/jeroenkr...')
#14 {main}
```

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Both
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-4
- Craft version: Craft Pro 4.0.3
- Multi-site: No

**Comment by engram-design** [comment]
This seems to point to some corrupt conditions settings for the email notification. Can you send through the `conditions` column in your `formie_notifications` database table for the notification for this form? If you could also try re-saving the form, just in case.

Can you let me know your `max_input_vars` PHP setting? It could be that your form data is so large that your PHP settings might need to be tweaked to handle lots of POST data.

Failing all of that, if you send through a support request (Formie > Settings > Get Support) that'll send us through your form/notifications data so we can look firsthand.

**Comment by studiobruikbaar** [comment]
Thanks for your quick response. Just walked trough the email form settings and found out the email conditions were enabled, but no conditions were applied. Disabling the conditions solved my problem. 

![CleanShot 2022-06-01 at 09 29 32@2x](https://user-images.githubusercontent.com/15730488/171351691-d49cc805-f646-43f5-a90e-b12c2fad7431.png)

**Comment by engram-design** [comment]
Ah, thanks for pointing that out, we'll ensure there's extra checks in there for that!
