### ISSUE TITLE
No line breaks in email notification

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#924]
**Description**
In the email content field of an email notification, line breaks (shift+enter) are ignored in the preview and in the actual email.

While we're at it, I'm throwing a FR, could we have two more options in this field:
- clear format button (very helpful when pasting content with unwanted styling)
- add link button

**Additional info**
- Plugin version: beta 10
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.10",
  "...": "..."
}
```

Then run `composer update`. 

And both those additional buttons are available to be included - https://verbb.io/craft-plugins/formie/docs/get-started/configuration#available-buttons

**Comment by JeanLucEsser** [comment]
> And both those additional buttons are available to be included

I swear I always read the docs. Missed it completely, thanx!

**Comment by JeanLucEsser** [comment]
So to thank you for your excellent documentation (that I should read more often) I'm throwing a little sponsoring your way. Should have done this long ago tbh. 11 down, 9 to go, and probably way more.

**Comment by engram-design** [comment]
Quite alright to miss it, and to be fair, a bunch of those options are in fact new in Formie v2.

Thanks also for the sponsorship, that means so much! We've got lots of open source plugins coming in July, so that really helps! 🙏 ❤️
