### ISSUE TITLE
Allow markdown or html inside agree field description

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#93]
We always have an agree field in our contact forms which says something like "I agree with the privacy policy" where 'privacy policy' would link to the dedicated policy page. However, fields in Formie don't allow HTML or Markdown in their descriptions.
I've read here on GitHub that's due to keeping it simple for users, but it would be very nice if this could be added to the agree field alone. I think this is a use-case that a lot of people could benefit from?

An alternative (to have a better UX for less techie people) could be to have a separate setting in such a field to add a link (url or craft entry) and label for that link that would be positioned somewhere around the actual description? Or maybe just an icon with an arrow or question mark that would become visible.

**Comment by engram-design** [comment]
Yep, I can see how this would be common. I'm probably anti HTML and Markdown specifically, but would adding a rich text editor to the Description field work in your case? This would be just for the Agree field's description.

I'll just need some extra time to improve the link functionality to include picking from existing entries, and currently you can only enter in a URL - which is fine - but it'd be nice to mimic Redactor.

**Comment by TomDeSmet** [comment]
That would definitely solve my use-case.
Entering a URL only would work for now too. As you made all the fields translatable with the static translation files in a previous update, we can add a different URL for every language there. It's a workaround, but at least those hardcoded url's are all in the same place.

**Comment by engram-design** [comment]
Added in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)

**Comment by TomDeSmet** [comment]
Sorry to post in a closed topic, but I just updated and I get an error: `Invalid Argument – yii\base\InvalidArgumentException`.
![Screen Shot 2020-10-12 at 15 40 39 PM](https://user-images.githubusercontent.com/16959207/95753084-588f8200-0ca1-11eb-821b-65ed1ff5bad8.png)

I already added markdown to this field (prior to the update) and added my own `agree.html` template that parsed that markdown. It seems the migration there goes wrong.

But I can't get into the CP anymore to change this because of the error.

**Comment by engram-design** [comment]
The migration should've converted that text, as it seems to be still a string, rather than JSON content blocks. I

Should be improved in [1.2.21](https://github.com/verbb/formie/releases/tag/1.2.21), but maybe double check your field and re-save it.

**Comment by engram-design** [comment]
The migration should've converted that text, as it seems to be still a string, rather than JSON content blocks. I

Should be improved in [1.2.21](https://github.com/verbb/formie/releases/tag/1.2.21), but maybe double check your field and re-save it.
