### ISSUE TITLE
Entries field has no output in notifications

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#95]
**Description**
Entries field works fine now. But notifications contain No response for field's value (label is printed correctly).
IN CP / Formie / Submissions the submission shows correctly the entries field content.

**Steps to reproduce**
1. Create entries field, in my case News:Offers
2. send form
3. notification contains filed title and No response.
4. submission is saved correctly

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes 

**Additional info**
- Plugin version: 1.2.8
- Craft version: 3.5.9
- Multi-site: Yes

**Comment by engram-design** [comment]
Can you let me know the content of your email notification? The output for the email value should be pretty close to identical for the submission value. I'm surprised that the submission value is correct, but the notification isn't.

**Comment by lexislav** [comment]
I am using the same field and settings as in #94 
Screenshots of submission, notification body and field settings here:
https://www.dropbox.com/sh/9zultbde1hfs95i/AADZUZ4DN7UEUT2ufNk_y2DXa?dl=0

edit: I have update to 1.2.9 and no change with notifications

**Comment by engram-design** [comment]
Thanks for that. The entry you've picked - anything special about that? Is it from a particular site, or anything like that to give me a clue to reproduce it?

It's normal (for the moment) for it to show "No Response" in the email preview, but that's unrelated.

**Comment by lexislav** [comment]
I did some testing – I have created a few entries fields with different sections.

Only one has correct output in notification: https://www.dropbox.com/s/hfwi26wgmrqjf0s/screnn7%20-%20notification%20body.png?dl=0
It is Photogallery section, its settings:
https://www.dropbox.com/s/qa7xsbs94r5060r/screen8%20-%20fotogalerie%20section%20setting.png?dl=0
and the selected entry:
https://www.dropbox.com/s/baqcaje091t7w5d/screen9%20-%20fotogalerie%20entry%20setting.png?dl=0
Primary site marked with yellow dot.

Screenshots related to field with no output:
https://www.dropbox.com/s/cv9n0jokh8ndwi6/screen9%20-%20source%20section%20content.png?dl=0
https://www.dropbox.com/s/irh7lqwyg0fmk21/screen9%20-%20section%20setting.png?dl=0
https://www.dropbox.com/s/u8ejop85nltsdac/screen9%20-%20entry%20record.png?dl=0

So, my guess is that it checks the status of entry on primary site…

**Comment by engram-design** [comment]
Thanks for that info - should be fixed in [1.2.10](https://github.com/verbb/formie/releases/tag/1.2.10)

**Comment by lexislav** [comment]
It works. Thanks.
