### ISSUE TITLE
Blank e-mail in Outlook and Mail

### ISSUE THREAD

**Issue by Saboteur777** [verbb/formie#952]
**Description**

The notification e-mail is blank if viewed in Outlook or in Apple Mail. The content is visible if viewed in Gmail. 
In the control panel the preview is working fine, the sent notification also looks good. 

**Steps to reproduce**
1. Set up a regular notification for a form. No HTML template is used, just plain text. 
2. Set notification content to All Form Fields (and nothing else).
3. Submit a form, check the notification in Outlook or Apple Mail. 

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.6.1
- Craft version: 3.7.45.1
- Multi-site: No

**Additional context**

I can send an example notification for you if you need it for debugging.

**Comment by engram-design** [comment]
That seems strange, as the default templates are about as plain HTML as you can get. I can't replicate this on my end, and I've even run the output through [Litmus](https://www.litmus.com/)

**Comment by Saboteur777** [comment]
Thanks for the quick response! I have just resent the notification to web@verbb.io.

**Comment by engram-design** [comment]
Thanks for sending that through. Testing in Apple Mail 13.4 looks good to me! 

![CleanShot 2022-06-24 at 20 02 56@2x](https://user-images.githubusercontent.com/1221575/175513215-f442ccb4-7a25-4ece-8427-bf96854e9faf.png)

**Comment by Saboteur777** [comment]
Thanks a lot for looking into it, the cause must be somewhere else then.

**Comment by engram-design** [comment]
- What mailer are you using?
- What version of Apple Mail?
- Does a test email from Craft do the same thing?
- What about re-sending a sent email notification?
- Using all just the default Formie email template?

**Comment by Saboteur777** [comment]
- Amazon SES
- 16.0 (3696.100.31)
- The content of the password reset e-mail is visible. 
- The content is still not visible. 
- The e-mails are plain text without any e-mail templates set up. You can see the settings below: 

![kép](https://user-images.githubusercontent.com/9061795/175607068-378e6ad7-6e91-4c03-8a5f-626576e58715.png)
![kép](https://user-images.githubusercontent.com/9061795/175607145-4a5955e1-48a3-4a89-9504-005779551603.png)

**Comment by Saboteur777** [comment]
@engram-design Did you have a chance to look into this? Do you have any progress?

**Comment by engram-design** [comment]
I haven't been able to make any progress I'm afraid, despite even spinning up Outlook on a Windows 10 machine just to test. The only thing I can think of is Amazon SES being the difference, so I'll spin that up.

**Comment by Saboteur777** [comment]
Is there anything I can help with your investigation?

**Comment by engram-design** [comment]
Not quite sure, maybe even just reducing the content of the notification to plain text - so no variables or submission content, or using a different mailer?

**Comment by engram-design** [comment]
I've been testing using Amazon SES and your listed email clients, and no issue there. If you can try some of my suggestions and let me know?

And just to check you're not using any **HTML Email Template** in Craft > Settings > Email (not Formie).

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1221575/178479346-7439f91e-3d27-4984-8db7-d04131fe46a2.png">

**Comment by engram-design** [comment]
@Saboteur777 Any chance to try:

> reducing the content of the notification to plain text - so no variables or submission content, or using a different mailer?

Still unable to replicate this I'm afraid!

**Comment by Saboteur777** [comment]
Thanks for the follow ups! I recently checked up with the client, and the error is pretty hard to reproduce, as it is not consistent: sometimes the same user/app receives the e-mail with all the content, sometimes the e-mail is completely blank. 

The **HTML Email Template** option is empty. 

I think this has nothing to do with Formie, so I close this issue.

**Comment by engram-design** [comment]
Right, that's interesting how it isn't consistent. I'll keep at it on my end.

However, with the change in mailer service in Craft 4, I'm almost sure this won't be an issue for Formie 2 (although as I can't reproduce it, I can't guarantee that)

**Comment by Saboteur777** [comment]
We successfully narrowed this down to a hidden field with HTTP Refer URL as a default value: tried every field one-by-one to be included in the notification e-mail, and the only case when Mail failed to display the e-mail was with this field (and it was consistent).

**Comment by engram-design** [comment]
How strange, I can't replicate that on my end either! The email shows the value of the referrer (the URL where the form was submitted from), on Apple Mail 16, Gmail, iOS 15/16 Mail.

I can't imagine Amazon SES does anything like filtering the content of the email. I don't suppose it worth trying another mailer just in case there's something specific about SES?

**Comment by Saboteur777** [comment]
Yes, it is strange. But the content is there, as we checked the source of the emails. It is just not displayed. 😶

(The issue is also present on a Windows machine with Outlook.)

**Comment by engram-design** [comment]
Huh, that's even stranger! Are you sure there's no other software that might be interfering, like AntiVirus stuff? 

Looking back on your original email you forwarded to `web@verbb.io` I can see that just fine. Since then, I have updated to Apple Mail 16, and I've also tested it on Windows 10 with Outlook - all show the email fine. 

That email does use Gmail as its provider, but I don't _think_ that would make a difference. But, what email provider does the recipient of these emails use - just in case its a bespoke one with its own filtering or spam handling that might be interfering on their servers?

It seems extremely suspect that the content of the email exists in your source, but it's not displayed.

The referrer URL doesn't have any special characters or anything in it?

**Comment by Saboteur777** [comment]
Yeah, I agree. According to the users of these devices, no antivirus software is running. As far as I know, Outlook on PC, Mac Mail and Outlook on mobile are affected. (`No content to display` & `This message has no content` is displayed.)

The e-mail provider is Google, as these accounts are Google Workspace accounts. The content of the e-mail is there, as the standard Gmail web client displays it fine, and the source is also visible in the client if inspected with the View > Message > Raw Source option.

Only those special characters are present which supposed to be in a URL. 

I sent another example to web@verbb.io, which was saved from one of the affected e-mail client.

**Comment by engram-design** [comment]
Thanks for sending that through, so that clarifies things a bit. It's rendering the plain text version of the email just fine:

```
--_=_swift_1669914721_44454e3ade8109bc583d9499308326d2_=_
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

 LEAD CHANNEL
Website

etc...

--_=_swift_1669914721_44454e3ade8109bc583d9499308326d2_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

----CONTENT SHOULD BE HERE----

--_=_swift_1669914721_44454e3ade8109bc583d9499308326d2_=_--
```

But not the HTML version of the email (which should be after the `Content-Type: text/html; charset=utf-8`) - it's just empty. At least I can see that replicated with that email.

Are you able to check your `storage/logs/formie.log` files, in case there's been an issue rendering the HTML content of the email? Just trying to determine _where_ the HTML content is being stripped off - at Formie's end, SES, or the recipient server.

**Comment by Saboteur777** [comment]
There is no HTML template set in Craft's configuration. Could that be an issue in this case? I will give it a try and we will see.

**Comment by engram-design** [comment]
Nah you don't need to setup a HTML template, Formie will generate a HTML version and plain text version of the email content, and use that for the email. A notification template is just in case you want to use your own design for the notification.

**Comment by Saboteur777** [comment]
Testing locally with Mailhog: 

![kép](https://user-images.githubusercontent.com/9061795/206244861-46d1c88e-f8a1-4ef8-b03b-bfcb280b9474.png)

![kép](https://user-images.githubusercontent.com/9061795/206244952-f030c71a-d1a3-4510-97a5-d1597cf4b770.png)

![kép](https://user-images.githubusercontent.com/9061795/206245088-46355c7b-17e9-471f-afe6-542532d79a48.png)

It seems the HTML is present. Tested it with another Google Workspace account, the HTML content was there. 
¯\\_(ツ)_/¯

**Comment by Saboteur777** [comment]
Just out of curiosity I set up HTML template for e-mail being sent by Craft, and also set up an HTML template for Formie, which finally solved the issue!

**Comment by engram-design** [comment]
Interesting! I've been testing with no email template (in Craft or Formie), but glad that's got it solved for you!
