### ISSUE TITLE
Populate Entries field

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#96]
**What are you trying to do?**
I would like to define selected option on entries field.
Something like:

```
{% do craft.formie.populateFormValues(formId, { entriesField: entry.id }) %}
{{ craft.formie.renderForm(formId) }}
```

Or does this work somehow already?

**Comment by jaydensmith** [comment]
Hey @lexislav, for element form fields, the `populateFormValues` method expects a query:
```twig
{% do craft.formie.populateFormValues(formId, {
    entriesField: craft.entries.id(entryId),
}) %}
```

**Comment by engram-design** [comment]
Also added docs to clarify - https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms
