### ISSUE TITLE
Unable to save form after bulk adding options to dropdown, radio, checkbox, ... fields

### ISSUE THREAD

**Issue by Antimated** [verbb/formie#961]
**Steps to reproduce**
1. Create a form
2. Drag a dropdown into the editor
3. Press "Bulk add options"
4. Select from "Predefined options" (e.g. countries)
5. Enter a field label (because it's required)
6. Try and save the form receiving a "Unable to save form" message.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 2.0.0-beta.14
- Craft version: Craft Pro 4.0.5.2
- Multi-site: Yes

**Additional context**

Screenshot of console error after save:
<img width="1655" alt="Screenshot 2022-06-29 at 10 32 58" src="https://user-images.githubusercontent.com/2869409/176390876-3a801c10-dc1b-4588-b3ca-68c609086642.png">

**Comment by Antimated** [comment]
@engram-design Hey, did you find any time to look at this issue? not that pressing of an issue for me but could be critical for other people :)

**Comment by engram-design** [comment]
Not sure how I missed this, but fixed as per https://github.com/verbb/formie/issues/990
