### ISSUE TITLE
[SalesForce] Lead are not saved

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#963]
**Description**
 The leads are not saved in Salesforce anymore. We have checked and the issue is with the Country field. When we disable the Country field in the form settings, the integration works and the lead is sent to SF. When it's enabled, the integration breaks.

**Sentry:**
`2022-06-30 12:11:10 [-][1609][-][error][formie] Salesforce: API error: “[{"message":"There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries.: Country","errorCode":"FIELD_INTEGRITY_EXCEPTION","fields":["Country"]}]” /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113`

**Lead mapping:**
![изображение](https://user-images.githubusercontent.com/496132/176656759-58bae5c9-0994-4738-beb6-d8b917a732ad.png)

**Form**
![изображение](https://user-images.githubusercontent.com/496132/176659022-84c68fe1-f78c-4eaf-9a15-2d934ce7d21c.png)

![изображение](https://user-images.githubusercontent.com/496132/176659079-dbda469b-c678-434f-881d-a26313169e63.png)

![изображение](https://user-images.githubusercontent.com/496132/176659128-3543b533-203d-43fc-b4e5-b4fab15bee67.png)

![изображение](https://user-images.githubusercontent.com/496132/176659195-274f7e26-7fc2-440d-9b9e-d237600441f0.png)

![изображение](https://user-images.githubusercontent.com/496132/176659272-ce5a7110-5df1-412d-8760-30959dd1e505.png)

**Steps to reproduce**
1. Add SF integration
2. Setup Lead with country from phone
3. Submit form

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: YNo

**Additional info**
- Plugin version:  1.6.1
- Craft version: Craft Pro 3.7.46
- Multi-site: Yes or No

**Additional context**

**Comment by engram-design** [comment]
Right, so the country value from a phone number field will only be the ISO value for the country that it resolves to. I believe Salesforce will need the full country name, which is not something the Phone field supports (yet).

We'll probably need to look into a way to provide both the ISO code and full country name and the ability to select either one from the integration settings.

I would recommend removing that mapping and using a proper Address or Text field if you need to capture the country information from the user. Or there are events you can use to modify the payload sent to Salesforce through PHP, you can lookup the full country name from the ISO code and swap it out.

**Comment by umkasanki** [comment]
Got It.
Added event

**Comment by engram-design** [comment]
Added the ability to pick the country ISO and full name for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)

**Comment by umkasanki** [comment]
Hi @engram-design .
Previously we used this code to fix the country:
```
        Event::on(Submissions::class, Submissions::EVENT_BEFORE_TRIGGER_INTEGRATION, static function(TriggerIntegrationEvent $event) {
            // Salesforce integration
            if ($event->integration instanceof Salesforce) {
                /* @var Submission $submission */
                $submission = $event->submission;
                $phoneNumber = $submission->phoneNumber;
                if (true === isset($phoneNumber) && $phoneNumber instanceof \verbb\formie\models\Phone && true === isset($phoneNumber->country)) {
                    $countryIsoMap = Craft::$app->config->getConfigFromFile('formie')['customCountries'];
                    $submission->phoneNumber->country = $countryIsoMap[$phoneNumber->country];
                }
            }
        });
```
This worked fine until the Craft update to v4.
After the update, this trick stopped working :(
```
Salesforce: API error: “[{"message":"There's a problem with this country, even though it may appear correct. Please select a country/territory from the list of valid countries.: Country","errorCode":"FIELD_INTEGRITY_EXCEPTION","fields":["Country"]}]” /home/forge/builds/bkbn/master/61/app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```
Could you check what could be the problem?
Thanks.

Craft Pro 4.3.6
Formie |2.0.20

**Comment by engram-design** [comment]
Might have something to do with:

```
$submission->phoneNumber->country = $countryIsoMap[$phoneNumber->country];
```

Which isn't the correct way to set element field values in Craft 4.

```
$phoneNumber = $submission->phoneNumber;
$phoneNumber->country = $countryIsoMap[$phoneNumber->country];

$submission->setFieldValue('phoneNumber', $phoneNumber);
```

**Comment by umkasanki** [comment]
Thanks Josh!
Awesome support!
