### ISSUE TITLE
Triggering form integrations error in Queue Manager

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#97]
**Description**
I am getting a lot triggering errors for formie submissions in Utilities / Queue Manager
Screenshots here:
https://www.dropbox.com/sh/r5qqo51n3b0erue/AAC_cI2bpY2tmxNU1UmeMaM0a?dl=0
Not sure if it is caused by wrong settings, but settings seems right to me…

- Multi-page form: No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.10
- Craft version: Craft Pro 3.5.9
- Multi-site: Yes

**Comment by engram-design** [comment]
Not sure how that regression slipped in, but should be fixed in [1.2.11](https://github.com/verbb/formie/releases/tag/1.2.11).

I should mention you can safely delete those queue jobs. They shouldn't have been created in the first place.
