### ISSUE TITLE
Forms fail to init if DOMContentLoaded has already fired before formie.js runs

### ISSUE THREAD

**Issue by rungta** [verbb/formie#977]
### Describe the bug

https://github.com/verbb/formie/blob/fe25fd7e629a8166ca0454c7af0c0c3dd361b207/src/web/assets/frontend/src/js/formie.js#L7-L10

There are cases when the `formie.js` script may only have a chance to run _after_ the page has loaded. One example is if using Pjax on a site and including the Formie script only on the second or third page (because that is the one that contains a form). In these cases, the `DOMContentLoaded` event has already fired so `window.Formie.initForms()` is not called. 

Perhaps the script could check for this condition and directly call `initForms()` when `document.readyState != 'loading'` ([as suggested by MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#checking_whether_loading_is_already_complete)).

### Steps to reproduce

1. Create a page which completes its initial load without the Formie script
2. Add a Formie form to the DOM
3. Add the Formie script to that page
4. Test `window.Formie.forms` in the console.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.47.1

### Plugin version

1.6.2

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by rungta** [comment]
Thanks Josh!

**Comment by rungta** [comment]
Applied the fix and now the forms do get initialised (JS validation etc. kick-in) even if they are loaded at a later point of time via Ajax. However, any custom field JS appears to be broken. For instance, I have a form with the Phone field. When that is lazyloaded along with `formie.js` I can see network requests for `/cpresources/c92efe83/phone-country.js?v=1657283757` and subsequently for `https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.min.js` as well but this is what happens to the phone field.

![image](https://user-images.githubusercontent.com/663677/177996904-12d5c50c-0f2d-4aca-90b8-1b38404abda0.png)

Normal synchronous page load works fine:

![image](https://user-images.githubusercontent.com/663677/177997102-0dfa137c-707f-4df8-95dd-9e8dae987426.png)

**Comment by engram-design** [comment]
So any field-level JS is lazy-loaded itself, after the form is initialized. Is it just the phone field playing up, or other [fields with JS](https://github.com/verbb/formie/tree/craft-3/src/web/assets/frontend/src/js/fields)

I should mention that it looks like the JS is being triggered as those countries don't appear without it, but maybe the CSS is failing. Do you see a network request for `/cpresources/6ce53e93/phone-country.css?v=1657286217`?

**Comment by rungta** [comment]
I tried out a checkbox field and I believe that is functioning as expected.

> I should mention that it looks like the JS is being triggered as those countries don't appear without it, but maybe the CSS is failing. Do you see a network request for /cpresources/6ce53e93/phone-country.css?v=1657286217?

Right, this might indeed be the case. I don’t see any network requests for the `phone-country.css` file. I do see that file request on a normal synchronous page+form load.

**Comment by engram-design** [comment]
So the CSS for field's isn't lazy-loaded, but loaded in [templates](https://github.com/verbb/formie/blob/1405b0811a2a896af29329975b0120c1d3cf98d0/src/templates/_special/form-template/fields/phone.html#L33), which I wouldn't have _thought_ be an issue. But it depends how you're lazy-loading the form.

Typically, for lazy-loaded forms, you'll have something like:

**index.html**
```twig
<div class="form-wrap"></div>
<button class="js-load-form">Load Form</button>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$('.js-load-form').on('click', (e) => {
    e.preventDefault();

    $('.form-wrap').load('ajax.html', function() {
        Formie.initForms();
    });
});
</script>
```

**ajax.html**
```twig
{{ craft.formie.renderFormCss('myForm') }}
{{ craft.formie.renderFormJs('myForm') }}

{{ craft.formie.renderForm('myForm') }}
```

**Comment by rungta** [comment]
That fixed it. Manually rendering the CSS alongside the form’s HTML now fetches field-specific CSS files as well. Thanks!
