### ISSUE TITLE
Fix Entry integrations resetting using PHP 8.1

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#979]
### Describe the bug

This can only be reproduced with PHP 8.1, but I can't immediately reproduce it. But at least 2 people are reporting this issue.

> Each time we go to edit an integration the 'Entry Field Mapping' field is blank. it says no fields available. If I change the Entry Type dropdown to a different section and then back to the desired section again the fields all appear but they all need to be set again.

Downgrading to PHP 8 solves this.

**Comment by superflausch** [comment]
@engram-design The DB dump I provided for [the memory issue in 2.0.2](https://github.com/verbb/formie/issues/993) is the same project we have this issue. Maybe this helps.

**Comment by engram-design** [comment]
Ah, handy @superflausch! I've tested the forms for your database and on PHP 8.1, and it's all working correctly for me.

![image](https://user-images.githubusercontent.com/1221575/180121851-22eb36b6-e59b-417d-b6cf-b2cf5268cf77.png)
