### ISSUE TITLE
Render field "input submit"

### ISSUE THREAD

**Issue by paallaire** [verbb/formie#983]
### Question

I have a form with a custom layout. 
I managed to have the fields of the form (with https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields)
but not the input "submit"

How to get the input "submit" ?

**Code**
`    
{% set formHandle = currentSite.language == 'en' ? 'jobsAvailableEnglish' : 'jobsAvailableFrench'  %}
{% set form = craft.formie.forms({ handle: formHandle }).one() %}

    <form method="post" data-fui-form="{{ form.configJson }}">
      {{ csrfInput() }}
      {{ actionInput('formie/submissions/submit') }}
      {{ hiddenInput('handle', form.handle) }}

      {{ craft.formie.renderField(form, 'courriel') }}

      {# input submit ???? #} 
    </form>
`

**Comment by paallaire** [comment]
Also the javascript "formie.js" is not loaded when l try custom "rendering fields"

**Comment by engram-design** [comment]
This is correct behaviour because you are custom rendering. Please read the docs on [custom rendering](https://verbb.io/craft-plugins/formie/docs/theming/custom-rendering) forms.

You will have to implement buttons yourself, along with registering CSS and JS.
