### ISSUE TITLE
Googlesheets integration missing country code for phone numbers

### ISSUE THREAD

**Issue by jubalj** [verbb/formie#987]
### Describe the bug

Country codes for phone number fields are stored in submission data but do not populate in google sheets integration - only the phone number does.

### Steps to reproduce

1. Create form with mobile number
2. setup integration with google sheets
3. make a submission with phone number
4. View submitted data (with country code) vs view data in google sheets - missing country code

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: No

### Craft CMS version

4.1.7

### Plugin version

2.0.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Not seeing this on my end. If you map a country-code enabled Phone field to a column in Google Maps (or any integration) you'll get the international-formatted phone number. i.e. `+61 3 63XX XXXX` (for an Australian landline).

What comes through in Google Sheets? Just want to confirm it's not just a formatting thing on their end?

**Comment by jubalj** [comment]
I'm sorry - my error  - had selected ":Number"!8

![image](https://user-images.githubusercontent.com/39228775/178929279-5a44d462-bac7-4cb4-81e5-bc86bb21bcec.png)
****
